### ISSUE TITLE
Update Bug

### ISSUE THREAD

**Issue by DannysList** [Kareadita/Kavita#1003]
I'm running the windows 64 bit build for this which is version 0.5.0.0. 

Bug:

When I select Check for Updates, the system notifies me there is a new update v0.5.0 which is the same build I already have. I can post screenshots if need be.

**Comment by majora2007** [comment]
Thanks, I'll take a look. Btw, how were you able to create this issue without the template? What steps did you use to open the issue? 

A few users have done so and the label is not being applied, hence I'm missing the issues when they come in.
