### ISSUE TITLE
Feature request: epub text highlighting 

### ISSUE THREAD

**Issue by tenleftfingers** [Kareadita/Kavita#1005]
I’ve just tried the demo and the UI is great. 

highlights are the core of my E-book use. It would be great if you could not only display highlights in existing epubs, but allow making more highlights as well as the ability to export them.

**Comment by majora2007** [comment]
This is not the correct place for feature requests. Please request on feats.kavitareader.com. Please include more information. Like how highlights work within the epub, what features you expect from highlights and what Kavita remembers, etc. 

More information means it's more likely to be considered.
