### ISSUE TITLE
Unable to add library

### ISSUE THREAD

**Issue by JJGO** [Kareadita/Kavita#1009]
**Describe the bug**

I'm unable to add a library using the path since the "Share" button is not activated

**To Reproduce**

- On fresh install, try to add a library typing the path
- The path is not recognized, no error is printed (neither in the UI nor docker) and share button is not activated, so library can't be added

I believe the main issue is that the folder for the bind mount is a FUSE mount on the host.
E.g. I create a FUSE mount under `/home/user/fs` in the host and then bind mount `/home/user/fs/media:/data` in Docker.
Then trying to add `/data/Manga` fails. However, when I execute `docker exec -it kavita_kavita_1 bash` to open a shell on the container I can navigate to `/data/Manga` and I can list the files and get their properties ( using `ls`) without any issue.

**Expected behavior**
 
I should be able to add the library

**Desktop (please complete the following information):**
- OS: Debian 10 (buster)
- Arch: amd64
- Installation: Docker (compose)
- Version:   0.5.0.0

**Comment by therobbiedavis** [comment]
@majora2007 This could be related to the library name being removed from the directory explorer's folder names? For instance if I create a library "Test" then try to navigate to "/data/Test Library" I see "/data/ Library" instead.

**Comment by majora2007** [comment]
Hmm I thought I had fixed that issue....

**Comment by JJGO** [comment]
Another datapoint in case it helps.

I tried the bind mount `/home/user/fs/media/Manga:/manga` and adding the library Manga with path `/manga`. With these settings the web UI lets me add the library but it finds no content despite the folder being populated with many files. Again, if I drop down into a shell with `docker exec -it` I can navigate to `/manga` and list of files correctly.

**Comment by therobbiedavis** [comment]
> Another datapoint in case it helps.
> 
> I tried the bind mount `/home/user/fs/media/Manga:/manga` and adding the library Manga with path `/manga`. With these settings the web UI lets me add the library but it finds no content despite the folder being populated with many files. Again, if I drop down into a shell with `docker exec -it` I can navigate to `/manga` and list all files correctly.

Can you delete the library, clear all your log files, Re-add the library (which will do a scan), wait for it to finish, then share the log file?

**Comment by majora2007** [comment]
> This could be related to the library name being removed from the directory explorer's folder names? For instance if I create a library "Test" then try to navigate to "/data/Test Library" I see "/data/ Library" instead.

I tested this and I did fix this in previous releases, so it's not this. 

@JJGO When you are using the directory picker, you're going back to / then looking for manga right?

**Comment by JJGO** [comment]
Ok, so with the bind mount `/home/user/fs/media:/data` I was able to add `/data/Manga` library. There were two major UI items confusing me:

- Directories are not sorted in alphabetical order which made it hard to go through them (specially at `/` where there are a lot of miscellaneous `/proc`, `/sys` and `/dev` entries)
- I did not realize that the filter was relative and thought I could input the absolute path there. I now understand that is a relative filter and not for inputting paths.

Navigating manually, I was able to confirm that 1) I can add the `/data/Manga` library and 2) that I can navigate within it from the directory picker and that folders are listed correctly

It seems to be working now, although I thought it was still broken for a solid 5-10 minutes since the library was empty and even triggering a rescan did not appear to do anything. Items in the library were abruptly added in bulk without thumbnails. Thus, this is likely another pure UI/UX issue where instead of listing the library as empty, it should indicate that a scan is in progress.

I confirmed this last behavior by creating a Comics library and the same happened,  no progress for over 10 minutes and then entries were added in a burst.

**Comment by majora2007** [comment]
Adding in bulk without thumbnails is standard. The thumbnail code is slow and expensive, eats up a lot of memory. So we split it off from the initial scan code so you can at least get stuff into your system and read while covers generate later. 

A scan in progress is noted in the top right. Currently it can loose state if you refresh your browser mid scan, as it needs the next event to know that it's in the middle of something. This is something I'm planning to tackle later. 

It's great that you were able to resolve this. I'll take note of the sorting work for a later release, when I plan to update that screen.
