### ISSUE TITLE
exception for 4 ebooks out of 33?

### ISSUE THREAD

**Issue by cocoonkid** [Kareadita/Kavita#1027]
`	[0]	[BookService] There was an exception when opening epub book: //manga/bookdir/somebook.epubSystem.AggregateException: One or more errors occurred. (Incorrect EPUB manifest: item with ID = "Images/9d2c66cc-7cb7-4f88-a20d-ae062dce1151.png" is missing.)`

All ebooks seem to be working in Thorium.

**Comment by majora2007** [comment]
I'm not sure what Thorium is, but this is an error saying that the metadata within is incorrect. I can't do anything about this. Your best bet is to import into Calibre and re-export which will fix that bad image definition in the metadata.

**Comment by cocoonkid** [comment]
@majora2007 Thank you.

Can't Kavita just ignore bad metadata?   At least it would be helpful if it could produce a a error cover image so the book can still be opened.

I tested that on 4 different epub readers now and they all have no issues. Only Kavita has.

Because for anyone who ahs more than 100 ebooks kavita becomes useless if I cannot be sure if it accepts my library or not TBH.

I recommend taking a second look at this issue as I consider it pretty structural.

Happy to help.

**Comment by majora2007** [comment]
I use an underlying library, docnet. The metadata you're talking about it how to read the archive file, not a missing author.  I have no control over how dotnet works. 

If you can code, please take a look at docnet and see if you can figure out how to solve the issue.

**Comment by cocoonkid** [comment]
@majora2007 Thanks for the swift reply.

Understood. It's just that I REALLY LOVE Kavita. It's very well done.  So this is driving me crazy.

I just moved 360 ebooks to kavita and it just shows me 69 of them :(

**Comment by majora2007** [comment]
Run them through calibre to fix those issues. Our discord has people that can help you do it quickly. Glad you like it. I've put a lot of time building it.

**Comment by cocoonkid** [comment]
@majora2007  I tried https://komga.org/ just now and it immediately picked up all books. no errors at all.  I will go with Komga for now and revisit calibre++discord+fix  next time I cleanup my library.

Thanks so much for taking the time.

**Comment by cocoonkid** [comment]
@majora2007  Maybe it would be helpful to add something like in this screenshot. That way at least users have a way to notice and manually intervene about non-compatible books.

![CleanShot 2022-02-19 at 16 06 27@2x](https://user-images.githubusercontent.com/43231640/154806571-0db6acb4-376f-4a86-9a69-e667adc8e81e.jpg)
