### ISSUE TITLE
[BUG] When Search is performed in Mobile browser Collection Name does not appear

### ISSUE THREAD

**Issue by mystic-man-rhino** [Kareadita/Kavita#1034]
**Describe the bug**
When I click on to search in mobile app browser (chrome) it displays appropriate data but for Collections it shows icon but not name of collection but it works as expected in desktop.

**To Reproduce**
1. Go to mobile app browser
2. Click on Kavita apps Search bar
3. It displays searched data if collections present collection with no name

**Expected behavior**
When Searched It should display COllection with it's name.

**Screenshots**
[Sample 1](https://cdn.discordapp.com/attachments/851515194185744464/939407150172753920/Screenshot_2022-02-05-11-56-50-758_com.android.chrome.jpg)
[Sample 2](https://cdn.discordapp.com/attachments/851515194185744464/939407150495723540/Screenshot_2022-02-05-11-56-41-701_com.android.chrome.jpg)

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 5 Pro]
 - OS: [Android 9]
 - Browser [Google Chrome]
 - Version [98.0.4758.87]

**Comment by majora2007** [comment]
What is the name of the collection?

**Comment by majora2007** [comment]
Validated, this only occurs on mobile chrome.

**Comment by majora2007** [comment]
Fix did not work, still present. This only effects mobile browsers.
