### ISSUE TITLE
rearrange order of homepage

### ISSUE THREAD

**Issue by gittynick** [Kareadita/Kavita#1063]
Hello,
I really like this new 0.5.1 update ! ;-)
The new [Recently Added] section on the homepage is particularly useful for me... is it possible to reorder sections on the homepage ? (so i can for example move it up 2nd position just under [On Deck])
It would be nice to have the option to reorder/hide these sections so to customise a bit the homepage
Best Regards
Nick

**Comment by majora2007** [comment]
This is not for feature requests. Use feats.kavitareader.com.
