### ISSUE TITLE
Setting a cover image by URL results in an error when saving, while the cover loaded to selected.

### ISSUE THREAD

**Issue by ocgineer** [Kareadita/Kavita#1064]
**Describe the bug**

Using and URL to set a cover image loads the images, but once selected and trying to save Kavita shows an error;

```
400
You must pass on a url to use
```

Tried using a few URL cover images, for example;

https://cdn.myanimelist.net/images/manga/2/245351.jpg

**To Reproduce**

1. Edit a series to Cover Image
2. Enter a valid image URL.
3. Selected the loaded image.
4. Try to save.

**Expected behavior**

Saving the selected image that loaded from the entered URL.

**Screenshots**

![image](https://user-images.githubusercontent.com/12483966/153696200-42760fab-f2aa-4f18-b37a-a8bb30a4795e.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - 0.5.1.0

**Additional context**

Adding cover image by file works properly.
This was not an issue in version 0.5.0.0 so this is a regression bug.

**Comment by majora2007** [comment]
This will be fixed by implementing #1082
