### ISSUE TITLE
Not ignoring Hidden and System folders when doing a library scan 

### ISSUE THREAD

**Issue by CDarwin7** [Kareadita/Kavita#1067]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
In version .48 this was indicated as fixed "Fixed: Ignore Hidden and System folders when doing a library scan"
However, my hidden folder is still being scanned and the contents are being parsed, resulting in comics in the library I didn't want. 

**To Reproduce**
1. Make a directory hidden by adding a . at the beginning of the directory's name. 
2. Do a new scan OR remove the library and create it again.
3. Once the scan is done, books within the hidden directory are still in the library.

**Expected behavior**
The scan should ignore Hidden and System folders when doing a library scan. Therefore, any books within the folder should not be in the library post-scan.

**Screenshots**
![Screenshot_20220212_133558](https://user-images.githubusercontent.com/57640874/153729259-95515d73-3898-4305-8c26-262a6d448999.png)
![Screenshot_20220212_133958](https://user-images.githubusercontent.com/57640874/153729329-fa535377-1fc3-4f6a-9f24-e9ac67f93aa8.png)

**Desktop (please complete the following information):**
 - OS: Docker:latest
 - Browser Chrome Version 98.0.4758.80 (Official Build) (64-bit)
 - Version 0.5.1.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majora2007** [comment]
What is the underlying OS that the disk is on and is it network storage? 

I have a hidden folder in my test system and it is not picking up anything in it.

**Comment by CDarwin7** [comment]
Hi - Thanks for responding. OS is OpenSUSE Tumbleweed running KDE. The library is on the 2nd of 2 512gb NVME SSDs installed. Linux is installed on an identical SSD.

![image](https://user-images.githubusercontent.com/57640874/153733744-e67a0015-e2ef-4bdc-ab02-0a01f2d74e25.png)


![image](https://user-images.githubusercontent.com/57640874/153733765-e9a7ae88-503c-445b-b76b-d786e9830490.png)
 


Operating System: openSUSE Tumbleweed 20220210
KDE Plasma Version: 5.24.0
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.16.5-1-default (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-9700 CPU @ 3.00GHz
Memory: 31.1 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 630

**Comment by CDarwin7** [comment]
looks like rebooting did it, I'm not seeing that folder anymore after I rebooted. I'll report any further oddities.
