### ISSUE TITLE
I have a General Question not really an Issue

### ISSUE THREAD

**Issue by darkmoon2** [Kareadita/Kavita#1102]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
My general question is about getting an error that my EPUB which is version 1.0, but there does not seem to be a place on here or the wiki explaining that EPUB version 1.0 is not allowed, and why it is not allowed.  Also on the wiki there was not a place for me to ask this general question will that be changing in the future or is this the correct place to ask even general questions such as mine.

I would also like to say I do like the product overall and I am wondering if a lot of the issues I am having with opening, and reading files is because of old files versus newer files.  I do not want to list specific instances or waste any more of your time if it is just because of file level on old file formats that are not supported.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker]  Ubuntu 20.04
 - Browser [e.g. chrome, safari] Chrome, Firefox, Brave, Several Android Readers
 - Version [e.g. 22] (can be found on Server Settings -> System tab)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Android 12 

**Additional context**

**Comment by majora2007** [comment]
So what is your issue? You didn't really say much except something about epub 1...can you elaborate more on what is happening for you? What logs say etc? Help me help you.

**Comment by darkmoon2** [comment]
Sorry yeah it was more an informational issue than an issue, is there a posting or faq about what versions of items are supported I have a large set of ebooks that all work fine in Ubooquity but when I load them in to Kavita I got tons of issues with files not showing up that work fine in both Ubooquity and Kavita, and when I started looking into them based on your page about how to interrogate the log I find repeated the following error message about several books so I guess I am trying to find out where the information about supported file levels resides so I don't have to bother anybody to determine what I need to cleanup in my own files in order to get them to work.

I have also been unsuccessful in opening any kind of PDF through Kavita as well which I guess is the only real issue I have experienced but I do not have good logging for that so I will try to get that together and submit separately.

The other main issue / not really an issue but again more general is I did not feel this was really the proper place to post my question about a generality missing from the wiki page.  However if this is the correct place I will work on my submissions.  I am sorry for being more long winded.  I tried to obtain this information from the sources I am aware of before creating this post.

**Comment by majora2007** [comment]
For ebooks, it's likely an issue of the metadata (not authors but more like how to read the file) is missing or corrupt. Other software might be able to read it, but the underlying library I chose can't. You can import then export through Calibre to fix those.

PDFs should open. Search the GitHub or FAQ on our wiki. Some systems require some additional steps, but they def work. If you have error logs submit an issue or jump into discord for hands on support.

Usually questions come into the discord, but this is the correct place. Your opening post was misleading as you mentioned question but the actual question wasn't defined. I hope this clears things up for you.

**Comment by darkmoon2** [comment]
Okay I will look for the discord link I must have missed that, so that I could ask more generic problem type items I am sorry for wasting your valuable time with this.  Thank you for taking the time to still respond.  I am enjoying the direction of your product and will try to contribute in ways that I am able too.  Thank you very much.

**Comment by majora2007** [comment]
You can find it on our main site: kavitareader.com

No problem, glad to hear you like it. I'll see you in the discord.
