### ISSUE TITLE
Name Parser strips out 'special' from words that contain this as part of their own word.

### ISSUE THREAD

**Issue by ocgineer** [Kareadita/Kavita#1104]
**Describe the bug**

The name parser (manga library) strips out the literal part 'special' of words that have this part of their own word.

For example;
```
Dr. Ramune - Mysterious Disease Specialist v01 (2020) (Digital) (danke-Empire).cbz
Dr. Ramune - Mysterious Disease Specialist v02 (2020) (Digital) (danke-Empire).cbz
```

Is parsed by Kavita with the series title of 
`Dr. Ramune - Mysterious Disease ist` 

**Expected behavior**

Only the exact match 'Special' with bounding whitespace should be parsed out if you want to consider a title 'special' without the use of comicinfo.xml. Any other word containing 'special' as part of its word, should not be parsed out. 

**Screenshots**

![image](https://user-images.githubusercontent.com/12483966/155059111-a49bf1c1-ce52-4fb0-99cf-282add993d00.png)

**Desktop (please complete the following information):**
 - OS: Unraid Docker 
 - Browser Chrome
 - Version v0.5.1.0

**Comment by majora2007** [comment]
This is something I can't solve unfortunately, the only solution is to embed the ComicInfo.xml, which will not do special stripping or rename the series in the UI, which will then stick and still match correctly.
