### ISSUE TITLE
Assigning metadata to EPUB 3.3

### ISSUE THREAD

**Issue by zeedif** [Kareadita/Kavita#1108]
I've been using Kavita since my last request and i've noticed some possible upgrades on metadata assignement to EPUB 3.3:

- Kavita can only collect **Writers/Authors** values on EPUBs and it does it finding coincidences from ` <dc:creator> ` tag. However, specifying authors, illustrators, translators, modelers and other contributors can be done by using the [MARC Relators](https://www.w3.org/TR/epub-33/#sec-opf-dccreator) property on the meta tags which applies to ` <dc:creator> ` and ` <dc:contributor> ` tags. Valid values indicated by the **MARC Relators** can be found [here](https://www.loc.gov/marc/relators/relacode.html).

Into my EPUBs I use:
` <dc:aut> `, ` <dc:ill> `, ` <dc:tra> `, ` <dc:mrk> `, ` <dc:dst> `:
```html
    <dc:creator id="creator01">Autor Apellido</dc:creator>
    <meta property="role" refines="#creator01" scheme="marc:relators">aut</meta>
    <meta property="alternate-script" refines="#creator01" xml:lang="ja">アネコ ユサギ</meta>
    <meta property="file-as" refines="#creator01">Apellido, Autor</meta>
    <dc:creator id="creator02">Ilustrador Apellido</dc:creator>
    <meta property="role" refines="#creator02" scheme="marc:relators">ill</meta>
    <meta property="alternate-script" refines="#creator02" xml:lang="ja">村上 春樹</meta>
    <meta property="file-as" refines="#creator02">Apellido, Ilustrador</meta>
    <dc:contributor id="contrib1">Traductor</dc:contributor>
    <meta property="role" refines="#contrib1" scheme="marc:relators">trl</meta>
    <dc:contributor id="contrib2">Maquetador</dc:contributor>
    <meta property="role" refines="#contrib2" scheme="marc:relators">mrk</meta>
    <dc:contributor id="contrib3">ZeePubs</dc:contributor>
    <meta property="role" refines="#contrib3" scheme="marc:relators">dst</meta>
```

- You could also add support for identifiers such as ` isbn-10 `, ` isbn-13 `, ` amazon (ASIN) `, ` url (URI) `:
```html
    <dc:identifier id="isbn13">urn:isbn:000-00-0000-000-0</dc:identifier>
    <meta property="identifier-type" refines="#isbn13" scheme="onix:codelist5">15</meta>
    <dc:identifier id="isbn10">urn:isbn:00-0000-000-0</dc:identifier>
    <meta property="identifier-type" refines="#isbn10" scheme="onix:codelist5">02</meta>
    <dc:identifier id="amazon-id">urn:amazon:BXXXXXXXXX</dc:identifier>
    <meta property="identifier-type" refines="#amazon-id" scheme="xsd:string">amazon</meta>
    <dc:identifier id="uri-id">urn:uri:http://publisher-group.com/novel</dc:identifier>
```

- Another thing I found is the ` <dc:date> ` is not recognized despite being documented into [W3](https://www.w3.org/TR/epub-33/#sec-opf-dcdate).

- Also, ` dc:language ` values (Spanish, French and so) should be included. Info can be found [here](https://www.w3.org/TR/epub-33/#sec-opf-dclanguage) and [here](https://www.rfc-editor.org/rfc/rfc5646).

- Finally, if a ` calibre:rating ` value is used, it should be used as the initial novel/volume rating.
```html
    <meta content="9" name="calibre:rating" />
```

Another problem i found is when having 2+ EPUBs that belongs a same novel and  with the same volume number/identifier (but from different publishers), Kavita ignores the second coincidence and only shows the first one when analizing the library. [4 EPUBs that meet this condition](https://1drv.ms/f/s!AtXUisPt_TL8i-9Z-2TAD2r1kWDkNA). This does not happen if the volume number/identifier doesn't match with their serial numbers.

It'd be amazing if support could be given to this issue, so Kavita could filter EPUBs from one publisher.

Also, I had an idea. It'd be nice if OneDrive/Google Drive accounts could be linked into Kavita for sincying documents and stuff.

**Comment by majora2007** [comment]
I know it's been a long time since I asked you to create this ticket. Let me jump in on a few items:

> Finally, if a calibre:rating value is used, it should be used as the initial novel/volume rating.
I don't support reading rating from the file because ratings are bound to users. The scan doesn't know who the user is on the system.

> Also, dc:language values (Spanish, French and so) should be included. Info can be found [here](https://www.w3.org/TR/epub-33/#sec-opf-dclanguage) and [here](https://www.rfc-editor.org/rfc/rfc5646).
Language seems to be supported already by the parser. 

> Another thing I found is the <dc:date> is not recognized despite being documented into [W3](https://www.w3.org/TR/epub-33/#sec-opf-dcdate).

This looks to be valid. When using `<dc:date>` directly without any event type, then yes, Kavita wouldn't recognize. I have fixed that to check for publication date first and fallback to a normal date tag if publication date tag is not present.

> [MARC Relators](https://www.w3.org/TR/epub-33/#sec-opf-dccreator)
This is something I can't personally implement as I don't have the scope necessary from the library I'm using. I Would highly recommend asking for Epub 3 support on MARC Relators to that library. If they implement it, then I can support it with the appropriate people fields we support.

[https://github.com/vers-one/EpubReader](https://github.com/vers-one/EpubReader)

> You could also add support for identifiers such as isbn-10, isbn-13, amazon (ASIN), url (URI):

I don't see any need at the moment to support ISBN or other type of tags like that.

> Also, I had an idea. It'd be nice if OneDrive/Google Drive accounts could be linked into Kavita for sincying documents and stuff.

You can already do this via rclone mounts or network drives.

**Comment by luistoledo** [comment]
> I don't see any need at the moment to support ISBN or other type of tags like that.

Im curious, Where in the roadmap it is the ISBN support? 

Going further: It sounds like a great help for users to automatically fill up book details & metadata. Do u plan to add something similar?

I barely understand that id lookup can be a pain trying to cover several sources (like zotero does), but openlibrary has a decent DB to begin with, afaik.

**Comment by majora2007** [comment]
There isn't any. I haven't gotten anywhere close to external metadata for books, so I don't know much about it yet.

**Comment by GlassedSilver** [comment]
If it's now a to do in backlog, isn't the wontfix tag inaccurate now?

**Comment by majora2007** [comment]
@zeedif  I know it's been a long time but I finally got around to the first bullet point of your ask (on latest nightly). I'll see if I can tackle a few more of them in v0.7.3

**Comment by majora2007** [comment]
Here is an update for you, as of the latest code I'm about to push:

- ISBN support is implemented,
- Dates are recognized
- Languages work properly (ie both en and en-US will recognize)
- MARC Relators are supported

> calibre:rating is not supported.
Upvote the existing feature request. 
>  It'd be nice if OneDrive/Google Drive accounts could be linked into Kavita for sincying documents and stuff. 
This is already supported via Rsync and other tools.
