### ISSUE TITLE
Event hub grouping

### ISSUE THREAD

**Issue by therobbiedavis** [Kareadita/Kavita#1110]
**Describe the bug**
Multiple entries in the event hub for the same thing

**To Reproduce**
1. Have a large comic/manga library on an rclone mount
2. Scan that library
3. Wait...

**Expected behavior**
No duplicate entries.

**Screenshots**
![image](https://user-images.githubusercontent.com/7907265/155362205-eae6b93f-dbc1-4b14-801d-8837b17891c7.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: All
 - Version: 0.5.1.14

**Smartphone (please complete the following information):**
 - Device: ALL
 - OS: ALL
 - Browser: ALL
 - Version: ALL

**Comment by majora2007** [comment]
Have you seen this occur since this reporting? I can't seem to reproduce it.

**Comment by therobbiedavis** [comment]
Yes. I see it every time I scan. Seems to be possibly related to the event emitting on start of chunks as it seems to happen consistently but not constantly (like spamming the human  so there are hundreds of the messages).
