### ISSUE TITLE
Book Reader Redesign

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#1124]
In order to satisfy book readers on e-ink devices, the current book reader needs to be updated in terms of design and functionality to meet the needs of our users.

This story is not fully baked out, but contains a list of items that I want to explore:
- [x] New Design
- ~~Custom Book Themes: These will be managed by admins just like normal themes~~ This is not doable without lots of internal details on book reader html. Pulling this feature
- [x] Expand color themes: White, Dark, Black, Sepia
- ~~Custom Fonts~~ This is being pulled to another release
- [x] Layout mode (like Calibre)
- [x] Attempt to solve issues when adjusting margins, progress point gets shifted due to scrolling/page layout shifts
- ~~[ ] Table of Contents redesign~~ Pulled for now, too much css. Let's get feedback before we update it. 
- ~~[ ] UI should use Page 1, not Page 0~~ This isn't worth the headache. Can revist later. 
- [x] Add in OpenDyslexia font to the reader
- [x] Prefetch prev/next chapter like manga reader does
- ~~Ability to hide the action bar~~

Smaller Items for me to do:
- [x] Refactor ResetSettings to first reset form then rebuild page styles
- [x] Provide more hooks into theming accordions
- [x] Allow reader controls to be customized via site theme
- [x] Figure out how to propagate reading direction from new settings component to reader in a clean way
- [x] Fix drawer toggle state not propagating
- [x] Side nav select is not styled correctly
- ~~[ ] Rework how we show bottom bar to move into a user setting since it can be nice for small eink readers~~ Column layout will be common for eink readers and in column mode, it always shows on bottom. Let's collect feedback and revisit. 
- [x] Implement User Preference saving
- [x] Finalize with Migration before merge

Bugs:
- [x] Column layout when paging back to previous page will put you at the start of said page. 
- [x] 1 Column layout still has some image cutoff if switched to from 2 column
- [x] Switching from 2 col -> 1 col on mobile doesn't work. Mobile is only doing default or 2
- [x] 1 Column layout moving to 2nd split image page then hitting prev page, goes back a full page
- [x] Page restoration doesn't work with column layout
- [x] Ability to restore progress doesn't work on column layout (scroll to position)
- [x] Need to hook into window resize for column layout

**Comment by MidnightSnowleopard** [comment]
Would the view not shifting back to the top of the page when switching pages on a manga on a view size where it stretches larger than the usual viewport be part of the rework or is that a bug?

**Comment by majora2007** [comment]
@MidnightSnowleopard I would suggest visiting discord for support or creating an issue with more information. This is strictly a feature story.

**Comment by majora2007** [comment]
@dathbe Yes, it is. If you want to beta test, please join the discord and pay attention to the dev-testing channel, which is where testing occurs for these releases. 

It's not complete, it's complete in my branch, that doesn't mean this whole story is ready to release to nightly users. You can subscribe to this issue and it will be linked to the nightly release (which has a docker image) when it's ready to be tested.
