### ISSUE TITLE
More than 2 decimals in chapter number mess up chapter number

### ISSUE THREAD

**Issue by ThePromidius** [Kareadita/Kavita#1160]
**Describe the bug**
File path:
`Library\GATE - Jieitai Kanochi nite, Kaku Tatakaeri\GATE - Jieitai Kanochi nite, Kaku Tatakaeri Vol.11 Ch.062.55.cbz`

ComicInfo.xml (cut):
```xml
<?xml version="1.0" ?>
<ComicInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <Series>Gate: Jieitai Kanochi nite, Kaku Tatakaeri</Series>
   <AlternateSeries>Gate</AlternateSeries>
   <Number>062.55</Number>
```
(Volume number is parsed from filename)

**To Reproduce**
Setup a file with the above configuration. Chapter number with 2 decimals

**Current behavior**
Chapter number = 6255
(see screenshot)

**Expected behavior**
Chapter number = 62.55

**Screenshots**
![image](https://user-images.githubusercontent.com/34222883/158717674-8054506b-bea9-444f-9d2e-ce89919e4ae0.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: chrome
 - Version: #1155 Commit: #b1c4b286 (build from source. that's latest commit on develop)

**Additional context**

**Comment by majora2007** [comment]
I tried to reproduce this myself and was unable. Is this still an issue for you?

**Comment by ThePromidius** [comment]
I haven't found this issue recently. So i guess the answer is no.
