### ISSUE TITLE
Support (Or improved support) for complex Epub formatting.

### ISSUE THREAD

**Issue by Bitwolfies** [Kareadita/Kavita#1167]
**Describe the bug**
More complex Epubs fail to load in Kavita, even if they did load, I cannot confirm if all the features would work right.

**To Reproduce**
1. Get an EPUB with complex formatting/metadata, something with heavy use of specific fonts and formatting, something like this.  (I used Halo: The Flood)
![image](https://user-images.githubusercontent.com/65789901/159369296-e7897053-ee39-4552-9970-248d744dadd8.png)

2. Add it to Kavita, youll probably receive this error on load: 
![image](https://user-images.githubusercontent.com/65789901/159369371-fff17a40-494f-4f4a-8020-1c5d449ebd53.png)

**Expected behavior**

Well, it to load for one, and two, for the books requested formatting and fonts to load correctly

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox
 - Version 0.5.1.1

**Additional context**
Here's an example of a reader that ignores that special formatting, unknown how Kavita treats these books yet, hopefully not like this ;)
![image](https://user-images.githubusercontent.com/65789901/159369629-d33ab61f-9f3d-4d46-9a85-89a1ef8805f5.png)

**Comment by majora2007** [comment]
I took a look into this and the issue was kobo was included and the way the epub referenced the file was not standard. Kavita will now ignore invalid paths like this (after attempting to correct the key).
