### ISSUE TITLE
Cavita doesn't detect the correct Cover Art

### ISSUE THREAD

**Issue by Alpha272** [Kareadita/Kavita#1173]
I have a book here, for which Kavita is unable to detect the correct cover art.
![image](https://user-images.githubusercontent.com/22331613/159561568-2f7c2eed-d2c0-493e-bf1b-e5c94ae0bce7.png)

Taking a look into the book, the cover art is correctly marked as the cover.
![image](https://user-images.githubusercontent.com/22331613/159561788-4da78260-e43d-44af-ba91-3e0acc13e5bc.png)

Apparently it takes the first Image by alphabetical order as the cover art.
![image](https://user-images.githubusercontent.com/22331613/159561841-ff9fa900-cc90-413a-bfea-20fd6c86499e.png)

In the cover.xhtml (which is correctly the first xhtml in the book) and in the package.opf, the cover art is also correctly classified as the cover.
![image](https://user-images.githubusercontent.com/22331613/159562286-e26057a5-c317-4ca5-ada8-c3d57439eadf.png)
![image](https://user-images.githubusercontent.com/22331613/159563155-5f8a1199-4af9-4c0a-8474-3539510c317f.png)

So yeah, it seems like Kavita just blindly takes the first image in the list and ignores if its really the cover art or not. And this behavior just breaks on this book.

Or Kavita tried to take the correct Cover Art and just fails for some reason, and taking the first image in the list is a fallback.

Anyway, thats probably not intended.

I can send you the book if you need it for further debugging.

Also, I use the Current Docker Release of Kavita (v.0.5.1.1) on a Synology NAS, if this is at all relevant for this issue.

**Comment by majora2007** [comment]
Hi, Kavita does not" just choose" the first image in the epub. It uses the embedded metadata and if no such image is set in the metadata, it falls back and attempts to find a cover image. It is likely that your epub is not properly tagged. I will take a look at one of mine and give you the syntax (or use Calibre to re-export, in which it will write the correct tag)

**Comment by Alpha272** [comment]
Actually, the book is already exported from Calibre. Its a Adobe Digital Editions book and I used Calibre to strip the DRM from it.

Metadata SHOULD also be set (if calibre didn't messed up)
![image](https://user-images.githubusercontent.com/22331613/159567763-1c242351-8dcd-4924-b1e4-5cd6b5ba3f22.png)

**Comment by therobbiedavis** [comment]
When Kavita "falls back" to try and find the cover image it looks through for an image that has `cover` in the filename. So worst case is you could just rename the cover image and re-export.

**Comment by majora2007** [comment]
You need to have this in your opf file:
<meta name="cover" content="x_cover-image" />

Where the content string should map to an id of an image, like:
<item id="x_cover-image" media-type="image/jpeg" href="Images/cover00147.jpeg" />

If this is missing, Kavita falls back and tries to find a cover image by filename and if that fails, it just takes the first image it can find defined. 

So your issue is that your metadata is not correct, you are likely missing the tag or you have some alternative implementation that we don't support.
