### ISSUE TITLE
Error 400 when saving admin settings

### ISSUE THREAD

**Issue by crxssed7** [Kareadita/Kavita#1174]
**Describe the bug**
Shows a red 400 error message, stating that the directory doesn't exist or isn't accessible.

**To Reproduce**
1. Go to admin settings
2. Enable OPDS (or any other setting)
3. Click save

**Expected behavior**
Settings should be saved

**Screenshots**
![image](https://user-images.githubusercontent.com/48864420/159899778-d510fd0f-ff30-4bf3-9262-fc07b2fc123f.png)

**Desktop (please complete the following information):**
 - OS: Raspbian
 - Version 0.5.1.1

**Additional context**
Error occurs when trying to save any setting

**Comment by crxssed7** [comment]
I've got it to work by manually creating the `cache` directory, however I'm not sure what caused the issue.

**Comment by majora2007** [comment]
Did you delete the cache directory by any chance?

**Comment by crxssed7** [comment]
Nope - I'm not sure if it was ever created in the first place however all the other directories and files were there.

**Comment by majora2007** [comment]
Okay, well I altered the code for this situation. It just means you edited the admin settings before reading anything. It's old code from when I was going to allow changing of cache directory. It will be fixed in v0.5.2.
