### ISSUE TITLE
Wrong cover for normal chapter when a special chapter is present

### ISSUE THREAD

**Issue by RealStickman** [Kareadita/Kavita#1176]
Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
This is an issue with the manga chapters view.  
Normal chapters will use the special chapter's first page instead of their own first page as cover.  
Eg. "Chapter 51" will use the cover of "Chapter 51.5 Extra SP04".  

Wrong cover:  
![grafik](https://user-images.githubusercontent.com/61015582/160174593-8196c11a-f1d0-482b-ab73-52e857b43d81.png)

Correct cover:  
![grafik](https://user-images.githubusercontent.com/61015582/160174660-8b4b53bf-f3c2-4979-b2ba-7fba7d8de4e4.png)

The second image is from Kavita stable 0.5.1.1, so something between then and the current nightly build (0.5.1.34) broke this.  

**To Reproduce**
1. Have normal and special chapter with same chapter number
2. Compare cover shown to actual first page in normal chapter

**Expected behavior**
The normal chapter should show the correct cover.  

**Desktop (please complete the following information):**
 - OS: Kavita container 0.5.1.34
 - Browser: Firefox

**Smartphone (please complete the following information):**
 - Device: OnePlus 3
 - OS: LineageOS 18.1 (Android 11)
 - Browser: Firefox mobile

**Additional context**
Partial folder tree to show the file layout I have on disk.  
![grafik](https://user-images.githubusercontent.com/61015582/160175206-fec5333c-20dd-4992-bc2f-7f0c076ec0ee.png)

**Comment by majora2007** [comment]
I can't reproduce this.
Vol. 10 Chapter 51.cbr
Specials/Vol. 10 Chapter 51.5 Extra SP10.cbr

![image](https://user-images.githubusercontent.com/735851/161570473-1e2b167a-01f6-492d-8ed9-c1a374e0883e.png)
![image](https://user-images.githubusercontent.com/735851/161570569-ff89bb92-c1fd-4ba1-838d-49b50297c151.png)

**Comment by RealStickman** [comment]
I ran a "refresh covers" operation and it's working fine now. No idea why it broke originally.
