### ISSUE TITLE
Scan is aborted if one of the root folders is empty

### ISSUE THREAD

**Issue by 24KaratCarrot** [Kareadita/Kavita#1178]
Currently running the latest Kavita Docker Image. I have my root folders spread across many drives, and my current setup can result in me having several root folders empty across multiple libraries. Right now, if I try to run a scan on a library that has an empty root folder, but another root folder that has content, then I get this error:

`
crit: API.Services.Tasks.ScanService[0]
    Some of the root folders for the library are empty. Either your mount has been disconnected or you are trying to delete all series in the library. Scan will be aborted. Check that your mount is connected or change the library's root folder and rescan
`
This is an inconvenience, because I like to set up the root folders for specific libraries ahead of time, and add content to them as I get it.

This also results in more weird behavior, as if I remove all the content out of a root folder, then run a scan, Kavita still shows that the content is there, as the scan is never run to pick up the changes.

**Comment by majora2007** [comment]
We have this condition as some users have drices that are disconnected at points in time and if the scan was not aborted, then they would loose all their data.

The idea is if you see this, then you can remove the folder from the library and rescan. In the upcoming version, this error will be pushed to the UI so you shouldn't need to dig into the logs.
