### ISSUE TITLE
Linked Series

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#1182]
Implement the ability to link a series to another via a pre-defined type (Sequel, Prequel, Side Story, etc). The UI will then provide some sort of link for users to click on.

A story can have multiple types linked. If we have multiple Prequel and Sequel, the idea of a reading list is out the window.

Types:
- Side story
- Prequel
- Adaptation (this can be used between Manga and LN)
- Sequel
- Parent Story (from an Adaptation back to original? Or perhaps it automatically generates)
- Spin-off
- Other (catch all?)
- Alternative Version
- Alternative Setting?
- Contains? (For One-Shots)

I'm not sure if we can generate a reading list from this, but look into it.

https://feats.kavitareader.com/posts/41/interlinking-of-series-books

**Comment by majora2007** [comment]
Per MAL, this is how links work:
sequel 		  Direct continuation of the story.
prequel 		  Story that occurred before the original.
alternative setting 		  Same universe/world/reality/timeline, completely different characters.
alternative version 		  Same setting, same characters, story is told differently.
side story 		  Takes place sometime during the parent storyline.
summary 		  Summarizes full story, may contain additional information.
full story 		  Full version of the summarized story.
parent story 		  Parent of all the shows (ex: Naruto TV is the 'parent story' of all its movies).
spin-off 		  Uses characters of a different series, but is not an alternate setting or story.
adaptation 		  Manga/Anime adaptation. This field is already vice versa enabled.
character 		  When characters appear in both series, but is not a spin-off
other 		  When nothing else fits

**Comment by majora2007** [comment]
Some good sources for interesting cases:
https://anilist.co/manga/65003/Yamadakun-to-7nin-no-Majo/
Bleach

**Comment by GlassedSilver** [comment]
I may add my thoughts to this too late, but I got linked here a while ago by you and whilst this may be closed I think it still serves as good context.

I can still branch this out into another separate issue if needed, but [I just wrote this down in Kavita's Discord in a thread](https://discord.com/channels/821879810934439936/975544112046555136/975637085014880307) and noticed it perfectly applies here.

Furthermore, I doubt I'll ever do a similarly cohesive write-up of my general idea again, so better to take this opportunity to copy and paste into here.

If anything is unclear still I'll be happy to explain further!

> Manga Library <-> Doujinshi LIbrary
> 
> Franchise (e.g. first Manga)
> example. Himouto! Umaru-Chan
> 
> Then you have the series level:
> Himouto! Umaru-Chan
> Himouto Umaru-chan S
> Himouto Umaru-chan G
> (so this is where you have your main plot, the spin-offs, etc... anything official belonging to the series
> 
> 
> Now the doujinshi library:
> 
> Each doujinshi has either a Franchise or a series link field (or both)
> 
> It must be identical to how the franchise is named in the manga library obviously.
> 
> In the background when a user clicks on a UI button in the manga lib for "show related doujinshi" you get the douninshi library opened up, filtered to the context of what you had before. So if you wanted to see all of the franchises' doujinshi you get that
> and the series level doujjinshi below it of course
> it's inclusive
> or rather recursive
> ideally changing a series name will also adapt the linked metadata in the doujinshi library through a look up and replace
> (i.e. you stored Himouto Umaru-chan and now you hate not having the stylized version with the exclamation mark included)

And further:

> also doujinshi have certain particular metadata that are different from official releases
> (also a doujinshi can be original and not tied to a series... but you know that)
> e.g. a Redrawer you will not see in official releases
> or a "circle"

**Comment by majora2007** [comment]
Tha ks for the input. This story is closed because it's already implemented. In the upcoming release, I encourage you to try it out and come back in the discord and suggest improvement's to it. 

I've been using it and the system as is, is really nice. I don't have doujinshi personally, so there may be some enhancements we can make in another release.
