### ISSUE TITLE
Cannot create any new users 

### ISSUE THREAD

**Issue by Chocolate-Banana** [Kareadita/Kavita#1185]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
When I go to create a new user, I am stuck on a perpetual loading screen and it doesn't create a user with or without the correct email SMTP address. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Invite users
2. Enter email of user and select libraries
3. Stays on 'Checking accessibility of server' and doesn't create a user.

**Expected behaviour**
Prompt me with a link to send to the person to setup account. 

**Screenshots**
![image](https://user-images.githubusercontent.com/43570997/161157455-99043040-6327-406b-b29a-0f05ce6b24cf.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Chrome
 - Version 0.5.1.1

**Additional context**
I managed to create one user but since then I haven't been able to make another. 

I have the url set to localhost just to try and force it to work. 
![image](https://user-images.githubusercontent.com/43570997/161157683-cad2f2e9-6a11-4654-a827-7205b50ea134.png)

Is there not a setting to just allow me to create a new user without the email? 

Thanks

**Comment by majora2007** [comment]
This is a bug that is in the current version. It has been fixed and validate. We are doing release testing for the upcoming release, so please be patient with us. Should be here within a weeks time. 

There is no current way to create an user without an email at this time.

**Comment by Chocolate-Banana** [comment]
Thanks for responding, I'll keep an eye out for it.
