### ISSUE TITLE
Sort Name broken

### ISSUE THREAD

**Issue by earth4s** [Kareadita/Kavita#1190]
After updating to 5.2 "Sort by" "Sort Name" goes by when the Book/Manga/Comic is added. When i fill out the "Sort Name" field of a series it start acting appropriately. If the "Sort Name" filed is left blank as by default the library items revert to listing by when the series was added. If the "Sort Name" is left unprotected when the library is scanned this field is made blank again and the collection revert back to using the time the series was added.

I did deleted and recreated one of my libraries to confirm this. Before being deleted it would alphabetize if I set the collection to "last modified". The only catch was that the series added after the update would be appended to the end.

**Comment by majora2007** [comment]
I'm sorry, I'm not understanding what you are saying. Can you break it down by:

Steps to reproduce:
1. Scan library
2. Do this on UI
...

Expected:

Actual:


There is a template, but you somehow bypassed it. Try next time to use the [template ](https://github.com/Kareadita/Kavita/issues/new?assignees=&labels=needs-triage&template=bug_report.md&title=) so the bug report can be more helpful on first look.

**Comment by majora2007** [comment]
I think I figured out what you are saying, there is a regression where Sort Name is blank after updating or fresh install, and hence sorting is broken within the app.

**Comment by earth4s** [comment]
Not sure how I bypasses the template, i just hit the big green button for "New Issue". Anyway for future clarification.

**Describe the bug**
After updating to 5.2 my library's rearranged them selves in non-alphabetical order. Manually setting the"Sort by" filter to "Sort Name" and clicking apply did not affect the ordering.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to a library that was created before 5.2
2. Library will be non-alphabetical
3. Go to "Open Filtering and sorting" icon
4. Set "Sort by" to "Sort Name" and "Apply"
5. Library will not change.
6. Set "Sort by" to "Last Modified" and "Apply"
7. Library will sort in Alphabetical order
      - The exemption being that items added after 5.2 will be after the pre 5.2 items.
**Expected behavior**
Library items should sort in alphabetical order.

**Desktop (please complete the following information):**
 - OS: Fedora Linux 35
 - Browser Chrome
 - Version 5.2.0

**Additional context**
1. By adding a "Sort Name" in the Meta data in Kavita the alphabetical sorting fiction starts working again. But this gets annoying with 100s of items.

Let me know if you need anymore details.

**Comment by majora2007** [comment]
Thanks, interesting that you were able to bypass when yeah, there is only one template and it always forces it. 

I have fixed the one issue where Sort Name is getting cleared during a scan. I need to validate that Sort field works on filtering, this missed release testing. I'm planning to do a hotfix for this, but likely in a few days (it takes a while to run through the different test criterias)
