### ISSUE TITLE
Manga Library parser does not interpretes series names with numbers and letters correctly.

### ISSUE THREAD

**Issue by earth4s** [Kareadita/Kavita#1193]
**Describe the bug**
It looks like parser for Manga gets confused when their is a mix of letters and numbers in the title. It will separate out items in the "Specials" folder separate from the parent series when listing them in the library.

**To Reproduce**
1. Create a new Manga series folder called "Foo 50"
2. Add several files and title them appropriately "Foo 50 v1.cbr, Foo 50 v2.cbr, etc...."
3. Create a "Specials" folder inside the "Foo 50" folder
4. Add several files and title them appropriately "Foo 50 SP1.cbr, Foo 50 SP2.cbr, etc...."
5. Scan the library with "Foo 50" folder
6. Library with create to different series. One called "Foo 50" with the main series and "Foo" with just the specials.

**Expected behavior**
The library should be creating one "Foo 50" with the specials listed under it

**Screenshots**
![Screenshot from 2022-04-03 16-54-14](https://user-images.githubusercontent.com/9957002/161450337-7d448f3a-1a59-4d1b-8128-819ac138a206.png)
![Screenshot from 2022-04-03 17-04-19](https://user-images.githubusercontent.com/9957002/161450687-43d3622f-7432-4da4-9738-92bb18be70d7.png)
![Screenshot from 2022-04-03 17-04-46](https://user-images.githubusercontent.com/9957002/161450688-468534ec-9c12-4698-985e-ddd67708fc66.png)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 35
 - Browser Chrome 100
 - Version 5.2

**Additional context**
I have attached a dummy series I used to test this with. Each CBR contains a single image. Most images used are Car logos or Video game related.

[Foo 50.zip](https://github.com/Kareadita/Kavita/files/8405568/Foo.50.zip)

**Comment by majora2007** [comment]
Update for myself, this is not a parser issue, but rather a Scan loop issue. During Falling back to folder, the logic is parsing a series from "Foo 50" and assumes the 50 is a chapter and thus returns Foo. However, it might be advantageous to validate that if the folder name is already what was parsed from the file, we break early.

**Comment by earth4s** [comment]
I was looking at the Comicinfo route as a possible workaround but haven't gotten around to creating one for testing.

Maybe force users to use a standard format that specifies the type with v - volume, ch - chapter, etc? Or maybe have some type of delimiter between the title and the volume/chapter information like a dash "-"? Then again i'm a scripter not a programmer so anything i could make would be hacky and not fit for general use.

**Comment by majora2007** [comment]
You can't force people to use a format because then no one will use the program. We have a ton of parsing code to detect different naming conventions, it's just when a series ends with a number that errors can occur and for that, ComicInfo provides the best workaround. I've already fixed this issue in your case, by enhancing some of the fallback code. 

But yeah, best case would be to use ComicInfo, else for your special, you could also just have SP01 or some title of the special, doesn't need the series name if it's under Series/Specials/.
