### ISSUE TITLE
Renaming a series with a title that already exists results in error after scan

### ISSUE THREAD

**Issue by dreaganluna** [Kareadita/Kavita#1198]
**Kavita v0.5.2.0 - Windows 10**

Imagine I have 2 series of comics, one named "Batman" and another incorrectly named "Batman (2020-)" (caused by incorrect name in the xml file).

I have the option to rename a series, so I remove " (2020-)" from the name and localized name of that second series and click save.
At this point, all issues of that seond series are gone, I can't find them anymore. The counter on the homepage's recently updated series does include the additional comics that I wanted to move over to the first series, but when I open that first series (Batman), the issues are not listed.

Afterwards, when I perform a new library scan, I get this error:
"There was an issue writing to the DB. Chunk {ChunkNumber} did not save to DB. The following series had constraint issues: ..." and then it list a large number of series, including "Batman" and "Batman (2020-)".

If I then remove the files from series "Batman" from disk and then perform a new scan, the error no longer appears.
I can also safely re-add the files and scan again to end up in my initial situation.

**Comment by majora2007** [comment]
This is indeed a bug. You should not be able "merge" series at this point in the app yet. I'll make sure the check works and throws an error.
