### ISSUE TITLE
KOReader is unable to parse OPDS catalog

### ISSUE THREAD

**Issue by andycarlberg** [Kareadita/Kavita#1199]
**Describe the bug**
I'm using KOReader (specifically on a Kindle Touch). It is able to connect and view the root of the OPDS catalog on Kavita but is unable to browse further. I receive one of three messages

1. "Failed to parse catalog"
2. "Server refuses to serve uncompressed content"
3. 500 Server error

I understand if KOReader is simply not supported. I wanted to share the issue in case an uncompressed response or if a more flexible response for OPDS could be sent from Kavita. In other words, if a server side fix is possible. KOReader explicitly supports Calibre's OPDS catalog but I would much *much* rather use Kavita.

**To Reproduce**
1. On a device running KOReader, go to the OPDS catalog
2. Enter the catalog URL for your user
3. Save
5. Browse the OPDS catalog
6. See one of the three errors listed above

**Expected behavior**
KOReader displays appropriate listings of books.

**Screenshots**
Unable to easily provide (and probably not useful)

**Comment by majora2007** [comment]
KOReader has not been tested, but as long as it supports OPDS standard, it should work. 

To validate, you're using the OPDS url, which is something like: demo.kavitareader.com/api/opds/3234sdr-34w34sa-3433ad

https://wiki.kavitareader.com/en/guides/settings/opds

**Comment by majora2007** [comment]
I would also say, if it doesn't work, you might want to open an issue on KOReader which is also open source and link it on this issue (or vice versa). I can def work with KOReader devs to help get things working correctly.

**Comment by andycarlberg** [comment]
Yep, I'm using the correct URL and it's working perfectly in Moon+ Reader in my Android tablet.

I'll open an issue with KOReader and hopefully start a dialog. 

Unfortunately, I don't think I have the time right now to sufficiently understand both codebases to try to make a PR to the appropriate place. If I manage to find some spare time, I'll see if I can find any leads though.

**Comment by majora2007** [comment]
Yeah, I don't need or expect you to jump into my codebase. Setting up and linking the issues together is enough, I can follow up once the issue is created. Appreciate you reporting it to my attention, hopefully it's a straightforward thing.

**Comment by andycarlberg** [comment]
In trying to reproduce the issue a second time for the KOReader team, everything worked as expected. I did regenerate the API key since I had posted the first key publicly in the log file. With the new key, it worked as expected. That seems like an unlikely cause but I can't think of any other changes I made between this morning and this evening.

I'll consider this issue closed and report back if it comes up again. Thanks for the awesome response and all the fantastic work on Kavita. I love it!

**Comment by Silther** [comment]
> I'll open an issue with KOReader and hopefully start a dialog

Any news from KOReader?

**Comment by Silther** [comment]
After creating a new Account it works now, pretty sure it's not KOReader who has the error

**Comment by majora2007** [comment]
I'm not sure who's at fault here, but many OPDS readers cache the opds url the first time it's added and the fix is usually to delete, save, close the app, then add the link again. I'm always open to trying to fix anything, but OPDS is consistent between all other devices and Panels or Moon Reader, for example, is working as expected.
