### ISSUE TITLE
Raspberry Pi 32-Bit PDF reading regression

### ISSUE THREAD

**Issue by ChristofferGreen** [Kareadita/Kavita#1205]
In the recent release arm builds have stopped being able to read pdfs. They show up in the browser but when trying to open them you get thrown out to the browser again after a few seconds.

To reproduce this attempt to show a pdf in the latest Kavita release on an arm machine. I am using "Raspbian GNU/Linux 10 (buster)".

Here is a log of the error:
`Apr 06 09:46:41 RaspberryPi Kavita[22195]:       System.AggregateException: One or more errors occurred. (The type initializer for 'SixLabors.ImageSharp.Configuration' threw an exception.) (The type initializer for 'SixLabors.ImageSharp.Configuration' threw an exception.) (The type initializer for 'SixLabors.ImageSharp.Configuration' threw an exception.) (The type initializer for 'SixLabors.ImageSharp.Configuration' threw an exception.) (The type initializer for 'SixLabors.ImageSharp.Configuration' threw an exception.)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:        ---> System.TypeInitializationException: The type initializer for 'SixLabors.ImageSharp.Configuration' threw an exception.
Apr 06 09:46:41 RaspberryPi Kavita[22195]:        ---> System.TypeInitializationException: The type initializer for 'SixLabors.ImageSharp.Memory.MemoryAllocator' threw an exception.
Apr 06 09:46:41 RaspberryPi Kavita[22195]:        ---> System.OverflowException: Arithmetic operation resulted in an overflow.
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at SixLabors.ImageSharp.Memory.Internals.UniformUnmanagedMemoryPool..ctor(Int32 bufferLength, Int32 capacity, TrimSettings trimSettings)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at SixLabors.ImageSharp.Memory.UniformUnmanagedMemoryPoolMemoryAllocator..ctor(Int32 sharedArrayPoolThresholdInBytes, Int32 poolBufferSizeInBytes, Int64 maxPoolSizeInBytes, Int32 unmanagedBufferSizeInBytes, TrimSettings trimSettings)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at SixLabors.ImageSharp.Memory.UniformUnmanagedMemoryPoolMemoryAllocator..ctor(Int32 sharedArrayPoolThresholdInBytes, Int32 poolBufferSizeInBytes, Int64 maxPoolSizeInBytes, Int32 unmanagedBufferSizeInBytes)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at SixLabors.ImageSharp.Memory.UniformUnmanagedMemoryPoolMemoryAllocator..ctor(Int32 poolBufferSizeInBytes, Int64 maxPoolSizeInBytes, Int32 unmanagedBufferSizeInBytes)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at SixLabors.ImageSharp.Memory.UniformUnmanagedMemoryPoolMemoryAllocator..ctor(Nullable`1 maxPoolSizeMegabytes)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at SixLabors.ImageSharp.Memory.MemoryAllocator.Create()
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at SixLabors.ImageSharp.Memory.MemoryAllocator..cctor()
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          --- End of inner exception stack trace ---
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at SixLabors.ImageSharp.Configuration..ctor(IConfigurationModule[] configurationModules)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at SixLabors.ImageSharp.Configuration.CreateDefaultInstance()
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Lazy`1.CreateValue()
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Lazy`1.get_Value()
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at SixLabors.ImageSharp.Configuration..cctor()
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          --- End of inner exception stack trace ---
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at SixLabors.ImageSharp.Configuration.get_Default()
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at SixLabors.ImageSharp.Image.LoadPixelData[TPixel](Byte[] data, Int32 width, Int32 height)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at API.Services.BookService.GetPdfPage(IDocReader docReader, Int32 pageNumber, Stream stream) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\BookService.cs:line 722
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at API.Services.BookService.<>c__DisplayClass25_0.<ExtractPdfImages>b__0(Int32 pageNumber) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\BookService.cs:line 629
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:       --- End of stack trace from previous location ---
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:       --- End of stack trace from previous location ---
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Apr 06 09:46:41 RaspberryPi Kavita[22195]:       --- End of stack trace from previous location ---
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Apr 06 09:46:41 RaspberryPi Kavita[22195]:       --- End of stack trace from previous location ---
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          --- End of inner exception stack trace ---
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:       --- End of stack trace from previous location ---
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at API.Services.BookService.ExtractPdfImages(String fileFilePath, String targetDirectory) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\BookService.cs:line 626
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at API.Services.ReadingItemService.Extract(String fileFilePath, String targetDirectory, MangaFormat format, Int32 imageCount) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\ReadingItemService.cs:line 114
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at API.Services.CacheService.ExtractChapterFiles(String extractPath, IReadOnlyList`1 files) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\CacheService.cs:line 96
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at API.Services.CacheService.Ensure(Int32 chapterId) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\CacheService.cs:line 81
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at API.Controllers.ReaderController.GetChapterInfo(Int32 chapterId) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Controllers\ReaderController.cs:line 84
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at lambda_method656(Closure , Object )
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Apr 06 09:46:41 RaspberryPi Kavita[22195]:       --- End of stack trace from previous location ---
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at API.Startup.<>c.<<Configure>b__4_3>d.MoveNext() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Startup.cs:line 236
Apr 06 09:46:41 RaspberryPi Kavita[22195]:       --- End of stack trace from previous location ---
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
Apr 06 09:46:41 RaspberryPi Kavita[22195]:          at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Middleware\ExceptionMiddleware.cs:line 30`

**Comment by samytichadou** [comment]
hi, same issue here, where could i download nightly build ? (sorry if dumb question, didn't find the link)

**Comment by majora2007** [comment]
@samytichadou Nightly are docker builds. We have confirmed this works and I will be making a hotfix shortly for stable users.

**Comment by samytichadou** [comment]
> @samytichadou Nightly are docker builds. We have confirmed this works and I will be making a hotfix shortly for stable users.

all right, thanks for the info, didn't know about this, i'll wait for the stable version

**Comment by majora2007** [comment]
If this is breaking any 32-bit builds, here is a nightly build:
https://we.tl/t-pJEkUA74EN

Hotfix is being tested for release later today.

**Comment by majora2007** [comment]
This is now closed and released in a hotfix.
