### ISSUE TITLE
No cbz chapters visible when mixed in with image folders

### ISSUE THREAD

**Issue by mxafi** [Kareadita/Kavita#1207]
**To Reproduce**
1. Fresh instance of Kavita running on Docker
2. Create a Manga library
3. Create a series folder in the library root, e.g. "Reformation of the Deadbeat Noble"
4. Move cbz chapters inside of the folder, named appropriately, e.g. "Reformation of the Deadbeat Noble Vol.000 Ch.0001 [Asura Scans].cbz"
5. Scan the library on Kavita front-end
6. Read the cbz chapters on the front-end
7. Move "imagefolder" chapters inside of the series folder, e.g. "Reformation of the Deadbeat Noble Vol.000 Ch.0002 [Asura Scans]"
8. Make sure the chapters folders contain only images in jpg format and named numerically, e.g. "1.jpg, 2.jpg, 3.jpg..."
9. Scan the library on Kavita front-end
10. Now the series doesn't show the cbz chapters, only the imagefolder chapters. E.g. Chapter 0001 is no longer visible in the UI, only Chapter 0002, following the earlier examples.

**Expected behavior**
It is expected to see all the chapters that are present in the series directory.

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Chrome, Brave, Vivaldi, Safari, Firefox
 - Version 0.5.2.0

**Additional context**

Manga Library Root/
├─ Series Folder/
│  ├─ Chapter 1.cbz
│  ├─ Chapter 2/
│  │  ├─ 1.jpg
│  │  ├─ 2.jpg
├─ Reformation of the Deadbeat Noble/
│  ├─ Reformation of the Deadbeat Noble Vol.000 Ch.0001 [Asura Scans].cbz
│  ├─ Reformation of the Deadbeat Noble Vol.000 Ch.0002 [Asura Scans]/
│  │  ├─ 1.jpg
│  │  ├─ 2.jpg

In the above filetree, only the chapter 0002 is visible in Kavita.

Edit: removed unnecessary template text

**Comment by majora2007** [comment]
Mixed formats are not supported within a single Series. Check your library, you should have an Archive Series present.

**Comment by mxafi** [comment]
> Mixed formats are not supported within a single Series. Check your library, you should have an Archive Series present.

That seems to be the case, there is an archive series and an image series for the same series. Both are readable. In my case, one contains chapters 1-3,5,9,11 and the other one contains 4,6-8,10. They are very annoying to read in order.

**Should this be a feature request that should be on the website then instead?**

I'm automating my written content collection with Readarr and scripts, the format that the scrapers find is not always the same for the same series. I'm assuming automation and non-uniform formats (per series) from multiple sources are growing trends, and require action.

**The current behaviour is not user friendly and is definitely an issue from my perspective, nobody should have to hop between "multiple" series to read chapters in order.**

**Comment by majora2007** [comment]
My advice is to standardize with cbz like most other people do. This leads you with a better experience. You can feature request it on our feature site, but I won't be working it. You're asking for a core change, something that would break everyone's install. 

I agree it would be more friendly, but the work required doesn't add up to the benefit in my eyes.
