### ISSUE TITLE
If you begin the scan of a library and then delete the library the scan continues.

### ISSUE THREAD

**Issue by LordFransie** [Kareadita/Kavita#1208]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**

**To Reproduce**
1. Create a Library
2. Begin a scan for the library
3. Delete the library
4. Scan continues even though there is no longer a library to scan for

**Expected behavior**
As a user when I delete a library I expect the scans for that library to be halted.

**Comment by majora2007** [comment]
Nice catch, I've never tested this before. Will take a look at implementing something for this.

**Comment by majora2007** [comment]
Just to let you know, this is a low priority issue and isn't slotted. I doubt many people are running into this issue.

**Comment by LordFransie** [comment]
> Just to let you know, this is a low priority issue and isn't slotted. I doubt many people are running into this issue. 

It's what I would call an incredible edge case.

**Comment by majora2007** [comment]
I put a fix in a long while back to prevent this action, I'm going to close out this issue. Thanks for reporting it.
