### ISSUE TITLE
Internal Server error while accessing content

### ISSUE THREAD

**Issue by AC-WhiteGlint** [Kareadita/Kavita#1216]
I have deployed kavita as a docker contianer.

Sometime when reading an ebook we get an internal server error

I found this error message in the container logs :       Entity Framework Core 6.0.2 initialized 'DataContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite:6.0.2' with options: DetailedErrorsEnabled 

I am using the most up to date version of Kavita

**Comment by majora2007** [comment]
That is not an error. It is likely a metadata error in your epub where it says a file exists but it's missing. I try to handle bad metadata as much as possible, but there are always edge cases.

Can you try re-exporting the file through calibre and seeing if it still throws an issue?
