### ISSUE TITLE
CBZ whit WEBP error on iOS.

### ISSUE THREAD

**Issue by lecelmakerman** [Kareadita/Kavita#1219]
When I try to use Kavita from iPad, it has the following errors:

Login: When you enter the username and password, it sends an error message, and the page is left unloaded. If I update the page, they load all my libraries normally.

Read PDF: ok, not problem.
Read CBZ: ok, no problem whit: JPG, PNG.
Read CBZ: ERROR only whit WEBP format image.

 - Device: iPhone4
 - OS: iOS 10.3.3
 - Browser safari, edge, chrome, firefox
 - Version lasted

**Comment by majora2007** [comment]
WebP doesn't have support on safari browsers. There is nothing I can do, you would need to use another browser. 

https://caniuse.com/webp
