### ISSUE TITLE
Checking for null after usage

### ISSUE THREAD

**Issue by mihaibargau** [Kareadita/Kavita#1222]
In ```DefaultParser.cs``` 

```
              if ((ret.Volumes.Equals(Parser.DefaultVolume) || string.IsNullOrEmpty(ret.Volumes)) && !parsedVolume.Equals(Parser.DefaultVolume))
              {
                ret.Volumes = parsedVolume;
              }
              if ((ret.Chapters.Equals(Parser.DefaultChapter) || string.IsNullOrEmpty(ret.Chapters)) && !parsedChapter.Equals(Parser.DefaultChapter))
              {
                ret.Chapters = parsedChapter;
              }
```
For these 2 if statements ```ret.Volumes``` and ```ret.Chapters``` are being compared first and then checked if they have null values.
I think the ```IsNullOrEmpty``` check should be first. 
If it's OK for you I can create a pull request.

**Comment by majora2007** [comment]
Oh sure, you can raise a PR. They should be flipped around like you suggest, even though I know it will never be null. 

Raise a PR to develop.
