### ISSUE TITLE
OPDS client get wrong content type for cbz files

### ISSUE THREAD

**Issue by sulisu** [Kareadita/Kavita#1239]
**Describe the bug**
Extension of Manga file is cbz. With OPDS, Marvin 3 can see the manga, but refuse to download, which report "This book isn't available as an EPUB, CBR, or CBZ.", in book detail provided by Marvin3, it shows the content type is "applicatioin/zip"

Marvin 3 is an ebook reader support OPDS on Apple Store.

While it works with Calibre-web for the same cbz file, which provided correct content type "application/x-cbz".

OPDS info provided by calibre-web

```
    <link rel="http://opds-spec.org/acquisition" href="/opds/download/36/cbz/"
          length="39476962" mtime="2022-05-02T00:56:16+00:00" type="application/x-cbz"/>
  </entry>
</feed>
```

OPDS info provided by kavita

```
<link rel="http://opds-spec.org/acquisition/open-access" type="application/zip" href="/urlto/manga.cbz" title="manga.cbz" p5:count="[id]"/>
```

**To Reproduce**
I have not test other OPDS clients, maybe other clients will ignore the content type and download it anyway.

To reproduce it, download Marvin 3 from Apple store, it is free with AD. Connect to kavita with OPDS and try some cbz format files.

**Expected behavior**
OPDS should get the correct content type for cbz files as "application/x-cbz", and cbr for rar compressed cbr files.

**Additional context**
Kavita server Version     0.5.2.5, windows-x86

The file is put into library folder with zip extension at first. But I have remove it from library folder on disk and from kavita web gui, rescan library, ensure it is gone. Then rename it with cbz extension, put it back to library folder and rescan, no change.

**Comment by majora2007** [comment]
Hmmm....this seems to be a bug on Marvin's side. Cbz and cbr are zip and RAR files themselves, so the mime type we send back should work. Seems maybe it's coded to only support cbz files.

**Comment by sulisu** [comment]
According to this article <https://www.howtogeek.com/291936/what-are-cbr-and-cbz-files-and-why-are-they-used-for-comics/>, I think it may be intended behavior on Marvin side as an ebook reader.

> By packaging comic books with this special extension, Ayton and everyone after him accomplished two things. Not only did the extension change make it readily apparent the file was a comic book, but it it also paved the way for comic-book centered apps like CDisplay to create file associations with the format. That way, when you double-clicked on one of the files, they would open not in the archive applications they were created in, but in the comic viewers designed to read them. That simple tweak completely changed the way we read comics on our computers and devices.

Although it seems not as useful for an server side app as for a windows desktop ebook reader, I think following the de facto standard and giving cbx extrension some special treatment is not a bad idea. Especially, Kavita is "Built with a focus for manga".^_^

**Comment by majora2007** [comment]
I ended up testing by switching to x-cbz and others and i didn't see any issues. This will be available in nightly in 20 mins or you can wait for the next stable.
