### ISSUE TITLE
People metadata lost if a library scan

### ISSUE THREAD

**Issue by maxpuissance** [Kareadita/Kavita#1240]
By the way : hello everyone :-)

**Describe the bug**
Manually added people in metadata are lost after a library scan. Others metadata I use (not the whole package but at least summary, genre, age rating) are kept. It doesn't seem to come from an embedded comicinfo.xml as I get this behaviour also with a vanilla cbz.

**To Reproduce**
1. Add a new people such as a writer into a comic, save it
2. Start manually a library scan
3. Check the people into the comics : they are gone

**Expected behavior**
To not lose these people :-)

**Desktop**
 - OS: dockerized on Synology / DSM 7
 - Browser Chrome (but would be surprizing to be browser dependent)
 - Version 0.5.2.5

**Comment by majora2007** [comment]
Is the field locked?

**Comment by maxpuissance** [comment]
> Is the field locked?

Yes, I didn't unlock it after manually editing.

**Comment by majora2007** [comment]
I believe this is already fixed in the nightly and will be released on next stable. After re-reading, it appears to be an old issue on the stable (there were a lot of issues with metadata persisting). I'm going to close the issue as it is working on nightly.

**Comment by maxpuissance** [comment]
> I believe this is already fixed in the nightly and will be released on next stable. After re-reading, it appears to be an old issue on the stable (there were a lot of issues with metadata persisting). I'm going to close the issue as it is working on nightly.

Great, thanks :-)
