### ISSUE TITLE
Invite URL change

### ISSUE THREAD

**Issue by DoubtfulTurnip** [Kareadita/Kavita#1243]
I have looked through the Wiki and the issues here on Github but maybe I missed it.

Is it possible to change the URL being used within the invite emails? 
I am using docker and when the invite is sent out via email it then provides the link with the internal docker IP and port which obviously won't resolve for users.

Example;
http://docker-internal-ip:5000/registration/confirm-email?xxxxxxxxxxxxxxxx

I would like it to be able to display my public URL that I am using on my reverse proxy;

https://publicurl.com/registration/confirm-email?xxxxxxxxxxxxxxxx

Is this just a case of adding something within appsettings.json?

- In the Admin dashboard click on Invite 
- Fill in user invite details
- URL displayed is using docker internal IP and port

**Comment by scare376** [comment]
are you connected to the server through the local ip when inviting? If so try it when connected through the public URL.

**Comment by DoubtfulTurnip** [comment]
So I just double checked to make sure.

I am accessing Kavita through the public URL which is setup on my reverse proxy.

When creating invites it is still displaying the links with the docker internal IP and port

**Comment by majora2007** [comment]
The way the code works is we take the url in which you access the site though. So if you access via your reverse proxy, it will send out email links with that, else if you use an internal ip, it will try that. 

It might be interesting to allow a setting to force links to use the external proxy url (if it is accessible and set). 

I'll double check that it uses external when you invite with external url.

**Comment by majora2007** [comment]
I'm not able to reproduce this. What version of Kavita are you on?

**Comment by DoubtfulTurnip** [comment]
> I'm not able to reproduce this. What version of Kavita are you on?

My apologies for not responding sooner. I believe the issue was somehow caused by a configuration issue in my reverse proxy when using NPM
