### ISSUE TITLE
Investigate Folder-based requirements

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#1250]
In order to bring more performance to the scanner and functionality to not have to scan everything before insert, I want to investigate a requirement of having all of one series within one folder. 

Sub folders are fine, so:
Bloody Monday/Bloody Monday Season 1/
Bloody Monday/Bloody Monday Season 2/
Bloody Monday/Bloody Monday Final Season/

would still work fine. But you can't have Death note in Bloody Monday/ and Death Note/ and still be grouped together. 

This will bring much faster scans and ability to monitor the underlying disk, but may alienate some users. 

We can store highest folder on the Series object, to allow for easy triggering of a series scan and quick updates.

**Comment by tocotronaut** [comment]
would be fine if you can choose set this behavior for every "Library".
