### ISSUE TITLE
How do you restore a database that's backed up? 

### ISSUE THREAD

**Issue by ofsaleem** [Kareadita/Kavita#1251]
Hi could you add something to the docs that explains where a backed up database goes, what it contains, and how to restore it if need be?

i'm using container station for my kavita install and i realized CS swapped the tag to "latest-data-1" so if i ever need to update kavita, i'll have to recreate the container, and im not sure but i think that means i'll lose my database. id like to be able to drop-in a replacement, mainly so i don't have to re-invite users. are they stored in the database?

thanks!

**Comment by majora2007** [comment]
Hi, I can add a wiki entry for that.

You shouldn't ever need to recreate your container and start from scratch. Everything important is in the config directory. Inside are backup zips that you can use to replace the files in config, including the database, bookmarks, etc.

Note, if you've gotten on a nightly release on accident, just wait for the next stable before you switch back. The database schema will be the same at that time.

**Comment by majora2007** [comment]
Added a wiki entry for this:
https://wiki.kavitareader.com/en/guides/misc

Thanks for pointing it out.
