### ISSUE TITLE
WebP missing from default upload image window

### ISSUE THREAD

**Issue by azuravian** [Kareadita/Kavita#1252]
**Describe the bug**
WebP images are not included in the select file dialog box when uploading image for a cover.

**To Reproduce**
1. Go to any issue or volume.
2. Edit issue or volume and choose cover image/cover.
3. Select "Upload an Image" from provided options.
4. Dialog box only shows png, jpg, and jpeg

WORKAROUND: choosing All Files allows you to select the webp image and it does save correctly as the cover.

**Expected behavior**
webp would be included as an option for cover images in the default dialog box.

**Desktop (please complete the following information):**
 - OS: Kavita server running in Docker, accessing from Windows 11 desktop
 - Browser: Edge 101.0.1210.39
 - Version: 0.5.2.5

**Comment by majora2007** [comment]
This is more of a feature request. We don't support webp upload as webp is not universally supported on all browsers, hence we'd have to convert it. Please visit feats.kavitareader.com to request this. Thanks.
