### ISSUE TITLE
importing incorrectly. title has the word special but is not a special.

### ISSUE THREAD

**Issue by fonephreak** [Kareadita/Kavita#1253]
Kavita Version 0.5.2.5 running on windows

the manga I added has the word special in the title of it and when importing it thinks the 15 chapters I have are different specials depending on the page instead of one manga with different chapters 

examples

\A Returner's Magic Should Be Special\_Chapter 1\002.jpg
(imports as)
Title: 002
Chapter: 1
Pages: 1

\A Returner's Magic Should Be Special\_Chapter 2\002.jpg
(imports as)
Title: 002
Chapter: 2
Pages: 1

**Comment by majora2007** [comment]
Special as a keyword gets stripped. You'll have to put these in a cbz and use ComicInfo to get around it.
