### ISSUE TITLE
When in safari or in chrome ion ipad, the bar will cover some image when I choose Image Scaling to height.

### ISSUE THREAD

**Issue by Unknown-Chinese-User** [Kareadita/Kavita#1256]
**Describe the bug**
The searching bar will cover some of image when I choose Image Scaling to height in safari on ipad.
![P~93WU9)}%M %BLUFZQI_$9](https://user-images.githubusercontent.com/56683174/168460407-a0070355-66fc-4ba7-bdc8-1d5389351ddc.jpg)

samilar in Chrome
![OG`M9$@ZGW$QMIT 8X(MIHQ](https://user-images.githubusercontent.com/56683174/168460608-12b6ead5-cbde-4973-bbe8-395513c9cdb6.jpg)

When on firefox, it performs well.
![0KWIZFPAM)MN4PNYX_F$ S0](https://user-images.githubusercontent.com/56683174/168460422-928fbc86-8134-453e-b21c-be6596466827.jpg)

**To Reproduce**
1. open server on computer
2. open website in safari on ipad
3. choose Scaling Options in setting, switch it to fit to height
4. open a manga(zip), and you can see the brower bar cover part of image

**Expected behavior**
The bar should not cover images

**Smartphone (please complete the following information):**
 - Device: Ipad air 3
 - OS: 15.3.1
 - Browser: safari
 - Version: 15.3.1

**Comment by majora2007** [comment]
I'll take a look. We have just done some changes on the manga reader so I think this issue might be solved, but I'll double check with newest code on the different browsers.

**Comment by Unknown-Chinese-User** [comment]
by the way, do manga and comic have difference in features?

**Comment by majora2007** [comment]
No. They are the same thing just different words based on country of origin. Comic library use a different filename parser based on the conventions of comics.

**Comment by majora2007** [comment]
This issue is not reproducible on our new reader code. I'm going to close it out and after our upcoming stable, which is entering testing phase, you can re-validate and open if needed.
