### ISSUE TITLE
Search for a book in a series doesn't find the book or the series 

### ISSUE THREAD

**Issue by zombiehoffa** [Kareadita/Kavita#1259]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
When I search for a book that is in a series nothing shows up but if I search for the series I can see the book in the series

**To Reproduce**
1. search for a book that is in your library but that is part of a series of books. 
2. notice nothing shows up.
3. search for  the series, enter the series and note the presence of the book in the series.

**Expected behavior**
If I search for a book that is present then it should show up in the search results. At the bare minimum searching for a book that is in the library but in a series should bring the series up.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker] Docker latest
 - Browser [e.g. chrome, safari] brave  on linux
 - Version [e.g. 22] (can be found on Server Settings -> System tab) 0.5.2.5

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majora2007** [comment]
This is already implemented in the nightly. Please wait for v0.5.3
