### ISSUE TITLE
Support for FB2 format

### ISSUE THREAD

**Issue by asm0dey** [Kareadita/Kavita#1264]
FB2 ebook format is very popular format at least in Russia. It's very rich and described extensively as XSD: https://github.com/gribuser/fb2

It would be nice to have support for fb2 books in Kavita too!

**Comment by asm0dey** [comment]
Thanks!

**Comment by 9Skrip** [comment]
sorry for opening but voting page is 404

**Comment by scare376** [comment]
Our feature requests moved to GitHub discussions

**Comment by majora2007** [comment]
FB2 is also not something I'm interested in pursuing.

**Comment by asm0dey** [comment]
At this point I'm not interested either :)
