### ISSUE TITLE
[Manga Reader] Ability to use keyboard keys on Original image viewing

### ISSUE THREAD

**Issue by Havokdan** [Kareadita/Kavita#1273]
Good morning, I just wanted to ask a question, when I configure the program to view the files in the original image size, sometimes the image exceeds the screen field, which keys can I use in this case to view the image page? Keyboard arrows go to the next or back one page.
Sorry I'm using google translate.

**Comment by majora2007** [comment]
Hmm in this case, I guess this is an oversight. You'd have to use your mouse to scroll. I never use original honestly since we have the new renderer which allows zooming without quality loss.

**Comment by Havokdan** [comment]
> Hmm in this case, I guess this is an oversight. You'd have to use your mouse to scroll. I never use original honestly since we have the new renderer which allows zooming without quality loss.

OK, thanks, too bad my mouse has a life of its own here and doesn't behave well...would it be possible to have keys on the keyboard to navigate the page without going to the next or back?

**Comment by rdawman** [comment]
Looks like keyboard control is being added but don't work as expected - randomly works once or twice. There are 2 "UP" arrow key doing the same thing in the shortcuts menu.
