### ISSUE TITLE
support for Chinese language

### ISSUE THREAD

**Issue by Unknown-Chinese-User** [Kareadita/Kavita#1275]
We use "第01卷" or "卷1" for volume and "第2话" for chapter or episode.
My suggest regex
`(?<Series>.*)第(?<Volume>\d+)[卷册]`,`(?<Series>.*)卷(?<Volume>\d+)`

**Comment by majora2007** [comment]
As mentioned in the discord, please provide characters translations. 

Symbol -> Volume
Symbol -> Chapter

as many as you can. 

Please provide cases for testing against, like (in english, but yours in chinese) "One-Punch Man Volume 03.cbz", etc. 

The more information the better. Without that, I cannot work on this request.

**Comment by Unknown-Chinese-User** [comment]
In chinese, we use `第n卷` combination to stand `Vol. n`, and sometimes it can be used as `卷n`.(`n`stands for a number)
第n卷 -> Volume n
第n册 -> Volume n
卷n     -> Volume n
册n     -> Volume n
第n话 -> Chapter n

as for test case
幽游白书完全版 第03卷 天下.pdf
阿衰online 第1册.pdf
夏日時光 - 卷02.kepub.epub
【TFO汉化&Petit汉化】迷你偶像漫画第25话.zip

**Comment by majora2007** [comment]
Do you have examples of both volume and chapter in one filename?

**Comment by daydreamrabbit** [comment]
in korean we use this

제n권 -> Volume n
n권 -> Volume n
n화 -> Chaper n
제n화 -> Chapter n

**Comment by HelloMusician** [comment]
For Chinese version, please refer to them:
卷 -> Volume
章 -> Chapter
库 -> Libraries
列表 -> Lists
合集 -> Collections
正在阅读 -> On Deck
最近添加 -> Recently Added
管理员 -> Admin
用户设置 -> User Settings
服务器设置 -> Server Settings
注销 -> Logout
搜索 -> Search Series
--------------------------------------------------------------------------------------------------------------------------------------------
用户面板 -> User Dashboard
首选项 -> Preferences
书签 -> Bookmarks
这些是关联您账户的全局设置。 -> These are global settings that are bound to your account.
网站 -> Site
暗黑模式 -> Dark Mode
启用 -> True
禁用 -> False
重置 -> Reset
保存 -> Save
阅读 -> Reading
漫画 -> Manga
阅读方向 -> Reading Direction
从左到右 -> Left To Right
从右到左 -> Right To Left
缩放选项 -> Scailing Options
自动 -> Automatic
适应高度 -> Fit To Height
适应宽度 -> Fit To Width
原始比例 -> Original
分页 -> Page Splitting
适应屏幕 -> Fit To Screen
不拆分 -> No Splitting
阅读模式 -> Reading Mode
从上到下 -> Up To Down
网络动漫 -> Webtoon
自动关闭菜单 -> Auto Close Menu
书籍 -> Books
书籍阅读方向 -> Book Reading Direction
单击翻页 -> Tap to Paginate
字体库 -> Font Family
默认 -> Default
字体大小 -> Font Size
行高 -> Line Height
页边距 -> Margin
密码 -> Password
修改您的密码 -> Change your Password
新密码 -> New Password
确认密码 -> Confirm Password
--------------------------------------------------------------------------------------------------------------------------------------------
管理员面板 -> Admin Dashboard
基本设置 -> General
端口和日志级别的改动必须手动重启Kavita才能生效。 -> Port and Logging Level require a manual restart of Kavita to take effect.
缓存目录 -> Cache Directory
端口 -> Port
日志级别 -> Logging Level
允许收集匿名使用信息 -> Allow Anonymous Usage Collection
向Kavita的服务器发送匿名使用和错误信息。这包括有关浏览器、错误报告以及操作系统和运行时版本的信息。我们将使用这些信息来确定功能、错误修复和性能调优的优先级。需要重新启动才能生效。 -> Send anonymous usage and error information to Kavita's servers. This includes information on your browser, error reporting as well as OS and runtime version. We will use this information to prioritize features, bug fixes, and preformance tuning. Requires restart to take effect.
发送数据 -> Send Data
OPDS支持将允许所有用户使用OPDS从服务器读取和下载内容。如果启用了OPDS，用户在使用媒体时将不需要下载权限即可下载媒体。 -> OPDS support will allow all users to use OPDS to read and download content from the server. If OPDS is enabled, a user will not need download permissions to download media while using it.
启用OPDS -> Enable OPDS
身份认证 -> Authentication
通过禁用身份验证，所有非管理员用户将能够仅凭其用户名登录。无需密码即可进行身份验证。 -> By disabling authentication, all non-admin users will be able to login by just their username. No password will be required to authenticate.
启用身份认证 -> Enable Authentication
计划任务 -> Reoccuring Tasks
扫描库 -> Library Scan
备份数据库 -> Library Database Backup
每周 -> Weekly
每日 -> Daily
禁用 -> Disabled
用户 -> Users
创建用户 -> Add users
上次登录 -> Last Active
共享 -> Sharing
角色 -> Roles
类型 -> Type
共享文件夹 -> Shared Folders
上次扫描 -> Last Scanned
系统 -> System
关于系统 -> About System
版本 -> Version
安装ID -> Install ID
更多信息 -> More Info
主页 -> Home page
更新日志 -> ChangeLog
操作 -> Actions
备份数据库 -> Backup Database
清除缓存 -> Clear Cache
下载日志 -> Download Logs
检查更新 -> Check for Updates

**Comment by majora2007** [comment]
Hello @HelloMusician , thank you for your translations. This issue is closed and is about supporting Chinese characters when filename parsing. For localization, I will be tackling this very soon and be using a community tool, like weblate, so the community can translate the app for me.

**Comment by HelloMusician** [comment]
> 您好@HelloMusician，感谢您的翻译。此问题已关闭，是关于在文件名解析时支持中文字符。对于本地化，我将很快解决这个问题，并使用社区工具，如 weblate，以便社区可以为我翻译应用程序。

Sorry, I didn't notice that it was already closed. Thank you for your contribution to open source！
