### ISSUE TITLE
Consolidate admin and user dashboards

### ISSUE THREAD

**Issue by Tyestor** [Kareadita/Kavita#1277]
The two dashboards:

Admin:

![image](https://user-images.githubusercontent.com/4704145/169732669-590e295b-35a8-4829-aec8-181fc0ba74ad.png)

User:

![image](https://user-images.githubusercontent.com/4704145/169732701-9cbec1bf-87d5-43f2-abc9-8437d1fc8302.png)

Accessed two different ways: Cogwheel next the username dropdown and settings button under the username dropdown.

These settings being on different pages make it a pain to configure kavita. They should be consolidated down to one page just like plex.

Suggestion: Firstly, rename the dashboard to just "Settings Dashboard". Next, cogwheel icon next to the username should have all the settings: General (Admin), Users (Admin), Libraries (Admin), System (Admin), Preferences (Non-Admin), Password (Non-Admin), 3rd-Party Clients (Non-Admin), Theme (Non-Admin). The new consolidated dashboard should simply hide the admin relevant settings on non-admin accounts. Naturally, admins should also be able to administrate defaults for non-admin accounts for all non-admin settings.

**Comment by majora2007** [comment]
These are 2 different areas of the app. It doesn't make sense to combine them. I understand your point kind of but this is not a change I'm willing to consider.
