### ISSUE TITLE
Home Page Does Not Appear on Load When Already Logged In (iOS)

### ISSUE THREAD

**Issue by dathbe** [Kareadita/Kavita#1278]
Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
When opening Kavita stored as a home screen shortcut on an iOS device and a user is already logged in, a mostly blank screen is presented.  Clicking the Home button fixes the issue.  This does not appear to happen on a desktop browser, it does not appear to happen when prompted to log in, and it does not appear to happen if using the actual Safari app.  

**To Reproduce**
1. Open Safari on iOS, navigate to Kavita instance, log in
2. Click the actions button
3. Click "Add to Home Screen"
4. Close Safari
5. Open the Kavita shortcut app just created
6. Log in
7. Close the Kavita shortcut app
8. Open the Kavita shortcut app

**Expected behavior**
Home screen displays properly

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Safari on iOS (home screen shortcut only)
 - Version: 0.5.3

**Smartphone (please complete the following information):**
 - Device: iPad 6th Gen.
 - OS: iOS 15.5
 - Browser Safari shortcut
 - Version 0.5.3

**Additional context**
![22-05-22 20-25-09 0032](https://user-images.githubusercontent.com/14321825/169875015-a2fc48b0-7c73-4a01-996b-9da8253342c5.png)

**Comment by dathbe** [comment]
Confirmed that this is the issue.  The software seems to want to redirect ```<domain>``` to ```<domain>/login``` if not logged in or ```<domain>/libraries``` if logged in.  This doesn't seem to happen reliably (at least in Firefox).  Fortunately, ```<domain>/login``` will reliably redirect to ```<domain>/libraries``` if you are logged in, so by going to the former directly, everything works as expected.

I have written a regex redirect for my reverse proxy so that whenever anyone tries to go to the root, it will automatically redirect to the /login page.  This seems to be working:

```
regex: "^https://kavita.yourdomain.com$"
replacement: "kavita.yourdomain.com/login"
```

Hope this helps someone.

**Comment by majora2007** [comment]
Thanks for reporting this issue with a fix, I wish you were here last release. I have actually already fixed this, finally, and it will be coming on next stable.

**Comment by dathbe** [comment]
NP.  I only confirmed the problem and figured out the solution in the last couple days.  Your solution is probably entirely different, but I should mention that I did have to have a second regex rule for the situations when the user or browser puts a "/" at the end of the url:

```
regex: "^https://read.beffa.us/$"
replacement: "read.beffa.us/login"
```

**Comment by majora2007** [comment]
Yeah, my solution is the actual bugfix actually. There was an infinite redirect loop occurring in a very strange way, which made it very hard to track down. But after I finally was able to identify, the fix was trivial.
