### ISSUE TITLE
New table of contents does not work with some books

### ISSUE THREAD

**Issue by coscosname** [Kareadita/Kavita#1279]
**Describe the bug**
The new table of contents does not work with some books. (The old ToC worked with these books.)

**To Reproduce**
1. Go to some book
2. Click on Menu button
3. Clink on Table of Contents
4. You can see the empty ToC

**Expected behavior**
A working table of contents with all books.

**Screenshots**
![image](https://user-images.githubusercontent.com/89737988/169885186-2a1cf992-7004-4b61-8c88-90587188cf00.png)

**Comment by majora2007** [comment]
Please provide the book to me in discord and I will investigate. I did not touch that code in the last release, but perhaps the underlying update is handling something differently.

**Comment by majora2007** [comment]
I took a look at this and it seems to be an issue with our underlying library on how it handles the key's. I'm seeing keys come back as: `Text/../Text/file.xhml' when it should be 'Text/file.xhtml'. 

I will need to open an issue with the library, so this might be slow to fix.

**Comment by majora2007** [comment]
https://github.com/vers-one/EpubReader/issues/45
