### ISSUE TITLE
ComicInfo Format Tag Support

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#1283]
In order to mark some files as a Special without using special keywords or SP marker, we can use the `Format` tag.

If the Format tag is set and it has one of the following set, the file will be treated as a special. This is needed as the schema dictates that it is a free form string. Values are coming from ComicTagger for reference. 

Tags:
`Special, Reference, Director's Cut, Box Set, Box-Set, Annual, Anthology, Epilogue, One Shot, One-Shot, Prologue, TPB, Trade Paper Back`

**Comment by therobbiedavis** [comment]
Omnibus, Compendium, Absolute
