### ISSUE TITLE
Is there any plan to support text book?

### ISSUE THREAD

**Issue by javara999** [Kareadita/Kavita#1288]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Currently, the book library supports epub and pdf formats.
Are there any plans to add text support?

**Comment by majora2007** [comment]
What is text support mean? Please be descriptive to help me understand.

**Comment by javara999** [comment]
> What is text support mean? Please be descriptive to help me understand.

I mean *.txt format files..
Is there any plan for *.txt support?

**Comment by majora2007** [comment]
What you're looking for is our feature request site to ask for this functionality.

https://feats.kavitareader.com/posts/146/please-support-txt-file

Someone just asked this yesterday, so give it an upvote.
