### ISSUE TITLE
EPUB Column Mode causes cropping issues along right edge of text

### ISSUE THREAD

**Issue by LDShadowLord** [Kareadita/Kavita#1289]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
When using the "One Column" mode in Kavita, it causes the edge of the words to the right to be cut off. It can cut off partial characters or entire words. This issue persists even when margins are changed, removed, or increased to maximum. It's can be temporarily removed by changing margins, but this fix will not persist across pages within a chapter.

**To Reproduce**
Using a Samsung Galaxy S22+, open a book in Kavita. Set it to any margin size and "One Column" mode and proceed to read through, at some point the text will begin to be cut off along the right hand edge. This is variable as it is based on the length of words.

**Expected behavior**
Word wrapping to take effect and cull any words that would have gone into that margin region, and move them onto a lower line.

**Screenshots**
![tempFileForShare_20220526-181137](https://user-images.githubusercontent.com/3749770/170540974-efb1914e-79a9-4922-a80a-021e443633c9.jpg)
![tempFileForShare_20220526-181306](https://user-images.githubusercontent.com/3749770/170540987-2dd63acb-6821-4e25-ba4f-08f8b181a388.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22+
 - OS: Android 12
 - Browser: Chrome 102.0.5005.58

**Additional context**
Could be partially replicated by using Chrome Dev Tools "Device Emulation" mode and setting it to Samsung Galaxy S20 Ultra, though that only took a few pixels off and is not as egregious as on the actual mobile device.

Issue has only been seen on books generated by FanFicFare, so may be an isolated issue related to their CSS or generation method.

Changing the Margin would fix the issue for the specific page I was on, but the issue would then revert within the following pages. This was the same regardless of what margin size was chosen.

**Comment by majora2007** [comment]
I was only able to reproduce on the Samsung Galaxy S20 Ultra with no margin, which is not the ideal way to read. 

My suggestion would be to set margin to 5% and save that in your user settings so all books get that treatment (I personally use 15% for all books, works great). 

There isn't anything I can really do to fix at 0% margin.
