### ISSUE TITLE
Korean Parser Support

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#1290]
Implement Korean Parsing Support. 

From discord discussion: 
제n권 -> Volume n
n권 -> Volume n
n화 -> Chapter n
제n화 -> Chapter n

08권#187 -> Volume 8 Chapter 187

**Comment by daydreamrabbit** [comment]
제n화 = Episode n | Chapter n 
n화 = Episode n | Chapter n 

제n권 = Volume n
n권 =  Volume n

제n부 = Part n
n부 = Part n

제n장 = Chapter n | Episode n
n장 = Chapter n | Episode n

시즌n = Season n
n시즌 = Season n
