### ISSUE TITLE
Japanese Parser Support

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#1294]
Implement some native japanese characters to extract volume and chapter information.

See #1275 for format information.

**Comment by scare376** [comment]
第n話 -> Chapter n
n巻 -> Volume n
n -> Volume
（n）-> Volume

Examples
【期間限定　無料お試し版】異世界征服記～不遇種族たちの最強国家～（単話版）第1話.cbz
スライム倒して300年、知らないうちにレベルMAXになってました 1巻【期間限定 無料お試し版】.cbz
幼なじみが絶対に負けないラブコメ 2 - 二丸修一.epub
スライム倒して３００年、知らないうちにレベルＭＡＸになってました２.epub
五等分の花嫁（１０）.cbz

**Comment by scare376** [comment]
updated it. didnt like one of the examples i had so i grabbed another i was more comfortable with. instead of english i gave the romanji.

**Comment by scare376** [comment]
the first example is? i have the examples in the same order i have them up top
