### ISSUE TITLE
Series Duplication Bug

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#1295]
Starting in v0.5.3, series can duplicate.

**Comment by soju6jan** [comment]
Thank you for your excellent project.
I am using your program with a slight modification and the same problem has occurred.
I'm not sure, but please check the answer here.

https://stackoverflow.com/questions/28849407/disable-re-queueing-of-failed-hangfire-backgroundjob

It seems that definition is needed on the interface ( IScannerService )
thanks.

**Comment by majora2007** [comment]
Interesting. I'll give it a shot and report back.

**Comment by majora2007** [comment]
https://stackoverflow.com/questions/28849407/disable-re-queueing-of-failed-hangfire-backgroundjob 

Did not work. It only made things worse. I did a partial revert in latest code (it's on both interfaces and implementation) and things are stable again. Just on interfaces, duplication was rampant.
