### ISSUE TITLE
scanning / finding / not everything 

### ISSUE THREAD

**Issue by mamema** [Kareadita/Kavita#1299]
Just used the latest docker image and made my calibre library as root folder

have 33.000 ebooks and pdfs

just finds a fraction of it.
several times pressed scan library, without help

Only info messages in the log.

deleted every empty directory within my calibre library folder .... just in case....

Expected behavior**
should find every ebook/pdf

 - OS: [Docker - latest]
 - Browser [chrome - latest]
 - Version 0.5.3.0

**Comment by majora2007** [comment]
You're going to need to give me more information that just this. We have many users and things are working as expected. 

What are your volume mount points? What type of files do you have? How many are found? PDFs rely on filename parsing, so some could be dropped if not properly named. Ebooks rely on internal metadata inside the epub's opf (we do not support external).

If you're pointing your kavita library at a calibre library, it will not work well. You need to point at the raw files.


More information is needed for support.

**Comment by mamema** [comment]
...i've pointed to the Calibre Library Folder where all subfolders of .epubs and .pdfs are. All metadata is created and maintained with calibre itself.
From the >30.000 .epubs about 900 were found and from the about 500 pdfs none were found.
I have in every subfolder a metadata.opf file from calibre. I'm not sure if my metadata is external then....

**Comment by majora2007** [comment]
As mentioned we don't support calibre library, you need to point to the source files. We do not support external opf files, they must be embedded in the file.

**Comment by mamema** [comment]
.epub and .pdf, nothing else. But it's okay, as i'm coming from calibre, it "shouldn't" be an issue to scan a tree which is maintained by calibre. Its just the structure /calibre library/Author/Bookname/epub file. If this is too much for a scan tasks, then i dunno ......just create another/other folder structure because the app "want it so" isn't a solution for me

**Comment by I-G-1-1** [comment]
> just create another/other folder structure because the app "want it so" isn't a solution for me

sorry to tell to the developer but @mamema is right. If Kavita is not able to scan a simple structure folder like the calibre author/bookname/book.epub this piece of software is failed at the start. I really hope the devs could change this incomprehensible choice. Meanwhile I'll user another software.

**Comment by therobbiedavis** [comment]
> > just create another/other folder structure because the app "want it so" isn't a solution for me
> 
> 
> 
> sorry to tell to the developer but @mamema is right. If Kavita is not able to scan a simple structure folder like the calibre author/bookname/book.epub this piece of software is failed at the start. I really hope the devs could change this incomprehensible choice. Meanwhile I'll user another software.

Kavita supports the any folder structure, we're folder structure agnostic. For context Kavita is primarily focused on manga, so the foundational logic is based around just parsing metadata or the filename. We can parse epubs filename but it's not as informative, so epub metadata (opf file) is crucial and Calibre, by default, stores metadata in an external opf file; we don't support that. We support when the opf file is inside the epub, which Calibre will do if the epub is exported as such. 

That said there are a multitude of reasons why only some of @mamema files not being picked up but the most likely scenario is that the epubs could be malformed which could be confirmed by looking at the logs (Calibre and other readers are much more flexible about reading malformed epubs than our external reader library).

This logic is not going to change. We're not really interested in supporting any other software's self-imposed standards unless it has wide spread support and adoption. Enjoy your other software. 👍

**Comment by mamema** [comment]
>unless it has wide spread support

what else is a calibre structure?
It's a steep argument to tell me my >30.000 epubs are malformed. But, anyway, yes i'm enjoying (other) functioning software then.

**Comment by I-G-1-1** [comment]
> unless it has wide spread support and adoption

Calibre de facto is a standard with wide spread adoption.

> Enjoy your other software. 👍

I found calibre-web and it's perfect for my purpose.


However thanks to take the time to explain this project is focused on manga and will never fit my needs.
