### ISSUE TITLE
Cannot view nested zip files

### ISSUE THREAD

**Issue by chrisk414** [Kareadita/Kavita#1309]
Hi, first of all, I really appreciate the wondering project. 
I think I'm going to make this my default comic viewer.
One problem I have is that it cannot read/view nested zip files, i.e., a zip file that contains several zip files. 
I can unzip the zip files but I prefer not to have too many files in a directory. 
Thanks for your support.

**Comment by majora2007** [comment]
FYI, I don't think any program supports this due to the zip bomb security vulnerability and complexity. It is very rare for comics to be double zipped.

**Comment by chrisk414** [comment]
Nested zip comics are common and Honeyview supports them.

**Comment by majora2007** [comment]
Kavita will not support them. You can try another application if that is important to you.
