### ISSUE TITLE
Problems using Kavita with Firefox

### ISSUE THREAD

**Issue by bjoerns1983** [Kareadita/Kavita#1312]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
Trying to use Kavita with Firefox on Linux or Windows end with Kavita not loading the Page and soon after it Firefox (current Version) complains that Kavita is slowing down the Browser. It works without issues with Chrome and Safari. Also tried private mode so no addon can interfere.

**To Reproduce**
Install Kavita via docker and try to access it using Firefox.

**Expected behavior**
Kavita Webpage should load

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux and Windows
 - Browser Firefox
 - Version 101.0 64bit

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majora2007** [comment]
Please search or read our release notes. There is a workaround noted for Firefox on the release notes.
