### ISSUE TITLE
ComicInfo field "Number" seems to break Kavita's ability to read some metadata if number is a range e.g. 1-10

### ISSUE THREAD

**Issue by Juri4su** [Kareadita/Kavita#1313]
As the title says, if the field has a range of numbers inside it then some things seem to break. For example it could no longer read any author information such as writer, penciller or cover artist. I could reproduce this everytime by removing the field or setting it to a single number which would fix it, and if I changed it back it would break again.

**Comment by majora2007** [comment]
This is because a range is not a valid value for the Number field. All applications seen have only supported single numbers.

The way I get around this is naming the chapter range in the filename.

**Comment by Juri4su** [comment]
Ah, if it’s a limitation of the ComicInfo format then I guess not much can be done about it. I’ll try your suggestion of putting it in the filename!
