### ISSUE TITLE
Tags not removed from kavita when removed from comicinfo.xml

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#1326]
**Describe the bug**
When removing tags from comicinfo.xml. Upon refreshing the tags are not removed from kavita.
The tags are getting updated because any new tags added to the file are added to kavita

**To Reproduce**
1. remove tags from comicinfo.xml
2. scan series in kavita

**Expected behavior**
Removed tags no longer appear in kavita

**Desktop (please complete the following information):**
 - OS: Docker
 - Version 0.5.3.19

**Comment by tanpro260196** [comment]
Not just comicinfo, epub metadata like subject, author, publisher etc are the same, they only added on top, not actually update to match the file's metadata.
