### ISSUE TITLE
Kavita can't load in Firefox.

### ISSUE THREAD

**Issue by tanpro260196** [Kareadita/Kavita#1335]
Build: v0.5.3.23
Firefox will just load forever like the pic below:
![image](https://user-images.githubusercontent.com/12226439/175852836-d73fb391-56ce-4c6e-9573-ee1804f1aa48.png)

It load just fine in Chrome and Edge.
I tried to use a clean install of Firefox with no add-on, same problem.
Firefox version is 101.0.1 (64-bit)

**Comment by majora2007** [comment]
It's good practice to search for issues before opening one. Just add /login and it will fix itself.
