### ISSUE TITLE
Brazilian Portuguese in the list of languages ​​for comics.

### ISSUE THREAD

**Issue by Havokdan** [Kareadita/Kavita#1347]
Would you like to ask to put the Brazilian Portuguese language in the list of possible languages ​​for the comics? Strange is that I saw in the list "Spanish of Brazil" being that Spanish is not official language of Brazil....

**Comment by Havokdan** [comment]
![image](https://user-images.githubusercontent.com/6549729/176904437-1e0c4af5-ff5b-4282-8aea-aa1588d4d2a2.png)

Well, actually a correction, the only official language in Brazil (my country) is Portuguese, known as Brazilian Portuguese, Brazilian Portuguese, pt-BR, pt_BR, ptb, pob and etc...

**Comment by majora2007** [comment]
So is this an issue then? If the option is there, there shouldn't be any issue. Kavita doesn't assume anything. We read tags from the metadata or provide a huge list to allow you to specify.

**Comment by Havokdan** [comment]
> The ISO code for Brazilian Portuguese is 'pt-BR' as per RFC5646 and ISO 639-1 (country code ISO 3166-1). .NET Cultures 'es-BR' doesn't seem right for us Brazilians, but the option for 'pt-BR' is there anyway. <img alt="image" width="299" src="https://user-images.githubusercontent.com/75567460/176919060-38623b59-6bd0-4db7-859f-8fb3fb30e363.png">

This option is not showing up for me...
