### ISSUE TITLE
List View doesn't display volume that starts with zero BUG

### ISSUE THREAD

**Issue by kevlp3000** [Kareadita/Kavita#1356]
**Describe the bug**
List view is not displaying volume that start with zero (0.5). Search will find it but selecting the book will open volume 1. When going into the Series edit/info the book is listed. It displays in card view as it always has and can be opened.

**To Reproduce**
Add a book that starts with zero as the volume and switch to or set global default as List View.

**Expected behavior**
See the volume and various details.

**Screenshots**
List view missing volume 0.5
![Screenshot_20220702-143025_Brave](https://user-images.githubusercontent.com/40123829/177015808-c8cab5d7-10d5-4265-8362-d246142b512c.jpg)

Card view showing volume 0.5
![Screenshot_20220702-143042_Brave](https://user-images.githubusercontent.com/40123829/177015840-c90323db-b833-4947-ba6a-93d1e9696b8d.jpg)

**Comment by majora2007** [comment]
Nice find, I'll take a look into it.
