### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by JanikWie** [Kareadita/Kavita#1360]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker]
 - Version [e.g. 22] (can be found on Server Settings -> System tab)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majora2007** [comment]
You didn't fill out the template
