### ISSUE TITLE
Problem with manga with number in title

### ISSUE THREAD

**Issue by Sp4rky001** [Kareadita/Kavita#1362]
**Describe the bug**
For Kaiju No. 8, the folder structure that I have is:
Kaiju No. 8/
    Kaiju No. 8 v000 0001.cbz
    ....

Kavita scans the correct series, but only chapter 8 shows up.  I think this may be becaue of the No. 8 in the filename and Kavita is assuming that all files in the folder are chapter 8

A little more detail:  Kavita is showing the chapter as having over 1000 pages, meaning it treating all of the files as one chapter

**To Reproduce**
1. Acquire Kaiju No. 8 series
2. Name the chapters as Kaiju No. 8 v000 0001.cbz
3. Add to Kavita's library

**Expected behavior**
All chapters should be scanned and listed.

**Comment by therobbiedavis** [comment]
@majora2007 @magujun This is related to the regex. Not sure if fixable (similar to #368) but would one of you like to look at it?

**Comment by Sp4rky001** [comment]
I renamed the files to 
Kaiju No. 8 #0001.cbz

and the series scanned correctly.  Thanks for the help.  I understand that there are too many different formats for filenames and it's too difficult to get regex to recognize all of them.
