### ISSUE TITLE
Horizontal Shift per page

### ISSUE THREAD

**Issue by micfort** [Kareadita/Kavita#1366]
Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
For every page in a chapter of an epub, the text shift a little bit to the left. After a while(high page count), the letters on the right fall of the screen. My best guess it shifts sub pixel for every page.
When opening a book, the first page is normal, the shift happens when going to the next page. The shift amount seems to be correlated to the page number.

**To Reproduce**
1. Open an epub on a phone
2. Go to a high page count in a chapter
3. go to the next page

**Expected behavior**
There should be no shift.

**Screenshots**
![WhatsApp Image 2022-07-07 at 10 19 18 AM](https://user-images.githubusercontent.com/6042490/177728195-293acd7f-e9f9-4749-96c3-49cfcd433bd1.jpeg)

**Smartphone (please complete the following information):**
 - Device: Fairphone 3+
 - OS: Android 11
 - Browser Chrome
 - Version 103.0.5060.71

**Additional context**
I have tried it with multiple epubs
Kavita docker image kizaing/kavita:latest updated on 2 july 2022

**Comment by majora2007** [comment]
Hmm interesting. I tried on my browser emulating iPhone and on a 29 virtual page book and no shifting occurred. Just for good measure, I went through multiple pages (actual pages, not virtual pages for 1 column layout) and no shifting occurred. 

Perhaps this is a webkit bug? @therobbiedavis If you have a chance, could you test this out on mac or iphone and see if you get any shifting?

**Comment by micfort** [comment]
I'm indeed using chrome on android. And I was also thinking about CSS issues from the epub itself, but I noticed on multiple books one of which was Dan Brown, The Lost Symbol.

also It gets really terrible when going to page 253 in a section, then it whole letters from the previous page are vissible.

**Comment by majora2007** [comment]
@micfort If you wouldn't mind PMing me on discord with a link to your book, I can test it out and get to the bottom of the issue.

**Comment by LrrrAc** [comment]
I'm having this same issue. I'm on 0.5.6.1, through brave browser on my phone. Its been multiple books in a series.

**Comment by micfort** [comment]
I have looked further into this issue. 
Chrome on the Fairphone 3+ has this problem, I have also tested with the Fairphone 4 from a friend, which worked fine.
Also different browsers(Brave and Opera) that probably use the same engine as chrome also has this problem.

Flow did work. Because of a different issue Firefox did not load Kavita correctly.
After the last update, Flow stopped working, but Firefox could load it.
In both cases the shift issue did not exist in those browser. (probably because of a different engine)

Currently I use Firefox as a workaround.

**Comment by ASNosal** [comment]
Issue occurs with Android System Webview as well. The first page you pull up will look fine, but subsequent page turns (assuming 1 column mode) will shift to the right and start to cut off text.

Firefox on Android does not appear to have this issue.

**Comment by CtrlAltDefeat94** [comment]
> Firefox on Android does not appear to have this issue.

I'm using Firefox on Android, and am having the issue as well.

**Comment by majora2007** [comment]
This should be fixed as of v0.7.4.
