### ISSUE TITLE
API Endpoint /api/Reader/progress not marking progress properly

### ISSUE THREAD

**Issue by RealStickman** [Kareadita/Kavita#1371]
**Describe the bug**
Using the endpoint /api/Reader/progress with certain options returns a code 200, but doesn't properly mark the chapter as read.  
No amount of reloading the page, restarting the browser or restarting kavita fixes that.  

**To Reproduce**  
Use the API to mark any chapter as read with the following payload filled in:  
```
{
  "chapterId": 0,
  "pageNum": 0,
  "seriesId": 0
}
```
The code 200 is returned  

Now check the UI for progress. On Deck it's properly marked, however the chapter you wanted to mark as read is still unread in the series.  

**Expected behavior**
The chapter should be marked as read properly, or the API should return an error.    

**Screenshots**  
Correct progress shown on deck  
![on-deck-progress](https://user-images.githubusercontent.com/61015582/178485926-c64d3f28-7c7c-4298-af42-318b4841c6a2.png)  

Volumes (and also chapters) aren't marked as read when looking at the series  
![missing-progress-volumes](https://user-images.githubusercontent.com/61015582/178486087-91f7374e-f6f7-419f-a648-14b922674181.png)  

**Software versions**  
Kavita version: 0.5.4.0  
Hosted using containers  

Browsers tested: Firefox and Chromium

**Comment by majora2007** [comment]
You need to pass a valid chapterId/seriesId for the API to do something. Pages has to be > 0 for something to be considered in progress or read. 

It might be good to observe how the reader works.

**Comment by RealStickman** [comment]
I am passing valid Ids and page numbers. I just wanted to show which payloads I'm passing  
Here's a valid example for my server.  
There are 24 pages in that chapter, so it should be marked as read.  
```
{
  "chapterId": 1217,
  "pageNum": 24,
  "seriesId": 13
}
```

**Comment by majora2007** [comment]
Sorted via Discord. Response requires all params except bookScrollId. I have updated the documentation and API to return a bad request if not all required fields are provided.
