### ISSUE TITLE
Series not being updated/deleted when issue/chapter metadata is updated

### ISSUE THREAD

**Issue by therobbiedavis** [Kareadita/Kavita#1382]
**Describe the bug**
I updated the series metadata for some comics. Then scanned series but the issues are not being changed from one series to another.

For example: I had an issue load under series name “Hulk (2021-)”. Changed the series metadata on the issue to “Hulk”, scanned series, but the issue isn’t deleting from series “Hulk (2021-)” nor is it loading under series “Hulk”

**To Reproduce**
1. Have issue/chapter(s) with comicinfo.xml metadata with series "1-1"
2. Scan in Kavita, notice series "1-1"
3. Change series metadata to "1-2"
4. Scan series "1-1" in kavita
5. Notice issue/chapter(s) are still in series "1-1" and they are not in series "1-2"

**Expected behavior**
Ideally if all the items in series "1-1" have their metadata changed to "1-2" then series "1-1" should be deleted, and the issues should be picked up in "1-2"

**Screenshots**
![image](https://user-images.githubusercontent.com/7907265/179419543-baa49823-d6ba-4f39-9130-f4f31d074f02.png)
![image](https://user-images.githubusercontent.com/7907265/179419553-64c807b1-cb2d-4cce-a991-1e89d49546fd.png)
![image](https://user-images.githubusercontent.com/7907265/179419562-e61fea18-031e-4bd5-ab18-a817c9df01a8.png)
**Desktop (please complete the following information):**
 - OS: Docker
 - Browser All
 - Version 0.5.4.9

**Comment by majora2007** [comment]
Please retest this against v0.5.5.6

**Comment by majora2007** [comment]
Just a reminder to test this out on latest nightly, else I'll close due to new scan loop.
