### ISSUE TITLE
Kubo Reader Integration

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#1384]
Offer integration with Kubo Reader

https://github.com/janeczku/calibre-web/wiki/Kobo-Integration

**Comment by majora2007** [comment]
This can be accomplished with Send To Device

**Comment by bjw-s** [comment]
Thanks for creating the Send To Device functionality! I am curious how this workflow would work for Kobo devices though, since they don't have the same email to device functionality that the Kindle devices have? Could you perhaps elaborate a little bit on that?

**Comment by majora2007** [comment]
I believe you would just email this to your personal email and either move the file or use an external tool (kobo-sync maybe) to perform the sync to your device. If you still want something custom, you can request it on our feature request site: feats.kavitareader.com. Please include as much details as possible to make it easy for me to take it up.
