### ISSUE TITLE
Idea: Repository for Themes that user's can create and manage.

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#1386]
Custom theme support is starting to grow, but now the problem is there are no ways for other users to use commonly maintained themes, like the eInk or light theme. 

In order to satisfy this need, Kavita can host a separate library of common themes and appoint some users as maintainers. 

Kavita's theme manager will build out support to read theme packs from the Github Repository, provide description, tags, image preview, and a way to download it automatically. There should be an auto-update functionality as well.

The idea is to have a metadata.json next to the css file (or any assets). The metadata would be something like:
```
{
    "name": "Dracula Inspired",
    "selector": "bg-dracula-inspired",
    "author": "Mat",
    "description": "A theme built around the Dracula concept",
    "version": "0.0.1",
    "supports": "0.5.4",
    "hash": "",
    "changelog": [
        {"version": "0.0.1", "description": "Initial Release"}
    ],
    "preview": ["previews/All_Series.jpg", "previews/Library_Detail.jpg"]
}
```

**Comment by DieselTech** [comment]
https://github.com/Kareadita/Kavita/releases/tag/v0.8.2 added this functionality
