### ISSUE TITLE
BUG - Continuous Scroll/Webtoon w/ Full Screen doesn't progress

### ISSUE THREAD

**Issue by Dekumori** [Kareadita/Kavita#1387]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
When using the Continuous Scroll/Webtoon mode and the Full-Screen mode via the UI, scrolling does not progress through the pages and will not allow you to scroll down for the next volume.

**To Reproduce**
1. Open a Manga/Comic/Webtoon
2. Click on the left-right arrows to change to continuous scroll and click the full screen button
3. Scroll down to the bottom of the page
4. Next volume won't be triggered

**Expected behavior**
When in continuous scroll/webtoon mode, scrolling to the top or bottom of a volume should load the previous or next volume respectively.

**Screenshots**
F11 Page Count
![F11 Page Count](https://user-images.githubusercontent.com/73398796/180381199-7b7e0070-8d22-4e42-8b68-e92ffad99cea.png)

UI Full Screen Page Count
![UI Full Screen Page Count](https://user-images.githubusercontent.com/73398796/180381213-768b5c61-deff-4e3c-b94b-e7769405e0e7.png)

Bottom with F11
![Scroll to Bottom F11](https://user-images.githubusercontent.com/73398796/180381200-c6f17d3f-2a7f-4a01-9520-b344d685c014.png)

Bottom with UI
![Scroll to Bottom UI Full Screen](https://user-images.githubusercontent.com/73398796/180381202-b5e89bb9-18e9-494f-bbf9-f66320facc5a.png)

Top with F11
![Scroll to Top F11](https://user-images.githubusercontent.com/73398796/180381204-b7664557-e1d7-4f6b-976c-2ded0574d5e6.png)

Top with UI
![Scroll to Top UI Full Screen](https://user-images.githubusercontent.com/73398796/180381211-c4fda878-046d-406c-ab52-ae3b3342fc0d.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 0.5.4.10

**Additional context**
If you full screen using "F11" rather than the built-in button in the UI, scrolling works correctly.
-- Kavita is running via Docker on a separate machine.

**Comment by majora2007** [comment]
After investigating, this is due to vertical offset not reporting the correct offset when manually in fullscreen, whereas the browser reports the correct (document.body). However, the fix is not so trivial that we can use document.body as that will break a lot of logic in the scroller code.
