### ISSUE TITLE
If a summary is too short to have the "Read More" button, it will not be blurred

### ISSUE THREAD

**Issue by TheIceCreamTroll** [Kareadita/Kavita#1397]
**Describe the bug**
If a summary is too short to have the "Read More" button, it will not be blurred

**To Reproduce**
1. Find a chapter with a short summary (1-2 sentences). It shouldn't be blurred.
2. Find a chapter with a long summary (paragraph or more). It should be blurred.

**Expected behavior**
Summaries should always be blurred

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox
 - Version 0.5.4.14

**Comment by majora2007** [comment]
Hmm i  think this is by design, because if there is no read more, then there is no way to unblur the summary.

**Comment by TheIceCreamTroll** [comment]
The info icon next to the `Blur Unread Summaries` option in user settings states that it blurs unread chapter / volume summaries to avoid spoilers, which does not reflect its current behavior (and is why I reported it as a bug). 

I think this feature would be worth re-implementing in a way that blurs all unread summaries, as blurring spoilers is a very useful function.
