### ISSUE TITLE
Covers get streched while resizing the browser window

### ISSUE THREAD

**Issue by TheIceCreamTroll** [Kareadita/Kavita#1398]
**Describe the bug**
Covers get stretched out while resizing the browser window.

**To Reproduce**
1. Slowly decrease and increase the width of your browser like in the video

**Expected behavior**
Cover images should maintain their aspect ratio at all times.

**Screenshots**
https://user-images.githubusercontent.com/33820904/183236733-1d97e7e2-c0c6-4e68-b75d-46206bc5b9e7.mp4

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox
 - Version 0.5.4.14

**Comment by majora2007** [comment]
Hmm, while this is technically a bug, I'm not sure about the solution. The image uses max width/height. We can't use width/height directly as then we need to code a lot of media queries and maintain them (and this uses a special component that handled image updates when sent from backend). 

I would say this is a low priority bug on the UI, but I'll put it in backlog and see if anyone wants to solve it creatively.
