### ISSUE TITLE
Active Library Indicator is innacurate

### ISSUE THREAD

**Issue by TheIceCreamTroll** [Kareadita/Kavita#1399]
**Describe the bug**
The green indicator on the left the the library name in the sidebar does not follow the active library. Only user-created libraries are affected. Clicking the same library twice will move the green indicator to the correct library.

**To Reproduce**
1. Click on a user-created library
2. Click on a different user-created library
3. The green vertical bar on the left of the library name should be attached to the wrong library

**Expected behavior**
The active library indicator should always follow the active library.

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox
 - Version 0.5.4.14

**Comment by majora2007** [comment]
I believe this is fixed now in v0.5.4.18. Would you mind re-validating for me?

**Comment by TheIceCreamTroll** [comment]
> I believe this is fixed now in v0.5.4.18. Would you mind re-validating for me?

Can confirm it was fixed in v0.5.4.18
