### ISSUE TITLE
When in settings, save button will activate when there are no changes to be made

### ISSUE THREAD

**Issue by TheIceCreamTroll** [Kareadita/Kavita#1402]
**Describe the bug**
Clicking on and off of any intractable in the admin and user settings dashboards will trigger the "Save" button to activate.

In addition to buttons:
- Directory paths for the Cache and Bookmarks under the Admin Dashboard

The "Save" button on the user password field wouldn't activate by just clicking on and off of it, but it will activate if there is _any_ text in both fields. They don't have to match, it will activate regardless.

What doesn't activate the "Save" button:
- The "Run" buttons on the Admin Tasks page.
- The background color picked under `User Dashboard > Preferences > Image Reader`

**To Reproduce**
1. Go to the Admin or User Dashboards, and enter a tab with a "Save" button
2. Click on an intractable.
3. Click on something else
4. The "Save" button should turn green

**Expected behavior**
The "Save" button should only activate if there are changes to save. For the password field, it should only be enabled if the passwords match.

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox
 - Version 0.5.4.14

**Comment by majora2007** [comment]
Would you want to take this up @TheIceCreamTroll? Seems pretty straightforward.

**Comment by TheIceCreamTroll** [comment]
> Would you want to take this up @TheIceCreamTroll? Seems pretty straightforward.

This is fixed in PR #1407 

The save button will still activate if you set, then unset a value without saving, but as we discussed in Discord, it would be too much effort for too little gain.
