### ISSUE TITLE
Jumpbar overshoots the target letter

### ISSUE THREAD

**Issue by TheIceCreamTroll** [Kareadita/Kavita#1404]
**Describe the bug**
When I select any letter to jump to, the location I end up is noticeably further down than I should be. Window size does not influence this.

**To Reproduce**
1. Go to a library with a large amount of content (I tested with 86 series)
2. Click on some letter in the jump bar
4. See the series at the top of the screen. They will not match the letter selected.

**Expected behavior**
When a letter is selected to be jumped to, the series that match should be at the top of the screen.

**Screenshots**
https://user-images.githubusercontent.com/33820904/183239405-407b7c62-7714-42a5-96d6-a06ca050987f.mp4

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox
 - Version 0.5.4.14

**Smartphone (please complete the following information):**
 - Device: iPad Pro (2018)
 - OS: iPadOS 15.5
 - Browser Safari
 - Version I don't think iPadOS shows Safari ver.

**Comment by majora2007** [comment]
I have validated this on my browser, but not as extreme as yours. I'll take a look.
