### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [Kareadita/Kavita#1406]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@vultza) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by majora2007** [comment]
Hello, I have added the Security.md. As per it, there is an email majora2007@users.noreply.github.com or you can reach out to me via Discord in our discord server.

**Comment by JamieSlome** [comment]
@majora2007 - thanks for your diligence 👍 

There are 6 reports in total, and we have already sent a few over to the e-mail address. Let me know if you haven't received or have any questions!

**Comment by majora2007** [comment]
@JamieSlome I have not received them, maybe that email doesn't work? Would you please use admin@kavitareader.com instead and I'll update the Security.md file later.
