### ISSUE TITLE
CBR/CBZ comics archives containing ._* files are considered unreadable

### ISSUE THREAD

**Issue by magujun** [Kareadita/Kavita#1409]
**Describe the bug:**
CBR/CBZ comics archives (possibly any type of archive) containing macOS metadata files (._*) are considered unreadable.

**To Reproduce:**
1. Load a new volume/chapter/issue archive containing ._* metadata files
2. Scan Library/Series
3. The card will show the default CANNOT READ image and the issue won't be readable
4. Error: "_There are no pages. Kavita was not able to read this archive._"

**Expected behavior:**
Metadata ._* files (including those inside archives) should be ignored, as per https://github.com/Kareadita/Kavita/pull/443.

**Screenshots:**

![image](https://user-images.githubusercontent.com/75567460/183328182-25ac5db9-29e5-4cd2-9e09-8cd5c5a6eaa3.png)

![image](https://user-images.githubusercontent.com/75567460/183331815-7f489e29-78a0-491d-8d80-7b2366f02cde.png)

**Desktop:**
 - OS: Docker build on macOS 12.5 amd64/arm64 (possibly all versions and architectures)
 - Browser: Safari/Chrome (possibly all browsers)
 - Version 0.5.3.22

**Additional context:**
To manually fix the error the user has to uncompress (or decompress) the archive, delete the ._* metadata files, and recreate/recompress the archive.

**Comment by majora2007** [comment]
I noticed the version you're on is less than the stable. Can you please update to v0.5.4.2 and please revalidate? I don't support non stable versions.

**Comment by magujun** [comment]
https://user-images.githubusercontent.com/75567460/185688581-f5892b35-0db2-4007-a875-81d0990d8c65.mp4

The issue still seems to be present on v0.5.4.21

**Comment by majora2007** [comment]
Okay, I do want to just note that v0.5.5 is the latest version.

**Comment by magujun** [comment]
You're going so fast! 😅
Don't worry, I'll update, rescan, and revalidate the issue...

**Comment by majora2007** [comment]
Validated and fixed, thanks for the report.
