### ISSUE TITLE
Can't log in after hotfix

### ISSUE THREAD

**Issue by lukaszliniewicz** [Kareadita/Kavita#1422]
Hi, 
after installing the hotfix update (the second one hasn't changed this), I can't log in to my server. The login page is displayed correctly, but when correct credentials are provided, nothing happens. Wrong credentials cause an error message to pop up. This happens on Chrome and Edge, and Firefox doesn't even display the login page correctly (just a black bar). The server is running on Linux Mint 20.2 (x64). 
This is the output in the terminal after I try to log in:
```

      Request starting HTTP/1.1 POST http://redacted/hubs/messages/negotiate?negotiateVersion=1 text/plain;charset=UTF-8 0
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[12]
      AuthenticationScheme: Bearer was challenged.
info: Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware[27]
      The response could not be cached for this request.
```

**Comment by majora2007** [comment]
Hi, I redacted your logs since it exposed your server url. 

Can you validate you're on v0.4.5.2? You can see in logs or in console window when you start your server manually.

**Comment by lukaszliniewicz** [comment]
Thank you. Yes, I was certainly on the newest release. For now I downgraded to 0.4.5 and things went back to normal.

**Comment by magujun** [comment]
I'm having the same issue and it seems to be related to loading external content (download-content) after login (css theme). 
If we already have a valid session with that file loaded on cache the dashboard will load. If not, we get a 401 Non Authorized on that request and are redirected to login.
Changing the database record for 'themeId' back to 1 (default internal Dark theme) the login works just fine.

**Comment by majora2007** [comment]
@magujun The custom theme is now fixed, it will be available on nightly soon.

**Comment by lukaszliniewicz** [comment]
Thanks!

**Comment by majora2007** [comment]
Can you confirm this is working for you on the latest?
