### ISSUE TITLE
Email systems issues

### ISSUE THREAD

**Issue by Maydeedvd** [Kareadita/Kavita#1433]
Hi.
Trying to invite users via email does nothing except error.. 

![Capture d’écran 2022-08-14 152438](https://user-images.githubusercontent.com/59835411/184539231-e8062605-dffb-4bd3-a81d-636f1e87ca0b.jpg)

All config is by default and test is good.
The system is Docker on Synology.

Note: Logs have been redacted due to personal information.

**Comment by majora2007** [comment]
Just leaving comment for myself, the email link was generated and in logs, but token was not accepted. Working with user via discord, will need them to test some docker builds as I can't reproduce issues.

**Comment by majora2007** [comment]
Confirmed with the user that using Nightly has fixed their issue.
