### ISSUE TITLE
Can't open PDF files with ſ in filename

### ISSUE THREAD

**Issue by Sanookmakmak** [Kareadita/Kavita#1435]
![Snipaste_2022-08-14_20-01-43](https://user-images.githubusercontent.com/24833757/184549230-808ed0e0-f317-443e-a518-4ed67c05950b.png)

**Comment by majora2007** [comment]
Before I start researching this, can you validate on any other symbols or umlauts from your language? Or at least provide a comma separated list for me, and I'll test each one.

**Comment by Sanookmakmak** [comment]
Yes, umlauts accents are working and those too: ¿ ± × ÷ © … ‰ ² ³

Not working:
₿, ⸘, ‽, ₭, ฿, ⁄, ∶, ≈, ≙, ≤, ⌀, ✓, ✝, ∞, №, ẞ, ſ, μ

Thai ที่รัก is also not working

**Comment by majora2007** [comment]
I have opened an issue on the underlying library we use, so it's up to them. I'll track this with next release.

**Comment by majora2007** [comment]
This is fixed in the nightly, so v0.5.5 you will get the fix.
