### ISSUE TITLE
Adding multiple new tags at once clears all new tags

### ISSUE THREAD

**Issue by StrangeOne101** [Kareadita/Kavita#1439]
## Description
When editing a series' information and adding new tags, adding multiple at once doesn't work. It seems to mostly be a clientside thing as they disappear from the UI window before you can hit save, so I don't believe they are sent to the server yet.

## To Reproduce
1. Go to a book.
2. Click the edit button
3. Go to Metadata
4. Add a new tag
5. Add another new tag. See both the current tag and the tag in step 4 be deleted from the UI window

## Expected behaviour
All tags are added and not cleared.

## Screenshots

![temp1](https://user-images.githubusercontent.com/2769013/184832421-88aa6d2c-8849-47a2-a945-aa62f75a8b31.PNG)
![temp2](https://user-images.githubusercontent.com/2769013/184832436-05b125c0-38f0-420d-a629-1b26c186b8e8.PNG)
![temp3](https://user-images.githubusercontent.com/2769013/184832438-bea4fab0-12c2-4dbd-94bf-321d0a3c44eb.PNG)
(These screenshots are NOT out of order)

## Desktop Environment
 - OS: Windows 10 
 - Browser: Chrome 104.0.5112.81 x64
 - Version: 0.5.4.2 x64

**Comment by majora2007** [comment]
This regression has appeared since v0.6.1
