### ISSUE TITLE
Comics parsing broken - everything parsed as Specials

### ISSUE THREAD

**Issue by git-Contributor** [Kareadita/Kavita#1441]
**Describe the bug**
Parsing of comic files seems to be broken/changed in 5.4.2 (but could happen several versions before, was not checking it for couple of weeks). But definitely was working 1-2+ months ago. Also it seems only comics are affected(?). For manga it seems to be ok.

The issue is that all comics are now listed under Specials tab only (it is only tab I have there). They are not anymore named as Volume X with the name under mouseover, but the name is directly there (see screenshot below). 

**To Reproduce**
Use any comics file and name it like Series name\Series Name v01 #&#x2060;001 - Volume Name - (year).cbr

Some examples: 
- Battlepug (2011)/Battlepug - v2 #&#x2060;002 - This Savage Bone - (2013).cbr  
- Folklords/Folklords - v1 #&#x2060;001 - (2020).cbr
- Nocterra/Nocterra - v1 #&#x2060;001-6 - Full Throttle Dark - (2021).cbz
- Rat Queens/Rat Queens - v6 #&#x2060;006 - The Infernal Path - (2019).cbr

Also the files mentioned above they are in Kavita shown as e.g. The Infernal Path, not as used to be as Volume 6 (and The Infernal Path used to show when mouseover the Volume 6).

**Expected behavior**
Show comics files correctly under Storyline, Volumes and Chapters and not everything under Specials, as it used to be in previous versions. 

**Screenshots**
![kavita_parsing](https://user-images.githubusercontent.com/91840689/184989993-43b6e33f-9900-4a9f-8422-192de92e3e6f.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Firefox 
 - Version: 5.4.2

**Additional context**
**Same naming** is used for **Manga** in separate Manga library. There is **no issue with it.**
Example (which works correctly, shows both as Volume 3 and under Chapters as chapters 18-26 :
-  One Piece/One Piece - v3 #&#x2060;018-26 - Don't Get Fooled Again - (2004).cbz
![kavita_manga](https://user-images.githubusercontent.com/91840689/184991345-a215d354-16bd-4fa5-a619-8dda41b059f4.png)

Note:
- Most of the comics has metadata from comictagger and the file name is then generated based on it (but the same apply to manga).

**Comment by tjarls** [comment]
In your example I see the Rat Queens Trade Paperbacks. Do they happen to have their metadata field set to `TPB` or `Trade Paper Back` or anything else?

**Comment by git-Contributor** [comment]
Yes, you are correct, have not noticed this change. Used Specials and SP01 for specials before. 

But I am not sure if TPB should be treated as a special, since TPB just groups couple of volumes/chapters together, but has nothing extra in it, so marking it as special will displace it in story. If kept as before even with mixed normal volumes and TPB it will still be placed correctly in the storyline. Currently it is sitting outside of it. Just to reconsider this :)

**Comment by git-Contributor** [comment]
But this issue itself can be clsoed :)

**Comment by majora2007** [comment]
I would ask you to raise your purposed change on our feature request site and we can let the community discuss this potential change.
