### ISSUE TITLE
Covers set on Collections no longer show

### ISSUE THREAD

**Issue by earth4s** [Kareadita/Kavita#1445]
**Describe the bug**
Covers that are set on Collections no longer display. This started after updating to 0.5.5

**To Reproduce**
1. Access Collections
2. Existing Collections show The Open Book image but not the Cover image
3. New Collections show a blank radial gradient image until the Cover image is set. Then the Cover changes to the Open Book image.

**Expected behavior**
When setting a cover Image the Collections should update with the image.

**Screenshots**
Collections after updating to 0.5.5
![Screenshot 1](https://user-images.githubusercontent.com/9957002/185271779-e2f68d00-dcee-4dc9-b393-a91a01ca644d.png)
After Creating a new collection
![Screenshot 2](https://user-images.githubusercontent.com/9957002/185271788-15ccd8b3-41b6-429b-9e1e-55e314eceafc.png)
Cover set on Collection
![Screenshot 3](https://user-images.githubusercontent.com/9957002/185271795-3d0b012c-f002-43c7-98d0-520b14bc3e29.png)
Cover show in Collection
![Screenshot 4](https://user-images.githubusercontent.com/9957002/185271887-282ad94f-a61a-4158-bc72-a120bc3e8883.png)
Cover not shown in main Collections page
![Screenshot 5](https://user-images.githubusercontent.com/9957002/185271902-744f54b7-5f96-4cc4-9591-e002a96b51b3.png)

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Browser: Chrome and Firefox
 - Version: 0.5.5

**Additional context**
When I accessed Collections on Chrome none of the Covers I set showed up when on the main Collections Page. At first I though this was related to the issues with Chrome not updating covers correctly. So I switched to Firefox and had the same results. Whats interesting is when you edit a collection the image will show up in the Covers page. It will also show up when you click on the Collection to see its contents.

**Comment by ForkboyInk** [comment]
Came to report the same thing. Attempted to verify (as per this comment: _"Changing cover images on Chromium-based browsers will not reflect. This is due to Chromium not respecting the Cache-Control header (spec) and hence requires a hard refresh from the user._") nut does not register even after a hard refresh, does not refresh even if removed and reapplied in non-chromium based browser w/ hard fresh from user (i.e. Firefox) nor a cleaned cache through browser tools.

**Comment by majora2007** [comment]
This actually came up last release, but because no github issue was created I forgot about it. I have fixed it and it will be out on next stable.
