### ISSUE TITLE
Not visible "Apply", "Reset" buttons

### ISSUE THREAD

**Issue by zsuatem** [Kareadita/Kavita#1453]
**Describe the bug**
The "Apply" and "Reset" buttons on the last line are not visible

![image](https://user-images.githubusercontent.com/17302628/185759181-6ef48d25-d508-4e5c-a048-17e8f570f910.png)
![image](https://user-images.githubusercontent.com/17302628/185759246-3d45b874-ca25-4807-9836-bdfc6fb7a649.png)
![image](https://user-images.githubusercontent.com/17302628/185759277-7c1e8e0f-5042-47eb-a9ed-1ea4c37aa490.png)
![image](https://user-images.githubusercontent.com/17302628/185759473-d8c50bc8-d516-451f-b19d-e12cb60f8361.png)

**To Reproduce**
1. Go to some book
2. Click on the three dots -> "Details" -> "Cover"
3. Scroll down to the end

**Expected behavior**
Buttons should be visible.
Example
![image](https://user-images.githubusercontent.com/17302628/185759500-5535261d-a58f-483a-bdcd-7492e624cba9.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Edge v104, Chrome v104
 - Version: 0.5.5.1

**Comment by majora2007** [comment]
Can you provide dimensions of your screen? This type of issue usually happens due to dev tools being open, so likely something dimension related.
