### ISSUE TITLE
Comic Issue #0 Not In Issues Tab

### ISSUE THREAD

**Issue by maniccomputer** [Kareadita/Kavita#1454]
**Describe the bug**
When a comic volume includes an issue #0, the comic is not included in the Issues tab. It is included in the volume for the Storyline and Volumes tab. The issue does not show in the Specials tab, though likely expected behavior. If the metadata for Format is changed to "Special" the issue will show in the Specials tab and not in the Storyline or Issues tab (again likely expected behavior).

**To Reproduce**
1. Go to any comic that includes an issue 0.
2. Click on the Storyline tab or Issues tab.
3. Tap the '...' and then the Info button. 
4. See issue 0 in the list.
5. Click on the Issues tab.
6. Scroll through issues and issue 0 will not be present.

**Expected behavior**
Issue #0 should show in the Issues tab if format is not marked as "Special" in the metadata.

**Screenshots**

File structure:
![image](https://user-images.githubusercontent.com/10536330/185760882-88a26a94-5661-4810-97bb-8d79d5dcca1e.png)

Metadata (none):
![image](https://user-images.githubusercontent.com/10536330/185760909-631fd570-3d1f-4c63-9b42-4d2ce0e0ba39.png)

Storyline tab:
![image](https://user-images.githubusercontent.com/10536330/185760927-fbc02690-642e-4b1d-a322-45864dc652d3.png)

Volumes tab:
![image](https://user-images.githubusercontent.com/10536330/185760940-2bcedcb4-10a3-4a74-a06e-a04bfc577526.png)

Issues tab (no issue 0):
![image](https://user-images.githubusercontent.com/10536330/185760952-3bf4f826-3214-4e80-ba5a-c6da78d5868b.png)

Specials tab (no issue 0):
![image](https://user-images.githubusercontent.com/10536330/185760967-0798708e-d35d-4ba7-bbec-49e81c173bd0.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Chrome
 - Version 0.5.5.1

**Additional context**
Ideally Issue #0 would not be the first issue in a Volume or Storyline if the date of that issue is not first. This also creates a slight conflict with cover art for the issue being that of the cover for issue 0 instead of the 1st issue in the series. This seems more like a feature request than a bug. It is also possible that issue 0 should automatically be considered a special without needing the "sp" tag in the file name or "special" format in the metadata.

**Comment by maniccomputer** [comment]
Workaround for this issue is add the Format metadata tag "Special". This ensures the issue is available at least in the Specials tab.

**Screenshots AFTER updating metadata**

Updated metadata:
![image](https://user-images.githubusercontent.com/10536330/185762383-90b77943-079f-460c-b0f8-a70dfe3de690.png)


Volumes (Issue 0 no longer in the Info section and you can see the cover was removed):
![image](https://user-images.githubusercontent.com/10536330/185762397-5d52ae90-449d-40b1-a04c-e596079afefe.png)

Specials (Issue 0 added to Specials tab):
![image](https://user-images.githubusercontent.com/10536330/185762405-d3f3a12e-0a03-4217-b5f6-84a22968637b.png)

**Comment by majora2007** [comment]
Issue #0 or Volume #0 is not supported in Kavita. This is a special number reserved for Specials. An oversight in development due to lack of understanding in the Comic scene and too ingrained to change. You can use 0.1 as a workaround.
