### ISSUE TITLE
Titles with numbers in it gets cut before the number

### ISSUE THREAD

**Issue by ShuuGoya** [Kareadita/Kavita#1457]
Series Title with a number in it for example "Kou 1 Desu Ga Isekai De Joushu Hajimemashita" or "Saving 80000 Gold Coins In The Different World For My Old Age" gets cut after the number to "Kou" and "Saving" after scan.

I use the windows version of the build and open it in chrome.

![Bug](https://user-images.githubusercontent.com/110826791/185808722-1b6e0e98-a6c6-40d9-9567-8f5f5c7830da.JPG)

**Comment by majora2007** [comment]
This unfortunately is a known limitation of parsing filenames, as the Parse can't tell the difference between `Cyberpunk 2077`, `Saving 80000 Gold Coins In The Different World For My Old Age`, and `Batman 2`, where Batman is the series and 2 is the issue or chapter (which is a more common case). 

You're best bet is to ensure you have chapter or volume markers in your filenames or use embedded metadata to force the series title.
