### ISSUE TITLE
Accessing Kavita 0.5.5.1 using safari from iPad Air (1st Generation released 2013)  iOS 12.5.5 returns blank page

### ISSUE THREAD

**Issue by leocordis27** [Kareadita/Kavita#1458]
**Describe the bug**
Accessing Kavita using safari from iPad Air (1st Generation released 2013)  iOS 12.5.5 returns blank page.
I use Portainer to auto update Kavita. My iPad can still display Kavita until the last version (0.5.4.2) but since the 0.5.5 update, it only show white blank screen. I can still access Kavita using desktop or iPhone 11.

**Expected behavior**
Opening Kavita using my iPad will show login screen or library screen as usual

**Smartphone (please complete the following information):**
 - Device: iPad Air 1st Generation (released 2013)
 - OS: 12.5.5
 - Browser Safari
 - Version

**Comment by makmillion** [comment]
I faced this same issue with my iPad mini 2 running iPadOS 12.5.5 (Safari 12.1.2).
The same iPad works with Komga, but Kavita is much lighter and very much preferred, so I'm very happy this made the to-do list.

**Comment by majora2007** [comment]
Could someone on this ticket please open dev tools (usually right click in the browser and inspect) and see if any errors are coming up in the console?

**Comment by majora2007** [comment]
@leocordis27 I suppose your iPad, which is much harder. I'm not sure on Mac, but on my FF with Android, I can debug over USB. I don't have any iOS devices, so I need to rely on you guys in order to solve this issue. 

I checked on my side and I don't see anything about Angular 14 dropping support or any posts about this issue. 

@therobbiedavis Do you have an old version of Safari that we can test on or any insight?

**Comment by majora2007** [comment]
I think I have a path forward. This is due to us changing to ES2020 which has features that aren't supported on these old browsers.

**Comment by leocordis27** [comment]
> I think I have a path forward. This is due to us changing to ES2020 which has features that aren't supported on these old browsers. 

Hopefully the next update will fix it. 😄

**Comment by majora2007** [comment]
This was validated as working. So next release you will get your fix.

**Comment by thacmpunk17** [comment]
I’m getting the same issue with my iPad 6th gen on version 14.0. Just a blank screen on both safari and chrome. I completely reset my device and it’s still happening.

**Comment by Svenito** [comment]
Also seeing this on iPad Air 2 iOS 15.8.3 using safari or Firefox

**Comment by majora2007** [comment]
Can anyone here try our demo-next instance and let me know if the page loads? 
https://demo-next.kavitareader.com/

In the currently nightly, the restrictions around browsers was loosened significantly.

**Comment by Svenito** [comment]
Doesn’t load for me on iOS 15.8.3. But understandable, this is an old device. Thanks for the response though

**Comment by sdepool** [comment]
same issue

**Comment by sdepool** [comment]
> Also seeing this on iPad Air 2 iOS 15.8.3 using safari or Firefox

same issue
