### ISSUE TITLE
Series are not deleted when having a relationship with another.

### ISSUE THREAD

**Issue by ocgineer** [Kareadita/Kavita#1462]
**Describe the bug**

A series in not being deleted when it still has a relationship with another series, such as being the parent or having a sequel set.
Having another series pointing to the series you want to delete as prequel/sequel does allow you to delete.

**To Reproduce**
1: Have two series.
2: Set in the series to-be-deleted a relationship to the second (e.g. sequel).
3: Try to delete the series you just adjusted.
4: Observe the green "Series Deleted" info-box, but it failed. 
     logs will show 'FOREIGN KEY constraint failed'
     
5: remove the relationship
6: Try deleting the series again
7: Observe the deletion is successful.
  
**Expected behavior**
The series can be deleted regardless of the set relationships or give an error stating these need to be deleted prior.
However, having to manually do this will also cause the scan not be able to delete series if they are removed on filesystem.

**Docker**
on Unraid, both current stable 0.5.5.1 (and 1 version before that) and nightly 0.5.5.7.

**Additional context**

I believe this is due to the database table `SeriesRelation` which has a FORGEIGN KEY constraint linked to to the `Series` table. as deleting a series seem to only delete prior chapters, volumes and then tries to delete the series (according to what I saw in the logs), the constraint from SeriesRelation is thrown. There is no ON DELETE CASCADE on this key either to have the row deleted automatically, so Kavita/User needs to remove the relationship first.

**Comment by majora2007** [comment]
I'm moving this to the next release as I'm not having much luck getting support externally on the fix. I will note this as a known issue in the release.

**Comment by majora2007** [comment]
For me later:
https://stackoverflow.com/questions/73568815/altering-ef-core-schema-ondelete-not-working-constriant-issue
https://www.reddit.com/r/dotnet/comments/wvwumv/need_help_altering_schema_ondelete/
