### ISSUE TITLE
Existing series exception

### ISSUE THREAD

**Issue by therobbiedavis** [Kareadita/Kavita#1466]
**Describe the bug**
Getting error from UI on scan. `There was an exception finding existing series for Head Lopper with localized name of for library 1`

**To Reproduce**
1. Create new db and add a library
2. Have multiple comics with the same series name in the multiple folders
3. Scan

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/7907265/186182282-c5e6f0f1-378c-4c1a-ab96-f3563c8dfe4e.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser All
 - Version 0.5.5.7

**Additional context**
Folder Structure:
![image](https://user-images.githubusercontent.com/7907265/186182783-1e4a2468-e877-4a30-9d4b-e6e72101e944.png)
![image](https://user-images.githubusercontent.com/7907265/186182883-1bc726dd-3903-4443-a8f2-3bd7826bb880.png)
![image](https://user-images.githubusercontent.com/7907265/186183030-2d1d0da7-f8a8-4423-89bb-9d8530e0f9d3.png)
![image](https://user-images.githubusercontent.com/7907265/186183149-c8f4e44b-1928-4949-92a9-b9440a250788.png)
![image](https://user-images.githubusercontent.com/7907265/186183303-287052a8-c8a0-4a6c-a1bf-b93df2c9abf0.png)

**Comment by Sulframus** [comment]
Same issue both on 0.5.5.7 and 0.5.5.9 docker for light novels - category in kavita "Books"

Root library is /mnt/user/data/media/Books/Light Novels/
![image](https://user-images.githubusercontent.com/50105122/186238396-f1d4b1d1-f74d-4836-8a21-495ce5ef0058.png)
![image](https://user-images.githubusercontent.com/50105122/186238418-aedaed9b-fb0e-4fec-8c9e-896490cabb0d.png)
![image](https://user-images.githubusercontent.com/50105122/186238478-dd9e35b7-97fc-422a-a615-d4461465a9cc.png)

**Comment by majora2007** [comment]
Okay I was able to reproduce on my local with Ashita Dorobou on a new library. 

However, the real issue is:
```
 System.ObjectDisposedException: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same conte
xt instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection c
ontainer take care of disposing context instances
Object name: 'DataContext'
```

**Comment by majora2007** [comment]
This has been solved. Note to self: Validate all cases of RollbackAsync()
