### ISSUE TITLE
Name and localized name being read from filename instead of metadata

### ISSUE THREAD

**Issue by Sulframus** [Kareadita/Kavita#1468]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
Name and localized name are setup by filename in Kavita instead of using metadata from epub.

**To Reproduce**
1. Have file named "Quantum Devil Saga - Avatar Tuner - Volume 01 [Bento Books][Google Play].epub"
2. Have metadata as per screenshot below
3. Scan in Kavita

**Expected behavior**
Name and localized name should be set from metadata as it exists

**Screenshots**
![image](https://user-images.githubusercontent.com/50105122/186239383-805202a5-4604-4f5f-9b20-8615dc70717c.png)
![image](https://user-images.githubusercontent.com/50105122/186239410-73d5797c-a557-4fef-9d7f-466a3d2e3931.png)
![image](https://user-images.githubusercontent.com/50105122/186239433-27146ffd-4284-471e-8f0f-50fdc5f6fa73.png)
![image](https://user-images.githubusercontent.com/50105122/186239466-2a674f5f-22d3-4dc5-8477-f13c013be91c.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Brave
 - Version 0.5.5.9

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majora2007** [comment]
I looked into this and this file has invalid metadata. The issue is you have `calibre:title_sort` defined, but are missing `calibre:series` as well, which is necessary so Kavita doesn't fallback to filename parsing. This leads Kavita to use `dc:title` for both Series and Title.
