### ISSUE TITLE
Collection deletion prompt doesn't grey out background

### ISSUE THREAD

**Issue by TheIceCreamTroll** [Kareadita/Kavita#1469]
**Describe the bug**
Background doesn't grey out when deleting a collection. Another fun z-index issue.

**To Reproduce**
1. Go through the steps to delete a collection until you reach the confirmation prompt

**Expected behavior**
The background should grey out

**Screenshots**
![delete_cover_image](https://user-images.githubusercontent.com/33820904/186258145-86ec048d-84ac-42e8-b851-e71d76d970ed.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox
 - Version 0.5.5.8

**Comment by majora2007** [comment]
This is not an issue. This is because this is a confirm, which is not a modal.

**Comment by TheIceCreamTroll** [comment]
> This is not an issue. This is because this is a confirm, which is not a modal.

Looks like it's a regression from the old behavior though, and makes the confirm popup blend into the "Edit Collection" menu

How it used to look:
![kavita_Collections_Delete](https://user-images.githubusercontent.com/33820904/186752918-f27de72e-c76b-4182-8ebe-8c364fcb8905.jpg)
