### ISSUE TITLE
Two series with same name but a special character difference issue

### ISSUE THREAD

**Issue by ocgineer** [Kareadita/Kavita#1472]
**Describe the bug**
Series that are nearly identical in filename but have a small difference in the form of a special character such as an !, will have an issue where the two series are merged together due to normalizing the series name.

Current issue with the series `Doubt` and `Doubt!!`

- https://myanimelist.net/manga/5293/Doubt
- https://myanimelist.net/manga/884/Doubt

(There is even a series called `Doubt!` but didn't got an official translation).

**To Reproduce**
1. Add a series called `Doubt`
2. Add a series called `Doubt!!`
3. Scan the library
4. Observe merging/adding issue.

```
root
|- Doubt
|    |- Doubt v01 (2014) (Digital) (Uasaha).cbz
|    |- Doubt v02 (2014) (Digital) (Uasaha).cbz
|
|- Doubt!!
     |- Doubt!! v01 (2005) (Digital) (rocky93).cbz
     |- ...
     |- Doubt!! v06 (2005) (Digital) (rocky93).cbz
```
    
On current stable (old scan loop):
> Sets the series name as Doubt!! and shows the 6 volumes correctly, but merged the 2 books from series Doubt into first 2 books of Doubt!! so no series for that is created.

On current nightly (new scan loop):
> Sets the series as Doubt but shows the 6 volumes from Doubt!!. It does not show the books from Doubt anywhere, not do i get duplicate errors/logs.

**Expected behavior**
The two series will individually be added to the library with the correct name.

**Additional context**
As a (temporary) solution one can add the artist to the filename `Doubt {Yoshiki Tonogai}` this will cause both series be added and `Doubt!!` is then also named correctly again (with the new scan loop).

I did *NOT* test this with the series name set in ComicInfo.xml so the behavior might be different then.

**Comment by majora2007** [comment]
I am investigating this. This type of change requires a large migration to be run, which for such critical code, is extremely expensive.
