### ISSUE TITLE
Double Page Layout not always correct

### ISSUE THREAD

**Issue by lifegpc** [Kareadita/Kavita#1476]
**Describe the bug**
The `Double (Manga)` layout mode cause some issues.

**To Reproduce**
1. Open the manga in viewer. ([Example file](https://1drv.ms/u/s!Aoq8mAMlVv8UwRiTWG0QFuJId8Dl?e=kHKh1l) Password: `rnkbHwruJd1NdTQE/gWVCA==`)
2. Click on Settings.
3. Switch Layout Mode to `Double (Manga)`
4. Page 6 and Page 7 are not in the same view.

**Expected behavior**
Page 6 and Page 7 in the same view.

**Screenshots**
Kavita:
![image](https://user-images.githubusercontent.com/41434272/186633258-edcffa35-cb60-4109-be69-2b385525bad7.png)

Example in Okular (With `Facing Pages (Center First Page)` View Mode and enable `Right to left reading direction` in settings,):
![image](https://user-images.githubusercontent.com/41434272/186632439-9f133954-3200-43df-afeb-9dd33521b03c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 104.0.5112.102

**Additional context**
Maybe add another layout mode just like Okular do.

**Comment by majora2007** [comment]
I have validated this is indeed a bug. Very interesting that it only occurs on page 6. Likely an issue with prefetching.

**Comment by majora2007** [comment]
Okay I have fixed this issue, but do note, it will not mimic your program. Kavita has some logic and rules around when to double pages up and when not to. In our case, the 2nd page is shown as a single as it follow the cover.
