### ISSUE TITLE
Jumpbar not anchored correctly in a collection

### ISSUE THREAD

**Issue by ocgineer** [Kareadita/Kavita#1482]
**Describe the bug**
The navigation letter bar on the right of the screen does not seem to be anchored correctly to the edge of the view space when browsing inside the collection on a mobile device (iOS in my case). The scrollbar/position is also on the right of it, instead left like when browsing a library. This will cause the letter bar to scroll away.

**To Reproduce**
1. Have a larger collection so that you would need to scroll.
2. Open the collection and start scrolling
3. Observe the letter bar not having a fixed position.

**Expected behavior**
Like anywhere else that the letter bar is anchored properly to the right edge of the view and does not scroll away.

**Screenshots**
![kavita_collection_letter_bar](https://user-images.githubusercontent.com/12483966/186902949-ed60d8b8-6192-453d-a599-3fc659336e00.jpg)
The above is the incorrect anchoring of the letter bar inside a collection view.

![kavita_library_letter_bar](https://user-images.githubusercontent.com/12483966/186903046-789c13c8-7d5d-4795-a03c-49ece495ee8a.jpg)
The above is the correct anchoring of the letter bar inside the library view.

**Smartphone (please complete the following information):**
 - OS: Docker
 - Browser iOS 15.6.1 iPhone 11 
 - Version 0.5.5.1 (stable) and 0.5.5.15 (nightly)

**Comment by ocgineer** [comment]
Update; it actually also happens in the browser on a computer.

![image](https://user-images.githubusercontent.com/12483966/187015796-ff6ea705-af44-401c-b83e-8cd51ef40e06.png)

**Comment by majora2007** [comment]
Hmm, this is a problem but without an easy solution. I need to have a parent to scroll on. If I don't have it on the page and on the scrolling area, then this page will have a double scrollbar, but then the jumpbar doesn't feel right as it scrolls down. I'll put this in the backlog while I think of a good solution.

**Comment by therobbiedavis** [comment]
@majora2007 I think this has been fixed, has it not?

**Comment by majora2007** [comment]
Yeah it has
