### ISSUE TITLE
Allow Series cover selection to see all covers from Volumes

### ISSUE THREAD

**Issue by Sulframus** [Kareadita/Kavita#1483]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
The cover for the series gets selected from Specials instead of Books

**To Reproduce**
1. Have a book library
2. Have series with both a standard volume and a special
3. When series get scanned, cover will be used from specials

**Expected behavior**
Cover will be selected from standard volume

**Screenshots**
![image](https://user-images.githubusercontent.com/50105122/186978965-c24ea923-eb9c-4dd2-9852-2b89774481b1.png)
![image](https://user-images.githubusercontent.com/50105122/186978981-f85c1cc1-6c7d-41a7-b2d5-4a9d0fb5a2ab.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Brave
 - Version: 0.5.5.15

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majora2007** [comment]
This is actually how Book libraries work by default as usually Books are treated as special. I need to think about how to handle an enhancement like this.

**Comment by Salindris** [comment]
Would it be possible to offer all covers in this series and you just choose the one you like? That way there doesn't have to be any special code for determining which cover to use and the covers of the individual volumes are in the DB anyway.
When you go to the cover setting where you can upload a file, there would be the volume covers and you just select one like you can after uploading.

**Comment by ocgineer** [comment]
Interesting enough, for me, the summary is from volume 1 (index 1) and it seems the tags (and cover) are from series index 0.

![image](https://user-images.githubusercontent.com/12483966/191882653-430636a5-17ba-42f8-8129-0d7902f3098b.png)

**Comment by majora2007** [comment]
I thought I've already implemented this cover selection code so you can switch it to any in the series, while keeping the original cover logic, but it looks like I only had extended that to volume and collections, so I'll ensure series cover selection gets the same treatment.
