### ISSUE TITLE
Cannot open files with "№" in title

### ISSUE THREAD

**Issue by TheRonGDD** [Kareadita/Kavita#1489]
Name file with №01 or № anything in the title.

**Comment by majora2007** [comment]
Hi, please use the template appropriately to help me reproduce.

**Comment by TheRonGDD** [comment]
**Describe the bug**
Files with № in filename will not open in Kavita

**To Reproduce**
Steps to reproduce the behavior:
1. Go have file with № in the filename
2. Scrape library
3. Try to open file for reading in Kavita
4. See error


**Expected behavior**
File would be readable


**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Browser: Edge, Chrome, Firefox
 - Version: 0.5.5.0

![Capture2](https://user-images.githubusercontent.com/19981887/187230081-cb36bab7-1ec0-4b8b-bf2c-cb796f28d90f.JPG)

**Comment by majora2007** [comment]
This issue is either already fixed in the nightly (aka coming next stable) or an issue with your file not being supported. I just tested and I was able to open and read. 

You can try on a new zip, but if it doesn't work, then consider a fix coming on the next stable.
