### ISSUE TITLE
Unable to change/save any settings in User Dashboard>Preferences

### ISSUE THREAD

**Issue by doasfan** [Kareadita/Kavita#1494]
Version 0.5.5.1, Docker
Logged in as an admin via either Chrome on Win10, or Safari on iPadOS.

From the upper right username dropdown>Settings>Preferences>
For example: I'm unable to change any settings and get them to stick. Toggling Image Reader>Scaling Options>from "Automatic" to "Fit to Height". The "SAVE" button lights up green. I click SAVE, which highlights SAVE. I click away to the HOME button, then back in to check and Scaling Options is back to Automatic. Same with all the other dropdowns and toggles under preferences.

**Comment by doasfan** [comment]
No, nothing popping up in the browser. BTW, Chrome 104.0.5112.102.

![kavita-after-clicking-save](https://user-images.githubusercontent.com/9890160/187966180-57f94abe-7f60-417d-ab9e-941463733b08.PNG)
![kavita-after-toggling](https://user-images.githubusercontent.com/9890160/187966182-c1e5ab00-8517-45fb-bcb3-f36a1d5b9090.PNG)
![kavita-before-changes](https://user-images.githubusercontent.com/9890160/187966184-375fcbf9-2256-446f-9cac-af4e0d8b07db.PNG)

**Comment by majora2007** [comment]
Hmm this implies the button isn't actually clicking or being registered as clicked. I have a stable release coming within a day or two and we've already ran through this flow as successful, so please wait until then (v0.5.6) and report back if this is still an issue.

**Comment by doasfan** [comment]
Will do. FYI, same behavior on Microsoft Edge and on Chrome on iPhone IOS 15.6.1.

**Comment by doasfan** [comment]
Upgraded to v0.5.6, still no toaster popups when toggling settings then clicking SAVE within Chrome in User Preferences. Haven't tried other browsers.

Worth mentioning that toaster popups work in the Admin Dashboard menus to confirm SAVE there.

**Comment by majora2007** [comment]
Hmm I can't reproduce this. My only thought is maybe there is an error that's being recorded in the logs. Could you clear your logs, run the flow, then send me your log file? 

When did you first install Kavita (version number)? Maybe some migration issue is messing the save up.

**Comment by jvonhoff** [comment]
Not OP, but I am affected by this bug.  I noticed this (on Firefox) in the console when I click Save:
```
ERROR 
Array [ "The Theme field is required." ]
core.mjs:7630:22
    Angular 2
    RxJS 6
    Angular 20
    RxJS 16
    Angular 16
    RxJS 22

```
My logs are here:
https://gist.github.com/jvonhoff/032aaf100974d789b95734f116500a4b

I also went over to the Theme tab, which only has the default "Dark" theme.  The only enabled button was Scan, so I clicked that, and once it scanned, it came back and acted the same way, so it seems that there's nothing to fix it on that tab page.

**Comment by majora2007** [comment]
@jvonhoff This is what I needed to deduce the issue. The issue is in fact a migration issue, where your user accounts are missing an entry to the Theme. 

The way to fix this would be to add a blank css file (name it bg-dummy) in your themes directory, scan, apply that, then delete it and rescan, to get back onto the default Dark theme. 

Otherwise, you can wait for me to fix the issue and release it on v0.6.0 (or nightly if you are nightly users).

**Comment by jvonhoff** [comment]
> The way to fix this would be to add a blank css file (name it bg-dummy) in your themes directory, scan, apply that, then delete it and rescan, to get back onto the default Dark theme.

I can confirm that this works.  I'm able to save my prefs now.  Thanks!

**Comment by ghost** [comment]
I have this issue again, version 0.81, browser: edge，System: Android 10

**Comment by ghost** [comment]
I show saved, but the book background color has not changed.
