### ISSUE TITLE
Cover does not scale properly on 2K/QHD monitor

### ISSUE THREAD

**Issue by tanpro260196** [Kareadita/Kavita#1505]
**Describe the bug**
The main cover in the series details page does not scale properly in 2K/QHD monitor
![image](https://user-images.githubusercontent.com/12226439/188255340-0fb0da48-32f2-44c3-b747-794a3ec473ec.png)

**To Reproduce**
1. Go to the details page of any series (tested with books and manga so far)
2. The main cover is way too big.

**Expected behavior**
![image](https://user-images.githubusercontent.com/12226439/188255395-77a0d380-4b82-4243-b302-628b3b885c7e.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Version: 0.5.6.2

**Comment by TheIceCreamTroll** [comment]
Caused by #1498
