### ISSUE TITLE
Please add support for Russian

### ISSUE THREAD

**Issue by lopatkarise** [Kareadita/Kavita#1508]
In russian, we use "Том n" combination to stand Vol. n and "Глава n" for chapter. 
Том n -> Volume n
Тома n-n -> Volume n-n (multiple volumes in one file)
Том n-n -> Volume n-n
n том -> n volume (volume numbers at front and back are both grammaticly correct)
Глава n -> Chapter n
n глава -> n chapter (same situation as with volume)
Главы n-n -> Chapter n-n
Глава n-n -> Chapter n-n

as for test case
Kebab Том 1 Глава 1.pdf
Манга Том 3 Глава 1.pdf
Девушка на час Том 76 Глава 4.pdf
Реинкарнация Том 1 Глава 1.pdf
something Том 123.cbz
something else Том 132 Глава 92.zip

**Comment by majora2007** [comment]
Would these keywords also apply to Comics? Is there a word for Issue in Russian?

**Comment by majora2007** [comment]
Also would this be a valid case? Манга Том 1 2 Глава.cbz -> Манга Volume 1 Chapter 2
