### ISSUE TITLE
Problem with Metada (Again) V3

### ISSUE THREAD

**Issue by Rougecarlos** [Kareadita/Kavita#1510]
Hi with the new version Kavita 0.5.6, in spanish when i scan the library have a lot of FAIL like this:
 
> fail: API.Services.Tasks.Scanner.ProcessSeries[0]
      There was some issue when updating chapter's metadata
      System.FormatException: String '10/19/2021' was not recognized as a valid DateTime.
         at API.Services.Tasks.Scanner.ProcessSeries.UpdateChapterFromComicInfo(Chapter chapter, ComicInfo info) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\ProcessSeries.cs:line 0

When in windows i put regional format in English (EEUU) this issue not show and metadata are well

Maybe for this in spanish some metadata is not showed, in USA the time is set to MONTH/DAY/YEAR but in spain by default is DAY/MONTH/YEAR.

The previus issue #1411 

Pd: other thing i was find but not know if is a bug, if in library you select a folder with only the epubs inside it is not recognised, but if you put it in a folder work well

**Comment by ThePromidius** [comment]
> USA the time is set to MONTH/DAY/YEAR but in spain by default is DAY/MONTH/YEAR.

That seems to be the case. 
Seems hardcoded.
```cs
        if (comicInfo.Year > 0)
        {
            var day = Math.Max(comicInfo.Day, 1);
            var month = Math.Max(comicInfo.Month, 1);
            chapter.ReleaseDate = DateTime.Parse($"{month}/{day}/{comicInfo.Year}");
        }
```

**Comment by tjarls** [comment]
I just took a look at the code and it's definitely a bug. It's also a suboptimal convulated way to setting a date.
