### ISSUE TITLE
Quick menu (?) will not auto-close, manual close, all menu buttons become unresponsive.

### ISSUE THREAD

**Issue by makmillion** [Kareadita/Kavita#1516]
**Describe the bug**
While reading any cbz/cbr, regardless of if it is set to Manga or Comic, the in-reader menu will not close once it has been opened. If the "auto-close menu" option has been selected the buttons become unresponsive after some time, and the menu remains open, leaving the browser back-button the only option to escape the comic.

**To Reproduce**
Open a cbz/cbr file using Safari and expand the lower menu. The menu remains open and cannot be closed. All buttons in the upper and lower menu become unresponsive after some time.

**Expected behavior**
The menu should open and auto-close with the appropriate option selected, or manually closed by selecting the full-screen button or tapping the center of the screen.

**Smartphone (please complete the following information):**
 - Device: iPad Mini 2
 - OS: iOS 12.5.5
 - Browser: Safari 12.1.2
 - Version: 0.5.6
 
 **Notes**
I resolved this by enabling "Web Animations" in Settings/Safari/Experimental Features/(toggle: ON) and restarting Safari.
Assuming this is a Safari issue and not a bug, could we add this information added to the Wiki?

**Comment by ocgineer** [comment]
This is a known issue, due to Angular not supporting older iOS devices with the animations. Did not know the experimental feature resolves the issue though! Did confirm that this actually solves the f.animation() not found issues and that the menu can be closed.

If my pull request is not accepted we can use that as alternative for older devices, but the pr can also solve issues on other (than iOS) devices that do not have this experimental feature.

#1504

**Comment by leocordis27** [comment]
> **Describe the bug** While reading any cbz/cbr, regardless of if it is set to Manga or Comic, the in-reader menu will not close once it has been opened. If the "auto-close menu" option has been selected the buttons become unresponsive after some time, and the menu remains open, leaving the browser back-button the only option to escape the comic.
> 
> **To Reproduce** Open a cbz/cbr file using Safari and expand the lower menu. The menu remains open and cannot be closed. All buttons in the upper and lower menu become unresponsive after some time.
> 
> **Expected behavior** The menu should open and auto-close with the appropriate option selected, or manually closed by selecting the full-screen button or tapping the center of the screen.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: iPad Mini 2
> * OS: iOS 12.5.5
> * Browser: Safari 12.1.2
> * Version: 0.5.6
> 
> **Notes** I resolved this by enabling "Web Animations" in Settings/Safari/Experimental Features/(toggle: ON) and restarting Safari. Assuming this is a Safari issue and not a bug, could we add this information added to the Wiki?

Yes I also have the same issue browsing via safari with my iPad Air 1st Generation (released 2013) OS 12.5.5. I usually just refresh the page to make the menu disappear.

**Comment by ocgineer** [comment]
It is any iOS that is running below 14.
