### ISSUE TITLE
Zip files in root folder not being parsed/opened

### ISSUE THREAD

**Issue by NepBlanc** [Kareadita/Kavita#1518]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
all files that are in the root folder of a library are not being scanned or opened which is annoying as these are a folder but then compressed most of the times.

**To Reproduce**
1 download files in root folder that are in zip file and not a subfolder
2 scan the library
3 books/manga does not show up

**Expected behavior**
books/manga shows up

**Desktop (please complete the following information):**
 - OS: Docker on Ubuntu 22.04
 - Browser doesn't make a difference

 - Version 0.5.6.0

**Additional context**
I've also come across some warnings not sure if these are related but I've added the logs.
[kavita_logs_09_10_2022.zip](https://github.com/Kareadita/Kavita/files/9541519/kavita_logs_09_10_2022.zip)

**Comment by majora2007** [comment]
This is a requirement of the new scan loop. Please see the wiki for requirements.
