### ISSUE TITLE
False "special" positives in ComicSpecialRegex

### ISSUE THREAD

**Issue by tjarls** [Kareadita/Kavita#1529]
The current special regexp does not use word boundaries on the keywords used to recognise special issues/chapters. As a result it can falsely identify those words when part of a larger word. Some examples of false positives:
```
Mazebook 001
G.I. Joe - A Real American Hero Yearbook 004 Reprint (2021)
```
Using word boundaries (\b) in the regex fixes this issue.

**Comment by ocgineer** [comment]
would that also help/solve #1104?

**Comment by tjarls** [comment]
That seems likely. I have already staged a fix. Let me add a filename from #1104 to the unittests to find out.

**Comment by tjarls** [comment]
Yup! That fixes it also.
