### ISSUE TITLE
New Relation option for 'different' editions of the same series.

### ISSUE THREAD

**Issue by ocgineer** [Kareadita/Kavita#1533]
Created issue as per request via Discord.

For people that keep the different published editions and like to have them both in Kavita, to link them together with relationships my proposal would be to add an additional relationship like `Alternate Edition`, `Other Edition`,  or simply `Edition`. 

Preferably the relationship should **not** show 'Parent' as there is no real parent here. It would be best for users to set-up the other edition similar to prequel/sequel (if automatic does not allow this) so that whenever the user checks either of the edition the user can see other edition always in the relations tab.

With this extra relation option, users can use this for, but not limited to;
- Normal published <> Omnibus published
- Special Edition Anniversary Edition
- Expired License <> New License (re)published
- Black & White <> Color Edition
- Official <> Scanlation

The current available relation option do not convey that it is a different edition. `Alternate Version` which is the closest would be more used to link Manga with the Light Novel, as the format is different but basically the same story. With different Editions only slight changes are made, like translation or colorization while the story is exactly the same.

**Comment by majora2007** [comment]
@ThePromidius will you take care of implementing this with your Series Relation tests story?

**Comment by ThePromidius** [comment]
> @ThePromidius will you take care of implementing this with your Series Relation tests story?

Will take a look at it tomorrow

**Comment by ThePromidius** [comment]
>>> Preferably the relationship should not show 'Parent' as there is no real parent here. It would be best for users to set-up the other edition similar to prequel/sequel (if automatic does not allow this) so that whenever the user checks either of the edition the user can see other edition always in the relations tab.
This is not really clear to me.

You want to have a one-way relationship or a 2 way relationship (where parent tag is just another "edition" tag)

a) Series A (parent) <--> Series B  (A shows as "parent" in B)
b) Series A <--> Series B (A shows as "edition" in B)
c) Series A --> Series B (A won't show in B)

**Comment by ocgineer** [comment]
not sure if that was a question but the idea would be b, showing as 'edition', never as a 'parent' as there is no parent in my opinion for editions.

Series A (B shows as "edition" in A) <--> Series B (A shows as "edition" in B)

**Comment by ThePromidius** [comment]
So @majora2007 how do you see that? From what you told me the way to go would have to be a

**Comment by majora2007** [comment]
@@ThePromidius what was implemented is correct. An edition is one way without a generated parent tag linking back from the target series.
