### ISSUE TITLE
Cannot change bg color of manga reader, `User Preferences -> Image Reader -> Background Color` cannot change or save

### ISSUE THREAD

**Issue by BenzLeung** [Kareadita/Kavita#1535]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**

I cannot change bg color of manga reader, `User Preferences -> Image Reader -> Background Color` cannot change or save.

**To Reproduce**
1. Nav to User Preferences -> Image Reader
2. Click and change `Background Color` to `#ffffff`.
3. Expect `Save` button turn to enable, but it still disabled, not clickable. 
4. Change any other options.
5. `Save` button turn to clickable, so click it.
6. Expect `Background Color` is saved, but after I click `Save`, it return to black color `#000000`.

**Expected behavior**
Expect I can change the bg color of manga reader via user preferences.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS Big sur
 - Browser: chrome
 - Version: 105

**Smartphone (please complete the following information):**
 - Device: Oneplus 10pro
 - OS: Android 12
 - Browser: [Iceraven](https://github.com/fork-maintainers/iceraven-browser)
 - Version: 1.17

**Additional context**
Kavita version: 0.5.6.0 Windows x64, served on Windows 11

**Comment by majora2007** [comment]
Can you change any settings or does #1494 maybe apply to you? There is a workaround in that issue.

**Comment by BenzLeung** [comment]
All the other settings can be saved and take effect except `Background Color`. So it looks like I'm not having the same issue as #1494 .

**Comment by majora2007** [comment]
Thanks, looked into it and last release this got missed due to a change in when the Save button enables.
