### ISSUE TITLE
A manga volume title set in ComicInfo does not show in list layout mode for Storyline and different behavior for Volumes.

### ISSUE THREAD

**Issue by ocgineer** [Kareadita/Kavita#1538]
I have noticed that in list layout mode of the Storyline the title of the volume does not show, unlike chapters. There are also manga volumes where each individual volume has a (sub)title. For example;

```
I''s v01 - Iori (2005) (Digital) (aKraa).cbz
<ComicInfo>
    <Title>Iori</Title>
    <Series>I''s</Series>
    <Count>15</Count>
    <Volume>1</Volume>
</ComicInfo>
```
```
I''s v02 - Itsuki (2005) (Digital) (aKraa).cbz
<ComicInfo>
    <Title>Itsuki</Title>
    <Series>I''s</Series>
    <Count>15</Count>
    <Volume>2</Volume>
</ComicInfo>
```
![image](https://user-images.githubusercontent.com/12483966/190853330-27513e3a-40ed-4fd6-ad75-9665df6c4874.png)

It looks like under Volumes, the title is appended behind as Volume x - Title, which is a different look/behavior as a chapter with title seen in both Chapters and Storyline.

![image](https://user-images.githubusercontent.com/12483966/190853160-98074a81-6209-4753-8eef-007d8408dd12.png)

![image](https://user-images.githubusercontent.com/12483966/190853395-e0479c8b-68a5-43c2-b85e-1f3bea742c72.png)

**Comment by majora2007** [comment]
Just to let you know, I haven't forgotten about this. Just getting code in place to tackle a different way than I've done prior.

**Comment by majora2007** [comment]
Finally got around to it this issue. Yes, you are correct. I made a conscious decision to prioritize the Title in the Volume and Chapter tab, but not on Storyline, where Volume and Chapter keywords are more important. In your example you have `Volume` in the title, however, the reality is the title is usually without Volume or Chapter information, hence it would be confusing in Storyline view (unless the series is a book, then we will always as books work differently).

**Comment by ocgineer** [comment]
Just to clarify, in my example test case I did not have `Volume` in the title set in ComicInfo.xml.
It is not an issue but just something I saw ;)
