### ISSUE TITLE
Re-scanning existing series removes special issues

### ISSUE THREAD

**Issue by amazing-rando** [Kareadita/Kavita#1544]
**Describe the bug**
Scanning my collection of magazines (all CBZ or PDF files being scanned in the "comics" mode) works as designed and properly organizes everything into the Volumes, Issues, and Specials tabs.  Unfortunately, when I choose to "Scan Series" it will update the available issues to include new files but drops the "Special" tab entirely.

All normal issues have file names in the form: MAGAZINE_NAME vYEAR #MONTH.ext  where YEAR and MONTH are numeric representations of the year and month.  For example, "Nintendo Power v1990 #10.pdf" would be the October 1990 issue.

Special issues have file names in the form: MAGAZINE_NAME SPXX - ISSUE_NAME.ext where XX is a unique two-digit number.  For example, "Nintendo Power SP01 - Final Fantasy Strategy Guide.pdf".

All special issues are stored in a subdirectory named "Specials" which resides in each series' directories.

**To Reproduce**
1. Create a "comic" library which points to a set of properly named CBZ/PDF files of magazines.
2. Scan this newly created "comic" library.
3. Re-do the scan by choosing "Scan Series" for a specific series and specials will disappear.

**Expected behavior**
I would expect that "Scan Series" would leave existing specials in the "Specials" tab as is the original library scanning behavior rather than having Kavita remove them from the listing.  "Scan Series" is helpful for updating Kavita when new issues are added to my server.

Unfortunately, right now, the only solution to this problem has been to delete a specific Series and "Scan Library".  If this work-around is performed, then the specials tab remains available.

**Screenshots**
![Picture1](https://user-images.githubusercontent.com/44684502/190923021-633f5656-0754-4820-9a32-e3dfdb310519.png)

**Desktop (please complete the following information):**
 - OS: Accessed with Windows 10, running on Docker hosted on an Ubuntu server.
 - Browser: Firefox
 - Version: 0.5.6.0

**Comment by majora2007** [comment]
You're right, when performing a Scan series, the special tab, despite me seeing it parse. This is indeed an issue. I'll take a look this release.

**Comment by majora2007** [comment]
I looked into it, this was indeed an oversight with Specials/ folder parsing being skipped due to a change in how we scan and how the code that fall's back to folder parsing works. I have validated a fix.
