### ISSUE TITLE
About default port being 5000

### ISSUE THREAD

**Issue by pkreuzt** [Kareadita/Kavita#1547]
I know this is gonna be controversial, but why is this port chosen? Usually this kind of apps try to get an unused and unique port. But Ombi (another app usually installed on media server/seedbox machines) also uses tcp/5000. Not meaning Kavita is to blame for the possible port conflict. Just raising awareness that this port was already used by somebody else. Anyway in case this is a problem it's really a minor issue since Kavita allows to change listening port very easily.

**Comment by majora2007** [comment]
There is no way to keep every program from using different ports to avoid conflict. You can change the port after launch or in appsettings.json if you don't want to stop Ombi first.
