### ISSUE TITLE
Multiple Series, Same Name, Different Years/Volume

### ISSUE THREAD

**Issue by CDarwin7** [Kareadita/Kavita#1552]
On the website the workaround for this issue is this "
If you have multiple comics from different years, you can name them as "Fables 2004" and "Fables 1989". Then in Kavita's UI, you can rename the "Name" field to be "Fables (2004)" and "Fables (1989)" so they are separate series. This workaround is the only way for different releases of the same series to be supported in Kavita. 

Where is the Name field in the UI? I've looked under the Series, then under Issues, Storylines and Volumes. Cannot find the name field. Specifically, the issue I'm having is with the 2019 and 2021 Volumes of "X-Men". The title for both volumes is X-Men, no adjective like uncanny or unlimited or whatever. The 2019 volume is volume 4 and 2021 is volume 5 according to scaping Comicvine. Both directories were created with Mylar3 using the default settings but allowing for both folder and file name renaming, thus

Volume 4 begins in 2019 for 1 issue and runs thru issue 21, covering 3 years

X-Men (2019)
 -- X-Men 001 (2019)
 -- X-Men 002 (2020)
 -- X-Men 014 (2021)
 -- X-Men 021 (2021)

Then X-Men volume 5 picks up, beginning in 2021 causing some overlap between v4 and v5 in 2021, currently at issue 14.
X-Men (2021)
-- X-Men 001 (2021)
-- X-Men 014 (2022)

Kavita doesnt know what to do with this. Suggests re-naming, which I'm fine with but cannot find the Name field. So where is the name field, or any other suggestions on how to parse these issues?

Thanks!

**Comment by majora2007** [comment]
The name field is found via the edit series flow. You can find it by clicking the ... button then Edit.

To avoid overlap, you can use {} as () are stripped from filenames (although if you use comicInfo which is preferred, you won't have any of these issues).

**Comment by CDarwin7** [comment]
ill get comicinfo...ive been following the anasi project with much interest. hopefully this resolves me issue

**Comment by CDarwin7** [comment]
ok confused, what are we supposed to do with comicinfo.xsd? Drop it in Kavita somewhere?

**Comment by CDarwin7** [comment]
nvm I got it https://wiki.kavitareader.com/en/guides/misc#external-tools
