### ISSUE TITLE
Series Cover Image on Series Page too large/overflowing bounds.

### ISSUE THREAD

**Issue by cityeyes** [Kareadita/Kavita#1559]
Hi, I'm having an issue where the Series Image is just a bit too big, overstretching its bounds and overlapping with other things on the series info page. 

![You can see an image of the problem here - it applies to all of my files.](https://user-images.githubusercontent.com/8008991/192112162-166ffa6a-7b90-4c5d-b960-d5bf6d605417.png)

I'm seeing this on a Windows PC in both the Firefox and Edge browsers. I've tried clearing cache entirely (both in browsers and in Kavita), re-generating covers, and re-upgrading to the newest version of Kavita to no avail.

I also, for the sake of repetition, tried the same on a phone browser in desktop mode and notice that it's _also_ oddly sized in that case, but it's small instead of large, shrinking to a small corner in the series page.  Maybe related?

 - OS: Windows 11
 - Browser - Chrome/Firefox, both desktop.
 - Version 0.5.6.0

**Comment by majora2007** [comment]
@therobbiedavis can you take a look at this when you get a chance?
