### ISSUE TITLE
pdf files not loading

### ISSUE THREAD

**Issue by Eric111111** [Kareadita/Kavita#1560]
Hello, newbie here, 
Hope someone here can help me out. When I create a library, not all the pdf files load. ie some files don't show up. I was using version 5.1 and all the files were showing up. Now on version 5.6, I'm having this problem.

I'm using windows 10 64 bit, Chrome and edge browser, Kavita 5.6

Thanks so much :)

**Comment by majora2007** [comment]
You're going to need to give me a little more than this for support. Can you please give a visual of the screen? How large is the pdf itself? Does it open normally on your system via other software?

**Comment by Eric111111** [comment]
Good morning,
File sizes vary, can be 1029 kb to 8786 kb for example. The files do open up with other apps on my computer. 
![IMG_1893](https://user-images.githubusercontent.com/15671159/192153260-851f58dd-1534-46c0-8af9-84349cda60bd.jpg)
![IMG_1894](https://user-images.githubusercontent.com/15671159/192153266-e018532e-69cf-4d74-b679-95e621c93ad5.jpg)

Thanks :)

**Comment by Eric111111** [comment]
The first pic is the folder holding the files. The second pic it shows only one book showing up.

**Comment by majora2007** [comment]
Wait, let me clarify your issue. Is your issue that the pdfs don't lead in the reader? Or don't load in Kavita? 

If it's not loading in Kavita, it is because you are not following the new Scanner requirements: 
https://wiki.kavitareader.com/en/guides/managing-your-files/scanner#file-layout

**Comment by Eric111111** [comment]
That did it! They were not loading in Kavita. Changed the file layout, and works!! 
Thank you so much :)
