### ISSUE TITLE
Getting HTTP failure response, 500 Internal Server Error when I try to move to page 2

### ISSUE THREAD

**Issue by SkipsterTheHipster** [Kareadita/Kavita#1563]
Per the thread on reddit, I'm opening this bug report here:

I've run into a weird error with 3 epubs I'm trying to read. When I click to move past the cover to the first page, I get this error:

Http failure response for https://xxxxx.xxxxx.xxx/api/book/5490/book-page?page=1: 500 Internal Server Error

I'm not sure what's going on, as nothing is reflected in the log either, with the logging level even set to Debug or Trace. I know that these epubs open and are readable, because I'm able to read them in other reading applications.

I've attached my (hopefully adequately) scrubbed log file.

[kavita_scrubbed.log](https://github.com/Kareadita/Kavita/files/9668057/kavita_scrubbed.log)

**Comment by majora2007** [comment]
Hello, as mentioned on Reddit, please make the epub available to me via a private discord message or a DM on Reddit.

**Comment by majora2007** [comment]
I looked into this issue and the epub is not packed correctly. From what I'm seeing is page 2 asks for stylesheet.css, but that file is not present in the root manifest. This instead has both a root and manifests inside each "page" folder (1, 2, 3). This is not valid and of course, gets skipped by the parser and hence the key code can't find the valid stylesheet. 

I recommend you repack the epub by processing through calibre.
