### ISSUE TITLE
MacOS installation guide

### ISSUE THREAD

**Issue by roblogic** [Kareadita/Kavita#1564]
A few notes for other weird MacOS users like myself! Hopefully I can turn this into a PR when I figure out how.

Current [MacOS installation guide](https://wiki.kavitareader.com/en/install/macos) is incomplete. 

### Remove extended file attributes (step 4)
 * incorrect: <s>`attrx -r -d com.apple.quarantine ~/Downloads/Kavita`</s>
 * correct: `xattr -r -d com.apple.quarantine ~/Kavita/Kavita`

### Help Kavita to find sqlite on MacOS (new step)
* This only works when running Kavita from the Terminal; setting up a service will need further elaboration here (todo):
 `export alias sqlite=sqlite3`

### Change the port number if there's a clash (new step)
* If you see an exception like this reported to the console (or in the log; `~/Kavita/Kavita/config/kavita.log`)
`Unhandled exception. System.IO.IOException: Failed to bind to address http://[::]:5000: address already in use.`
 * edit the file `~/Kavita/Kavita/config/appsettings.json` and change the value near the bottom of the file to `"Port": 5555`
(or something else that is not in use)

### Open Kavita client (new step, after starting up)
* Open a browser window, at address: http://localhost:5000/  
  or http://localhost:5555/ , or the port number you set in the above step.

**Comment by majora2007** [comment]
Hi, please either open an issue on our wiki or even better, open a PR with the changes you're suggesting. I would really welcome a PR since I do not own a Mac. Closing as this is the wrong repo.

**Comment by roblogic** [comment]
PR submitted (my first ever, be gentle!)

**Comment by itsmistermoon** [comment]
I stumbled upon the port conflict. On macOS, the 5000 port is used for the AirPlay Reciever, the change should be part of the installation instructions to avoid simple problems for newbies.
