### ISSUE TITLE
Add japanese fonts

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#1575]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
A user of mine pointed out that with the current fonts japanese characters aren't always the correct characters. He recommends adding Meiryo UI, Yu Mincho, Meiryo, Yu Gothic. 

**Expected behavior**
Character that appears should be correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/2068470/194685463-9c642730-c19c-41b6-8e48-684c48ba85c1.png)
The top first character is the issue. The bottom is what the character should look like. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 0.5.6.20

**Additional context**

**Comment by majora2007** [comment]
I'm not sure where you're referring to? We don't have localization, so if it's coming from a book, then the book has a font which doesn't properly support the language. 

Please let me know. (ps you need steps to reproduce when you report bugs so I can just test it rather than commenting and waiting for a response)

**Comment by scare376** [comment]
Yeah sorry I don't have much information myself. ill try to get more info from my user. I havent really gotten around to reading the jp books i have. Most of the ones i have i got from him to host and he's fairly certain the issue is because of the font packs. I'll try to get something specific for you to test with.

**Comment by majora2007** [comment]
Please do. If it's from a book, they have their own fonts so that could likely be the issue. If it's with our custom override fonts, then I could see that (but not something I can change imo).

**Comment by scare376** [comment]
Alright. I got some more details and did some testing. So he is correct there is something with the font here but it varies from device to device. I dont have the issue on my PC but i could replicate it on my phone. 
![image](https://user-images.githubusercontent.com/2068470/194709003-55290ab8-157b-4c19-a3bf-1fe4ee625c37.png)
![image](https://user-images.githubusercontent.com/2068470/194708988-e1a1685a-8757-4ddf-bef1-a83725acb7bd.png)
the first image is what he sees. the second image is what i see. the main difference is that the line at the top of the characters is slanted.

I was able to embed a japanese font and the book looked fine for him so that will likely be how I handle these books from now on unless there was something else you wanted to try.

**Comment by majora2007** [comment]
So is the book reader using the default font for each of these tests? If so, it could be how the browser renders them is different.

**Comment by scare376** [comment]
yes

**Comment by majora2007** [comment]
Okay then nothing Kavita can do. It's the embedded font and the browser at fault here.
