### ISSUE TITLE
Cover on Series is always one of specials if special instead of first issue

### ISSUE THREAD

**Issue by sarakha63** [Kareadita/Kavita#1577]
**Describe the bug**
The cover of a serie (comics) seems to always take one of the specials if there are some instead of taking the first cover of the serie (first issue)

**To Reproduce**
Have a series of comic without special and scan it, the principal cover of the serie will be issue #1.
Have the same serie being scanned with specila the cover will always be a cover from one special.

**Expected behavior**
Same as series without specials the principal cover should be the first issue's one. Or why not an option like "define this cover as the serie cover"

**Screenshots**
![image](https://user-images.githubusercontent.com/2008029/194704386-3e95c47a-6e47-4e39-8cf5-b6784b7ffe2c.png)
Here gaston is shown with the first issue (that's ok)

but the three others on the screen are showing specials
for example Kid Paddle
![image](https://user-images.githubusercontent.com/2008029/194704420-1fa69024-2f6e-4a87-b952-889b62c9f200.png)
![image](https://user-images.githubusercontent.com/2008029/194704431-d9b92481-02e1-4170-8267-a96da99af0ab.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Chrome
 Version
0.5.6.0
Install ID
9a88f23e

**Smartphone (please complete the following information):**
Not used on this issue

**Comment by majora2007** [comment]
Can you provide the folder/file layout from the Library Root please? This is not something I can reproduce myself and I believe it is likely due to the special being spread out into a separate folder from library root. 

Also provide what type of library this series is in. Books have different rules.

**Comment by sarakha63** [comment]
Hello thanks for tout answer.

Those are set as comics.


And my folder structure is :

Library
    Serie
         Issue 1
         Issue 2
         Issue x
         Specials
                Sp1
                Sp2

So specials are in a sufolder inside the serie folder itself

Regards

**Comment by majora2007** [comment]
Do you have any specials that map to the Series in a separate folder at library level? Can you please attach logs of the scan where this behavior is present? 

I'm not able to reproduce and this looks very similar to an issue of improper setup of folder structure, as Kavita doesn't recalculate covers on scans unless the underlying file has been touched and it never chooses a special unless the Library type is Book (as in Book libraries, nearly everything is a special).

**Comment by sarakha63** [comment]
Hi @majora2007 

No i have not any other folders anywhere else


I have 3 folders :   Bds (for comics)   Mangas for (mangas) and romans (for ebooks)

Each one is declared as it's own library in kavita.

IN the folder Bds i have a folder for each series each one containing the issues and optionally a Specials folder with specials issues inside it

I removed one serie and made a rescan for the log here it is (note that is an example, i can reproduce this on each comic series once i add a special

`dbug: API.Services.DirectoryService[0]
      [ScanFiles] called on /mediatheque/Ebooks/Bds/Game Over (2004)
dbug: API.Services.DirectoryService[0]
      [ScanFiles] called on /mediatheque/Ebooks/Bds/Game Over (2004)/Specials
dbug: API.Services.Tasks.ScannerService[0]
      Found 23 files for /mediatheque/Ebooks/Bds/Game Over (2004)
info: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Beginning series update on Game Over
info: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Processing series Game Over
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Updating 1 volumes on Game Over
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Parsing Game Over - Volume 0
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 0
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 0
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 0
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 1
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 2
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 3
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 4
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 6
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 10
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 12
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 14
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 15
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 16
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 5
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 8
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 7
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 9
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 11
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 13
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 17
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 18
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 19
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Adding new chapter, Game Over - Vol 0 Ch 20
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Specials/Game Over - HS - Midam's Director's cut.cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Specials/Game Over - HS - The Origins.cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Specials/Game Over - HS - Princess Over.cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #01 (2004).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #02 (2006).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #03 (2008).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #04 (2009).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #06 (2011).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #010 (2013).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #012 (2014).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #014 (2016).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #015 (2016).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #016 (2017).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #05 (2010).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #08 (2012).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #07 (2011).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #09 (0000).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #011 (2013).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #013 (2015).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #017 (2018).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Read ComicInfo for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #018 (2020).cbz
dbug: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Updated Game Over volumes from 0 to 1
info: API.Services.Tasks.Scanner.ProcessSeries[0]
      [ScannerService] Finished series update on Game Over in 47 ms
dbug: API.Services.MetadataService[0]
      [MetadataService] Processing cover image generation for series: Game Over
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Specials/Game Over - HS - Midam's Director's cut.cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Specials/Game Over - HS - The Origins.cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Specials/Game Over - HS - Princess Over.cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #01 (2004).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #02 (2006).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #03 (2008).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #04 (2009).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #06 (2011).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #010 (2013).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #012 (2014).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #014 (2016).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #015 (2016).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #016 (2017).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #05 (2010).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #08 (2012).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #07 (2011).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #09 (0000).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #011 (2013).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #013 (2015).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #017 (2018).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #018 (2020).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #019 (2021).cbz
dbug: API.Services.MetadataService[0]
      [MetadataService] Generating cover image for /mediatheque/Ebooks/Bds/Game Over (2004)/Game Over #020 (2022).cbz
info: API.Services.MetadataService[0]
      [MetadataService] Updated covers for Game Over in 1351 milliseconds
dbug: API.Services.MetadataService[0]
      Dispatching 25 update events`


As you can see when Kavita starts processing covers It starts with the specials in first so the general cover for the serie is the first one processed and not the issue #1


Hope that helps

**Comment by majora2007** [comment]
The order in which it generates the covers is not the same thing as Kavita choosing which cover becomes active.

Okay I was finally able to reproduce. The situation is that you have no Volumes and only issues, hence there is a case where the logic falls through and prioritizes a Special over a Chapter.

**Comment by sarakha63** [comment]
Thanks for all.

I really like Kavita.

And im sure with somebody like you taking in consideration feedbacks it will get better and better.

Thanks again

**Comment by sarakha63** [comment]
Hello @majora2007  

Just tested the nightly and i can confirm that the bug is solved
Thanks
Regards
