### ISSUE TITLE
Series Covers and Summary being reset when new Chapter Added to series

### ISSUE THREAD

**Issue by Turtlepoker** [Kareadita/Kavita#1578]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
When a library scan is run , series with new chapter added to their folders have Series Covers (manually set) and Summary (manually set) changed. Series Covers are changed to chapter 1 cover.

Library Named: Webtoons
Type: Comics

File Structure is

Library Root
  ┠── Series Name A
        ┖── Series Name A - Episode 1.cbz
  ┖── Series Name B
        ┖── Series Name B - Episode 1.cbz

**To Reproduce**
1. Have series in Library
2. Set custom Cover Image and Summary
3. Add new Chapter to Series Folder
4. Wait for daily library scan or run manual library scan
5. Set cover imaged replaced by 1st chapter cover, summary erased.

**Expected behavior**
Library scan should lead to new chapters being updated in Series. Keeping all previous series settings intact.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [raspberry pi OS]
 - Browser [firefox 105]
 - Version [0.5.6] recently updated from 0.5.5

**Additional context**
Previously series would sometime be recognized as name plus episode in title, (example: Cape of Spirits - Episode). I would change name, sort name, and localized name to remove "- Episode" from series title. Cape of Spirits - Episode ==> Cape of Spirits

Repeated error
2022-08-28T15:47:32.8423455-05:00	CRIT	[API.Services.Tasks.ScannerService]	[0]	[ScannerService] There are multiple series that map to normalized key capeofspirits. You can manually delete the entity via UI and rescan to fix it. This will be skippedSystem.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at API.Services.Tasks.ScannerService.UpdateLibrary(Library library, Dictionary`2 parsedSeries)

2022-08-28T15:47:32.8496583-05:00	CRIT	[API.Services.Tasks.ScannerService]	[0]	[ScannerService] Duplicate Series Found: cape-of-spirits maps with Cape of Spirits - Episode
2022-08-28T15:47:32.8585765-05:00	CRIT	[API.Services.Tasks.ScannerService]	[0]	[ScannerService] Duplicate Series Found: cape-of-spirits maps with cape-of-spirits
[kavita.log](https://github.com/Kareadita/Kavita/files/9739840/kavita.log)

**Comment by majora2007** [comment]
This is an easy issue, you are not meeting the scanner's requirement, hence why you're getting resets happening. You cannot have series spread into multiple folders from the Library Root. 

I'm going to close it. Once you correct your Scan loop and if you still see this occurring, come back and open the issue or comment and I can provide support or investigation.

https://wiki.kavitareader.com/en/guides/managing-your-files/scanner#file-layout

**Comment by Turtlepoker** [comment]
Sorry, Library structure didn't format correctly  in my post, This is current structure.
Would this not be the correct file structure?
![image](https://user-images.githubusercontent.com/83781928/194722457-6fc04a4c-d2f4-4eca-b59e-b916f252b1ba.png)
![image](https://user-images.githubusercontent.com/83781928/194722677-cfb8e5e2-ca0d-4977-9d3d-755bbb49cdac.png)
![image](https://user-images.githubusercontent.com/83781928/194722790-969589f4-658b-4686-84d1-64ae35b02571.png)
![image](https://user-images.githubusercontent.com/83781928/194722852-8198fcc9-7867-4001-9bdb-6b27682213f3.png)

**Comment by majora2007** [comment]
Ahh indeed it did not. I am going to guess this is due to some instability with the scan loop. Unfortunately, the nightly has fixed many issues with the scan loop (as v0.5.6 was the first version of the new loop), so debugging this issue isn't possible. Although, the next release is right around the corner, so it should be fixed for you soon.

I'll reopen the ticket for you and can follow up post v0.6 release.

**Comment by Turtlepoker** [comment]
Looking more closely at files, the issue seems to be related to files with "Episode" in name (She's Hopeless - Episode 1.cbz). This results in Series being added as "She's Hopeless - Episode". In previous versions I would just rename in Kavita to "She's Hopeless".
Version 0.5.6 doesn't seem to like changes to "Name"; can edit "Sort Name" and "localized name" just fine. When I change "Name", series seems to get broken. 

If I can I try to Scan Series from Series Page this error pops up
![Scan for new file from series](https://user-images.githubusercontent.com/83781928/194793305-46bd66e2-e9f7-40b5-8268-902201c09cb8.PNG)
Running full library scan results as Series being detected as new (when updated with new chapters). Series is added with original pre-edit title "She's Hopeless - Episode" and new creation date. Thus, resetting my previously set cover, summary, and any other manually set info for series.

Found Solution:
Don't have chapters named with "Episode" in file title.
Incorrect: "She's Hopeless - Episode 1.cbz" or "She's Hopeless Episode 1.cbz"
Correct: "She's Hopeless - Ep 1.cbz"  or "She's Hopeless - Ep.1.cbz" or "She's Hopeless Ep 1.cbz

Is this expected or unexpected behavior?

**Comment by majora2007** [comment]
Okay, so this issue has become a bit messy. First off, your first issue is due to the bugs in the stable. So I'm going to leave that as that, as it's fixed on nightly and a stable is right around the corner. 

For your second issue, it indeed was an issue and thank you for bringing it up. I have corrected the issue where Scan Series on a Series with a custom name in Kavita would cause a deletion. Next time throw that up on a separate issue.
