### ISSUE TITLE
Changing Magazine library from "books" to "comics" causes no icons to display

### ISSUE THREAD

**Issue by TaakoMagnusen** [Kareadita/Kavita#1579]
**Describe the bug**
Had a bunch of files in my magazines library with the name "Issue XXX", library was originally created as "books". This caused all files to be recognized as separate chapters of a single icon.  Was told to change to "comics" so the name would parse out each file as a separate icon in the series. Changing library to "comics" and triggering rescan caused all icons (only 1) to disappear entirely

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Version : 0.5.6.0]

[kavita_logs_10_09_2022.zip](https://github.com/Kareadita/Kavita/files/9742028/kavita_logs_10_09_2022.zip)

<img width="1067" alt="Screen Shot 2022-10-09 at 9 30 13 AM" src="https://user-images.githubusercontent.com/39819109/194768426-8d622e3f-e5c5-40ef-9c67-957b05a7155c.png">

<img width="602" alt="Screen Shot 2022-10-09 at 9 10 29 AM" src="https://user-images.githubusercontent.com/39819109/194768386-686d292a-89bf-42b9-b64f-276fc9cca111.png">

**Comment by majora2007** [comment]
I believe this to be fixed, if you are still having it on v0.7.1+, please comment.
