### ISSUE TITLE
Corrupted volume entries cause duplicate records to be created

### ISSUE THREAD

**Issue by motodrew** [Kareadita/Kavita#1592]
**Describe the bug**
When adding new comics to the application, the logs will sometimes mark volume entries as corrupted and result in duplicate comics in the system.

**To Reproduce**
0. Unsure exactly how to reproduce as it only seems to happen sometimes
1. Confirm that Folder Watching is enabled
2. Move a decent number of comics into a folder that is being watched in Kavita
3. Check the comic/manga for any duplicate entries usually if it happens each comic that was added will be duplicated sometimes many times. OR check the logs for [ScannerService] Kavita found corrupted volume entries on... errors
4. If wanting to fix the series. Delete it and run a scan on the library with the issue.

**Expected behavior**
It looks like the comics are still added into the system, so I would expect that no duplicate comics are created, or a notification is produced that will show which comics need to be deleted and re-scanned

**Screenshots**
![image](https://user-images.githubusercontent.com/4896141/196578763-ad8f5675-e679-428e-a0b2-df47ef052f2d.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Version: 0.5.6.29

**Comment by motodrew** [comment]
#1576 I think that this is the same issue that we were talking about near the end of this issue. It had seemed fixed which is why I did not create this ticket until now.

**Comment by motodrew** [comment]
I'm also actually direct downloading into the folder with a script that I wrote. I wasn't really keeping track of how long the downloads were taking but likely was over 10 min as it was close to 400 chapters.

By the sounds of it, I may just be using it incorrectly and may add an intermediary spot to download the files to then move them into the watched folder. Or actually, make my script a bit more efficient :)

Since it sounds like this should be an unsupported feature (downloading directly into a watched folder) want me to close this ticket?

**Comment by majora2007** [comment]
No, don't close the ticket. Because while it is an unsupported feature, duplicate chapters still shouldn't be possible. I'll do some extra testing in the next release (as v0.6 is getting release tested now) to harden any code.

**Comment by motodrew** [comment]
Sounds good, if it is helpful for testing purposes I can make my script public and send the details in a dm on discord. Currently only works with one site but overall has been decent at making this error occur.

**Comment by majora2007** [comment]
This should be fixed as of v0.6.0. Can you confirm? 

I tested by doing 200 downloads in one go and no duplicates occurred.

**Comment by motodrew** [comment]
Just ran about 200 records as well. It may have just been the timing but looks like it performed the scan after all of the copy operations were completed!
