### ISSUE TITLE
Issues with Mark as Unread

### ISSUE THREAD

**Issue by TheIceCreamTroll** [Kareadita/Kavita#1595]
**Describe the bug**
Marking a Kavita-generated volume as unread doesn't always mark the underlying chapters as unread, and doesn't always update the volume card properly

**To Reproduce**
1. Re-create steps in the video

https://user-images.githubusercontent.com/33820904/196844019-6bd90094-1979-41a0-8319-6d7d495ddb4b.mp4

**Screenshots**
![unknown](https://user-images.githubusercontent.com/33820904/196842820-d2345a98-3164-4bc5-9faa-80ca9fe46cfb.png)
an unread volume's incomplete progress bar after being marked as read

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox
 - Version 0.5.6.31

**Comment by majora2007** [comment]
So I do see the individual chapters marking as read, all that's left is the volume card not reflecting current state.
