### ISSUE TITLE
Books seen as files when searching, but not showing up in libraries for users to download

### ISSUE THREAD

**Issue by jveronese** [Kareadita/Kavita#1598]
**Describe the bug**

I have a fresh install of Kavita on an Ubuntu container I host. I have my books on an SMB share. Kavita shows a little over half my books in the libraries to download, but many are missing. If I search I can see the file (path and everything), but it doesn't show up in my actual library for users to download. I have tried editing data in Calibre, deleting all non epub files, running new scans, and setting up fresh SMB directories to see if that fixes the issue to no avail.

**To Reproduce**

Point to SMB share for a library and scan

**Expected behavior**
All my .epub files should show as books (with or without metadata) and be available to download

**Tried On:**
 - OS: Issue on Windows, PopOS, and iOS
 - Browser: Chrome and Firefox
 - Kavita Version: 0.5.6.0

**Comment by majora2007** [comment]
Did you check the scanner requirements first? 
https://wiki.kavitareader.com/en/guides/managing-your-files/scanner

There are requirements on v0.5.6 (highlighted in release notes) that you have to follow a new structure for Kavita to work. 

Please validate this first and get back to me.
