### ISSUE TITLE
Culture is not supported. (Parameter 'name') | en_us is an invalid culture identifier.

### ISSUE THREAD

**Issue by VegethB** [Kareadita/Kavita#1607]
OS: Windows Server 2019 DataCenter LTSC x64 v.1809;
Browser: Chrome 106.0.5249.119 (Build ufficiale) (a 64 bit);

**Describe the bug**
Opening the kavita server console (kavita.exe) after starting it 1 day ago, I found this error (maybe others too, but it is too long output to read it all).

I didn't notice if it was also there in the version before, what I know is that it comes from the update to 0.6.0.
Also, when I updated to 6, it reset the config and custom port I had put in.

**To Reproduce**
I have no idea, but Kavita I use it for Light Novels anime (like a KonoSuba) in Epub/PDF format: some Epub v2 some Epub v3, Some Epubs are edited to change certain tags with 2 software.
) Calibre
) Epub Metadata Editor 1.9.2
Being Italian, I don't touch the LNs which are en-us of defautl.
I just create collections through metadata (because you can't create collections virtually in the server... which makes it more elaborate, having to operate on physical files instead of virtual structures in the server and leaving files untouched 🤷‍♂️)

**Screenshots**
![image](https://user-images.githubusercontent.com/17975351/197385337-8d3b03ff-f7b2-49f7-bf69-8293c1bf2a09.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019 DataCenter LTSC x64 v.1809;
 - Browser Chrome 106.0.5249.119 (Build ufficiale) (a 64 bit);
 - Version 0.6.0.0

**Additional context**
I don't know if I can pass the logs, I don't know if there is sensitive information logged.

**Comment by majora2007** [comment]
I know I'm late to this issue, but can you please reproduce and attach logs. Logs do not have sensitive info (except filenames, but you can clear logs, do test, then attach logs).

**Comment by majora2007** [comment]
From the logs, I can def see this is likely an issue with one of your Epubs or archives. The language within it doesn't match a valid culture and hence when translating from "en" -> "English", your language string isn't valid and has no where to translate to. 

Finding the series that is throwing this and sending the language tag would help a ton.

**Comment by majora2007** [comment]
This issue is only caused from looking up existing cultures. Perhaps you can open All Series page, open the metadata filter, then the language auto-complete? That should do the same thing.

**Comment by majora2007** [comment]
Unfortunately no, I don't own the culture strings. I rely on .NET, for which there is a default list of strings. 
From Kavita's side we just accept then try to translate. However, that is why I was asking. I could instead just drop the language if it doesn't validate at the scan step.

**Comment by majora2007** [comment]
Enhancement: Drop language tags at the scanner if the language doesn't validate to a valid Culture.

**Comment by majora2007** [comment]
No problem. I would see if Calibre could be used or something like that. Join our discord, many calibre users there and might have some advice. I am leaving this open as I plan to enhance Kavita from this experience.
