### ISSUE TITLE
PDFs crashing on older Tablets

### ISSUE THREAD

**Issue by DannysList** [Kareadita/Kavita#1617]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Tablets I've tested this with:

Nvidia K1 Tablet 
IPad 2
Ipad Mini 2
Kindle Fire 6th 4th Generation

All have been updated to the latest OS releases.

When I started my Kavita journey I was using my NVIDIA K1 almost exclusively and occasionally would use the Ipad Mini 2, everything worked perfect until [v0.5.4](https://github.com/Kareadita/Kavita/releases/tag/v0.5.4).  

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**

After viewing a pdf that is heavy in images (magazines for example) the browser crashes on me. and I have to restart my browser in which it picks up right where it dropped.

**To Reproduce**
1. Go to any pdf and open it
2. Scroll down slowly as if you are reading it (or really read it if its interesting)
4. There is no time frame but sooner than later the browser will crash

**Expected behavior**

expect to view the pdf to completion

**Screenshots**

These screenshots are slightly edited to remove my ip address but the error is still correct. One is on Chrome and the other is on Brave.

![fcd7148a7694e6c559c896299b77adff575596f9_2_690x407](https://user-images.githubusercontent.com/91218838/198359119-bb61758a-d279-4ec4-b7a1-500abadadb6c.png)
![AwSnap](https://user-images.githubusercontent.com/91218838/198359146-87f38224-24fa-415d-aff7-a89ae1499601.png)

** NVIDIA K1 Tablet (please complete the following information):**
 - OS: Android 7 (highest it can go)
 - Browser: Chrome and Brave (most stable recent release)
 - Version: most stable recent release

** Ipad Mini 2 Tablet (please complete the following information):**
 - OS: iOS 12.5.5 (highest it can go)
 - Browser: Opera 
 - Version: most stable recent release

** Ipad 2 Tablet (please complete the following information):**
 - OS: : iOS 9.3.5 (highest it can go)
 - Browser: Opera 
 - Version: most stable recent release

** Kindle Fire 6th 4th Generation Tablet (please complete the following information):**
 - OS: : Fire OS) 5 (highest it can go)
 - Browser: Silk
 - Version: most stable recent release

**Additional context**

NVIDIA, Kindle and Ipad mini 2 are the ones where the pdfs just crash after a few minutes of reading. The Ipad 2 doesn't even load Kavita which is definitely not related to the issue but I wanted to say I tried on there as well

**Comment by DannysList** [comment]
I tried running it on firefox last night and while I didn't crash, I had several instances where the screen would flash several times and reload the pdf.

**Comment by majora2007** [comment]
This might be working in the v0.7.8.11 nightly. If you are on the nighties please let me know, else I'll ping on the v0.7.9 release.

**Comment by DieselTech** [comment]
@DannysList It's been some time since this was opened and many versions of Kavita have been released since then. If you're still having this issue, please comment here and we'll reopen the ticket.
