### ISSUE TITLE
Filename keywords for comic specials don't work properly

### ISSUE THREAD

**Issue by pssandhu** [Kareadita/Kavita#1618]
**Describe the bug**
[This page of the wiki](https://wiki.kavitareader.com/en/guides/managing-your-files/comics) lists special keywords that can be used in filenames to get kavita to mark them as specials.

**To Reproduce**
1. Have a library with this folder structure (the files have no metadata in them):

```
Library Root/
    |-- Batman Beyond (1999)/
        |-- Batman Beyond 01.cbz
        |-- Batman Beyond ...
        |-- Batman Beyond 06.cbz
        |-- Batman Beyond Annual 01.cbz
        |-- Batman Beyond Annual 02.cbz
```
2. Scan the library
3. The issues show up in kavita correctly but the annuals are not there

**Expected behavior**
The annuals should be in the library and marked as specials

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Version: Kavita 0.6.0.0

**Additional context**
On a fresh install the annuals showed up as a separate series called Batman Beyond Annual but I'm unable to reproduce that after renaming the files. Might need to do a fresh install to see this.

I tested various filenames one at a time (shown below). Some of these are unlikely to be real filenames like `Batman Beyond Book.cbz` or `Batman Beyond Annual.cbz` but I thought testing these might be useful.

Treated as a special:
```
01 Annual Batman Beyond.cbz
Batman Beyond Omnibus.cbz
Batman Beyond Omnibus (1999).cbz
Batman Beyond TPB.cbz
Batman Beyond Bonus.cbz
Batman Beyond Specials.cbz
Batman Beyond OneShot.cbz
```

Treated as a volume:
```
Batman Beyond TPB v01.cbz
```

Not added to library:
```
Batman Beyond Annual 01 (1999).cbz
Batman Beyond Annual 01.cbz
Batman Beyond Annual #001.cbz
Batman Beyond Annual (1999).cbz
Batman Beyond Annual.cbz
1 Annual Batman Beyond.cbz
Batman Beyond Omnibus 01.cbz
Batman Beyond Omnibus 1.cbz
Batman Beyond TPB 1.cbz
Batman Beyond Book 01.cbz
Batman Beyond Book.cbz
```

**Comment by majora2007** [comment]
Hi @tjarls, this issue looks to be from https://github.com/Kareadita/Kavita/pull/1531 where specials were word bounded to prevent false positives, however from testing, I'm seeing "Batman Beyond Annual" and "Ippo - Artbook" to not be considered a special. 

From the regex: `|\d.+?\WAnnual|Annual\W\d.+?|`, you'd think it'd work, but it does not match. Any ideas?

**Comment by majora2007** [comment]
It seems the \d is what is our culprit, so what if we just left \d out and changed to `.\WAnnual`, which would still act very similar.

**Comment by majora2007** [comment]
I settled for `\b(?:\d.+?(\W|-|^)Annual|Annual(\W|-|$))\b` (just looking at Annual). This allows us to meet all the Unit tests and works against this case as well.

**Comment by tjarls** [comment]
That behaviour predates #1531 and has nothing to do with word bounding the key words used for special. I suspect the intention was indeed to only match Annual alongside a year or just a number. Comic annuals almost always have a date alonside the world "annual" (for example `Action Comics 2021 Annual`, `Amazing Spider-Man Annual 2 (2021)`).  Here's the original regex from before the word bounding changes:
```
@"(?<Special>Specials?|OneShot|One\-Shot|\d.+?(\W|_|-)Annual|Annual(\W|_|-)\d.+?|Extra(?:(\sChapter)?[^\S])|Book \d.+?|Compendium \d.+?|Omnibus \d.+?|[_\s\-]TPB[_\s\-]
|FCBD \d.+?|Absolute \d.+?|Preview \d.+?|Art Collection|Side(\s|_)Stories|Bonus|Hors Série|(\W|_|-)HS(\W|_|-)|(\W|_|-)THS(\W|_|-))",
```

The unit test for `Annual Days of Summer` is another evidence that this was indeed legacy behaviour. So there hasn't been any regression on that side.

On the other hand, the widening of the match for Annual and, even more so, for Absolute, is introducing quite a few additional false positives. Some examples I have spotted in my own library
- Superman/Batman: Absolute Power
- Blue Monday: Absolute beginners
- A few Marvel series with "Absolute Carnage"
While there are mechanisms to tag as special individual issues, there isn't a way of doing the opposite short of actually changing the series names on those affected.

so I do not think it's a good idea to so widden the filename special matching mechanism for Absolute and to a lesser extend Annual without year. There are plenty of other words that are occasionally used to denote a special edition of a series (Definitive, Collected, Album, Digest,..) that are not automatically detected and covering all of them is both non realistic and unnecessary as the explict tagging with SP# for example or setting the comicinfo "special" tag already covers those case. We do not have a "not-special" tag for the reverse use case. So the current fix looks to me as a regression where we are trading minor annoyances that are already easily solvable for an issue without a solution and often a way worse user experience (all issues from a series suddenly tagged as special and no longer properly sorted).

Finally if we decide to keep the current fix, the regular expression is unnecessary complex. To achieve, the desired goal of matching Annual, Absolute, etc the more efficient regex would be simply:
```
$@"\b(?:{CommonSpecial}|Annual|Book \d.+?|Compendium|Omnibus|FCBD \d.+?|Absolute|Preview|Hors[ -]S[ée]rie|TPB|HS|THS)\b"
```

**Comment by majora2007** [comment]
Hmmm...you make some good points and it's good to also learn more about how some keywords are used in comics, as I do not collect them myself. As we can support via SP# or ComicInfo Special tag, it does make sense to reduce false positives rather than support more loose rules. 

Do you suggest removing Absolute and Annual (without year) altogether? I need guidance on comic support. I'm also not sure how often these keywords are used.

**Comment by robsonsobral** [comment]
First comment! I just have found this project and I'm still reading everything about it. It looks really cool.

Why not to require separators? So the word "Annual" would only be recognized in this case if there's `-` before it? `#`, `-`, `(`, `)`, `[` and `]` could be used as separators.

Too bad idea?

**Comment by majora2007** [comment]
I know this is an old issue, but I'm now considering removing special keyword parsing. Would love feedback on the other issue:
https://github.com/Kareadita/Kavita/issues/2967
