### ISSUE TITLE
No show Table of contents in epub3 generated with Sigil

### ISSUE THREAD

**Issue by zeedif** [Kareadita/Kavita#1621]
![image](https://user-images.githubusercontent.com/60901341/198891677-b4cb275a-0c7a-4650-813b-a5d9f713ca57.png)

This problem occurs with the tables of contents of all epubs generated by [Sigil](https://sigil-ebook.com/sigil/download) software. Only occurs with the epub3 format that uses a toc.xhtml file.
```
<nav epub:type="toc" id="toc" role="doc-toc">
  <h1>Índice de contenido</h1>
  <ol>
    <li>
      <a href="Section0001.xhtml">Inicio</a>
    </li>
  </ol>
</nav>
<nav epub:type="landmarks" id="landmarks" hidden="">
  <h2>Hitos</h2>
  <ol>
    <li>
      <a epub:type="toc" href="#toc">Índice de contenido</a>
    </li>
  </ol>
</nav>
```
The problem does not seem to be in the .NET EpubReader library because I have examined your file "[Epub3NavDocumentReader.cs](https://github.com/vers-one/EpubReader/blob/master/Source/VersOne.Epub/Readers/Epub3NavDocumentReader.cs)" and a correct check is made for h1-h6 in the nav on line 87.

Using one of the [demos](https://github.com/vers-one/EpubReader#demo-apps) to test the library, the table of contents is generated correctly.

![image](https://user-images.githubusercontent.com/60901341/198892007-4c3e1d22-b41d-456d-bc38-d86fbb789a9d.png)

**Comment by majora2007** [comment]
@zeedif would you mind pming me a file in discord for this issue?
