### ISSUE TITLE
Manga library series count keeps changing and messing up tracking

### ISSUE THREAD

**Issue by fonephreak** [Kareadita/Kavita#1622]
**Describe the bug**
I have 171 mangas in my library and after update with version 6 after 5.6 with folder watching on my library decreased to 161 then to 123. i had to scan library and analyze files twice to get the count back but now i have missing mangas again. 

i turned off folder watching and rescanned library the missing mangas return but all custom info i entered for it gone. it seems to happen more with mangas i rename in kavita and its no longer has similar to folder name. so i keep losing my chapter tracking, cover, description etc that i add to it.

i dont use cbz but raw images for my mangas (i dont know if that matters)

i had no issues before 5.6. When i went to 5.6 if i renamed something it would delete the manga and add it as new when the library scanned but the amount i had didnt change. in v6 folder watching just makes them disappear. i turn it off rescan and they are back but all custom information added is lost.

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 0.6.0.0

**Comment by majora2007** [comment]
V0.5.6 as per the changelog changed Kavita to have requirements for the scan loop. These can be found on the wiki. 

This is your problem. Your file layout is not conforming and things are overriding with each other. 

Go over the wiki article, this is a common issue many users are having. After correcting, their issues are resolved.

**Comment by fonephreak** [comment]
ok, I'll use shield hero as an example. the folder name is Tate no Yuusha no Nariagari and how it shows up in kavita. I change it to display return of shield hero then one of 2 things happens when there is a new chapter. 1 when folder watching is on it eventual disappears. OR 2 when its off it gets removed then added as a new series with folder name.

**Comment by majora2007** [comment]
For your example, what is the file layout under that folder? We don't use folder names except a few cases. Do you have any other shield heros on your library?

In order for me to investigate this as a bug, I need a minimal reproducible steps listed, like in the issue template.
