### ISSUE TITLE
Continue button opens wrong comic volume

### ISSUE THREAD

**Issue by pssandhu** [Kareadita/Kavita#1625]
**Describe the bug**
I have a comic with 3 volumes of issues. I have read some of the issues in volume 1 but if I go to the series page and press the Continue button it opens Volume 2 Issue 1.

**To Reproduce**
1. Have a series with multiple volumes:

```
Library Root/
    |-- Ultimate Spider-Man (2000)/
        |-- Ultimate Spider-Man v01 001 (2000).cbr
        |-- Ultimate Spider-Man v01 002 (2000).cbr
        |-- ...
        |-- Ultimate Spider-Man v02 001 (2009).cbr
        |-- ...
        |-- Ultimate Spider-Man v03 001 (2011).cbr
        |-- ...

```
3. Go to the series page in kavita, make sure the whole series is unread
4. Mark the first two issues of volume 1 as read
5. Press Continue at the top of the page
6. Volume 2 issue 1 opens

**Expected behavior**
Volume 1 issue 3 should open i.e. the next unread issue

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Version: Kavita 0.6.0.0

**Comment by majora2007** [comment]
Your example did not have a chapter 3. How are you marking the first 2 issues as read? Via Issues tab?

**Comment by pssandhu** [comment]
Where I wrote `...` in my example I skipped listing all the issues for each volume. The first has over 100 issues, the others have around 30. Sorry, I should have been more explicit.

Yes, I'm going to the issues tab on the series page and marking the individual issues as read.

**Comment by majora2007** [comment]
I just tested this out. I had a blank series, 3 volumes, each volume is roughly 60 chapters long. I marked the first 2 as read via bulk update then hit continue. Chapter 3 opened.

**Comment by pssandhu** [comment]
I think the problem is related to issue/chapter numbering in volumes. In my example the issue numbers restart at 1 for each volume. However, if the issue numbers in different volumes do not overlap (e.g. v01 has issues 1-5 and v02 has issues 6-10) then the Continue button opens the correct item.

It's as though kavita is looking for the unread issue with the lowest chapter number and ignoring the volume number.

**Comment by majora2007** [comment]
I don't know how I forgot to link to this, but I fixed this at least last release. Let me know if you're still having this issue.

**Comment by pssandhu** [comment]
I'm still having this issue on 0.7.2 but the behaviour is different.

I'm using the same series as before:
- Volume 1 has 100 issues, numbered 1-100
- Volumes 2 and 3 have around 30 each, numbered 1-30
- Kavita correctly identifies the volume and issue number of each file
- The library Type is Comic

If I mark Vol 1 issue 1 as read, it wants me to continue with Vol 1 issue 21. If I then start at v1 issue 21 and mark chapters read one at a time, it works correctly until Vol 1 issue 41 after which it wants me to read Vol 1 issue 9.

If I mark the whole of Vol 1 as read, Continue takes me to Vol 2 issue 8. If I mark volumes 1 and 2 as read, it Continues with Vol 3 issue 4.

**Comment by majora2007** [comment]
I'll try to reproduce locally and see if there is another edge case.

**Comment by majora2007** [comment]
I am seeing another issue that I want to take care of in this ticket:
Volume 1-10 are fully read (single volumes), 
Special 1 is fully read
Chapters 56-90 are read
Chapter 91 has partial progress on

Continue is resuming at volume 1

**Comment by majora2007** [comment]
I wasn't able to reproduce your case, but as you see, I did find a bug in one case. After I solved this, I tested yours, so it must be fixed or it's really not reproducible.
