### ISSUE TITLE
Bug with SQLite being locked

### ISSUE THREAD

**Issue by fruizaviles** [Kareadita/Kavita#1626]
Hi there! I am currently running Firefly-III self-hosted finance software at GitHub, and Kavita bookshelf, and I have found that Kavita stopped working properly after half an hour of installing Firefly. I am using Docker containers and as described at mariushosting.com:

https://mariushosting.com/how-to-install-firefly-iii-on-your-synology-nas/

https://mariushosting.com/how-to-install-kavita-on-your-synology-nas/

The log of my Kavita container, that is what fails, is:

2022-10-31T17:44:04.335541953Z | stdout | [Kavita] [2022-10-31 17:44:04.335 +00:00  3786] [Error] Hangfire.Storage.SQLite.SQLiteDistributedLock Unable to update heartbeat on the resource 'HangFire:recurring-jobs:lock'. The resource is not locked or is locked by another owner.

I have stopped the 3 Firefly containers and restarted Kavita and works smooth again, BUT stops again half an hour aprox. since I start Firefly again.

My hardware is a Synology DS720+ running DSM 7.1 latest release (up-to-date).

Any idea on how to fit it? I would like to be using both Kavita and Firefly-III.

Kind regards,

Frank

**Comment by majora2007** [comment]
Hi Frank,

This message does not mean that your Firefly container is accessing the database of Kavita. It is something that Kavita uses to ensure 2 jobs don't run at the same time. It is not an error per-se, but rather an info from the underlying library. 

However, it is good practice to ensure the mounted volume for Kavita is used solely for Kavita.

**Comment by majora2007** [comment]
Do you need further support or can I close this issue?

**Comment by Cybolic** [comment]
@majora2007 Could you provide more info on what's triggering this? I have 17 other docker containers running (not Firefly) and I'm getting this as well, with Kavita crashing before ever finishing a scan.

**Comment by dll3e** [comment]
@majora2007 Same problem for me. I mapped a books folder in kavita but on the system that is where Calibre stores its books.

**Comment by majora2007** [comment]
This issue should be fixed on v0.6.1. Can you retest and let me know.

**Comment by dll3e** [comment]
Tested with the newest docker image (0.6.1) as of now the error does not appear to be happening. 
Thanks a lot for the quick fix.

**Comment by Cybolic** [comment]
Can confirm that 0.6.1 seems to fix this issue.
