### ISSUE TITLE
PDF don't show up in Kavita

### ISSUE THREAD

**Issue by Lindsey-Bonnier** [Kareadita/Kavita#1638]
Hi, I got curious about putting books in a "PLEX" kind of way and tried Kavita since I read only good thing about this software.

I'm using a **Unbuntu server 22.04**. The server is a **fresh install**.
Kavita run in a container with Docker.  The only addition is Docker, SAMBA and Kavita through Docker. 

This is the script I used to create the container:
```
docker run --name kavita -p 5000:5000 \
-v /media/2tb-dl-server/_Kavita.books:/manga \
-v /kavita/data/directory:/kavita/config \
--restart unless-stopped \
-e TZ=UTC-4 \
-d kizaing/kavita:latest
```

Comics, manga, EPUB works fine.

I tried to add a library point to a directory with multiple PDF. I downloaded also the PDF (other.zip) from the Kavita demo. Even if I clearly see the files in the directory, Kavita doesn't display any PDF files. I tried different browser too. Same result.  

I tried a MANGA, a COMIC and a BOOK type library. Same result. I'm absolutely new on Kavita and tried to find solution online for a couple of hours and now I'm asking at the source!

Did I made a mistake? Is it a bug? I bet not, I just overlook something very clear and simple... right?

Thanks for any support you can give!

This is my library files I used to test.
![files](https://user-images.githubusercontent.com/117558469/200155754-38725939-4ee1-4fb9-9e46-a070aa51469f.png)

Config of the 3 test library I setup.
![dash](https://user-images.githubusercontent.com/117558469/200155808-9ff175e6-523d-4567-9655-51164be61b17.png)

**Comment by scare376** [comment]
You're not following the scanner requirements. In this case you cooking folder is the root folder for these libraries and kavita doesnt pick up loose files in the root folder.
https://wiki.kavitareader.com/en/guides/managing-your-files/scanner#introduction

**Comment by Lindsey-Bonnier** [comment]
WOW.

Thank you so much. That was of course the problem!!!
