### ISSUE TITLE
Deadlock on SQLite write acces ?

### ISSUE THREAD

**Issue by yves-gaignard** [Kareadita/Kavita#1639]
Kavita installation:

On Synology DS1019 through docker
Image version

TAG [latest](https://registry.hub.docker.com/layers/kizaing/kavita/latest/images/sha256-b3373503d26173e58b32a1a88c020860011e533aa778c49f3c4b4144838ee62d?context=explore)
docker pull kizaing/kavita:latest
Last pushed 16 days ago by [jvmilazz0](https://registry.hub.docker.com/u/jvmilazz0)

DIGEST             OS/ARCH      COMPRESSED SIZE 
b3373503d261 linux/amd64 196.29 MB
7f19ac881cd9   linux/arm/v7 185.48 MB
c9ac44a6e253   linux/arm64 191.05 MB

**Describe the bug**
After a cleaned installation, I added 1 comic serie and every 
Then I created 3 librairies : comics, books, magazines and add 5 series on each.
I relaunch a scan on these 3 libraries ... and the kavita website stopped to display anything

In the terminal of the container, here are the messages displayed:

[Kavita] [2022-11-07 07:21:05.599 +00:00  2614] [Error] Hangfire.Storage.SQLite.SQLiteDistributedLock Unable to update heartb
eat on the resource 'HangFire:job:76:state-lock'. The resource is not locked or is locked by another owner.                  
[Kavita] [2022-11-07 07:21:05.957 +00:00  1405] [Error] Hangfire.Storage.SQLite.SQLiteDistributedLock Unable to update heartb
eat on the resource 'HangFire:job:76:state-lock'. The resource is not locked or is locked by another owner.                  
[Kavita] [2022-11-07 07:21:07.223 +00:00  743] [Error] Hangfire.Storage.SQLite.SQLiteDistributedLock Unable to update heartbe
at on the resource 'HangFire:job:76:state-lock'. The resource is not locked or is locked by another owner.                   
[Kavita] [2022-11-07 07:21:08.481 +00:00  1511] [Error] Hangfire.Storage.SQLite.SQLiteDistributedLock Unable to update heartb
eat on the resource 'HangFire:job:76:state-lock'. The resource is not locked or is locked by another owner.                  
[Kavita] [2022-11-07 07:21:10.223 +00:00  2814] [Error] Hangfire.Storage.SQLite.SQLiteDistributedLock Unable to update heartb
eat on the resource 'HangFire:job:76:state-lock'. The resource is not locked or is locked by another owner.                  
[Kavita] [2022-11-07 07:21:14.498 +00:00  2473] [Error] Hangfire.Storage.SQLite.SQLiteDistributedLock Unable to update heartb
eat on the resource 'HangFire:job:76:state-lock'. The resource is not locked or is locked by another owner.                  
[Kavita] [2022-11-07 07:21:15.409 +00:00  1542] [Error] Hangfire.Storage.SQLite.SQLiteDistributedLock Unable to update heartb
eat on the resource 'HangFire:job:76:state-lock'. The resource is not locked or is locked by another owner.                  
[Kavita] [2022-11-07 07:21:29.073 +00:00  1582] [Error] Hangfire.Storage.SQLite.SQLiteDistributedLock Unable to update heartb
eat on the resource 'HangFire:recurring-jobs:lock'. The resource is not locked or is locked by another owner.                
[Kavita] [2022-11-07 07:21:29.073 +00:00  848] [Error] Hangfire.Storage.SQLite.SQLiteDistributedLock Unable to update heartbe
at on the resource 'HangFire:job:133:state-lock'. The resource is not locked or is locked by another owner.                  
[Kavita] [2022-11-07 07:21:35.242 +00:00  933] [Error] Hangfire.Storage.SQLite.SQLiteDistributedLock Unable to update heartbe
at on the resource 'HangFire:locks:schedulepoller'. The resource is not locked or is locked by another owner.                
[Kavita] [2022-11-07 07:21:35.819 +00:00  1804] [Error] Hangfire.Storage.SQLite.SQLiteDistributedLock Unable to update heartb
eat on the resource 'HangFire:job:76:state-lock'. The resource is not locked or is locked by another owner.                  
[Kavita] [2022-11-07 07:21:36.515 +00:00  1289] [Error] Hangfire.Storage.SQLite.SQLiteDistributedLock Unable to update heartb
eat on the resource 'HangFire:job:76:state-lock'. The resource is not locked or is locked by another owner.   

**To Reproduce**
1. Install a fresh Kavita on Synology through docker'
2. Create 3 libraries
3. Add 3 series of serveral comics, book or magazines
4. inspect the journal of errors

**Expected behavior**
A functional and normal behavior of Kavita

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Comment by majora2007** [comment]
This is actually not an error and is expected, however I already switched out the underlying store so these won't appear.

**Comment by yves-gaignard** [comment]
So as it seems as a normal behavior, how can I debug what it happens ?
For reminder, until I added several comics, books and magazine, the server does not answering anything

**Comment by majora2007** [comment]
So the way these errors works are 2 part. 1. You have multiple tasks that are waiting to run, but due to my code, it's saying don't run concurrently. So it logs out about deadlocks. 
2. Is database is locked, which can be from above or can be due to an invalid config setup around write rights, etc. 

Yours looks like the first error. I would just restart Kavita. As I mentioned, I have switched out the underlying store which removes all these issues. I'm working on a hotfix to release soon.
