### ISSUE TITLE
Only one PDF magazine is shown when there are 8 of them in the serie

### ISSUE THREAD

**Issue by yves-gaignard** [Kareadita/Kavita#1640]
**Describe the bug**
I create a serie of PDF magazines: Bois +
This serie is represented by a directory containing 8 PDF files.
![image](https://user-images.githubusercontent.com/70469625/200336911-02af2d51-2369-40bf-8d2b-94884d85dab1.png)

Once parsed by Kavita, the serie is normaly shown but only one book is displayed on it : the first one in fact.
![image](https://user-images.githubusercontent.com/70469625/200337297-ba11aaab-293c-481a-9578-53cf78de48d0.png)

The library is declared like that:
![image](https://user-images.githubusercontent.com/70469625/200337603-4e861289-fe2d-4521-9838-efa97afc4891.png)

**To Reproduce**
1. Create a library on a directory containing several PDF magazine of the same serie
2. Scan this directory
3. Verify that the serie contains all magazines of the serie or see error

**Expected behavior**
The series must contain all PDF magazine of this serie as they have the same pattern name

**Screenshots**
See screenchot above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 0.6.0.0

**Comment by majora2007** [comment]
Did you read the wiki like I told you to? Because this isn't a supported configuration.

**Comment by yves-gaignard** [comment]
Yes I read the wiki and that's why I tried put in different directories a bunch of a same magazine.

Clearly something is going wrong as, in my example, the Bois magazine series is consdered as 561 pages (see the picture I sent above) when each magazine is only 70 pages and put 8 og them (70 x 8  = 560 pages)

The analyzer has found these 8 magazine of Bois serie but only the first one is reported in the serie

In addition, in the detail of the book (cover section), Kavita found those 8 covers (one for each magazine) (refer to next picture)
![image](https://user-images.githubusercontent.com/70469625/200393533-2404f692-f2fa-4a84-9b22-2dff57f3f8b3.png)

So I don't konw what I am doing wrong.
The section of the wiki about PDF does not present example of file structure to follow. (https://wiki.kavitareader.com/en/guides/managing-your-files/pdf) 

Thank you for your help

**Comment by yves-gaignard** [comment]
OK I found the problem

The issue number of each magazine must be prefixed by "v" or "vol". It was not the case in my example.
I apologize for the time you spent to read me.
Thank you again.
