### ISSUE TITLE
Series order failure

### ISSUE THREAD

**Issue by Curiousjoe13** [Kareadita/Kavita#1641]
**Describe the bug**
I have trouble organizing my Ebooks. I have no problem making the series itself like in the wiki page, but Volumes are all mixed up inside the series. I edit my EPUB files metadata in Calibre and make sure that all books have series tag and series index. But it's always like that.

![2022-11-07_22-17-29](https://user-images.githubusercontent.com/117684464/200408598-565692f8-4b99-4fde-9b86-21c7eda4692f.png)

**To Reproduce**
1. Change metadata in Calibre
2. Save to Disk
3. Save only EPUB format in one folder
4. Library scan

**Expected behavior**
All books in a series in a correct order

**Screenshots**
My settings in Calibre
![image](https://user-images.githubusercontent.com/117684464/200409038-d6014437-476b-4cd0-82be-e1924c556fa0.png)
![image](https://user-images.githubusercontent.com/117684464/200409145-26ce395c-e384-4608-9211-1fdd128083c0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Yandex. Browser
 - Version 0.6.0.0

**Additional context**
All data is in Russian. Files are provided
[Ведьмак 1.zip](https://github.com/Kareadita/Kavita/files/9955252/1.zip)
[Ведьмак 2.zip](https://github.com/Kareadita/Kavita/files/9955253/2.zip)
[Ведьмак 3.zip](https://github.com/Kareadita/Kavita/files/9955256/3.zip)

**Comment by majora2007** [comment]
Can you open volume 4 and please show the series index?

**Comment by Curiousjoe13** [comment]
Sure
![image](https://user-images.githubusercontent.com/117684464/200647090-68872b72-ca55-4b2f-a686-535d6d0d6570.png)
![image](https://user-images.githubusercontent.com/117684464/200647268-a4c84908-4433-40b2-8fa3-8346412cb309.png)

**Comment by majora2007** [comment]
This one is tricky because I can't reproduce it. For me, when using calibre:series_index, Kavita always orders correctly. So I'm not sure how to proceed on this.
