### ISSUE TITLE
"Promoting" a reading list results in HTTP error 500

### ISSUE THREAD

**Issue by amazing-rando** [Kareadita/Kavita#1642]
**Describe the bug**
While signed in as admin, I created a reading list with a few books with the intention to have this reading list viewable by every user on my server.  To do this, I "edit" the list and click on the "Promote" button but get a red error box stating that an internal server error has occurred.  Because of this error, the reading list is not visible by other users.

**To Reproduce**
1. Sign in as admin user.
2. Create a reading list.
3. Edit the reading list.
4. Click "Promote".

**Expected behavior**
I would expect to not receive an error message and I'd expect that the reading list would now be visible by all users on my server.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/44684502/200442189-46b5ea80-af85-43c7-b244-7496997acf9d.png)

**Desktop (please complete the following information):**
 - OS: Accessed with Windows 10, running on Docker hosted on an Ubuntu server.
 - Browser: Firefox
 - Version: 0.5.6.0

**Comment by majora2007** [comment]
This is a duplicate:
https://github.com/Kareadita/Kavita/issues/1608
