### ISSUE TITLE
database backup during scan causing lock error

### ISSUE THREAD

**Issue by spynotebook** [Kareadita/Kavita#1648]
I was trying to track down what set off a number of FOREIGN KEY constraint errors and it looks to me like a backup launched during my scan causing database locked errors. I am new to this so I could be wrong. Submitting issue on advice from discord.

[kavita20221111.log](https://github.com/Kareadita/Kavita/files/9993001/kavita20221111.log)

**Comment by spynotebook** [comment]
Attaching previous logs to show scan was going well up until that point.

[kavita20221110.log](https://github.com/Kareadita/Kavita/files/9993013/kavita20221110.log)

**Comment by majora2007** [comment]
Foreign key constraints should be fixed with upcoming v0.7.2 release.
