### ISSUE TITLE
Kavita ram usage rises after each folder sync

### ISSUE THREAD

**Issue by Shagon94** [Kareadita/Kavita#1656]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**

**To Reproduce**
1. Go to folder view
2. Note ram usage
3. Sync folder
4. See ram usage rise
5. Sync folder again (there don't have to be any changes in the folder)
6. See ram usage rise again

**Expected behavior**
Subsequent syncs shouldn't raise RAM usage.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker] Docker
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] (can be found on Server Settings -> System tab)

**Smartphone (please complete the following information):**
 - Version [e.g. 22] 0.6.1

**Additional context**

**Comment by Shagon94** [comment]
I managed to spam the sync folder feature and it causes the ram usage to jump from ~200MB to over 700MB even though there aren't any changes.

**Comment by majora2007** [comment]
This is expected. When you spam it, the OS still emits events and Kavita still needs to check if there is any work to do. You should not download directly to your library, per the wiki.

For your steps to reproduce, what does "Sync folder" mean?

**Comment by Shagon94** [comment]
Apologies, it is the "Scan library" button.

**Comment by majora2007** [comment]
Okay, then what do you expect? Of course RAM utilization will increase in a heavy operation. If you keep spamming it, it will have to allocate new memory. This isn't an issue in my eyes.
