### ISSUE TITLE
New re-install, scanner broken for nfs mounts

### ISSUE THREAD

**Issue by kmfstudio** [Kareadita/Kavita#1658]
**Describe the bug**

due to server problems, i've reinstalled kavita on a new docker instance( so new data-dir). completely new. docker:latest. which is now version 0.6.1.0

just like my previous install, i've mounted nfs directory into the kavita container.

but when trying to rebuild a library by adding a rootdirectory.  Kavita scanner  would get stuck on the first dir. it does sees 3 files, but that's it. nothing more in the logs. (when docker exec into kavita. i can browse the nfs files, edit, create and delete them. even chmod 777 them, but to no avail)

**To Reproduce**
new instance with docker compose

```
kavita:
    container_name: kavita-comics
    image:  kizaing/kavita:latest
    environment:
      - PUID=1000
      - PGID=1000
    ports:
    - 5000:5000
    volumes:
    - /docker/nfs/data/Strips:/nfs/Strips
    - /docker/nfs/data/Manga:/nfs/Manga
    - /docker/volumes/kavita/data:/kavita/config

```

/etc/fstab on host machine
`192.168.1.###/srv/storage/data /docker/nfs/data nfs  rw,auto,hard,intr,noexec,namlen=255,hard, 0 0`

3. recreate kavita and open page to add library which forces an initial scan

4. check status
6. See error

`
ORDER BY "t"."Id"
[Kavita] [2022-11-16 23:04:43.999 +00:00  32] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Strips
[Kavita] [2022-11-16 23:04:44.088 +00:00  32] [Information] Microsoft.EntityFrameworkCore.Database.Command Executed DbCommand (0ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT EXISTS (
    SELECT 1
    FROM "Series" AS "s"
    WHERE "s"."FolderPath" = '/nfs/Strips')
[Kavita] [2022-11-16 23:04:44.104 +00:00  32] [Information] Microsoft.EntityFrameworkCore.Database.Command Executed DbCommand (0ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT "g"."Id", "g"."ExternalTag", "g"."NormalizedTitle", "g"."Title"
FROM "Genre" AS "g"
[Kavita] [2022-11-16 23:04:44.127 +00:00  32] [Information] Microsoft.EntityFrameworkCore.Database.Command Executed DbCommand (0ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT "p"."Id", "p"."Name", "p"."NormalizedName", "p"."Role"
FROM "Person" AS "p"
ORDER BY "p"."Name"
[Kavita] [2022-11-16 23:04:44.147 +00:00  32] [Information] Microsoft.EntityFrameworkCore.Database.Command Executed DbCommand (1ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT "t"."Id", "t"."ExternalTag", "t"."NormalizedTitle", "t"."Title"
FROM "Tag" AS "t"
[Kavita] [2022-11-16 23:04:44.205 +00:00  32] [Information] Microsoft.EntityFrameworkCore.Database.Command Executed DbCommand (0ms) [Parameters=[@__libraryId_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT "s"."LastFolderScanned", "s"."Name", "s"."FolderPath", "s"."Format", "s"."Id", "l"."Id", "f"."Path", "f"."Id"
FROM "Series" AS "s"
INNER JOIN "Library" AS "l" ON "s"."LibraryId" = "l"."Id"
LEFT JOIN "FolderPath" AS "f" ON "l"."Id" = "f"."LibraryId"
WHERE ("s"."LibraryId" = @__libraryId_0) AND ("s"."FolderPath" IS NOT NULL)
ORDER BY "s"."Id", "l"."Id"
[Kavita] [2022-11-16 23:04:44.255 +00:00  30] [Information] Microsoft.EntityFrameworkCore.Infrastructure Entity Framework Core 6.0.10 initialized 'DataContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite:6.0.10' with options: DetailedErrorsEnabled 
[Kavita] [2022-11-16 23:04:44.269 +00:00  32] [Debug] API.Services.DirectoryService [ScanFiles] called on /nfs/Strips/Niky 01-03 (c)
[Kavita] [2022-11-16 23:04:44.270 +00:00  30] [Information] Microsoft.EntityFrameworkCore.Database.Command Executed DbCommand (1ms) [Parameters=[@__userName_0='?' (Size = 5)], CommandType='"Text"', CommandTimeout='30']
SELECT "l"."Id", "l"."Name", "l"."LastScanned", "l"."Type", "f"."Path", "f"."Id"
FROM "Library" AS "l"
LEFT JOIN "FolderPath" AS "f" ON "l"."Id" = "f"."LibraryId"
WHERE EXISTS (
    SELECT 1
    FROM "AppUserLibrary" AS "a"
    INNER JOIN "AspNetUsers" AS "a0" ON "a"."AppUsersId" = "a0"."Id"
    WHERE ("l"."Id" = "a"."LibrariesId") AND ("a0"."UserName" = @__userName_0))
ORDER BY "l"."Name", "l"."Id"
[Kavita] [2022-11-16 23:04:44.283 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library responded 200 in 28.6831 ms
[Kavita] [2022-11-16 23:04:44.304 +00:00  32] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 3 files for /nfs/Strips/Niky 01-03 (c)
[Kavita] [2022-11-16 23:04:53.275 +00:00  4] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages responded 200 in 0.7096 ms
[Kavita] [2022-11-16 23:05:08.285 +00:00  30] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages responded 200 in 12.5057 ms`

**Expected behavior**

just like previous versions, kavita should just scan and add the files.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker]
 - Docker using driver fuse-overlayfs 
 -chrome
 - Version
 -Version
0.6.1.0

**Comment by scare376** [comment]
The scan loop changed. I would read over this and make sure your library is following the requirements. Keep in mind when it says root folder it's talking about the folder you selected for the library. https://wiki.kavitareader.com/en/guides/managing-your-files/scanner#introduction

**Comment by kmfstudio** [comment]
some more testing:

copying the nfs-directory to a local directory and mounting that in docker does allow the scan to work (on the local directory). so it's something wrong with nfs mount. which is strange, as i can exec into the kavita docker and change the nfs-ed files. kavita is running as root so that's the same user.
I do understand that kavita does not modify the files themselves. and the first scan won't open the files to do covers.  so what can be wrong if listing the nfs does work? the log cearly says 
` [Kavita] [2022-11-16 23:04:44.304 +00:00 32] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 3 files for /nfs/Strips/Niky 01-03 (c)`

What should happen after that?
setting the logging level to trace does not give any more info

**Comment by majora2007** [comment]
Hi,
First off, your opening post is not showing an error, it's just showing log output. Not once do I see [Error] in the logs here.

Second, what version did you upgrade from? There are limits on how long ago you update from, as I remove migrations for user data after so many updates (4 updates ago to now, you would loose user data - wiki states update 2 versions at a time). I ask this to gain context if there is a DB issue that wouldn't be known unless we knew this info.

Third, for your reply. You found 22 files. Kavita will process them and write to the Database. You should stay on Debug log level to get the most benefit. Kavita also DOES generate covers on any scan if it's applicable.

This is def some sort of docker mounting issue, which is not my specialty. @therobbiedavis @ThePromidius can you please help support this user.

**Comment by kmfstudio** [comment]
@majora2007 that is exactly the problem, i see no error. kavita just stopped scanning without further messages. this is what makes it so hard to debug.

I'd expect some insert statements too, but it just doesn't. so i think something is amiss while checking those files.

anyway, i've found a workaround. by mounting the nfs directly with docker, kavita was able to scan and continue

like this

`
  kavita:
   container_name: kavita-comics
   image:  kizaing/kavita:latest
#   restart: unless-stopped
   ports:
    - 5000:5000
   volumes:
    - /docker/volumes/kavita/data:/kavita/config
    - type: volume
      source: nfs
      target: /nfs
      volume:
         nocopy: true

volumes:
  nfs:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.190,nolock,soft,rw"
      device: ":/srv/storage/syncthing-data"`

I do wish you'd have an explanation on the cause of the previous problem. as i never had to mount nfs like this.

**Comment by majora2007** [comment]
Let's give Robbie and Promidius a chance to debug. I'm not very adept at docker other than the basics. Many other people are using docker just following the config we have on our wiki, so there is def something else amiss here. 

Okay, 5.6 wasn't too long ago. There are often users coming from versions a year back, where the software was something completely different. Btw, read through the changelogs, setting up user accounts is much more streamlined now so should be easier for you now.

**Comment by therobbiedavis** [comment]
@kmfstudio I do not use NFS shares, but from what I've gleaned from other people's issues your workaround solution is indeed one available way to mount nfs shares inside docker (and likely the easiest). Mounting the volume directly as you first tried to do is not a reliable method without other flags and a volume plugin as seen here: https://forums.docker.com/t/how-to-mount-nfs-drive-in-container-simplest-way/46699/7
