### ISSUE TITLE
Arbitrary password length limit

### ISSUE THREAD

**Issue by ngInit** [Kareadita/Kavita#1661]
**Describe the bug**
It was mentioned [here](https://github.com/Kareadita/Kavita/issues/204) that the password length limit was arbitrary. So why was the solution arbitrarily limiting it again to 32? This issue is just going to keep coming back with someone else wanting a higher limit than the last.

The limit should be removed or be a configurable option.

**Comment by majora2007** [comment]
I'm not interested in any changes to the password length. I think it is fine as it is.

**Comment by ngInit** [comment]
Then the password length should at least be enforced on the login screen. It makes it very difficult to sign in to the app using a password longer than 32 characters when that password gets limited on account creation but not the login screen.
