### ISSUE TITLE
Kavita OPDS + Moon Reader Pro = XML Document Displayed

### ISSUE THREAD

**Issue by createchange** [Kareadita/Kavita#1665]
Hello! First, sorry if this is a bad report. I am entirely new to the world of ebook and document management systems. I have gone through a few options this evening to figure out how I can centrally manage ebooks. The path this evening has been:

- standalone server with SFTP (lacking all the obvious niceties that I have since discovered exist with an application such as Kavita)
- Komga (doesn't support epub)
- Calibre (works fine)
- Kavita (looks to meld best of all worlds)

As I am using Moon Reader as my ebook app of choice, I am looking to use OPDS functionality. I have had no issues configuring this with both Komga and Calibre, but seem to be hitting a snag with Kavita. While I have enabled OPDS on the Kavita server, and utilized the link provided within my user settings, Moon Read doesn't seem to properly parse the response. Rather than getting a navigable library, I receive an XML document.

**To Reproduce**
1. Run Kavita with Docker command provided in documentation
2. Index resources
3. Enable OPDS
4. Configure Moon Reader with OPDS link generated by system

**Expected behavior**
Navigable library, similarly to what has been the case with other applications I have configured OPDS with.

**Screenshots**
Can provide upon request, but writing this from tablet. Github isn't wanting to process the screenshots I have captured.

**Desktop (please complete the following information):**
 - OS: Macbook M1, Docker 
 - Browser N/A
 - Version 0.6.1

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab S7
 - OS: Android 12

**Comment by majora2007** [comment]
Hi, this should work as I test it every release.

Please validate that OPDS is enabled on your server (just double check the setting).

Please tell me what is in the XML? There should be some text in there.

Please tell me if the host is localhost or 192.x.x.x? Are you connecting on the same network or an external one (you need a reverse proxy). 

If you haven't, double check our wiki on this topic. Make sure you're grabbing the full URL and not putting any username/password in the readers.

**Comment by createchange** [comment]
Hi, thank you for your prompt response. I am traveling, and did not bring my Android device with me. 

With that said, in troubleshooting, I should have tried another client application. I only have an iOS device to test with, but just downloaded and configured tiReader on my iPhone - this consumed the feed just fine. So, it seems like the issue may have been with the Android app I was using, rather than the feed itself.

For posterity - I am accessing Kavita via LAN, as well as via Wireguard. I tested with both internal IP addresses, and those worked fined with the iOS app.

I will have to revisit the configuration with Moon Reader when I return home. If the problem persists, and there is any question whether the problem is server side, I will re-open with more details.

Happy Thanksgiving :)

**Comment by SamBouwer** [comment]
Solution as presented here worked for me: delete the OPDS entry, close the app, restart the app, create new entry.

https://www.reddit.com/r/KavitaManga/comments/vsf96f/cant_get_moon_reader_opds_working/

**Comment by drandarov-io** [comment]
Just to confirm: The workaround still works in 2026:
1. Delete the Kavita catalog from Moon+.
2. Fully close/force-stop Moon+.
3. Reopen it.
4. Add the OPDS URL again.
(I also rerolled the OPDS URL)

But for anyone else who might find this in the future:
I also had to add `^/api/opds/.*$` to unauthenticated URLs in Authentik.
