### ISSUE TITLE
Up/Down keyboard keys in webtoon mode don't work as expected

### ISSUE THREAD

**Issue by ItsABlackScreen** [Kareadita/Kavita#1670]
**Describe the bug**
When the comic reader is in webtoon mode, pressing the up/down keys produces very inconsistent results.
Pressing they key works some times, but other times it jumps all over the place. 
In the middle of the chapter when pressing the up key, it sometimes loads a previous chapter and when pressing the down key it loads to a few pages in the next chapter. 

**Expected behavior**
Up/Down Keys just scroll the current page without jumping around. 

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Browser : Tested on both firefix and chrome
 - Version :    0.6.1.0

**Additional context**
Scrolling the page using the mouse works as expected, so this is limited to the keys.
In the wiki 
https://wiki.kavitareader.com/en/guides/start-reading/comic-manga-reader

I saw that shortcuts were listed for *up and down* and *left and right* reading directions, but not for webtoon. 
Is this the case that there aren't any shortcuts for webtoon mode?

**Comment by majora2007** [comment]
Webtoon mode wasn't designed with Keyboard keys in mind because it's completely scrolling based, so you can't really move a "page" at a time.

**Comment by ItsABlackScreen** [comment]
Hmm, I thought as much but just wanted to be sure. But I would still prefer keys since, scrolling for a long time gets tiring very quickly, especially in long  webtoons. 
Since this isn't a bug and i guess more of a feature request, this can closed it if it breaks the rules.

**Comment by majora2007** [comment]
I just took a second look at this and it's working as expected actually. You can scroll by holding the up/down keys and it moves consistently. Continuous reading mode works as well in the Webtoon reader, so I'm going to close this out.
