### ISSUE TITLE
An API to know the dimensions of the pages

### ISSUE THREAD

**Issue by hgourvest** [Kareadita/Kavita#1683]
**Describe the bug**

There is no API to know the dimensions of each page of a book.
This information is useful to facilitate integration into third party reader.

**Expected behavior**

Ideally, an api of this form returning a json packet
/api/reader/get-pagesizes?chapterId=123
[{width: 1080, height: 1920}, ...]

**Additional context**

The dimensions of each page are used to prepare the layout and to avoid visual jumps in the interface or during animations when the image is presented to the interface asynchronously. It allows you to know how to assemble the double pages or to know where to scroll in the case of a continuous reading mode when you resume reading.

**Comment by hgourvest** [comment]
It is also necessary to know the path of the file in the archive. This is important for files that contain several issues in separate folders, it allows you to build a table of contents and avoid assembling two pages from different books in double-page mode.

ex:
[{"width": 1080, "height": 1920, "filename": "/foo/bar/001.jpg"}, ...]

**Comment by majora2007** [comment]
Kavita does all that work for the reader already, so when you request page 2, it will grab it from a flattened cache and not have to worry about nested folders or any details of the archives (Kavita supports archives split into parts to make up one issue).

**Comment by hgourvest** [comment]
I'm sorry, I tried with an archive containing several subfolders with images inside and nothing happened. There is still only one book and the pages are assembled incorrectly in double page mode. Is there an option to enable ?

**Comment by majora2007** [comment]
Are you talking in your reader or mine? If mine, there is an open bug I'm working to fix the double page readers.

**Comment by hgourvest** [comment]
Your reader. Anyway, the library only shows one book, so I need the file path to extract the TOC and put the files together as I want.

**Comment by majora2007** [comment]
Let's discuss in discord, I need to better understand and Github is not an ideal place to talk, we can update the issue if there are different requirements.

**Comment by majora2007** [comment]
So this is what I came up with:
![image](https://user-images.githubusercontent.com/735851/206906506-1158af46-3d67-48be-a8af-fe5630b12fa8.png)

As discussed, I could also include the file name, but Kavita doesn't maintain folder structure once cached. instead all nested folders are flattened and sorting is maintained via natural sort. The flattening ensures there is no conflict and as such, filenames are useless.

I did however have an idea of including said filenames of the cached. The folder is represented as foldername_original file name or firstfolder_anothernested_filename. Let me know if this would be helpful for you.

**Comment by hgourvest** [comment]
Thanks a lot.

This naming convention can allow me to distinguish the folders, but the name of the folder must then be transformed to remove a possible underscore character. However, the file name is used to generate the table of contents which is presented to the user.

You can flatten the folder structure by encoding the file path in URI format. You will then probably have to sort the files by decoding the URI format. Pay attention to the # character in this case, there are often problems with it.

**Comment by hgourvest** [comment]
For information, I didn't need the full path of the file on disk, only the "folder_file.jpg" part. If you remove the parent path it won't bother me.
