### ISSUE TITLE
Feature Request: MOBI support

### ISSUE THREAD

**Issue by latetedemelon** [Kareadita/Kavita#1684]
Awesome product, was curious if MOBI support was on the roadmap?  Perhaps via libmobi?

https://github.com/bfabiszewski/libmobi

**Comment by scare376** [comment]
Feature requests go to feats.kavitareader.com. There is already a mobi request. https://feats.kavitareader.com/posts/3/mobi-support

**Comment by Fmstrat** [comment]
@scare376 That link no longer functions. Is there still an open request for this anywhere?

**Comment by majora2007** [comment]
@Fmstrat Feature requests go on our Github Discussions. Mobi will not be supported. It's a dead format and there are no libraries that make it easy to integrate.
