### ISSUE TITLE
Fix display of chapters with no cover in double-page mode

### ISSUE THREAD

**Issue by w108x** [Kareadita/Kavita#1685]
As already discussed on discord, many scanlated chapters do not have a cover image and start directly at the first page. Mangadex's webreader gives an option to start the chapter at either page01 or page 01+page02 by having the option "offset double page spreads".

Komga and Cdisplayex have also the options to toggle the display mode to either with or no cover.

This allows chapters without a cover image to display properly in double page mode.

To add a little bit more context, manga chapters are designed with a white space in the middle, so that they can be bound to volumes. As is now, if a chapter does no have a cover image, it is being displayed incorrectly like so in Kavita:

https://i.imgur.com/7ivMbZE.png

And this is how the pages would be properly displayed, as intended:

https://i.imgur.com/0dbGwK7.png

**Comment by majora2007** [comment]
Please copy paste this to feats.kavitareader.com. GitHub is just for issues. Thank you.

**Comment by w108x** [comment]
how is this not an issue if it makes reading in double-page mode impossible due to wrongly aligned pages?

I'm not gonna waste more time on this, you can post it there yourself.
