### ISSUE TITLE
Expose the last modified date of the reading progress in the API

### ISSUE THREAD

**Issue by hgourvest** [Kareadita/Kavita#1700]
Please expose the last modified date of the reading progress in the API for each chapter.

Reason:
It would be useful to have this information in case you use several devices in offline mode, it would allow to keep the most recent reading status when you sync back.

Api concerned:
/api/Reader/get-progress
/api/Reader/progress
/api/Series/volume
/api/Series/volumes
/api/Series/chapter
/api/Series/chapter-metadata
/api/Series/series-detail

**Comment by majora2007** [comment]
Please add the APIs you want it on and give the reason, so when i take this up, i can ensure i meet expectations.

**Comment by hgourvest** [comment]
I probably wasn't clear enough. I need the date of modification of the reading status of the chapter to be mentioned in the dto chapter object next to "pagesRead". It would also be necessary to have it in the reading list which does not expose a chapter object (I wonder why by the way).
