### ISSUE TITLE
Fullscreen not working on iPad

### ISSUE THREAD

**Issue by Draknars** [Kareadita/Kavita#1701]
**Describe the bug**
Fullscreen option does not work on iPad, when I click nothing happen.

**To Reproduce**
1. Open any book or comics
2. Click on Fullscreen button (for Epub - Menu -> Fullscreen -> Enter)
3. Then Nothing Happen.

**Expected behavior**
I would expect that the page takes the Fullscreen.

**Screenshots**
Hard to see "Nothing" happening, but when I click literally nothing happen.
![IMG_0013](https://user-images.githubusercontent.com/40360399/208164919-047595a5-01b5-4f13-9148-3e308a7e900c.PNG)
Easier to see here, it should already be in Fullscreen mode as it shows "Exit" to exit from it, but you can see that it is not.
![IMG_0014](https://user-images.githubusercontent.com/40360399/208164911-36dca685-a80e-4aa8-be56-79239fa962fb.PNG)

**Kavita (please complete the following information):**
 - OS: Docker
 - Version : 0.6.1.0

**Device (please complete the following information):**
 - Device: iPad Pro 3rd Gen
 - OS: iPadOS 16.2
 - Browser : Tried on all of them, Chrome, Edge, Safari, Firefox

**Additional context**
Not sure why I never thought to report this, but I mainly use my iPad to read on Kavita, and this feature never worked on iPad. It works on my PC and on my Google Pixel 3A XL, just not iPad 

Also, a slightly unrelated note regarding UI, as you can see from the Screenshots
![image](https://user-images.githubusercontent.com/40360399/208166285-217d1145-cfad-43fc-a04e-1ed621c96d88.png)

iPads have a white bar in the bottom center (called Handlebar I believe) "Used" to go back to your home screen. As far as I know, this is not removable. As per the Screenshot, you can see that it's over the "Fullscreen" icon, not sure if anything can be done about that but I thought I would point it out. 

At first, I thought it was the issue, but even when zooming enough so that it doesn’t cover it anymore make no difference, so it purely a request from a cosmetic point of view.

Let me know if you need anything else!

**Comment by majora2007** [comment]
For the handlebar, I can def take care of that. @therobbiedavis when you are free, can you give this iOS a spin and see what might be happening for fullscreen?
