### ISSUE TITLE
Features - add ebook

### ISSUE THREAD

**Issue by arist0v** [Kareadita/Kavita#1703]
I would like to have the ability to add ebook from the web interface, so i could host Kavita on a remote server without the need to access the filesystem.

**Comment by mystic-man-rhino** [comment]
Use FTP to upload.

**Comment by paulcsiki** [comment]
I run this within kubernetes and accessing the storage is not as easy as it sounds. I too would be interested in an upload feature.

**Comment by scare376** [comment]
https://github.com/Kareadita/Kavita/discussions/2668#discussion-6157840 this is the discussion for upload. It is very unlikely to happen.
