### ISSUE TITLE
Special series version treated as non-special

### ISSUE THREAD

**Issue by papaj-na-wrotkach** [Kareadita/Kavita#1704]
My library looks like this
- Library root

  - Some Manga Title

    - Some Manga Title v01.cbz
    - Some Manga Title v02.cbz
    - Some Manga Title v04.cbz
    - Some Manga Title v03.cbz
    - ...
    - Some Manga Title v14.cbz

  - Some Manga Title (Special Edition)

    - Some Manga Title (Special Edition) v01.cbz
    - Some Manga Title (Special Edition) v02.cbz
    - Some Manga Title (Special Edition) v03.cbz
    - Some Manga Title (Special Edition) v03.5.cbz
    - ...
    - Some Manga Title (Special Edition) v11.cbz

I would like these two directories to appear as different series since the "Special Edition" is a compilation of the original series with additional stories. Kavita treats these two as one series:

![image](https://user-images.githubusercontent.com/29522138/208548530-6082fe46-a817-4a9f-9161-f209cc727fd1.png)

I suppose it's a problem with how the app treats special characters in file path (like the brackets) since when I changed the file paths (directory name and file names) not to contain them, a new manga appeared... With wrong title though - it ignored "Special" and left only "Edition":

![image](https://user-images.githubusercontent.com/29522138/208549463-274dd82d-2012-438c-a82b-f8781e6b626f.png)

**Desktop:**
 - OS: Manjaro Linux
 - Version 0.6.1.0

**Comment by papaj-na-wrotkach** [comment]
Thanks, I would like the title to appear as in original title. Many series nowadays have very complicated titles containing special characters like `∬` so ComicInfo sounds good but I also don't want to change the files content. Is there any way to have `ComicInfo.xml` in the series Folder. `ComicInfo.xml` for every volume would also be very useful if possible (e.g. naming xml for file `Manga Title v01.cbz` as `Manga Title v01.xml` or just `v01.xml`).

**Comment by majora2007** [comment]
You can change it manually once in Kavita's UI to have it show with () instead. Sidecar comicinfo is not something I'll be pursuing. You can use komf though to make the changes at the API level from scrapped data.

**Comment by papaj-na-wrotkach** [comment]
Yeah, I think `komf` with API mode is the best solution in my case. Thank you for providing me the info.
