### ISSUE TITLE
Expose file size in bytes in the REST API

### ISSUE THREAD

**Issue by hgourvest** [Kareadita/Kavita#1705]
I need to know the size of the files from the API, it's the "Bytes" field of the "MangaFiles" table. I would like this value to be exposed in the "File" objects of each chapter.

This information is necessary to provide statistical information on libraries, series ... and also to configure a progress bar when a file must be downloaded.

**Comment by majora2007** [comment]
We already have this information available via download size API.

**Comment by hgourvest** [comment]
that's great, but I still need to have this information in the File object of each chapter to avoid making an additional network request on each file when I scan a library.

**Comment by hgourvest** [comment]
Thank you, exactly what I need.
