### ISSUE TITLE
Unable to login to Kavita web UI: '[object Object]' and 'An error occurred while saving the entity changes. See the inner exception for details.'

### ISSUE THREAD

**Issue by SkipsterTheHipster** [Kareadita/Kavita#1709]
Since recently manually installing 0.6.1 to update the version on my server, I've been unable to login to the web UI for Kavita.

When I enter my credentials, I receive the following error messages in red error pop-ups in the window:

`[object Object]
`

and

`An error occurred while saving the entity changes. See the inner exception for details.`

I've attached my scrubbed logs, along with the copied error messages and the output in the FireFox Browser Console.

Please let me know if I've done something wrong, and need to make a change to fix this behavior, or if this is a known or unknown bug.
[skipster_kavita_logs.zip](https://github.com/Kareadita/Kavita/files/10316259/skipster_kavita_logs.zip)
[kavita_login_error.txt](https://github.com/Kareadita/Kavita/files/10316260/kavita_login_error.txt)
[kavita_scrubbed.log](https://github.com/Kareadita/Kavita/files/10316261/kavita_scrubbed.log)

edit: I also moved all files into separate subdirectories within the library directory, per previously stated instructions.

**Comment by majora2007** [comment]
You mentioned updating recently, what version did you update from?

**Comment by SkipsterTheHipster** [comment]
I don't clearly remember the specific version number – sorry – but it was a few releases back. I think it honestly might have been 0.5.4.2. I deleted kavita.db from /opt/Kavita/config/ after the new installation, as I thought I had read to do that as part of the upgrade process, and I didn't mind starting fresh in terms of database (I'm the only user currently).

**Comment by majora2007** [comment]
Okay well two issues. A) you deleted your database so you basically just restarted from scratch and b) you jumped a few too many versions in one go.

To fix this, restore a backup db from config/backups. Then upgrade every 2 versions. You don't need to touch anything in config. 

After that, everything should work for you.

**Comment by majora2007** [comment]
I'm going to close this ticket out. If you still have an issue, please re-open and comment.
