### ISSUE TITLE
Same book in different formats creates separate series

### ISSUE THREAD

**Issue by zeidoo** [Kareadita/Kavita#1710]
This may be a duplicate of https://github.com/Kareadita/Kavita/issues/1517. But that issue got sidetracked, so opening a new one as I'm not really sure I understood the main resolution.

I understood that Kavita doesn't use folder structures for series organization. However, there doesn't seem to be an easy way to group multiple copies of the same book in different format in a "Series" or at least a "Collection".

This is especially useful for Humble Bundle downloads (with the help of https://github.com/xtream1101/humblebundle-downloader) as it groups the book versions in the same folder as such:

```
CompTIA Security_ Certification Guide < -- folder
|-> comptiasecuritypluscertificationguide.epub
|-> comptiasecuritypluscertificationguide.pdf
```

Is there an easy way to automatically group these two in the same "Series"? Plex, for example, if you have the same movie in multiple copies, will still consider those copies as the same movie regardless of audio language or quality or edition or other differentiating factors. Plex will play the "default" version, but any user can choose the alternative version if they want. Kavita could do something similar, no?

If not, could I kindly get the technical reasons why it's not possible? I may take a stab at implementing such feature and make a PR if it's something that could be merged in. 

PS: One thing I got from the other issues, is that PDF's don't contain any metadata and that causes issues. Would Kavita be open to get the metadata info from external metadata (ie: metadata in a separate file that lives besides the PDF) ? Like XMP files in Photoshop and Lightroom (https://www.bwillcreative.com/what-are-xmp-files-in-photoshop-lightroom/).

**Comment by majora2007** [comment]
Hi, Kavita doesn't group different formats into the same series. So you'd have to split into separate folders, remove one of the files, or use a .kavitaignore at the root or at any folder to ignore whichever extension you don't want to show up. 

To support multiple formats in series would require rewriting a huge portion of core code, so it's not something I will be supporting. 

As for your suggestion, Kavita tries to not use any sidecar files as it enables bad practice. We are investigating alternatives for embedded PDF metadata (outside of just the standard as they are never tagged well).

**Comment by jcnventura** [comment]
New user of Kavita here. I really like what I see, but the lack of multi-format support is indeed annoying. All my ebooks are in as many formats as provided by the publisher. I like having PDFs for the perfect book experience when reading in large screens, but prefer epub on smaller screens. A solution where I'd have a single entry for a book and can press the available formats to open one of them would be highly desirable.

**Comment by majora2007** [comment]
@jcnventura as mentioned in my comment, this is not the place for feature requests and supporting multiple formats within one series is not something planned.
