### ISSUE TITLE
Blank page when trying to read, and I need to refresh multiple times

### ISSUE THREAD

**Issue by Moreasan** [Kareadita/Kavita#1711]
Sometimes when trying to read my mangas, I need to refresh multiple times to get the images. When looking at the requests, I saw 400 responses for requests for fetching images. The text says to refresh the page to allow re-caching of the images.

Can you give details of what happens? Also, it is really a bad experience, and we should show a message to the user. If I didn't look at the requests, I won't have known how to resolve the issue.

**Comment by majora2007** [comment]
What version and browser? Please provide information as per the template to help me help you. I just read 10k pages of manga with no issues.

**Comment by Moreasan** [comment]
I am using the master version from a week ago. I see 400 responses for requests `/api/reader/image?chapterId=152&page=127` and the response is `No such image for page 127. Try refreshing to allow re-cache.`. Waiting some seconds and resending the same request, the image is correctly fetched.

**Comment by majora2007** [comment]
So you're on 0.6.1, are you having this on local network or external via reverse proxy?if it's sending directly after a refresh, seems very odd. 

Next time that happens can you validate that the cache directory has the files for the chapter?

Also what browser is this occurring on?

**Comment by Moreasan** [comment]
Kavita is running behind a reverse proxy (Nginx). It did happen today but the time I connected to my server all the files were there, but the change date is the same time as the time I opened the chapter. 

I am using Firefox.

**Comment by Moreasan** [comment]
I should test it next time, but I need to change the configuration as the port is not exposed to the Internet.
Why do you think that it would be different without the reverse proxy ?

**Comment by majora2007** [comment]
Because only you had ever reported this issue. Usually issues where assets don't load, like in book reader, are due to reverse proxy properties. 

As mentioned, I've been reading a lot via reverse proxy and locally without any issues. So this is likely some external factor.

**Comment by Moreasan** [comment]
I checked today and the cache is empty. Also I saw the following logs:

`[Kavita] [2023-01-04 00:00:13.482 +01:00  109] [Information] API.Services.Tasks.CleanupService Starting Cleanup
[Kavita] [2023-01-04 00:00:13.482 +01:00  75] [Information] API.Services.Tasks.CleanupService Performing cleanup of Series that are Completed and have been fully read that are in Want To Read list
[Kavita] [2023-01-04 00:00:13.753 +01:00  109] [Information] API.Services.Tasks.CleanupService Cleaning temp directory
[Kavita] [2023-01-04 00:00:13.838 +01:00  109] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache & Temp directories
[Kavita] [2023-01-04 00:00:14.308 +01:00  109] [Information] API.Services.Tasks.CleanupService Cache and temp directory purged
[Kavita] [2023-01-04 00:00:14.309 +01:00  109] [Information] API.Services.Tasks.CleanupService Cleaning old database backups
[Kavita] [2023-01-04 00:00:14.419 +01:00  75] [Information] API.Services.Tasks.CleanupService Performing cleanup of Series that are Completed and have been fully read that are in Want To Read list, completed
[Kavita] [2023-01-04 00:00:14.745 +01:00  109] [Information] API.Services.Tasks.CleanupService Beginning cleanup of Database backups at "2023-01-04T00:00:14.7457100+01:00"
[Kavita] [2023-01-04 00:00:14.862 +01:00  109] [Information] API.Services.Tasks.CleanupService All expired backups are older than 30 days. Removing all but last backup
[Kavita] [2023-01-04 00:00:15.163 +01:00  109] [Information] API.Services.Tasks.CleanupService Finished cleanup of Database backups at "2023-01-04T00:00:15.1629499+01:00"
[Kavita] [2023-01-04 00:00:15.163 +01:00  109] [Information] API.Services.Tasks.CleanupService Cleaning deleted cover images
[Kavita] [2023-01-04 00:00:15.268 +01:00  109] [Information] API.Services.Tasks.CleanupService Performing cleanup of logs directory
[Kavita] [2023-01-04 00:00:15.337 +01:00  109] [Information] API.Services.Tasks.CleanupService Finished cleanup of logs at "2023-01-04T00:00:15.3377918+01:00"
[Kavita] [2023-01-04 00:00:15.338 +01:00  109] [Information] API.Services.Tasks.CleanupService Cleanup finished`

**Comment by majora2007** [comment]
Those logs are for the nightly cleanup, but could it be that you're reading at midnight and the cleanup is clearing out your files? (the next page would re-create them).

**Comment by Moreasan** [comment]
No, I am not reading at midnight (but around 19h). Yes, the files are recreated, but we should at least the message to the user instead of showing the blank page.
