### ISSUE TITLE
Do not leak full path for images' paths

### ISSUE THREAD

**Issue by Moreasan** [Kareadita/Kavita#1712]
The API `/api/reader/chapter-info?chapterId=XXX&includeDimensions=true` is returning the full path of the images. The full path may contain sensible information, and it is not a good practice to give a lot of information to attackers. Also, I don't think that the full path is used anywhere in the frontend.

**Comment by hgourvest** [comment]
related to this:
https://github.com/Kareadita/Kavita/issues/1683#issuecomment-1359493184

**Comment by majora2007** [comment]
Yup, this makes since. Oversight on my quick implementation. Thanks for reporting it.
