### ISSUE TITLE
Kavita won't index CBR files in directory unless they are strictly organized

### ISSUE THREAD

**Issue by anaisbetts** [Kareadita/Kavita#1715]
**Describe the bug**
Despite trying all three different library types (Comic/Manga/Book), none of my files are indexed for a certain collection of files. 

**To Reproduce**
1. Add a library of files with the filename format `Nintendo Power Issue 001.cbr`, `Nintendo Power Issue 002.cbr`, etc...
2. View the Library
3. No files are found

**Expected behavior**
One of the three library types should index this content, even if it is in an odd order. A library type that Always finds all files, even if they aren't organized a certain way, would be Helpful

Kavita v0.6.1

**Comment by majora2007** [comment]
Are you following the scanner requirements? It sounds like you aren't. Kavita supports rar and rar5. 

https://wiki.kavitareader.com/en/guides/managing-your-files/scanner#file-layout

**Comment by anaisbetts** [comment]
My point is more, that there should be a library type that *doesn't care* about strict organization requirements, and should simply index every file it sees

**Comment by majora2007** [comment]
That is not the direction of the software. Please validate your following the requirements and report back if it's not working for you. For now, I'll close the issue.

**Comment by anaisbetts** [comment]
No worries, thanks for having a look
