### ISSUE TITLE
failed to fetch PDF

### ISSUE THREAD

**Issue by tXJtqlb3bbeKD1yW8SV7** [Kareadita/Kavita#1721]
PDF don't load and prompt me to download the file instead.

 - OS: Windows (not using docker)
 - Browser: Brave
 - Version: 0.6.1.0

![brave_ZjqlBQhVh8](https://user-images.githubusercontent.com/88219689/210616111-54b21ea7-01a6-48d8-bb2e-2ea73673d315.gif)

**Comment by majora2007** [comment]
Do any PDFs work for you or is it just this? Are you using a reverse proxy to access?

**Comment by tXJtqlb3bbeKD1yW8SV7** [comment]
I've tested four and none of them worked so far. No, I'm not using reverse proxy. Just set up the folder structure, executed the the kavita.exe and open it on Brave.

**Comment by majora2007** [comment]
...I mean, you setup a library already and scanned right? Have you walked through the First Time Setup on the wiki?

**Comment by majora2007** [comment]
Okay, then please send me the file via discord or something besides Github and I can test it locally.

**Comment by tXJtqlb3bbeKD1yW8SV7** [comment]
Unfortunately, I don't have a discord account. Hope you don't mind downloading it from here https://gofile.io/d/30l7PX. Notice that the reader of the site that I've uploaded the file to is also throwing the same error, maybe the issue is the PDF.js version the kavita and the site are using. The file opens normally using Brave' PDF reader, though.

**Comment by majora2007** [comment]
I just tested this on my local with Chrome and Brave and it works. 

![image](https://user-images.githubusercontent.com/735851/210649492-ff8f49f1-14a1-48b8-a50b-92e9b5723c4a.png)

**Comment by daVinci2793** [comment]
> I figured it out. It was the Internet Download Manager extension messing things up. Thanks for your patience and help.

I am having the same issue, and I also use IDM. Can you be more specific about what your fix was?
