### ISSUE TITLE
Image Selection Issue

### ISSUE THREAD

**Issue by JShiesty-dev** [Kareadita/Kavita#1725]
**Describe the bug**
Sometimes it takes multiple tries to set the cover image for collections and library images. It may be the same for other parts of the server like series covers, I am not sure.

**To Reproduce**
1. Create a few collections or a library.
2. Try to set the cover on some collections or the library.
3. Notice that sometimes it takes multiple attempts before it actually works (even if you refresh after a failed attempt).

**Expected behavior**
Being able to set the cover or library image on the first try.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker]
 Windows 11
 Chrome
 - Version [e.g. 22] (can be found on Server Settings -> System tab)
 0.6.1.23

**Comment by majora2007** [comment]
I'm going to need logs to be able to help as for me, covers generate first try.

**Comment by majora2007** [comment]
Going to close this as version is old and no one provided information.
