### ISSUE TITLE
[Epub] Scroll Mode UI Issue

### ISSUE THREAD

**Issue by officialdevjackson** [Kareadita/Kavita#1726]
**Describe the bug**
When using scroll mode and reading a book, the bottom part of the UI doesn't follow as you scroll. *See screenshot*

**To Reproduce**
1. Turn on scroll mode.
2. Read a book.
3. Tap to bring up the UI.
4. Scroll down.
5. Notice the bottom part of the UI doesn't follow as you scroll. *See screenshot*

**Expected behavior**
The UI follows as you scroll.

**Screenshots**
![5RZoLaQMy](https://user-images.githubusercontent.com/102483672/210931264-59a8cc4b-7559-4202-85d8-328518ac59ce.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker]
 Windows 11
 Chrome
 - Version [e.g. 22] (can be found on Server Settings -> System tab)
 0.6.1.23

**Comment by majora2007** [comment]
I'm not able to reproduce this on v0.6.1.26, but I do see that on immersive mode, the bottom menu bar is not rendering at all.

**Comment by majora2007** [comment]
Nevermind, I was able to reproduce. I'll get this sorted.
