### ISSUE TITLE
[Epub reader] Pagination not resetting scroll

### ISSUE THREAD

**Issue by rastacalavera** [Kareadita/Kavita#1727]
**Describe the bug**
When navigating using tap pagination on a mobile device, moving to the next page does not take the reader to the top of the next page. 

**To Reproduce**
2. Click on ‘tap pagination’
3. scroll down and tap to advance

**Expected behavior**

Expected behavior would be that when the reader taps to advance, they are taken to the top of the next page. 

**Screenshots**
SEE below FOR VIDEO.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: safari
 - Version ?

**Smartphone (please complete the following information):**
 - Device: IPAD MINI, IPHONE XS
 - OS: 15.7.2
 - Browser: safari
 - Version ?

**Comment by majora2007** [comment]
Hi, I need some more context as the video, while helpful, isn't clear. Is the reader not scrolling back to top for you automatically? 

This is something that's working on my local, what version of Kavita are you running?

**Comment by rastacalavera** [comment]
Correct. When using the navigation arrows, it moves as expected. When using
tap pagination, it does not do that. My version is 0.6.1.0

**Comment by majora2007** [comment]
This is already fixed in the nightly and will be in the upcoming v0.7 release. I have however added it to the release shakeout testing matrix so it doesn't get missed again. Appreciate the bug report.
