### ISSUE TITLE
Dockerfile deployment failed

### ISSUE THREAD

**Issue by AncientCatz** [Kareadita/Kavita#1732]
**Describe the bug**
```
-----
> [copytask 4/6] COPY UI/Web/dist /files/wwwroot:
-----
failed to compute cache key: "/UI/Web/dist" not found: not found
```

**To Reproduce**
1. Deploy using Dockerfile

**Expected behavior**
Deployment successful

**Desktop (please complete the following information):**
 - OS: Docker
 - Version v0.6.1

**Comment by majora2007** [comment]
This looks like you are trying to build our docker file vs use our docker image. Can you clarify your end goal?

**Comment by AncientCatz** [comment]
> This looks like you are trying to build our docker file vs use our docker image. Can you clarify your end goal?

I want to deploy Kavita with Dockerfile, but ended up failing with the error as I stated above

**Comment by majora2007** [comment]
We have a wiki and a prebuilt image for you to use. Shouldn't ever need to deal with the source code.

https://wiki.kavitareader.com/en/install/docker-install

**Comment by AncientCatz** [comment]
> We have a wiki and a prebuilt image for you to use. Shouldn't ever need to deal with the source code.
> 
> https://wiki.kavitareader.com/en/install/docker-install

I know about that, but the service where I built Kavita doesn't support docker-compose, it only supports Dockerfile

**Comment by majora2007** [comment]
The command is given at the very top of the article if you're not using a compose file.

**Comment by AncientCatz** [comment]
> The command is given at the very top of the article if you're not using a compose file.

The problem is I can only run the Dockerfile
