### ISSUE TITLE
Mandating subdomains for Kavita Reader and HTTPS

### ISSUE THREAD

**Issue by FlattusBlastus** [Kareadita/Kavita#1733]
I would really like to port forward 5000 via my router and be able to add a certificate in order to secure Kavita Reader on the web. 

The current solution requires extra software AND a subdomain like kavita.mydomain.com. No-IP is mentioned in the wiki so that would be kavita.mynoip.hopto.org.

Use cases:
1) External access for myself when out and about.
2) External access for my friends.

Please consider adding this capability to the absolute best pdf and comic reader out there!
Thank you for all your work!

**Comment by scare376** [comment]
Feature requests go on https://feats.kavitareader.com
