### ISSUE TITLE
GMX SMTP not working.

### ISSUE THREAD

**Issue by OuterWinnie** [Kareadita/Kavita#1738]
I'm trying to use GMX as SMTP, because it has a 50MB file limit (specially useful for mangas) but i'm getting a "400 error, there was an error sending the file to the device". It only happens with GMX, i have tried with Gmail and works fine (but has a 25MB file limit).

It's hosted in a Raspberry Pi 4, through Docker, Kavita 0.6.1.0 and accessing the UI trough Windows 11 22621.963 OS using Edge.

**To Reproduce**
1. On KavitaEmail put the GMX SMTP configuration: 
SSL/TLS: mail.gmx.com:465 
STARTTLS : mail.gmx.com:587
User: Your GMX email
Password: Your GMX email password
(https://support.gmx.com/pop-imap/imap/server.html)
2. Try sending any file
 
**Screenshots**
![image](https://user-images.githubusercontent.com/6392320/211662576-e76361b0-0b85-4d5d-a5ca-5f59a7cb8c85.png)

**Desktop (please complete the following information):**
 - Host OS: Raspberry Pi, Docker 
 - Browser: Edge on Windows 11
 - Version: Kavita 0.6.1.0

Docker Logs:

[_kavita-email_logs.txt](https://github.com/Kareadita/Kavita/files/10386857/_kavita-email_logs.txt)

**Comment by majora2007** [comment]
Can you please post your SMTP config WITHOUT your password and with a censored version of your GMX username/email?

**Comment by OuterWinnie** [comment]
> Can you please post your SMTP config WITHOUT your password and with a censored version of your GMX username/email?

Here it is:
![image](https://user-images.githubusercontent.com/6392320/211691498-2d290505-84fa-40f3-b4f8-2b47281b5dde.png)

**Comment by majora2007** [comment]
Can you try with port 25? Also you have size limit of 25 bytes, not 25 MB. 26214400 would be 25 MB.

**Comment by OuterWinnie** [comment]
> Can you try with port 25? Also you have size limit of 25 bytes, not 25 MB. 26214400 would be 25 MB.

Changed the port to 25 and it works now. Thanks, and sorry for the trouble!

**Comment by OuterWinnie** [comment]
Sorry for reopening this, but i can't send files over 25mb for some reason. I have change "SIZE_LIMIT" to "52428800" that is the maximum for GMX but when i try to send a file over 25mb, it gives me a "file is too large" error.

**Comment by OuterWinnie** [comment]
Log added:
[_kavita-email_logs.txt](https://github.com/Kareadita/Kavita/files/10394446/_kavita-email_logs.txt)

**Comment by majora2007** [comment]
What is your logging level set to in the config.yml? It's showing bad request, but logs look fine.

**Comment by OuterWinnie** [comment]
> What is your logging level set to in the config.yml? It's showing bad request, but logs look fine.

I have this setup on Docker, how can i check/change that? The only thing that i can find is this:
![msedge_2023-01-11-23-06-48](https://user-images.githubusercontent.com/6392320/211928600-a88a3dad-15fa-4284-937d-fa5a4b413ab2.png)

**Comment by majora2007** [comment]
You will need to go inside the Kavita email service likely and pull from config/logs/ folder.

**Comment by OuterWinnie** [comment]
Here is the log, with debug level:
[_kavita-email_logs.txt](https://github.com/Kareadita/Kavita/files/10406958/_kavita-email_logs.txt)

**Comment by majora2007** [comment]
So if you read the log, it tells you the issue. Your certificate with GMX is not valid.

**Comment by OuterWinnie** [comment]
Forgot about tell you what happened, the last log wasn't actually the problem sorry. 

I don't know who is the one developing the docker container (kizaing/kavitaemail), but the environment variable "SIZE_LIMIT" isn't working and it's not overriding the default "26214400". I have edited the internal docker container appsettings.json (stored in the config folder) and changed the values to "52428800" and it works now.

**Comment by majora2007** [comment]
Oh good to know. I'll look into the docker and make sure it's updating the config correctly.
