### ISSUE TITLE
Filename parsing issue

### ISSUE THREAD

**Issue by rosystain** [Kareadita/Kavita#1743]
Kavita's filename parser is too radical for number detecting.

For example:

I have some mangas called Doujinshi which named start with 'Event Number' just like '(C90) [Author] Title.cbz'. The filename parser will always take it as chapter 90.  Deleting '(C90)' from the filename is a solution but I don't want to lose these information.

Besides, some mangas have only 1 volume. Kavita take them as 'Special' if they don't have a filename with a vol number. That is not a big problem for me but if there is a number which is not related with volume/chapter in the filename like 'Classroom of the Elite 2nd Year.cbz', problem occured. For this case, Kavita will consider its format as 'Special' and take 'Classroom of the Elite' as its Title but '2nd Year' will be ignored.

I know Kavita did a lot of work to make the parser better but it is difficult to match everyone's file structure or filenaming. It brings convenient for some people while it brings problems for others.
In my opinion,  a simple and strict naming rule is suitable for most of people. For example, chapter/volume number should only be detected when they follow behind text like 'ch' or 'vol' because Kavita will never really know if 'Title (2)' means chapter 2 or volume 2. It will not affect people who orgianze their books according to the documentation or some community rules but can reduce the probability of errors for the others.

Hoping my poor English did not give you a wrong understanding~

**Comment by majora2007** [comment]
Thank you for the post and I do understand your situation, but there are alternatives rather than relying on filenames - metadata.

Kavita supports ComicInfo spec and will use that above any filename parser information.

There are many tools out there that allow for tagging and even scraping metadata into ComicInfo. This standard is respected across the main software in the scene.

**Comment by majora2007** [comment]
You can fill out the `Number` field in the ComicInfo to force it not to recognize the group. For this, I'd use Issue 0 Volume 1 in the ComicInfo, this will make Kavita treat it as just a Volume. 

Sometimes comicinfo is incomplete, so falling back to filename makes sense. I can understand the frustration with C90 looking like a chapter, but unfortunately v02 c30 is a very common naming pattern found in practice, so removing it would have more negative effects.

**Comment by rosystain** [comment]
> You can fill out the `Number` field in the ComicInfo to force it not to recognize the group. For this, I'd use Issue 0 Volume 1 in the ComicInfo, this will make Kavita treat it as just a Volume.
> 
> Sometimes comicinfo is incomplete, so falling back to filename makes sense. I can understand the frustration with C90 looking like a chapter, but unfortunately v02 c30 is a very common naming pattern found in practice, so removing it would have more negative effects.

Oh I didn't realize the missing `Number`.
A complete comicinfo can solve it. Thank you for your help!

**Comment by majora2007** [comment]
No problem. I'll close this issue out. Reach out if you need any other help. Don't forget our feature request site to add your ideas in.
