### ISSUE TITLE
.jxl or .avif images do not show up in the library

### ISSUE THREAD

**Issue by tipozodis** [Kareadita/Kavita#1744]
**Describe the bug**
.jxl or .avif images do not show up in the library, get cannot read error.

**To Reproduce**
Add a .jxl or .avif file to library.

**Expected behavior**
.jxl or .avif images to show up in the library

**Screenshots**
![Screenshot from 2023-01-12 22-59-03](https://user-images.githubusercontent.com/102413831/212180263-ffb44f22-0af4-4e47-98a5-793ce70e6d7c.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox 108.0.1
 - Version: 0.6.1.0

**Additional context**
I found a workaround, changing the .jxl or .avif extension to .jpg makes the files show up and they display property, so that means there is something that checks for file extensions and does not let some through.

**Comment by majora2007** [comment]
That is because we don't support them. Please add a feature request on feats.kavitareader.com with your case to get them considered.
