### ISSUE TITLE
no e-books after scan 

### ISSUE THREAD

**Issue by Ganzhans** [Kareadita/Kavita#1747]
container is up and running , web site ok !
create first user ok  !
log on with the user ok !
adding library ok !
scanning library ok ! but no book found

lats part of the log : 

[Kavita] [2023-01-13 13:53:43.324 +00:00  37] [Information] API.Services.Tasks.CleanupService Cache and temp directory purged
[Kavita] [2023-01-13 13:53:43.343 +00:00  71] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on E-books
[Kavita] [2023-01-13 13:53:43.358 +00:00  71] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished file scan in 5 milliseconds. Updating database
[Kavita] [2023-01-13 13:53:43.998 +00:00  71] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished library scan of 0 series in 669 milliseconds for E-books. There were no changes
[Kavita] [2023-01-13 13:53:43.999 +00:00  71] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan
[Kavita] [2023-01-13 13:53:44.001 +00:00  71] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 0 series that needs to be removed: []
[Kavita] [2023-01-13 13:53:44.002 +00:00  71] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan - complete

docker-compose.yml 

version: '3'
services:
    kavita:
        image: kizaing/kavita:latest
        container_name: kavita
        volumes:
            - ./manga:/manga
            - ./config:/kavita/config
        ports:
            - "5000:5000"

I put some files on the folder  manga, scan  and scan but no books to show

Raspberry PI 3b 1 GB
64 bit os  Debian latest 

what next ?

**Comment by majora2007** [comment]
You need to read the wiki which tells you that files at the root of the library will not show up and must be within a nested folder. 

https://wiki.kavitareader.com/en/guides/managing-your-files/scanner#file-layout

**Comment by Ganzhans** [comment]
thnx ! it works
