### ISSUE TITLE
BUG: Series with edited metadata disappears when adding another series

### ISSUE THREAD

**Issue by jj-hk** [Kareadita/Kavita#1750]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
If a comic series has changed metadata (name, sort name, and localized name), then although it displays correctly after editing, subsequently adding another, unrelated comic series to the library seems to make the comic series with changed metadata disappear from the UI.

**To Reproduce**
1. Add comic series to library (I am not sure if there needs to be more than 1, I reproduced this with 10-20 series in a library)
2. Edit metadata of a series (name, sort name, and localized name)
3. Confirm series has updated correctly
4. Copy additional unrelated series to library folder, and initiate library scan from menu
5. Observe new series appears in UI, but series with previously edited metadata has disappeared

**Expected behavior**
Series with edited metadata should remain visible in library even if other series are added

**Screenshots**
So... I start with a few series for testing. Note there are 18 series here, including one called "thrawn trilogy"
![image](https://user-images.githubusercontent.com/69840762/213150869-c6ca2ec6-e007-4af6-810d-adfaf5f6a9cc.png)
I decide to rename this to "Star Wars - Thrawn Trilogy" to be consistent with the others
![image](https://user-images.githubusercontent.com/69840762/213150974-d9b8d87f-9087-447f-9fc1-59c6439e40ca.png)
That works, note the position has changed, still 18 series
![image](https://user-images.githubusercontent.com/69840762/213151027-95a71c75-97d3-4cb8-a16f-29c9e15154b6.png)
Now I add a totally different series (but still Star Wars). I copy the files to the library folder:
![image](https://user-images.githubusercontent.com/69840762/213151071-7074f596-269f-4526-a58a-5d5c3b16328f.png)
go to scan the library, note 18 series before scan
![image](https://user-images.githubusercontent.com/69840762/213151117-84670ef3-f84a-4864-b864-4de4400dbde0.png)
after the scan the new series (Knights of the Old Republic ) appears, and "Star Wars - Thrawn Trilogy" has disappeared. Note here still only 18 series:
![image](https://user-images.githubusercontent.com/69840762/213151173-c33aa322-bd5b-4f6f-aa0b-0afe33345a7b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox  Version 108.0.2 (64-bit)
 - Kavita version: 0.6.1.0

**Additional context**

Reproduced reliably using CBR and CBZ files, every time I edit metadata and add a series, the previously edited series consistently disappears
Rescanning library does not cause series to re-appear
Removing library and re-adding does cause series to re-appear, without metadata changes

**Comment by majora2007** [comment]
I haven't gone through this, but I do believe there is some issue with deletions in v0.6.1.0. This works fine in nightly and the next release is pretty close. I'll re-validate this exact flow and update/close the issue based on the results of that.

**Comment by majora2007** [comment]
Hi, just here to see if this is still an issue for you in the v0.7.1+ releases?

**Comment by jj-hk** [comment]
so..... yes, the issue as reported is resolved, if i edit metadata, the series remains in place when the library is scanned and a new series added - great, thanks!

However, in testing this, I've discovered that I can no longer add series to a sub-folder and scan them.

If I have a folder structure 

root
- sub folder
- - series A1
- - series A2
- series B

on initial scan it works fine, 3 series appear. 

If I add a series 

root
- sub folder
- - series A1
- - series A2
- - series A3
- series B

... then Series A3 is not detected on scan.

Shall I log a separate bug for this, or do you think it's related?

**Comment by majora2007** [comment]
Sorry for late reply, please create a separate issue for your scanner issue. 

For the issue related here, I believe this is now fixed in the latest nightly branch. There were some regressions around how localized name was handled.
