### ISSUE TITLE
Save the general settings (like Font Size, Line Spacing, etc..)

### ISSUE THREAD

**Issue by fymbbc** [Kareadita/Kavita#1752]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
I'm not sure if this is a bug or a new feature request, as I've been using Kavita for a week as a reader application. And I need to change the font size, line spacing and margins every time I go into the same book.

**To Reproduce**
1. Click to read a book
2. Click the Book Settings 
3. Change the Font Size / Line Spacing / Margin (for example, change the Line Spacing from 100% to 200%.)
4. Refresh the browser or quit the book.
5. click the same book.
6. All the settings will be set to default.

**Expected behavior**
Every time I enter to the same book, the last setting should be used.
I think it should have a save button or cookie cached function that to save the settings for each book / user profile.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome & Firefox
 - Version [e.g. 22] (can be found on Server Settings -> System tab): 0.6.1.0

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: 14.4
 - Browser: Safari / Chrome / Firefox
 - Version [e.g. 22] (can be found on Server Settings -> System tab): 0.6.1.0

**Comment by scare376** [comment]
You can set reader preferences in the user settings page.

https://user-images.githubusercontent.com/2068470/213629130-c9acab63-5962-43a0-943e-ed212a768795.mp4

**Comment by fymbbc** [comment]
@scare376 Thanks! it helps a lot. 
Then, change this to a new feature request, it will be great that has a button in the setting page or to be able to create multiple font profiles for different books for a better experience.

**Comment by scare376** [comment]
Feature requests go on feats.kavitareader.com. Check to make sure there isn't a similar request already before you create a new one.
