### ISSUE TITLE
Problems running under basic authentication

### ISSUE THREAD

**Issue by oprietop** [Kareadita/Kavita#1755]
I'm running kavita under a traefik setup and want to use http basic authentication because i don't want to expose the service directly.

Kavita seems to be stripping the "Authorization: basic foo" header and using his bearer token instead making everything unable to pass basic authentication.

Maybe kavita should use another header for the bearer like "Authentication-kavita: bearer bar" or keep the basic auth header alongside the bearer using "Authorization: Basic foo, Bearer bar"

**Comment by majora2007** [comment]
The Authentication header is how Kavita operates and is how it should operate. Kavita has no plans to change the authentication header.
