### ISSUE TITLE
Deleted Files are not Detected as a Filesystem Change by Kavita

### ISSUE THREAD

**Issue by loocool2** [Kareadita/Kavita#1760]
**Describe the bug**
Deleted files don't disappear off the library after being deleted because Kavita thinks the filesystem wasn't changed

**To Reproduce**
1. Have a bunch of folders with pdf files in them
2. Recursively delete them using find . -name "*.pdf" -type f -delete
3. Trigger a manual scan from the dashboard
4. Logs say filesystem changes were not detected

**Expected behavior**
The deleted files would disappear from Kavita after being detected that the filesystem had changed due to the date modified date changing. 

**Desktop:**
 - OS: Windows 10 Enterprise 20H2
 - Browser Vivaldi 5.7.2914.3 (Official Build) (64-bit) 
 - Version 6.1.0

**Additional context**
File watchers are off
Files were recursively deleted using the command `find . -name "*.pdf" -type f -delete` on the main Proxmox hypervisor that Kavita is hosted on.
Kavita is hosted in a Proxmox Alpine-based LXC
Disks are passed through passthrough from the host
The date modified date was edited for folders that had pdf files deleted

**Comment by majora2007** [comment]
This is a bug on v0.6.1 and has been validated to be fixed in upcoming v0.7.
