### ISSUE TITLE
grid-breakpoints customization

### ISSUE THREAD

**Issue by cb70-2023** [Kareadita/Kavita#1761]
Attempted a custom theme in order to update grid-breakpoints-lg. Reason is that metadata columns overlap if media width between 992px and 1200 px (columns class as col-lg-1).

However, variables from _variables.scss ($grid-breakpoints-lg: 992px;) override the custom values.

**Comment by majora2007** [comment]
Okay I did look into this, it wont be possible to change the breakpoints as bootstrap doesn't provide a css variable. 

Instead, you can put custom css in your theme and it will apply it to the page, so you can target classes to fix whatever issue you need.

**Comment by cb70-2023** [comment]
First of all, thanks! I would have attempted to update css definitions through selectors and classes without asking if the wiki did not leave the impression modifications were restricted to the listed variables.
