### ISSUE TITLE
Jpeg Gets added as book

### ISSUE THREAD

**Issue by Deekerman** [Kareadita/Kavita#1767]
So, i dont know if im doing something wrong or not but how i have my file structure is 
>Author
  > Book
      > sometitle.epub
      > sometitle.jpeg
      > sometitle.obf
![image](https://user-images.githubusercontent.com/33733383/215607942-f3cc5aca-19d8-4244-bd36-65a800532485.png)

*this is how LazyLibrarian is setting it up.*

For some reason Kavita is showing the .jpeg as a book instead of an image for said book. 

Is there a naming scheme or something im missing?

Thanks,

**Comment by majora2007** [comment]
Use a .kavitaignore at root level to ignore the images. 

https://wiki.kavitareader.com/en/guides/misc/ignoring-files-and-folders
