### ISSUE TITLE
Difficulty in turning pages, mostly back

### ISSUE THREAD

**Issue by cityeyes** [Kareadita/Kavita#1770]
**Describe the bug**
Sometimes unable to turn page backwards in a CBZ without closing out of the book and reopening it or using the page slider.

**To Reproduce**
1. Open any CBZ file
2. Flip forward a few pages quickly (and sometimes slowly, but quick seems to get it to trigger every time)
3. Try to flip page back, but it won't work - this is true to touch as well as arrow keys on a PC.

**Expected behavior**
Page should flip backwards when you hit an arrow key or tap on screen.

**Screenshots**
No screenshots, but [here](https://youtu.be/8gZ9htZBaTQ) is a video of the issue in action.

**Desktop (please complete the following information):**
 - OS: Windows 11 standalone
 - Browser Chrome, Chromium Edge, Firefox (Pretty much any browser I've tried)
 - Version 0.6.1.0

**Additional context**
The issue seems to persist between browsers, and be indiscriminate of any CBZ in particular.

**Comment by majora2007** [comment]
This looks like an issue that was plaguing an older version of Kavita. Can you please include your Kavita install version from system tab?

**Comment by cityeyes** [comment]
Yep, sure can. I'm a pretty obsessive updater - although I'm not running a docker so I'm not doing nightly, but I've pretty much always got the newest version available on Github.

<img width="481" alt="image" src="https://user-images.githubusercontent.com/8008991/216800362-0f41854a-fa6f-4772-b8da-9921ae6fa37e.png">

**Comment by cityeyes** [comment]
Good (and expected) news - looks like the newest version, 0.7.0.0, fixed this issue like you assumed it would. I haven't done any extensive testing, but it's certainly not happening in the same way it did in the past. I tried on a number of cbz books and wasn't able to replicate, so I'll close it. Thanks for all the hard work!
