### ISSUE TITLE
API send-to responded error 400

### ISSUE THREAD

**Issue by Shadow229** [Kareadita/Kavita#1777]
I have a fresh install of Kavita and KavitaEmail (populated with smtp details from a new gmail account) and when I try to send to my kindle I get the following error:

![image](https://user-images.githubusercontent.com/55843220/217244135-e1a14989-9dd2-41fd-8062-fb84e4ec3d07.png)

If I download the log file it displays a single line that looks to represent this but no additional information:

`[Kavita] [2023-02-07 12:18:09.610 +00:00  49] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/device/send-to responded 400 in 486.9385 ms`

The tests on the email service URL return successful.

Attached is my latest log with testing and attempted sending being the last things I did.

[kavita20230207.log](https://github.com/Kareadita/Kavita/files/10675044/kavita20230207.log)

**Comment by majora2007** [comment]
You need to check the KavitaEmail service logs. The Test just means that KavitaEmail service can be communicated with. It does not mean your SMTP settings are correct or the Email service can talk to your SMTP server.

**Comment by Shadow229** [comment]
Thanks @majora2007 - you're right, was looking in the wrong log! 

For anyone else that has this issue - it was due to gmail no longer allowing connection to less secure apps. The solution was turning on 2FA and creating an app password, then updating my KavitaEmail log in details with this app password for the connection.
