### ISSUE TITLE
Cover Image Fails to Apply/Save

### ISSUE THREAD

**Issue by brettcol-mdj** [Kareadita/Kavita#1779]
**Describe the bug**

Attempting to change the cover on one of the volumes of a series causes "400 Error: Unable to save cover image to Chapter"

![image](https://user-images.githubusercontent.com/101075262/217421452-9bf66411-3550-4aa6-86df-bd9b7fb631e0.png)

The logs show:
```
[Kavita] [2023-02-07 19:21:03.995 -08:00  1068] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/image/chapter-cover responded 304 in 1.4061 ms
[Kavita] [2023-02-07 19:21:03.995 -08:00  1072] [Error] API.Services.ImageService Error creating thumbnail from url
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at API.Services.ImageService.CreateThumbnailFromBase64(String encodedImage, String fileName) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\ImageService.cs:line 145
```
**To Reproduce**

1. Go to /library/2/series/1237
2. Click on volume 1's context menu
3. Select "Details"
4. Select "Cover"
5. Attempt to change the cover to another image

**Expected behavior**
The image be selected and applied. In the below screenshots, the first image is shown as applied, but the second is what displays. Refreshing covers does not fix the issue.

![image](https://user-images.githubusercontent.com/101075262/217422374-d15eea4e-7456-4a08-bd9d-d7bb0cc72f8f.png)
![image](https://user-images.githubusercontent.com/101075262/217422399-d634f79b-4f5c-4cd4-8fb8-b80fa1355da2.png)

**Server**
- Google Cloud VM
  - Distributor ID: Debian
  - Description:  Debian GNU/Linux 11 (bullseye)
  - Release: 1
  - Codename: bullseye
- Kavita Version
  - 0.6.1.0
- Install ID
  - 648187a3

**Desktop (please complete the following information):**
 - OS: Windows 11 Version 22H2 (Build 22621.1105)
 - Chrome (109.0.5414.120 (Official Build) (64-bit) (cohort: Stable))

**Comment by majora2007** [comment]
Was this done via file upload or URL?

**Comment by brettcol-mdj** [comment]
I've tried both.

**Comment by majora2007** [comment]
Hmm, i tried this on my server which is running the nightly and had no issue. Are you running this flow behind a reverse proxy? It could be external interference or firewall that is causing some issue.

**Comment by majora2007** [comment]
Just following up if you were are able to provide more information? I will close the issue and you can reopen with the information later.
