### ISSUE TITLE
Library tab showing collections

### ISSUE THREAD

**Issue by Shadow229** [Kareadita/Kavita#1780]
**Describe the bug**
Clicking on the library button shows collections, instead of the full ungrouped library. This leads to a lot of confusion as to whether books are being imported as they don't show in the library, but inside the series. At present, 'Library' and 'All Series' tabs both display grouped in the same way meaning finding a book, or discovering a title is difficult when you don't necessarily know which series its in.
You can can't filter in Library by book title with all the other filters?

**Expected behavior**
All books to show in the library regardless of series. Series to group together in the series tab. 

**Desktop (please complete the following information):**
 - OS: Unraid
 - Browser Chrome
 - Version 0.6.1.0

**Comment by majora2007** [comment]
Github is only for bugs, not feature requests. Please use feats.kavitareader.com for that.
