### ISSUE TITLE
Unable to go from Chapter 0 to 1, but I can go to previous chapter from 1 to 0 .

### ISSUE THREAD

**Issue by Draknars** [Kareadita/Kavita#1782]
**Describe the bug**
Many Webtoon's use Chapter 0 as a preview for the series, and those are categorized correctly as "Special" in Kavita, However for I reason that I cannot understand, I cannot move to the next (or first) chapter after Chapter 0, I have to manually go back to the serie and select the chapter 1. And for some reasons I can go back from Chapter 1 to 0 …

**To Reproduce**
1. Open any series with a Special Chapter 0 in the series
2. You Cannot move to the next chapter
3. Go back to the homepage, select the series again, and select the Chapter 1, you can select previous and go back to chapter 0

**Expected behavior**
The expected behavior would that I can move from chapter 0 to chapter 1 seamlessly.

**Screenshots**
![23-02-10 -19 59 00](https://user-images.githubusercontent.com/40360399/218229007-1e47aae5-5f84-4ade-9bc5-2051c418a9dd.png)
![23-02-10 -19 59 12](https://user-images.githubusercontent.com/40360399/218229015-081ec2cd-196e-4129-855d-1a6c585335b8.png)

**Server / Host : ** 

 - OS: Linux debian-server with Kavita running in Docker
 - Version 0.6.1.0 / Install ID fcaa65f9
 - Docker Image : kizaing/kavita:latest

let me know if you need anything else!

**Comment by majora2007** [comment]
Specials are ordered last as usually you read the series then read extras aka specials. So while your use case is valid, it is not how Kavita functions and is a one-off edge case.
