### ISSUE TITLE
Metadata pdf

### ISSUE THREAD

**Issue by Zourlo** [Kareadita/Kavita#1783]
Hello,

I have just installed kavita. I would like to know if my pdf can get any metadata.

I cutted and scanned my books, they are saved in pdf format. I imported them into calibre and got some metadata. Converting to epub is not an option unfortunately, I must have a copy in pdf to be able to add annotations.

Kavita cannot read the opf file with the same name as the pdf file. Isn't? If there is a way to get the metadata from opf or another format, I would like to know.

Thank you

**Comment by majora2007** [comment]
Kavita does not support sidecar files. Please see our wiki for what is supported. For PDF, you must rely on filenames exclusively.

**Comment by Zourlo** [comment]
> Kavita does not support sidecar files. Please see our wiki for what is supported. For PDF, you must rely on filenames exclusively.

Thank you for your reply. On the wiki, I did not find how to tag the filename. name, author, year, publisher, etc...
I can only get Series Name / Book name for pdf? 

Thank you
