### ISSUE TITLE
Kavita doesn't respect belongs-to-collection on EPub 3

### ISSUE THREAD

**Issue by yamimizu832** [Kareadita/Kavita#1793]
Kavita seems to have an issue with following the series information of the metadata of a file if the file itself has a number within the title. I experienced this issue with a light novel that was named Kingdom Hearts II. The light novel's metadata stated that this comic should be the 5th in the series. However, since it had the number the 2 in the title of the file it was placed as the second entry in the series instead of the 5th.

**Comment by majora2007** [comment]
I have confirmed this is a bug where ComicInfo method is overriding the correct series from ParserInfo. I have a separate ticket with details to fix this.
