### ISSUE TITLE
Admin dashboard statistics misreports library size.

### ISSUE THREAD

**Issue by Irvanya** [Kareadita/Kavita#1818]
On the statistics panel in the admin dashboard the total size is reported in MB when it should be reported in GB.

**To Reproduce**
With a total library size >1GB 
1. Goto Admin Dashboard
2. Click on Statistics
3. Total size is reported as xxx MB.  (On my server reports as 367 MB, actual size on disk is ~320 GB)

**Expected behavior**

With libraries >1 GB total size should be reported in GB not MB

**Desktop (please complete the following information):**
Windows 11, Chrome 110

**Comment by majora2007** [comment]
This is how it works. Can you give exact size you have vs what is being shown? 

Like on mine:
![image](https://user-images.githubusercontent.com/735851/220127594-9c35ed9d-b67d-4054-a910-e0eb0cd6ac10.png)

**Comment by Irvanya** [comment]
As I noted in the bug report I have about 320GB on disk, but the statistics
panel shows 367MB approximately 1/1000th of the correct size. When I get
home after work I will check if any of the folders used for libraries is
only 367 MB.

I was thinking that it would be a 3 line fix to show the correct units.
However since it correctly shows GB for you, I will need to dig deeper for
a likely source of the problem.

**Comment by majora2007** [comment]
I think you're confusing how it works. It is taking the file size of the files. If you are updating from v0.6.1, then you need to do a force scan (in library settings) to allow Kavita to learn about the file size of each file (and extension).

**Comment by therobbiedavis** [comment]
Yeah, as @majora2007 said this is likely the fact that kavita hasn't yet scanned your whole library yet post-update to figure out the sizes.

**Comment by Irvanya** [comment]
After forcing scans on the libraries The statistics resolve to a much more
reasonable 308 GB.  Thanks for looking at the issue.
