### ISSUE TITLE
The image splitting leaves scrollbar on mobile

### ISSUE THREAD

**Issue by alei643** [Kareadita/Kavita#1820]
**Describe the bug**
When I reading double managa, I want to use the image splitting funtion, Whatever option I choose Right to left or Left to right, 
The split images are displayed in full size. This problem shows up on my phone and tablet, But my computer is normal. So I think it's a bug.

**Screenshots**
![蜂蜜浏览器_微信图片_20230221081833](https://user-images.githubusercontent.com/38073408/220216935-6499fb50-43b1-4e92-8698-1903ccb1ae02.png)

![蜂蜜浏览器_微信图片_20230221081837](https://user-images.githubusercontent.com/38073408/220216884-c8507bcb-b311-4df2-ab24-a2779a3aad7d.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome 110.0
 - Version: Kavita 0.7.1

**Smartphone (please complete the following information):**
 - Device: Mi 10x
 - OS: Android 12
 - Browser: Chrome 110.0
 - Version: Version: Kavita 0.7.1

**Additional context**

**Comment by majora2007** [comment]
So my understanding from your post is that on phone and tablet, the split image is displaying a scrollbar even though you have scaling set to width, correct? 

Your expectation is there to be no scrollbar on width and instead the split image is shown scaled down correct?

**Comment by majora2007** [comment]
I can't do that unfortunately. Image splitting is done by using a canvas, as you cannot just split images in half. The canvas is limited, so if we scale to fit to width, the image inside will be cut off, as there isn't enough space to render. I could apply another layer of scaling, but the end result will be bad and it would add needless complexity, imo not worth it.

**Comment by alei643** [comment]
But this feature was normal in previous versions.The problem only started when I upgraded to 0.70

**Comment by alei643** [comment]
please see the screenshot..the first one from kavita 0.7.1, the second one from kavita 0.6.1, This image can be split and displayed normally when I used the image splitting funtion in the kavita 0.6.1. but in kavita 0.7.1, this picture is full size
![2023-03-21_21-27](https://user-images.githubusercontent.com/38073408/226620457-787c2560-df8b-4f85-b8be-f8bba7b59a5c.png)
![2023-03-21_21-18](https://user-images.githubusercontent.com/38073408/226618899-697cbf74-fa6a-4463-8cf6-ba54c39315f1.png)
