### ISSUE TITLE
Kavita only scans root folder and shows nothing

### ISSUE THREAD

**Issue by fruizaviles** [Kareadita/Kavita#1827]
Kavita 0.7.1.2 does not show books, since only scans root folder but shows a blank library with 0 books/files. 

Running nightly Kavita 0.7.1.2, as docker container, on a Synology DS720+ running DSM 7.1.1-42962 Update 4, the latest from Synology. 

**Expected behavior**

Should read all folders, old and new ones, and added pdf when populating folders. 

**Screenshots**
![IMG_20230222_185835](https://user-images.githubusercontent.com/26512079/220719920-028c7d85-f595-470e-be23-849965f1bd2f.jpg)

**Smartphone (please complete the following information):**
 Despite it happens on any device and I think it is independent, Kindle Fire, Win10, Android tablet, iPad, etc, but here

- Device: POCO X3 Pro
 - OS: android 12
 - Browser Chrome
 - Version 110.0.5481.65

**Additional context**

I have been using Kavita with all the same structure since a year ago approximately, and has been working smooth almost always. But since a month ago more or less, stopped reading subfolders, only updated pdfs or epubs stored on root folder, not a subfolder deep ones (different unique subfolders inside root subfolder with 1 folder depth regarding file route).
Since DSM OS update 3 I think it was when it started having issues for reading libraries, and I decided to clean install Kavita. Now, only reads root folder and shows nothing. I also disabled folder watching, that was an issue for me in version 0.6.

**Comment by mastervol** [comment]
I have a similar behavior, since I believe the update of DSM to Update 7.xxx Update 4 with Kavita 0.7.1.2.
I saw a few errors in the Kavita log related to the GUI problem you are experiencing.

**Comment by fruizaviles** [comment]
Hi there. I can say that bug is solved in versión 0.7.1.4.
Will wait with expectation new versions.
Cheers

**Comment by fruizaviles** [comment]
Kavita works again even smoother. Love it
