### ISSUE TITLE
Some books have blank page as error for last page. Does not get marked as complete

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#1828]
**Describe the bug**
I have some books that after the last page of the book it will show another blank page with an error. When this happens the book does not automatically get marked as complete.

**To Reproduce**
1. Go to last page of a book.
2. Progress 1 page further.
3. Book may show a blank page with error. If next book appears then book is unaffected.
4. Progress 1 page further.
5. Next book in series should appear.
6. Exit book and completed book is not marked complete.

**Expected behavior**
All books end on the expected last page and are marked as complete.

**Screenshots**
![image](https://user-images.githubusercontent.com/2068470/220770781-b318cfd3-9712-44e6-ab34-c5c633cebc85.png)
![image](https://user-images.githubusercontent.com/2068470/220770730-ff14e4eb-778c-46da-893c-82ba8c31481d.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Opera GX, Chrome
 - Version: 0.7.1.2

**Additional context**
The series I noticed the issue on and am sending a few volumes of to Joe is _The Angel Next Door Spoils Me Rotten_

Also unknown if its related but I believe all the books are epub 3.2

**Comment by majora2007** [comment]
I took a look and a bit confused. I do see the TOC is listed twice in the manifest, but nothing inherently wrong. Kavita essentially counts all the html files and that is what makes up the pages. Other books are working fine and inspecting the epub, everything looks fine.

**Comment by majora2007** [comment]
Okay I found a way to fix this.
