### ISSUE TITLE
Comic issue #00 not showing up with other issues in a series, but they show up in search

### ISSUE THREAD

**Issue by doasfan** [Kareadita/Kavita#1829]
I see this behavior with several (all?) series with an issue #00, but demonstrating with The Immortal Hulk below.

Searching "The Immortal Hulk" shows the correct series, but only 50 issues (#1 thru #50). But there is an issue #0 that shows up as a file, but not an issue.

From the series page, under Issues, only 1-50 show up.

From the series page, click PENCIL>INFO> there are a few fields that look incorrect:
1. Max items shows 2018... but that's the Volume date from the comicinfo.xml
2. Total item count shows 0, but there should be 50
3. Size 0 B, seems to be showing 0 Bytes for everything across the entire library
4. But Issue #00 shows up here, as Chapter 0

From the Storyline or Volumes tabs, when clicking on the 3 dots>Details>Info, I can see #00 is listed, but as a "File" vs an "Issue". See screenshot.

![hulk 0 in search](https://user-images.githubusercontent.com/9890160/220780855-b0ac32c8-1a46-4ee7-835f-5fdb1b4ecce8.JPG)
![hulk 0 xml](https://user-images.githubusercontent.com/9890160/220780908-e647beab-ed3a-4c68-9e38-1a7b20b2ac91.JPG)
![hulk series display](https://user-images.githubusercontent.com/9890160/220780945-a2c6da32-ea95-48d8-a375-8226f4a42a19.JPG)
![hulk info](https://user-images.githubusercontent.com/9890160/220780965-68743542-97cd-4dbd-858b-c9c228812392.JPG)

Some other titles I've seen this occurs with:
Star Trek: The Mirror War
Voltron - Defender of the Universe
Batman - Legends of the Dark Knight
Flashpoint Beyond

Docker
Version  0.7.1.0

Chrome 109.0.5414.121 on Windows 10

**Comment by majora2007** [comment]
You can't use Volume 0 or Issue 0 in Kavita. They are reserved. You will have to use 0.1 unfortunately.

**Comment by majora2007** [comment]
Issue 0 will be treated as a special hence why you see it as a file in the series.
