### ISSUE TITLE
Comics scroll down to a black screen when set to single page (Chrome/Chromium)

### ISSUE THREAD

**Issue by ch13696** [Kareadita/Kavita#1830]
**Describe the bug**
Any comic that is opened will open with a scroll bar that scrolls down to a black screen. Like there's a blank second page. My settings for the comic are set to 
Image Splitting - Fit to Screen
Image Scaling - Width
Layout Mode - Single
Auto Close Menu - Enabled
Swipe Enabled - Enabled
Emulate Comic Book - Disabled

This is on both Chrome and Brave (Chromium) on Android 13. Kavita v0.7.1.0

**To Reproduce**
1. Open any comic or manga
2. Scroll bar will show on the side once the image loads
3. Scroll down and it will show a black page

**Screenshots**
https://ibb.co/LCwq3Z8
https://ibb.co/99VnLXb

**Desktop (please complete the following information):**
 - OS: Android 13
 - Browser Chrome and Brave (Chromium)
 - Version [e.g. 22] (can be found on Server Settings -> System tab)

**Smartphone (please complete the following information):**
 - Device: Galaxy Tab 7 FE
 - OS: Android 13
 - Browser Chrome and Brave (Chromium)
 - Version 0.7.1.0
![Screenshot_20230223_092303_Chrome](https://user-images.githubusercontent.com/5604614/220984230-ab19acdd-2b6e-4f19-bef4-78816924714f.jpg)
![Screenshot_20230223_092333_Chrome](https://user-images.githubusercontent.com/5604614/220984234-13cc2db1-3047-4373-8eb9-7856ff12e260.jpg)

**Comment by majora2007** [comment]
I need the reader options you have selected and steps to reproduce please

**Comment by ch13696** [comment]
> I need the reader options you have selected and steps to reproduce please

I edited the post. Added version number in description, the settings when reading the comic or manga, and added steps. Steps are pretty simple though. It's basically just opening the comic. I'm going to download an Android emulator and see if the same thing happens with that. If not then I would think it's my particular model tablet.
