### ISSUE TITLE
When I am loading a directory, I am unable to pick a mounted driver.

### ISSUE THREAD

**Issue by yoannfelix** [Kareadita/Kavita#1831]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
I installed kavita using docker compose. When I am loading a directory, I am unable to pick a mounted driver.

**To Reproduce**
1. Go to Admin Dashboard
2. Click on Add Library
3. Fill in name then click Next.
4. Click on Browse for Media Folders
5. Enter /mnt/f
6. See error

400 Error [1]
This is not a valid path.

**Expected behavior**
I should be able to add a mounted drive as a directory

**Screenshots**
![image](https://user-images.githubusercontent.com/67986128/221036392-1efd78d3-f734-48e1-9953-493cf89cf321.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Firefox and Chrome

Processor	Intel(R) Xeon(R) W-2104 CPU @ 3.20GHz   3.19 GHz
Installed RAM	32.0 GB (31.7 GB usable)
System type	64-bit operating system, x64-based processor
Docker Engine v20.10.22

Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

**Additional context**

**Comment by yoannfelix** [comment]
I installed it on the C drive from the Ubuntu WSL.

**Comment by therobbiedavis** [comment]
@yoannfelix We need to see the docker run or docker compose used, specifically the volume mount. Can you please provide that information?

**Comment by yoannfelix** [comment]
Hi,
I did not modify the docker-compose.yml when I copied the git repo.

![image](https://user-images.githubusercontent.com/67986128/221214870-5b7b6ca6-3c84-4500-bdec-190cba755f3f.png)

**Comment by Kizaing** [comment]
You need to mount your drive directory that contains your manga. 

Under volumes you'll need to put /mnt/c/<wherever your manga is>:/manga etc

Currently you don't have your folders mounted inside the container

**Comment by yoannfelix** [comment]
Thank you for your patience with me. That was it. Once I added it, I am able to pick the mounted drive from the UI.
