### ISSUE TITLE
will you add support for freebsd like ports or something

### ISSUE THREAD

**Issue by aohan237** [Kareadita/Kavita#1833]
there are many os or nas os support .
if there any will be nice

**Comment by majora2007** [comment]
Feature requests go on feats.kavitareader.com. FreeBSD is unlikely to come due to complexity in supporting.

**Comment by agrajag9** [comment]
I'm trying to grind the port to FreeBSD. It's definitely possible now that we have [lang/dotnet](https://www.freshports.org/lang/dotnet/).

I'm not done yet, but I'll share some tidbits of the journey so far.

1. `/bin/bash` does not exist on FreeBSD. The proper modern way to invoke is `#!/usr/bin/env bash`, this will make scripts portable.
2. I added a target for `freebsd-x64`. Once I get that building, I'll try to get through the other Tier 1 archs.
```
diff --git a/build.sh b/build.sh
index 673620e3..c39b29b9 100755
--- a/build.sh
+++ b/build.sh
@@ -1,4 +1,4 @@
-#! /bin/bash
+#!/usr/bin/env bash
 set -e
 
 outputFolder='_output'
@@ -135,6 +135,8 @@ then
     cd "$dir"
     Package "osx-arm64"
     cd "$dir"
+    Packaged "freebsd-x64"
+    cd "$dir"
 else
     Package "$RID"
     cd "$dir"
```
3. **This is where I'm stuck:** The output package is missing some so's. I am not a dotnet developer, so hints welcome.
```
$ diff <( tar -tf kavita-linux-x64.tar.gz | sort ) <( tar -tf kavita-freebsd-x64.tar.gz | sort )
12d11
< Kavita/createdump
71,72d69
< Kavita/libcoreclrtraceptprovider.so
< Kavita/libe_sqlite3.so
82,83d78
< Kavita/libvips.so.42
< Kavita/LICENSE
252d246
< Kavita/pdfium.so
```

**Comment by majora2007** [comment]
@agrajag9 What so's are missing? Compare it to a linux build to identify. The biggest concerns are around NetVips and Pdfium. For Pdfium we had to add our own support to pdfium for Arm64.

**Comment by socphoenix** [comment]
Not the desired implementation (I'd much rather have this in ports), but Kavita does run on a linux jail. Using bastille I was able to do it with the following:

> bastille bootstrap jammy

> bastille create -L kavita jammy 10.1.1.12

> bastille edit kavita

On this add "allow.mlock;" on a line under "allow.mount.devfs" making sure to match indent.

> bastille start kavita (use restart if needed)

> bastille console kavita

Navigate to your kavita folder/use curl/wget to get it and untar it. chmod/chown files as shown in the getting started, and the finally

> ./Kavita

as shown in the getting started.
