### ISSUE TITLE
"Cover Image" setting shows no covers for reading lists

### ISSUE THREAD

**Issue by DatuStram** [Kareadita/Kavita#1835]
**Describe the bug**
When trying to set a cover for a reading list, the "Cover Image" tab stays empty and doesn't show covers from any of the books making up the reading list.
The same tab works just fine for collections.

**To Reproduce**
1. Go to 'Reading Lists'
2. Click on the three dots of any reading list, then 'Edit'.
3. Go to the 'Cover Image' tab.
4. See error: no covers showing up.

**Expected behavior**
The "Cover Image" tab should display a list of all the covers from the books making up the reading list.

**Screenshots**
![Collection](https://user-images.githubusercontent.com/24694690/221223615-de9cdc9f-d97e-455f-a9d4-637e4c9b0e7b.png)
![Reading_list](https://user-images.githubusercontent.com/24694690/221223623-00d6340e-5cea-4c9b-a6b2-733224722b73.png)

**Desktop**
 - OS: Docker
 - Browser: Brave Browser Version 1.48.167 Chromium: 110.0.5481.104
 - Version: 0.7.1.0

**Smartphone**
 - Device: OnePlus 8 Pro
 - OS: Android 13
 - Browser: CDisplayEx
 - Version: 1.3.54

**Comment by majora2007** [comment]
Sorry, forgot to tag this. This was fixed in #1862. In case you're unaware, it will go out with the next stable release.
