### ISSUE TITLE
When updating LocalizedSeries from Comicinfo, Kavita creates a new series

### ISSUE THREAD

**Issue by Roshri** [Kareadita/Kavita#1837]
Updating series to have a LocalizedSeries title in the comicinfo (using komf in this case), causes the series to be deleted and created again with a new series ID.

For example this was ID 7049
![image](https://user-images.githubusercontent.com/29184137/221247155-e4212af1-ec2a-4269-ac0e-1f72bf2768c8.png)

After adding a LocalizedSeries it became ID 7061
![image](https://user-images.githubusercontent.com/29184137/221247253-6551bcdb-a09d-4f7d-9958-dd943a525d49.png)

The expeced behavior would be to have the newer data appended to the existing series, since its not the main title what is being changed

EDIT seem to only occur when series didn't have any localizedSeries tag and it was added or when all books changed the tag from old one

**Comment by majora2007** [comment]
I have validated this occurs when adding LocaliedSeries in comicinfo and then scanning.
