### ISSUE TITLE
Occasional "Black Screen" when loading to the next chapter (Webtoon reader)

### ISSUE THREAD

**Issue by Draknars** [Kareadita/Kavita#1838]
**Describe the bug**
Sometime when proceeding to the next chapter of a webtoon, The only thing I get is a black screen, I can still technically Scroll and interact with the interface, but no images are loaded. No error shows up either. As a workaround, I have discovered that I can “fix it” by manually clicking in the progress bar to make the images appear. 

**To Reproduce**
_Note_ : This issue has been inconsistent for me, I can read multiple chapters in a row without issues, but sometimes it happen every other chapters. What I can say is that I have been experiencing this since using Kavita, many versions ago, across many Webtoons. However, I currently can't recall it happening to Text format like light novels.
.
1. Read any webtoon, scroll to the bottom
2. Click Next Chapter or Scroll to next chapter
3. The next Chapter Load, however it is all black. Click on the chapter progress bar and the images will show up.

**Expected behavior**
Would expect the page to load properly 

**Screenshots**

After the page turn black, you can see me scrolling (see the scroll bar moving) but nothing load or change

https://user-images.githubusercontent.com/40360399/221280818-d6fb9b9d-65a4-48a9-9920-ebd427a590bc.mp4

Happening again, about 15minutes later

https://user-images.githubusercontent.com/40360399/221280697-77a9f773-acd7-4339-a11c-080fc1f04a57.mp4

**Server (please complete the following information):**
 - OS: Linux debian-server with Kavita running in Docker
 - Version 0.7.1.4 / Install ID fcaa65f9
 - Docker Image : kizaing/kavita:latest

**Device (please complete the following information):**
 - Device: iPad Pro 3rd Gen
 - OS: iPadOS 16.2

**Additional context**
Let me know if I can provide anything that can help

**Comment by majora2007** [comment]
I have seen this rarely as well in my dev machine, I'll take a look.

**Comment by Draknars** [comment]
Thanks, much appreciated, let me know if I can help !

**Comment by majora2007** [comment]
I was able to reproduce by bringing my network profile at Offnetwork speed. Seems to be a timing issue.

**Comment by majora2007** [comment]
Okay it was a fluke, I can't seem to reproduce it again.

**Comment by majora2007** [comment]
There is another thread here with more information.
https://github.com/Kareadita/Kavita/issues/1848
