### ISSUE TITLE
Covers and Manga Crashing Docker Image on Older AMD CPUs Unless Work Around is Applied

### ISSUE THREAD

**Issue by prosthetichead** [Kareadita/Kavita#1839]
**Describe the bug**
Crashes on old cpus unless work around is applied. Was ment to be fixed by pull request https://github.com/Kareadita/Kavita/pull/1479/files

**To Reproduce**
1. have an older CPU.
2. pull the stable or nightly docker image
3. Generate Covers or open a image based comic (Not PDF)

Work around
4. Apply the work around found in this comment https://github.com/Kareadita/Kavita/issues/1423#issuecomment-1213207354
5. Opening image based comics and generating covers now works

**Expected behavior**
The work around does not need to be applied and image processing does not crash the docker image on older cpus

**Screenshots**
https://discord.com/channels/821879810934439936/840693141082341406/1077932807957000234
https://discord.com/channels/821879810934439936/840693141082341406/1077932209845051422
https://discord.com/channels/821879810934439936/840693141082341406/1077931825315459172
https://discord.com/channels/821879810934439936/840693141082341406/1077928491330314290 (pdf working)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Edge and Firefox used to test
 - version 0.7.1.4

**Additional context**
Discussed on discord  02/22/2023 with prostheticHead and majora2007 (Joe)
First message can be found here https://discord.com/channels/821879810934439936/840693141082341406/1077907516219985931

**Comment by majora2007** [comment]
I think perhaps you misunderstood me in discord. This is not something I can fix automatically. The workaround needs to be applied each update.

I've already looked at removing this requirement but the other libraries are slower or eat more memory, so I can't make that move.

**Comment by scare376** [comment]
Would it be possible to add a bash script to the docker image that will do this and only run it when a docker variable is passed? I've not messed with creating docker images enough to know if this is possible.

**Comment by majora2007** [comment]
@Kizaing could you comment on the feasibility or do some basic testing?

I'm not sure honestly, but we don't have any way to reproduce and test said changes.

**Comment by majora2007** [comment]
Closing this issue. We have the workaround available. I'm not going to be working on making it applied automatically. If there is a way to support more platforms in the future, I will investigate.
