### ISSUE TITLE
Epub metadata not being respected

### ISSUE THREAD

**Issue by therobbiedavis** [Kareadita/Kavita#1841]
**Describe the bug**
While running 0.7.1.4 (stable) it seems some epubs with `vol.` in the get grouped into a single volume despite having proper metadata.

On Develop branch this works fine.

**To Reproduce**
1. Download the following:
https://mega.nz/file/ttRjSZ4A#_M9KSjFPL8FwY9QWBmoySsOqAhE1t27T6c68ySc_7eA
https://mega.nz/file/QhpHFTwS#TBJAMOUtV3sUUUqRxp0rhPt41DVW3kgZmz8E76ueQ28
2. Import them into a books type library on stable 0.7.1.4
3. See that they are group into one volume.

**Expected behavior**
OPF metadata is respected over filename and the files are not group but rather separated and given their appropriate series index.

**Screenshots**
Running on Main 0.7.1.4:
![image](https://user-images.githubusercontent.com/7907265/221431565-68719426-6423-4a86-ac46-e29886b635b5.png)

Running on Develop 0.7.1.4:
![image](https://user-images.githubusercontent.com/7907265/221431682-d6b91ac1-e2a3-4932-afe5-7f9cb028d643.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 0.7.1.4

**Comment by majora2007** [comment]
Validated this works on nightly. This was a bug where belongs-to-collection was getting overridden in the Scanner loop.
