### ISSUE TITLE
BUG: Unused metadata suggestions not being removed from db

### ISSUE THREAD

**Issue by KingIzzymon** [Kareadita/Kavita#1844]
# BUG: Unused metadata suggestions not being removed from db
I added the tag "Sample" to one book, verified it showed up as a suggestion in another book, then returned to the first book to remove it. After removing the "Sample" tag from the only book in my library, it is still being suggested as an existing tag.

This is an issue since, if someone keyboard mashes "hbfunerida" and saves the metadata entry, then that tag will be stuck in the db and be suggested for future entries starting with "h" in this example.

## **To Reproduce**
Follow the above description

## **Expected behavior**
Unused tags to be cleared from the db and no longer be suggested.

## **Screenshots**
![image](https://user-images.githubusercontent.com/94716517/222265466-17ed9ae4-f925-4061-8ac9-9174de060bbc.png)

## **Server**
 - OS: Ubuntu 20.04.5 LTS - Docker 23.0.0
 - Browser: Chrome 110.0.5481.178
 - Kavita Version: 0.7.1.4

**Comment by majora2007** [comment]
This is actually per-design. The tag gets cleaned up at night usually, but I do think it raises a concern for the average user, so I took care of this.
