### ISSUE TITLE
Book ingestion performances decreases with library size

### ISSUE THREAD

**Issue by matt-innes-inss** [Kareadita/Kavita#1845]
I have a large library of EPUBs (approx 45,000).   I started ingesting them into a Kavita instance a couple of days ago.   I have observed the following performance 

| Book # | Time to process |
| 1 | 0.2s |
| 20000 | 6s |
| 34000 | 12s | 

This performance is consistent (i.e right now every book is taking ~12s).  Looks like book ingestion performance drops off ~linearly with library size.  It's not clear where the bottleneck is. Docker stats below. The SQLite database is ~60Mb so it shouldn't be that. Something to do with the word count or cover refresh mayb?  I will see how long it takes to complete and update.

Additionally, I have seen EPUBs not processed on account of the EPUB XML using v1.1 (the error in the logs indicates .Net cannot process v1.1 XML files). Can't find the details right now. I'll raise another issue  if it proves insurmountable

System:
kizaing/kavita docker image
Ubuntu 22.04.2
32Gb RAM
AMD Ryzen 5 5600G

* Docker stats

I restarted the process in the last hour to see it would speed things up. It didn't, but it has reduced CPU usage (it was around ~300% before I killed it)

`CONTAINER ID   NAME             CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
2042f44a4f69   kavita           103.36%     570MiB / 30.71GiB     1.81%     4.52MB / 38.3MB   220MB / 917MB     75`

**Comment by majora2007** [comment]
This is likely just the cost of memory to maintain all the people, genres, tags, etc. This should only be problematic on first scan, which is always heavy and slow. Subsequent scans skip much of the work the first scan has to do. I'm not sure there is much I can do here.
