### ISSUE TITLE
"Convert Covers to WebP" is broken in 0.7.1.4

### ISSUE THREAD

**Issue by Draknars** [Kareadita/Kavita#1860]
**Describe the bug**
Decided to give a try to the new feature and enabled Save Covers to WebP, I then ran the Convert Covers to WebP and after processing I no longer have any Cover images.

**To Reproduce**
1. Go to Server settings -> Media 
2. Enable "Save Covers as WebP?"
3. Go to Tasks and start Job "Convert Covers to WebP"
4. Once done, Cover images fail to show up

**Expected behavior**
Would expect to have the covers working

**Screenshots**
The path it trying to reach is formatted like : http://10.0.4.10:5000/api/image/series-cover?seriesId=2799
![image](https://user-images.githubusercontent.com/40360399/223495170-2bd144fb-cb43-4498-868e-80f680ce7957.png)

**Server (please complete the following information):**
 - OS: Linux debian-server with Kavita running in Docker
 - Version 0.7.1.4 / Install ID fcaa65f9
 - Docker Image : kizaing/kavita:latest

**Device (please complete the following information):**
 - Device: iPad Pro 3rd Gen
 - OS: iPadOS 16.3

**Comment by majora2007** [comment]
Yes, in the stable this is still an issue. It should be fixed now in the latest nightly. I'll pin this since it's a large issue for the stable.

**Comment by Draknars** [comment]
Sorry I must have missed that it was only fixed in Nightly for now, thanks for answer!
