### ISSUE TITLE
"Incorrect Credentials" When Autofilling with Bitwarden on Mobile

### ISSUE THREAD

**Issue by brwarner** [Kareadita/Kavita#1861]
Kavita Version: 0.7.1.4 (though also happened on 0.6)
Device: iPhone
Browser: Firefox Mobile or Safari

When using BitWarden, a password managment app, to auto-fill passwords on the mobile login screen in Kavita, I'm given an "Incorrect Credentials" error however typing the correct password manually works. Auto-filling works fine on both my desktop (Windows, Firefox) and Tablet (Surface, Firefox). The issue seems to only appear on mobile regardless of the browser (I tried two).

Using the "Request Desktop Site" in either mobile browser didn't seem to do anything.

EDIT: Originally believed this was an issue with logging in generally, but it's now clear to me manually typing in the password worked. Details and Title have been updated appropriately.

**Comment by majora2007** [comment]
Are you sure you're typing in the correct credentials into your instance? You could also change your password to something simple and then validate you can log in from your mobile. 

I use Firefox and just now was able to login to my instance (my password also has various symbols). 

iOS could be causing an issue, however I think unlikely. @therobbiedavis  can you check on your  IPhone?

**Comment by therobbiedavis** [comment]
I can confirm that when autofilling with Bitwarden on iOS it errors and says the credentials are incorrect. If you manually copy and paste the same password from Bitwarden into Kavita's password field it works. The autofill works properly with Bitwarden on desktop.

I need to dive deeper into this.

**Comment by brwarner** [comment]
Maybe I made a mistake when I manually typed in the password. I’ll try again later today.

**Comment by brwarner** [comment]
Okay so manual password entry does work--I must have just made a typo. However BitWarden autofilling the same password on mobile does _not_. Autofill is working on tablet and desktop though. I'll update the bug description.

**Comment by majora2007** [comment]
I think this might be more of a defect on your autofiller. I use Firefox auto filling just fine. I don't think there is much for me to do from Kavita's side. I use type=password.

**Comment by MrAlucardDante** [comment]
I can confirm that the same thing happened to me today after installing for the first time 0.8.4

I created my admin account by pasting the generated password from bitwarden, then when I tried to log in I got the error
I then copied and pasted manually the password from bitwarden, and it worked

**Comment by therobbiedavis** [comment]
> I can confirm that the same thing happened to me today after installing for the first time 0.8.4
> 
> I created my admin account by pasting the generated password from bitwarden, then when I tried to log in I got the error
> I then copied and pasted manually the password from bitwarden, and it worked

Can you share how many characters your password is?

**Comment by MrAlucardDante** [comment]
> > I can confirm that the same thing happened to me today after installing for the first time 0.8.4
> > I created my admin account by pasting the generated password from bitwarden, then when I tried to log in I got the error
> > I then copied and pasted manually the password from bitwarden, and it worked
> 
> Can you share how many characters your password is?

Sure, it is 21 characters long
