### ISSUE TITLE
Korean Font Issue

### ISSUE THREAD

**Issue by Sarangnamu** [Kareadita/Kavita#1863]
Although this is not a bug report, I would like to request support for KOREAN fonts. Currently, the default font, Nanum Gothic, is already included, but even if it's not installed, it still appears. I would be grateful if you could add the Nanum Myeongjo font. Alternatively, if it is possible to add fonts, that would be greatly appreciated as well.

**Comment by TheIceCreamTroll** [comment]
Feature requests should be posted on https://feats.kavitareader.com/
