### ISSUE TITLE
User invite landing page has confusing guidence

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#1867]
**Describe the bug**
When creating a new user and getting to this screen:

![image](https://user-images.githubusercontent.com/30128380/223870399-9155324e-0181-4cc6-9f36-6f674b37f59c.png)

There is the "Invite" button that can't be clicked on. If there is a certain circumstance that is used in then it should be hidden unless true. The wording of the whole page feels off here based on the info displayed. It's saying "Enter their email in and we will send them an email to create an account." but that was done on the screen before it. That part could just be shown on the first page and not after the account has been made. When you follow the "Setup user's account" link it takes you to the register page here: 

![image](https://user-images.githubusercontent.com/30128380/223875138-acef0021-489e-4493-a87a-0f49c09d5306.png)

Once you fill out this page is where it gets confusing. It doesn't tell you any status of making the account, it just dumps you back into your own home page logged in as your existing user. I think either moving this part to the first page (see 1st screenshot) or having it hit a landing page saying "User created" would be better flow. Something other than clicking register and having it dump you into your own account. 

**Expected behavior**
A clear and concise description what you just did that goes with the workflow. 

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Version: 0.7.1.14

**Comment by majora2007** [comment]
The code will pop a toaster saying "Account registration complete" after hitting register.
