### ISSUE TITLE
Book Fold Emulation Not Full Height

### ISSUE THREAD

**Issue by bradymenegay** [Kareadita/Kavita#1868]
When you enable the center fold shadow, the seam doesn't reach the bottom of the page. This is due to the `.image-container .full-height` class being offset by 34px for the scrollbar and the shadow being set to 100% of its parent. This causes it to render 34px short.

If you remove the offset, disable the brightness filter, or set the `::before` height to 100vh, the shadow reaches the bottom of the page as expected.

## Shadow Parent Height
https://github.com/Kareadita/Kavita/blob/d88a4d5d0ce0051cc5f61539ef415cb6115b11ff/UI/Web/src/_manga-reader-common.scss#L15

## Shadow Element Height
https://github.com/Kareadita/Kavita/blob/d88a4d5d0ce0051cc5f61539ef415cb6115b11ff/UI/Web/src/_manga-reader-common.scss#L76

## Current Behavior
![image](https://user-images.githubusercontent.com/7523158/224058169-3106a8e0-9b84-4f9e-9f99-7da183be5103.png)

## Height 100vh Fix
![image](https://user-images.githubusercontent.com/7523158/224064298-ffcc5724-ad7c-4c72-bb5b-9a5c51c77209.png)

 - Server: Docker
 - Client: Windows
 - Browser: Firefox
 - Version: 110.0.1 (64-bit)

**Comment by majora2007** [comment]
That -34px is actually needed to handle this case right here.
![image](https://user-images.githubusercontent.com/735851/225726805-08448219-5c45-4f38-9d50-1f2390177ff5.png)

However, this is definitely a bug that slipped through testing, so I'll look into a solution to fix it.
