### ISSUE TITLE
PDF Support

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#187]
To support PDFs, we need to figure out how to propery send the data to the client. 

It looks like we can generate images from each of the pdf pages and utilize the same functionality of the Manga reader.

**Comment by majora2007** [comment]
This library meets our needs:
[docnet](https://github.com/GowenGit/docnet)

**Comment by therobbiedavis** [comment]
After discussion and review, it looks like iTextSharp should meet our needs despite it be deprecated: https://github.com/itext/itextsharp

License is AGPL which should work for our needs.

**Comment by majora2007** [comment]
This feature has been moved to 0.4.3 due to a huge improvement in how mixed libraries can work. This will also rework the Raw Images support added in this release.
