### ISSUE TITLE
Kavita crashes when attempting to generate cover

### ISSUE THREAD

**Issue by Hunsu** [Kareadita/Kavita#1870]
**Describe the bug**
I added a new manga and when I scanned the library Kavita crashed and did restart when attempting to generate the covers. So I ended up with the new Manga being added, but without covers. I installed Kavita using docker, and it did crash each time it tries to generate covers. It didn't crash when I did it on last October (same files). 

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Version     0.7.1.14 (tested stable and nightly)

**Additional context**
```[Kavita] [2023-03-09 17:44:21.322 +00:00  33] [Debug] API.Services.Tasks.Scanner.ProcessSeries Updating XXX FolderPath to /media/Spanish/XXX
[Kavita] [2023-03-09 17:44:21.906 +00:00  33] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Finished series update on XXX in 1477 ms
[Kavita] [2023-03-09 17:44:21.931 +00:00  33] [Debug] API.Services.MetadataService [MetadataService] Processing cover image generation for series: XXX
[Kavita] [2023-03-09 17:44:21.934 +00:00  33] [Debug] API.Services.MetadataService [MetadataService] Generating cover image for /media/Spanish/XXX/XXX.cbr
[Kavita] [2023-03-09 17:44:21.944 +00:00  36] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library responded 200 in 2.5944 ms
/entrypoint.sh: line 29:     7 Illegal instruction     (core dumped) ./Kavita```

**Comment by majora2007** [comment]
You installed the wrong version of Kavita for your underlying OS or you're hitting a known issue:
https://wiki.kavitareader.com/en/faq#q-kavita-doesnt-seem-to-run-or-generate-covers-on-my-computer

**Comment by Hunsu** [comment]
I don't think so, I am aware of that issue, but my CPU does support SSE4.2 and as I said it did work on the version I installed in October. Also, normally Kavita does not crash when CPU does not support SSE4.2. It just that you don't get covers. Am I mistaken?

**Comment by majora2007** [comment]
That is correct, your logs look like it's the wrong architecture type. Illegal instruction implies you're running ARM and have x86 or vice versa. 

@therobbiedavis

**Comment by therobbiedavis** [comment]
@Hunsu Can you try with a known good archive that worked back when you first installed Kavita? My guess is either the filename or image format are causing exceptions.

**Comment by Hunsu** [comment]
Kavita (0.6.1.0) without docker also crashes when trying to generate covers. I am sure I downloaded the right architecture package. Though I don't see ` Illegal instruction`. I just see Kavita restarting.

**Comment by Hunsu** [comment]
OK I will try, but now I think I may restored my data from a backup so I am not sure if cover generation ever worked on that machine.
My CPU info:

```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         48 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  2
  On-line CPU(s) list:   0,1
Vendor ID:               AuthenticAMD
  Model name:            AMD Athlon(tm) II X2 220 Processor
    CPU family:          16
    Model:               6
    Thread(s) per core:  1
    Core(s) per socket:  2
    Socket(s):           1
    Stepping:            3
    CPU max MHz:         2800.0000
    CPU min MHz:         800.0000
    BogoMIPS:            5599.99
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl n
                         onstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nr
                         ip_save
Virtualization features: 
  Virtualization:        AMD-V
Caches (sum of all):     
  L1d:                   128 KiB (2 instances)
  L1i:                   128 KiB (2 instances)
  L2:                    1 MiB (2 instances)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0,1
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Not affected
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

**Comment by therobbiedavis** [comment]
@Hunsu After some research, your CPU supports SSE4a not SSE4.2. It's also missing AVX therefore you need the workaround. My guess as to why it's now crashing is our upgrade to .NET 7.
