### ISSUE TITLE
[Manga Reader] Up/Down Arrow not Scrolling without Highlighting the Page

### ISSUE THREAD

**Issue by xScarbo** [Kareadita/Kavita#1874]
I'm on my PC while reading manga.
I read horizontally with original scaling, and rely on the arrow keys to scroll down or turn the page.
The left/right arrow keys work as intended for page turning, but up/down keys don't initially.
The user has to left click and highlight the page for the up/down keys to scroll the page.

This is exclusive to the up/down arrow keys because with a scroll wheel on the mouse, it works without the highlighting.
Even after the page is highlighted, if you exit out of the current manga and go to another one (or restart that one), the problem occurs again.

**Comment by majora2007** [comment]
You need to give more information with your ticket, like the template shows. Steps to reproduce so I can quickly get a grasp and attempt to fix or enhance.

**Comment by xScarbo** [comment]
Expected Behavior:
When one starts reading manga on original scaling, using the down arrow on their keyboard should scroll the page down accordingly without needing to highlight the page with their mouse.

To Reproduce:
1. Open Kavita on PC and open any manga in the reader.
2. On the reader menu, change image scaling to 'Original' (if it already wasn't).
3. Make sure you're zoomed in enough for there to be a scroll bar on the righthand side and there are some actually pages to scroll down.
4. Press ESC and go back to the series info page. Open up the manga again.
6. Without touching anything, try using the down arrow on your keyboard. It shouldn't scroll down as intended.
7. Now left click anywhere on the reader. Try using the down arrow again. It should work now. Up arrow will scroll up too.


Desktop
- OS: Windows 10 Home
- Browser: Chrome
- Kavita Version: 0.6.1.0

**Comment by xScarbo** [comment]
Issue still present in version 0.7.1.4
