### ISSUE TITLE
Mark as read in Want To Read doesn't save

### ISSUE THREAD

**Issue by Sulframus** [Kareadita/Kavita#1895]
Describe the bug

Mark as read doesn't save in Want To Read view

To Reproduce

1. Add a book to Want To Read
2. Navigate to Want To Read
3. Mark book as read
4. Refresh page
5. Book is marked as unread

Expected behavior

Book would remain marked as marked or even disappear from Want To Read

Desktop (please complete the following information):

OS: Docker
Browser: Opera
Version: 0.7.1.4

**Comment by majora2007** [comment]
I see what's happening. The Want to Read doesn't pull progress information, so even though it was marked as read, the api is returning it as if it's not read. I will correct this. It will not be removed automatically, it will wait for the nightly job. Removing a series from want to read only occurs if the series is fully read and in state of Completed or Cancelled. If it's ongoing, it stays in Want to Read to ensure you complete it fully.
