### ISSUE TITLE
Launching Kavita after reboot under Linux Deb Bullseye

### ISSUE THREAD

**Issue by Aymris** [Kareadita/Kavita#1906]
Hello, I am a Frenchie so excuse my poor english.
I am using Kavita since 0.5. And I install it frequently on my Diepi under Debian Bullseye.
At the first start, next to the installation it works fine.
When I make a first reboot, after adding it on "start on wake up" - do you know app that start after launching PC, like a service, but it is not a service -. So, when I make a first reboot, I obtain a JSON debug.
What is the matter ? What can I do.

Thanks for your help.
**Expected behavior**

**Screenshots**
![Capture du 2023-03-31 07-18-33](https://user-images.githubusercontent.com/129482882/229030747-4a00641d-a5c8-4b46-bb21-4bae7a8fc400.png)

**Comment by majora2007** [comment]
Please check your appsettings.json. it looks like your token is missing.

**Comment by Aymris** [comment]
Thank you. I do not know if it is the right answer, but I have found this under F12 on Firefox : "NC_token : Value dfm6caI73CWh7n%2FsEXJg30GgK1lF7DGH  path:/nextcloud " but I have not got nextcloud. I have got some other value under /nextcloud but I did not install Nextcloud. Only File Browser (filebrowser.org)
![token](https://user-images.githubusercontent.com/129482882/229196458-38473324-ea57-470a-acd2-169d00d3b92e.png)

**Comment by majora2007** [comment]
This has nothing to do with Kavita. Open the place you installed Kavita, open the ./config/appsettings.json and see the TokenKey. Show me what that is.

**Comment by Aymris** [comment]
{
  "TokenKey": "oClai9QUsmgFwwBgznvzXorBMHqZfYDINtr5ZS1zxreKenEFIfGDubjGY\u002BXJm9ipemlyK7BYSbTeThy6pZ1Xnii86Va1c1ml27HZn>
  "Port": 5000,
  "IpAddresses": "0.0.0.0,::"
}


Here is the folder : /home/dietpi/Kavita/config

**Comment by majora2007** [comment]
Okay that json doesn't look well formatted. Change the token key to "" and Kavita will regenerate it. You can validate your json online on any json validation service. 

Once you've done that, restart Kavita.

**Comment by Aymris** [comment]
Soryy. I have tried a lot of things and it does not work.
I have loaded API.deps.json file and appsettings.json under an online json validator. Everything is fine. I have downloaded both and replace them on /~/Kavita and /~/Kavita/config. Olders would be overwritten.
I had reboot. Did not work.
I have "reinstalled" everything. Done chmod +x on Kavita (exec) and chown dietpi (my user) on Kavita/ (folder). I had reboot. And I obtain a same result.
Maybe it is a bug on chown / chmod ? Or something is missing under my Debian install ? But if it was something like that, it would not work at first use ? Is there a conflict with Nextcloud / File Browser ? Something like that ?*
I think I have forgotten after install but I do not know what.
Under Dietpi I use LXQT (to have a desk on my TV, it is my media center) and I added Kavita to run at launch. Could it be the cause ? 

![autostart](https://user-images.githubusercontent.com/129482882/229289878-d5c034ac-9275-4781-b124-16f2d6775bca.png)

**Comment by majora2007** [comment]
Would you be able to join the discord? We have some french speaking users that might be able to help you (and generally more people familiar with Linux)? 

Otherwise @therobbiedavis would you be able to provide support? It looks like their app settings is not valid json and program.cs is getting caught on token code.

**Comment by Aymris** [comment]
Thank you very much for your help. Maybe I am going to join discord or trying with dietpi forum. Thank you. Have a nice day.

**Comment by Aymris** [comment]
I have found. The trouble comes from autostart. I deleted entry and it works again. Bye.
