### ISSUE TITLE
BUS ERROR, ubuntu 22.04

### ISSUE THREAD

**Issue by AxePlex** [Kareadita/Kavita#1907]
Hi, i had Kavita on my old VM on ubuntu 21.10 and it was working fine! I just made me a new one but with ubuntu 22.04 and Kavita won't going on I have this error in my logs: 
/entrypoint.sh: line 27:     8 Bus error               (core dumped) ./Kavita

But I don't know why, so if someone can help me fix it, thx in advance

**Comment by majora2007** [comment]
See our FAQ on wiki for core dumped. You grabbed the wrong package.

**Comment by AxePlex** [comment]
@majora2007 I went to the wiki and found the page you were talking about, so I added the line "privileged: true" but its reporting this in the log "/entrypoint.sh: line 27:     8 Bus error               (core dumped) ./Kavita" 
here is ma command for the docker compose:
  kavita:
    image: kizaing/kavita:latest                            # Change latest to nightly for latest develop builds (can't go back to stable)
    privileged: true
    container_name: kavita
    volumes:
       - /home/ubuntu/Fichier:/Fichier
       - /home/ubuntu/Config/Kavita:/kavita/config          # Change './data if you want to have the config files in a different place. # /kavita/config must not be changed
    environment:
       - TZ=Europe/Paris
    ports:
       - "5000:5000"                                        # Change the public port (the first 5000) if you have conflicts with other services
    restart: unless-stopped


what Is weird is when I was In ubuntu 21.10 there were no issue but with the 22.04 its like that!

**Comment by majora2007** [comment]
Please report back. I'm closing for now.
