### ISSUE TITLE
Limiting Passwords to 32 in HTML leads to unexpected behavior

### ISSUE THREAD

**Issue by thiccaxe** [Kareadita/Kavita#1908]
If a tool such as KeePass-XC is used to generate random passwords for accounts, and the user configures such a tool to use passwords greater than 32 characters, when pasting in the newly generated password into a signup page on Kavita, it will be automatically cropped to 32 characters.

However, a warning is not displayed to the user and he will proceed as normal. This will lead to the inability to login, as the actual password stored in Kavita is only the first 32 characters of the password the user expects.

Note according to MDN: "By default, browsers prevent users from entering more characters than allowed by the maxlength attribute."

Perhaps feedback can be given to the user about this. However, to maintain the client side semantics, the "pattern" attribute can be used in place of max/minlength, as such:

```html
<input type="password" pattern="^.{6,32}$">
```

This should have equivalent functionality.

**Comment by therobbiedavis** [comment]
This should be handled by this bit:
https://github.com/Kareadita/Kavita/blob/develop/UI/Web/src/app/registration/_components/register/register.component.html#L47-L49

However we can certainly add a pattern for further frontend validation.

**Comment by thiccaxe** [comment]
The issue is more specifically that when maxlength is an attribute on an input field, it will crop without giving indication to the user. So the code you mentioned would be modified slightly as well.

**Comment by thiccaxe** [comment]
The PR does not solve the issue, for example:
- copy password of length > 32 from password manager
- paste into password field -> password is cropped by the browser due to maxlength attribute
- no feed back to user about this crop.

See my fork for the intended changes. Since server side validation is done, this will not create a situation where a password > 32 characters is used.

**Comment by therobbiedavis** [comment]
I didn't realize you had a fork. I looked over it and saw you just removed mom and max lengths. Let me consider the changes.

For future reference feel free to submit your own PR especially if you've already made the changes.

**Comment by thiccaxe** [comment]
I was intending to make a PR, but wanted to discuss it in an issue first. I updated my fork after your PR to show what I meant exactly.
