### ISSUE TITLE
Copy issue

### ISSUE THREAD

**Issue by samueler2016** [Kareadita/Kavita#1909]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

**Describe the bug**
Sometimes you try to copy one paragraph,but the system forces you to choose more than that. 
**To Reproduce**
1. Go to "boookname"
2. Click on 'read'
3. Scroll down to 'any paragraph',copy
4. I use both Kavita(Chrome PC) and bookfusion(Chrome PC),but bookfusion seems to offer a better copy experience.

**Expected behavior**
Kavita copy experience could be like that of bookfusion.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker]
 - Browser Chrome
 - Version [e.g. 22] (can be found on Server Settings -> System tab)

**Smartphone (please complete the following information):**

**Additional context**
This happens on Chrome PC.

**Comment by majora2007** [comment]
This isn't helpful. You're talking about copying text in an epub correct? can you give what is wrong with the experience? What does bookfusion do differently, etc.

**Comment by samueler2016** [comment]
Yep,the copy experience in an epub.(Chrome browser PC)
There are 5 paragraphs here.I like paragraph 3(Therefore learn how to condcut...) and need to copy and paste it to Obsidian.

Kavita: It is diffcult to land down the cursor anywhere in paragraph 3.If I am lucky to land it down,it gets something like this. [https://ibb.co/42Fsrvk](url)

bookfusion:please see attached. [https://ibb.co/7VFfFK3](url)

**Comment by majora2007** [comment]
I'm not understanding the suggestion. The bookfusion has a custom highlight function for it's annotation system, which Kavita doesn't yet have. In Kavita, your copy experience is just the browser's copy experience. It would be the same as going to another website and copying text out of it. 

I'm going to close this and ask you to resubmit (maybe with videos) on our feature suggestion website instead.
