### ISSUE TITLE
[Enhancement] Better integration with kaizoku

### ISSUE THREAD

**Issue by Belphemur** [Kareadita/Kavita#1910]
Hello,

When I download manga with Kaizoku, Kavita get notified of the manage downloaded, great.
However, I always have to go back and set the cover.

In the folder that is created by Kaizoku, there is always a cover.jpg file. Could that file be automatically taken for the cover of the manga ?

**Comment by therobbiedavis** [comment]
We do not accept sidecar files like cover.ext. The series cover is typically taken from either the cover or first image in the first archive. I recommend either changing the source in kaizoku to one that has better archives/images (mangapill seems to be better for that) or using komf - https://github.com/Snd-R/komf
With their userscript - https://github.com/Snd-R/komf-userscript

**Comment by Belphemur** [comment]
I see, thanks for the info and the links for Komf.

Can I ask the what's the reason against side car files ?

Sent from Nine
________________________________

**Comment by therobbiedavis** [comment]
The additional complexity and performance hit it adds to the scan loop isn't worth the benefit added.

**Comment by Belphemur** [comment]
Make sense.

Thanks for taking the time, Komf works for me :)
