### ISSUE TITLE
Series detection problem in EPUB

### ISSUE THREAD

**Issue by zsuatem** [Kareadita/Kavita#1911]
**Describe the bug**
Since some version (I'm not sure because I haven't looked at Kavita for a while) the program doesn't treat the series specified in the epub file as the most important one but most likely divides the series based on the title.

I have the series "Ascendance of a Bookworm":
![image](https://user-images.githubusercontent.com/17302628/229597187-07915bd2-eb4c-4d7e-a1c1-f2c271df2a5e.png)

As you can see there is a division into arks here, but it is one series and I have it that way in the metadata.
```xml
<dc:title id="id">Ascendance of a Bookworm: Part 3 Adopted Daughter of an Archduke Volume 3</dc:title>
...
<meta property="belongs-to-collection" id="id-2">Ascendance of a Bookworm</meta>
<meta refines="#id-2" property="collection-type">series</meta>
<meta refines="#id-2" property="group-position">10</meta>
```
However, Kavita has now started dividing this into separate series :/

![image](https://user-images.githubusercontent.com/17302628/229598125-6a977b37-1722-4f0b-99e4-44a62eb3ec8b.png)

**To Reproduce**
1. Add a series where a sub-series can be extracted from the title
2. Scan the library
3. See how the series is divided into several instead of one

**Expected behavior**
If a series is given in the metadata then it should be treated as the most important as it was before. Based on it, the division into series in Kavita should be made.

**Desktop (please complete the following information):**
 - OS: Windows (Client) + Docker (Kavita)
 - Browser: Edge (Chromium)
 - Browser Version: 111
 - Kavita Version: 0.7.1.4

**Comment by therobbiedavis** [comment]
@zsuatem Can you confirm these epubs are epub 3 format? If they are epub 2 you will need to use difference metadata.

`calibre:series` and `calibre:series_index`

https://readium.org/architecture/streamer/parser/metadata.html#collections-and-series

**Comment by zsuatem** [comment]
Version 3
```xml
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="pub-id" xml:lang="en" prefix="calibre: https://calibre-ebook.com">
```

**Comment by Remnence** [comment]
I can confirm this happens to me too. [https://github.com/Kareadita/Kavita/issues/1749](url)

Scanner doesn't always treat metadata as gospel and defaults to filename/folder name to create/sort series.
