### ISSUE TITLE
Table of contents is missing

### ISSUE THREAD

**Issue by coscosname** [Kareadita/Kavita#1912]
**Describe the bug**
Again, the table of contents is missing as in #1279

**To Reproduce**

1. Go to some book
2. Click on Menu button
3. Click on Table of Contents
4. You can see the empty ToC

**Expected behavior**
A working table of contents with all books.

**Screenshots**
![image](https://user-images.githubusercontent.com/89737988/229605819-e32f2e77-c2a9-412c-9d1e-16dce2c71798.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 111

**Additional context**
Kavita version : 0.7.1.4

**Comment by therobbiedavis** [comment]
@coscosname Same book as before?

**Comment by coscosname** [comment]
This screen is from some other book but from what I've checked, the ones with which there was a problem before also don't have a table of contents

**Comment by majora2007** [comment]
Table of contents is provided by the epub file itself. If it's not, Kavita will try to build one for you if certain tags are available. If there aren't any errors in the log, then this isn't really a Kavita issue.

**Comment by coscosname** [comment]
These files have a table of contents. I let you know on discord what files have the problem

**Comment by majora2007** [comment]
Closing this down. I believe this is fixed. If not, please comment again. v0.7.3 released with a lot of work done on ToC generation and fallback.
