### ISSUE TITLE
Live demo site repeatedly downloading epub

### ISSUE THREAD

**Issue by zaSmilingIdiot** [Kareadita/Kavita#1915]
Occurs in the live demo linked from the main website. Epubs downloaded from the site are repeatedly downloaded when navigating certain links. Specifically, navigating to the user account details, and clicking on various tabs will repeatedly download the same epub file (one for each link clicked on). This can be stopped by manually refreshing the page (using the browsers refresh button). However, if instead of viewing the user details, if a menu link such as 'Reading Lists' is selected, then the repeating download behaviour does not occur.

Its almost as if the download request is cached and clicking on a menu item ignores that cached download request, but the user menu does not do this (or rather, the user menu section caches the download request)

1. Log into the live demo ( https://demo.kavitareader.com/ ) with the website provided username/password
2. In the left-side menu, select the "Books" option.
3. Click on an image of any of the listed books, opening a "details" page.
4. Near the top of the page, are 4 buttons, click the "..." button and select the "Download" option.
5. After the file has downloaded, click on the username in the top-right of the page, and select the "Settings" option in the drop-down menu.
6. Note that the epub file is downloaded again. 
7. In the "User Dashboard" page, clicking on any of the tabs or buttons in the page (eg: refresh API key button), the same file is downloaded again.
8. Navigate to any other left-side menu item, eg: Reading Lists. Clicking buttons and navigating around the menu and the menu pages does not re-attempt a file download.
9. Click again on the username in the top-right of the page, and select the "Settings" option in the drop-down menu. When the page loads, or clicking on tabs or buttons, the same file is downloaded again (one per 'actionable' click).

**Expected behavior**
File is downloaded once?

**Screenshots**
not provided.

**Desktop (please complete the following information):**
 - OS: Fedora Linux 36
 - Browser: Chrome v111.0 and Librewolf (fork of Firefox)
 - Version: unknown? Live demo version

**Smartphone (please complete the following information):**
N/A

**Additional context**
Nothing additional to add

**Comment by gene1wood** [comment]
I also saw this behavior

**Comment by gene1wood** [comment]
It looks like this moved from `Done, Not Pushed` to `Done` yesterday however the demo site still manifests this problem. If I follow the steps outlined to reproduce it, it still occurs.
