### ISSUE TITLE
[eBook] Chapter image hiding text

### ISSUE THREAD

**Issue by samin-xactly** [Kareadita/Kavita#1917]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
Not sure if it's just this eBook, or if it's the reader, but the chapter image is being rendered on top of text

**To Reproduce**
1. Find a book that has an image under the chapter number
2. Read it using kavita
3. Read it using calibre

**Expected behavior**
There should be spacing under the image that pushes the text down. If this is undesirable, there should be an option to hide, or render it under text. Or some other way to handle chapter images

**Screenshots**
![image](https://user-images.githubusercontent.com/42816963/230213836-0e471c4c-68e7-4363-9930-74f7a911ed0e.png)![image](https://user-images.githubusercontent.com/42816963/230213858-91f10399-7468-4897-abc7-3ce5743a044d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker]
 - Version [e.g. 22] (can be found on Server Settings -> System tab)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: 16.3.1
 - Browser safari (as Home Screen app)
 - Version latest on App Store 

**Additional context**
I get around this by copying the text under the image and reading it in the notes app.

**Comment by majora2007** [comment]
![image](https://user-images.githubusercontent.com/735851/235303875-14fb727d-686d-438a-8cb2-4bcac9c6f61d.png)
![image](https://user-images.githubusercontent.com/735851/235303891-4632347a-5a0d-42f4-95d9-0c6d45b632da.png)

It's working for me on the latest version of Kavita. Please update to the latest version.
