### ISSUE TITLE
Bug when adding multiple new tags

### ISSUE THREAD

**Issue by Dgenner** [Kareadita/Kavita#1918]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
When adding tags to metadata and creating new tags adding a second new tag will remove the first tag entered. 

**To Reproduce**
1. Go to 'Edit Series Data'
2. Click on 'Metadata'
3. Go to 'Tags'
4. Add (new not previously used) tag (using example tags): "Blue"
5. Press 'Enter' to add tag and tag is entered
6. Type and entered 2nd new tag: "Red" 
7. Press Enter
8. Blue tag is removed red tag never shows. 

**Expected behavior**
That each time a tag is entered it's entered into the list as its own tag. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome  
 - Version 112.0.5615.50 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majora2007** [comment]
This is already fixed in Kavita nightly.
