### ISSUE TITLE
.kavitaignore rules not applied to already indexed files

### ISSUE THREAD

**Issue by IvoMajic** [Kareadita/Kavita#1919]
If the .kavitaignore file is added after a file is already indexed into a library, the ignore rules are not respected for the existing files. Example - I already had some PDF files indexed but decided to globally exclude them, after adding the .kavitaignore file into the root of the library and rescanning, the PDF was still included.

**Expected behavior**
The .kavitaignore rules are applied even to already indexed library items

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox
 - Version 0.7.1.4

**Comment by majora2007** [comment]
This is correct and how I designed it. The solution is to remove the files in the UI then rescan. You can also use a Forced Scan which will treat all files as being modified and thus the kavitaignore will ignore them and delete them from Kavita, however you incur extra work scanning other parts of your library.
