### ISSUE TITLE
Errors when scanning books

### ISSUE THREAD

**Issue by yeraycito** [Kareadita/Kavita#1921]
Kavita installed via Docker on Qnap NAS

Calibre library of 30,000 books

Once the folder with the Kavita books has been assigned, the scanning starts. The first 8000 books are detected without errors, but from then on all the following books give an error. Sometimes it does it because of an error in the database and sometimes when reading the metadata of the books, which is impossible because all the books in the library are managed by Calibre and have the same structure.

**Comment by majora2007** [comment]
This issue isn't very helpful. Are you asking for support? Where are the logs? Are you following the requirements? What are you expecting me to do?

**Comment by yeraycito** [comment]
The requirements are met. I do not put logs because I already have it uninstalled, the installation through docker is perfect and I have done it several times and the same thing always happens. Once the folder with the books is assigned, the quick scan starts and when it finishes, the second scan starts to check the number of pages. After about 36 hours it has scanned about 7000 - 8000 books perfectly and from then on it gives metadata reading error with the following books something that should not happen because all the books have the same structure not only of folders but also of metadata. I have the impression that after a certain number of books Kavita does not work properly.

**Comment by yeraycito** [comment]
![1](https://user-images.githubusercontent.com/65027248/231471364-2c4f93e8-aa87-4870-83e3-b73db6c8c441.png)

I have reinstalled Kavita, when I get an error I will post screenshots and logs.

**Comment by yeraycito** [comment]
Folder structure:

![3](https://user-images.githubusercontent.com/65027248/231476014-9fa82d73-c0c3-4044-8914-d8df7f11037e.png)

**Comment by yeraycito** [comment]
![5](https://user-images.githubusercontent.com/65027248/231476623-beb5f374-8c60-4624-bcbc-729d0a0a657d.png)

**Comment by yeraycito** [comment]
![6](https://user-images.githubusercontent.com/65027248/231476722-be18c24c-244d-494b-ac31-6000febf181b.png)

**Comment by yeraycito** [comment]
Calibre-web library:

![4](https://user-images.githubusercontent.com/65027248/231476934-aeb4beb1-52d3-4a10-9a31-ea84e817f3c7.png)

**Comment by yeraycito** [comment]
![7](https://user-images.githubusercontent.com/65027248/231478418-8b7d1f9c-0706-426d-89a1-d1f43b149db3.png)

**Comment by yeraycito** [comment]
![8](https://user-images.githubusercontent.com/65027248/231478482-b981d806-b451-4011-9449-f5c3e2258197.png)

**Comment by yeraycito** [comment]
![1](https://user-images.githubusercontent.com/65027248/231482199-024e674d-eb97-4609-a6aa-aad3a6d9eacd.png)

**Comment by yeraycito** [comment]
![2](https://user-images.githubusercontent.com/65027248/231483046-82ea5bc0-a627-44de-896e-ae4b0d5351ee.png)

**Comment by yeraycito** [comment]
Despite the page count error Kavita still adds the books correctly.

![1](https://user-images.githubusercontent.com/65027248/231486149-050255cb-a725-4d59-a06f-0b659b40a5f2.png)

**Comment by yeraycito** [comment]
![2](https://user-images.githubusercontent.com/65027248/231486231-a8f893e3-d57b-4f81-b3b4-266d5e593939.png)

**Comment by yeraycito** [comment]
![3](https://user-images.githubusercontent.com/65027248/231487622-0acc39a1-cfcb-4ea4-a596-c52ca60ceb45.png)

**Comment by yeraycito** [comment]
![1](https://user-images.githubusercontent.com/65027248/231491464-2e86a8d1-dae0-423d-81c2-d7af98843a98.png)

**Comment by yeraycito** [comment]
Despite the error Kavita continues to add books correctly.

![1](https://user-images.githubusercontent.com/65027248/231501312-62169422-461b-449e-89ee-f3639d139118.png)

**Comment by yeraycito** [comment]
![3](https://user-images.githubusercontent.com/65027248/231501458-8fe022c5-651a-49f0-b281-f9644b070e62.png)

**Comment by yeraycito** [comment]
[kavita20230412.log](https://github.com/Kareadita/Kavita/files/11213023/kavita20230412.log)

**Comment by yeraycito** [comment]
It continues to add books without problems despite the error.

![1](https://user-images.githubusercontent.com/65027248/231532702-16f423c4-da02-40a8-82cd-d5a4642b3635.png)

**Comment by yeraycito** [comment]
![2](https://user-images.githubusercontent.com/65027248/231532788-034a6a92-a497-4fd3-9778-ea6e0bf39baf.png)

**Comment by yeraycito** [comment]
![3](https://user-images.githubusercontent.com/65027248/231532837-0e2aba95-8e32-4815-b795-e9cf14969606.png)

**Comment by yeraycito** [comment]
[kavita20230412.log](https://github.com/Kareadita/Kavita/files/11214169/kavita20230412.log)

**Comment by yeraycito** [comment]
Later on, a different type of failure occurs that stops adding more books to Kavita. Tomorrow I will post more screenshots and logs.

**Comment by yeraycito** [comment]
![2](https://user-images.githubusercontent.com/65027248/231756548-e2188b08-a075-42c9-92a7-47fbf9c59ade.png)

**Comment by yeraycito** [comment]
![5](https://user-images.githubusercontent.com/65027248/231756672-ca78858b-f39c-48cf-9a41-96c8c7387c5f.png)

**Comment by yeraycito** [comment]
![6](https://user-images.githubusercontent.com/65027248/231756717-89c69569-fa6e-47a1-b666-13bc55ab5759.png)

**Comment by yeraycito** [comment]
![3](https://user-images.githubusercontent.com/65027248/231756884-469ec5fe-fecc-45b1-bfa5-fcc8976d5b97.png)

**Comment by yeraycito** [comment]
![4](https://user-images.githubusercontent.com/65027248/231756974-33f1b466-74e8-468b-a363-654dfcb72629.png)

**Comment by yeraycito** [comment]
[kavita20230412.log](https://github.com/Kareadita/Kavita/files/11222132/kavita20230412.log)
[kavita20230413.log](https://github.com/Kareadita/Kavita/files/11222145/kavita20230413.log)

**Comment by yeraycito** [comment]
![1](https://user-images.githubusercontent.com/65027248/231758326-7fd95144-5b6b-48d4-8570-a4edaec817b6.png)

The pages are not numbered.

**Comment by yeraycito** [comment]
![1](https://user-images.githubusercontent.com/65027248/231761024-45113886-71ca-47df-8d4b-5e267097663e.png)

**Comment by yeraycito** [comment]
I was testing version 0.7.1.4 with my library of 15000 books ( epub 3 validated with Sigil ) when scanning it gave errors and Kavita only detected 14500 books. I uninstalled Kavita and installed the new version 0.7.2 and after scanning it detected 14700 books. I am very surprised by the scanning system of kavita, the first hour it scans very fast but then it slows down the scanning speed. The first hour it scans about 1000 books but after the third hour it only scans 200 books per hour. I get the impression that it is the slowness of the scanning that causes the errors. When it scans a few books, there are no errors, but when the library is large, Kavita fails. Kavita uninstalled due to malfunctioning.

**Comment by yeraycito** [comment]
The error discussed here also occurred on my nas Qnap: https://github.com/Kareadita/Kavita/issues/1966

**Comment by cabiamdos** [comment]
I have the same error here I don't understand why kavita just don't limit itself to hosting epub/pdf or whatever files instead it has to do all these mess
