### ISSUE TITLE
Metadata Genre and Tag fields are caching all inputted data

### ISSUE THREAD

**Issue by GarrettDN** [Kareadita/Kavita#1922]
**Describe the bug**
Metadata genre and tags are remaining in the system after they have been removed from all media that were using those genres and tags. A lot of media that is placed into Kavita is dirty, typos, inaccurate metadata, etc. and Kavita is keeping a history of the trash metadata in dropdown lists, cluttering the interface when trying to appropriately enter metadata.

**To Reproduce**
1. Add media to library (book, comic, or manga)
2. Edit the media using the pencil icon
3. Click on 'Metadata'
4. Add any genre, for example (History)
5. Delete the metadata genre
6. Genre is still available in the suggested dropdown even when no media is using the genre

**Expected behavior**
I would expect the genre to be removed from the system once the genre has been removed from the last media entity. If not that approach, a place to refresh the genre dropdown list by pulling only actively used genre and tags.

**Screenshots**
![KavitaGenreTrash](https://user-images.githubusercontent.com/130538345/231372240-d911fd92-039c-460d-9e8b-f663d0e4d16c.png)

**Desktop (please complete the following information):**
 - OS: Synology 7.1, Docker
 - Browser: Chrome
 - Version: 111.0.5563.148

**Comment by majora2007** [comment]
This is already fixed in Kavita nightly.
