### ISSUE TITLE
Epub Highlighting can get caught under Tap to Paginate and feel weird

### ISSUE THREAD

**Issue by samueler2016** [Kareadita/Kavita#1931]
Hi Majora,I've uploaded two videos to elaborate.

My Copy&Paste plan: ONLY "Therefore learn how to conduct an interview...or even yourself,awake."

Copy&Paste with Kavita&Obsidian：https://youtu.be/ZqFU9f-jJyQ

Copy&Paste with Bookfusion&Obsidian：https://youtu.be/J0vrvDklH7E

**Comment by scare376** [comment]
Are you trying to point out the fact that if you are highlighting and cross over the tap pagination area it jumps to the top of the page?

**Comment by samueler2016** [comment]
> 

Sort of. The cursor does not seem to "focus" or "land down"

**Comment by majora2007** [comment]
From the video and testing, it seems that if you scroll into the tap to paginate area, it gets caught and has the effect you're talking about. I'll look into it.

**Comment by samueler2016** [comment]
Disabling the "Tap to paginate" (username-settings-preferences-bookreader-tap to paginate)button seems to help solve this issue...
