### ISSUE TITLE
The current time zone does not match the last time scanned.

### ISSUE THREAD

**Issue by YTOAA** [Kareadita/Kavita#1935]
Written in docker-compose on Ubuntu os. When you enter the date command in that container, the normal time is displayed. In fact, If you look at the time of the document recorded inside Kavita, it's also normal. However, even if you just pressed Scan in the library in the kavita settings, it shows the time 9 hours ago.

The actual time in the picture below was 10:39 a.m
![Screenshot_20230420_104147_Edge](https://user-images.githubusercontent.com/24527825/233236054-cc9da0dd-9c0d-4ab3-a86e-39aa71471d5f.png)

version: '3'
services:
    kavita:
        image: 'kizaing/kavita:latest'
        volumes:
            - /manga:/manga
            - /kavita/config:/kavita/config
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Seoul
        ports:
            - "5000:5000"
        restart: unless-stopped

**Comment by majora2007** [comment]
For me, the timezone works, except when viewing from a different timezone than my server, the time ago is from the browser's timezone and doesn't take server timezone into account. This might be happening for you, but last scanned time and others are always in server time.

**Comment by YTOAA** [comment]
What's interesting is that the last modified time in the series of scanned folders is normal. Can this be modified in the next version?

**Comment by majora2007** [comment]
I confirmed this to be a bug from last release.
