### ISSUE TITLE
Filter - find blank matches

### ISSUE THREAD

**Issue by jungle-boogie** [Kareadita/Kavita#1936]
Hi,

Sorry if this is the wrong format to ask about this...

I really like all the filter options with in Kavita, but I can't seem to find a NOT filter.

For instance, if I have 100 ebooks and 75 have the proper genre tags, how do I find the 25 with BLANK genre data?
With this kind of search, I would be able to update the metadata for my materials and filter better next time.

Thanks!

**Comment by majora2007** [comment]
There is a feature request for this already. Please upvote that. GitHub is for issues and support.
