### ISSUE TITLE
Incorrect number of books

### ISSUE THREAD

**Issue by yeraycito** [Kareadita/Kavita#1939]
Kavita on docker installed on Qnap nas.

A few days ago I had a problem scanning my books through Kavita: https://github.com/Kareadita/Kavita/issues/1921

You replied that I had two problems with my book library, the first was that some of my books were in EPUB1 format and the second problem was that many of the books had the wrong metadata. To solve the latter you told me to use Sigil to validate the books. I have started to solve these two problems, I am converting the books in my library to EPUB3 and then validating them with Sigil one by one. Once this is done, I'm adding them to Kavita.

**Comment by yeraycito** [comment]
![2](https://user-images.githubusercontent.com/65027248/233638251-41753023-38da-49d9-8cc1-09179e402f5b.png)

**Comment by yeraycito** [comment]
![3](https://user-images.githubusercontent.com/65027248/233638312-cf3d9c9b-721b-4939-8492-07e70ea31f54.png)

**Comment by yeraycito** [comment]
As of today I have 5827 books that way.

![1](https://user-images.githubusercontent.com/65027248/233638566-bf2ca30c-8fbb-4204-a52b-72ba9625e884.png)

**Comment by yeraycito** [comment]
Kavita scans the books I add without errors. However, the number of books does not correspond to the actual number of books.

![4](https://user-images.githubusercontent.com/65027248/233638913-d7cde37e-1730-4bc3-a368-405b95a5ea3f.png)

**Comment by yeraycito** [comment]
The more books I add to Kavita the bigger the difference in the number of books becomes..... and the books are perfect.

[kavita20230420.log](https://github.com/Kareadita/Kavita/files/11295803/kavita20230420.log)
[kavita20230421.log](https://github.com/Kareadita/Kavita/files/11295805/kavita20230421.log)

**Comment by majora2007** [comment]
Logs look good, so nothing stands out there. Do you happen to know any books might be missing? In addition, can you verify that the 5827 are all unique books and none of them are the same, which would cause stacking?

**Comment by yeraycito** [comment]
I have created a new empty Calibre library on my computer and I am adding the books bit by bit so it is impossible to miss any of them. Once I have added the books I convert them to EPUB3 and then validate them with Sigil one by one. Then I add them to a different and empty library in Calibre, which is the definitive one. The 5827 books are unique and there are no repeated books.

**Comment by yeraycito** [comment]
![1](https://user-images.githubusercontent.com/65027248/233661874-edf99858-776d-431d-9a68-d5836b6db13c.png)
![2](https://user-images.githubusercontent.com/65027248/233661913-f5d55f7b-4ad4-4726-82a4-f32efbe74ce5.png)
![3](https://user-images.githubusercontent.com/65027248/233661939-7d351908-e9b3-429d-941d-3f7e7e2f1a7c.png)
![4](https://user-images.githubusercontent.com/65027248/233661963-ac1b2067-1c8b-4a15-89e0-5a15286e1159.png)

**Comment by majora2007** [comment]
In the logs, it's showing that you're doing a normal scan. Can you do a forced scan on the library so Kavita ignores previous folders from last scan that haven't changed? You can find this in Library Settings (from side nav) and Force Scan.

**Comment by yeraycito** [comment]
Before doing the forced scanning you ask me to do, I added some books to Calibre and Kavita.

Calibre Library before: 5827 books
Calibre Library now: 6355 books
Difference: 528 books

**Comment by yeraycito** [comment]
![1](https://user-images.githubusercontent.com/65027248/233702123-a56e267d-a771-4fe8-9ce3-261824da0b50.png)

**Comment by yeraycito** [comment]
I have made a normal scan

![2](https://user-images.githubusercontent.com/65027248/233702293-b38b4693-5611-48bc-adfa-4437c0f776a0.png)

**Comment by yeraycito** [comment]
Kavita shows that the scan was performed 2 hours ago and it is incorrect, it finished 5 minutes ago.

![3](https://user-images.githubusercontent.com/65027248/233702589-42c4c454-6bfd-42ad-bc1d-996264ec7910.png)

**Comment by yeraycito** [comment]
![4](https://user-images.githubusercontent.com/65027248/233702644-5436fd04-1b9c-4382-bccc-118e5c930b69.png)

**Comment by yeraycito** [comment]
Kavita before: 5769 books
Kavita now: 6283 books
Difference: 514 books

14 books missing

**Comment by yeraycito** [comment]
[kavita20230421.log](https://github.com/Kareadita/Kavita/files/11298169/kavita20230421.log)

**Comment by yeraycito** [comment]
I proceed to do a forced scan.

![1](https://user-images.githubusercontent.com/65027248/233703475-551b2e6f-690d-4c14-bec9-1bba4b652791.png)

**Comment by yeraycito** [comment]
![2](https://user-images.githubusercontent.com/65027248/233703513-27f632a9-52dd-4b53-8332-658b6be235b3.png)

**Comment by yeraycito** [comment]
Because of the number of books it will take a few hours to scan. I will post the result later.

**Comment by yeraycito** [comment]
After 4 hours from the start of the forced scan without any errors Kavita has started to fail.

![1](https://user-images.githubusercontent.com/65027248/233742737-e6d0e2d6-c07a-49f5-a464-9ec7cd78c3ca.png)

**Comment by yeraycito** [comment]
The number of books remains the same.

![2](https://user-images.githubusercontent.com/65027248/233742842-3d84cb79-fb77-4b76-9921-befd99431c4a.png)

**Comment by yeraycito** [comment]
[kavita20230421.log](https://github.com/Kareadita/Kavita/files/11299570/kavita20230421.log)
[kavita20230422.log](https://github.com/Kareadita/Kavita/files/11299571/kavita20230422.log)

**Comment by yeraycito** [comment]
This can't go on, I stop the container to stop the forced scanning.

**Comment by majora2007** [comment]
Okay you are showing the issues in #1611 which are preventing those books from being added. Unfortunately this is a hard to debug issue as it's only reproducible on other users setups and not my own. I've been slowly chipping away, but I do not have a solution as of yet.

**Comment by yeraycito** [comment]
Even so, the problem of the difference in the number of books still occurs. This last problem was due to the use of forced scanning, with normal scanning it has never happened before.

**Comment by majora2007** [comment]
It did happen before, hence the difference in books. When this error occurs, the series is dropped.

**Comment by yeraycito** [comment]
I honestly don't understand how you develop software that doesn't work. You say that problems occur with other people's configurations but not with yours. I have Kavita installed using a Docker provided by you so the question is what is the difference? I have been using Calibre-web installed via Docker on my nas for years and also natively installed on a computer with Manjaro always without any problems. If Kavita is unable to correctly scan a simple folder with books you have a major problem.

**Comment by Rob117** [comment]
Don't worry - you're entitled to a full refund of the purchase price if you don't like it.
