### ISSUE TITLE
Issue parsing epubs mangas

### ISSUE THREAD

**Issue by nithou** [Kareadita/Kavita#1940]
I'm trying to add my manga library to Kavita in epub but it doesn't seem to recognise my series and create separate entry for each epub file even if I followed the naming convention as good as I could so it look like this:

Doushitemo Furetakunai - Vol. 001 Ch. 0001.epub
Doushitemo Furetakunai - Vol. 001 Ch. 0002.epub
Doushitemo Furetakunai - Vol. 001 Ch. 0003.epub
[...]
Doushitemo Furetakunai - Vol. 002 Ch. 0027.epub

Each appears as a separate entry instead of being aggregated inside the serie name and separated by Volume

**Comment by majora2007** [comment]
Please follow our guide here. You need to use the correct internal metadata for epub files. 
https://wiki.kavitareader.com/en/guides/managing-your-files/ebooks

**Comment by nithou** [comment]
That’s the part I don’t understand, per the documentation it’s supposed to parse first by the filename but it does not : « The first pass tries to parse from the filename. If volume and series name can be parsed »

**Comment by majora2007** [comment]
That is true. Open your epub and show the opf inside of it. Is there anything in there that would contradict? What does the Series say?

**Comment by nithou** [comment]
Looks like that for one volume:

```
    <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
        <dc:title>Clover / Chapter 1</dc:title>
        <dc:language>en-UNDEFINED</dc:language>
        <dc:identifier id="JTJGVmsdWlcyUyRkNvbWljcyUyRkhbmdhcyUyRkNsbZlciUyRkNoYXBZXIlMjAxLmVwdWI" opf:scheme="UUID">JTJGVmsdWlcyUyRkNvbWljcyUyRkhbmdhcyUyRkNsbZlciUyRkNoYXBZXIlMjAxLmVwdWI</dc:identifier>
    </metadata>
```

**Comment by majora2007** [comment]
Interesting, I looked and I have a series that relies like this on filename parsing (shows as Volumes) in the Book library and the metadata is similar to yours

```
<metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
    <dc:identifier id="BookId" opf:scheme="UUID">urn:uuid:e4de0666-740c-4527-9aa5-29a522d7d3ec</dc:identifier>
    <dc:title>Kore wa Zombie Desu ka? - Volume 1: Yes, I’m a Masou Shoujo</dc:title>
    <dc:creator opf:role="aut">Kimura Shinichi</dc:creator>
    <dc:language>en</dc:language>
    <dc:date opf:event="modification">2022-11-29</dc:date>
    <meta content="1.9.20" name="Sigil version"/>
    <meta name="cover" content="cover.png"/>
  </metadata>
  ```

**Comment by majora2007** [comment]
Okay I was able to reproduce this. I do see why this is happening and I suppose I need to update the wiki. If the Series tag is missing from the opf file, then it will fallback to Title of the book (as many books are not actually Light Novels or manga). This is not something I want to change as it makes sense for the main use-case of books.

I will update the wiki to make it more clear that for EPUBs, only volume and chapter can be parsed out in certain situations. For the most part, epub expects all metadata to be within the file, as it has a system that's documented to support it.

**Comment by nithou** [comment]
Thanks for your help!
