### ISSUE TITLE
Reading throws exception in webtoon mode on ios

### ISSUE THREAD

**Issue by strauzen** [Kareadita/Kavita#1947]
I am running a Kavita 1.7.4 server in a docker container, when I read using vertical infinite scrolling (Webtoon?) mode on Windows Edge it all goes fine, but when I do it on ios edge or safari I get a series of unexpected errors. When looking at the logs it states: "database locked"

To reproduce:
- Using iOS Open safari and log into Kavita
- (Optional) Save as a desktop shortcut and use that instead.
- Load a heavy comic 60+ pages high quality pictures (I used a cbz 13MB)
- Set vertical scrolling mode
- Scroll as fast as possible to the end of the comic with your finger
- See series of errors appear on screen and pages stop loading
- See logs

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.4.1
 - Browser Safari

 
**Additional information
Attached are a screenshot and the logs, the error start can be seen at: [Kavita] [2023-04-30 16:16:34.208 +00:00  39]

[kavita20230430.log](https://github.com/Kareadita/Kavita/files/11361766/kavita20230430.log)
![unnamed](https://user-images.githubusercontent.com/2372024/235364933-941913a6-1820-485b-8bd6-3486971c6070.jpg)

**Comment by strauzen** [comment]
The error happens independently if I try to load a previous chapter or not. It just happened to be I scrolled to high up in the screenshot.

**Comment by majora2007** [comment]
If you're hitting database is locked issue, you can use this fix:
https://wiki.kavitareader.com/en/faq#q-im-seeing-database-is-locked-errors-in-my-logs

Likely it's trying to save progress but can't. This fix has been confirmed on my users' machines.

**Comment by strauzen** [comment]
I enabled the WAL mode as indicated by you but I just recreated the issue. You may find the updated log attached. It is still a database locked issue.

Look for:
[Kavita] [2023-04-30 17:06:07.924 +00:00  40] [Error]
[kavita20230430 (1).log](https://github.com/Kareadita/Kavita/files/11361870/kavita20230430.1.log)

**Comment by majora2007** [comment]
Can you provide some background on how your system is setup? Like where your config/ directory is located, what type of Hard drive, and the OS?

**Comment by strauzen** [comment]
The system is running on a docker container on a Synology NAS DS219.
The config directory is in docker/kavita.
Hard drives are Seagates ST8000VN004-2M2101 of 8TB each running in RAID0

**Comment by DieselTech** [comment]
This issue is for a very old version of Kavita that is out of date now. If you are still having this problem, please open a new issue.
