### ISSUE TITLE
Metadata Contributors - EPUB3

### ISSUE THREAD

**Issue by Dunkler2Engel** [Kareadita/Kavita#1950]
I has do a search for how to set Illustrator Metadata for epubs, and it should be supported by EPUB3, but Kavita does not recognize it
I see this:
https://www.w3.org/publishing/epub3/epub-packages.html#sec-role
In example 50, show how illustrator must be set, but if you do this dont recognice it.
But other programs like this https://github.com/benchen71/epub-metadata-editor take without problems the metadata.
Is not supported or is a bug?

Another thing is fields like "Publication Status", that no have similiar option for Metadata Epub , may be possible, to make a Kavita standard?
Like a custom field in Calibre named #PubStatus or something like that, if all have the same can take the publication status for all people, the thing is to make a "standard" and add it to wiki https://wiki.kavitareader.com/en/guides/misc/calibre

But this is secondary and I don't think it will be done.

Edit: There is not only Illustrator, there are some others like

dc:creator or dc:contributor | pbl | publisher
dc:creator or dc:contributor | trl | translator
dc:creator or dc:contributor | edt | editor
dc:creator or dc:contributor | ill | illustrator
dc:creator or dc:contributor | art | artist
dc:creator or dc:contributor | clr | colorist
dc:creator or dc:contributor | nrt | narrator

**Comment by majora2007** [comment]
This is currently not possible due to my downstream library:
https://github.com/vers-one/EpubReader/issues/80

I will however implement if I can get it fixed downstream.
