### ISSUE TITLE
I can't see the image cove

### ISSUE THREAD

**Issue by dkdemfp1002** [Kareadita/Kavita#1962]
<img width="1727" alt="33" src="https://user-images.githubusercontent.com/132772398/236635502-40650d98-29c8-4ba3-a01a-5d5ce504a82f.png">
<img width="1333" alt="34333" src="https://user-images.githubusercontent.com/132772398/236635731-d5db3016-9988-4ab0-9e00-392ca2bfd553.png">

<img width="1357" alt="6666" src="https://user-images.githubusercontent.com/132772398/236635736-d596b708-2f4f-45a9-831e-bd62a8c34849.png">

NAS 7.2RC Docker Kavita version 0.7.2.0 update or later
I can't see the book cover image 
Like the attached image, even if you refresh it
I can't see it.

**Comment by majora2007** [comment]
Hi, did you do anything prior to the update? Can you attach your logs? They should indicate if the file got deleted in config/covers.

**Comment by majora2007** [comment]
I know what the issue is. You need to do a hard refresh.

**Comment by dkdemfp1002** [comment]
> 문제가 무엇인지 압니다. 하드 새로 고침을 수행해야 합니다.

Thank you. Resolving nas Reboots

http://192.168.0.15:8384/library/2  <-2 
Problem Occurred

http://192.168.0.15:8384/library/
problem-solving

Thank you. I solved this problem in no time
