### ISSUE TITLE
Cover Image Uploads above 8 MB fail on Google Chrome for Android

### ISSUE THREAD

**Issue by GlassedSilver** [Kareadita/Kavita#1963]
**Describe the bug**
I have set up Kavita through a reverse proxy and at first thought the issue of not being able to upload (or rather, I tested referencing a URL) cover images for volumes that exceed 8 MB in size was up to my reverse proxy config. Well, I checked it, turns out it shouldn't limit this scenario.
I confirmed this by trying these scenarios:

Firefox for Android: works proxied and unproxied.
Chrome for Android: doesn't work either proxied or unproxied.

Error message appears in the bottom right (white text on red background):
`Request body too large. The max request body size is 8000000 bytes.`

**To Reproduce**
1. Go to a given library entry and try to change the cover art for it.
2. I used the URL reference method for this. Probably errors out for plain image uploads as well.
3. It'll appear in the list of selectable images that otherwise is prepopulated with images extracted from the book(s) themselves. It'll appear at the bottom of the list.
4. Try to apply the image
5. Error as described above should appear.

**Expected behavior**
For the image to be applied like on Firefox for Android.

**Screenshots**
Not much to show except for what the message looks like, but if desired I can make a screenshot and attach it.

**Smartphone (please complete the following information):**
 - Device:  Samsung Galaxy Z Fold4
 - OS: Android 13, One UI 5.1, unrooted
 - Browser: Google Chrome Beta
 - Version: 113.0.5672.51

**Additional context**
I love Kavita!

EDIT:

I'm using the cover images for the Ijiranaide, Nagatoro-san manga from Mangadex.

Whilst a bunch of pictures worked in Chrome, eventually I stumbled upon some that didn't. Firefox worked but now the images for chapter 10 and 11 for example don't work in there either. (unexpected error)

[THIS](https://mangadex.org/covers/d86cf65b-5f6c-437d-a0af-19a31f94ec55/3f37ee5d-4d08-49ad-a0a6-9af7d937c5e7.png) image doesn't work in either Chrome or Firefox, but uploading it through the file uploader after downloading it to my phone works just fine in Firefox.

Seems really convoluted.

**Comment by majora2007** [comment]
This is per design, I hard-coded it at 8MB because I figured it would be extremely rare for someone to upload an image that's larger than that. This is an edge case, but I can likely just increase the limit a bit. I doubt many people run into this and I personally don't want to make it configurable (as there is extra maintenance and testing cost associated).

**Comment by GlassedSilver** [comment]
Thing is, this triggers on files a lot smaller than 8 MB as well... some under 5 MB got yote and to be fair, I think the span between some accidental exaggeratedly large upload causing trouble and mere user intent to upload the best quality available is fairly slim.

If there is any way we could possibly have covers autoloaded from files with the correct naming (similar to "album.jpg" for music, but instead something like "cover_vol1.jpg" or "cover_ch20.png" and so forth) that could be really helpful as well.

In any case it's extra troublesome since the message isn't even appearing consistently and the worst kinds of errors are the ones you spend a long time trying to narrow down.

IMHO 8 MB is very small, especially when you consider that sources like MangaDex experience a LOT more traffic and pride themselves with almost sinful image quality. It feels disingenuous to shrink images publicly sourced for a local setup I can put however resources I want into.

I get the point of having A limit, absolutely, but maybe you can see where I'm coming from?

**Comment by majora2007** [comment]
Sidecar files are not something I'm interested in. You can always just save the cover in the underlying archive and use the word cover, which will take it as priority. This is the flow I personally use.

In addition, massive files don't actually make much difference since Kavita will resize them down and compress them regardless.

I see your point and I think it's more important to align the messaging and ensure that sub-8MB don't fail.

**Comment by GlassedSilver** [comment]
I don't want to store the covers in archives for items I store with chapter granularity, which is all of my manga so far.

I prefer having my chapters preview imagine be the first frame whilst the volumes are virtual wrappers for them with their own metadata hierarchy level, that's where I would like to assign my cover. (I specifically do so from Kavita right now as well, not assigning to my chapters)

The difference is definitely there, because should I ever switch my manga server (no plans to do so at all, from all the options I went over over the years Kavita looks by far like the best option, but nothing lasts forever and maybe one day I need to run a fork or whatever...)

So portability and having the highest quality source to generate the actual samples from makes a lot of sense. Even more so if Kavita scales them down and compresses them anyhow? 🤔

**Comment by GlassedSilver** [comment]
Regarding the extension of the issue concerning sidecar files... I know you said you're not interested in them, but I think I laid out why they can make sense, at least for some users and how they would like to work with their libraries.

If you're not completely against it, tell me if it's worth adding it as a new issue for trackability. I've never been a big fan of storing things redundantly on a smaller hierarchy level, although I appreciate that Kavita allows for that sort of flexibility. It makes things work smoothly when otherwise you wouldn't have values and such because info can be spotty. (e.g. the publication status being able to be overridden by the latest chapter, iirc I brought that up as idea at some point somewhere, maybe even with Komga, I cannot remember. Could have been in the ANANSI project as well.)

**Comment by majora2007** [comment]
I'm going to close this issue out. 
1. Uploading an image over 5MB (which I've never seen) works as of Kavita v0.7.10
2. I checked MangaDex for the series in question and the largest image I could find was 2MB. 
3. This issue is quite old. Please recreate a new one if you're facing it.
