### ISSUE TITLE
Changing pages freezes sometimes around pages 10-13

### ISSUE THREAD

**Issue by iamhanyolo** [Kareadita/Kavita#1977]
I'm having  a weird issue where scrolling through (using the browser on pixel 6 pro) causes it to freeze around pages 10-13 and it'll hang and then start working again. Happens sporadically across multiple CBZ. U can see the video here in Fullscreen
https://youtu.be/-Ohi1mI9Lbk

**Comment by iamhanyolo** [comment]
Not sure if you need specs but Server is currently running on Windows Server 2019 VM with 8vCPUs and 8GB of RAM, and 10Gbps NIC. 

Not sure if that's affects anything.

**Comment by iamhanyolo** [comment]
Yeah it happens every now and then. I appreciate all your hard work. Thank you for looking into this.

**Comment by majora2007** [comment]
I believe I actually fixed this in a recent v0.7.8.x release. If you're on the nightly, would appreciate it if you could check it out. If not, I'll ping once v0.7.9 is out.

**Comment by majora2007** [comment]
Pinging now that the release is out. Let me know if you're experiencing this anyone on the latest.

**Comment by DieselTech** [comment]
@iamhanyolo If you are still having this issue please reach out and let us know. Closing for now.

**Comment by iamhanyolo** [comment]
Hi. Thanks for all your hard work. I am not experiencing this issue anymore
I believe. Thank you!
