### ISSUE TITLE
Unsupported file format include cover jpg

### ISSUE THREAD

**Issue by phhowe17** [Kareadita/Kavita#1978]
I'm test driving your application and it looks promising. My test library contains a number of .mobi formatted book.  When the library is scanned, an entry is made for the book, but it only includes the cover page.  

D:\Plex\Books\_Digital books\A\Anonymous\The Arabian Nights
cover.jpg
The Arabian Nights - Anonymous.mobi

I would prefer that if a format was not supported, the other material in the folder was not included.

Thanks.

**Comment by majora2007** [comment]
This is because Kavita supports image libraries and likely the image is being thought of as an image library. 

You can add a .kavitaignore file to your library root with this:
*.jpg
*.png
...etc

It will ignore files types that you put in it.
