### ISSUE TITLE
Series with the same name get combined in recently updated series section despite being in 2 different libraries

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#1979]
**Describe the bug**
2 Series with the same name will get combined in the recently updated series section of the home page even if they are in 2 separate libraries

**To Reproduce**
1. Add a series to 2 different libraries with the same name
2. Go to home page
3. Recently updated series will have a number indicating the number added and it will be the same as both combined.

**Expected behavior**
Series with the same name in 2 separate libraries are not combined in recently updated section.

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/2068470/ee24b207-a797-4e0e-9b76-4f7fb058b198)

**Desktop (please complete the following information):**
 - OS: Docker
 - Version 0.7.2.2

**Comment by majora2007** [comment]
This will be released in v0.7.4.
