### ISSUE TITLE
PDF shows background but text is blurred/smudged away on some pages but not others

### ISSUE THREAD

**Issue by TinyLexy** [Kareadita/Kavita#1990]
**Describe the bug**
I'm having an issue with a PDF that I was not experiencing on 0.7.1.4. There are backgrounds behind the text that display fine however the text on some pages look like the text is blurred/smudged off. It's not every page, just some. When viewing in Kavita, it is wonky across all my devices (computer, iPhone, iPad). Have verified that it looks fine while opening the PDF in Firefox (113.0), Chrome (v113.0.5672.93) and Adobe Reader. Pages affected is a long list so will just add a few examples: 24, 30, 41, 60, 120, etc.

Server info:

    OS: Synology NAS DSM 7.1.1-42962 Update 5
    Kavita version: 0.7.2, installed from Docker Hub (2nd update that was pushed)

The PDF in question is already sent to @majora2007 by Discord DM.

**To Reproduce**
1. Open PDF in Kavita
2. Scroll down to page 24, 30, 41, 60, 120, etc.
3. See the page behavior

**Expected behavior**
Text be seen instead of smudged/blurred/removed.

**Screenshots**
![Taken from Kavita on iPhone](https://i.imgur.com/SVy3nnV.jpg?raw=true)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox, Chrome
 - Version: Firefox v113.0, Chrome v113.0.5672.93

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max and iPad Pro
 - OS: both running iOS version 16.5
 - Browser: Safari

**Comment by TinyLexy** [comment]
This could be completely irrelevant development wise but I wanted to come back and update, if not for development purposes for other users who may run into any edge cases. It has been driving me crazy that this is the only PDF in my library that has the weird disappearing text issue, especially since I have a decently sized PDF library and all of them outside of this file work flawlessly. Before I go on my little (_okay, long_) explanation, things to note: 

- (1) This was a non-issue while running Kavita v0.7.1.4 but has been present since 0.7.2 and all subsequent releases 
- (2) Even though the pdf was not viewing correctly in v0.7.2 onwards - Firefox, Chrome and Adobe all viewed the file perfectly
- (3) I know little about the technical terms you'd use to describe these things so bare with me as I describe my findings

I kept circling back to "it looks like the words are just blurred off the page" which led me to question if OCR was contributing to the problem. I have plenty of other OCR'd pdfs that behave correctly but I couldn't shake the feeling this might be where the hang up was so I decided to run some experiments. The first thing I wanted to try was flattening the PDF. When I opened the PDF in Adobe Acrobat, I noticed that there was a hidden cover layer. Ah I thought, this might be it! This might be the issue, right? I used Adobe to flatten the layers, saved and moved it to my Kavita library. Pull it up, no dice. Still has words blurred off the pages, even though the hidden layer was now visible. Shoot okay...maybe the hidden layer wasn't it after all.

Circle back to questioning if OCR may be the culprit so I moved to figuring out how to get a fresh slate. Flattening in Adobe wasn't removing the OCR. You could use Microsoft's Print to PDF feature but that leaves you with ugly white borders at the top/bottom or sides so I spent way more time than I'm willing to admit here to find a tool that would flatten the PDF without borders and without losing image quality (pdfFlattener). I was left with a file much larger than the original file (>1gb). From there, I moved that file to my Kavita library and **bam** - all text was completely visible. I was stoked, I was ecstatic! But I couldn't stop there: once flattened, all selectable text and bookmarks were obviously gone. **BOO!** I decided to move to the last phase of my tests. I couldn't bare to hand bookmark 300+ pages so I used pdfXchange to copy the bookmarks from the OG file to the new, working flattened PDF. Moved that file over, bookmarks in working order and text still visible in Kavita Reader. Check! Here comes the moment of truth...could it be that OCR _really was_ causing all this fuss? 

*drum roll please*

...No? _Maybe_? After flatting the PDF, adding the bookmarks back in and then re-OCR'ing it in Adobe I am left with a completely new PDF file that is functioning as intended in Kavita. If you are a Kavita user and run across a similar edge case, it may be worth exploring this option as a fix (if willing to put in the time to do so, in my case it was a reference book that I use weekly so it was totally worth the effort). Your mileage may vary, of course.

**Comment by majora2007** [comment]
@TinyLexy thank you for the update. You might want to actually submit the 2 pdfs to the downstream library I'm using as it's likely a bug in their implementation (since a version update causes the problem). 

Here is the link if you are so inclined:
https://github.com/stephanrauh/ngx-extended-pdf-viewer

**Comment by DieselTech** [comment]
A bunch of other PDF related issues have been resolved by updating the downstream libraries lately. If you are still seeing this issue in the latest kavita release (0.8.2) then please open a new ticket so we can investigate.
