### ISSUE TITLE
Unable to promote more than one collection without needed a reboot.

### ISSUE THREAD

**Issue by hermy65** [Kareadita/Kavita#1991]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
If i promote one collection i am unable to promote another one until i restart the server

**To Reproduce**
Promote a collection
Attempt to promote another collection
Restart server
Promote collection

Version: 0.7.2.0

**Comment by majora2007** [comment]
I wasn't able to reproduce this. Can you retest on the latest version and comment? If so, then please add more information about your setup.
