### ISSUE TITLE
Series renaming fails inconsistently

### ISSUE THREAD

**Issue by 42648594** [Kareadita/Kavita#2000]
**Describe the bug**
Series renaming fails inconsistently

**To Reproduce**
1. Attempt to rename a series
2. For some series, this works, and for others it does not.
3. Embedded metadata seems to conflict/override series rename through web interface, but again inconsistently.
4. Changing the entries in Sort Name and Localized name behaves similarly, sometimes it will successfully change once, and then subsequent changes will fail

**Expected behavior**
Renaming series through web interface should change displayed series name.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 113.0.1
 - Version: 0.7.2.0

**Additional context**
Strangely, sometimes by deleting the whole library and setting up a new one, without changing any files or folder structure, a single name change will go through successfully, but subsequent ones will fail.

**Comment by majora2007** [comment]
This isn't a very helpful issue. I'm not sure how I can help you or what is not working. Please give examples and concrete issues rather than vague general issues.
