### ISSUE TITLE
Book Reader clipping on Pixel 4a - Chrome

### ISSUE THREAD

**Issue by 474r4x14** [Kareadita/Kavita#2001]
**Describe the bug**
When reading an ePub book on my Pixel 4a, if I change the page the right side of the text is cropped by a few pixels. This happens on both Chrome and Brave, using either the browser or installed to the home screen as a PWA. If I close the book and re-open it, the margins display correctly. Looking at the screenshots below, you can see that the body of text is actually offset by a few pixels. It doesn't seem to matter if I change the margin percentage.

I've tried it on another Android phone with a wider screen and it doesn't happen on that. I've also tried it using Firefox on the Pixel 4a which also displays it correctly.

**To Reproduce**
1. Open an epub book in Chrome
2. Go forward or back a page

**Expected behavior**
I would expect the text clipping to not occur

**Screenshots**
![No clipping](https://i.imgur.com/dYrdS9H.png)
![With clipping](https://i.imgur.com/HguUm4Y.png)

**Smartphone:**
 - Device: Google Pixel 4a
 - OS: Android 13
 - Browser Chrome
 - Version 113.0.5672.76

**Comment by majora2007** [comment]
This should be fixed in v0.7.4
