### ISSUE TITLE
Issue grouping working not as expected

### ISSUE THREAD

**Issue by marcdieters** [Kareadita/Kavita#2002]
**Describe the bug**
According to this I need to put files in a certain structure.
https://wiki.kavitareader.com/en/guides/managing-your-files/scanner#file-layout

I've created a test library as following:
- Root folder: /mnt/nas/Stuff To Read/Test
- Type: Comic

But, I have the following structure, which I think, is correct. 
![image](https://github.com/Kareadita/Kavita/assets/24914093/18d157b1-f5a6-4d30-a2aa-54797a4f995f)

Other folders in the library's root /Marvel/Ghost Rider:
![image](https://github.com/Kareadita/Kavita/assets/24914093/6d62d6dd-56f8-41a9-9704-db83c02d0a30)

But, for some reason, Kavita bundles the whole thing into one series
![image](https://github.com/Kareadita/Kavita/assets/24914093/c04f57d0-7a11-41ba-8924-58c728c82ba9)

So there are multiple number 1 issues 
![image](https://github.com/Kareadita/Kavita/assets/24914093/398b21cb-e52a-4a14-9204-40efc536ca08)

**Expected behavior**
I would expect (if I understand the docs correct), each folder represents it's own series.

**Comment by scare376** [comment]
So it looks like you don't have metadata so it's pulling from filename. Or it does have metadata and they all have the series name ghost rider. If there's no metadata then Kavita ignores anything between parentheses in the filename. If there is metadata then you need to edit the series name to distinguish the different series

**Comment by marcdieters** [comment]
Thanks for your quick answer !

Ah I see, that makes sense. On the other side, editing all these files is way too much work to make a reader app working.
Too bad.

Why is there no option to just browse the folders (in addition to the current method).

**Comment by majora2007** [comment]
Ubooquity is a program which offers a simple folder view. I would recommend using that.

**Comment by marcdieters** [comment]
Right. But Kavita looks much nicer. And Ubooquity  is Java, and I hate Java  😆 
And it hasn't gotten an update in 5 years....

Thanks for the quick answers though
