### ISSUE TITLE
Base Url setting doesn't override the base url

### ISSUE THREAD

**Issue by yiatz** [Kareadita/Kavita#2006]
As far as I can tell this setting really sets a base route, not a base url like the description implies. This also makes sense when the error message says "Must start and end with /" (this error also always shows even when you do start/end with a slash). This means that urls generated end up being something like "http://{local ip address}:{port}/{Base Url Setting}/registration/confirm-email" when I'd expect it to be "http://{Base Url Setting}/registration/confirm-email" with the setting having a default value of "{local ip address}:{port}" for what's setup on the listener.

Without this I don't see a way to override the ipaddress:port with a custom domain.

**Comment by scare376** [comment]
You don't understand what a base url is for then. If you want a custom domain use a reverse proxy. A base url is essentially used to allow multiple webapps to use the same domain without a subdomain.

**Comment by yiatz** [comment]
quick search for "base url definition" on google shows that "http://{Base Url Setting}" from my above example would be the base url and "/registration/confirm-email" would be the relative url.

even if that isn't the definition being used, there's no setting to set a custom domain in the application to use for generated urls like the registration email and link.

**Comment by scare376** [comment]
Its the terminology use for basically every self hosted web app. It means the base url for the app itself where everything else will be built off of. The domain is omitted because it's already known info. For the email generated links you're looking for the host name setting on the email settings page.

**Comment by yiatz** [comment]
I don't agree with your point on the base url, but I do appreciate you pointing out where that setting can be found. I hadn't looked in the email settings as it seems like that would be used in more places.

It looks like there's no mention of this setting in the wiki yet. A mention there could help people find this setting as well.
