### ISSUE TITLE
Can’t change settings in admin dashboard

### ISSUE THREAD

**Issue by MagicSG1** [Kareadita/Kavita#2012]
Can’t change settings in admin dashboard e.g folder watching. 

Running latest stable UNraid build and Kavita container in docker. Have attached picture of error 
![D6BADFB7-670C-4993-9ACA-328B98CBEB80](https://github.com/Kareadita/Kavita/assets/61438516/cd9f8fc4-82f6-423d-a44d-9b24497fd94f)

**Comment by majora2007** [comment]
This is a duplicate of https://github.com/Kareadita/Kavita/issues/1966
