### ISSUE TITLE
Forbidden MIME type ("text/html")

### ISSUE THREAD

**Issue by davidbono** [Kareadita/Kavita#2021]
I generate this error after a fresh install of Kavita using the container  "kizaing/kavita" with docker -compose.

I get several errors :

"Le chargement du module à l’adresse « https://XXXXXX/runtime.765c8dfc23e9d91f.js » a été bloqué en raison d’un type MIME interdit (« text/html »)." 

"Le chargement du module à l’adresse « https://XXXXXX/main.73155fb2918e6af4.js » a été bloqué en raison d’un type MIME interdit (« text/html »)."

Le chargement du module à l’adresse « https://XXXXXX//vendor.526eac3b2a23f5d5.js » a été bloqué en raison d’un type MIME interdit (« text/html »).

La feuille de style https://XXXXXX/styles.1b8935b274329a16.css n’a pas été chargée car son type MIME, « text/html », n’est pas « text/css ».

Le chargement du module à l’adresse « https://XXXXXX/polyfills.44b31e73bf2d577c.js » a été bloqué en raison d’un type MIME interdit (« text/html »).

**Loading of module was blocked due to forbidden MIME type ("text/html")**

**Comment by majora2007** [comment]
Please state the Kavita version and how I can reproduce? This seems like files are failing to load and may be blocked or scrambled by your network or reverse proxy.

**Comment by davidbono** [comment]
Thanks for this little look.

Kavita version is the one related to docker image 0.7.2.23 

https://hub.docker.com/layers/kizaing/kavita/nightly-0.7.2.23/images/sha256-030ec92b927c9a5496638ba353c1414dbcf315b8578aafdeea08ce803aea17c5?context=explore

service is exposed behind a nginx proxy :
        location ^~ /kavita {
        proxy_pass         http://127.0.0.1:5000;
        include                proxy_params;
        }

**Comment by majora2007** [comment]
What browser are you using? Are you seeing this when loading Kavita locally via localhost:5000?

**Comment by davidbono** [comment]
Firefox 113.0.2 (64 bits)
