### ISSUE TITLE
Migration from Calibre-Web to Kavita

### ISSUE THREAD

**Issue by Surgical71** [Kareadita/Kavita#2023]
**Describe the bug**
Meta Data issues

**To Reproduce**
Moved folder structure of Volumes of Calibre-Web within Linux to Kavita.
Kavita does pick up/read the comic books and the Cover images, but the meta data does not import/pick up.

**Expected behavior**
A sort of Migration tool or Guide

**Desktop (please complete the following information):**
 - OS: Docker

**Additional context**
I understand maybe this wont work by just moving the files over, but All the Meta Data and everything was already setup in Calibre-Web so any form of help or Guide on how to Migrate would be nice.

**Comment by majora2007** [comment]
Please see our wiki. Calibre does not write metadata into the epubs by default and Kavita expects that. We have a guide to configure Calibre to do this by default.

**Comment by therobbiedavis** [comment]
If they are .epub file format, then the metadata (OPF) needs to be embedded. https://wiki.kavitareader.com/en/guides/managing-your-files/metadata#ebooks

For .cb* file format Kavita expects a comicinfo.xml file inside the archive. https://wiki.kavitareader.com/en/guides/managing-your-files/metadata#comics-and-manga

Calibre does not write comicinfo.xml (maybe through a plug-in), so you would need a separate third-party program like Manga-manager, comictagger, or comicrack.

**Comment by roederorm** [comment]
> If they are .epub file format, then the metadata (OPF) needs to be embedded. https://wiki.kavitareader.com/en/guides/managing-your-files/metadata#ebooks
> 
> For .cb* file format Kavita expects a comicinfo.xml file inside the archive. https://wiki.kavitareader.com/en/guides/managing-your-files/metadata#comics-and-manga
> 
> Calibre does not write comicinfo.xml (maybe through a plug-in), so you would need a separate third-party program like Manga-manager, comictagger, or comicrack.
> 
> 

For ppl. finding this result while searching for information to migrate, there is a very stable plugin.

https://github.com/dickloraine/EmbedComicMetadata
