### ISSUE TITLE
Auto-Collections do not combine all series with the same metadata tag

### ISSUE THREAD

**Issue by KittyTheS** [Kareadita/Kavita#2024]
Collections auto-generated from the 'series group' metadata tag sometimes, but not always, do not contain all the series with that tag. For instance, the Avengers collection is missing 26 titles, including 'Avengers' and 'The Avengers', whereas X-Men is missing nearly a hundred series.  The missing series don't have a problem showing up in the library and can still be added to the collection manually but will not be automatically added no matter how many times they are rescanned. 

I am not sure how to reproduce the issue because I am unable to find any point of commonality between the missing series, other than that it does not appear to affect any new series groups added to the library after the auto-collection feature was implemented (but any series that had any part of it already in the library can be affected).

All the files being affected are in .cbz format with embedded metadata (and I've checked to confirm that they only have one ComicInfo.xml file, and that it contains the proper series group tag).

**Desktop (please complete the following information):**
 - OS: Windows (running as service)
 - Browser: Chrome, Edge
 - Version: 0.7.2.0

**Comment by majora2007** [comment]
Just to validate, you have let's say 20 series all with the SeriesGroup tag of "FooBar" and from a force scan, you aren't getting all 20 added to the collection? 

Are these series all in the same library or different libraries and are all libraries having "manga collections" on?

**Comment by KittyTheS** [comment]
Correct. The omission doesn't seem to follow any pattern either. For instance, the Murderworld collection (which should have five single-issue titles) has only three, one from six months ago, one from three months ago, and one from two months ago, and is missing the 5- and 4-month titles.

Everything is in the same library and the collections option is on.

**Comment by dgparryuk** [comment]
I've also had some issues with this, 

it didn't create "Series Group" "28 Days Later" at all, which contained "28 Days Later" and "28 Days Later: The Aftermath"
"30 days of night" only added 9 out of 15 series with that tag
"300" didn't add "300" but added "Xerxes: The Fall of the House of Darius and the Rise of Alexander"

**Comment by majora2007** [comment]
I am using the following to reproduce:
```
<?xml version='1.0' encoding='utf-8'?>
<ComicInfo>
  <SeriesGroup>ManySeriesShouldGroup</SeriesGroup>
</ComicInfo>
```

All series will have the following ComicInfo to validate that the grouping should occur. I will tag multiple series then perform a force scan to ensure that scanner optimizations don't skip processing any files. 

Expectation is all series show up in the group.

**Comment by majora2007** [comment]
It's working for me. Can you validate that you have the first chapter/volume tagged with the group or are they random issues in your series? 

Like all metadata that affects the Series in Kavita, Kavita will look at the first appropriate issue (issue 1, else volume 1) and consume that into the series level metadata. The only case that failed to get included in my test is when i tagged an arbitrary issue (issue 22) and hence the metadata wasn't included in calculations.

**Comment by dgparryuk** [comment]
HI, i checked a few of the ones that i knew weren't working and it appears to be as you suggested, so i'm checking all the .xmls and making sure they are there etc

**Comment by KittyTheS** [comment]
The first volume always has the tag, as do they all (I manually add the seriesgroup tag immediately after scraping metadata on a new file because my auto-renamer uses that tag to sort them into appropriate folders under the publisher - if they didn't have the tag, then they would be going into a publisher-level folder instead of the series group subfolder they're supposed to be in and would be overwriting the rest of the series every time a library scan is run, so since they show up in the library at all I can be 100% confident that all of the affected series are appropriately tagged).
    On Friday, June 2, 2023 at 06:31:32 a.m. MDT, Joe Milazzo ***@***.***> wrote:  
 
 


It's working for me. Can you validate that you have the first chapter/volume tagged with the group or are they random issues in your series?

Like all metadata that affects the Series in Kavita, Kavita will look at the first appropriate issue (issue 1, else volume 1) and consume that into the series level metadata. The only case that failed to get included in my test is when i tagged an arbitrary issue (issue 22) and hence the metadata wasn't included in calculations.

**Comment by majora2007** [comment]
@KittyTheS can you please attach one of the ComicInfo.xml from the first volume that is not being included in a collection?

**Comment by KittyTheS** [comment]
Do attachments actually go through when I reply via email? I can upload them properly if they didn't, sorry.

**Comment by majora2007** [comment]
They do not.

**Comment by majora2007** [comment]
I created a new folder called Black Panthers, took 2 cbrs and added your ComicInfo into each. I ended up with 2 series in a new collection. 

Your issue is likely due to scan optimizations. Please do a force scan.
