### ISSUE TITLE
v0.7.2 breaks support for macOS < 12

### ISSUE THREAD

**Issue by muneebmahmed** [Kareadita/Kavita#2026]
Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
Updating from v0.7.1.4 to v0.7.2 is not possible on macOS versions prior to Monterey. I encountered this error on macOS 10.14
<details>
<summary>Error log</summary>
<pre>
[Kavita] [2023-05-31 22:13:59.617 -07:00  1] [Fatal]  Host terminated unexpectedly
System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: Unable to load shared library 'e_sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable:
dlopen(/Users/muneeb/Downloads/kavita/New/Kavita/e_sqlite3.dylib, 1): image not found
dlopen(e_sqlite3.dylib, 1): image not found
dlopen(/Users/muneeb/Downloads/kavita/New/Kavita/libe_sqlite3.dylib, 1): no suitable image found.  Did find:
	/Users/muneeb/Downloads/kavita/New/Kavita/libe_sqlite3.dylib: cannot load 'libe_sqlite3.dylib' (load command 0x80000034 is unknown)
	/Users/muneeb/Downloads/kavita/New/Kavita/libe_sqlite3.dylib: cannot load 'libe_sqlite3.dylib' (load command 0x80000034 is unknown)
dlopen(/Users/muneeb/Downloads/kavita/New/Kavita/libe_sqlite3.dylib, 1): no suitable image found.  Did find:
	/Users/muneeb/Downloads/kavita/New/Kavita/libe_sqlite3.dylib: cannot load 'libe_sqlite3.dylib' (load command 0x80000034 is unknown)
	/Users/muneeb/Downloads/kavita/New/Kavita/libe_sqlite3.dylib: stat() failed with errno=126
dlopen(libe_sqlite3.dylib, 1): no suitable image found.  Did find:
	libe_sqlite3.dylib: cannot load 'libe_sqlite3.dylib' (load command 0x80000034 is unknown)
	libe_sqlite3.dylib: stat() failed with errno=126
	/Users/muneeb/Downloads/kavita/New/Kavita/libe_sqlite3.dylib: cannot load 'libe_sqlite3.dylib' (load command 0x80000034 is unknown)
dlopen(/Users/muneeb/Downloads/kavita/New/Kavita/e_sqlite3, 1): image not found
dlopen(e_sqlite3, 1): image not found
dlopen(/Users/muneeb/Downloads/kavita/New/Kavita/libe_sqlite3, 1): image not found
dlopen(libe_sqlite3, 1): image not found
</pre>
</details>

It's entirely due to the file `libe_sqlite3.dylib`, which sets the minos version too high:
```
$ otool -l libe_sqlite3.dylib | grep LC_BUILD_VERSION -A4
       cmd LC_BUILD_VERSION
   cmdsize 32
  platform 1
       sdk 12.3
     minos 12.0
```
And these are the details for the dylib included in v0.7.1.4:
```
$ otool -l libe_sqlite3.dylib | grep LC_BUILD_VERSION -A4
       cmd LC_BUILD_VERSION
   cmdsize 32
  platform 1
       sdk 11.1
     minos 10.15
```

It's worth noting that the `Kavita` binary itself still sets minos to 10.14, and just copying the old `libe_sqlite3.dylib` into the new directory allows Kavita to launch successfully.

**To Reproduce**
1. Use a macOS version < 12
2. `chmod +x Kavita`
3. `./Kavita`

**Expected behavior**
`libe_sqlite3.dylib` should have been loaded

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Browser: any
 - Version: 0.7.2

**Additional context**
Dotnet 7 [officially supports](https://learn.microsoft.com/en-us/dotnet/core/install/macos) macOS back to 10.15, and it seems to [run on 10.14 as well](https://formulae.brew.sh/cask/dotnet).
It looks like this error could be due to updating the toolchain on whatever host is used to compile the release binaries without setting variables for backwards compatibility. An environment variable like `MACOSX_DEPLOYMENT_TARGET` likely needs to be set to `10.14` when compiling `libe_sqlite3.dylib`

**Comment by majora2007** [comment]
Hmm...this is interesting but I'm not sure if this is something we can fix per-se. We just use dotnet build and dotnet publish to build the app. It seems like the .NET team might need to be made aware that a dependency isn't being packed.

**Comment by AbandonedCart** [comment]
.Net 8 set the minimum to 10.15, so at this point it may be best to have a note on https://wiki.kavitareader.com/en/install/macos (clicking the submit a PR button is also a 404).

In case you are wondering, 10.14 marked the end of 32 bit support, which is why it seems oddly popular.

**Comment by majora2007** [comment]
@DieselTech would you mind updating the wikis for me?
