### ISSUE TITLE
New library advanced settings not saved

### ISSUE THREAD

**Issue by pssandhu** [Kareadita/Kavita#2029]
**Describe the bug**
When making a new library the advanced settings are not saved.

**To Reproduce**
1. Go to the admin dashboard and click Add library
2. Follow the steps for creating a new library and change the advanced settings
3. Press save
4. Edit the library or browse kavita and see that the settings weren't saved

**Expected behavior**
Settings should be saved and used immediately

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Version: 0.7.2

**Comment by majora2007** [comment]
I can't reproduce this. What settings are you changing?

**Comment by pssandhu** [comment]
I'm getting this issue when I change one or more of the following before saving the new library:
- Manage Collections
- Manage Reading Lists
- Folder Watching
- Include in Dashboard
- Include in Recommended
- Include in Search

They're all enabled by default. For each of them, I tested creating a new library with just that one setting disabled and it never saves.

I can change them after the library is already created and it works fine
