### ISSUE TITLE
Reading list dates displayed incorrectly

### ISSUE THREAD

**Issue by pssandhu** [Kareadita/Kavita#2031]
**Describe the bug**
Reading list dates are displayed incorrectly. The starting month is always shown as "Jan" and the month format is inconsistent.

**To Reproduce**
1. Create a reading list
2. Make sure the list has dates. I'm using starting 5-2001 and ending 12-2012
3. See the the date is displayed as "Jan, 2001 — 12, 2012"

**Expected behavior**
The correct dates should be shown with consistent formatting, e.g. "May, 2001 — Dec, 2012"

**Desktop:**
 - OS: Docker
 - Browser: Firefox
 - Version: 0.7.2

**Comment by majora2007** [comment]
You are not using the correct date format. 

I support: 2015-01-25 (which is standard for Epubs) and the dates from ComicInfo (Year, Month, Day tags).

**Comment by pssandhu** [comment]
These dates can be entered manually by editing the reading list and entering the months and years:
![image](https://github.com/Kareadita/Kavita/assets/11130930/cb5dfebe-abeb-4819-840c-dc618508180c)

The result:
![image](https://github.com/Kareadita/Kavita/assets/11130930/c815df20-4121-42a5-9780-1cad93b677da)

Reproduced on the kavita demo server by editing the list dates:
![image](https://github.com/Kareadita/Kavita/assets/11130930/8d8d99f3-cf4c-46cd-bfb1-f346b95722c8)

This also happens when the list gets its dates from the items it contains which have metadata with the correct date information as you've described.

**Comment by pssandhu** [comment]
Just to clarify, this bug has two parts:
- The starting month is always displayed as January even if the underlying data says a different month
- The end month has inconsistent formatting

**Comment by majora2007** [comment]
Would you mind creating another issue and link to this one for the first issue?

I'm going to release the software, so the first part of the issue won't be able to make it in. I'll take care of it in the next release.
