### ISSUE TITLE
Questionable password policy

### ISSUE THREAD

**Issue by whalehub** [Kareadita/Kavita#204]
I checked the SQLite database that Kavita generated and saw that passwords are stored as hashes, so I don't understand why the password length is limited to a maximum of 16 characters during sign-up. The hash will be the same length regardless of how long the password is. If there has to be a limit at all, perhaps 100 characters would be more suitable.

**Comment by majora2007** [comment]
Hi Whalehub, Yes the passwords are hashed and salted. The limit just arbitrary when I started the project, I can def bump it up. I've never heard of a 100 character password, but how about max of 32 characters? 32 characters with symbols and alphanumerics would take years and years to crack the password.

**Comment by majora2007** [comment]
Sounds good, I will slate this for the next release.
