### ISSUE TITLE
Logins broken with 0.7.3

### ISSUE THREAD

**Issue by CountMurphy** [Kareadita/Kavita#2042]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
After updating, entering the correct credentials on the login page generates this error:

```
IDX10720: Unable to create KeyedHashAlgorithm for algorithm 'http://www.w3.org/2001/04/xmldsig-more#hmac-sha512', the key size must be greater than: '512' bits, key has '224' bits. (Parameter 'keyBytes') 
```

**To Reproduce**
1. start the kavita service after upgrading
2. Attempt to login

**Expected behavior**
Application logs in

**Screenshots**
![Screenshot_20230607_102730](https://github.com/Kareadita/Kavita/assets/2205997/e081298c-dd63-4f01-8b76-fa21bf4bc6a0)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 114.0-1

**Smartphone (please complete the following information):**
NA

**Additional context**
Downgrading to 0.7.2 fixes the problem

**Comment by CountMurphy** [comment]
I see that the update has the following changes:


```
Changed: Updated initial install default keys to be 256 bits for the encryption. You may be logged out and have to reauthenticate or change your token key to "super secret unguessable key" and restart (which will allow Kavita to regenerate the key for you)
```

but it is unclear how to regenerate my keys if I can't log in

**Comment by majora2007** [comment]
You need to change the key to what was noted in the release notes: "super secret unguessable key" and restart. Kavita will then re-generate the key correctly for you.

**Comment by majora2007** [comment]
This is in the appsetting.json under config/

**Comment by CountMurphy** [comment]
I figured out the problem. This was my fault (surprise surprise). So I created an arch linux package for kavita. The package symlinks appsetting.json to /etc/Kavita/appsetting.json and creates a seperate kavita user. The new user did not have write permission to the config. I'll have to update my package to fix it. Thank you for helping me troubleshoot!

**Comment by CountMurphy** [comment]
I am the author of the AUR package. Arch packages do not auto restart after updating by default. Just to double check, I verified this with the mariadb, apache, and networkmanager packages. Unless I see the mainline repos doing it, I'm hesitant to make that change.
