### ISSUE TITLE
Unable to open some Epubs on v0.7.3

### ISSUE THREAD

**Issue by xxshade** [Kareadita/Kavita#2043]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
Trying to open a epub results in a message 'Incorrect EPUB 3 navigation document: target for anchor href "#" not found in EPUB manifest.'. Not all ePubs are affected, noticed that it happens with some prepubs from jnovel (Ascendance of a Bookworm Part 05 Volume 05 PREPUB [5/8])

**To Reproduce**
1. Go to library with books
2. Select the book and click continue

**Expected behavior**
Book opens and can continue reading

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/30564479/0a7131e3-6e7c-49ca-b841-6bf903d1377c)

**Desktop (please complete the following information):**
 - OS: Docker latest
 - Browser vivaldi
 - Version 6.0.2979.22 (Stable channel) stable (64-bit) 

**Smartphone (please complete the following information):**
 - Device: zenphone 8 flip
 - OS: android 13
 - Browser Kiwi Browser
 - Version latest

**Additional context**
On version 0.7.2 this problem didn't occur

**Comment by majora2007** [comment]
This is likely to bugfixes in adding Epub 3.3 support. There were a few cases where inproper metadata in the epub wouldn't throw an exception, while now they do. 

I would first try to run it through Sigil and see if it can fix the issues, else send me a copy via a DM on discord and I can look into it.

**Comment by xxshade** [comment]
Running through Sigil fix the issue. Thanks!
