### ISSUE TITLE
Unsorted directory list when choosing library directory

### ISSUE THREAD

**Issue by svtkachenko** [Kareadita/Kavita#2045]
**Describe the bug**
When adding library directory filesystem content is unsorted and there is no way to sort it in UI.
It makes it really hard to navigate in big collections or if Library is nested deep down in FS structure.
I'm getting same output order (see screenshots) on Linux server if I use `ls -U`:
```
$ ls --help | grep "\-U"
-U                         do not sort; list entries in directory order
```

**To Reproduce**
1. Go to 'Server Setttings'
1. Go to 'Libraries'
1. Click on 'Add Library'
1. Fill any name and select any type
1. Click 'Next'
1. Click 'Browse for Media Folders'
4. See unsorted list of directories

**Expected behavior**
Alphabetically sorted list of directories or means of sorting it in UI manually.

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/2845814/6d64586d-9de0-434c-a3de-25161669ca00)
![image](https://github.com/Kareadita/Kavita/assets/2845814/d346c639-a99c-4e7f-b6ba-d7445176c381)

**Desktop (please complete the following information):**
 - OS: docker
 - Browser chrome, firefox
 - Version 114, 113

**Comment by majora2007** [comment]
Couldn't you just use the filter which autocompletes as you type?

**Comment by svtkachenko** [comment]
I guess it is possible. Though experience with it not so smooth:
1. I prefer visual list representation rather then typing whole path from the top of my head and autocomplete suggestion is in the same weird order.
2. It spams 400 errors during typing until full name of the directory is entered.

**Comment by majora2007** [comment]
Can you send me the error that you are receiving? What OS are you on? Via Docker?

**Comment by svtkachenko** [comment]
Server is in docker, yes. Client: Windows, Chrome 114.0.5735.110 if it matters.
Let's say I start typing in filter and I want to have `/media`:
1. Type `/` -- all is good, autocmplete is loaded and suggests `/etc`, `/tmp` and so on.
2. Type `m` -- 400
3. Repeat for letters e, d, i
4. Type `a` -- all is good, autocomplete is loaded and sugegsts folders inside `/media/`
Error:
```
GET https://192.168.1.1/api/library/list?path=%2Fm 400
{
    "headers": {
        "normalizedNames": {},
        "lazyUpdate": null
    },
    "status": 400,
    "statusText": "OK",
    "url": "https://192.168.1.1/api/library/list?path=%2Fm",
    "ok": false,
    "name": "HttpErrorResponse",
    "message": "Http failure response for https://192.168.1.1/api/library/list?path=%2Fm: 400 OK",
    "error": "This is not a valid path"
}
message-hub.service.ts:186 ERROR TypeError: Cannot read properties of null (reading 'hasOwnProperty')
    at Object.next (manage-library.component.ts:57:65)
    at Xe.next (Subscriber.js:91:33)
    at q._next (Subscriber.js:60:26)
    at q.next (Subscriber.js:31:18)
    at distinctUntilChanged.js:14:28
    at oe._next (OperatorSubscriber.js:13:21)
    at oe.next (Subscriber.js:31:18)
    at filter.js:6:128
    at oe._next (OperatorSubscriber.js:13:21)
    at oe.next (Subscriber.js:31:18)
```

**Comment by majora2007** [comment]
Thanks, I'll take a look.

**Comment by majora2007** [comment]
For the unsorted directory, this must be something at OS, because on my machine, everything is sorted correctly. I ended up just adding custom sorting on Kavita's side.
