### ISSUE TITLE
Covers Undefined Error

### ISSUE THREAD

**Issue by Ark1369** [Kareadita/Kavita#2047]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
Upon accessing the application for first time after starting Kavita.exe the library covers are all changed to Undefined Cover Icon but are shown properly on Refreshing/Hard Refreshing the page (Tho Covers take a second or so to load/regenerate?)

**To Reproduce**
1. Start Kavita.exe
2. Open the Kavita URL in Browser and login
3. See error

**Expected behavior**
Seeing proper covers that are already set without lag.

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/123398211/08b9ddce-2532-44a9-a88c-fa071f4367ee)

**Desktop (please complete the following information):**
 - OS: Windows running through CMD
 - Browser Firefox 113
 - Version 0.7.3

**Comment by majora2007** [comment]
Please give system info like your OS. 

Is this an upgraded server or fresh install? Does this happen in incognito?

**Comment by Ark1369** [comment]
Windows 11 Home
Upgrade from 0.7.1 to 0.7.3
Did not happen in Incognito (But it also didnt happen in Normal browser this time, so I cant confirm Validity of it)
So far this "undefined" has occured on 5~ instances since upgrade, but at times it has worked proper (like just now).

**Comment by Ark1369** [comment]
> This sounds like a cache issue where the browser might have old UI code and isn't sending over the api key for your user. In v0.7.2, all image apis were updated to include authentication to ensure no data leaked to other users.
> 
> Hence why Incognito is working. You can delete your wwwroot and replace with a new one from the v0.7.3 update. That should ensure no leftover files are getting loaded by the browser. Or you can clear cache on the browser.
> 
> Let me know.

Sorry for delay and replacing WWWroot folder fixed it. Thanks
