### ISSUE TITLE
Paper theme styling issues

### ISSUE THREAD

**Issue by gmahomarf** [Kareadita/Kavita#2049]
First off, thank you soooo much for the Paper theme! I was about to start working on a sepia-ish theme myself, but I'm glad I don't have to anymore. 

**Describe the bug**
Styling of `<kbd>` tags in the paper theme result in black text on black background

**To Reproduce**
1. Open any epub with text in between  `<kbd>` tags
2. Locate said text
3. Set theme to paper

**Expected behavior**
Text should be readable. 

**Screenshots**
<details><summary>Screenshots</summary>
<p>

![Screenshot_20230609-105920~2](https://github.com/Kareadita/Kavita/assets/137055/facecd2d-f557-4a01-8993-e93d761931fc)

</p>
</details> 

**Desktop (please complete the following information):**
 - OS: Debian (server) and macOS (client) 
 - Browser: Chromium and Firefox
 - Version: 0.7.3.0

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 12
 - Browser: Brave and Firefox
 - Version: 0.7.3.0

**Additional context**
The selected text in the screenshot is a `<kbd>` element with class `calibre24`

<details><summary>Extra screenshots and snippet</summary>
<p>

#### HTML snippet
```html
<li class="calibre18">
  You can introduce a new method such as <kbd class="calibre24">IsAccessLevelCheckRequired()</kbd> in <kbd
    class="calibre24">AuditManager</kbd>. The application service would call this method before <kbd
    class="calibre24">AddRecord()</kbd>, and if it returned <kbd class="calibre24">true</kbd>, the service would get the
  access level from the database and pass it to <kbd class="calibre24">AddRecord()</kbd>.
</li>
```

#### Screenshot of computed style
<img width="392" alt="image" src="https://github.com/Kareadita/Kavita/assets/137055/cfd8efe0-5af4-4b30-b94a-92055391b89d">

<img width="631" alt="image" src="https://github.com/Kareadita/Kavita/assets/137055/557ec111-b972-4602-9f01-709b19b1f722">

#### Screenshots in other themes

Black: 
<img width="532" alt="image" src="https://github.com/Kareadita/Kavita/assets/137055/2c738cef-3ff6-40bc-bd22-84eaa33fa8d7">

Dark:
<img width="532" alt="image" src="https://github.com/Kareadita/Kavita/assets/137055/62bc237e-4391-48f5-8955-357a41dbdc5a">

White:
<img width="533" alt="image" src="https://github.com/Kareadita/Kavita/assets/137055/9fc71994-03d1-45eb-919d-0ccd41483603">

</p></details>

**Comment by majora2007** [comment]
This looks like it may be styling baked into your epub. I can validate on another book, but kavita might need to override the stylings.

**Comment by gmahomarf** [comment]
So, I think I found the cause. It's [this commented style](https://github.com/Kareadita/Kavita/blob/develop/UI/Web/src/app/book-reader/_models/book-paper-theme.ts#L119). I don't know, however, if just uncommenting it is enough, since I see that the color is a darker shade (it matches the color of the nav bar) than the [color of the reader background](https://github.com/Kareadita/Kavita/blob/develop/UI/Web/src/app/book-reader/_models/book-paper-theme.ts#L95). Given that for all other themes both those values match, I'll leave it to you to decide which option is best.

I rebuilt my local Kavita instance after uncommenting and setting the color to match the current BG, and this is the result: 
<img width="533" alt="image" src="https://github.com/Kareadita/Kavita/assets/137055/9ddde2bc-9745-4c51-abff-93758aa7dd66">

**Comment by majora2007** [comment]
I'll take a look and adjust, thanks for the RCA.
