### ISSUE TITLE
After update, my credentials no longer allow me to log in. If I revert to a different version it works. Error below.

### ISSUE THREAD

**Issue by lsultana98** [Kareadita/Kavita#2051]
If I could get a hand with the below, that would be great. Thank you.

IDX10720: Unable to create KeyedHashAlgorithm for algorithm 'http://www.w3.org/2001/04/xmldsig-more#hmac-sha512', the key size must be greater than: '512' bits, key has '128' bits. (Parameter 'keyBytes')

**Comment by majora2007** [comment]
https://github.com/Kareadita/Kavita/issues/2042

Also covered in the changelog for the release
