### ISSUE TITLE
After renaming folders/files and scan, old folders/files are still visible

### ISSUE THREAD

**Issue by Maitresinh** [Kareadita/Kavita#2062]
Everything is in the title.

When i make changes on the files folder (renaming....), and i scan, the old previous folders/files (now dead) are still visibile.
As the scan don't clean up the database, ii have to deleted manually the dead folders.

Is there a way to clean up the database ? Or am i doing something wrong ?

**Comment by majora2007** [comment]
Can you give me step by step reproduction? I don't know what scan means.

**Comment by Maitresinh** [comment]
Thanks for your answer.

1/ I change the names of the files in the folder
2/ I make a "scan libarry" in the corresoonding liibrary.
3/ Kavita (on a PI3B+) freeze. I have to reboot. The older folder are still here when i reboot.

**Comment by Maitresinh** [comment]
I have the logs, if needed

**Comment by majora2007** [comment]
Attach the logs. If Kavita is freezing it implies the scan didn't finish, meaning that it didn't do anything and hence you're seeing stale data. Scan has to complete for updated state.

**Comment by Maitresinh** [comment]
here they are.
(by the way, i t just freeze again, and i did not launch any scan folder - but added files)

[kavita20230611.log](https://github.com/Kareadita/Kavita/files/11715591/kavita20230611.log)

**Comment by majora2007** [comment]
Please comment with your system information. How much RAM do you have, are you using docker, etc.

**Comment by Maitresinh** [comment]
Raspberry PI3B+ (i think 1Go)
Installed directly on debian (no docker)
nothing more running on the pI

**Comment by majora2007** [comment]
Do me a favor, clear out your logs, remove a file, then scan, once scan is complete, try to open the pdf, then send me the logs.

I can't tell how many files you have, but 1GB of RAM is pretty small, esp when running on a low power machine. It depends on how many files you have in a single library. If a few thousand, it shouldn't be crashing (although how rich of metadata will vary usage)

**Comment by Maitresinh** [comment]
Thanks.

How do i clean the logs ? I could not find that in the ad hoc and recurring tasks.
By the way, if i wait a long time (all the night) the scan seems to work, and the freeze disapear.

**Comment by majora2007** [comment]
You clear the log by deleting the file in config/logs. What it sounds like is you weren't allowing the scan to complete and killing the app before it could finish. Likely it's eating up lots of resources on your constrained system.
