### ISSUE TITLE
[Feature Request] Shortcut to go to next/previous Chapter/Volume

### ISSUE THREAD

**Issue by RandomLegend** [Kareadita/Kavita#2063]
Hello,

i currently use Kavita on my PC and i'd love to have a shortcut that goes to the next chapter / volume

I am reading in webtoon mode and pressing any of the arrow keys makes the reader blackscreen with infinite loading for me. I currently use AntiMicroX to rebind a key to mouse wheel down so i don't have to use the mouse.

But everytime i am at the end of a chapter i have to press the "next chapter / volume" button with my mouse manually.
Would be awesome to have a shortcut for that that is not "next page" but specifically next chapter.

With best regards!

**Comment by majora2007** [comment]
Please reopen this on our feature request site: feats.kavitareader.com.
