### ISSUE TITLE
Web Links literally break apart if they contain commas.

### ISSUE THREAD

**Issue by Oniicode** [Kareadita/Kavita#2064]
**Describe the bug**
It's impossible to add a Web Link if it contains commas.

**To Reproduce**
1. Open any Manga
2. Click "Edit"
3. Go to "Web Links"
4. Try adding the following one: https://en.wikipedia.org/wiki/No_Matter_How_I_Look_at_It,_It%27s_You_Guys%27_Fault_I%27m_Not_Popular!

**Expected behavior**
The Link shouldn't fall apart into two seperate and unusable records.
(Side note: The link came from chrome's URL bar with the comma already innit like that. So i'd expect it to work as-is)

**Screenshots**
Before clicking save:
![Screenshot_3623](https://github.com/Kareadita/Kavita/assets/46069626/34eb3776-cf53-4955-9a24-4604ee17b710)

On the manga detail page after saving:
![Screenshot_3621](https://github.com/Kareadita/Kavita/assets/46069626/6fde691e-878a-4c0a-9462-5b1f5fa632a2)
![Screenshot_3622](https://github.com/Kareadita/Kavita/assets/46069626/fa8e4481-e25f-4777-a3df-c3f1c4274738)

Then after reopening the edit modal:
![Screenshot_3620](https://github.com/Kareadita/Kavita/assets/46069626/beff5d73-f0e7-4420-af91-8dc2e0bb08a3)

**Desktop:**
 - OS: Docker
 - Browser: Chrome 114.0.5735.110 (Official Build) (64-bit) (cohort: Stable)
 - Version: 0.7.3.1

I suspect there might even be some sort of injection vulnerability here.

**Comment by majora2007** [comment]
This will be released in v0.7.4.
