### ISSUE TITLE
Front-end displays OPDS URL incorrectly, if BaseUrl is configured using appsettings.json

### ISSUE THREAD

**Issue by Oniicode** [Kareadita/Kavita#2065]
**Describe the bug**
To use my kavita instance with my reverse proxy under a subdirectory, i configured the BaseUrl by editing the appsettings.json and restarting the docker container. Everything works fine, except for a minor front-end bug, where the OPDS URL is displayed incorrectly.
Specifically, the configured BaseUrl seems to get appended _twice_ instead of just once.

**To Reproduce**
1. Configure BaseUrl via appsettings.json in kavita data directory
2. Restart it's docker container
3. Click "Settings" in the dropdown with your user name top right corner
4. Go to "3rd Party Clients"
5. See contents of OPDS URL text box.

**Expected behavior**
Said text box should output something like:
`http://nas2/<your BaseUrl>/api/opds/5bXXdeXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX`
instead of 
`http://nas2/<your BaseUrl>/<your BaseUrl>/api/opds/5bXXdeXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX`

**Screenshots**
As described, it's being displayed incorrectly:
![Screenshot_3626](https://github.com/Kareadita/Kavita/assets/46069626/fd2eeea5-3c07-406d-a651-1f259b46c439)

**Desktop**
 - OS: Docker
 - Browser: Chrome 114.0.5735.110 (Official Build) (64-bit) (cohort: Stable)
 - Version: 0.7.3.1

**Additional context**
Additionally: observed in the admin dashboard, the front-end seems to display it correctly:
![Screenshot_3627](https://github.com/Kareadita/Kavita/assets/46069626/6d5a9e8f-e608-47cc-885e-accf2a9549c9)

**Comment by majora2007** [comment]
Does this only happen when you manually edit it via appsettings.json and not when you use the UI to configure it?

**Comment by Oniicode** [comment]
@majora2007 it happens both ways, using the UI and with just the config. just tested it in a seperate :latest container.
![Screenshot_3632](https://github.com/Kareadita/Kavita/assets/46069626/dc763fd9-0846-4c7b-a577-6025591056b2)

Also setting it via UI led to it being written in appsettings again.

And also, interestingly, after setting it in the UI it displayed it immediately and correctly, without the restart.
Only after restarting, it's displayed incorrect again.
