### ISSUE TITLE
So, is the email optional or required? Registration UI kind of contradicts itself.

### ISSUE THREAD

**Issue by Oniicode** [Kareadita/Kavita#2066]
**Describe the bug**
I'm not sure it can be really called a bug, but..
When starting the app container for the first time and registering, the UI says the email is optional.
But when actually treating it as optional and leaving the text box empty, it says "this field is required".
It kind of contradicts itself. 
(lol is this like a new next gen type of captcha, designed to fry a robot's brains using a paradox statement?)

**Expected behavior**
I'm not sure?

**Screenshots**
![Screenshot_3630](https://github.com/Kareadita/Kavita/assets/46069626/aada72e6-00f6-4ca6-8c97-851dc1e72461)

**Desktop:**
 - OS: Docker
 - Browser: Chrome 114.0.5735.110 (Official Build) (64-bit) (cohort: Stable)
 - Version: 0.7.3.1

**Comment by scare376** [comment]
The email field is required to be filled in but it does not need to be a valid email address.

**Comment by Oniicode** [comment]
That much i have figured out too so far. But wouldn't it make more sense for it to be actually optional then? Or maybe the phrasing of that tooltip should be different, removing the "this is optional"-part.

**Comment by majora2007** [comment]
It can't be optional, but I can tweak the wording to be more coherent.

**Comment by majora2007** [comment]
This will be released in v0.7.4.
