### ISSUE TITLE
Height image scaling causes image to shift upwards on tablet

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2069]
**Describe the bug**
Height image scaling in image reader causes the image to shift upwards causing the top of the image to get cut off.

**To Reproduce**
1. Open book that uses the image reader.
2. Set Image scaling to height
3. Image will be shifted upwards cutting off the top of the image

**Expected behavior**
Image fits flush with the screen height.

**Screenshots**
![Screenshot_20230613-062004](https://github.com/Kareadita/Kavita/assets/2068470/7f0b4452-67ad-420d-9ed6-53d2b6162d43)

**Desktop (please complete the following information):**
 - OS: Docker
 - Version 0.7.3.4

**Smartphone (please complete the following information):**
 - Device: Boox Nova Air C
 - OS: Android 11
 - Browser Chrome

**Additional context**
I've tried reproducing in other environments but have been unable to.

**Comment by majora2007** [comment]
I'm not able to reproduce on the latest nightly

**Comment by scare376** [comment]
I can still reproduce it on latest nightly. Like I said I can only reproduce it on here. Got a different condition when using the browser normally as opposed to accessing it through a home screen shortcut.
![Screenshot_20230701-071910](https://github.com/Kareadita/Kavita/assets/2068470/1b72c60f-60f4-4ee1-b220-57cfa1390f8d)
![Screenshot_20230701-072024](https://github.com/Kareadita/Kavita/assets/2068470/12631bc3-b0dc-4da4-ad8e-00672ac931e4)

**Comment by majora2007** [comment]
Can you change the background color of the reader to something besides black? It's hard to tell on the images what's happening

**Comment by scare376** [comment]
Oh the images are to show that it's set to height image scaling but there's a scroll bar and empty space above the image. There's some below the image as well. I can try to later but I'm in a car all day x.x

**Comment by majora2007** [comment]
When looking into this I did notice that some calculations I have for fit to height don't work across browsers. I need to remove the scrollbars height if there is a horizontal scroll but FF doesn't render the scroll while Chrome does.
