### ISSUE TITLE
Imprecise media type for the OPDS endpoints

### ISSUE THREAD

**Issue by mickael-menu** [Kareadita/Kavita#2070]
**Describe the bug**

The Kavita OPDS endpoints are sending an `application/xml` media type instead of the OPDS one in the `Content-Type` response header.

This created a problem in Aldiko, as it failed to identify Kavita as an OPDS feed.

**To Reproduce**
1. Start the server, with the OPDS setting enabled
2. Navigate to the OPDS URL, for example from Google Chrome
3. Notice the `Content-Type` response in the Web Inspector

<img width="573" alt="Screenshot 2023-06-13 at 17 44 02" src="https://github.com/Kareadita/Kavita/assets/58686775/ffcedaf8-22f4-49fd-a2b9-3c5e435d2457">

**Expected behavior**

Ideally, the `Content-Type` should contain the appropriate OPDS media type depending on the type of feed:

* for a navigation feed: `application/atom+xml;profile=opds-catalog;kind=navigation`
* for an acquisition feed: `application/atom+xml;profile=opds-catalog;kind=acquisition`

Alternatively, using the Atom feed media type `application/atom+xml` only might be enough.

**Desktop (please complete the following information)😘*
 - OS: macOS
 - Browser Chrome
 - Version 0.7.3.1

**Comment by majora2007** [comment]
I will need to see if Chunky and Panels can support this change before I implement it.

**Comment by majora2007** [comment]
This unfortunately breaks Chunky and Panels when using content type of `application/atom+xml`. The downloading function fails. I unfortunately cannot make this change and break compatibility with software the majority of my users use.
