### ISSUE TITLE
[EPUB Reader] Moving to next page doesn't lead to move to the top of the next page

### ISSUE THREAD

**Issue by Entmatix** [Kareadita/Kavita#2073]
**Describe the bug**
When I move to next page using right side of a page (click on it) it doesn't lead to move to the top of the next page. Most of the time view keeps the same as on previous page (like at the bottom if I ended up there on the previous page).

**To Reproduce**
1. Continue reading a book.
2. Scroll down to the bottom of the page you've just read.
3. Click on the right side of the page to move to the next page.

**Expected behavior**
Go to the top of the next page.

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Browser: firefox, brave
 - Version: 0.7.3.1 (kavita), 111.0.1 (firefox), 1.52.122 (brave).
 - Kavita from latest official docker image on debian 11 server with latest stable docker.

**Comment by majora2007** [comment]
You need to provide the reader settings

**Comment by majora2007** [comment]
Have you already been to that page before when you go next? Because the reader will always set your scroll position to where you were last, so if you've read that page before, went back, then forward, it would scroll you back down.

**Comment by Entmatix** [comment]
It happens to new pages (pages I've never read) as well.

**Comment by majora2007** [comment]
I just tested this again and I'm unable to reproduce. If you're still having this issue, can you send me the book you're having issue with and what page you're navigating from -> to. I'll test on that as my books are all working.

**Comment by superbloomie** [comment]
I have the same issue for any epub. If I’ve scrolled through a chapter then go to the next chapter it always starts at the equivalent spot. Or the end if the next chapter is shorter. It means for each new chapter I start in the middle/bottom and scroll to the top to start reading.

I’m reading on an iPhone and iPad in Safari, with Kavita hosted in an unraid docker. 

Kavita v0.7.6
Safari 16.1

![CA4DFAE7-C1E5-4E7A-8E18-A5CB4D68D97F](https://github.com/Kareadita/Kavita/assets/7771700/a4a26d17-9240-4f55-89d0-f7dd6a8f1eaf)

link to screen recording: https://youtube.com/shorts/8K6ckA06AJE
