### ISSUE TITLE
Cannot change cover image for some series

### ISSUE THREAD

**Issue by Jokey665** [Kareadita/Kavita#2074]
**Describe the bug**
On 0.7.3.1 (and on 0.7.3), most series do not let me update the cover. I can go through the motions and choose a cover, but it does not actually update the cover, even after waiting for hours. 

New cover does not appear in the "Cover Images" section after saving and re-opening the series properties. Happens in both book and comic libraries. Restarting Kavita does not resolve, nor does restarting the server.

It doesn't happen for every series, but the majority added since updating. 

**To Reproduce**
1. Go to a series
2. Click on pencil icon to edit
3. Click on "Cover Image"
4. Either choose a cover from the list, or upload a new cover
5. Click "Save"
6. Refresh/wait and see that the cover did not update

**Expected behavior**
Cover to update.

**Desktop (please complete the following information):**
 - OS: Server is Windows 10 Pro 22H2
 - Browser: Shows wrong cover in Firefox 113.0.2 and 114.0.1, haven't tried others.
 - Kavita Version 0.7.3.1, and also on 0.7.3 before I updated

**Comment by majora2007** [comment]
This indicates that your config directory does not have the proper write permissions. Where did you install Kavita? Do covers naturally generate?

**Comment by majora2007** [comment]
Please also clear your logs (config/logs), do the operation, then attach the logs. There is likely a backend error.

**Comment by Jokey665** [comment]
I did install Kavita in a weird place accidentally, "F:\Downloads\Kavita", but the user that it runs as has full permissions for that folder. Covers naturally generate as I would expect them to, just not always using the picture I would prefer. Attached is fresh log file. All I did was open Kavita, and try to change the cover of two series, one comic and one book.

[kavita20230614.log](https://github.com/Kareadita/Kavita/files/11746152/kavita20230614.log)

**Comment by majora2007** [comment]
`HTTP POST /api/upload/series responded 200 in 33.8922 ms`

This is showing that it was successful. Can you check in config/temp and see if there are any of the images you were trying to upload?

**Comment by Jokey665** [comment]
config/temp is empty
If I look in config/covers I see the images (in this instance I'm looking at series1186.png and series1211.png which are both present and the picture I want)
But they still do not show as covers in Kavita, and are not listed in the cover change interface for the series

**Comment by majora2007** [comment]
Oh that means Kavita did everything correctly. It may be aggressive caching from your browser. Kavita allows the browsers to cache the images for a few mins, hence why a popup shows saying it may take a few mins for images to reflect. Can you open another browser or incognito and see if the covers reflect?

**Comment by Jokey665** [comment]
Tried in Firefox incognito, and in Chrome which I've never used to go to my Kavita server before. Looks like 1211 has updated, but 1186 is still not showing the correct image.

**Comment by majora2007** [comment]
Can you re-do the 1186 series?
