### ISSUE TITLE
Kavita automatically generates poster.jpg and categorizes them into a separate series

### ISSUE THREAD

**Issue by hiikii** [Kareadita/Kavita#2075]
**Describe the bug**
Hi, I found out that Kavita will automatically generate poster.jpg for my Epub files in the same directory, and the images will be grouped into a new separate series on the next scan.

**To Reproduce**
1. Copy multiple epub files into a series folder (they are all Japanese ebooks)
2. Waiting for the images to be generated for each epub file, I don't know when they were there but I'm sure I didn't do it
3. Wait for kavita to scan automatically or I perform the scan manually
4. Now there are two series shown in my library, one is the epub series and the other is the image series

**Expected behavior**
There should only be one series in the library, or no poster.jpg should be generated.

**Screenshots**
Have manually removed redundant series, I can add pictures later if needed.

**Additional context**
Kavita's environment: Debian 11, the folder is mounted via rclone

I can provide epub files if needed, just to mention that my files are all in Japanese, but the generated posters are not from my files, they are all in English.

**Comment by majora2007** [comment]
You can use a .kavitaignore to ignore images from your library. Kavita supports image-based series as well, hence why this is happening. You can read up on .kavitaignore from our wiki, but a simple:

*.png
*.jpg
etc 

stored at the root of your library will suffice.

**Comment by majora2007** [comment]
As I mentioned, you have a loose image in your filesystem and Kavita saw it as it's own series. Some users have loose leaf images only (not archives or epubs) and Kavita supports that. 

We have ample documentation on our wiki that should explain how to best organize.
