### ISSUE TITLE
i cant see Kavita server from the Kindle

### ISSUE THREAD

**Issue by 9acca9** [Kareadita/Kavita#2076]
Kavita is working fine, but i want to know if it is possible go to the server through the web browser of the Kindle (paperwhite). I  set the e-ink theme to my user from the notebook browser, and is working, but when i try from the Kindle web browser i dont see nothing.
Thanks.

**Comment by majora2007** [comment]
No. Kindle's do not support modern javascript, so it's not useable. You will need to utilize Send to Device for a Kindle. Other eInk devices, like Boox do work fine with an eInk reader.
