### ISSUE TITLE
Send invitation to user dont work

### ISSUE THREAD

**Issue by 9acca9** [Kareadita/Kavita#2077]
Hi.
I can do this manually but want to know if it is possible to do it automatically.
The email server is working (i can send the books to my kindle and a test email to the email account).

My kavita server can be also be reached with my PUBLIC IP FROM OUTSIDE (internet), but, cant be reached from my own local network with the public ip. This is a router that dont like to call himself... (i dont know how is this call).
So, i can reach my server from my cellphone (4g) going to my ip public and port.
But, cant reach from my own network the ip public, just the local of course.
So, there is something i can do to tell kavita, put the appropriated url (ip public)? and send the email automatically?

**Comment by majora2007** [comment]
You need to setup a reverse proxy. You can use our wiki which has some config, but it's outside the scope of Kavita support. If you need more help, as you've opened a few issues, please join the discord and we can help you with all your questions. Thanks.
