### ISSUE TITLE
Adding new content to renamed series removes the series

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2078]
**Describe the bug**
If you change the title to a series in kavita and then add new content or change the current content to the series it removes the series from the library upon the next library scan

**To Reproduce**
1. Add a series to a library.
2. Change the title to the series.
3. Add or modify a file for that series.
4. Run a library scan.
5. Series with changed title should be removed.

**Expected behavior**
Series is not removed and content is added/modified successfully.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Opera GX
 - Version 0.7.3.6

**Additional context**
I was able to confirm the issue with a manga library, did not try it with a comic library, and tried to test with a novel library but had some issues with getting the scan to trigger consistently (i blame my smb setup being dumb for no reason).

**Comment by majora2007** [comment]
I'm not understanding the reproductions steps. Can you please add a concrete example?

**Comment by scare376** [comment]
https://github.com/Kareadita/Kavita/assets/2068470/3907ed4b-5142-4795-9842-596e6090e30f

**Comment by scare376** [comment]
That makes sense and I figured that was what was going on. I agree making the field read only is probably the way to go.

**Comment by majora2007** [comment]
This will be released in v0.7.4.
