### ISSUE TITLE
Change password requirements or disable auth?

### ISSUE THREAD

**Issue by strig** [Kareadita/Kavita#208]
Hey, I'm testing out this app and it seems really cool so far, great work 😄 
I run these kinds of things on my home network only, so I don't really need auth or users and so I usually just set admin:admin for everything. 
Would it be possible to configure the password requirements such that I don't need to include capitals/numbers? Alternatively, is there a way to just disable the auth and use a default user?

Cheers!

**Comment by strig** [comment]
Any particular reason why? A lot of other apps give you this option, sonarr/radarr for example.

**Comment by majora2007** [comment]
The architecture of Kavita is around having an admin user and non-admin users, so authentication must occur, roles have to be set etc. 

Given the workaround of having a browser save your password which will keep you authenticated and the offchance you have to re-log, it's nearly instant, I don't see the upside in putting in the added complexity. 

I have a feathub, if you get enough support, I will look at adding it. But for now, I would like to focus on the bigger features. 

https://feathub.com/Kareadita/Kavita
