### ISSUE TITLE
[EPUB] Small image size issues

### ISSUE THREAD

**Issue by avgnerd** [Kareadita/Kavita#2083]
**Describe the bug**
Chapter image files appear smaller when reading ebooks on mobile

**To Reproduce**
Reader settings
pagination on
1 colum mode

**Screenshots**
![Screenshot_20230619_092731_Firefox](https://github.com/Kareadita/Kavita/assets/2313860/215c2065-a61d-489d-a22b-345d04cf3b4b)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Galaxy S10+
 - OS: [e.g. iOS8.1] Android 12
 - Browser [e.g. stock browser, safari] Firefox
 - Version [e.g. 22] 114.1.1

**Comment by majora2007** [comment]
I need more information, as this looks to be expected. What is the base size of the image? What is the dimensions of the browser? What are the reading settings like margin?

**Comment by avgnerd** [comment]
Base size of the image : 1512 x 2220
Browser size : 414 x 785
Reading Setting
Font Size 100%
Line Height 100%
Margin 15%
Layout Mode 1 Column
Tap to Paginate On

**Comment by Hobogrammer** [comment]
I also have come across this bug. I believe the issue is with the layout mode. Images appear normal in scroll mode.

**Comment by majora2007** [comment]
This isn't a bug. On column mode, we try to prioritize aspect ratio and keep it within the column based on the size of the image. You have 15% margins, so there isn't much space for the image to start.
