### ISSUE TITLE
SIGILL (illegal instruction) for ARM64 binary

### ISSUE THREAD

**Issue by rahulmb** [Kareadita/Kavita#2084]
I'm running arch linux on ARM64 on an Odroid HC4. The latest update is giving me a sigill for arm64 . The binary does say it's compiled for aarch64. 
output of command 'file Kavita':
Kavita: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=10e9fc0262d4f73baf5638db12040547875538e3, stripped

**Comment by majora2007** [comment]
Kavita does not maintain the Arch Linux build. You can reach out to @CountMurphy who made the image.

**Comment by CountMurphy** [comment]
@rahulmb feel free to leave comments at https://aur.archlinux.org/packages/kavita-bin if you run into package issues. That said, the arm package is working on a fresh pi 3 I just tested with.

**Comment by majora2007** [comment]
@CountMurphy  if you're on discord, please send me a ping. I can get you hooked in for release testing on your package.

**Comment by CountMurphy** [comment]
ping sent
