### ISSUE TITLE
SIGILL error on ARM64 binary

### ISSUE THREAD

**Issue by rahulmb** [Kareadita/Kavita#2085]
I'm running aarch64 on Manjaro Linux on an Odroid HC4.

I've run both the github release and arch aur Kavita binaries and I'm getting the same sigill (illegal operation) error for both. I've also tried reinstalling. v0.7.1.4 arm64 and previous builds run fine. v0.7.2 also produced the sigill error. I've attached a strace.

[kavita_strace.txt](https://github.com/Kareadita/Kavita/files/11783875/kavita_strace.txt)

**Comment by scare376** [comment]
Joe responded to you on the last issue that you posted #2084 that he does not maintain the arch package. the person who maintains the arch package responded with a link. Report your issue there so that you can get support.

**Comment by rahulmb** [comment]
I did. He suggested testing the upstream binary to see if it was an upstream issue as well as strace. The upstream binary didn't work.

**Comment by majora2007** [comment]
Understand but please use his GitHub for your issue.

**Comment by CountMurphy** [comment]
I had him not use my package entirely and just download the latest release from the official source. My understanding (which admittedly could be flawed) is that kavita's database, config and everything it needs all live under the same parent directory where the release is unzipped/untar'd. I had rahulmb unzip the official github  release in a different location from where the arch package installs it to and try to run it and he got same error. All the work my packaging script does was bypassed so I don't think it was a packaging problem on my end.

**Comment by rahulmb** [comment]
Reposted for clarity:
I'm sure it's arm64. I'm copy-pasting commands I used when I tested. I tested with official binaries downloaded to a kavita folder in my home folder created with mkdir kavita. I used 'rm -r *' between each of the 4 tests below. the strace shows binary runs for a bit till it gets a SIGILL.

The 0.7.1.4 release worked fine no issues:
1. curl -OL https://github.com/Kareadita/Kavita/releases/download/v0.7.1.4/kavita-linux-arm64.tar.gz
2. tar xvzf kavita-linux-arm64.tar.gz 
3. chmod +x Kavita/Kavita
4. Kavita/Kavita

The 0.7.2 and all builds after result in SIGILL:
1.1 curl -OL https://github.com/Kareadita/Kavita/releases/download/v0.7.2/kavita-linux-arm64.tar.gz
1.2 curl -OL https://github.com/Kareadita/Kavita/releases/download/v0.7.3/kavita-linux-arm64.tar.gz
1.3 curl -OL https://github.com/Kareadita/Kavita/releases/download/v0.7.3.1/kavita-linux-arm64.tar.gz
2. tar xvzf kavita-linux-arm64.tar.gz
3. chmod +x Kavita/Kavita
4. Kavita/Kavita

**Comment by majora2007** [comment]
Can you cd into Kavita/ then do ./Kavita? 

Are you updating from an existing install or is this a fresh install?

**Comment by rahulmb** [comment]
I ran into the problem when updating. Systemctl kept trying to restart the service.
The tests are fresh installs.
I still get SIGILL when cd into Kavita with latest release.

**Comment by rahulmb** [comment]
I Just tested the new release and I'm still running into the issue. Anyway to find out if it's related to a library that was updated?
