### ISSUE TITLE
Webtoons reader doesn't register quick page changes

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2088]
**Describe the bug**
While using webtoons/continuous scrolling mode if you progress too quickly Kavita will not register that the page has changed. It also seems to affect the last page where it might not show progress to that page at all if it is too small. I believe this also affects the ability to progress to the next chapter by scrolling. 

**To Reproduce**
1. Open a book that uses the image reader.
2. Turn on webtoon/continuous scrolling mode if it is not already.
3. Scroll through quickly.
4. Kavita will not show progress is being made in the chapter. 

**Expected behavior**
Kavita accurate shows what page you are on.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 13
 - Browser: Chrome
 - Version 0.7.3.9

**Additional context**
I was able to reproduce this on Android but have not been able to test on other platforms. I also seem to be having an issue uploading the short video I made showing the issue. Will add it when I get the chance to.

**Comment by majora2007** [comment]
From what I've seen, occasionally the reader can loose track of the current page if blasting through the reader, however if reading normally, it tracks pretty well. In addition, using the scrollbar will reset it.

**Comment by scare376** [comment]
I think it's a mostly mobile issue. Sorry I forgot to update this but I could occasionally get it to happen on desktop but it happens with pretty much every manhwa on mobile and I'm not exactly reading fast I think it's just the size of the images. I can shoot you over the file I've been testing with.

**Comment by majora2007** [comment]
Please do as I've tested quite a bit on mobile and it works reliably for me. But webtoons have many different strategies on how they size the images.

**Comment by majora2007** [comment]
@scare376 can you confirm if you're still having this issue on the nightly/v0.7.14? I believe the recent webtoon improvements over the last 2 releases have solved this.

**Comment by DieselTech** [comment]
User can't reproduce the issue anymore, so considering solved for the time being.
