### ISSUE TITLE
Show Chapter Name from File Name

### ISSUE THREAD

**Issue by Epicrex** [Kareadita/Kavita#2091]
I maybe started off on the wrong foot with the main dev and I’m sorry for the rude and false comments.

I’ve gone through alternative comic book/ manga reader software and like Kavita the most, from how it works to it’s UI/ UX design. I’ve nicely set up my library of manga Using the file name structure of:

```
Vol 1 Ch 1.cbz
Vol 1 Ch 2.cbz
Vol 2 Ch 3.cbz
```

The result is every volumes cover nicely displayed in the Volumes tab and all chapters seen in the Chapters tab. I’m a big fan of this behavior and find the naming structure easy to do (for comparison in some software one has to put chapters in a folder called Volume 1 for example).

Now to what I would like so see added, please allow us to add the name of the chapter at the end of the filename like so:

```
Vol 1 Ch 1 - A girl named Yumeko Jabami.cbz
Vol 1 Ch 2 - A boring girl.cbz
…
Vol 2 Ch 5 - The girl who is now a housepet.cbz
```

This parsing behavior should be an opt in toggle in the library settings as to not destroy anyones library that uses different naming conventions.

You might ask, why not just use metadata?

I prefer to add titles directly into the file name, this makes me more independent of what software I’m using and it’s easier to press F2 vs opening up a metadata software, editing the metadata of the file, filling the title field and saving the metadata. 

Also many will already have their library set up with chapter names in the file name. 

(For comic readers metadata is more powerful because they can use tools that auto add it, that sadly doesn’t work as well for manga).

~~~

I’m fine with waiting for the feature and will for the time being be fine with not seeing any chapter names, but I really hope that this is added at some point, thanks in advance.

**Comment by majora2007** [comment]
You need to create a feature request on Feathub, not Github (link in the template of from all our support/sites).

**Comment by Epicrex** [comment]
Ok i looked for kavita feathub on google and was brought to this github, I’ve never before used feathub.

**Comment by majora2007** [comment]
https://feats.kavitareader.com/

**Comment by Epicrex** [comment]
Thanks for the link, I added it to feathub.
