### ISSUE TITLE
EPUB can't load image resource that contains space

### ISSUE THREAD

**Issue by AlienHack** [Kareadita/Kavita#2096]
**Describe the bug**
In Webview EPUB Reader, when reading books that has image resource that name contains space, the encoded url calling for that resource is invalid

**WebView will request**
`https://<host>/api/book/152/book-resources?file=images%2FSolo%2520Levelling-2%2520copy.jpg`

**Instead of** 
`https://<host>/api/book/152/book-resources?file=images%2FSolo%20Levelling-2%20copy.jpg`

Image Filename Is
`Solo Levelling-2 copy.jpg`

**To Reproduce**
1. Go to EPUB novel, read the page that has <img> tag that has image resource which name contains space
2. The image won't show

**Expected behavior**
Image will show and load properly

**Screenshots**
Image File Name in EPUB
<img width="376" alt="image" src="https://github.com/Kareadita/Kavita/assets/8213866/4a33f8bc-8c78-4933-816e-cd20dc3b7705">

Problematic HTML Page (In EPUB)
<img width="391" alt="image" src="https://github.com/Kareadita/Kavita/assets/8213866/992adbf3-769b-4a8c-980b-a0c3cd81428e">

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser Edge
 - Version 114.0

**Additional context**
Request URL:
`https://<host>/api/book/152/book-resources?file=images%2FSolo%2520Levelling-3%2520copy.jpg`

**Payload:**
`file=images%2FSolo%2520Levelling-3%2520copy.jpg`

**Response**
File was not found in book

**EPUB HTML CONTENT**
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="styles.css?version=1" />
<title>Test Book</title>
</head>
<body>
<p>
	<img alt="" src="images/Solo%20Levelling-2%20copy.jpg" /></p>
<div></div>
</body>
</html>
```

=======

**Comment by majora2007** [comment]
Images need to be [valid](https://en.wikipedia.org/wiki/URL#Syntax) urls, so in this case, this is a user issue rather than something Kavita should fix. You should either encode your url correctly or remove the space in the filename and thus the url.

**Comment by AlienHack** [comment]
Oh okay
