### ISSUE TITLE
Reading continues past last chapter / volume and loops back to start

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#2099]
**Describe the bug**
When reading the last chapter or volume in a series, when you get to the very last page the reader will loop back around to chapter 1 again. 

**To Reproduce**
1. Go to the last page in a series
2. Click forward to advance the page
4. Be amazed your back at the start 

**Expected behavior**
In the past there was some kind of warning or popup, can't remember the wording exactly but it was like "You've reached the last page" or "No more pages" 

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Firefox 
 - Version: 0.7.3.15 (Edit by Joe: This is present in all versions until this issue is closed)

**Additional context**
So not only does it loop back around to the starting chapter, it starts marking the progress of that chapter as 'in progress" throwing off your resume.

I've also noticed that if your using Volumes and not chapters, that when it loops back to volume 1, that it will be on the last page of volume 1. I was reading Volume 9 and ended on page 150, clicked to advance the page and I was looped back into Volume 1 at page 150. 

Reproducible in /library/2/series/347

**Comment by majora2007** [comment]
I took a look and it looks like this is a side-effect from another bugfix I did. 

I spent 3 hours working on fixing this and was unsuccessful. I'm going to leave it open for anyone to try and tackle, but at the moment, it's a small annoyance and just not something I can solve.

**Comment by DieselTech** [comment]
~~Technically this doesn't exist anymore because of the new bug that stops the manga reader from progressing to the next file. You have to exit the image viewer and navigate to the next file to continue reading.~~

This is still occurring in the latest nightly as if 1/3/24. Not all series exhibit the issue.

**Comment by majora2007** [comment]
This should have been auto closed with the Foundational Rework. You can retest on the latest nightly. This should be fixed 100%.
