### ISSUE TITLE
Reading list page shows repeated Characters

### ISSUE THREAD

**Issue by pssandhu** [Kareadita/Kavita#2102]
**Describe the bug**
The Characters section on a reading list's page shows the same character multiple times if multiple items in the list contain that character

**To Reproduce**
1. Create a reading list
2. Add multiple items that contain the same characters in their metadata to the reading list
3. Go to the reading list's detail page
4. Expand the Characters section if necessary
5. See that the same character is shown multiple times

**Expected behavior**
Each character should be shown once

**Desktop:**
 - OS: Docker
 - Browser: Firefox
 - Version: 0.7.3

**Comment by majora2007** [comment]
This will be released in v0.7.4.
