### ISSUE TITLE
Switching from webtoon mode to left to right while a double layout mode is selected will always use double layout

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2106]
**Describe the bug**
When webtoon reading mode is set to default and you open up a book that uses the image reader if you have double layout mode turned on as well and you switch to left to right reading mode it will use the double layout even if it is on a screen that it would use the single layout instead.

**To Reproduce**
1. Set browser window to a size that the image reader would default to a single page layout rather than using double or use a device that does the same.
2. Set default settings for image reader to webtoon reading mode and double/double (manga) layout mode
3. Open a book that uses the image reader (one with similar sized pages)
4. Change from webtoon reading mode to left to right.
5. Layout will use double page rather than using the single page.

**Expected behavior**
Layout switches to single page rather using the double page

**Screenshots**
Sent through discord.

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Opera GX
 - Version 0.7.3.18

**Comment by majora2007** [comment]
This will be released in v0.7.4.
