### ISSUE TITLE
Extremely slowing page loads when there is a large number of series

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#2107]
**Describe the bug**
Trying to load the main page on a slightly under powered tablet leads to 20+ second page loads. Might be because of the number of libraries (200+)

**To Reproduce**
https://discord.com/channels/821879810934439936/821879810934439939/1126227971074707516

**Expected behavior**
Pages should load ideally in under 5-8 seconds

**Smartphone (please complete the following information):**
 - Device: Samsung Tab A
 - OS: Android 11
 - Browser: DuckDuckGo Browser
 - Version: 5.159

**Comment by majora2007** [comment]
Please open network tab and share response times of API calls.

**Comment by majora2007** [comment]
From the user (remove .txt)
[Firefox_Focus_Beta_2023-07-08_15.42_profile.json.txt](https://github.com/Kareadita/Kavita/files/12004389/Firefox_Focus_Beta_2023-07-08_15.42_profile.json.txt)

Note to self: I already optimized library api in v0.7.4. This looks to be due to scss imports causing multiple css loads (although they should be incredibly fast, they aren't on this system).

**Comment by majora2007** [comment]
Please let me know if you notice improvement in v0.7.4.

**Comment by DieselTech** [comment]
I do see an marked improvement. Times decreased from ~24 seconds to 13 seconds for the main page loading. However I'm still seeing the `Spartan-VariableFont` being sent twice in a single request of `/library`

![image](https://github.com/Kareadita/Kavita/assets/30128380/9d1cfd56-9577-428b-9ddb-6b2930e60b9c)

**Comment by majora2007** [comment]
Is this still happening on the latest?

**Comment by DieselTech** [comment]
I'm not seeing the font being sent twice anymore,.

**Comment by majora2007** [comment]
I mean, are you still experiencing slow page loads?

**Comment by DieselTech** [comment]
Yes, but I'm going to experiment more with the device in question. Something just feels off about a tablet from 2017 being this slow, especially on content that is essentially just a web site.

**Comment by DieselTech** [comment]
I think this might of been caused by my extremely long sidenav list. Testing on the same device now that the customization update is out I'm seeing much better performance. Loading the main page is a more reasonable 2-4 seconds now instead of 10+.

I'll close this out for now and reopen it in the future if the slowness comes back.
