### ISSUE TITLE
Manga reader does not progress to next volume/chapter with tap pagination on mobile

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2109]
**Describe the bug**
Cannot progress to the next chapter/volume in the manga reader with tap/swipe pagination on mobile. Must open the menu and press the double arrow to progress

**To Reproduce**
1. Open a series that uses the manga reader and has a following chapter/volumes while in left to right reading mode .
2. Progress to the last page.
3. Tap/swipe to progress further.
4. Series will not progress to the next volume/chapter.

**Expected behavior**
Series progresses to the next volume/chapter

**Screenshots**
Screenshots of my manga reader settings
![image](https://github.com/Kareadita/Kavita/assets/2068470/13277f82-a281-4497-8834-1e49d5baaee7)
![image](https://github.com/Kareadita/Kavita/assets/2068470/f7293459-e657-4b05-902b-4d4949688f10)

**Desktop (please complete the following information):**
 - OS: Docker
 - Version 0.7.3.19

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 13
 - Browser Chrome

**Comment by majora2007** [comment]
This only occurs for users using Split page aka not fit to width. I'll take a look.

**Comment by majora2007** [comment]
This will be released in v0.7.4.
