### ISSUE TITLE
"Send to" not working on ebook list pages

### ISSUE THREAD

**Issue by Jojolam44** [Kareadita/Kavita#2110]
Hi,

On my ebook library, when I'm on a list page (all Books or in a specific collection) and when I click on "send to" device, there is no log on kavitaEmail and no book is sent.
It's ok when I do the same thing on single book pages.

I tried on Chrome for Android and Chrome on my laptop (latest for both).
I don't try this feature on manga or comic library so I can't tell if this bug is specific to ebooks or not.

Can you please fix this bug or tell me what I'm doing wrong ?

Kavita version : 0.7.3.1
OS : Unraid with Docker image

Thanks !

**Comment by majora2007** [comment]
What version of Kavita email are you using? Are there any logs in Kavita? What is the email URL you have set up? You said unRAID, so I assume you're using docker? Do you have the network set up correctly?

If you go into the email tab you should be able to check and it'll send you an email. Do you receive that email? What is that check say?

**Comment by Jojolam44** [comment]
I think I found it !

There is no ajax call on "Send To" click on the "src/app/cards/series-card/series-card.component.ts" component (no network call in Chrome DevTools).
If I compare the "handleSeriesActionCallback" method with the other in "series-detail.component.ts" , there is no "case Action.SendTo:" so the action fall in the default path.

Maybe the patch can be the following : 

```
src/app/cards/series-card/series-card.component.ts:123

SeriesCardComponent.handleSeriesActionCallback(action: ActionItem<Series>, series: Series) :

case Action.SendTo:
        {
          const chapterIds = [series.id]
          const device = (action._extra!.data as Device);
          this.actionService.sendToDevice(chapterIds, device);
          break;
        }
```

**Comment by majora2007** [comment]
I can take a look. We might have an edge case bug here. I do know the feature is working. Can you provide me more information, like setting a debugger on `this.actionService.sendToDevice(chapterIds, device);` and telling me chapterIds and if device has anything like an email or id in it?

**Comment by Jojolam44** [comment]
Of course adding a debugger on the ActionService.sendToDevice(chapterIds, device) was my starting point. This method was not called at all on the "list page". It's called only on the "detail page".

KO :
![image](https://github.com/Kareadita/Kavita/assets/4331282/f9ad8d3a-d64e-4c7e-ac7d-c2f90eab8eec)

OK : 
![image](https://github.com/Kareadita/Kavita/assets/4331282/5c3868d9-fe59-43b1-b418-a1392432dd86)

OK : 
![image](https://github.com/Kareadita/Kavita/assets/4331282/7511abe6-b074-4cd2-88eb-da349dd3b07a)


That's what let me think that there is a missing switch on the series-card actions handler.

When I click on the menu on the series-card component, the method handleSeriesActionCallback(action, series) is called with these parameters :

![image](https://github.com/Kareadita/Kavita/assets/4331282/223d2871-ea68-4add-beb2-47820b511297)

The action = 17 represent Action.SendTo and is not catched in this handler.

It's probably an edge case but it will not be so easy to find 😄
And of course my device has an email on it. Kavita can send books on it but not on this kind of page.

Thanks for investigations and for this awesome app ! Great work !

And god bless sourcemap for easily debugging production web app \o/

**Comment by majora2007** [comment]
Thanks for all the help. I got it working. It seems I didn't implement on some pages as the series object didn't have the information necessary to make the API request. I ended up just adding a new variation to power this.
