### ISSUE TITLE
Kavita+ 400 Bad Request errors

### ISSUE THREAD

**Issue by jfenske89** [Kareadita/Kavita#2120]
**Describe the bug**

Using Kavita+ results in "400 bad request" errors in the logs. There is no review data available on the app when viewing ePub series.

The Kavita+ License is valid, showing a green check mark.

Example log message:

```
[Kavita] [2023-07-11 22:10:55.058 +00:00  144] [Error] API.Services.Plus.RatingService An error happened during the request to Kavita+ API
Flurl.Http.FlurlHttpException: Call failed with status code 400 (Bad Request): POST https://plus.kavitareader.com/api/rating
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at API.Services.Plus.RatingService.GetRatings(String license, Series series) in /home/runner/work/Kavita/Kavita/API/Services/Plus/RatingService.cs:line 50
```

**To reproduce**
1. Go to any ePub series.
2. Review the server logs, and see 400 errors.

**Expected behavior**
No errors in the log, and maybe review data appears in the app, if available.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Chrome
 - Version: 0.7.4.0

**Additional context**

**Comment by majora2007** [comment]
This can happen sometimes. Can you provide me with the series you are trying to view the rating for?

**Comment by jfenske89** [comment]
Here are a few with this issue:
- The Expanse
- The Kylar Chronicles
- A Song of Ice and Fire

I checked dozens and only a handful have been successful, such as Treasure Island for example.

Maybe it is an issue with my metadata. I will experiment some more.

**Comment by majora2007** [comment]
I will just say, none of these will be present for external ratings as none of these are on AniList or MAL.

**Comment by jfenske89** [comment]
Oh, that makes sense. I will ignore these errors in the log for now. Thank you for the quick response.

I will keep an eye out for supporting book reviews in the future.

**Comment by majora2007** [comment]
If you have any ideas, don't hesitate to reach out. I've searched a lot for providers for books and comics when I was developing and unfortunately didn't find much.
