### ISSUE TITLE
Library can't be created or edited, but still imports files - docker version

### ISSUE THREAD

**Issue by Kwikxilver** [Kareadita/Kavita#2121]
Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
Fresh install via Docker - trying to create a new library. It scans all the files in the folder, but when the scan is finished the library doesn't appear and it still says I have no libraries, even though I can see individual comics in the "Home" tab.

**To Reproduce**
1. Fresh install of Kavita on Docker. Set up everything as normal and launch via docker-compose.
2. Once logged in, click on "Add Library" and follow the prompts to set everything up (went back to "/" before selecting my folder with my comic collection)
3. Wait for everything to process.
4. When I return to the library list, there's no libraries listed there and it just prompts me to create a new one - although I can see the comics it's imported!

**Expected behavior**
I expected to see the library listed, or be able to access it from elsewhere in Kavita. I can't see or edit my libraries..

**Screenshots**
[https://imgur.com/a/Qnn287m](https://imgur.com/a/Qnn287m)

**Desktop (please complete the following information):**
 - OS: Docker (launched via docker-compose, Docker Desktop for Windows 10)
 - Browser: Firefox
 - Version: Doesn't say in the system tab, but I'm using the latest tag in docker-compose so my assumption is v.0.7.4

**Comment by majora2007** [comment]
This is an issue with the new cache I put in v0.7.4 for libraries. In my testing, it would bust it, but it seems like somehow that didn't happen. You can restart Kavita as a temp workaround and I will fix this in v0.7.5 or a hotfix.

**Comment by Kwikxilver** [comment]
Thank you. I restarted the container and the library has appeared now, which is great.
