### ISSUE TITLE
Kavita+ Scrobbling updates even if tracker has a higher number

### ISSUE THREAD

**Issue by Roshri** [Kareadita/Kavita#2122]
**Describe the bug**
When a Scrobble happens, and Kavita pushes the updated chapter read to Anilist, if for whatever reason (wrong metadata, having read stuff off Kavita, whatever), the current chapter in Anilist is higher than what Kavita reports, Kavita modifies to the lower value it is reporting.

**To Reproduce**
1. Set up scrobble
2. Have an entry in anilist to chapter n
3. Read in Kavita any chapter lower than n-1
4. Kavita will change Anilist to that new number

**Expected behavior**
Higher number should prevail and not update if Scrobble has a lower chapter than Anilist

**Screenshots**

This was my status before the scrobble, updated via tachiyomi
![image](https://github.com/Kareadita/Kavita/assets/29184137/e496bb41-ac78-4d54-bbf8-a32d7f57a312)

And this is what it was modified to, since I had fewer files on Kavita than what I read elsewhere

![image](https://github.com/Kareadita/Kavita/assets/29184137/cab3aa60-1b31-4c83-b3cd-e342b2980132)

**Comment by jacob9423** [comment]
Can confirm this happened to me as well. When I connected Kavita to anilist while the volume count stayed correct the chapter count on a lot of my light novels went to 0

**Comment by majora2007** [comment]
This is now deployed to Kavita+ (doesn't require any new Kavita version). Please test it out and let me know if we need any more tweaks.
