### ISSUE TITLE
Kavita+ Scrobbling when multiple Kavita series map to a single Tracker entry

### ISSUE THREAD

**Issue by Roshri** [Kareadita/Kavita#2123]
**Describe the bug**
For most of my library, I have two versions of the same series, one in English and one in Japanese. Sometimes even three, when I have Official English, Scanlated English and Japanese.
They all point at the same Anilist entry and have correctly set the weblink.

When a Scrobble happens, it should update to the highest of them. 

a series with higher volume in my Japanese library
![image](https://github.com/Kareadita/Kavita/assets/29184137/17d0eb03-5734-40c7-a8a5-d4d3e626f636)

the same series in my English library
![image](https://github.com/Kareadita/Kavita/assets/29184137/db34126c-3140-4625-ab7f-c8b88eb82663)

What was updated in Anilist

![image](https://github.com/Kareadita/Kavita/assets/29184137/1cb4b90c-3be3-40c7-a5b5-bc9ae7b1c901)

What Kavita Scrobbler says it updated
![image](https://github.com/Kareadita/Kavita/assets/29184137/19c8052d-ec2b-4fba-ac72-204f6476bd92)

**Comment by majora2007** [comment]
This is more nuanced as when a scrobble event occurs, it's done on that series. We then send that to Kavita+ which performs the match. So Kavita doesn't know that a given series has other series with the same AniList Id.

**Comment by majora2007** [comment]
But with the enhancements from #2122, this shouldn't be an issue.
