### ISSUE TITLE
amazon.co.jp favicon missing even after adding it locally

### ISSUE THREAD

**Issue by Roshri** [Kareadita/Kavita#2124]
After adding some favicons for the weblinks I noticed that even after placing the icon for amazon.co.jp and adding it to urls.txt, it still shows broken in the UI

The icon is present in my folder
![image](https://github.com/Kareadita/Kavita/assets/29184137/0d359b1e-8fe2-4cda-8517-a2a619fc0b69)

but it doesn't show on Kavita
![image](https://github.com/Kareadita/Kavita/assets/29184137/81da7d43-49f0-4004-8678-e9592f7d67b1)

**Comment by majora2007** [comment]
The issue here is when a manual override (aka adding an image directly), the code wasn't properly stripping away the "www.", which made the check fail.
