### ISSUE TITLE
BUG: Activity monitor shows errors that are somewhat vague and don't appear in the logs or on the admin dashboard under "media issues"

### ISSUE THREAD

**Issue by BU2B** [Kareadita/Kavita#2128]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
When scanning a library, the activity monitor will briefly show files with errors such as "There was an issue counting words on an epub". However, only 2 are displayed at a time and the errors do not appear in the logs or on the admin dashboard under "media issues" I was asked by majora2007 (Joe) to create a bug entry here.

**To Reproduce**
If I recall correctly, here's what I did. Steps to reproduce the behavior:
1. Go to 'Admin Dashboard'
2. Click on the green pencil button on a library that has epub files with known issues.
3. Next, click on "Force Scan" button' and click save button.
4. Errors appear in the upper left hand corner under "activity"

**Expected behavior**
It would be nice to see a list of all the problems with complete filename/folder info so they can be addressed.

**Screenshots**

**Desktop (please complete the following information):**
 - macOS 13.4.1
 - Safari 16.5.1
 - Kavita running on unRAID v6.11.5
 - docker version: 20.10.21
 -  Version: 0.7.4.0

**Smartphone (please complete the following information):**
N/A

**Additional context**
![image1](https://github.com/Kareadita/Kavita/assets/139401143/66e7e91e-535b-49e0-9bf0-f0653fdeb804)
![image2](https://github.com/Kareadita/Kavita/assets/139401143/e30a7ec8-9b96-4baa-81b6-5fe55f435cce)

**Comment by majora2007** [comment]
I just found another issue like this the other day and that bug, like this one, has been in the code for a long time. Thanks for raising an issue. This message is supposed to give the the full filename.

**Comment by BU2B** [comment]
> I just found another issue like this the other day and that bug, like this one, has been in the code for a long time. Thanks for raising an issue. This message is supposed to give the the full filename.

interesting... wish I knew how to help with debugging code, but I'm glad I could at least help out in a small way.

Do you want me to close this issue?

**Comment by majora2007** [comment]
No I will close it when it's linked with the PR that closes it. Such a small bug that went virtually unnoticed for a long time.

**Comment by BU2B** [comment]
> Such a small bug that went virtually unnoticed for a long time.

"If it compiles, it is good; if it boots up, it is perfect." -Linus Torvalds

:-)
