### ISSUE TITLE
Didn't receive my Kavita+ key, how can i contact you?

### ISSUE THREAD

**Issue by RandomLegend** [Kareadita/Kavita#2130]
Hello,

i just subscribed to your Kavita+ service. But i didn't receive any mail and there is no way for me to change or correct anything if i made a mistake.

You didn't list any kind of contact mail or ticket tool as far as i am aware. Please make it possible for me to contact you so we can figure this out.

Thanks.

**Comment by majora2007** [comment]
Solved, thanks for reaching out via Discord.
