### ISSUE TITLE
BUG - Kavita ignores folder hirarchy and treats chapter folders as Series

### ISSUE THREAD

**Issue by 7IXKTUIV1** [Kareadita/Kavita#2133]
**Describe the bug**
When processing a root folder that contains sub-folders (multiple series), Kavita ignores folder hierarchy and wrongly processes sub(sub-folders) as the series.

What it should do:

```
Library Root
  ┖── Series Name A (This should be the series)
       ┖── Chapter 1
         ┖── 001.jpeg
         ⋮
         ┖── 100.jpeg
```

What its doing:

```
Library Root
  ┖── Series Name A
       ┖── Chapter 1 (Kavita treats this as the series)
         ┖── 001.jpeg
         ⋮
         ┖── 100.jpeg
```

**To Reproduce**
1. Add new library in Kavita, and following the current folder structure.

```
Library Root
  ┖── Series Name A
       ┖── Chapter 1
         ┖── 001.jpeg
         ⋮
         ┖── 100.jpeg
```
2. Scan.
3. See error.

**Expected behavior**
Kavita should treat the folder contaning the images as chapter folder not the series folder.

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox
 - Version: v0.7.4

**Screenshots**
Root folder (and its sub-folders):

![image](https://github.com/Kareadita/Kavita/assets/20441269/82e3e126-dc81-4a2a-8724-d145fb755c1d)

Files inside a sample folder:

![image](https://github.com/Kareadita/Kavita/assets/20441269/c6c10889-02e8-4dec-a5d8-12563b99b983)

Selected folder in Library creation:
![image](https://github.com/Kareadita/Kavita/assets/20441269/2c8e97e9-b32d-4420-bc1b-e89ad8c57457)

How it shows up in Kavita after scanning:

![image](https://github.com/Kareadita/Kavita/assets/20441269/3de088a0-e2ad-463d-b412-e4e8f94c7092)

**Comment by KaitoKid** [comment]
I was able to recreate this on `0.7.4.4`. There's a couple of workarounds:

1. Making a second folder for the actual media eg.

Library Root
  ┖── Series Name A
     ┖── Series Name A
       ┖── Chapter 1 (Kavita treats this as the series)
         ┖── 001.jpeg
         
2. Compress all of your images into a zip folder, and then the existing structure that you have works

**Comment by 7IXKTUIV1** [comment]
I have already compressed my images to cbz format, and Kavita is working flawlessly. Feel free to close this issue.

**Comment by majora2007** [comment]
I took a look at this and it is a major issue. Since I changed the scanner a while back, loose leaf image parsing is non-ideal anymore. I might just have to remove it altogether.

**Comment by majora2007** [comment]
After input from the community I decided to fix this issue by redoing how image parsing works in Kavita. Note the linked PR that I believe fixes this (and improves the whole experience). If you can, please test the nightly docker or reply and I will build a nightly for your system.
