### ISSUE TITLE
value must be non-negative. (Parameter 'value') Actual value was -1669332992.

### ISSUE THREAD

**Issue by HelloMusician** [Kareadita/Kavita#2134]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
I updated the version to 0.7.4 today. As a result, when I opened kavita, the prompt value must be non-negative. (Parameter 'value') Actual value was -1669332992.  And my comic books can not be displayed now.
It was fine before the update.

**To Reproduce**
1. update kavita to v 0.7.4
2. Open the kavita
3. See error

**Expected behavior**
I hope that no error is reported and my books can be displayed.

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/105097307/2165fbc0-471d-4259-8cd6-e3b6fc0995fb)

**Desktop (please complete the following information):**
 - OS: Synology DS918+ dsm7.1.1 42962 update 6
 - Browser: Edge
 - Version:  109.0.1518.70 (release) (64bit)

**Comment by HelloMusician** [comment]
> 这已经在每晚修复。本周将推出一个新的马厩。问题是它在appsettings.json中使用了端口键而不是缓存键

Thank you very much! Have a good day~

**Comment by majora2007** [comment]
This will be out in the new stable tomorrow.

**Comment by HelloMusician** [comment]
> This will be out in the new stable tomorrow.

Thank you brother, I will update it as soon as possible to check the issue.
