### ISSUE TITLE
On rare ocassions Series detail doesn't update when metadata is changed on the first chapter/volume

### ISSUE THREAD

**Issue by Roshri** [Kareadita/Kavita#2137]
I have a few edge cases where I replaced metadata from one source to another,  but Kavita keeps showing the old one on the series detail page.

Old metadata from ComicVine
![image](https://github.com/Kareadita/Kavita/assets/29184137/6366df41-8dd8-417a-8610-b494323979bc)

Current metadata from Bookwalker
![image](https://github.com/Kareadita/Kavita/assets/29184137/f9ce3846-7089-4077-bac5-de3707e07b83)

The fields aren't locked or anything

![image](https://github.com/Kareadita/Kavita/assets/29184137/d9cea4a5-69f4-48fc-93ed-a32a29a732ee)

**Comment by majora2007** [comment]
Do me a favor and do a Series scan and see if it changes?

**Comment by Roshri** [comment]
I found the culprit.
I had both Volume 1 and Chapter 001.
Chapter 001 had the metadata shown at series level.
Removed the metadata from Chapter, and now it works as intended.
I kept some leaf chapters because there are some color covers that didn't make it to the volume release.
Closing since there was no issue with Kavita, it was me.
