### ISSUE TITLE
changing bookmarks folder location setting does not take

### ISSUE THREAD

**Issue by gen-angry** [Kareadita/Kavita#2138]
**Describe the bug**
When trying to update the bookmark directory, the setting reverts back to the default location after saving.

**To Reproduce**
1. Go to Admin Dashboard
2. Click on Media tab
3. Under 'Bookmarks Directory', click 'Change'. 
4. Set different folder, click 'share'.
5. Click save. It states that the setting was updated but folder location reverts back to the default setting.

**Expected behavior**
The updated folder location being changed and saved.

**Desktop (please complete the following information):**
 - OS: server - proxmox LXC running ubuntu 22.04, desktop - win10.
 - Browser both firefox and edge have same issue
 - Version: downloaded latest 0.7.4 release as of this post (going to system tab is blank, says "Sequence contains no elements" and generates a 500 error in console)

**Additional context**
All other settings seem to save and update ok, just that one doesn't seem to want to take. I'm not sure if the system tab generating a 500 error is related or not.

logs show this:

```
[Kavita] [2023-07-17 20:28:05.567 +00:00  4] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library/list responded 200 in 2.9140 ms
[Kavita] [2023-07-17 20:28:08.670 +00:00  10] [Information] API.Controllers.SettingsController gen_angry is updating Server Settings
[Kavita] [2023-07-17 20:28:08.672 +00:00  10] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/settings responded 200 in 4.8235 ms
```

POST response shows (from console):
```
XHRPOST
http://192.168.2.213:5000/api/settings
[HTTP/1.1 200 OK 7ms]

	
cacheDirectory	"/opt/Kavita/config/cache"
bookmarksDirectory	"/opt/Kavita/config/bookmarks"
```

I had been trying to set it to `/storage/library/bookmarks` so it doesn't seem to be reading that field correctly. (also I'd like to set the cache folder but that doesn't seem to be a setting)

**Comment by majora2007** [comment]
This ended up being a bug where the directory wasn't being sent to the backend. It has been corrected and will be available in v0.7.6.
