### ISSUE TITLE
Character Field on Series Page not appearing.

### ISSUE THREAD

**Issue by Ark1369** [Kareadita/Kavita#2143]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
Character Field doesn't appear on series page under see more if the only field in Metadata - People is Writers along with Characters.
But it functions normally if there is Writers+Any other field filled alongside characters or any other field besides Writers alone + Character.

**To Reproduce**
1) Open Series Page
2) Add Something in Writer Field under People Page
3) Add Something in Character Field under People Page
4) Click See more.

**Expected behavior**
Characters Field being shown.

**Screenshots**
Writer+Character Field
![image](https://github.com/Kareadita/Kavita/assets/123398211/74a86a1e-8921-4e81-a16a-8abae6051191)
Writer+Cover Artist+Character Field
![image](https://github.com/Kareadita/Kavita/assets/123398211/003a7081-dc4c-482e-9388-3401c0f7f465)
Cover Artist+Character Field
![image](https://github.com/Kareadita/Kavita/assets/123398211/69198dc9-f98a-4535-a663-b8b40043a7d8)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker] Windows Stable 
 - Browser [e.g. chrome, safari] Firefox 113
 - Version [e.g. 22] (can be found on Server Settings -> System tab) 0.7.4.

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majora2007** [comment]
The issue here is that if you just have a set of metadata that is normally under the collapse and NOTHING that is above, then the collapse doesn't show and you can't view that metadata. 

Let me investigate.
