### ISSUE TITLE
Import MAL Stack to create a Collection (Kavita+)

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#2144]
This is a working thought and not me committing to this. But users are free to comment on it. 

My idea is to either allow a user to import their stacks from MAL (once MAL is setup in Kavita+) or via a one-time interface import the collection. Anything that exists on the server (and the user has access to) will get linked. 

It would be cool to have items that are not within the server as well, but I might need a new entity type for that.

These collections may SYNC on a schedule to ensure new content is made available. This needs MAL Scrobbling to be implemented first.

**Comment by majora2007** [comment]
Anime-Planet has this as well. MAL currently have a very painful API to use.

**Comment by DieselTech** [comment]
This was added in release 0.8.2:

https://github.com/Kareadita/Kavita/releases/tag/v0.8.2

https://wiki.kavitareader.com/kavita+/features#mal-stack-import-and-sync
