### ISSUE TITLE
New user invite link screen not showing after creating user

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#2145]
**Describe the bug**
When creating a new user to invite to the server, the 2nd part of the creation process that contains the link to send to the user doesn't show up anymore. 

**To Reproduce**
1. Create user 
2. Click "Invite"

**Expected behavior**
A 2nd screen should show with the address and the base URL appended. 

**Desktop (please complete the following information):**
 - OS: Docker 
 - Browser: Firefox 
 - Version: 0.7.5.1

**Comment by majora2007** [comment]
The modal will automatically close if the email was sent aka your server is discoverable or host name is set. You can get the link from the users page by hitting setup if you're using a fake email.
