### ISSUE TITLE
Backups are missing files/files are not where they should be

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2150]
**Describe the bug**
Not all of the backups include everything. I have some recent backups that are missing the db files, some that are missing some of the folders, and all of the favicons are in the root of the zip (was told this is not intentional)

**To Reproduce**
1.) Backup db (let automatic run)

**Expected behavior**
Backup should have all files and favicons shouldn't be at the root of the zip

**Screenshots**
![dopus_pjGQfScX1g](https://github.com/Kareadita/Kavita/assets/2068470/62765424-bf1a-422d-8441-7477ceeb29b5)

I also noticed this. It creates multiple files over a few minutes. It doesnt always do it and the number isnt consistent
![dopus_UxhLLPnqae](https://github.com/Kareadita/Kavita/assets/2068470/c9313f23-8f65-45da-be90-2e9ced07d102)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Opera Gx
 - Version 0.7.5.1

**Comment by majora2007** [comment]
I already fixed the favicons, ill take a look into the missing files.

**Comment by majora2007** [comment]
I believe I fixed this by scheduling the backup task to be later in the night (2am). This avoids any contention of the db being in use from other maintenance tasks in progress.
