### ISSUE TITLE
Ratings are misaligned and have an extra column

### ISSUE THREAD

**Issue by JShiesty-dev** [Kareadita/Kavita#2152]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, and version are essential!

**Describe the bug**
Ratings are misaligned and have an extra column.

**To Reproduce**
1. Go to a series and wait for ratings to load.
2. See that ratings are misaligned.
3. Inspect and select the row.
4. See that there is an extra blank column.

**Expected behavior**
The rating row should be aligned with the weblinks and metadata rows below it and should not have an extra blank trailing column.

**Screenshots**
If applicable, could you add screenshots to help explain your problem?
![699Pq8act](https://github.com/Kareadita/Kavita/assets/102483672/1c0dd51b-d8a2-478a-9a02-493df00264e1)

**Desktop (please complete the following information):**
 - OS: Windows 11 Docker
 - Browser Chrome Beta
 - Version Latest Nightly

**Comment by majora2007** [comment]
This was done earlier in this release cycle.
