### ISSUE TITLE
Unable to manually Edit Name

### ISSUE THREAD

**Issue by Draknars** [Kareadita/Kavita#2153]
**Describe the bug**
After a recent update (not sure witch one exactly) I can no longer manually edit the display name for item added. The main reason why I do it usually is because there is a bug that cut title shorts when it contains numbers (AFAIK when scrape from the folder name, not metadata). 

**To Reproduce**
1. Go to edit an item
2. Name is grayed out

**Expected behavior**
I would expect that I can edit the name.

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/40360399/39c0c54d-0b3b-4223-be49-f42560fdc74b)
![image](https://github.com/Kareadita/Kavita/assets/40360399/e833ed8f-d72d-4d10-83db-85646ea28463)

**Kavita (please complete the following information):**
 - OS: Docker
 - Version : 0.7.5.0

**Comment by scare376** [comment]
That functionality was removed in 0.7.4.0. 
![opera_pyMPwGVNoi](https://github.com/Kareadita/Kavita/assets/2068470/9be5c94d-5ef8-4369-94d6-717ae3431c8a)

**Comment by teekay30** [comment]
Is there any alternative to do this? Having japanese characters as the filename name becomes messy so I leave my filenames in english but would prefer the actual Names in the UI to be in Japanese

**Comment by scare376** [comment]
Metadata

**Comment by majora2007** [comment]
You can rename your files to how you want them to show in Kavita or use Metadata. I would tag with <Series> and <LocalizedSeries>. You can keep the first Series as one name, and use LocalizedSeries as the other filenames. Kavita will merge them together.

**Comment by teekay30** [comment]
> I would tag with and .

Sorry I think you missed some words here? By metadata, do you mean create collections and then refer to the Collection portion of the app? This works but it's a shame you still don't see the names for it on the homepage as that's what I usually look at (the recently updated section in particular).

I guess that would be a feature request and should be put into that other form?

**Comment by scare376** [comment]
No by metadata we mean adding a comicinfo for cbz/cbr or using calibre/sigil or some other epub metadata tool ( there's now much) for metadata to set the series name.

**Comment by teekay30** [comment]
Ah right, I've not worked with cbz/cbr but does the comicinfo need to be in every archive? Or can it be in the root folder and be read per series?

**Comment by majora2007** [comment]
For the series, it needs to be the first chapter or volume in the cb* file. For the individual issue (only really for books or comics), it can be in the individual.

**Comment by teekay30** [comment]
Ah ok I'll give that a try, thanks!

**Comment by dsatfire** [comment]
Can we reopen this? Since a series has a Name and an OriginalName, there is no need to tie down the name field.
Also this thread seems to imply that you can change the display name via the Metadata tab. That doesn't seem to be the case, since for me there is no name field in metadata.

**Comment by scare376** [comment]
No this will not be reopened as there is nothing functionally wrong. By editing metadata we mean a comicinfo.xml inside of a cbz file or an opf file inside of an epub. If you feel there is a better way to handle this feel free to make a feature request.

**Comment by wlowen** [comment]
Just installed Kavita and came across this issue as I'm experiencing the same bug described in the first post. I have a PDF with a number in the name and the title gets cut off right before the number. Also, the PDF reader will never load. If I remove the number, everything works fine.

Is there something I'm doing wrong, or is it an actual bug? I can open a new issue if need be.

**Comment by scare376** [comment]
Being unable to edit the name within Kavita is functioning as it should. It is not a bug. The issue with the number in the name of the PDF is kind of tough as it's likely being stripped by the parser for use as a volume/issue/chapter number. I would pop into the discord if possible or create another issue for the PDF issue itself.

**Comment by dsatfire** [comment]
> No by metadata we mean adding a comicinfo for cbz/cbr

Then maybe I've been doing it wrong. I have a ComicInfo.xml in my cbzs, but the name in Kavita remains as the parser output. I've tried multiple ways to fix this and have resorted to disabling the scan and injecting rows into the database manually.
This is an example of my setup/file structure:
```
- <Collection Root>
  - The Great Mage Returns after 4000 Years
    - ComicInfo.xml (I have other folders without a series comicinfo, neither seem to work)
    -  The Great Mage Returns after 4000 Years CH 0001.cbz
      - ComicInfo.xml (These are all compressed into the cbz)
      - 0001.jpg
      - 0002.jpg
      ...
   -  The Great Mage Returns after 4000 Years CH 0002.cbz
     -  ...
  - Some Other Title
  ...
```
For `The Great Mage Returns after 4000 Years` in particular, the scan ends up merging all the chapters into one massive chapter.

Since there is obviously a clash with the parsing of titles and the inclusions of numbers in titles, maybe as a feature request, we could allow the assigning of alternative parsing strategies for specific collections. Like, for instance, a parser that takes the filename as the title directly without trying to parse out volume or chapter. The parser then could rely on the folder structure to define volume and chapter titles. E.g.
```
- <collection root>
  - This is a Series title
     - This is a Volume title
       - This is a chapter title
  - This is another Series
    - This is a chapter with no specific volume (will be assigned a volume with the same name as the series)
```
Or maybe a way to escape numerical values in the titles so that the parser recognizes them as part of the title. 

I can devote a weekend or two to the implementation if received well.

**Comment by MDanihy** [comment]
This one issue is the reason I stopped using Kavita.  Making a ComicInfo.xml  for over 500 titles is a bit of a pain.

**Comment by arcanescroll** [comment]
What exactly is the reasoning behind this? Why remove a function that allowed naming your documents when it's just mapped to a field in the database anyway? If this is going to be the standard, then we need Metadata for PDF files, something that could have been easily added ages ago.

**Comment by CubeyGlyph** [comment]
Requesting this to be reopened as a feature request. I know metadata is king in Kavita, but there are various reasons a person might not be able to have metadata on all files, and even if a person wants to get metadata on everything it certainly acts as a hurdle when migrating from another platform.

**Comment by CubeyGlyph** [comment]
> > No by metadata we mean adding a comicinfo for cbz/cbr
> 
> Then maybe I've been doing it wrong. I have a ComicInfo.xml in my cbzs, but the name in Kavita remains as the parser output. I've tried multiple ways to fix this and have resorted to disabling the scan and injecting rows into the database manually. This is an example of my setup/file structure:
> 
> ```
> - <Collection Root>
>   - The Great Mage Returns after 4000 Years
>     - ComicInfo.xml (I have other folders without a series comicinfo, neither seem to work)
>     -  The Great Mage Returns after 4000 Years CH 0001.cbz
>       - ComicInfo.xml (These are all compressed into the cbz)
>       - 0001.jpg
>       - 0002.jpg
>       ...
>    -  The Great Mage Returns after 4000 Years CH 0002.cbz
>      -  ...
>   - Some Other Title
>   ...
> ```
> 
> For `The Great Mage Returns after 4000 Years` in particular, the scan ends up merging all the chapters into one massive chapter.
> 
> Since there is obviously a clash with the parsing of titles and the inclusions of numbers in titles, maybe as a feature request, we could allow the assigning of alternative parsing strategies for specific collections. Like, for instance, a parser that takes the filename as the title directly without trying to parse out volume or chapter. The parser then could rely on the folder structure to define volume and chapter titles. E.g.
> 
> ```
> - <collection root>
>   - This is a Series title
>      - This is a Volume title
>        - This is a chapter title
>   - This is another Series
>     - This is a chapter with no specific volume (will be assigned a volume with the same name as the series)
> ```
> 
> Or maybe a way to escape numerical values in the titles so that the parser recognizes them as part of the title.
> 
> I can devote a weekend or two to the implementation if received well.

I am also having the issue where a number in the filename causes issues for the parser.  Did you ever figure out a good solution for this?

**Comment by majora2007** [comment]
For everyone who is asking for reopen, you would be better off raising a feature request and gathering data there. I do not look at closed issues when planning.
