### ISSUE TITLE
Cannot access password reset screen

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2161]
**Describe the bug**
Kavita appears to be redirecting back to the login screen when following the password reset url.

**To Reproduce**
1. Log out of kavita.
2. Click forgot password
3. Enter email
4. Follow link in email
5. New password dialog might appear for a second but is redirected back to login screen.

**Expected behavior**
New password screen stays and allows you to set new password

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Opera GX
 - Version 0.7.5.8

**Comment by scare376** [comment]
i just tested on 0.7.6.0 baremetal on windows. it immediately redirected me back to the login window. are you sure you were fully logged out when you followed the flow? maybe try in a private tab

**Comment by majora2007** [comment]
I tested from the localization branch, so perhaps an issue was solved on that branch. I'm wrapping it up, so we can retest this on the next nightly.

**Comment by majora2007** [comment]
This was confirmed to be fixed in latest nightly.
