### ISSUE TITLE
LocalizedName rejection isn't propagating to UI 

### ISSUE THREAD

**Issue by Roshri** [Kareadita/Kavita#2163]
In one of my epub libraries, the Localized Name rejection is not being shown to the user, after modifying and clicking save, the change doesn't persist.

![image](https://github.com/Kareadita/Kavita/assets/29184137/90a7e483-b75a-4b79-bd2b-6bdef3b61a4c)

![image](https://github.com/Kareadita/Kavita/assets/29184137/7602075c-188b-48f8-915a-d4683ff5b226)

LocalizedName duplicate check needs to be contained to one library.
If the rejection is caused via the Localized Name being used in another series from other library, it still should let me modify in the current one

**Comment by majora2007** [comment]
I just tried to reproduce and I looked into the code. There is no duplicate checks on uniqueness on the names. I was able to update the localized name to one in the current library exactly as is and everything worked. There is basically no logic except to take the strings from UI and set them. 

Could you open dev tools and show the payload?
![image](https://github.com/Kareadita/Kavita/assets/735851/2997d97d-422c-402b-b996-4cdb02290d98)

**Comment by majora2007** [comment]
OP has confirmed that this works after opening dev tools. Likely a caching issue.
