### ISSUE TITLE
Recently updated series doesn't update until a refreshed

### ISSUE THREAD

**Issue by JShiesty-dev** [Kareadita/Kavita#2165]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
Recently updated series doesn't update until refreshed.

**To Reproduce**
1. Go to the dashboard
2. Add a volume or chapter to a series
3. Scan the library
4. Recently updated series don't get updated

**Expected behavior**
Recently updated series updates when a series gets updated without needing to refresh.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker]
 - Version [e.g. 22] (can be found on Server Settings -> System tab)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majora2007** [comment]
How long did you wait? Because it doesn't trigger immediately, but waits some amount of time before it will trigger a refresh (as a fresh scan could overwhelm with reloads)

**Comment by therobbiedavis** [comment]
Also please fill out the template. We don't know if you are using Nightly or Stable. Knowing helps save time when trying to reproduce.

**Comment by majora2007** [comment]
This is working for me on latest nightly.

**Comment by majora2007** [comment]
I'm going to close as there is no Kavita information to help understand when this happened.
