### ISSUE TITLE
Series level metadata takes 1.5 over 1 on Book library

### ISSUE THREAD

**Issue by Roshri** [Kareadita/Kavita#2167]
A series has volume 1 and 1.5, Series level metadata should be filled with volume 1 but it's taking 1.5 for cover and Summary
![image](https://github.com/Kareadita/Kavita/assets/29184137/d677fec5-11a1-49e8-9fb3-bf57a13ede34)

![image](https://github.com/Kareadita/Kavita/assets/29184137/1ad1d516-1217-45c7-adf9-8317fce79b1a)

![image](https://github.com/Kareadita/Kavita/assets/29184137/8cfa3b25-e722-4866-9de2-f7eb43e059a4)

**Comment by majora2007** [comment]
Any chance you could just send me 2 books from this series? I'm seriously lazy to setup the test data. Just dm me on discord.

**Comment by majora2007** [comment]
Okay I took a look into this. It looks like it will require a change in the scan loop that might have adverse affects. I will work on this in v0.7.8 release to give ample time for testing.
