### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [Kareadita/Kavita#2168]
Changing the translation to specifically state "GPLv3-**only**" means terms have to be negotiated with every
translator if wanting to go AGPLv3, or upgrade to a potential GPLv4 in the future.

I don't understand how that can be beneficial.

Can be changed in
https://hosted.weblate.org/settings/kavita/ui/ and
https://hosted.weblate.org/settings/kavita/glossary

**Comment by majora2007** [comment]
I don't honestly understand the difference it makes and why translator would care if it was GPLv4. I changed to match Kavita's license.

Could you help me understand?

**Comment by comradekingu** [comment]
@majora2007 
It is whoever wants to go GPLv4 with the project that cares. If the translations are tied to GPLv3 (with the "only") it means translations can't be re-licensed without asking every single translator if it is OK.

Now it is LGPLv3-or-later. I think you meant to make it GPLv3-or-later. :)
