### ISSUE TITLE
Characters section is now displaying empty boxes after updating to 0.7.6

### ISSUE THREAD

**Issue by howdy-im-david** [Kareadita/Kavita#2173]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
Characters section on volumes/issues now displaying as blank boxes after upgrade from 0.7.5 to 0.7.6. 

**To Reproduce**
1. Go to All Series
2. Click on any series
3. Scroll down to individual issues/volumes
4. Verify that Characters are being display as blank boxes

**Expected behavior**
As per 0.7.5, expected behavior is to see character names in Characters sections

**Screenshots**
<img width="1349" alt="Screenshot 2023-08-01 at 4 46 59 PM" src="https://github.com/Kareadita/Kavita/assets/104217810/41bad9af-585a-405a-b41c-17f46a0f1f7c">

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Safari v17.0 (content blockers disabled) / Chrome Version 115.0.5790.114 (extensions disabled)
 - Version: 0.7.6.0

**Comment by majora2007** [comment]
Thanks, this was caught just after the release. It's already fixed locally and will be out in v0.7.7.
