### ISSUE TITLE
Can't reorder reading list

### ISSUE THREAD

**Issue by DireMunchkin** [Kareadita/Kavita#2176]
**Describe the bug**
In one of my reading lists, the drag to reorder button is missing. And also the order number is not correctly counted as you scroll. Please see the attached GIF for what happens. The bug is present on several combinations of OS / Browser.

**To Reproduce**
1. Go to reading list.

**Expected behavior**
Show reorder button, correctly count order number.

**Screenshots**

![Kavita Issue](https://github.com/Kareadita/Kavita/assets/1665676/175c63ff-6315-4669-a88b-4caff99162a0)

**Desktop (please complete the following information):**
 - OS: Windows 10, Linux Mint 20.3
 - Browser LibreWolf, Chrome
 - Version 0.7.6
 
**Additional context**
I only noticed this issue after updating to 0.7.6, but rolling back to 0.7.5 doesn't seem to fix it either.

**Comment by DireMunchkin** [comment]
Aha, so the button being missing is intended?.

The problem with the number is that it's not updating correctly as I'm paging down. It stays at 11 as I scroll, but it should be like 20-30 where I am in the list.

**Comment by majora2007** [comment]
> Aha, so the button being missing is intended?
Correct. Trying to drag and drop with 100+ items isn't a good experience and prevented virtualizing the DOM (aka making the page lightweight). 

Ahh okay, I'll take a look into it.

**Comment by DireMunchkin** [comment]
I temporarily removed some books from my reading list so it's 100 books, not 104: Then I confirmed the order number starts working correctly again. So the issue happens when the reading list has > 100 books and the drag button is hidden.

**Comment by DireMunchkin** [comment]
@majora2007 I tried out the fix in nightly, but now there seems to be another issue instead. If I move one of the books in the long list, the list gets rearranged in a random order.

**Comment by majora2007** [comment]
Nice find. I've fixed that as well. I'll push it out later today.

**Comment by DireMunchkin** [comment]
OK, now I'm on 0.7.7, but we have issue 3, which is I can't move books from the end of the list to the front. If I go to book 40 or something and change number to 0, hit enter, the input is ignored and the book stays where it is in the order.

**Comment by majora2007** [comment]
Create new issues please.

**Comment by DireMunchkin** [comment]
OK. #2203
