### ISSUE TITLE
Feature Request:  Sub-Libraries

### ISSUE THREAD

**Issue by mpatton125** [Kareadita/Kavita#218]
Hi there,

Any chance for sub-libraries?  I like to have overall groupings.

Eg:

Books --> Photography
           --> Sailing
           --> Yoga

Comics --> Rick & Morty
             --> The Walking Dead

Or would this be handled via tagging, somehow?

**Comment by majora2007** [comment]
Not sub-libraries per-se, but Collections like Plex are coming that will act as "virtual libraries". 

However, you could also have Libraries set out as:
Books: Photography (/books/photography)
Books: Sailing (/books/sailing)
etc if you wanted.

**Comment by majora2007** [comment]
Hi @mpatton125, v0.4.1 just released yesterday and has custom tagging support. I think this should meet your needs, please try it out and let me know if you want something different or have any ideas to improve.

**Comment by majora2007** [comment]
Closing this issue until a response comes stating that Collections does not solve this issue.
