### ISSUE TITLE
Can't move a book in a long list

### ISSUE THREAD

**Issue by DireMunchkin** [Kareadita/Kavita#2203]
**Describe the bug** 
When your reading list contains more than 100 books, it sometimes becomes impossible to move them on the list using the order number. 

**To Reproduce**
1. Go to a long reading list (> 100)
2. Click on Show order numbers.
3. Edit the order number of a book, hit enter.
4. Book does not move.

**Expected behavior**
I expect the book to be moved to that place in the list.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2
 - Browser LibreWolf
 - Version 0.7.7

**Comment by majora2007** [comment]
I can move books within the list via the order input.

**Comment by DireMunchkin** [comment]
OK, are you using a long list? I only get this issue on the same list as the last issue.

I had a look at web inspector and I get an error `ERROR TypeError: r is null` when the book fails to move.

![Screenshot from 2023-08-10 19-48-37](https://github.com/Kareadita/Kavita/assets/1665676/0dbc5cb8-5d78-47a5-bc03-392e3c3048f9)

**Comment by majora2007** [comment]
I just tested again on the latest and everything is working for me.

**Comment by DireMunchkin** [comment]
Thanks for having a look at it. I ended up working around the issue by subdividing my reading list instead. Not sure if I'm still affected as all my lists are shorter. I'll close the issue.
