### ISSUE TITLE
After closing book epub bookmark will jump to correct section (page) but not correct line/paragraph

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2218]
**Describe the bug**
After closing a book the epub bookmark will jump to the correct section (page) of the book but might not jump to the correct line.

**To Reproduce**
1. Create epub bookmark
2. Navigate to a different section (page) 
3. Close book
4. Open book
5. Click on bookmark.
6. Correct section (page) should open but it might not jump to the correct line.

**Expected behavior**
Clicking a bookmark should jump to the correct section and line.

**Screenshots**
https://github.com/Kareadita/Kavita/assets/2068470/1b845b3e-67e3-474f-a0ee-85e50b65edfa
also seen in the image is that I cannot delete one of the bookmarks because it is too long.

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser opera gx
 - Version 0.7.7.11

**Additional context**

**Comment by majora2007** [comment]
I think this is due to you going to the bookmark which is loading the top, closing. Thus the top of the page is being stored. So when you resume, it's putting you on that part.
