### ISSUE TITLE
Series or Issue Characters list not expanding in place

### ISSUE THREAD

**Issue by howdy-im-david** [Kareadita/Kavita#2219]
Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
When viewing an issue or volume with more than 6? Characters, Characters list will jump to right side of screen when expanding. If button says (and 1 more) or (and 2 more) when expanding, list stays in place as expected. 

**To Reproduce**
1. Go to 'Any Series with multiple Issues or Volumes'
2. To the right of the Characters area, in the Issue or Volume list click on '(and X more)'
3. Scroll down to Verify that list of Characters has shifted to right justified layout if more than a few additional when expanding. See Screenshot examples

**Expected behavior**
List of characters to not right-justify on the layout and just expand in place (similar to Writers/Authors section in Series overview) 

**Screenshots**
Correct/expected expansion without list of characters moving to the right 
<img width="711" alt="Screenshot 2023-08-16 at 2 08 45 PM" src="https://github.com/Kareadita/Kavita/assets/104217810/99159e37-e84e-4e6f-a227-dab79fc0a157">
<img width="684" alt="Screenshot 2023-08-16 at 2 08 56 PM" src="https://github.com/Kareadita/Kavita/assets/104217810/9fc84fb6-0ab1-4b1f-ad77-ae684584b173">

Character list expansion moves to far right of screen (right-justified layout)
<img width="694" alt="Screenshot 2023-08-16 at 2 09 05 PM" src="https://github.com/Kareadita/Kavita/assets/104217810/9a4d6c3b-3e14-4574-9035-7a8f88ae16be">
<img width="1215" alt="Screenshot 2023-08-16 at 2 09 25 PM" src="https://github.com/Kareadita/Kavita/assets/104217810/cbab15c5-86b0-4496-81f6-3e917086d965">

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Safari 17 & Chrome 115
 - Version: 0.7.7.11

**Comment by majora2007** [comment]
It would have helped for you to tell me where the bug was occurring. Took me some time.

**Comment by howdy-im-david** [comment]
Hi Joe, I don't believe the tone of the reply was necessary, but you're more than welcome to ask for additional feedback in written clarity or screenshots to help speed up triage. I was under the impression that the written reproduction steps were adequate to identify the problem area, but happy to add any added documentation when needed. Thanks for reviewing the submitted issue!

**Comment by majora2007** [comment]
I think you misunderstood the tone as I didn't mean to jab at you, but joke on it. 

For me, it would have been helpful for the issue screen to be identified, unless I'm misunderstanding your issue entirely. From what I'm reading, it seems this issue is occurring on item-list. As I tested series detail and see no issue present. Hence why I commented, it would be helpful to comment where you're having an issue, otherwise, I have to guess and test every place the screen might look like your pics.

Please do clarify the issue as now I'm not entirely sure where the issue is occurring.

**Comment by majora2007** [comment]
Okay perfect, it's on list item and not series detail. Let me look into this. Video was very helpful.
