### ISSUE TITLE
Epub bookmark wording consistency

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2220]
**Describe the bug**
The word for the page marker (page) when using epub bookmarks is not consistent with the word that the page marker jumps to (section)

**To Reproduce**
1. Create an epub bookmark
2. Bookmark page marker uses the word page
3. The word that page corresponds to when it jumps is actually section.

**Expected behavior**
The bookmark should say section marker rather than page marker to have consistent wording. Also there is an extra end curly bracket when there are no bookmarks.

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/2068470/7b8518d1-4ffa-4fc8-b814-299832b788b1)

![image](https://github.com/Kareadita/Kavita/assets/2068470/3d787cbf-7253-4cee-9bac-7a550a0f132a)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Opera GX
 - Version 0.7.7.11

**Additional context**

**Comment by majora2007** [comment]
I'm really not sure how to handle this because the bookmark is actually on a page. The Section you see is a virtualization of that page, but if you were to switch to Scroll mode, then the wording would match up.

**Comment by majora2007** [comment]
I'm closing this as I never got an answer. We can discuss in discord.
