### ISSUE TITLE
Adding multiple tags deletes previous tags

### ISSUE THREAD

**Issue by DrTinyFace** [Kareadita/Kavita#2221]
**Describe the bug**
When adding tags to a book/manga/whatever, if you do not save after adding the first tag, adding the second tag will delete both tags. Each tag must be added one at a time, saved, and then you must exit out of the edit menu and go back in before adding another tag.

**To Reproduce**
1. Edit any series/book/whatever
2. Go to Metadata
3. Add a tag, press enter
4. Add another tag, press enter

**Expected behavior**
I'd expect it to work the same as genres or collections, with which you can add as many genres/collections as you want simply by pressing "Enter" after adding each one and then saving once all are added.

**Screenshots**
Screenshots wouldn't be applicable to this as far as I know, but if you'd like a screenshot of something specific I'm happy to provide :)

**Desktop:**
 - OS: Windows
 - Browser: Firefox, Chrome
 - Version: 0.7.7.0

**Smartphone:**
 - Device: Samsung S9
 - OS: Unsure, but most recent Samsung S9 version
 - Browser: Firefox, Chrome, Stock Browser
 - Version: 0.7.7.0

**Additional context**
Only thing I can think to add to this is that I updated to see if that would fix the bug and it didn't work. Not sure if there's anything specific that you'd like from me in terms of information, but I'd be happy to provide anything you need :) also, I'm running the server locally on my PC and have tested on both my phone and PC. I'm also funneling Kavita through Tailscale but I doubt that should have any impact on it, especially since I've tested through both local and the actual Tailscale link.

**Comment by majora2007** [comment]
This requires #2292

**Comment by majora2007** [comment]
Notes to self: This is for when you use keyboard to add a new tag and add 2 new ones, the previous one gets removed.
