### ISSUE TITLE
Parsing issue when full word volume is used in file name

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2223]
**Describe the bug**
When the full word volume is used in the file name it doesnt seem to be parsing correctly. It should just recognize as volume but kavita will use the number as a chapter number

**To Reproduce**
1. Have a cbz file that uses the full word volume in the filename. can have metadata or no metadata (just no chapter tag)
2. Scan into kavita
3. Kavita will pull the volume number as a chapter number

**Expected behavior**
Kavita recognizes the number as just a volume number not a chapter number

**Screenshots**
![dopus_INBDqgcLxJ](https://github.com/Kareadita/Kavita/assets/2068470/f178b789-6def-4dff-bc2a-45011a3cf913)

![dopus_jAquY3XnCi](https://github.com/Kareadita/Kavita/assets/2068470/6bae1b27-4d5c-4c6c-a660-cec2a2d497ba)

**Desktop (please complete the following information):**
 - OS: Docker
 - Version 0.7.7.11

**Comment by majora2007** [comment]
This works for me on a manga library with no comicinfo....

**Comment by scare376** [comment]
I just reproduced it on the latest stable baremetal on windows.

**Comment by majora2007** [comment]
Send me the the file please. It's not clear from the image the folder structure, but I tested manually and with a unit test and it parses the volume number and series correctly.

**Comment by scare376** [comment]
sent. structure is library root > series name > series.cbz

**Comment by majora2007** [comment]
Okay I reproduced this. I misunderstood the issue. The issue is that Volume 1 is parsing as Chapter 1, not that Volume 1 is not parsing correctly.
