### ISSUE TITLE
Error applying cover image for artwork in raw set with volume

### ISSUE THREAD

**Issue by YTOAA** [Kareadita/Kavita#2229]
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at API.Services.ImageService.CreateThumbnailFromBase64(String encodedImage, String fileName, EncodeFormat encodeFormat, Int32 thumbnailWidth) in /home/runner/work/Kavita/Kavita/API/Services/ImageService.cs:line 353

The above error occurs. I don't know if this is the same with compressed works such as zip, but errors occur in a set of raw images consisting of simple folders.
This does not happen when you apply a cover image of a work
It happens when you apply the cover image of the volumes in the work. Also, the same error occurs when you go to the Chapter tab and click Apply images of the customer chapters arbitrarily. The tested version was tested on version 0.7.7 posted on docker. I've never seen this bug in the past version.

**Comment by majora2007** [comment]
You need to follow the template and attach the image so I can reproduce. I can't help without the template filled out.

**Comment by YTOAA** [comment]
![스크린샷 2023-08-22 044440](https://github.com/Kareadita/Kavita/assets/24527825/cbe906b5-41da-4e36-b6d4-afddb3b5684b)
If volumes exist in any work, setting the cover image in volumes will result in an error of 400 and the error mentioned in the first comment will appear in the docker log. What's interesting about this is that if you click on an image with an error twice in a row, the error will still be set to the cover image for that volume. Once again, this was tested with a collection folder of raw files, not with a compressed work such as zip.

**Comment by ytoaa** [comment]
@majora2007 The same symptoms still appear in version 0.7.8 
In any case, once a warning has been issued, press again to replace the cover image, so there is no functional problem. However, I am curious about the cause of the error.
