### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by AtreideGET** [Kareadita/Kavita#2230]
Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
The series whose first character is accented are found at the end of the library.

**To Reproduce**

**Expected behavior**
the order of the series in the library must not take accented characters into account

**Screenshots**
![kavita prob-case](https://github.com/Kareadita/Kavita/assets/88152664/1f40ed1b-283b-4d96-ad03-0c350fd699dd)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: firefox 116.0.3
 - Version : v0.7.7

**Comment by majora2007** [comment]
You can use sort title (embedded or via UI) to fix this.
