### ISSUE TITLE
Reading list bulk select

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2231]
**Describe the bug**
Joe mentioned bulk selecting reading lists in order to delete them but this does not seem to be an option.

**To Reproduce**
1. Go to reading lists.
2. Attempt to select multiple reading lists.
3. Can only select one.

**Expected behavior**
Multiple reading lists are able to be selected.

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Opera Gx
 - Version 0.7.7.14

**Comment by majora2007** [comment]
Going to close this. There is a feature request for this open. Bulk selection doesn't exist for Reading List or Collections currently. Need feedback from users before I take on that work earlier.
