### ISSUE TITLE
Hard coded paper-bg.png path that does not work with baseUrl

### ISSUE THREAD

**Issue by sulisu** [Kareadita/Kavita#2237]
https://github.com/Kareadita/Kavita/blob/24f5bf1167f20b993e9679b9a72b56946fd74d23/UI/Web/src/app/book-reader/_models/book-paper-theme.ts#L97

This line is not modified to align with baseUrl improvement.

https://github.com/Kareadita/Kavita/pull/1824

**Comment by majora2007** [comment]
Please update your pr to match the template

**Comment by sulisu** [comment]
> Please update your pr to match the template

Sorry, I can read and understand a little computer language. But I am not a developer, so I don't know how to use develop work flow properly.

**Comment by majora2007** [comment]
Oh this is an issue. Was using the mobile app and thought this was a PR.
