### ISSUE TITLE
Comic panels not loading - several HTTP POST requests but no GET

### ISSUE THREAD

**Issue by TheQwenton** [Kareadita/Kavita#2241]
**Describe the bug**
When going to the next panel in a comic while using Kavita on Ipad mini or google chrome, the panels are not loading. While the panel number will change (IE from 70 to 71 to 72) the panel image will remain the same. Sometimes even after several button taps the panel image will not change. Seconds later the panel will change to a panel that is farther then where you had scrolled in the first place. This occurs on all devices and browsers I try
**To Reproduce**
1. Sign into Kavita
2. Open comic to read
3. attempt to progress to next comic panel
4. Kavita reports the panel number has changed, but the image remains the same

**Expected behavior**
When the panel number changes, the image will change to the corresponding panel number,

**Screenshots**
Here is an example of several POST's with no image. 
![image](https://github.com/Kareadita/Kavita/assets/119769882/9f09c382-e0d9-410c-8d3d-838edd93894d)
Here is a short clip of me clicking through panels slowly and also with some speed without the image changing. I have live logs on the side of my screen. Take note on the panel number, it changes with no image update.
https://imgur.com/a/SJOSfhR

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 0.7.7.0 (Running Kavita via Docker on UNRaid

**Smartphone (please complete the following information):**
 - Device: Ipad Mini 6th generation
 - OS: iPad OS 16.6 (latest)
 - Browser: Safari
 - Version:16.5

**Additional context**
If I am missing any relevant information please let me know. Kavita used to work great for me! I do not know what is going on. I love the work you guys do and plan to continue donating. (:

**Comment by Carter0108** [comment]
Would like to add that my Kavita stopped loading new pages recently and upon seeing this issue I checked.

I can load comics no problem via http at localhost:5000 but when trying to access through https with my reverse proxy comics no longer load at all.

**Comment by majora2007** [comment]
@Carter0108 please add logs when this issue occurs for you.

**Comment by TheQwenton** [comment]
> Would like to add that my Kavita stopped loading new pages recently and upon seeing this issue I checked.
> 
> I can load comics no problem via http at localhost:5000 but when trying to access through https with my reverse proxy comics no longer load at all.

This is through nginx reverse proxy manager. I have never had issues before so this is all weird to me

**Comment by TheQwenton** [comment]
> So the browser your using to consume the images is safari?
> 
> I have seen issues like this before where when the response time is unreasonably long (a min), it won't render correctly. But you're showing 4ms.
> 
> I'll have a look after my holiday.

This is happening on Windows11 on Google Chrome, as well as Ipad mini 6th gen safari. Despite the HTTP POST time being very low I am getting no HTTP GET responses, no image actually loads. Were you able to check out the video I linked showing the problem happening live?

**Comment by TheQwenton** [comment]
> Would like to add that my Kavita stopped loading new pages recently and upon seeing this issue I checked.
> 
> I can load comics no problem via http at localhost:5000 but when trying to access through https with my reverse proxy comics no longer load at all.

Just double checked on this as well. Seems to be an issue only when accessing Kavita through reverse proxy. Connected via localhost:5000 and everything works as intended.. Trying to read the same comic through reverse proxy causes loading issues!!

**Comment by TheQwenton** [comment]
> @Carter0108 please add logs when this issue occurs for you.

Went and recreated the issue again just now with some fresh logs. The same thing seems to be happenin
[kavita20230827.log](https://github.com/Kareadita/Kavita/files/12448607/kavita20230827.log)
g. Note the other comments I made about this only occurring when using Kavita through reverse proxy as well. Let me know what you find out.

**Comment by TheQwenton** [comment]
When the image doesnt load, just shows a little place holder image... 
![image](https://github.com/Kareadita/Kavita/assets/119769882/5e5740d5-b168-4c65-8597-716abf701983)

**Comment by majora2007** [comment]
Are you on the same network as where the reverse proxy is running?

**Comment by TheQwenton** [comment]
> Are you on the same network as where the reverse proxy is running?

Yes I am on the same network, this has never been a problem before, and my connections to my (14) other proxy hosts work the same. I am attempting a deletion and rebuilding of my docker.img on unraid to see if there is any corruption I need to work on there. If that does not work I will be at a loss for words

**Comment by majora2007** [comment]
I'm still on holiday but back next week. I'll take a look and see what might be the issue. It seems to be rare as I haven't heard anything in support about this either.

**Comment by TheQwenton** [comment]
> I'm still on holiday but back next week. I'll take a look and see what might be the issue. It seems to be rare as I haven't heard anything in support about this either.

Sounds good. Finished rebuilding my docker.img in unraid, still having same issue. Went ahead and deleted NGINX proxy manager, along with all appdata and started from scratch. Recreated my wildcard cert, recreated access lists, and readded Kavita as a proxy host. Still having the same issue.

**Comment by TheQwenton** [comment]
Issue seemed to have fixed itself... My Router ended up killing itself about 2 weeks after opening this ticket. Have a new router now and kavita seems to working fine over reverse proxy now. Thanks for the help!
