### ISSUE TITLE
OPDS url strips https from url when host name not set

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2245]
**Describe the bug**
When the Host Name is not set in Email settings the opds will use an http url even if the page uses https.

**To Reproduce**
1. Have no Host Name set
2. Open 3rd party clients page with https url
3. OPDS URL will have http rather than https

**Expected behavior**
URL mimics the browser url.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser opera gx
 - Version 0.7.7.17

**Comment by majora2007** [comment]
I'm reading this issue as the user doesn't have host name, but is accessing via a reverse proxy over https, Kavita is generating as http.

**Comment by majora2007** [comment]
From what I'm seeing this happens only when the reverse proxy isn't forwarding X-FORWARDED-FOR
