### ISSUE TITLE
Kavita login not rendering on older Safari versions

### ISSUE THREAD

**Issue by RobertD502** [Kareadita/Kavita#2246]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
It looks like there is an issue with the Kavita frontend loading on Safari browsers that are a bit older - it seems to be related to `ngneat-transloco`.  <br><br> For example - when accessing Kavita on **iOS 15.1**, the following is seen:

![image](https://github.com/Kareadita/Kavita/assets/52541649/319c1315-6624-4524-9da5-71d9580b2d1f)

I fired up the developer tools in Safari and grabbed the errors from the iPhone for you which are located on the bottom of the issue.
I can confirm that Kavita loads just fine on iOS 16 and MacOS (Safari Version 16.6 (17615.3.12.11.3, 17615))

**Additional context**
Safari error console below:

![image](https://github.com/Kareadita/Kavita/assets/52541649/7fa7f84c-748f-4c45-ac6a-d1f8c6facded)

```
[Error] ERROR – ReferenceError: Can't find variable: structuredClone — ngneat-transloco.mjs:471
ReferenceError: Can't find variable: structuredClone — ngneat-transloco.mjs:471X — ngneat-transloco.mjs:471(anonymous function) — ngneat-transloco.mjs:226:94hydrate — core.mjs:9301get — core.mjs:9189Be — ngneat-transloco-persist-lang.mjs:10(anonymous function) — ngneat-transloco-persist-lang.mjs:67:131hydrate — core.mjs:9301get — core.mjs:9189qe — core.mjs:785o — core.mjs:9394hydrate — core.mjs:9301get — core.mjs:9189qe — core.mjs:785hydrate — core.mjs:9301get — core.mjs:9189e — core.mjs:25475(anonymous function) — core.mjs:25518:113hydrate — core.mjs:9301get — core.mjs:9189(anonymous function) — core.mjs:26933S0 — core.mjs:27201onInvoke — core.mjs:26313run — zone.js:129ww — core.mjs:26909(anonymous function) — main.ts:98a — bootstrap:19(anonymous function) — chunk loaded:23(anonymous function) — main.ts:133f — jsonp chunk loading:71fModule Code — main.2bcd4216dce530c0.js:1:85evaluatemoduleEvaluation(anonymous function)promiseReactionJob
	handleError (vendor.fdebb473bab0c0f4.js:1:199359)
	run (polyfills.6fa08403dc6f65ce.js:1:1934)
	S0 (vendor.fdebb473bab0c0f4.js:1:271768)
	onInvoke (vendor.fdebb473bab0c0f4.js:1:265703)
	run (polyfills.6fa08403dc6f65ce.js:1:1934)
	ww (vendor.fdebb473bab0c0f4.js:1:271367)
	(anonymous function) (main.2bcd4216dce530c0.js:1:267007)
	a (runtime.f1eb794a37c9cc5d.js:1:133)
	(anonymous function) (runtime.f1eb794a37c9cc5d.js:1:398)
	(anonymous function) (main.2bcd4216dce530c0.js:1:267593)
	f (runtime.f1eb794a37c9cc5d.js:1:3130)
	f
	Module Code (main.2bcd4216dce530c0.js:1:85)
	evaluate
	moduleEvaluation
	(anonymous function)
	promiseReactionJob
```

```
[Error] ReferenceError: Can't find variable: structuredClone — ngneat-transloco.mjs:471
	run (polyfills.6fa08403dc6f65ce.js:1:1934)
	(anonymous function) (polyfills.6fa08403dc6f65ce.js:1:16775)
	runTask (polyfills.6fa08403dc6f65ce.js:1:2555)
	_ (polyfills.6fa08403dc6f65ce.js:1:9204)
	promiseReactionJob
```

**Comment by majora2007** [comment]
I can open an issue on the library, but I don't have any iOS device, so if you wouldn't mind doing it and linking to this issue, that would be great:
https://github.com/ngneat/transloco

I didn't see any mention for browser support.

**Comment by RobertD502** [comment]
Will do!

**Comment by RobertD502** [comment]
@majora2007 I just noticed that this was [reported ~3 weeks ago](https://github.com/ngneat/transloco/issues/688) and fixed in `5.0.7`. Looks like you are currently using [5.0.6](https://github.com/Kareadita/Kavita/blob/b5540e58e0f81e5c0c38f6717a2433d6a167b735/UI/Web/package.json#L31C35-L31C35).

**Comment by majora2007** [comment]
Perfect, that's an easy fix then. I'll take care of it.

**Comment by RobertD502** [comment]
@majora2007 Can confirm that the version bump in the latest release has fixed rendering on older Safari browsers.
