### ISSUE TITLE
Updating metadata through API is causing high CPU load.

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#2247]
**Describe the bug**
When a lot of series are updated the kavita process can max out the CPU load and take a long time to respond to endpoints. It generally takes more than 1 series to be updated in a short time to trigger this condition. I have observed a single update briefly spiking CPU to 100% (1 core maxed). But the problem surfaces more when there is a lot of files changed at the same time. 

> [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/metadata responded 400 in 427712.2389 ms

**To Reproduce**
1. Add a lot of files to a library that didn't exist before
2. Use KOMF to update series metadata
2b. Or have library events turned on for KOMF 
3. See error

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: N/A
 - Version: 0.7.7.17

**Additional context**

[logs.zip](https://github.com/Kareadita/Kavita/files/12494839/logs.zip)

**Comment by majora2007** [comment]
From the logs it looks like the cleanup is hitting an issue as Komf might have already sent another update in a different thread. I just caught the exception with a nice log message for this case. The nightly job will take care of the cleanup. The side effect is that some people might show in the typeaheads and filters as they weren't cleaned up, but again, this will happen at night.
