### ISSUE TITLE
Synology docker problem - instance reset itself and lost ability to license. Missing check button.

### ISSUE THREAD

**Issue by ryanmccool** [Kareadita/Kavita#2274]
Hi there,
I'm a relatively new user. I installed Kavita on my Synology system via the new linuxserver docker image. Yesterday, the instance crashed, and when it rebooted, it lost my user account and all settings. The settings problem was due to wrong directory assignments caused by some confusion across install directions - now resolved, though I haven't determined what caused the hard crash.

The problem is that when I try to reactivate my license, it doesn't let me because it says it is tied to another instance. The instructions say to use the check button, but that does not appear on the page. Do you have any ideas how this can be resolved? Thank you!

**Comment by majora2007** [comment]
Please email me on the email from Kavita+ with your license and I can reset you.
