### ISSUE TITLE
PDF rendering issues on text heavy magazine scans

### ISSUE THREAD

**Issue by FaberfoX** [Kareadita/Kavita#2276]
I'm having blank pages on the first few magazine scans I had Kavita ingest. I see similar issues already reported but posting anyway at @majora2007 's request.

The one with most issues is this one: https://vintageapple.org/byte/pdf/197510_Byte_Magazine_Vol_00-02_Build_a_Graphics_Display.pdf where over half the pages are blank. Switching to text selection mode and dragging over the page shows that the text is there, just not rendering properly. This happens with Kavita for Chrome on Windows 11, ChromeOS, and Android 13, Firefox on Windows 11 and Firefox Focus on Android. 

The same pdf renders properly on the above mentioned desktop browsers, on Acrobat Pro and Sumatra PDF on Windows, and on Google Drive pdf viewer and Firefox Focus on Android 13. It hangs on start for CDisplayEx 64bits on Windows.

Kavita is running on Docker under Debian 12 WSL2, happens both with the pdf residing on a docker volume mapped nfs share as with the file being local to the container. Tried both :latest and :nightly

Pages 1 to 15 - Firefox / Kavita
![image](https://github.com/Kareadita/Kavita/assets/6801510/765e3a41-e81a-49b2-8cac-07804ac14da9)

Pages 1 to 15 - Firefox native
![image](https://github.com/Kareadita/Kavita/assets/6801510/52cb970b-a5f5-4a87-b60a-110f4bb8edce)

Pages 16 to 29 - Firefox / Kavita
![image](https://github.com/Kareadita/Kavita/assets/6801510/e222025d-2441-457e-939e-3aef8a00637f)

Pages 16 to 29 - Firefox native
![image](https://github.com/Kareadita/Kavita/assets/6801510/4ae1ca0b-c309-4785-9cbc-4fdd02b12d05)

Selecting text on page 6  - Firefox / Kavita
![image](https://github.com/Kareadita/Kavita/assets/6801510/925bd89e-0dde-45a1-b6d5-2ec366978acf)

Selecting text on page 6  - Firefox native
![image](https://github.com/Kareadita/Kavita/assets/6801510/a9e71013-d5e5-46a8-8461-2b01c48ce6e8)

**Comment by DieselTech** [comment]
The PDF module has been updated a few times since this issue was created. I tested the example PDF given and did not see any problems with it displaying or selecting text. 

![image](https://github.com/user-attachments/assets/21b7c1e2-d4d8-4194-8e5e-f646e806fd7c)

If you are still having issues with displaying PDF's please open a new issue.
