### ISSUE TITLE
Partial (fractional) chapters are not showing up

### ISSUE THREAD

**Issue by brachna** [Kareadita/Kavita#2277]
**Describe the bug**
Imported chapters that have partial numbers don't show up in Chapters menu.

**To Reproduce**
1. Put CBZ archives into Series folder
2. Scan and import
3. All chapters are accessible from Chapters menu, except partial ones.

**Expected behavior**
Imported partial chapters clearly visible and accessible from Chapters menu.

**Screenshots**
![kavita_archives](https://github.com/Kareadita/Kavita/assets/5756107/ebdfa1cf-adac-42b7-8192-eb866dbc4d3f)

![kavita_chapters](https://github.com/Kareadita/Kavita/assets/5756107/6b97b41a-9141-45cd-a813-d1238a9d1606)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox
 - Version 0.7.8.0 (downloaded from Releases)

**Additional context**
CBZ archives have ComicInfo.xml inside of them.
Some info from Chapter 9.1 `<Volume>2</Volume><Number>9.1</Number><Title>Volume. 2 Chapter. 9.1</Title>`
It looks like issue in #1606, but I'm having trouble with chapters.
Also partial chapters themselves have been imported, but navigation is horrible with them.
Going from Chapter 8 to Chapter 8.5 goes as one would expect, but going from 8.5 to 9.1 navigates to 16.5.

**Comment by majora2007** [comment]
Hello, I just made a fix in another issue and I believe these are the same. 

Are you on a non-english Region for your OS? 

#2339

**Comment by brachna** [comment]
Yes, my locale is non-english.

**Comment by majora2007** [comment]
Awesome, then this issue will be solved in the next release.

**Comment by brachna** [comment]
Just confirming that this is indeed fixed now, thanks.
