### ISSUE TITLE
[Discussion] Direct intergration of CBL-ReadingList repo

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#2284]
I know this would be a big ask on your part, but I want to see what it would take for Kavita to directly fetch the reading lists stored here on github at https://github.com/DieselTech/CBL-ReadingLists

I'm in the process of revamping the repo and attempting to clean up the lists. If there is a structure or set of guidelines you would like to see I'm all ears. My goal is to have the main branch be "very stable" and changes be vetted through a different branch. That way any integrations with apps won't break. I feel like this would bring value to a lot of people by allowing them to read issues in the order the series is intended to be. Also, once it's setup as a fetch type system in kavita there wouldn't need to be any commits or changes on Kavita's end to update and maintain lists.

**Comment by majora2007** [comment]
Please create a feature request on feats hub.

**Comment by DieselTech** [comment]
Sure, I can do that. I was posting here more of a "What would you need from me" kind of thing. That way it could be tracked and actioned on by directly linking issues from the 2 repos.

**Comment by majora2007** [comment]
Yeah the thing is I don't look for new features from GitHub. I explicitly go to feature hub to find, plans, and design features.

Btw I'm not opposed to something like this. It would be a good QoL for a lot of people.
