### ISSUE TITLE
Rename Read Progress sort name to not conflict with Read Progress filter

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2285]
**Describe the bug**
As discussed in discord the Read Progress sort name is a little confusing because it orders based on when a series was last read. This would be fine on its own but conflicts with naming of the Read Progress filter which filters based upon progress within the series.

**Expected behavior**
Read Progress sort name should sort based upon progress within a series like how the filter works. Where as the current form of the Read Progress filter should be renamed to something like Last Read or something similar.

**Comment by majora2007** [comment]
I think changing the name of the Sort By from "Read Progress" -> "Last Read" would be the easiest solution. Thoughts?

**Comment by scare376** [comment]
Yeah I agree. Though I do think a Read Progress sort could be nice.
