### ISSUE TITLE
 Request chapters, volumes, and special recognition bypass within parentheses such as (,[,{

### ISSUE THREAD

**Issue by ytoaa** [Kareadita/Kavita#2286]
If you put characters in brackets, series scans typically ignore the characters inside.However, if there is a chapter, volume, or special character inside, it is recognized as a volume, special, or chapter. So I hope that even these specific characters are ignored by the scanner if they are in brackets.

**Comment by majora2007** [comment]
I wasn't able to understand what you're asking.

**Comment by ytoaa** [comment]
> I wasn't able to understand what you're asking.

If you look at the kavita wiki, I heard that the characters in the brackets are omitted when the scanner reads the files. However, this is not omitted when the characters in the brackets contain the corresponding characters for chapters, volumes, and specials.

"Important: When parsing filenames, anything between parenthesis and parenthesis themselves will be removed from the series name.
If you wish to separate series using Series Name (2019), it's advised to change parenthesis to brackets { } and change series name in the UI"

**Comment by majora2007** [comment]
Correct. This is as designed. Filename parsing ignores bracketed stuff for parsing out the series name.

If you are asking to have a way to ignore characters from filename parsing, you'll need to open a feature request on feats.kavitareader.com.

I do not look at GitHub for planning new features.
