### ISSUE TITLE
Registration Emails not Sending when using KavitaEmail

### ISSUE THREAD

**Issue by maeveuay** [Kareadita/Kavita#2288]
Debian 11, Latest Kavita Version

**Describe the bug**
Registration mails not sending on Kavita Email with Gmail set up.
It will send test emails, but registration emails do not go through.
I initially asked for help on the Discord, and some were having the same issue, and encouraged me to make this.

**To Reproduce**
1. Go to Admin Dashboard
2. Click on Invite User
3. Enter User's email and permissions, Click Invite
4. No email seen on user's side

**Expected behavior**
Registration email is received by email target

**Screenshots**
[_kavita-email_logs.txt](https://github.com/Kareadita/Kavita/files/12680967/_kavita-email_logs.txt)
Redacted Emails are my own, from hitting the Test Button under the Email tab of the Admin Dashboard.

**Desktop (please complete the following information):**
 - OS: Docker for both Kavtia and Kavita-Email
 - Browser Firefox
 - Version 0.7.8.0

**Comment by scare376** [comment]
Just wanted to add this does not just affect Gmail. I am using a different webmail host. Registration emails sent through the default url work fine. its the hosted instance that it did not work.

**Comment by majora2007** [comment]
This indicates some sort of config issue on KavitaEmail, can you grab the logs from your email instance and show them? Do any emails send? Could it be you updated from before I added the test email and the template is missing in your templates folder?

**Comment by scare376** [comment]
So just tried something and turns out my issue was that KavitaEmail wasnt able to read the templates folder updated permissions and it works fine. For some reason it was able to send the test email fine which is weird.

**Comment by majora2007** [comment]
@maeveuay could you check your templates folder please? This is likely the issue.

**Comment by maeveuay** [comment]
Yeah, it was a permissions issue, fixed!
