### ISSUE TITLE
Insufficient Failed Login Detail in Logs 

### ISSUE THREAD

**Issue by wilsoniain** [Kareadita/Kavita#2291]
Logs do not show failed login attempt in enough detail. This won't allow use of Fail2ban etc.
Checked Debug, Warning, Critical log type.

**To Reproduce**
View logs after failed login. Debug shows login issue but not captured in detail. 

E.g. "[Kavita] [2023-09-24 05:02:41.446 +00:00  25] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP OPTIONS / responded 200 in 1.2009 ms"

**Expected behavior**
Possibly Warning log would have clear indication of failed login with IP address. Maybe also require some option for IP forwarding of using reverse proxy.

**Additional context**
Linux X64

**Comment by majora2007** [comment]
I can add a few log statements when we reject a login request.
