### ISSUE TITLE
Getting 400 error when reading

### ISSUE THREAD

**Issue by earth4s** [Kareadita/Kavita#2293]
I am getting a "400 Error There was an issues saving progress" when I am reading comics/manga. It's random and happens with both old and recently added items. The series still keeps place and the only affect is the progress bar on the manga/comic cover does not appear. I have not seen this issue with ebooks yet.

1. Happens randomly when reading a comic book or manga volume.

**Screenshots**
![400 error](https://github.com/Kareadita/Kavita/assets/9957002/a1329778-1774-4033-a998-8a8b88df753c)

**Desktop (please complete the following information):**
 - Server OS: Rocky Linux 9
 - Reading OS: Fedora 38,
 - Browser: Chrome
 - Version: 117

 - Reading OS: ChromeOS 116
 - Browser: Chrome
 - Version: 116

**Comment by earth4s** [comment]
Logs:
[kavita20230924.log.txt](https://github.com/Kareadita/Kavita/files/12710570/kavita20230924.log.txt)

**Comment by scare376** [comment]
Try the steps here at the bottom of the page under the database is locked errors question. https://wiki.kavitareader.com/en/faq

**Comment by earth4s** [comment]
I'll test it out and report back tomorrow.

**Comment by earth4s** [comment]
It looks like the fix on the FAQ worked. 

I think the "400" error should be more clear on what was happening to cause the error. While I feel comfortable with messing with the DB file I think this  fix should be a toggle option in the settings panel. Or to keep things clean, have it an line in the Kavita config file.
