### ISSUE TITLE
Not Contains doesn't appear to work for Tags or People

### ISSUE THREAD

**Issue by CianH** [Kareadita/Kavita#2296]
**Describe the bug**
Filtering using Not Contains doesn't work for Tags or People. It does work for Genres and Collection Tags.

**To Reproduce**
1. Have a series (e.g. `Series1`) with multiple tags (e.g. `tag1`, `tag2`)
2. From the library screen, show the filter view
3. Tap to add a new filter clause, select Tags
4. Select Tags, Not Contains, `tag1`
5. Result will contain `Series1`

**Expected behavior**
Results should not contain `Series1`, as it has `tag1` as a tag - it should only return series without `tag1`

**Desktop:**
 - OS: Docker
 - Browser: All (Edge, Safari)
 - Version: 0.7.8.0

**Additional context**
Similar steps can be used with People, e.g. Writers. Selecting `Contains` or `Not Contains` returns the same results. Both of the following return the same CLOVER series.
![image](https://github.com/Kareadita/Kavita/assets/1442396/29973bb0-223b-4869-8848-538455698c60)
![image](https://github.com/Kareadita/Kavita/assets/1442396/db6d239a-c911-40ba-ae6f-bf603f70774f)

Looking through the code, I think part/all of the issue is in `API/Extensions/QueryExtensions/Filtering/SeriesFilter.cs` - the code for Tags and People differs from Genres and CollectionTags.

Genres: `return queryable.Where(s => s.Metadata.Genres.All(p => !genres.Contains(p.Id)));`
CollectionTags: `return queryable.Where(s => !s.Metadata.CollectionTags.Any(t => collectionTags.Contains(t.Id)));`

`!Any` being equivalent to `.All(!)`. But for tags, it's `Any(!)`.

Tags: `return queryable.Where(s => s.Metadata.Tags.Any(t => !tags.Contains(t.Id)));`
People: `return queryable.Where(s => s.Metadata.People.Any(t => !people.Contains(t.Id)));`

I wasn't able to find UTs for this and had a hard time writing a new one not being that familiar with your codebase, so didn't want to push a PR without being able to validate.

**Comment by majora2007** [comment]
Thanks for the detailed issue. There aren't any unit tests because I was too lazy to write them, but I think you might have found it. I would welcome a PR if you're up for it, otherwise I'll get to it sometime in this upcoming release.

**Comment by CianH** [comment]
No problem on the UTs. Submitted the PR with the quick fix for now. 
I tried briefly adding some but had difficulty understanding how to "seed" the db to have a series with the requisite tags from the series filter tests similarly to how you've done it in the SeriesServicesTests.

**Comment by majora2007** [comment]
Yeah, I usually do a builder pattern. It's a bit hard to construct all the seed data. I wanted to have some mocked up files as Test data then point the scanner on it so that I can test with more realistic data to make it much easier, but it's a lot of work and hard to work on tests with new ideas floating around. 

Thanks again for the PR.
