### ISSUE TITLE
Inaccessible Server

### ISSUE THREAD

**Issue by angelfire76** [Kareadita/Kavita#2299]
**Describe the bug**

After extracted Kavita folder to my Desktop, I've started Kavita.exe and created account on localhost, but can't access the account. I keep getting this error:
Your credentials are not correct 

I've added the port and the exe to the Inbound/Outbound Rules in the Windows Firewall. I've tried it on Brave Browser and got the same result. 

When I try to change the pass, I'm getting this error:
Your server is not accessible. The link to reset your password is in the logs 

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Firefox
 - Version: 118.0.1 (64-bit)

Thanks.

**Comment by majora2007** [comment]
This means you are doing the password reset flow from localhost. So Kavita can't email a link that is guaranteed to work.

Open the logs in conf/logs and you'll see the link you need to put in your browser.

**Comment by angelfire76** [comment]
> This means you are doing the password reset flow from localhost. So Kavita can't email a link that is guaranteed to work.
> 
> Open the logs in conf/logs and you'll see the link you need to put in your browser.

Yeah. When I copy the link from the command line/logs, I can change it but still can't login.
[Kavita] [2023-10-03 07:29:27.203 +03:00  48] [Fatal] API.Controllers.AccountController [Forgot Password]: Email Link for Username: localhost link

Am I doing something wrong or missing at the first setup?

**Comment by majora2007** [comment]
Extremely likely. Let's start over from scratch as you haven't done anything yet.

Walk me through your setup and what you did.

**Comment by angelfire76** [comment]
> Extremely likely. Let's start over from scratch as you haven't done anything yet.
> 
> Walk me through your setup and what you did.

1. Grabbed kavita-win-x64.tar.gz file from the releases
2. Extracted it to the Desktop
3. Double clicked Kavita.exe and saw that line in the CLI:  
[Kavita] [2023-10-03 14:36:39.685 +03:00  1] [Information] Microsoft.Hosting.Lifetime Now listening on: http://[::]:5000
Kavita - v0.7.8.0
4. Opened localhost:5000 at Firefox
5. There is an error occured in the site but no logs for it: toasts.unauthorized-1
6. Created an account through this page and got "Account registration complete" info: http://localhost:5000/registration/register 
[Kavita] [2023-10-03 14:42:14.410 +03:00  49] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/admin/exists responded 200 in 1.8923 ms
7. Got "Your credentials are not correct" error when I try to login 
8. Clicked "Forgot Password"
9. Changed it but got this error: "Your server is not accessible. The link to reset your password is in the logs"
10. Pasted the link in the logs and changed the password.
11. Tried to login again and got the same error at 7th step

**Comment by majora2007** [comment]
Hmm very strange. I just can't imagine how the password can't be correct from your registration step to when you fill it in? 

Maybe move the Kavita folder elsewhere and try again? It really sounds like when you're entering the password, it's being typed in wrong.

**Comment by majora2007** [comment]
Closing this issue as no response. If you need further help, reply or join the discord.
