### ISSUE TITLE
Value was either too large or too small for an Int32.

### ISSUE THREAD

**Issue by Seulxy** [Kareadita/Kavita#2302]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**

**To Reproduce**
1. load equb 
【On Durkheims Rules of Sociological Me... (Z-Library).epub】
https://1acc9ff7e3.znas.cn/AppH5/share/?nid=LIYDIMJQGEYDEQKOKFATM&code=wSrfidBc8PQNLg9y7ITNbIkpem1Rzcm2Qe0AjSdnNUXvm3e60dFeNxHTp7GGlEvAZHm1&mode=file&display=list
2.it say 400 can't find html
3. See error

**Expected behavior**
not wrong again

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/51233036/ef3e7824-8f4f-42f2-9f06-78261ed93b0c)

**Desktop (please complete the following information):**
 - OS Docker
 - Browser chrome
 - Versionlatest

**Comment by majora2007** [comment]
Please attach your logs

**Comment by majora2007** [comment]
I also need how to reproduce it on the file in question. What page is this happening on? What are the reader settings?

**Comment by Seulxy** [comment]
> 我还需要如何在有问题的文件上重现它。这是在哪个页面发生的？阅读器设置是什么？

<img width="1069" alt="截图_20231006091209" src="https://github.com/Kareadita/Kavita/assets/51233036/c7eaf3be-973e-4fae-9dba-59b49cc19f63">
It happen in almost the entire file(sometimes I can read the directory). and that's my settings. 

https://drive.google.com/file/d/15b1a2YNH4VtQ34jVesxGhUORHUdkTb_A/view?usp=drive_link, https://drive.google.com/file/d/1y2GZob5de7RDNqg_2j94kEohuWCQYYAQ/view?usp=drive_link

**Comment by majora2007** [comment]
I can't reproduce this issue. I am able to read the book just fine. Is there anything more I need to know, like what page this error is thrown on?
