### ISSUE TITLE
Filtering: Matching on Publisher or Libraries not returning correct results

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#2305]
**Describe the bug**
Trying to set filtering options to match either `Publisher` or `Libraries` doesn't return expected results. Start of the [conversation on discord](https://discord.com/channels/821879810934439936/851515194185744464/1160660512309252178) starts here: 

**To Reproduce**
1. Setting match rule to "Match any of the following"
2. Publisher = Marvel
3. Publisher = DC Comics
4. [Results contain publishers that are outside of the conditions selected](https://media.discordapp.net/attachments/851515194185744464/1160665057370325133/image.png?ex=65357c91&is=65230791&hm=4be5e43127d1273b7ab093e7eb1126f8dd55a9dce5ee0e17ad3fabf5e8643e78&=)

Different Example:
1. Setting match rule to "Match any of the following"
2. Publisher "Must Contain" = DC Comics, Marvel
3. [Results show no matches](https://cdn.discordapp.com/attachments/851515194185744464/1160665302623866991/image.png?ex=65357ccc&is=652307cc&hm=a44594d19d0f8763a2f9625f743ee051bbb15371e6e164f152fd4073717e1425&)

Different Example 2:
1. Setting match rule to "Match all of the following"
2. Libraries `Equal` = DC Comics
3. Libraries `Equal` = Marvel
4. [Results show all kind of different libraries not wanted](https://cdn.discordapp.com/attachments/851515194185744464/1160666520792342588/image.png?ex=65357dee&is=652308ee&hm=b699346e2ce8e6de30397b12e3db64f6f73b837b4b3f3472b3a1514bd39ec323&)

Different Example 3:
1. Setting match rule to "Match any of the following"
2. Libraries `Equal` = DC Comics
3. Libraries `Equal` = Marvel
4. [Results seem to show all the series that are in the entire server ](https://cdn.discordapp.com/attachments/851515194185744464/1160666651042259127/image.png?ex=65357e0d&is=6523090d&hm=d9e44d8fcf5840ab1648e5e2f40452f56ba576e8b691dada6aacc58c2612695a&)

Additional Info:
There doesn't seem to be a "Must Contain" for the libraries selection. 

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Version: 0.7.8.7

**Comment by majora2007** [comment]
For your first attempt, I think you're looking for all series that have either A or B publisher, which can be done like:
![image](https://github.com/Kareadita/Kavita/assets/735851/1e7157c3-0553-40c1-a3c0-50d38ae8bfde)

Contains is the correct way to handle what you need. Must Contains doesn't make sense. For example, a Series only belongs to 1 library, so if you used Must Contains, then it would always fail, because a series will never have more than 1 library link.
