### ISSUE TITLE
Comic issue with "Special" as part of series name gets treated as specials

### ISSUE THREAD

**Issue by osclju** [Kareadita/Kavita#2308]
Windows 11

A comic series, in my case a singular issue called for example "Tales of Comic Special" instead of being parsed as a issue of the series "Tales of Comic Special" gets listed as an issue of "Tales of Comic". The "Special" gets removed from the series name.

**To Reproduce**
1. Add a comic book bearing special in the name such as "Tales of Comic Special #/01 (2008).cbr"
2. Scan library
3. Comic gets listed as "Tales of Comic"

**Expected behavior**
It should be possible to keep the special as a part of the series name in cases where it is not a special of a specific series and instead just part of the name of the issue/series.

**Comment by majora2007** [comment]
This is a bit of a hard one as normally the word special gets removed from series names and that issue gets treated as a special. In this case, you have poor filenames thus folder parsing is taking place and it's seeing the series and likewise, it's going through the same code to clean the series, thus stripping the word special.

As a workaround currently, you can just use embedded metadata to write the <Series> tag as "Tales of Comic Special", which Kavita will take as source of truth.

**Comment by danmarce** [comment]
Oh, I just installed it and noticed this with a series called "Special A". There a few manga with "Special" in the name .

Will check what I can do with metadata.

**Comment by DieselTech** [comment]
Discussion around special keyword removal: https://github.com/Kareadita/Kavita/issues/2967
