### ISSUE TITLE
ePub Reader: tap to paginate goes to next chapter instead of page

### ISSUE THREAD

**Issue by refactoriel** [Kareadita/Kavita#2315]
**Describe the bug**
Tapping the tap zones in ePub Reader jumps to next chapter.

**To Reproduce**
1. Open ePub
2. Tap on tap zone

**Expected behavior**
The reader jumps to next page in the ePub.

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 14
 - Browser Vanadium

**Comment by scare376** [comment]
What layout mode are you on? Column mode will create virtual pages that you can paginate on. In scroll mode pagination will move to the next full page which may be an image/new chapter.

**Comment by refactoriel** [comment]
Gosh, layout move is "scrolling". Sorry for the noise.

I was evaluating Kavita via the demo instance. If "scrolling" is the default for the instance, maybe it might be worth considering changing it to "1 column".
