### ISSUE TITLE
Changing E-mail for Admin account not working

### ISSUE THREAD

**Issue by LostSystems** [Kareadita/Kavita#2317]
**Describe the bug**
When changing the e-mail address of the Admin account, it will either send the invite link to the old e-mail and nothing will change or give an error of "Something unexpected went wrong."

Upon validating the request if received, it will redirect back to the server, already logged in and the e-mail stays the same. Rebooting and trying again doesn't change results.

E-mail services were confirmed working before doing this.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Account Name > Settings > Account
2. Click on 'Edit' in the Email category
3. Enter an e-mail address different than the one already used and confirm password
4. Check e-mail. Either the request was sent to the old e-mail or not received at all

**Expected behaviour**
E-mail address of Admin account should be changed to the new e-mail and would have to be verified and log in again upon redirect.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: FireFox
 - Version: 0.7.8.0

**Comment by majora2007** [comment]
Is this using the out of the box KavitaEmail service or your own? 

Do note, there is a reset link that is logged to config/logs ALWAYS for any of these flows. 

Also, how are you accessing the kavita interface? If it's via localhost or private IP, Kavita will not send an email (and should prompt you about that). Only when accessed via reverse proxy or if you have Host set under Email, will an email always be sent.

**Comment by LostSystems** [comment]
This is the out of the box service. I'm using an NGINX reverse proxy, accessing the interface through my domain and the host name is set as the domain as well. The e-mail does send, but it's to the old e-mail and doesn't transfer to the new one.

**Comment by majora2007** [comment]
I'll take a look into this.

**Comment by majora2007** [comment]
I took a look. It is supposed to send to the old email, there is a link, you click it and it confirms the switch. This is a security measure to ensure that if someone gets access to your account can't just change the email and hijack your account. You have one extra layer of security. 

I did see the toast message wasn't correct and thus didn't render out the message telling you to check your old email (this is a missed key from the big localization support).

**Comment by LostSystems** [comment]
Apologies, I see where I went wrong in my description.

I know the e-mail is sent for verification as a security measure, it just sometimes didn't send it at all. But, once the e-mail is verified and it notifies me to login once it redirects, the e-mail is still not confirmed in the admin panel and also under Users it claims it's pending.

I did notice before updating to the newest release my admin e-mail was stuck on the old one, but post-update was correct just still said unconfirmed. I was also able to get the e-mail to send to two different e-mails for testing and were able to verify, albeit still having the issue I explained above with confirmation.

**Comment by majora2007** [comment]
I just tested this flow and I used the link dumped in the logs and was able to successfully change my email. It reflected instantly as the updated email. 

I did receive the email, however, it looks like the template it chose was wrong (which I will fix). So I can't reproduce this.

**Comment by majora2007** [comment]
Fixed the email service not having the correct template:
https://github.com/Kareadita/KavitaEmail/releases/tag/v0.1.23.0
