### ISSUE TITLE
Corrected classification error and cannot be identified by scanning

### ISSUE THREAD

**Issue by murazi** [Kareadita/Kavita#2326]
When I find a book in the wrong folder, I delete the file, put a book in the right folder, the book can't be scanned again, even if I use Force Scan, it can't be recognized.

Version
0.7.8.0

**Comment by scare376** [comment]
What type of file is it?

**Comment by scare376** [comment]
Also what does the folder structure look like? If you moved the file from a subfolder to the library root it will never be picked up because the scanner skips all items at library root.

**Comment by murazi** [comment]
> Also what does the folder structure look like? If you moved the file from a subfolder to the library root it will never be picked up because the scanner skips all items at library root.

![image](https://github.com/Kareadita/Kavita/assets/4424520/295491ef-6cad-4d2b-ba6f-44d1410a9ba2)

This is my background error, I found that there are several books that cannot be identified, the question refers to this record

`EPUB	/books/book/国学文化/白话易经_1993.epub	There was an exception when opening epub book	Incorrect EPUB manifest: item with href = "css/main.css" is not unique.`

My e-books are all specified in this directory `/books/book/`

```
EPUB	/books/book/国学文化/白话易经_1993.epub	There was an exception when opening epub book	Incorrect EPUB manifest: item with href = "css/main.css" is not unique.
EPUB	/books/book/国学文化/《道德经[精品]》.epub	There was an exception when opening epub book	Data at the root level is invalid. Line 1, position 1.
EPUB	/books/book/国学文化/拾遗记（全本全注全译）.epub	There was an exception when opening epub book	An XML comment cannot contain '--', and '-' cannot be the last character. Line 42, position 56.
EPUB	/books/book/国学文化/花间集.epub	There was an exception when opening epub book	An XML comment cannot contain '--', and '-' cannot be the last character. Line 54, position 72.
EPUB	/books/book/宗教与信仰/论语新解.epub	There was an exception when opening epub book	Incorrect EPUB manifest: item with href = "css/main.css" is not unique.
EPUB	/books/book/武林/大唐乘风录 (金寻者) (Z-Library).epub	There was an exception when opening epub book	Incorrect EPUB manifest: item with href = "Styles/main.css" is not unique.
EPUB	/books/book/武林/逝去的武林.epub	There was an exception when opening epub book	Incorrect EPUB manifest: item with href = "Styles/main.css" is not unique.
EPUB	/books/book/心理学/命的礼物：关于爱、死亡及存在的意义.epub	There was an exception when opening epub book	Incorrect EPUB manifest: item with ID = "image" is not unique.
EPUB	/books/book/情感/被遗弃的日子.epub	There was an exception when opening epub book	EPUB parsing error: NAV item not found in EPUB manifest.
```

**Comment by scare376** [comment]
I think all those errors are fixable with calibre by converting into epub again. The image itself doesnt really help me understand the original issue you brought up it looks like you're just deleting a book and replacing it with a copy of the same book. Is the folder you selected in kavita for your ebook library /books/ or /books/book

**Comment by murazi** [comment]
I also think it may be a cache problem with the previous book, and if so, how do I fix it (do I need to delete the cache for this book?）？About the above error log, I can roughly understand that the book conversion may be incomplete, or the format is not rigorous, this I will find a solution from the book source ~

**Comment by scare376** [comment]
Shouldn't be a cache problem Kavita doesn't store books that way. It could be a metadata issue where its appearing under the wrong information. If the books with errors are the same books you're moving around then they are not going to appear until the errors are corrected.

**Comment by majora2007** [comment]
Please share logs and full file paths to help us understand.

**Comment by majora2007** [comment]
Closing as no information was provided to continue support. You can provide the information and I will reopen the issue.
