### ISSUE TITLE
Read Progress is not capped at 100

### ISSUE THREAD

**Issue by CianH** [Kareadita/Kavita#2327]
**Describe the bug**
It looks like it's possible to have a read progress greater than 100%. I'm not sure how exactly I got into this state, but currently, when filtering to `Read Progress` `Greater Than` `100`, I get some results. 
Inspecting the SQLite file and looking a bit at the code that computes the ReadProgress, I assume it's calculated using the equivalent of SUM(PagesRead) from AppUserProgresses, divided by the Pages number in Series?

Inspecting the values for one of the series that is exhibiting the issue on my server, I'm getting 685 pages read out of a possible 664. Should Read Progress be using MAX(100, <current_calculation_logic>) or is there a scenario where you'd need to support > 100% progress? My repro steps here won't be great since I don't actually know how I got into this state - perhaps adding / removing / replacing volumes and chapters after reading over time?

**To Reproduce**
1. In a server that's been around for a while, read lots of chapters / volumes, completing several series.
2. Attempt to filter to Read Progress equal to 100
3. Notice some "completed" series missing.
4. Filter instead to Greater Than 100
5. Missing Series appear

**Expected behavior**
Series completely read should have a Read Progress of exactly 100, not anything over 100.

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/1442396/a558341f-d87a-4a1f-b801-e71452c54054)
![image](https://github.com/Kareadita/Kavita/assets/1442396/538fd566-d66f-417c-b45a-2972fd6c8903)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Edge
 - Version: 0.7.8.0

**Comment by majora2007** [comment]
This type of page difference I believe happens when a volume or chapter is replaced while the existing exists, which Kavita merges them, then you remove one. The progress you've already had can exceed the actual total pages of the underlying chapters.

I think I'll tackle this in another area of the code so that the filter doesn't have a hack, but rather the underlying issue is fixed.

**Comment by majora2007** [comment]
I decided to tackle this by setting up a nightly task (part of the cleanup task) to just normalize and bring each user's progress inline with the replaced chapter. This ensures the 100% caps and the new feature (Series progress within the manga reader) both don't go out of bounds.
