### ISSUE TITLE
Login page not forwarding to libraries

### ISSUE THREAD

**Issue by Realexa** [Kareadita/Kavita#2328]
[kavita_logs_10_23_2023.zip](https://github.com/Kareadita/Kavita/files/13078817/kavita_logs_10_23_2023.zip)

**Bug description**
After entering login details, a popup with red cross appear in bottom right but without error message.
Checking the server log, the user is listed as having logged in successfully.
However the user is stuck at login page. 
When editing the url and adding /libraries you will get to the Kavita library without issues.

**To Reproduce**
1. Go to hosted comic server domain or IP
2. Log in
3. Get an error
4. Editing URL and add /libraries will give access

**Expected behavior**
Forwarding from the login page after entering credentials to /libraries

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome and Edge
 - Version of Kavita: 0.7.8.0

**Smartphone (please complete the following information):**
 - Device: Oneplus phone
 - OS: Android 13
 - Browser: Chrome
 - Version of Kavita: 0.7.8.0

**Comment by majora2007** [comment]
Can you please attach logs?

**Comment by majora2007** [comment]
I talked to a user in support yesterday that had a similar issue and they busted cookies/cache and it suddenly worked. Can you validate that for me?

**Comment by Realexa** [comment]
> I talked to a user in support yesterday that had a similar issue and they busted cookies/cache and it suddenly worked. Can you validate that for me?

Just cleared cache under tasks (bust cache, reading cache and want to read), that did not fix it. Are there other caches I should clear?

Maybe issue related: I noticed the Statistics tab doesn't work for me anymore. Just stays on the active screen. Could be a related forward issue?

**Comment by Realexa** [comment]
> Can you please attach logs?

Logs attached now.
Sorry for late reply, just moved house and still lots to do (issue was existing before moving btw)

**Comment by majora2007** [comment]
Sorry, I meant to clear your browser cookies and cache.

Also, you will want to update to the latest Kavita (v0.7.9). The statistic tab bug is fixed in that version along with massive other features.

**Comment by Realexa** [comment]
> Sorry, I meant to clear your browser cookies and cache.

Tried that and still same issue.
Same issue on Chrome (tried mobile, tablet and PC) aswell as on Edge (laptop)

 > Also, you will want to update to the latest Kavita (v0.7.9). The statistic tab bug is fixed in that version along with massive other features.

I'm using Unraid and the repositories there are often slightly behind. I did notice there are other repositories for Kavita now, so may be able to switch if i can manage that without losing the database and everything.

**Comment by majora2007** [comment]
I think you'll still need to move from the old docker repository to the new one (jvmilazz0/kavita). That is where the v0.7.9 release was deployed. 

I looked through your logs. What I'm seeing is mainly 'database is locked' which can be solved with:
https://wiki.kavitareader.com/en/faq#q-im-seeing-database-is-locked-errors-in-my-logs

Otherwise, the link for forgot password is generating. I did see a // in it, which you'll have to change to / when you put in your url (I will fix this in next release). 

Otherwise, everything feels right. 

Would you create a temp account for me with access to no libraries on your server and I can see if I can reproduce the issue?

**Comment by Realexa** [comment]
> I looked through your logs. What I'm seeing is mainly 'database is locked' which can be solved with: https://wiki.kavitareader.com/en/faq#q-im-seeing-database-is-locked-errors-in-my-logs

I did do the WAL thing somewhere last month as i got errors while reading, something that it couldn't write progress. Encountered some trouble to get it done but think i did manage in the end, errors i had in the reader are gone anyway.

> Otherwise, the link for forgot password is generating. I did see a // in it, which you'll have to change to / when you put in your url (I will fix this in next release).

Weird, not had any issues with emailing password resets.

> Would you create a temp account for me with access to no libraries on your server and I can see if I can reproduce the issue?

Just invited you using your gmail account. Thanks for the support!

**Comment by majora2007** [comment]
I figured it out. You have a theme that is named incorrectly, which is causing the code to break. 

"Themes_Native Themes_E-Ink_e-ink.css" theme has a space in it, which it cannot have. Thus it's breaking the code which runs after login. The login works, but Kavita cannot setup the theming system properly. 

I can add some extra logic in the Theme scanner to reject files with spaces, as they aren't supported, in the next release.

**Comment by Realexa** [comment]
I deleted the Theme and set theme to the default for my user. After that i logged out, reset cache and tried again.
Still getting the same issue.
Is that to be expected? Or do i have to wait for a future version with the fix?
Thanks!

**Comment by majora2007** [comment]
Did you also rescan the themes? Because that's required to remove it from the database.

**Comment by Realexa** [comment]
> Did you also rescan the themes? Because that's required to remove it from the database.

yes i did. Also restarted Kavita.

**Comment by majora2007** [comment]
It seems your server is down now. I'll check in after work today to continue debugging.

**Comment by majora2007** [comment]
I just took a look again, please see the theme is still there:
![image](https://github.com/Kareadita/Kavita/assets/735851/266ef9fa-fb5e-4d2f-a3a1-b1e5dc8667d1)
Note that the filename of the theme should be the selector minus the bg-. 

https://wiki.kavitareader.com/en/guides/settings/themes

**Comment by Realexa** [comment]
Seems i misunderstood you, i thought only the e-ink theme was an issue and deleted just that.
Didn't notice a space in the other one but now i deleted both, did a rescan and set the standard one, it works as it should.
Thanks again for the help!

**Comment by majora2007** [comment]
Glad we got it figured out. I've already made modifications to prevent this issue for Kavita v0.7.10. Appreciate you working with me to find the root cause. 

Please don't forget to update your container repo to get the latest version + future ones.
