### ISSUE TITLE
Link to scanner docs on "Managing your files" page is broken

### ISSUE THREAD

**Issue by tmzhuang** [Kareadita/Kavita#2330]
![image](https://github.com/Kareadita/Kavita/assets/1159725/796bb063-4842-4b7e-b82a-b6848b3163f6)
The above link from https://wiki.kavitareader.com/en/guides/managing-your-files give 404 but I presume it should link to https://wiki.kavitareader.com/en/guides/managing-your-files/scanner. I couldn't find the docs in the project or I would have submitted a PR instead.

**Comment by DieselTech** [comment]
Fixed. Thanks for pointing that out.
