### ISSUE TITLE
Firefox rendering of fonts are not very readable (kavita 0.7.8-0)

### ISSUE THREAD

**Issue by tmzhuang** [Kareadita/Kavita#2331]
Not too sure if this is a Firefox issue or something that can be done from within Kavita.

PDF rendered on Firefox:
![image](https://github.com/Kareadita/Kavita/assets/1159725/8b60afec-88df-4995-a9c2-553f30e018e3)
![image](https://github.com/Kareadita/Kavita/assets/1159725/9d157060-5698-4e1a-829a-4477f20f20bc)

PDF rendered on Chromium:
![image](https://github.com/Kareadita/Kavita/assets/1159725/c49b110b-450d-4804-9e2c-fca24dda0e8a)
![image](https://github.com/Kareadita/Kavita/assets/1159725/e0a03ce6-12c7-4bee-b292-4c0c7c5223ee)

**Comment by tmzhuang** [comment]
#1523 Didn't realize there was a generic issue for PDF rendering already.

**Comment by majora2007** [comment]
That issue is for feedback on features you want from the PDF reader. This issue is likely not fixable by Kavita, but you could raise an issue with PDF.js which is Mozilla's (Firefox) library that Kavita uses.

**Comment by tmzhuang** [comment]
Does Firefox not use the same PDF.js to render PDFs? When I open the PDF directly in firefox it renders okay.

File opened in Firefox directly:
![image](https://github.com/Kareadita/Kavita/assets/1159725/43427bc0-6679-4093-b15b-cb2742c217d9)


Kavita in Firefox:
![image](https://github.com/Kareadita/Kavita/assets/1159725/44179909-a981-4b6d-b6ca-c5b9cc9629fc)

**Comment by majora2007** [comment]
Interesting, then I think this might be with the library I use. 
https://github.com/stephanrauh/ngx-extended-pdf-viewer

Would you open an issue with them please? Sorry to put you on a wild goose chase, but I use this library which has a custom fork of PDF.js. The maintainer is extremely active and seeing that it renders fine in base FF, will likely prompt him to fix the issue.

**Comment by tmzhuang** [comment]
Okay so after creating a simple Angular app with ngx-extended-pdf-viewer, and then subsequently using pdf.js to display the same pdf file, I found that the behavior is the same across all three (Kavita, ngx-extended-pdf-viewer, pdf.js). So my problem isn't solved but at least I know it's not a problem with Kavita :')

I still get good pdf rendering with Firefox's (Mozilla Firefox 118.0.2) built-in pdf-viewer . Not too sure where the difference in behavior is coming from.

**Comment by tmzhuang** [comment]
I filed https://github.com/mozilla/pdf.js/issues/17149 on pdf.js to see if anyone there can help point me in the right direction.

**Comment by majora2007** [comment]
Very interesting results. I think filing a ticket on PDF.js will likely result in some win.
