### ISSUE TITLE
Extra chapters acting as chapter 0/first chapter of the volume

### ISSUE THREAD

**Issue by chilliwow** [Kareadita/Kavita#2339]
**Describe the bug**
I have an issue with "extra chapters" such as Chapter x.1, x.2, x.5, etc. When I go to read a Manga for the first time, or if I want to continue where I left off previously, it doesn't start from, let's say Chapter 2, it starts from Chapter 6.5, and if I go into the Details of said chapter, it tells me that it's Chapter 0, and thus it acts like the first chapter of the volume/book.

It's the same with or without ComicInfo, but for this case, I'm explaining the issue without Volume/Chapters set in ComicInfo and just in the filename itself.

**To Reproduce**
1. Make a new series folder in your root folder
2. Put 2 new archives *(.cbz)* without ComicInfo.xml in the new series folder (It can be more than 2, it's just for simplicity sake, it acts the same with any number of chapters)
3. Name one archive **"[series name] Vol. 1 Ch. 1"** (It's the same regardless of volume and chapter number, replace 1 with any number)
4. Name another archive **"[series name] Vol. 1 Ch. 1.5"**

**Expected behavior**
Expected behavior is just normal behavior, I want the chapter to act as an extra chapter, not as Chapter 0/First chapter of volume.

**Screenshots**

Screenshot 1 shows Chapter 6.5 acting as the first chapter of the series, or "Chapter 0".
![1](https://github.com/Kareadita/Kavita/assets/31785430/8bbaceaf-e4cc-466c-8b4f-7ed968c1a039)

Screenshot 2 shows the exact same file, but with Volume 1 added in the filename. It changes the Volume cover to the cover of Chapter 6.5 instead of Chapter 1, and also just says "Continue Vol 1" and jumps to chapter 6.5 instead of continuing off where I previously left off, in this case, Chapter 2.
![2](https://github.com/Kareadita/Kavita/assets/31785430/956cc841-bc4d-4b80-98f8-69cffa1b59c8)

**Desktop:**
 - OS: Windows 10
 - Browser: Brave
 - Version: 0.7.9.0

**Additional context**
As stated at the top, you can either have the Volume/Chapter number in the filename, or in [ComicInfo.xml](https://i.imgur.com/1XsMklv.png), it acts the same way.

**Comment by chilliwow** [comment]
To add to this, I tried it on a fresh install of the newest version of Kavita (0.7.9.0), on another computer, this time Windows 11. The issue persists no matter what I do.

**Comment by majora2007** [comment]
Based on conversation with user in discord, this is due to Sweeden Locale. 
CultureInfo currentCulture = Thread.CurrentThread.CurrentCulture;
https://stackoverflow.com/questions/4208244/get-current-language-in-cultureinfo

I can change the code to be current locale aware or change the parsing code from ComicInfo during cleaning. 

User reported the issue fixed when switching to US OS Locale. Their OS was presenting 6.5 as "6,5" to ComicInfo. 

I've already added some cleaning in v0.7.9.1.

**Comment by majora2007** [comment]
I'm not sure if you're able to test this issue on the latest nightly, but I have put code in to fix the underlying locale issue.

**Comment by majora2007** [comment]
You can find a build of the nightly here:
https://we.tl/t-mVJLW0Tuo6

**Comment by chilliwow** [comment]
The issue persists even after trying it with the nightly build. It only works when I change my Regional format to something other than Swedish. (United States) in this case.
![image](https://github.com/Kareadita/Kavita/assets/31785430/4a82b1c7-98e5-40c1-93af-6cb4b15e3c6c)
![1](https://github.com/Kareadita/Kavita/assets/31785430/dc59035a-6ebb-4a83-b9e4-f7c921d2cec2)

The log error doesn't mention ComicInfo this time, so it seems to be something else causing it.

Logs: [kavita20231025.log](https://github.com/Kareadita/Kavita/files/13170738/kavita20231025.log) (Error starts at line 553)

**Comment by majora2007** [comment]
Thanks for showing me this regional format. I can now test this myself easily. 

It's likely that it's throughout the codebase, I think I'll need to do a deeper investigation.

**Comment by majora2007** [comment]
Please try this build. I tested it on my system and everything seemed correct. It was quite an extensive change to the code.

https://we.tl/t-a6y61ipLzd

**Comment by chilliwow** [comment]
Tried it, everything is the same except for the errors. I'm getting no errors this time but the behavior is still the same. I'm down to hop on a Discord call and show everything that's going on from my point of view if that's something that might help show the process of reproducing it.

**Comment by chilliwow** [comment]
I tried it on a Windows 10 virtual machine that I setup as the Region United States and English (United States) as the Regional Format. But once I change the Regional Format to English (Sweden), or Swedish (Sweden), the issue persists.

Keep in mind that changing the "Country or region" to Sweden does not change anything, it's only the "Regional format".
![image](https://github.com/Kareadita/Kavita/assets/31785430/7f937c67-0fd6-4a31-a0ac-8e853bf6d300)
![image](https://github.com/Kareadita/Kavita/assets/31785430/9ecd04af-1d8d-498a-89a2-64fb35e54547)

I've tried the build on 2 different systems now and it's the same, so I don't really know how it's working for you. Make sure you're testing it by changing the Regional format and not just the country/region.

**Comment by majora2007** [comment]
Are you using comicInfo at all for these partial or is it just from parsing the filename?

**Comment by majora2007** [comment]
I tagged one of the files with `<Number>1.2</Number>` and got the correct issue number on the latest nightly tagged. I did a scan series to ensure it picked up the changes. 

Note the format for the OS which is how the Sweden Region shows. 

![image](https://github.com/Kareadita/Kavita/assets/735851/cd549bf7-0511-42b9-a4e1-b1d0bfc09cea)

Please give me another test. 🤞

**Comment by majora2007** [comment]
We got it! ❤️ This will be in the next nightly and in v0.7.10. Workaround is to use English Region until then.
