### ISSUE TITLE
Navbar is not rendering properly.

### ISSUE THREAD

**Issue by earth4s** [Kareadita/Kavita#2346]
The side NavBar "> More" is not rendering properly on my install after updating from 7.8 to 7.9. Not sure if this is theme or CSS related. I have verified this on Chrome on Windows and Android.

I have deleted the Themes, Cache, and temp folders and restarted the Kavita service to troubleshoot. 

Chrome on Windows:
![image](https://github.com/Kareadita/Kavita/assets/9957002/366cab02-94dd-489a-a5c7-5984baf9d892)
![image](https://github.com/Kareadita/Kavita/assets/9957002/6f23e9d9-ad77-4397-82dc-852c05fde5c7)

Chrome on Android:
![Screenshot_20231022-164147](https://github.com/Kareadita/Kavita/assets/9957002/9864af9d-5feb-4611-a824-9523715b4b97)

Running on
Rocky Linux 9.2
Kernel 5.14

 - OS: Windows 10
 - Browser: Chrome
 - Version: 118

 - Device: Pixel 5a
 - OS: Android 14
 - Browser Chrome
 - Version 118

Not sure which logs to upload but I will provide more info when requested

**Comment by majora2007** [comment]
Clear your cookies for the site and it will work. Some minor issues with our localization library between updates.
