### ISSUE TITLE
Smart filter sort by always saves in descending order

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2347]
**Describe the bug**
When saving a smart filter the sort by always saves in descending order but when you check the filter itself the switch will show ascending. 

**To Reproduce**
1. Create a smart filter and set sort by direction to ascending
2. Reopen the smart filter
3. Filter will be in descending order but the arrow will show ascending.

**Expected behavior**
Sort direction matches the saved direction.

**Screenshots**
![opera_mOuj82KOfd](https://github.com/Kareadita/Kavita/assets/2068470/5bce9203-d3cb-487c-8fed-2fc7422e2834)
This image shows the filter as it is saved.
![opera_4rkALuqqTC](https://github.com/Kareadita/Kavita/assets/2068470/2841ac23-bcdd-4218-9c1c-9b9838ef7cf1)
This image shows the filter after it is reopened.

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Opera GX
 - Version 0.7.8.16

**Additional context**

**Comment by majora2007** [comment]
Took a look and the filter was still working as expected, but the arrow icon was not reflecting the default load state.
