### ISSUE TITLE
Link Icon disapears

### ISSUE THREAD

**Issue by IndySE** [Kareadita/Kavita#2348]
when i add a link, for exmaple for MAL it show the MAL icon, but after a short time it just show a generic link icon

after a container restart the icon is visible for 1 second and then it will stay generic icon

testet sites:

https://www.anisearch.de 
icon is saved in favicon folder 
bug happend
icon visible for 1 second after restart

https://myanimelist.net/
icon is not saved in the favicon folder
bug happend
icon never visible 

https://anilist.co
icon is not saved in the favicon folder
bug dont happen
icon always visible

**Comment by majora2007** [comment]
I was able to reproduce this, it has to do with www. and the correct code wasn't called.
