### ISSUE TITLE
[bug]The menu name is not changed

### ISSUE THREAD

**Issue by kim08384** [Kareadita/Kavita#2351]
(NAS) Kavita 0.7.9

Using Chrome Internet

Renaming and saving menus in the libraries

The menu name needs to be changed, but it remains the same

Cache Delete Refresh Completed

The menu does not change

1
<img width="860" alt="20231026_114739" src="https://github.com/Kareadita/Kavita/assets/149031356/d9490796-216d-4877-9612-0cc8a1f31f05">

2
<img width="850" alt="20231026_114808" src="https://github.com/Kareadita/Kavita/assets/149031356/10e9ad00-8544-42b6-902b-fe99c41c3e2b">

3
<img width="851" alt="20231026_114826" src="https://github.com/Kareadita/Kavita/assets/149031356/23454d22-e649-4a33-9f73-4448b5a3f9b8">

4
<img width="875" alt="20231026_114854" src="https://github.com/Kareadita/Kavita/assets/149031356/56ada39f-1088-48d2-afb7-00ee712eb64d">

5
<img width="137" alt="20231026_114849" src="https://github.com/Kareadita/Kavita/assets/149031356/08b42f7a-6be8-43a9-b790-8ab5ffb3b789">

**Comment by majora2007** [comment]
You're saying that the side nav name isn't refreshing automatically when you change a library name. 

Ill take a look.

**Comment by kim08384** [comment]
yes 
Side menu name not changed
