### ISSUE TITLE
Webtoons on mobile doesn't scroll to the next chapter

### ISSUE THREAD

**Issue by chilliwow** [Kareadita/Kavita#2352]
**Describe the bug**
Webtoons on mobile do not scroll to the next chapter. I have this issue with iPhone 11, iPad (5th gen), and a friend of mine has the issue with Samsung Galaxy A54. It doesn’t seem to recognize that it’s on the last chapter or something? Watch the whole video and check the chapter number at the bottom.

**To Reproduce**
Go to the end of a webtoon chapter and try to scroll to the next chapter

**Screenshots**

https://github.com/Kareadita/Kavita/assets/31785430/ed432b5e-e646-4746-8c66-183c7ac9e769

**Smartphone:**
 - Device: iPhone 11, iPad (5th gen), Samsung Galaxy A54
 - OS: iOS16.6.1, iOS16.3.1, Android 12
 - Browser: Tried Safari and Brave on iOS, Chrome on Android
 - Version: 0.7.9.0

**Comment by scare376** [comment]
I believe this issue is related to https://github.com/Kareadita/Kavita/issues/2088. On a  lot of the chapters I have this issue on I don't see it move to the last page and I think that causes it to not allow the next chapter trigger.

**Comment by chilliwow** [comment]
I was reading a webtoon on my computer and stumbled across this issue on desktop as well. It happened when I was zoomed out in my browser.

In the video you can see me reading at normal zoom (100%) and then zooming out to see it not working. I've attached some chapters that I got the issue on if you want to test it, but in general, it's pretty much on every webtoon I read.

https://github.com/Kareadita/Kavita/assets/31785430/fbe629a1-43b1-4550-9c5d-7ba67eba3cf4

[Testing Chapters.zip](https://github.com/Kareadita/Kavita/files/13197099/Testing.Chapters.zip)

**Comment by majora2007** [comment]
I know this issue is quite old. Dec 2023 I did quite a polishing on the webtoon reader. I will be releasing it sometime early this year, so hopefully we can squash this issue.

**Comment by majora2007** [comment]
I believe this is fixed on v0.7.14 (just released), can you please test and let me know?

**Comment by chilliwow** [comment]
It works a bit better now. The "Next Chapter" text is showing up 100% of the time, and I can press it to move to the next chapter, but the scrolling itself does not work 100% of the time as you can see in the video.

The first two chapters in the video scrolls well, but the one after that does not. I can not see any sort of pattern with it. I tested it with multiple webtoons and my friend tested as well and had the same issues.

https://github.com/Kareadita/Kavita/assets/31785430/dea21032-48ff-4c10-84fa-fe403fe3bf85

**Comment by majora2007** [comment]
Okay I'll keep looking into this. I had one hiccup where I reproduced this, but afterwards it worked for many chapters. Appreciate the testing.
