### ISSUE TITLE
on startup kavita caches all my ram

### ISSUE THREAD

**Issue by ofsaleem** [Kareadita/Kavita#2354]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
when i start up kavita, it immediately allocates all my free ram, sorta, the os reports it as cached

**To Reproduce**
start kavita
check `free -m` and `top`
see instant 20gb ram used

**Expected behavior**
ram usage rising over time is expected, but not to this level, and also not instantly on startup

**Screenshots**

![image](https://github.com/Kareadita/Kavita/assets/7631554/a44c1d3d-6dbb-4da1-9449-dc81eb6613aa)

![image](https://github.com/Kareadita/Kavita/assets/7631554/5d7060d5-f829-4db1-8677-a4ee5deb4484)

it starts like: 
![image](https://github.com/Kareadita/Kavita/assets/7631554/8646585a-e849-497c-a3d4-08322f6b8256)
 (even though top shows the above values)

and eventually becomes like:

![image](https://github.com/Kareadita/Kavita/assets/7631554/325f1f7e-3764-471a-aeb2-ac1c46ba1e72)

**Desktop (please complete the following information):**
 - OS: docker (container station) on my qnap NAS
 - Browser: vivaldi, but this occurs before i even access kavita, so i don't think it matters here
 - 0.7.9.0

**Additional context**
dont know how relevant this is but `dmesg` shows this 

```
[ 1882.664905] ==== memory usage ====
[ 1882.676587] MemTotal:       32714900 kB
[ 1882.680480] MemFree:          413840 kB
[ 1882.690192] MemAvailable:   28685692 kB
[ 1882.700344] Buffers:         4732580 kB
[ 1882.711602] Cached:         23319328 kB
[ 1882.715474] SwapCached:            0 kB
[ 1882.726601] Active:          4610676 kB
[ 1882.730494] Inactive:       25756472 kB
[ 1882.747311] Active(anon):     262116 kB
[ 1882.759177] Inactive(anon):  2566444 kB
[ 1882.763411] printk: awk: 36 output lines suppressed due to ratelimiting
[ 1882.797286] Node 0, zone      DMA
[ 1882.800710]   per-node stats
[ 1882.803841]       nr_inactive_anon 641372
[ 1882.807908]       nr_active_anon 65528
[ 1882.812315]       nr_inactive_file 5797507
[ 1882.816451]       nr_active_file 1087195
[ 1882.820500]       nr_unevictable 4182
[ 1882.824195]       nr_slab_reclaimable 348480
[ 1882.828484]       nr_slab_unreclaimable 31418
[ 1882.832881]       nr_isolated_anon 0
[ 1882.836924] printk: awk: 166 output lines suppressed due to ratelimiting
[ 1882.865988] Filename                         Type            Size            Used            Priority
[ 1882.870962] /dev/md256                              partition        530108          776             -2
[ 1882.878368] /dev/md322                              partition        6702652         0               -3
[ 1882.885447] /share/CACHEDEV1_DATA/.swap/qnap_swap   file             16777212        0               -4
[ 1882.900620]              total       used       free     shared    buffers     cached
[ 1882.900620] Mem:      32714900   32300844     414056     516200    4733120   23319448
[ 1882.900620] -/+ buffers/cache:    4248276   28466624
[ 1882.900620] Swap:     24009972
```

![image](https://github.com/Kareadita/Kavita/assets/7631554/7d8d77c5-9101-4ad8-acff-8bf04c12301d)

![image](https://github.com/Kareadita/Kavita/assets/7631554/b73d6b39-b4c8-4e40-bb5f-641c1a57b85c)

**Comment by majora2007** [comment]
Hmm I'm not sure how to debug this issue. On my machine Kavita uses sub 100MB and climbs to 200MB when active with scans throughout the day.

Is this a fresh install or an update from a previous version? Can you attach logs when you start Kavita?

**Comment by ofsaleem** [comment]
```
Starting Kavita
ls -l /kavita/config/appsettings.json
[Kavita] [2023-10-27 12:20:11.467 +00:00  1] [Information] API.Services.TaskScheduler Scheduling reoccurring tasks
[Kavita] [2023-10-27 12:20:11.828 +00:00  1] [Information] API.Services.TaskScheduler Scheduling Auto-Update tasks
[Kavita] [2023-10-27 12:20:11.956 +00:00  1] [Information] API.Services.Tasks.Scanner.LibraryWatcher [LibraryWatcher] Starting file watchers for 3 library folders
[Kavita] [2023-10-27 12:20:11.982 +00:00  1] [Information] API.Services.Tasks.Scanner.LibraryWatcher [LibraryWatcher] Watching 3 folders
[Kavita] [2023-10-27 12:20:12.091 +00:00  6] [Information] API.Program Running Migrations
[Kavita] [2023-10-27 12:20:12.136 +00:00  6] [Fatal] API.Program Running MigrateRemoveWebPSettingRows migration - Please be patient, this may take some time. This is not an error
[Kavita] [2023-10-27 12:20:12.138 +00:00  6] [Fatal] API.Program Running MigrateRemoveWebPSettingRows migration - complete. Nothing to do
[Kavita] [2023-10-27 12:20:12.165 +00:00  6] [Fatal] API.Program Running MigrateExistingRatings migration - Please be patient, this may take some time. This is not an error
[Kavita] [2023-10-27 12:20:12.177 +00:00  6] [Fatal] API.Program Running MigrateExistingRatings migration - Completed. This is not an error
[Kavita] [2023-10-27 12:20:12.181 +00:00  6] [Fatal] API.Program Running MigrateUserLibrarySideNavStream migration - Please be patient, this may take some time. This is not an error
[Kavita] [2023-10-27 12:20:12.210 +00:00  6] [Fatal] API.Program Running MigrateUserLibrarySideNavStream migration - complete. Nothing to do
[Kavita] [2023-10-27 12:20:13.053 +00:00  6] [Information] API.Program Running Migrations - complete
[Kavita] [2023-10-27 12:20:13.422 +00:00  1] [Information] API.Startup Starting with base url as /
Kavita - v0.7.9.0
```

this is an update from a previous version. these are the output logs from the container.  do you need the internalish logs, how can i provide those and which ones

**Comment by DieselTech** [comment]
This is how .NET handles GC and memory allotment. It's mapping a range of memory to use so it can keep pages in RAM close to each other for performance reasons. It's more about how the tools are showing it that becomes confusing. Just because it's mapped doesn't mean it's used. You can reference this ticket to get a better understanding of the process that is going on:

https://github.com/dotnet/runtime/issues/9199
