### ISSUE TITLE
[BUG] Side menu name not changed(Side menu name bug Unmodified)

### ISSUE THREAD

**Issue by kim08384** [Kareadita/Kavita#2361]
https://github.com/Kareadita/Kavita/issues/2351   <-Side menu name bug Unmodified

(0.7,10 patch)
<img width="532" alt="20231029_081440" src="https://github.com/Kareadita/Kavita/assets/149031356/b0305e7b-d491-4356-b84d-e1f39191841c">

<img width="66" alt="20231029_075251" src="https://github.com/Kareadita/Kavita/assets/149031356/655a3f4e-3a86-4fdc-aed1-df4fd607e082">

NAS ( Kavita 0.7.10)
Side menu name not changed
Side menu name bug Unmodified (Cache Delete Refresh Completed)

1.(Renaming)
<img width="858" alt="1" src="https://github.com/Kareadita/Kavita/assets/149031356/fb6b252f-0fac-4f32-87ec-e699d3e29320">

2. (Renamed and saved)
<img width="855" alt="2" src="https://github.com/Kareadita/Kavita/assets/149031356/7bedfd98-0276-47db-bb9b-f62e7e77dc1d">

3. (Name Change Completed)
<img width="1714" alt="3" src="https://github.com/Kareadita/Kavita/assets/149031356/983e61e2-f614-408d-8130-67ba8eca3906">

4. (Side menu name not changed)
<img width="142" alt="4" src="https://github.com/Kareadita/Kavita/assets/149031356/1f3f2083-c2b6-43e5-9e8d-2a9f934d4fb6">

-------------------------------------------------------
Kavita 0.7.8 (kizaing/Kavita)  -> Kavita 0.7.9 (jvmilazz0/Kavita) ->  Kavita 0.7.10 (jvmilazz0/Kavita) 
After moving from Docker (jvmilazz0/Kavita)
This problem occurred

**Comment by majora2007** [comment]
You're right. This was still present and was a different issue than I thought.
