### ISSUE TITLE
Volume/Chapter Covers aren't working when using a URL

### ISSUE THREAD

**Issue by reitenth** [Kareadita/Kavita#2379]
go to cover. add url, click apply. nothing happens

**Comment by majora2007** [comment]
Please fill out with the template....

**Comment by majora2007** [comment]
Without proper reproduction steps, I wont be able to work on this. I tested this yesterday and it worked fine. 

Please help me help you.

**Comment by reitenth** [comment]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to cover for a manga volume
2. Click on add url
3. Click apply
4. Nothing changes

**Expected behavior**
Change the cover image

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Unraid, docker linuxserver container
 https://github.com/linuxserver/docker-kavita
 - Browser latest firefox
 - Version 0.7.10.1

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by ryshik** [comment]
I am also experiencing this so I'll try to add a little more.

I can update series covers without issue.

I can update the volume or chapter cover with any *existing* cover image.  However, if I enter an image URL or upload a local image then it will show the new cover in the list of options but pressing 'Apply' does nothing (pressing Apply on existing cover images will change the 'Apply' button to 'Applied').

I have then F5, Ctrl+F5, and even loaded in a different browser to ensure it was not a caching issue.

**Comment by majora2007** [comment]
Hmm I just tried this and it worked perfectly. 

I opened the edit series -> Cover Image. 
Url -> https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/b55574-TGViC2QIFUc2.jpg
Load
Save

Image appeared immediately on the UI.

![image](https://github.com/Kareadita/Kavita/assets/735851/481f67dd-612e-4665-a22b-edd12f811bda)

**Comment by reitenth** [comment]
cover image changes instantly as well. im on firefox with adblocker. tried multiple file types uploading and url, none work.

**Comment by majora2007** [comment]
> cover image changes instantly as well. im on firefox with adblocker. tried multiple file types uploading and url, none work.

You created the issue. I'm not understanding, if the cover changes, then what is the bug here?

**Comment by reitenth** [comment]
series cover image changes, volume cover does not
![image](https://github.com/Kareadita/Kavita/assets/94771708/96389f6c-c90b-433c-ae14-ebdc815d4da8)
![image](https://github.com/Kareadita/Kavita/assets/94771708/a228d99c-d1b4-4141-9e5e-70f9abd7f096)

**Comment by random-human-being** [comment]
This is currently happening to me when uploading the new cover rather than using an URL. The new cover appears to have been added, but clicking on "Apply" does nothing, and if the page is refreshed the new cover disappears altogether.

Maybe the commit above fixes my issue as well, but I figure I'd mention it just in case.

Kavita 0.7.10.2 on Docker, accessed via Firefox.

**Comment by majora2007** [comment]
@random-human-being Yes, that is what the OP mentioned and as you can see, the issue is closed, hence it will be released in the next stable.
