### ISSUE TITLE
Read progress not showing correct number within a series

### ISSUE THREAD

**Issue by chilliwow** [Kareadita/Kavita#2380]
**Describe the bug**
Read progress not showing correct number within a series.

**To Reproduce**
1. Hover over the read progress bar on a series (On Deck)
2. Hover over the read progress bar on a series (Within the series)

**Screenshots**
![1](https://github.com/Kareadita/Kavita/assets/31785430/77fc0fa9-dae3-45bb-80fc-0beef29d529b) ![ezgif com-resize](https://github.com/Kareadita/Kavita/assets/31785430/b884c973-eb3c-4f90-862f-f0797a048596)
![3](https://github.com/Kareadita/Kavita/assets/31785430/9c8c9391-c0dc-453f-82b7-be90c6b3c818)![ezgif com-resize (1)](https://github.com/Kareadita/Kavita/assets/31785430/c67929b1-55c3-46a4-aec4-3499a6971862)

**Desktop:**
 - OS: Windows 11
 - Browser: Brave
 - Version: 0.7.10.1

**Comment by majora2007** [comment]
While I can't reproduce this, I did get another report. I'm going to move this back to open.
