### ISSUE TITLE
Average Reading Per Week Seems Incorrect

### ISSUE THREAD

**Issue by duplaja** [Kareadita/Kavita#2381]
**Describe the bug**

The user's Average Reading Per Week stat seems incorrect, as does perhaps the logic in the code behind it. It looks like it's finding the average reading time per chapter (adjusted for partially read chapters), multiplied by the expected reading time of the chapter, and then averaging it before multiplying by 7.

For reference, my Average Reading Per Week currently shows 6.3 hours per week. I've had Kavita installed for exactly 1 year tomorrow, and my time spent reading stat shows as 2,597 hours.  That'd give an expected (roughly) of 2597 hours / 52 weeks, or 49.9 hours per week (which honestly isn't far off, since we're using estimated reading times rather than actual, and I read way too much).

**To Reproduce**
1. Go to the user stats page.

**Expected behavior**
Should be closer to the expected value.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04, Docker
 - Browser: All
 - Version: 0.7.9.0, but has been around for a while

**Comment by majora2007** [comment]
Would you mind DMing me your DB? I want to run the queries directly on your user progress so I understand where the logic isn't lining up. I do agree the result seems off, but the logic seems correct.

**Comment by duplaja** [comment]
Sure! Just sent that over, thank you.
