### ISSUE TITLE
OPDS on Kobo Libra 2 doesn't work

### ISSUE THREAD

**Issue by Funk3** [Kareadita/Kavita#2383]
OPDS doesn't work when using a Kobo Libra 2 

- Kobo firmware 4.38
- KOReader Ovis installed via Nickelmenu
- No reverse proxy

Issue:

When I inputted the opds api into the opds catalogue along with my username and password it gave me the issue -

```Cannot get catalogue, Server response status: service not supported for socket type```

As per request, this issue is created by the user Zensei on discord

**Comment by DieselTech** [comment]
Issue was around kobo doing basic http auth, not a problem within kavita.
