### ISSUE TITLE
When triggering a library scan through the API, only a library with ID 1 will start scanning

### ISSUE THREAD

**Issue by Jacksaur** [Kareadita/Kavita#2385]
**Describe the bug**
Using Tranga, requests are sent to scan each library. All requests got a success response, but only the library with ID 1 actually triggered a scan. As a temporary workaround, I tried recreating my libraries from scratch to shift my Manga library to ID 1. But instead that moved them further down the list (IDs are now 4, 5 and 6) and now no libraries scan after the API request at all.
I'm not a developer, just a user of another piece of software. I tried to set up Postman so I could be a bigger help in debugging, but unfortunately couldn't figure out how to get it authenticated with Kavita at all.

**To Reproduce**
1. Send a POST request to scan a library with an ID higher than 1.
2. Library will not scan.

**Expected behavior**
Library scans.

**Screenshots**
Requests successful, only first library scanned: https://i.imgur.com/gzi6xom.png
Library IDs changed, no library scanned entirely: https://i.imgur.com/nTghuur.png

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Version: 0.7.9.0

**Comment by majora2007** [comment]
Can you please attach logs to help me understand? The api you're calling is the same thing the UI uses to trigger a scan, which is working.

**Comment by Jacksaur** [comment]
Real stupid of me to forget logs, sorry about that.

[Kavita] [2023-11-01 20:18:43.965 +00:00  85] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/Library responded 200 in 1.4322 ms  
[Kavita] [2023-11-01 20:18:43.967 +00:00  55] [Information] API.Services.TaskScheduler Enqueuing library scan for: 5  
[Kavita] [2023-11-01 20:18:43.968 +00:00  55] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/Library/scan responded 200 in 1.6769 ms  
[Kavita] [2023-11-01 20:18:43.969 +00:00  36] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache & Temp directories  
[Kavita] [2023-11-01 20:18:43.969 +00:00  36] [Information] API.Services.Tasks.CleanupService Cache and temp directory purged  
[Kavita] [2023-11-01 20:18:43.971 +00:00  85] [Information] API.Services.TaskScheduler A Library Scan is already running, rescheduling ScanLibrary in 3 hours  
[Kavita] [2023-11-01 20:18:43.971 +00:00  85] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/Library/scan responded 200 in 1.2261 ms  
[Kavita] [2023-11-01 20:18:43.996 +00:00  55] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Comics  
--- Bunch of skipped files, since the first library was not changed ---  
[Kavita] [2023-11-01 20:18:44.853 +00:00  55] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished file scan in 855 milliseconds. Updating database  
[Kavita] [2023-11-01 20:18:44.855 +00:00  55] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished library scan of 21 series in 886 milliseconds for Comics. There were no changes  
[Kavita] [2023-11-01 20:18:44.855 +00:00  55] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan  
[Kavita] [2023-11-01 20:18:44.860 +00:00  55] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 0 series that needs to be removed: []  
[Kavita] [2023-11-01 20:18:44.860 +00:00  55] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan - complete

Seems the scans are being sent too quickly in succession for Kavita then. Is there a way a program could check over the API to see if the Library is ready to scan before requesting one then?

**Comment by majora2007** [comment]
Correct, Kavita can only run 1 scan at a time, otherwise, it will just schedule those excess calls to be run later. So it's okay to trigger all of them to scan, but you might just need to wait for Kavita to reschedule those jobs to actually run.

Is there a reason why you're not using Folder Watching or Scan Folder API?

**Comment by Jacksaur** [comment]
I have folder searching enabled, but it never reacts to anything I do in them. Is there meant to be something in logs when it schedules the 10 minute scan?

My library is on a separate NAS device, permanently mounted to the device running Kavita. Could that be impacting the folder watching capability?

**Comment by majora2007** [comment]
Very likely. The folder watching uses the underlying OS mechanism, so in this case, notify. You'd have to research if your setup works with notify or not. 

On windows I have a networked mounted storage via Ethernet and my folder watching works. But I know Linux is different also if your library is too big, you may need to increase your inotify limit
