### ISSUE TITLE
Clicking writer name does not filter by writer

### ISSUE THREAD

**Issue by cherryontopknife** [Kareadita/Kavita#2393]
I'm pretty sure this isn't a feature request, as it looks like Kavita _attempts_ to create the filter, but nothing changes. I tested this on Brave, Firefox, and Edge. Windows 10. I also tested this on Safari on my iPad. Server is the latest stable docker image from linuxserver on unRAID.

**Describe the bug**
After clicking a writer's name, Kavita attempts to filter the library, but nothing is changed.

**To Reproduce**
1. Go to any book
2. Click on the writer's name
3. Observe that the library is not filtered by chosen writer

**Expected behavior**
Clicking a writer's name should successfully automatically apply the filter

**Screenshots**
If I click the writer's name:
![image](https://github.com/Kareadita/Kavita/assets/109005960/af964cc3-f339-436c-a7ff-a7fbe22ea44e)

The library is not filtered, although the URL seems to be attempting to filter:
![image](https://github.com/Kareadita/Kavita/assets/109005960/7e04aebb-b06b-421b-9aee-7a8118ffc835)

If you then apply a filter to these results, nothing changes.

**Desktop (please complete the following information):**
 - OS: unRAID docker container
 - Browser: Chrome, Firefix
 - Version: 0.7.10.2

**Comment by majora2007** [comment]
This is already fixed in the nightly. It will be fixed in the next release.
