### ISSUE TITLE
Removal of .kavitaignore

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#2394]
Kavitaignore files are a complex system to allow the admin to use globbing syntax (which is already non-trivial) to filter out paths and file from the scanning system. 

Likely, users use this to ignore file types, like calibre's cover image in the directory. Folder filtering is likely not used very often. 

This system can be replaced by an advanced library option during setup/edit, which allows the user to have ALL or a mix of Image, Archive, Epub, Pdf (and any further extension support added in the future). 

This system is much easier than maintaining and editing files on their system, allows easier handling when new image types are added, etc. 

Globbing (exclude patterns) can even be added directly into this section as well, if there is a need for it.

**Comment by earth4s** [comment]
I can say I do use the Kavitaignore to ignore folders. The most common ones I use are "_Originals", "_Other" and "_Archive". This help me keep like files for a serise togeather that I do not want Kavita to read.

Folder explination:
Originals - Original files that are unedited. Usually the files i get from humble bundle that I want to keep a copy of before inject metat data (PDF or epub) or repackage them for the library (CBR/CBZ).

Other - If a book/comic/manga has "alternate covers", "alternate version", "bonus material" or "other related files" that I want to keep togeather with a serise.

archive - Older versions of a book/comic/manga that I want to keep. Usually it has diffrent translations from another group or an older version from another publisher.

Maybe take a page from *nix OS's and ignore folders that start with "." so they are hidden from the scan process if you take away Kavitaignore.

**Comment by scare376** [comment]
As long as the functionality of a .kavitaignore file still exists in some capacity I think its fine to remove it.

**Comment by majora2007** [comment]
Just an FYI, I decided to move forward with the removal of .kavitaignore. I will bring all the functionality into the Library Settings to make it easy for users to use this feature, rather than have it hidden as an advanced feature, like Plex does. Once the nightly is ready, I will reach out to you @earth4s with a build for some testing to see if it works just as well for you.
