### ISSUE TITLE
Favicons for weblinks are broken (still)

### ISSUE THREAD

**Issue by JShiesty-dev** [Kareadita/Kavita#2397]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Some people said its working for them but its not for me. It had been working till a recent update. I am on the latest nightly. Using the file "anilist.co.png".

**Describe the bug**

**To Reproduce**
1. See error

**Expected behavior**
It is supposed to show the favicon specified and not the broken link image.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker]
 - Version [e.g. 22] (can be found on Server Settings -> System tab)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majora2007** [comment]
This was a regression when I changed how we load images within Kavita in the nightlies. If it wasn't working prior to the latest release, please clear out your config/favicons directory to let the new code (which properly fixed it a few releases ago) take effect.

**Comment by JShiesty-dev** [comment]
> This was a regression when I changed how we load images within Kavita in the nightlies. If it wasn't working prior to the latest release, please clear out your config/favicons directory to let the new code (which properly fixed it a few releases ago) take effect.

I have already tried removing the favicons and it doesnt fix it, adding them back after also doesnt fix it.
