### ISSUE TITLE
Filter Comparision: IsEmpty

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#2403]
Allow a user to filter to see anything NOT linked with a collection/tag/want-to-read/people/etc. 

https://feats.kavitareader.com/posts/248/set-library-filter-to-show-books-not-in-a-collection

Note: A user is working this, but if not implemented by 2024, I will do it.

**Comment by DieselTech** [comment]
He has done it:

https://github.com/Kareadita/Kavita/commit/036f5239c1c8a1fb13073ef52beeda4cfe7c80bd

Will be out in the next stable (0.8.3)
