### ISSUE TITLE
400 error sometimes happens when saving progress for PDF

### ISSUE THREAD

**Issue by UlyssesZh** [Kareadita/Kavita#2406]
When jumping to a far position in a PDF (e.g. navigating through the left panel of table of contents), sometimes a 400 error is reported. This is not steadily reproduced, but I can sometimes see it.
![image](https://github.com/Kareadita/Kavita/assets/26196187/2ef5401b-7b61-4c5b-b4d4-0245e7701193)
![image](https://github.com/Kareadita/Kavita/assets/26196187/19da91cc-95cd-4945-a2ed-0c76b59cbe77)
In the backend log:
```
[Error] Microsoft.EntityFrameworkCore.Update An exception occurred in the database while saving changes for context type 'API.Data.DataContext'.
...
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
...
```

Server:
- OS: Arch (installed via AUR)
- Kavita version: 0.7.10.2

Client:
 - OS: Ubuntu 20.04
 - Browser: Brave 1.59.124 (Chromium: 118.0.5993.117)

**Comment by DieselTech** [comment]
https://wiki.kavitareader.com/en/faq#q-im-seeing-database-is-locked-errors-in-my-logs

**Comment by UlyssesZh** [comment]
> https://wiki.kavitareader.com/en/faq#q-im-seeing-database-is-locked-errors-in-my-logs

Seems great. I have just done that. I will close this issue if I do not see this error for some time.
