### ISSUE TITLE
Folder watching bug

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2408]
**Describe the bug**
If you create a new library with folder watching on while the server folder watching is disabled folder watching will still not trigger if you turn the server setting on until you toggle the library folder watching.

**To Reproduce**
1. Turn off server folder watching.
2. Create a library with folder watching on.
3. Turn on folder watching. (Library root should not appear in the list of watched folders)
4. Add an item to confirm that folder watching does not trigger.
5. Toggle the library folder watcher setting off then back on. (Logs should now indicate folder is being watched)
6. Add an item to confirm folder watching is working.

**Expected behavior**
The watcher should watch the new library folder, that has folder watching on, when the global watching setting is turned on.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX
 - Version 0.10.0.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majora2007** [comment]
I don't agree with this. I don't think setting something globally shouldn't override manual changes in the library. I would argue the user wants libraries to have it off explicitly, as that is what they set, and turning back on folder watching should only affect libraries where it wasn't explicitly disabled.

**Comment by scare376** [comment]
Sorry I very poorly explained the expected behavior before. It should have only covered the libraries that had the setting toggled on as well. I updated the original comment to reflect that.

**Comment by majora2007** [comment]
I don't agree with this. I don't think setting something globally shouldn't override manual changes in the library. I would argue the user wants libraries to have it off explicitly, as that is what they set, and turning back on folder watching should only affect libraries where it wasn't explicitly disabled.
