### ISSUE TITLE
PDF Settings/Layout menu blank 

### ISSUE THREAD

**Issue by TableCoffee** [Kareadita/Kavita#2410]
**Describe the bug**
Updated to v0.7.10.2 Hotfix 2 and when viewing any PDF's within the app the overflow/hamburger menu is blank. 

**To Reproduce**
- View any pdf document
- Tap the overflow menu
- see empty frame

**Expected behavior**
Settings for viewing the pdf / adjusting layout should be presented

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/110047644/977f723c-06b6-418a-a821-1f0338698805)

**Desktop (please complete the following information):**
 - Tested on Firefox and chromium browsers on Arch Linux

**Smartphone (please complete the following information):**
-Tested on firefox and chromium browsers on Android 13

**Comment by majora2007** [comment]
Issue opened with downstream library:
https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/1953

**Comment by majora2007** [comment]
After talking with the downstream developer, it looks like there is quite a bit for me to do. I'm not sure if I will get to this in the v0.7.x series of releases or if I will wait for v0.8.x to look for a replacement of the underlying library as it's moving in a direction that is opposite of my own.
