### ISSUE TITLE
Series Metadata not being pulled from first book in series. EPUB

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2412]
**Describe the bug**
On EPUBs the series metadata is coming from a seemingly random volume. I think this is just on EPUB 3 though. 

**To Reproduce**
1. Add EPUB series with multiple volumes and metadata.
2. Series metadata will come from one of the volumes. 

**Expected behavior**
Series metadata comes from the first volume in the series.

**Screenshots**
![opera_NxEustJx2c](https://github.com/Kareadita/Kavita/assets/2068470/f46ca84c-2e46-474e-b422-b05438380726)
![opera_1w4uLdwWcc](https://github.com/Kareadita/Kavita/assets/2068470/ffc3f6fd-be8b-4655-a891-4424e557f8da)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Opera GX
 - Version 0.7.10.6

**Additional context**

**Comment by majora2007** [comment]
Is this on the first scan of this series, the epub metadata is coming from a random library? Or do I need to add a new volume or something?

**Comment by scare376** [comment]
So iirc it used to grab from a different volume every time it scanned the series. Though now it does seem to be consistently grabbing from the first volume. I'll play around with it a bit more and see if I can reproduce it again. It might have been fixed already and this series just has not been scanned since.

**Comment by majora2007** [comment]
I think it's been fixed. I remember recently fixing this to make it more consistent.

**Comment by scare376** [comment]
Yeah i havent been able to reproduce it so far. I'll close this for now and reopen it if i come across it again.
