### ISSUE TITLE
Design on mobile breaks because of search field width if using komf-userscript

### ISSUE THREAD

**Issue by SwedishGojira** [Kareadita/Kavita#2413]
**Describe the bug**
The search field will be too wide on mobile if using the komf-userscript and make the header three times as high as it should be.

**To Reproduce**
1. Have the komf-userscript installed and activated.
2. Open kavita on phone and watch the header menu.
![Skärmdump 2023-11-08, 13 50 37](https://github.com/Kareadita/Kavita/assets/1439531/e80914fe-3fac-4618-8c1d-995e2ad10059)

**Expected behavior**
The search field should adapt to the available space instead of pushing all the icons away and making the menu higher.
![Skärmdump 2023-11-08, 13 50 22](https://github.com/Kareadita/Kavita/assets/1439531/e2a5d07d-7e3f-4d54-ae43-20e160ea2c9d)

**Smartphone (please complete the following information):**
 - Device: Pixel 7a
 - OS: Android 14
 - Browser Firefox Nightly
 - Version 121.0a1
Behavior can be replicated in firefox dev mode by selecting the Pixel 5 screen setting.

**Additional context**
Can be fixed by setting the width of the search field to 100% instead of 300px that it is now.

**Comment by majora2007** [comment]
To make sure I understand, you have Komf userscript installed on your mobile device?

**Comment by SwedishGojira** [comment]
Yes. So I can scrape on the go.

**Comment by majora2007** [comment]
This should be fixed with the UX overhaul, if not please report back and I can reopen.
