### ISSUE TITLE
First page load of a fresh docker container 404's 

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#2415]
**Describe the bug**
When a fresh docker image is made, the first time the base URL is loaded into a browser a blank page will load. 

**To Reproduce**
1. Update docker image
2. Load base URL (ie, not refreshing a existing page that you had open from before the docker image update) 
3. See error

```
[Kavita] [2023-11-08 14:17:55.617 -05:00  42] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /main.a63814dec392999d.js responded 404 in 4.2733 ms

[Kavita] [2023-11-08 14:17:55.617 -05:00  44] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /runtime.c5aeca50a76b8c90.js responded 404 in 4.4549 ms

[Kavita] [2023-11-08 14:17:55.617 -05:00  43] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /vendor.c8fbf7180cd330ca.js responded 404 in 2.9581 ms
```

**Expected behavior**
Front page loads like normal

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/30128380/6adb5871-7dfe-4811-b99c-fa9659904ee2)

**Desktop (please complete the following information):**
 - OS: Docker 
 - Browser: Firefox 119
 - Version: All so far

**Comment by majora2007** [comment]
Is this Stable or Nightly? I changed some routing in the nightly.

**Comment by DieselTech** [comment]
> Is this Stable or Nightly? I changed some routing in the nightly.

This was on nightly. I don't really pull stable at all so I don't know if it also shows up there. I've been able to reproduce this problem for months now, so it isn't something you just changed recently.

**Comment by DieselTech** [comment]
New container image created, new set of URL's 404'ing. At least they are differently named, so the cache busting on build seems to be working. Just need to figure out where it's going wrong. 

```
[Kavita] [2023-11-08 17:33:23.213 -05:00  49] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /main.05f8d8a1d31c02a9.js responded 404 in 3.3404 ms

[Kavita] [2023-11-08 17:33:23.213 -05:00  48] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /runtime.16a15029c92a32fa.js responded 404 in 3.4000 ms

[Kavita] [2023-11-08 17:33:23.213 -05:00  50] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /vendor.2a62f93185118153.js responded 404 in 3.3901 ms
```
