### ISSUE TITLE
Series with two different years isn't phasing the names correctly.

### ISSUE THREAD

**Issue by earth4s** [Kareadita/Kavita#2423]
I am trying to add a Comic series that has two different Years, "I Hate Fairyland (2015)" and "I Hate Fairyland (2022). I have tried different ways of renaming the folders including using { } to keep them separate but keep running into phasing issues on the first series.

In the first series Kavita keeps phasing the series name as "I Hate Fairyland - Book" or "I Hate Fairyland {2015} - Book" (If i add the year to the files). While the second series is added without issue.

Library is also set to "Comics"

The first series has the file names as:
"I Hate Fairyland - Book 1 - Skottie Young.cbz"

The second has the file name as:
"I Hate Fairyland v01 - Skottie Young (2022) (Digital).cbz"

Full file tree breakdown is below.

None of the files have comicinfo.xml inside them. I have tried adding the year to each file with { } but that does not affect the First series and it just adds the year to the second series name in curly brackets.

I noticed that the wiki says “you can rename the "Name" field to be "Fables (2004)" and "Fables (1989)" so they are separate series” but I believe that the ability to rename series directly in Kavita has been removed. I confirmed this when trying to edit the series.

Lastly the Comic section of the wiki stated that there are keywords that are treated special, including “Book”. So far I do not see a difference when using "Book" in the first serise.

Am I missing something or misunderstanding the wiki?

```
┖── Library Root
    ┠─── I Hate Fairyland {2015}
    │    ┖── I Hate Fairyland - Book 1 - Skottie Young.cbz
    │    ┖── I Hate Fairyland - Book 2 - Skottie Young.cbz
    ┖─── I Hate Fairyland {2022}
         ┖── I Hate Fairyland v01 - Skottie Young (2022) (Digital).cbz
         ┖── I Hate Fairyland v02 - Skottie Young (2022) (Digital).cbz
         ┖── I Hate Fairyland v03 - Skottie Young (2023) (Digital).cbz
         ┖── I Hate Fairyland v04 - Skottie Young (2023) (Digital).cbz
```
Am I missing something or misunderstanding the wiki? I will clarify anything if needed, I know I can be obtuse at times.

**Comment by scare376** [comment]
Sounds like you have some metadata in the files. You can check that and clean them up with comictagger or https://github.com/MangaManagerORG/Manga-Manager. I would recommend adding the year to the series title there and kavita should make everything distinct.

**Comment by earth4s** [comment]
The files were repacked and do not have XMLs/metadata in them. I have been trying to avoid embedding metadata as a personal preference.

If anything, I'm just wondering why the series phasing does not match up with the information from the wiki.

**Comment by majora2007** [comment]
It does, but you need to understand how Kavita cleans the series title when parsed from filename. 

I Hate Fairyland {2015} needs to be in the filename, not the directory. The directory is only looked at when there wasn't enough metadata that could be gathered from the filename. 

So if you had:
`I Hate Fairyland {2015}/1.cbz` then Kavita will look at the folder and parse out the series. But you have `I Hate Fairyland {2015}/I Hate Fairyland - Book 1 - Skottie Young.cbz` which parses the series as `I Hate Fairyland` and thus your 2 separate folders are getting merged together.

**Comment by DieselTech** [comment]
Cases like this are why the new library type "Comic (ComicVine)" was added. If the files you have come from mylar and you follow the folder structure it provides then kavita will be able to ingest these series as their own separate entities. 

If you haven't already, try using the new library type and get back to us.
