### ISSUE TITLE
[Bug] API checking tags/genres/people for duplicates causes large spike in CPU / RAM usage. 

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#2428]
**Describe the bug**
Joe:

komf is hitting the api quickly, the api has code in it that has to basically check against all the tags/geners/people so that duplicates aren't created
and that's straining your system as it can eat up a lot of ram on heavily tagged systems and just overall db strain, so you're cpu is spinning and waiting, all the while, a bunch of other threads are doing the same request type work on another series.

**To Reproduce**
1. Have a lot of metadata tagged files
2. Use KOMF to update a series'
3. Watch CPU spike to max for 5+ minutes

**Expected behavior**

**Screenshots**
[IMG](https://cdn.discordapp.com/attachments/851515194185744464/1173006494346772611/image.png?ex=6562626d&is=654fed6d&hm=c14ca05b48274b00a7fa1e5a2cf30295a561af3b4717fe5b194a96fc1b05d95c&)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: N/A
 - Version: 0.7.10.12

**Additional context**
It's the same underlying issue with the scanner that makes it so I can't parallel process series

**Comment by DieselTech** [comment]
This issue is back after the last release (0.7.11.2)

[img](https://cdn.discordapp.com/attachments/851515194185744464/1184375407131238460/image.png?ex=658bbe8d&is=6579498d&hm=65c7a73bec64c39bdfc20ba247f36a5ff9116db83bcf2b451cb28e1945f6b800&)

**Comment by majora2007** [comment]
I spoke with SnD and they have added rate limiting to not cause performance issues on Kavita's side when users have larger libraries.
