### ISSUE TITLE
series creating duplicate book entries as "Book 0" when only single item exists in series

### ISSUE THREAD

**Issue by LDShadowLord** [Kareadita/Kavita#2431]
[This issue continued from Discord Thread](https://discord.com/channels/821879810934439936/1169901267720601620)

**Describe the bug**
When a book is on its own in a series (ie: the series has only a single entry) a duplicate entry is made (unsure at what point) that adds a "Book 0" to the series. Both the book 0 and the "special" have the exact same path, and point to the exact same file. This can be easily validated by downloading the series as it will provide a zip file with 2 identical files in it.

**To Reproduce**
1. Have a series with a single entry. The book must not have a series within it that can be parsed. If it has a series, but no index, it won't be affected by this bug. Likewise, if it only has an index but no series it will also not be affected.
2. Unsure how to make this happen. I believe it may happen at server start (a migration artefact?)

**Expected behavior**
A "Specials" entry to be created, and no Book to be created. This was the former usual behaviour. Alternatively, have a "book 0" entry stand alone, but not both to be created.

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/3749770/7b91970c-1f70-461f-abdf-c3a5b50bc2aa)
![image](https://github.com/Kareadita/Kavita/assets/3749770/f19ac6b1-c22f-4594-9d58-0ee335a19cf3)

**Desktop (please complete the following information):**
 - OS: Docker on Unraid 
 - Browser: Chrome
 - Version: 119.0.6045.124

**Comment by majora2007** [comment]
Confirmed fixed.
