### ISSUE TITLE
Not able to use customizations in the Dashboard page

### ISSUE THREAD

**Issue by Chinmay-pathak** [Kareadita/Kavita#2435]
**Describe the bug**
Not able to use the customization options given here: https://wiki.kavitareader.com/en/guides/customization

**To Reproduce**
1. Go to 'Kavita home page'
2. Click on 'Home -> Options -> actionable.customize'

**Expected behavior**
Should be able to view the customization options

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/31542953/1d27e5fe-18c6-4682-af82-bb061f8b99d8)
![image](https://github.com/Kareadita/Kavita/assets/31542953/cd7c4c95-8879-44dd-93c2-0c9a41e19647)

**Desktop**
 - OS: Windows 10
 - Browser Chrome
 - Running Kavita via the provided jar given in the releases section. using version: [v0.7.10.2 - Hotfix 2](https://github.com/Kareadita/Kavita/releases/tag/v0.7.10.2)

**Comment by majora2007** [comment]
Is your issue that the locale needs to be busted (you can clear your cookies to fix this) or am I missing something else? Your steps imply you can't use the reordering but it looks usable.

**Comment by Chinmay-pathak** [comment]
Seems to be an issue with the browser, its fixed after clearing the cookies.
