### ISSUE TITLE
Bug: Double scrollbars on mobile

### ISSUE THREAD

**Issue by Jurgiss** [Kareadita/Kavita#2436]
**Describe the bug**
Front page of the app has double scrollbars on mobile, on Vertical orientation.
On Chrome, both scrollbars always visible. On firefox, they are not visible, but scroll behavior indicates that they are there.
 Ultra, 2316x1080

**To Reproduce**
1. Open home page on mobile device

**Expected behavior**
No double scrollbars.

**Screenshots**
![signal-2023-11-17-100928](https://github.com/Kareadita/Kavita/assets/3994723/aaa84006-fbab-44d6-9177-a0557ea36d60)

**Smartphone **
 - Galaxy S23 Ultra
 - OS: OneUI 6, Android 14
 - Chrome, Firefox
 - vLatest

**Additional context**
Issue might not be isolated to phones but I cannot confirm that for sure.
On iPad Pro I can see weird sizing of main container (will create separate issue for that).

**Comment by GottZ** [comment]
can confirm on Edge on S22 Ultra

**Comment by ghost** [comment]
can confirm on Chrome on S22

**Comment by Eforen** [comment]
Can confirm on S10+

**Comment by therobbiedavis** [comment]
I'll look into this hopefully tomorrow or Friday.
