### ISSUE TITLE
Bug: Layout breaking on iPad

### ISSUE THREAD

**Issue by Jurgiss** [Kareadita/Kavita#2437]
**Describe the bug**
Base layout seems to break in two ways on iPad:
* When changing screen size and refreshing page.
* When changing screen size in "1 column" text layout.

**To Reproduce**
Changing size:
1. Open a book (epub) in vertical orientation.
2. Either zoom in, or rotate to horizontal orientation, or both
3. Refresh page
4. Zoom-out or rotate back to vertical.
5. Result: reader's height remains the height at page load and does not always (~1/4 times it does) resize to fill the screen. (first screenshot)

Also, when performing "rotate screen" scenario while viewing book in 1-column layout, text gets split into two columns and remains so in that layout unless page is reloaded, or text layout is changed to to "scroll" and back to "one column" - but it looses progress position and scrolls back to start of the chapter.

**Expected behavior**
Book content always fills the screen. Rotating the device does not break the reader. 
Preferably - changing layout mode preserves progress, but that is a symptom, not the issue.

**Screenshots**
![signal-2023-11-17-103314_002](https://github.com/Kareadita/Kavita/assets/3994723/166803f2-3f73-4b17-a7b9-e545f90572a3)
![signal-2023-11-17-103314_003](https://github.com/Kareadita/Kavita/assets/3994723/69761ebd-f0f2-4562-b4b3-4cc5d791e135)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11 4th gen
 - OS: iPadOS 17.1.1
 - Browser Safari
 - Version Safari 17.1, Kavita 0.7.10.2

**Comment by majora2007** [comment]
I haven't seen this, but I also do not own an iOS device so I unfortunately cannot investigate this issue.

**Comment by DieselTech** [comment]
@Jurgiss Are you still having this issue in the latest version of Kavita? (0.8.2)

**Comment by DieselTech** [comment]
Haven't heard back from the user about this. Also, with the new UI overhaul going into multiple weeks of testing without this being reported I'm going to close this issue.

If you are still experiencing problems after the new UI overhaul comes out, please open a new issue ticket.
