### ISSUE TITLE
Bug: Reader setting persistance not working

### ISSUE THREAD

**Issue by Jurgiss** [Kareadita/Kavita#2438]
**Describe the bug**
I like to read ebooks (epub) using 1-column layout with tap-pagination, immersive mode, fullscreen.
However, no matter how many times I change those settings, either while in reader, or in profile settings, they are never persisted.
Every time I open a reader, or refresh an open one, they get reset back to default ones: scroll layout, no tap pagination, no immersive mode, no full screen.

**To Reproduce**
1. Change settings how reader should work
2. Refresh page OR navigate away and back
3. Settings get reverted.

**Expected behavior**
If I saved settings - at least in profile page, but preferably within reader itself, they should remain so after page refresh, navigation, or even between the sessions.

**Screenshots**
- not applicable, not a visual issue -

**Desktop (please complete the following information):**
 - OS: Garuda Linux, X-server
 - Browser Chrome, Firefox, FireDragon
 - Version All v-latest

**Smartphone:**
 - Device: Samsung Galaxy s23 ultra, iPad Pro 4th gen
 - OS: Android latest, one-ui latest, ios 17
 - Browser Safari, Firefox, Chrome
 - Version all v-latest

**Additional context**
On all devices - Firefox and FireDragon have privacy-first settings. Chrome and Safari are vanilla, no customizations.

**Comment by majora2007** [comment]
Persistent settings is not currently possible in the ebook reader or pdf reader. I had them originally but the confusion from users was immense. Please create a feature request to have persistent settings either on feats.kavitareader.com (old) or our new feature-requests channel in the discord.
