### ISSUE TITLE
[Windows] Run Kavita.exe silently

### ISSUE THREAD

**Issue by marvincyk** [Kareadita/Kavita#2439]
**Question**
How do I run Kavita.exe on Windows without having the command prompt open? Or if it does open, how can I safely close without stopping the application?

**To Reproduce**
1. Extract the Kavita Windows installer
2. Launch Kavita.exe
3. A command prompt will open with logs
4. Closing the command prompt will stop the application and localhost:5000 will be down

**Expected behavior**
I can either start Kavita silently, or close the command prompt without stopping Kavita.

**Desktop:**
 - OS: Windows 10

**Comment by majora2007** [comment]
You need to install it as a service:
https://wiki.kavitareader.com/en/install/windows-install#start-kavita
