### ISSUE TITLE
Issue with invite links behind reverse proxy

### ISSUE THREAD

**Issue by jakkarth** [Kareadita/Kavita#2440]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Running Kavita in a docker container on top of ubuntu, receiving the invite email with GMail but would apply to any email client.

**Describe the bug**
I am running Kavita behind an apache2 reverse proxy for SSL termination. Accessing Kavita from the internet over https works as expected, and trying to access it over http automatically redirects to https as expected. However, when sending an invitation email (using default email service url), the email received includes an http link rather than https. Everything else about the link is fine, and if I paste the link it works. But several users have reported that clicking the http link directly is causing a security warning on their devices. I'm not able to reproduce that problem, but the link is wrong regardless.

My theory is that API/Services/AccountService.cs line 70 is the issue, where Scheme is http because it's behind the reverse proxy. I don't have the capacity to debug the application while it's running to verify that's the case, and I don't know what to do about it. My first thought was to simply put the full https://domain.com/ as the base URL field, but it's expected to start and end with a /. Side note, the ui lets me save it that way and silently prepends a / to it, which is unintuitive to me; I would expect the save to fail if the form has validation errors.

**To Reproduce**
1. As an admin user accessing Kavita over https, invite a new user to join the Kavita instance, provide an email address, and hit send.
2. The user receives the email, and it contains an http link.

**Expected behavior**
I expect the user to receive an invite link that matches what the admin had in their browser URL at the time the invite was sent, including https.

**Desktop (please complete the following information):**
 - OS: Docker Community 24.0.7 on Ubuntu 20.04
 - Browser: Sending the invite using Firefox 119.0.1 on Linux Mint 20.1, email received in gmail but isn't client dependent.
 - Version 0.9.10.2.

Happy to provide additional information, let me know what you need.

**Comment by majora2007** [comment]
I've seen this happen when the headers aren't properly forwarded. I can't reproduce because on my reverse proxy, the headers are forwarded and thus the https generates. A workaround if you can't forward the headers is that you can set the Host name in the email tab which will always be used for url generation.

**Comment by jakkarth** [comment]
Workaround seems to work. Entering https://mydomain.com/ as the hostname does affect the email. However, I'd like to get it working without the workaround if possible. Which headers specifically need to be forwarded for this to work?

Another side note, while sending invite emails to myself for testing purposes, I occasionally ended up in a broken state where "optimistic concurrency" failed. Once that started happening, sending invites was no longer possible. I had to restart the container to resolve the issue. Logs contained:

```
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded.
```

Thanks for the quick response!

**Comment by majora2007** [comment]
I use Caddy and have nothing extra configured, but it might be X-Forwarded-Proto. There are a few X-Forwarded headers, but Proto is for HTTP/HTTPS determination. 

For the database concurency issue, I'm not exactly sure, but turning on WAL for your DB is usually the best thing to do. You can find that under our FAQ on the wiki. If that doesn't resolve it, please create a separate issue.

**Comment by jakkarth** [comment]
I'm using the following directives in my apache config:

```
RequestHeader set X-Forwarded-Proto "https"        
RequestHeader set X-Forwarded-Port "443"           
RequestHeader set X-Forwarded-For "%{REMOTE_ADDR}e"
```
which matches what was in the documentation (which I worked on today, thank you for merging my PR!) so it seems like it's already set up for that. I'll leave the workaround in place and investigate further if I have time. If the concurrency issue comes back, I'll look for that setting, and failing that try to get reproduction steps and file a separate report.

Thanks again!
