### ISSUE TITLE
Filters are all broken. Including Publisher, Writer, Character etc.

### ISSUE THREAD

**Issue by XyberDAWG** [Kareadita/Kavita#2441]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
All filters are broken. Any Character, Person, Publisher, etc all just take me back to the main library. 

**To Reproduce**
Click on any filter, or any linked metadata.

**Expected behavior**
Filters working

**Screenshots**
![Screenshot 2023-11-18 202837](https://github.com/Kareadita/Kavita/assets/47868784/2432138e-8ce8-453a-9453-fd496ef1413a)

As you can see even the filters do not see correct when trying to filter the database. They worked fine as of [v0.7.10 - Bugfixes](https://github.com/Kareadita/Kavita/releases/tag/v0.7.10)

I applied hotfix 2, without hotfix 1. Did this possibly break my install?

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 119.0.6045.107 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by scare376** [comment]
This is a known issue and has been resolved in the nightly build.

**Comment by XyberDAWG** [comment]
Ok, just making sure I didn't screw something up. I cant get nightly as I cant get Docker to function on my system.

**Comment by scare376** [comment]
also you should try clearing your browser cache and cookies. that should clear up all of those localization strings

**Comment by scare376** [comment]
and hit the bust locale cache in the tasks page of the admin dashboard.
![opera_H5K02vy1I3](https://github.com/Kareadita/Kavita/assets/2068470/06939bca-dd18-4cd9-ac32-43f8cc35f764)

**Comment by XyberDAWG** [comment]
not sure what you mean by localization strings, but i cleared my cache and cookies, as well as the bust local cache.

**Comment by scare376** [comment]
the *.* strings are localization strings. they should look something like this
![opera_pilfcPWjeS](https://github.com/Kareadita/Kavita/assets/2068470/faa366a0-05a1-4bb5-a975-d2e08dfc0409)

**Comment by XyberDAWG** [comment]
Oh ok, well i did all of that, and tried it on multiple browsers, even in private mode. and i get the same result on the filters.

**Comment by XyberDAWG** [comment]
Got it,

Now fixed, had to clear the cache, and cookies, as well as close several browsers in a separate desktop i forgot i had opened. 

Thanks. 

Ill call this closed then.
