### ISSUE TITLE
Bug: AL Link Error (Kavita+)

### ISSUE THREAD

**Issue by daydreamrabbit** [Kareadita/Kavita#2445]
**Describe the bug**
When capturing metadata using Kavita+, the Ratings link is linked to the wrong comic link.
Metadata was applied normally. The only problem is the Ratings link.

**To Reproduce**
1. Press Identify using Komf.
2. Enter Kekkaishi in the search box and select Anilist (anything else will work).
3. Ratings AL comes out as 0%.
4. If you click, you will be connected to the Fake-Partners adult cartoon.
5. The link in the metadata is normally registered as Kekkaishi.

**Expected behavior**
The rating of the Kekkaishi comic should be applied, not the rating of the comic called Fake-Partner.

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/80138664/179e25f9-58aa-4184-af17-63908ae8857e)
![image](https://github.com/Kareadita/Kavita/assets/80138664/eef5cf4b-0b55-4237-a68a-3e8bf5865430)

**Desktop (please complete the following information):**
 - Windows
 - Synology Nas
 - Browser : Edge
 - Version : 0.7.10.2

**Comment by majora2007** [comment]
This is because Komf is updating the metadata and it not able to tell Kavita to bust the cache. If you restart your Kavita instance or go to Tasks and bust Kavita+, does it show correctly?

**Comment by daydreamrabbit** [comment]
Yes, I rebooted, checked Kavita+, and re-received the metadata, but the results are the same.

**Comment by daydreamrabbit** [comment]
> This is because Komf is updating the metadata and it not able to tell Kavita to bust the cache. If you restart your Kavita instance or go to Tasks and bust Kavita+, does it show correctly?

Yes, I rebooted, checked Kavita+, and re-received the metadata, but the results are the same.

**Comment by majora2007** [comment]
I worked with the user on discord and a bug was fixed. It was released in v0.7.11.2.
