### ISSUE TITLE
please update docker hub version! latest only 0.7.8

### ISSUE THREAD

**Issue by ferocknew** [Kareadita/Kavita#2448]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker]
 - Version [e.g. 22] (can be found on Server Settings -> System tab)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DieselTech** [comment]
What is the problem here? Dockerhub has the last version of Kavita under the `:latest` tag

**Comment by ferocknew** [comment]
github release newest version is 0.7.10，but docker hub latest tag is 0.7.8

**Comment by majora2007** [comment]
Can you please link me to where you're seeing docker hub not showing the latest version?

**Comment by ferocknew** [comment]
https://hub.docker.com/r/kizaing/kavita/tags

Is it hard to find this link?？？？

**Comment by majora2007** [comment]
Do you see on this link, on the main page, that there is a banner saying this repo is no longer in use and to use the jvmilazz0 one instead?

Please switch to the correct repository. This was communicated on the wiki and in release notes.

**Comment by lapastillaroja** [comment]
@majora2007 the link in the README.md file points to the old docker
https://github.com/Kareadita/Kavita/blob/8e85ba069c39b8047650ca30e1d6a805a7992a7f/README.md?plain=1#L12

**Comment by majora2007** [comment]
Are you taking about the badges like docker pulls?

**Comment by ferocknew** [comment]
It's closed.

**Comment by lapastillaroja** [comment]
> Are you taking about the badges like docker pulls?

yes, that link is still pointing to the old one as of now in the default `develop` branch
