### ISSUE TITLE
[Bug] Metadata Link Delete Bug

### ISSUE THREAD

**Issue by daydreamrabbit** [Kareadita/Kavita#2456]
Describe the bug
Problem with unwanted links being deleted when trying to delete a desired web link

To Reproduce
When I try to delete a web link after downloading the metadata using Komf, a problem occurs where the incorrect link disappears.

Screenshots / Video
https://www.awesomescreenshot.com/video/22765130?key=8a4c0b49e247b7cdf01caae8b761bc21

Desktop (please complete the following information):
Windows
Synology Nas
Browser : Edge
Version : 0.7.10.2

**Comment by majora2007** [comment]
I was able to reproduce this issue. The issue revolves around not being able to properly extract the anilist id out of a weblink and send it, to take precedence over the series name.
