### ISSUE TITLE
Arm 64 docker installation lacks libpdfium.so

### ISSUE THREAD

**Issue by lumpsoid** [Kareadita/Kavita#2457]
**Describe the bug**
Unable to read pdf in Kavita. Kavita gives an error popup that the pdf does not contain any pages.

**To Reproduce**
1. [Installing Kavita with docker compose](https://wiki.kavitareader.com/en/install/docker-install#docker-compose)
2. Run `docker compose up -d`
3. Creating dirs for books: `mkdir -p ~/kavita/books/test-pdf`
4. Add a pdf file to the folder `test-pdf`
5. In Kavita web UI add books series, choosing folder as described on wiki
6. Scan created series
7. See pdf without cover
8. Click on pdf item
9. Click on read button
10. See the error popup about pdf doesn't containing pages

**Expected behavior**
Be able to read pdf in Kavita

**Screenshots**
Cover error: ![image](https://github.com/Kareadita/Kavita/assets/79290581/a8823d8d-3146-4670-b6c9-6d2f081d1b8b)
Popup: ![image](https://github.com/Kareadita/Kavita/assets/79290581/c10965d1-83cb-496c-984f-d24c29a3f6b0)

**Desktop (please complete the following information):**
- Raspberry 5 8 Gb
- [Raspberry OS Lite 64](https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit) (Debian 12 bookworm)
- `uname -a` : `Linux rbpi 6.1.0-rpi6-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.58-1+rpt2 (2023-10-27) aarch64 GNU/Linux`

**Additional context**
```
[Kavita] [2023-11-25 15:36:05.904 +01:00  98] [Warning] API.Services.BookService [BookService] There was an exception getting number of pages, defaulting to 0
System.DllNotFoundException: Unable to load shared library 'pdfium' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like stra
 If you're using glibc, consider setting the LD_DEBUG environment variable:
/kavita/pdfium.so: ELF load command alignment not page-aligned
pdfium.so: cannot open shared object file: No such file or directory
/kavita/libpdfium.so: cannot open shared object file: No such file or directory
/kavita/pdfium: cannot open shared object file: No such file or directory
/kavita/libpdfium: cannot open shared object file: No such file or directory

   at Docnet.Core.Bindings.fpdf_view.__Internal.FPDF_InitLibrary()
   at Docnet.Core.Bindings.fpdf_view.FPDF_InitLibrary()
   at Docnet.Core.DocLib..ctor()
   at Docnet.Core.DocLib.get_Instance()
   at API.Services.BookService.GetNumberOfPages(String filePath) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 719
```
# How to resolve it

For some reason, the docker image for `arm64` does not contain `libpdfium.so` in the root directory.
If you try to install pdfium in the docker container:
1. `docker exec -it kavita /bin/bash`
2. `apt-get install pdfium`
3. You will see 
```
root@b289c7028055:/kavita# apt-get install pdfium
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package pdfium
```

Found out several issues about same problem:
- https://github.com/Kareadita/Kavita/issues/468
- https://github.com/Kareadita/Kavita/issues/712
- https://github.com/Kareadita/Kavita/issues/1393

**For now to resolve this issue** you need to download pdfium binaries manually:
1. `docker exec -it kavita /bin/bash`
2. `mkdir pdfium-binaries && cd pdfium-binaries`
3. `curl -LJO https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-v8-linux-arm64.tgz`
4. `tar -xzvf pdfium-v8-linux-arm64.tgz`
5. `cp ./lib/libpdfium.so ../`
6. `exit`
7. on Kavita Web UI rescan book series

after this you should be able to read pdf in Kavita on arm64

**Comment by majora2007** [comment]
@Kizaing can you take a look at this?

**Comment by DieselTech** [comment]
I just dug out my old RPI4 and did a fresh install of the official RPI image that defaulted to Debian bookworm 12. I didn't choose "Lite" however, just the normal install. 

```
diesel@raspberrypi:~ $ uname -a
Linux raspberrypi 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

diesel@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```

Installed docker engine from dockers apt repo that installed version 24.0.7

```
diesel@raspberrypi:~ $ sudo docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:15 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:15 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
Mounted a network share directly in compose for kavita and added a book library that has PDF files. 

![image](https://github.com/Kareadita/Kavita/assets/30128380/cc6ab081-0e4b-4869-82bd-4f5de75be452)

I've tested dozens of books since adding them to the library and haven't seen any errors or rendering issues.

**Comment by DieselTech** [comment]
@lumpsoid Can you list your `docker version`  along with the container repo your using for the image?

**Comment by lumpsoid** [comment]
@DieselTech 

pi@rbpi:~$ docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:15 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:15 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by lumpsoid** [comment]
Re-checked my docker compose file and found that the server from which the docker image is pulled is different

Has it changed recently?

my docker file:
```yaml
services:
    kavita:
        image: kizaing/kavita:latest    # Using the stable branch from the offical repo.
        container_name: kavita
        volumes: 
            - ../copyparty/files/komga/books:/books
            - ../copyparty/files/komga/manga:/manga
            - ./config:/kavita/config                 
        environment:
            - TZ=something
        ports:
            - "5002:5000"
        restart: unless-stopped
```

on wiki it is
```yaml
...
        image: jvmilazz0/kavita:latest
...
```

**Comment by therobbiedavis** [comment]
@lumpsoid As of v0.7.9 the official image is `jvmilazz0/kavita:latest` 

kizaing has been archived.

**Comment by DieselTech** [comment]
It was announced on October 20th that the repos were changing: 

> Note: All docker images (kizaing) have been moved to jvmilazz0/kavita, jvmilazz0/kavitaemail. Please make sure you switch over to this repository going forward

So you've been running an out of date version of kavita this whole time. Also you skipped over the part of the bug template that asked for the kavita version number. (Version [e.g. 22] (can be found on Server Settings -> System tab) ). Partially my fault there for not double checking that you were running an up to date version, but also the importance of following the template so that critical information isn't missed.

**Comment by DieselTech** [comment]
This was unable to be reproduced and haven't heard back from the OP. If your still having issues you can drop by the discord for help.

**Comment by lumpsoid** [comment]
Sorry it took me so long to reply
I had then recreated the container with the latest valid docker image, and this problem does not exist on it. 
So the problem was really that I was using an old image.
I didn't expect the path from which the image is pulled to change, so when I revisited the wiki for docker compose I was blind to the change in that line.
I apologise for creating a silly issue.
