### ISSUE TITLE
Tachiyomi extension requiring v0.5+ when I'm running v0.7.10.2

### ISSUE THREAD

**Issue by ThibaultNocchi** [Kareadita/Kavita#2466]
**Describe the bug**
I installed the latest Tachiyomi extension version for Kavita, but once I setup the source it's saying I need a v0.5+ version when I'm running v0.7.10.2

**To Reproduce**
1. Install the Kavita extension from Tachiyomi (extension v1.4.10)
2. Connect to your account with the OPDS URL
3. Browse to the new source
4. See the error

**Expected behavior**
The source should work, or we should maybe edit the wiki to drop Tachiyomi if it isn't supported.

**Comment by majora2007** [comment]
Tachiyomi is working. Can you elaborate more on your setup? This seems to be related to Cloudflare where some users have a network configuration that is not working (which is outside the scope of Kavita to support).

**Comment by ThibaultNocchi** [comment]
I tried rebooting and resetting the settings, and it loaded. For info I'm "just" using a basic Nginx reverse proxy setup. I'm really confused for bothering you, I'm deeply sorry. Thanks for your answer and have a nice day!
