### ISSUE TITLE
Download arrows are displayed when they shouldn't

### ISSUE THREAD

**Issue by gregory-open** [Kareadita/Kavita#2474]
**Describe the bug**
When I am downloading a volume for a comic serie, the download arrows are displayed on the volume himself. It's correct.
But, if I switch to another serie in my library, the download arrows are also displayed for this one.

**To Reproduce**
1. Go to the serie I want to dowload
2. Click on Download
3. Go to another serie in the library
4. See the volume, the donwload arrows are also displayed

**Expected behavior**
No download arrrows displayed

**Screenshots**
![Capture d’écran du 2023-12-04 08-25-07](https://github.com/Kareadita/Kavita/assets/3799289/4891b98b-1743-4af6-86e5-c5887d473230)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 0.7.10.2

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android
 - Browser: Firefox
 - Version: 0.7.10.2

**Comment by scare376** [comment]
This is not clear as to what's wrong. Are you saying you download an item, wait for the item to finish downloading, and then move to another page and the download arrow reappears?

**Comment by majora2007** [comment]
I think they are saying the download indicator is displaying on the other series' volume card.

**Comment by gregory-open** [comment]
Thank you!
