### ISSUE TITLE
Error applying filter with Read Progress

### ISSUE THREAD

**Issue by Bluish9428** [Kareadita/Kavita#2475]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

**Describe the bug**
I'm trying to create a smart filter to show me all my unread comics/issues. I'm using a specific library and using Read Progress Equal 0. When I click Apply I get an error.

**To Reproduce**
1. Go to a library
2. Click on Filtering icon in upper right
3. Add criteria: Match all of the following + Read Progress Equal 0 percent + Libraries Equal (name of library)
4. Click Apply
5. See error: Exception of type 'System.ArgumentOutofRangeException' was thrown. (Parameter 'comparison') Actual value was 23.

**Expected behavior**
I would expect the filter to apply and be able to be saved.

**Screenshots**
<img width="864" alt="Screenshot 2023-12-04 at 9 48 42 AM" src="https://github.com/Kareadita/Kavita/assets/152899731/2f17d6ba-b7aa-4b4e-8cc9-b0d1b6a9fc05">

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Safari
 - Version: 0.7.11.0

**Additional context**
Other filters like Series name are working.

**Comment by majora2007** [comment]
Can you attach logs?

**Comment by Bluish9428** [comment]
[kavita20231204.log](https://github.com/Kareadita/Kavita/files/13548997/kavita20231204.log)

Here you go, hope this helps.

**Comment by majora2007** [comment]
Okay I think I know what's happening. I wasn't able to reproduce but there is a hard to reproduce bug in the UI code where the filter doesn't get properly updated and while it looks correct, it doesn't actually send a valid filter back. 

Can you refresh the browser and try to construct the filter again and see if it works?

**Comment by Bluish9428** [comment]
I was able to save the filter and see it in the Smart Filter box. Running it is giving 0 results with the progress indicator spinning at the bottom of the screen with the error
<img width="859" alt="Screenshot 2023-12-05 at 10 05 11 AM" src="https://github.com/Kareadita/Kavita/assets/152899731/583239e3-35ef-4d61-8ea8-46544e825fbc">
<img width="859" alt="Screenshot 2023-12-05 at 10 05 51 AM" src="https://github.com/Kareadita/Kavita/assets/152899731/2142e27d-03b1-4afc-9c6d-b7a1961709ad">

**Comment by majora2007** [comment]
Can you go to your dedicated smart filters page and see if the encoding is broken? 

![image](https://github.com/Kareadita/Kavita/assets/735851/a5302778-37c3-4e78-959b-81ad4f8ef5ae)

**Comment by Bluish9428** [comment]
Everything looks good there. 
<img width="231" alt="Screenshot 2023-12-07 at 11 01 03 AM" src="https://github.com/Kareadita/Kavita/assets/152899731/5086855a-3380-4ae5-9b01-d78ba6074d68">

**Comment by majora2007** [comment]
Okay I understand the issue. This is completely a UI bug where when constructing the filter, it can get messed up and the wrong thing is sent to the backend. It is a timing issue but hard to tackle. 

You can delete the filter and recreate it, or select a different comparsion on each dropdown then back to the orginal to save it and that should fix it.

**Comment by Bluish9428** [comment]
Thanks! I was able to slightly modify the filter and have it work.
