### ISSUE TITLE
Cannot open epub file. Getting error "Incorrect EPUB 2 NCX: content source "../html/1.html" not found in EPUB manifest"

### ISSUE THREAD

**Issue by ericma15** [Kareadita/Kavita#2476]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
this maybe a compatibility probelem. my epub in kavita web open with this error.But it works fine in other epub readers.
then i anlyse my epub.
It seems that in NCX file,the xml is `<content src="../html/1.html"/>`,
but in opf file manifest section,it is `<item id='Page_1' href="html/1.html" media-type="application/xhtml+xml">`
one use relative path while other use absolute path.
can kavita do this compatibility?
the file is manga download from a website.
all their manga have this problem.

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser chrome
 - Version 0.7.11

**Comment by ericma15** [comment]
BTW, the epub file works well in very old kavita.

**Comment by majora2007** [comment]
The underlying library I use to parse Epubs had fixes around relative paths and Kavita has as many fallbacks to try and handle all situations, but sometimes they fall through. I would suggest to just process this through Sigil or Calibre which will correct and normalize all the paths.

**Comment by ericma15** [comment]
> The underlying library I use to parse Epubs had fixes around relative paths and Kavita has as many fallbacks to try and handle all situations, but sometimes they fall through. I would suggest to just process this through Sigil or Calibre which will correct and normalize all the paths.

I write a script to correct the relative path,now it works well.

**Comment by ericma15** [comment]
today i find if i change the path,the toc will crash. that beacause ncx is in subdir. So ihave to use .. or move ncx to root dir. Finally, i write a script to covert epub to cbz with metadata, and webp.

**Comment by ericma15** [comment]
> The underlying library I use to parse Epubs had fixes around relative paths and Kavita has as many fallbacks to try and handle all situations, but sometimes they fall through. I would suggest to just process this through Sigil or Calibre which will correct and normalize all the paths.

I read the epub spec. That epub file has a virtual  fs. All url should be relative. for example， in file a/b.html href="c" means a/c,
href="../c/d" mean c/d, href="../../c/d" also mean c/d,because it reach root. in code like this.
```
    def resolve_path_on_any_platform( file_path, rel_path):
        root = pathlib.PurePosixPath(root_path).parent # remove file in the path
        rel_path = pathlib.PurePosixPath(rel_path)
        for p in rel_path.parts:
            if p == "..":
                root = root.parent
            elif p != '.':
                root = root / p
        return root.as_posix()
```
