### ISSUE TITLE
Pages skipped in webtoon scrolling mode on iOS

### ISSUE THREAD

**Issue by lyingloverr** [Kareadita/Kavita#2478]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
When scrolling Kativa in webtoon mode on iOS, the scroll will jump to random pages in the chapter.

**To Reproduce**
1. Open Kavita web app on iOS
2. Open manga chapter
3. Set to webtoon mode
4. Scroll through
5. See error

**Expected behavior**
To scroll without pages being skipped.

**Screenshots**

https://github.com/Kareadita/Kavita/assets/108381076/2d377547-12ab-461a-85f2-35d103454fdd
https://github.com/Kareadita/Kavita/assets/108381076/5069618e-eb0b-4c9a-bf8d-d82442ae10cb

**Desktop (please complete the following information):**
 - OS: Kavita running in Docker
 - Browser: N/A
 - Version: 0.7.11.0
 
**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro and other unknown iphone (other user)
 - OS: iOS 17.2 beta 2, 16.6.1, and 14.5.1 (both other user)
 - Browser 0.7.11.0 stock safari
 - Version: 0.7.11.0

**Additional context**
It seems as if the scrolling continues server side, i.e. you can keep scrolling and eventually you'll get to the end of the chapter. You will go from page 4, then jump to page 10, then back to 5, but if you continue scrolling you will get to the end.

**Comment by lyingloverr** [comment]
I’m having an issue specifically with “Solo Leveling” and I think it’s a continuation of this bug, so I thought I’d add more info that might be potentially useful. 

I receive this in my logs when a user tries loading Solo Leveling on their tachiyomi app. 

`[Kavita] [2023-12-07 05:49:43.236 -05:00  55] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/Reader/image?chapterId=10484&page=10&extractPdf=true&apiKey=081e126a-eb36-4591-9cb8-e028b08fe402 responded 204 in 1.7947 ms
` 

In their app this is an error they receive and they aren’t able to load any of the chapters. 
![IMG_1098](https://github.com/Kareadita/Kavita/assets/108381076/c637b136-aa0a-4cea-81d8-86f330f9e181)
![Screenshot_20231207-054638](https://github.com/Kareadita/Kavita/assets/108381076/884661f1-23b5-4e9a-9188-e44fb811f501)

On iOS using paperback, pages will be “missing” and instead replaced with a “too be continued” page (which is the last actual page of the chapter) 

Here is a video that hopefully explains what I mean: 

https://github.com/Kareadita/Kavita/assets/108381076/f7ec14e1-6919-4291-940c-609d7a51edd9

**Comment by majora2007** [comment]
I worked on this with the user via discord. I haven't been able to reproduce with my new code (Dec 2023). Likely something iOS specific.

**Comment by tezakaftor** [comment]
I've a similar problem on iOS with webtoons. Specially after reaching the second half of a chapter, then it starts to skip images and jumps to the end of the chapter. I'm on a Iphone 15 and using Safari. On my Macbook Air M1 in Safari the problem doesn't occur. I've no problems on iOS when using kavita with paperback.

**Comment by lyingloverr** [comment]
What version of Kavita are you running?

**Comment by tezakaftor** [comment]
I'm running version 0.7.12.0, docker.

**Comment by xInsertx** [comment]
Just posting to say I was having similar issues. Currently using either docker image 0.7.12 or 0.7.13 present the problem on iPadOS 15 and 17 - as well as iOS 17. Interesting enough I don't think I had the issues on 0.7.9 or .10 (I would have to go back and confirm).

Happy to provide any additional data for troubleshooting if I have time.

Note: For anyone having the issue - paperless works pretty well when having issues with the webapp (I've been using both - as it supports downloads + syncing reads).

**Comment by majora2007** [comment]
I'm currently stumped on this. I don't have an iOS device, so I can't really move forward on this without buying an iOS device (which aren't cheap). 

If anyone is open to submitting a PR or working with me on it, please reach out. I've tried so many different things to getting this to work, even rolling the code back to the last version that worked, but to no avail.

**Comment by Thundernerd** [comment]
I wouldn’t mind helping out. What do you need?

**Comment by majora2007** [comment]
> I wouldn’t mind helping out. What do you need?

I need someone to drive home a solution. It's likely an issue with the code around selecting the current page with the intersection observable. I'm assuming when we load the images in at the end, the scroll offset gets confused and it's thinking we are further than we should be. 

There is a debug mode in the infinite-scroller component that helps you visualize this. If you're on discord you can ping me and we can work it together.

**Comment by therobbiedavis** [comment]
@majora2007 I'll see what I can do regarding this issue.

**Comment by xInsertx** [comment]
Happy to gather or test anything provided I’m given a list.

I’ll try and dig up the chapters I knew when having issues and see if there’s a common theme with the images inside the cbz that might cause this

**Comment by lyingloverr** [comment]
Afaik you should be able to reproduce this issue, as long as you are using iOS and have the reader in webtoon mode.

**Comment by majora2007** [comment]
Thundernerd and I were able to make some promising progress. I will keep you posted.

**Comment by xInsertx** [comment]
Just figured I would confirm here that the fixes in v0.7.14 fixed all but one of the files having issues for me. This file does work in CDisplayEX - so ill put it aside and play around with it.

Will open another issue if I can track down the cause
