### ISSUE TITLE
Webtoon mode scrolling on desktop skipping pages all the way to the end.

### ISSUE THREAD

**Issue by thundrglaive** [Kareadita/Kavita#2483]
Environment: Docker container on synology nas. Kavita version 0.7.11.1
Client: Through webinterface (Tried chrome, firefox and edge)

**Describe the bug**
When using the webtoon reader it seems to skip many pages, all the way to the end. It can skip from page 10 to 100.

**To Reproduce**
1. Open a chapter in the webtoon reader mode.
2. scroll down.
3. It skips many pages, often all the way to the end of the chapter.

**Expected behavior**
Reading the chapter with the pages in order without it skipping.

**Screenshots**
![Scrnshot](https://github.com/Kareadita/Kavita/assets/106702708/58b9a469-2965-4903-b403-613f1a994bb4)
![Scrnshot2](https://github.com/Kareadita/Kavita/assets/106702708/7f881860-687b-44f0-8703-5a0316fa3f25)

**Desktop (please complete the following information):**
 - OS: 
 Server: Docker on synology DSM 7.2
Client: Windows 11, chrome, edge, firefox
Version: 0.7.11.1

**Additional context**
Connection between NAS and desktop is stable and fast. So i assume slow loading is not the issue.
Chapters are named according to the rules and most are in rar format.
(I don't see any obvious errors in the logs but during the reading of the chapter i see the following happen:
Fetching page 1000000 on chapter [chapter number]
Not sure if this is related but my chapters don't have that many pages. XD
It happens with every chapter, so will roll back for now. :)

**Comment by lyingloverr** [comment]
This is the same issue that I have.

[2478](https://github.com/Kareadita/Kavita/issues/2478)

**Comment by majora2007** [comment]
Going to close this issue in favor of https://github.com/Kareadita/Kavita/issues/2478
