### ISSUE TITLE
Unhelpful user name validation - 400 Error Invalid Email Confirmation

### ISSUE THREAD

**Issue by ckuethe** [Kareadita/Kavita#2486]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
I created a new user; let's call him `foo`. I then decided to rename the user to `Chris @ Work` so that it describes the purpose, then I went to the setup tool to finish setting up the account. Unfortunately, the `@` in the user name causes that to fail

**To Reproduce**
1. Go to Admin Dashboard
2. Click on 'Users'
3. Click on '[+ Invite]'
4. Name the user something like example, don't bother with an email
5. Copy the sign-up url
6. Click the edit user button
7. Change the username to "person @ place"
8. Save the changes
9. Open the sign-up url in an incognito tab
10. Fill out the setup form using reasonable values, eg. MyName / password123
11. click the register button
12. observe the `400 Error Invalid confirmation email` 

**Expected behavior**
* Separate username (`ckuethe`) from full name (`Chris Kuethe`)
* let me put whatever I want into the user full name
* immediately raise an error, or have a more robust validator, when I put an invalid character in a field

**Screenshots**
Found this in my logs:
`[Kavita] [2023-12-08 11:35:14.300 -08:00  200] [Fatal] API.Controllers.AccountController [Account] Email validation error: Username 'Chris @ Work' is invalid, can only contain letters or digits.
`

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Chrome 120
 - Version: 0.7.8.0

**Smartphone (please complete the following information):**
 N/A

**Additional context**

**Comment by majora2007** [comment]
Just to let you know you are quite out of date. You likely missed the announcements that the docker repository changed:
https://hub.docker.com/repository/docker/jvmilazz0/kavita/general

I'm going to take a look at this. I never thought about having an @ in the username. I think I can loosen the restrictions a bit, but unlikely allow @. Maybe Chris (Work) will be more suitable.

**Comment by ckuethe** [comment]
I don't mind not having an `@` or whatever in the user names; it's more a matter of the validator not telling me what I was doing wrong. If you want to restrict usernames to `[0-9a-f]` that's fine ... just so long as the ui tells me that I did something silly.

And yes, I did not see the repo change.

**Comment by majora2007** [comment]
It looks like this was more of something than I realized. The allowed characters were: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+/

The issue was that a) we had no validation on the UI and b) I wasn't actually updating something behind the scenes which controls the login. 

All that is fixed. Thanks for raising the issue. I hadn't touched this code in over a year.

**Comment by ckuethe** [comment]
Cool, thanks for fixing it, and thanks for making such a useful application.
