### ISSUE TITLE
ERROR TypeError: t.chapter.files[0] is undefined

### ISSUE THREAD

**Issue by Fmstrat** [Kareadita/Kavita#2487]
Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
When viewing certain trades, the above error is displayed. It's a `cbz` file with a valid `ComicInfo.xml`.

**To Reproduce**
1. Go to issue
2. Click on the three dots
3. No menu appears

**Expected behavior**
A menu appears

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox
 - Version 0.7.11.1

**Additional context**
Error in FF console:
```
ERROR TypeError: t.chapter.files[0] is undefined
    va entity-info-cards.component.html:43
    Angular 97
    RxJS 6
    Angular 7
    refresh_internal iharbeck-ngx-virtual-scroller.mjs:560
    Angular 13
    refresh_internal iharbeck-ngx-virtual-scroller.mjs:495
    Angular 3
core.mjs:11448:18
```

**Comment by majora2007** [comment]
This isn't enough information to support. Can you show some images to help me understand what you're seeing?

**Comment by Fmstrat** [comment]
I just discovered it's directly related to: https://github.com/Kareadita/Kavita/issues/2488

If I go into the trade's `ComicInfo.xml`, and alter the Title and Series tags to be unique, this error no longer shows up for the Trade.
