### ISSUE TITLE
If a trade and volume of issues share the same name, metadata swaps every time

### ISSUE THREAD

**Issue by Fmstrat** [Kareadita/Kavita#2488]
**Describe the bug**
If you have a Trade Paper Back that covers a whole volume of issues, and also the issues in your system, when you scan for metadata they swap each time.

**To Reproduce**
- Add the trade:
  - `/comics/Comic A (2013) [TPB]/Comic A 1 (2013).cbz`
- Add the volumes:
  - `/comics/Comic A (2013)/Comic A 1 (2013).cbz`
  - `/comics/Comic A (2013)/Comic A 2 (2013).cbz`
  - `/comics/Comic A (2013)/Comic A 3 (2013).cbz`
- Scan the library
- You will see either the trade of the volumes, let's say the trade first
- Scan the library
- You will now see the volumes, but not the trade
- Scan the library
- You will now see the trade, but not the volumes

This goes back and forth forever.

**Expected behavior**
If two distinct folders share a meta-data name from the `ComicInfo.xml`, allow them to exist separately.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox
 - Version 0.7.11.1

**Comment by majora2007** [comment]
https://wiki.kavitareader.com/en/guides/managing-your-files/scanner
https://github.com/Kareadita/Kavita/issues/2485

This is not a supported configuration of folders. Please see the other issue linked or the wiki.

**Comment by Fmstrat** [comment]
Hrm, am I missing something? The doc doesn't say how to handle where the Trade and the Volumes have the same series name. Also, this seems to occur regardless of folder name, and due to the conflict in the `ComicInfo.xml`. 

Also, I should note this creates issues that would go unnoticed by many on Reading Lists, as things get removed without notice as the items swap back and forth.

**Comment by Fmstrat** [comment]
Perhaps an example would help. Could you tell me how to organize:
- Michael Turner's Fathom: The Elite Saga (2013) - multiple issues released early 2013
- Michael Turner's Fathom: The Elite Saga (2013) - trade paper back released late 2013 including all issues

I currently have them in the folder structure above, but all of the examples defined in the scanner doc have different series names, but most scrapers that pull metadata are going to make them the same.

*EDIT*: As a note, if the series name is different in the `ComicInfo.xml` file, this is not a problem, but I've noticed a large portion of my collection doesn't show up because the series name is the same. Folder structure does not appear to overcome this issue.

**Comment by scare376** [comment]
If they have the same series name in the comicinfo then kavita will treat them as if they are the same. This is why the metadata changes. It's replacing the first volume of the series every time you scan. You need to make one of them distinct so that kavita recognizes it as something different.

**Comment by Fmstrat** [comment]
Wouldn't it be better to treat them as unique based on a combination of data to mirror how MetaData providers handle this? Example for the above:

https://comicvine.gamespot.com/fathom-the-elite-saga/4050-63726/
https://comicvine.gamespot.com/fathom-the-elite-saga/4050-70441/

**Comment by scare376** [comment]
How is kavita supposed to know this information though?

**Comment by Fmstrat** [comment]
Most MetaData providers include a web tag:
```
  <Web>https://comicvine.gamespot.com/fathom-the-elite-saga/4050-63726/</Web>
```

Could the existence of that in a new file be compared to that of an existing file to see if it's different (combined with the fact that it's in a new different folder)?

I.E. if two files are both issue 1, and the Web tag exists, and the Web tag is different, it's a new series? Trying to consider all the rescan potentials, too..

**Comment by scare376** [comment]
At this point this is less of a bug and more of a feature request. Kavita is functioning as it should. You can put in a request at https://feats.kavitareader.com or in our discord. If you do please check to see if there is already a similar request first.

**Comment by majora2007** [comment]
Agreed, please open a feature request if you think there is a better way to handle this.
