### ISSUE TITLE
A loading icon keeps spinning when reading in Webtoon mode

### ISSUE THREAD

**Issue by mozzenior** [Kareadita/Kavita#2489]
**Describe the bug**
A loading icon keeps spinning when reading in Webtoon mode

**To Reproduce**
1. Go to 'Preference > Image Reader' and set 'Reading Mode' to 'Webtoon'
2. Open a manga archive (a ZIP file in my case)
3. Observe the loading icon keeping spinning

**Expected behavior**
The loading icon would disappear after finishing loading the current image

**Screenshots**
Please find the loading icon in the center of the screenshot
![kavita-webtoon](https://github.com/Kareadita/Kavita/assets/624467/b6500209-043c-4bfb-b3a6-a4ee6ad28836)

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Browser: Chrome 119.0.6045.199
 - Version: 0.7.11

**Comment by mozzenior** [comment]
FWIW, the cause seems to be related to `<app-loading [loading]="isLoading || !(currentImage$ | async)?.complete" [absolute]="true"></app-loading>` in UI/Web/src/app/manga-reader/_components/manga-reader/manga-reader.component.html

Removing ` || !(currentImage$ | async)?.complete` works around this issue.

This change was added by commit e489d240 for addressing #2465

**Comment by majora2007** [comment]
Interesting that you're seeing this as I've been working on the webtoon reader for 3 days and haven't seen it, but this new loader code isn't meant for the webtoon reader, so I'll update it.
