### ISSUE TITLE
How to set up public books

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [Kareadita/Kavita#2491]
I want to anonymous users can also access my content, but there doesn't seem to be a setup for that
![image](https://github.com/Kareadita/Kavita/assets/87591236/00e18f66-da26-41a1-90c5-8d645938e553)

**Comment by DieselTech** [comment]
There is not a way, and won't be.

https://wiki.kavitareader.com/en/faq#q-is-there-a-way-to-use-kavita-without-authentication
