### ISSUE TITLE
Is it impossible for Kavita to apply Komga's folder recognition

### ISSUE THREAD

**Issue by kim08384** [Kareadita/Kavita#2499]
Does Kavita not recognize Komga's folder and only recognize it by EPUB name? This time, Komga EPUB
I support it, but in the case of Koma, it is recognized as a folder, so there is no need to modify the internal name of the EPUB file. Kavita
If the internal name of the EPUB file is abnormal
I need to change it separately
Is it impossible to apply Koma's folder recognition

Changing the internal file name of the EPUB file one by one is too difficult

I can't help it if it's not applicable, but thank you for always making and working hard on Karvita

**Comment by majora2007** [comment]
I'm not understanding what you're asking. Can you clarify?

Epub files always use the internal epub metadata to parse information out of. For the most part, you can assume the filename isn't used.

**Comment by kim08384** [comment]
> 나는 당신이 묻는 것을 이해하지 못하고 있습니다. 명확히 설명해 주시겠습니까?
> 
> Epub 파일은 항상 내부 epub 메타데이터를 사용하여 정보를 파싱합니다. 대부분의 경우 파일 이름이 사용되지 않는다고 가정할 수 있습니다.
---------------------------

Can kavita scan files with folder names, not with folder names
