### ISSUE TITLE
Can't edit metadata

### ISSUE THREAD

**Issue by amazing-rando** [Kareadita/Kavita#2502]
**Describe the bug**

I'm accessing up-to-date Kavita via Firefox running on Windows 10 and I'm unable to edit any metadata.  For example, when I try to edit the sort-name, I often (but not always) get the following error box: "An error occurred while saving the entity changes.  See the inner exception for details."

I dumped a log here:
[kavita_log.txt](https://github.com/Kareadita/Kavita/files/13690849/kavita_log.txt)

It looks like the database is locked for some reason.

I have had this happen when trying to edit the metadata of both CBZ and a PDF files but have not tried on EPUB or any other format.

**To Reproduce**
1) Go into a Book library and click on a series.
2) Click the "edit" button.
3) Move a word from the start of the title to the end. (e.g. "The Hound of the Baskervilles" to "Hound of the Baskervilles, The")
4) Click "save"
5) Get error.

**Expected behavior**
I expected the metadata changes to be saved.

**Desktop (please complete the following information):**
 - OS: Docker on Ubuntu Linux
 - Browser: Firefox
 - Version: 0.7.8.0

**Comment by majora2007** [comment]
First you need to update to v0.7.11.2. You likely missed the numerous announcements stating the movement to a new docker repository. Please update, retest and let me know if you need support. 

Second, for your issue please see the FAQ on our wiki, it has a fix.
