### ISSUE TITLE
[Translation] Missing french "Issue #"

### ISSUE THREAD

**Issue by LeoShivas** [Kareadita/Kavita#2504]
**Description**
Missing translation for "issue #<number>".

**To Reproduce**
1. Set your Kavita UI to french
2. Go to the main page of one comic or your choice
3. Set your display to "List"
4. Click on the `Numéros` tab
5. See that the word `issue` is used

**Expected behavior**
The word `numéro` should be used instead 

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/28844182/6791fe04-4e4f-4943-abf5-9230b37757a1)

With the grid display option, the translation is well done :
![image](https://github.com/Kareadita/Kavita/assets/28844182/d3c85c6d-cad5-4d79-a709-bd5c824695dc)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser : Chrome Version 120.0.6099.110
 - Version : 0.7.10.2

**Comment by scare376** [comment]
This is not a bug. That string has not been translated yet. If you would like to contribute you can here https://hosted.weblate.org/projects/kavita/
