### ISSUE TITLE
"Input String was not in a correct format" message on a few series

### ISSUE THREAD

**Issue by Patataonk** [Kareadita/Kavita#2506]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**

On a few of my Manga series I get the error message "Input String was not in a correct format"
Here is the log:
[kavita20231223.log](https://github.com/Kareadita/Kavita/files/13759651/kavita20231223.log)

it affects these series:

7Seeds (contains png for pages and jpg for cover and credit page)
![image](https://github.com/Kareadita/Kavita/assets/154692449/251591ba-fb46-42a5-b5df-a3af1e35e6f7)

Apocalypse no Toride  (contains jpg in folder)
![image](https://github.com/Kareadita/Kavita/assets/154692449/4ebd7330-bcb0-4858-b932-6921d3ed7423)
this is inside volume 1
![image](https://github.com/Kareadita/Kavita/assets/154692449/2565d9cf-c6dd-478e-9944-72b482cf356a)

Billy Bat (contains both png and jpg)
![image](https://github.com/Kareadita/Kavita/assets/154692449/5efda654-ed2e-4edf-ba16-275adf13ddb3)
this is inside volume 1
![image](https://github.com/Kareadita/Kavita/assets/154692449/33110c54-904b-450f-9a68-6f1d395e7b5c)

Vagabond (contains jpg in zip)
![image](https://github.com/Kareadita/Kavita/assets/154692449/8bb09f88-261d-42a9-a3df-c1206f4064ed)
![image](https://github.com/Kareadita/Kavita/assets/154692449/a01ddc9e-f830-425c-a69b-96ba155a48e5)

**To Reproduce**
1. click on series

**Expected behavior**

the error message nshows up

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/154692449/05b8598c-2786-462b-87ca-f9d7af447629)

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS
 - Browser  Opera GX
 - Version 0.7.1.4

**Comment by majora2007** [comment]
You're extremely out of date. This isn't an issue on the latest version of the software. Please update to v0.7.11.2.
