### ISSUE TITLE
Cover eror, doesnt loading and stopping the scans.

### ISSUE THREAD

**Issue by aligundogar** [Kareadita/Kavita#2507]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!
![image](https://github.com/Kareadita/Kavita/assets/48637822/0895eb18-31ed-410e-a999-e5b984e7fc23)
Kali Linux 2023 with Portainer (docker installation)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker]
 - Version [e.g. 22] (can be found on Server Settings -> System tab)
 -About System
Version
0.7.11.2
Install ID
a60d333b
[docker-conf.txt](https://github.com/Kareadita/Kavita/files/13774295/docker-conf.txt)
[docker-log.txt](https://github.com/Kareadita/Kavita/files/13774297/docker-log.txt)

Browser: Firedox and Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DieselTech** [comment]
Can you provide some info about your host hardware? What cpu are you using?

**Comment by aligundogar** [comment]
2 core CPU and 4 GB of ram.

**Comment by majora2007** [comment]
https://wiki.kavitareader.com/en/faq#q-kavita-doesnt-seem-to-run-or-generate-covers-on-my-computer

Please see the requirements for the CPU and if your CPU supports it.

**Comment by majora2007** [comment]
Otherwise, only other thing I see is:
/entrypoint.sh: line 33:     7 Illegal instruction     (core dumped) ./Kavita

which indicates you're using the wrong distribution for your system. 

Usually covers not generating in mass like this is due to the CPU not supporting SSE 4.2, which is required by NetVips, which we use for cover generation.

**Comment by DieselTech** [comment]
@aligundogar Have you resolved this issue?

**Comment by DieselTech** [comment]
Marking this issue as stale as there hasn't been an update in 2 weeks. If your still having problems with this even after following the instructions given, then you can re-open this issue.
