### ISSUE TITLE
Bug in API Services - Services - AccountServices.cs - GenerateEmailLink (with temporary work around)

### ISSUE THREAD

**Issue by drmlewando** [Kareadita/Kavita#2508]
The email link generated and emailed when inviting users is broken, specifically the ternary statement on line 76 for the function GenerateEmailLink in 'Kavita/API/Services/AccountServices.cs'

var removeCount = serverSettings.BaseUrl.EndsWith("/") ? 2 : 1;

In the general settings base url MUST start and end with "/" but you are removing 2 characters from the string.
This leads Kavita to send invites with "/kavit/registration" instead of "/kavita/registration" using a normal "/kavita/" proxy and base url in the settings.

given that you enforce the field settings in the UI to always start and end with "/" this remove count should essentially be a static 1, however, I understand the desire to check, you can rewrite this to be:

var removeCount = serverSettings.BaseUrl.EndsWith("/") ? 1 : 0;

and resolve the issue.

Here is what is produced under normal proxy settings and Kavita settings
![image](https://github.com/Kareadita/Kavita/assets/135249125/759beecd-0f5c-4c46-a447-42a32cef0436)

and here is the work around that resolves the error and enables a functional registration, proxy, and login process in the apache conf. Oh, edit, and make sure your base url is also /kavita_/
![image](https://github.com/Kareadita/Kavita/assets/135249125/05c1b517-dd64-408a-990a-d379ef727b6d)

**Comment by majora2007** [comment]
Appreciate the detailed investigation. I'm out for holiday, but will take a look next year.

**Comment by majora2007** [comment]
Took a look and you're right. I'm not sure why I had 2 : 1, nor how it got past testing.
