### ISSUE TITLE
"X-Frame-Options" setting has no effect

### ISSUE THREAD

**Issue by carbolymer** [Kareadita/Kavita#2509]
Kavita:     0.7.11.2

**Describe the bug**
Kavita does not open in an iframe.

**To Reproduce**
1. Set in `appsettings.json`:
``` 
"XFrameOptions": "" 
```
2. Restart Kavita.

**Actual behaviour**
`X-Frame-Options	SAMEORIGIN` header is present in the server response. Kavita cannot be opened in an iframe.

**Expected behaviour**
Kavita can be opened in an iframe

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser Firefox 
 - Version 120.0.1 (64-bit)

**Comment by scare376** [comment]
Kavita does not support iframes. You add iframe support via a reverse proxy.

**Comment by majora2007** [comment]
I'll take a look. @scare376 Kavita has an override via the app settings to disable a security measure and allow framing.

**Comment by scare376** [comment]
My apologies I forgot that had been added and when I had scanned through the wiki the only reference I could find to it was with the reverse proxy examples.

**Comment by majora2007** [comment]
I checked the code and setting to a blank string isn't supported. 

From Mozilla:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

I think `ALLOW FROM origin` is what you likely want. This option is only there for iframing within Organizr. Please let me know if there is a better way to support the iframing.

**Comment by carbolymer** [comment]
Does this setting still work? I'm setting it to:
```
"XFrameOptions": "ALLOW FROM kavitahosturl.com"
```
and it makes no difference

**Comment by majora2007** [comment]
I think the issue is that XFrameOptions is deprecated and instead CSP header is used by browsers. I will put a quick build up on this issue (please supply your OS) that will give access to the CSP header as well.
