### ISSUE TITLE
ePub images not working while server is behind proxy

### ISSUE THREAD

**Issue by yiatz** [Kareadita/Kavita#2510]
I have kavita running behind a reverse proxy. While it handles this fine for the most part, I've found that when it does api translations for images in epubs it tries to use the local server IP address instead of the hosted url.
Example:
![image](https://github.com/Kareadita/Kavita/assets/27975613/6679023a-d21b-40ff-8505-6a17bbf74d86)
The book is correctly loaded using the external url.
![image](https://github.com/Kareadita/Kavita/assets/27975613/fc9ca3ec-3ddc-4a9a-9909-9fd786155d4e)
but the images attempt to use an internal IP address for the route.

If I manually replace the base url to be the correct external url it works fine. It also works if I change it to an absolute path: "/api/book/1600/book-resources?file=index-1_1.jpg". I would think that almost all urls would want to be absolute paths unless you were planning on separating the web server from the api server so they could be hosted at different locations.

I believe a clean fix would be editing [this line](https://github.com/Kareadita/Kavita/blob/5ed8ef5a3cc308db1903d8513d7a9de77f55c32c/API/Controllers/BookController.cs#L156C15-L156C15) from
`var baseUrl = "//" + Request.Host + Request.PathBase + "/api/";`
to
`var baseUrl = "/api/";`
It may also need the Request.PathBase. I haven't gotten the code to a runnable state yet to test.
That baseUrl variable is only used to replace image references with api references further down in the code.

**Comment by yiatz** [comment]
Example tag from the epub returned to the browser:
`<img alt="Image 3" class="calibre2 kavita-scale-width" src="//192.***:***/api/book/1600/book-resources?file=index-5_1.jpg">`

**Comment by scare376** [comment]
This is likely your reverse proxy not being set up properly. Take a peek in #1183 and the reverse proxy examples on the wiki please.

**Comment by Anatrok** [comment]
I had the same issue and it was due Nginx Proxy Manager (which btw the current latest does not have working custom locations so you have to put it all into Advanced -> Custom Nginx Configuration):

I specifically added "proxy_set_header Host $host;" to top of my config (before any sublocations i added manually)
