### ISSUE TITLE
Kavita sharing data between libraries

### ISSUE THREAD

**Issue by AlanDunaway** [Kareadita/Kavita#2515]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

OS: Windows 10
Browser: All

**Describe the bug**
When you create more than one Kavita Library and start to fill up info, data from one library, such as artist, letrist and other data will be shared among libraries.

**To Reproduce**
1. Create two or more libraries;
2. Fill up info for one comic/manga/book in one library;
3. Move to the second library and start to fill up metadata;
4. Some metadata from the first library will show up in the second one as you are filling up info.

**Expected behavior**
I'd expect each library's metadata to be isolated or at least have a toggle to allow or disallow sharing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Applicable to all browsers.
 - Version 0.7.11.2

**Comment by majora2007** [comment]
This is per design. As an admin, you have access to all data across the whole instance. 

I'm assuming you're manually tagging a Series in another library and seeing people from another library as a prompt. This makes sense. 

Non-admin users cannot edit metadata, so they only see Series and the metadata associated with it in libraries they have access to.
