### ISSUE TITLE
After upgrade to 0.7.11 from 0.5.2 all accounts are disablesd

### ISSUE THREAD

**Issue by yves-gaignard** [Kareadita/Kavita#2517]
I upgraded my kavita installation on docker from version 0.5.2 to 0.7.11 (latest tag). Then all accounts are now disabled. 
The exact error message is:
  Your account is disabled
  Contact your server admin

I am the server admin but I don't have any idea how to activate it again. 

I looked for in the different release notes especially 0.7.0 as it is indicated that the account management changed. 
As indicated, I logged out again but nothing is better 

**To Reproduce**
1. Install a version 0.5.2 of kavita
2. Create an admin account
3. Upgrade to 0.7.11
4. See the error message: "your account is disabled"

**Expected behavior**
Please provide a procedure to reactivate my admin account or create a new one. I suppose then I'll be able to reactivate my admin account and the other accounts

Thank you for your help

**Comment by majora2007** [comment]
You can't jump that far in one go. You're jumping from over a year back to the latest. 

The rule of thumb is to update 2 releases (if a hotfix is there, you can skip the non-hotfixed release) at a time to ensure your database is migrated correctly.

**Comment by majora2007** [comment]
This is due to a new role being added a long time ago, but since it has been over 6 months, I removed the migration. Keeping migrations like that indefinitely just slows down the startup for users, hence why you need to jump a few releases at a time.

**Comment by yves-gaignard** [comment]
So, do you recommend to restore the backup of version 0.5.2 and then apply upgrade to 0.6.0 and then 0.7.0 and finally 0.7.11 ?
Or do I have to upgrade to each patch release ?

**Comment by yves-gaignard** [comment]
additional question , on docker hub the oldest available version is [nightly-0.7.8.2](https://hub.docker.com/layers/jvmilazz0/kavita/nightly-0.7.8.2/images/sha256-2e2f91b9224bdd931b42281a39d71dff6174fc950a9bed5f9b1c3fc8a0fe21ce?context=explore) 

Is there any other older docker version somewhere ?

**Comment by majora2007** [comment]
Yes, as seen here (and a few other times in notifications): 
https://github.com/Kareadita/Kavita/releases/tag/v0.7.11.2

The docker repo has changed to my repo:
https://hub.docker.com/r/jvmilazz0/kavita

The releases in Kavita are a little different. We don't follow semver. So your update order would be:
0.5.2 (rollback to this version)
[v0.5.6](https://github.com/Kareadita/Kavita/releases/tag/v0.5.6) <- NOTE: This has a new scan loop. Please be prepared and read against the wiki
[v0.7.1.4](https://github.com/Kareadita/Kavita/releases/tag/v0.7.1.4)
[v0.7.3.1](https://github.com/Kareadita/Kavita/releases/tag/v0.7.3.1)
[v0.7.6](https://github.com/Kareadita/Kavita/releases/tag/v0.7.6)
[v0.7.11.2](https://github.com/Kareadita/Kavita/releases/tag/v0.7.11.2)

I manually ensured that there are no migrations removed. 

Glad to see you updating to the latest. The software will feel like a v2 to you, given you're on such an old version. Please subscribe to the Github for releases so you can stay up to date. Also please use the stable unless you're going to be helping with testing with the nightlies (which given you're so out of date, it's unlikely you are). 

Let me know if you hit any issues.

**Comment by yves-gaignard** [comment]
Thank you a lot for your help. I succeeded to upgrade my kavita installation upto the latest version.
May I suggest to have a section in the documentation providing the different versions to be upgraded as the upgrade operation is not cumulative ?
I work on other software where the upgrade is cumulative, at least between minor version. 
For major version, as the semantic versioning told us, the compatibilty is not assumed. So for these versions it is probably another story.
Do you think that a version 1.0.0 of Kavita can happen a day ?

I wish you the best for you and your great product kavita.
