### ISSUE TITLE
Converting from a 'username' account to an email based login needs the wording cleaned up

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#2519]
**Describe the bug**
A user trying to add an email to their account who has not had one (username account) will get a success style message by using the change email workflow. However an email never actually goes out due to security decisions made in the past. 

`[Update Email]: User is trying to update their email, but their existing email () isn't valid. No email will be send`

The user isn't told this. Instead they see a message:

![image](https://github.com/Kareadita/Kavita/assets/30128380/069b7b89-9996-429c-a6e1-0c4179ba9e9b)

(which is also a lie, but we'll get to that down the line in another issue) 

**To Reproduce**
1. Go to user dashboard
2. Click on email
3. Input your email
4. Click save

**Expected behavior**
The user needs to be told that the email was not updated and that the admin of the server has to look through the logs to find the link to send to them manually. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker]
 - Version [e.g. 22] (can be found on Server Settings -> System tab)

**Additional context**
Short side note, I think the email part of the user dashboard could use a small heading or some descriptive text. When you click the edit button you just get 2 text boxes with only 1 snip of text asking for current password,

**Comment by majora2007** [comment]
I ended up taking care of this and much more to ensure the invalid emails were appropriately handled. 

![image](https://github.com/Kareadita/Kavita/assets/735851/592a823c-440a-4b80-9466-c6067d1a32fe)
