### ISSUE TITLE
Series doesn't show cards

### ISSUE THREAD

**Issue by Sulframus** [Kareadita/Kavita#2530]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**

**To Reproduce**
1. Open the specific series

**Expected behavior**
A card with chapters/volumes/storyline is shown as per any other series

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/50105122/c87f430b-7898-40fa-9ded-3e226675cb6a)
![image](https://github.com/Kareadita/Kavita/assets/50105122/391a62ab-3e06-4a43-80cc-c4766c087dd2)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Version: 0.7.11.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DieselTech** [comment]
Is this happening on a desktop browser or mobile?

**Comment by Sulframus** [comment]
Tested local access by desktop browser, reverse proxied access by desktop browser, local access by mobile browser, reverse proxied access by mobile browser.

**Comment by majora2007** [comment]
This is a scanner issue for sure

**Comment by majora2007** [comment]
First off, chapter 0 will force Kavita to treat this as a special. I think you'd be better off making it chapter 1. 

Second, this is a parser issue. the format c01-c04 isn't supported, but c01-04 is.
