### ISSUE TITLE
Updated series not appearing in filter

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#2534]
**Describe the bug**
I have some series that are not appearing in my in progress filter. Screenshot of exact filter to follow. These are the same series that previously reported higher than 100% reading progress because i upgraded the files.

**To Reproduce**
Unsure at the moment. The affected series seem to be the same that previously reported over 100% reading progress because i updated the files. Will add a comment with steps to reproduce if/when i can later.

**Expected behavior**
My in progress filter should match the on deck minus the series i have filtered separately

**Screenshots**
![opera_0oqaWi8sJu](https://github.com/Kareadita/Kavita/assets/2068470/af361efd-e62b-4e05-b924-20c5535f19b2)
![opera_LuyCURtGL0](https://github.com/Kareadita/Kavita/assets/2068470/0e8a87ca-2355-4f3c-9aa4-2b035031bd88)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Opera GX
 - Version 0.7.11.12

**Comment by scare376** [comment]
Wait it was just coincidentally was the same series that had the progress issue. The actual issue appears to be that they arent registering as having english language despite having the english language tag.
![opera_hk0k7qtwEM](https://github.com/Kareadita/Kavita/assets/2068470/bc4b41d1-b135-47dc-ab7a-a7e34e188b61)

**Comment by scare376** [comment]
if i click save it updates and appears in the filter

**Comment by majora2007** [comment]
Can you provide a file that isn't being read in as English? I'll do a bit of testing.

**Comment by scare376** [comment]
I figured it out. Komf is adding the english tag but i guess the series isnt updating to reflect that its the english language? Because these have no comicinfo.

**Comment by majora2007** [comment]
What is the exact metadata being set? Kavita expects an ISO language code.

**Comment by scare376** [comment]
im not sure. the language tag looks exactly as it does in the last image i sent. all i did to fix the others was open the menu and click save

**Comment by majora2007** [comment]
For this, you may need komf to write the tag, then inspect the db. I don't think I can debug this.

**Comment by scare376** [comment]
![SQLiteStudio_uSiAcoBgLd](https://github.com/Kareadita/Kavita/assets/2068470/9ea6bc86-771f-4e22-abcd-905d1ffa5fa5)
blank column being the language column

**Comment by scare376** [comment]
ok so it looks like the english tag being there is a kavita behavior and komf might not be adding a language tag at all. added a series to my test library and the column is still blank in the db but i saw the tag there in the ui

**Comment by scare376** [comment]
cant do anything more right now but if you have anything else you want me to try i can get to it after work

**Comment by majora2007** [comment]
Okay so likely komf isn't writing the field or explicitly sending null, then Kavita isn't including in your smart filter. So is there really a bug here?

**Comment by scare376** [comment]
Komf isn't sending null its not set to automatically update the test library. Kavita is setting null by default but in the UI I can see it there so is Kavita supposed to have it null or not.

**Comment by scare376** [comment]
Trying to figure out what the default behavior is because I know I didn't add an english tag to every series i've added.

**Comment by majora2007** [comment]
We found the issue. There is code that defaults to english only in the UI.
