### ISSUE TITLE
Bookmark cache problem

### ISSUE THREAD

**Issue by charles7668** [Kareadita/Kavita#2565]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
The bookmark reading feature caches images, so when you change the bookmark, the picture may still display the old image, unless you press Ctrl + F5 to refresh

**To Reproduce**
1. select a book
2. add page 1 and page 2 to bookmark
3. go to bookmark reading , you'll see page 1 and page 2
4. remove page2 bookmark
5. add page3 to bookmark 
6. go to bookmark reading , still see page 1 and page 2

**Expected behavior**
display bookmarked page correctly after bookmark has changed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser firefox , edge
 - Version 23H2
 
**Additional context**

**Comment by majora2007** [comment]
I think this is just that the browser is caching the image. There isn't much I can do other than users just waiting for it to expire (i think it's a max of 5 mins). 

This is an edge case for sure.
