### ISSUE TITLE
Save metadata in folder

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [Kareadita/Kavita#2580]
Adding an option to save metadata as a separate file within the eBook/comic folder, either as NFO or json would be a great addition.
Audiobookshelf has a great implementation of this.

**Comment by DieselTech** [comment]
Issues aren't used for feature suggestions. Github Discussions are where feature requests go now.

On top of that the dev has stated in the past that Kavita won't write metadata to users files. It massively increases the complexity of things and is a lot of burden once you start touching users files like that.
