### ISSUE TITLE
How to get Genres to show up from EPUB?

### ISSUE THREAD

**Issue by nothing2obvi** [Kareadita/Kavita#2584]
I added a custom column called "Subjects" with the lookup name "subjects" in Calibre, edited that custom metadata for "Subjects" with "Autobiography, Humor, Nonfiction" saved the book then imported into Kavita, but the genres don't appear in Kavita.

In Calibre I also tried "Edit Book" and edited the .opf file manually, adding <dc:subjects>Autobiography, Humor, Nonfiction</dc:subjects> then hit save. Then I saved the book and imported into Kavita, but again the genres don't appear.

What am I doing wrong? Thank you in advance for your help.

**Comment by majora2007** [comment]
First you are going to want make sure calibre is saving the opf file inside the epub. See our wiki for a guide on how to setup calibre to do by default. 

Then it will work.

**Comment by nothing2obvi** [comment]
@majora2007 

Thanks for your response. I followed the instructions [here](https://wiki.kavitareader.com/en/guides/misc/calibre). Didn't work for me, for either method I mentioned above. What's the proper way? The first way or the second way I mentioned?

**Comment by majora2007** [comment]
Can you open up the epub in question that isn't working for you with an archive program (zip, winrar, etc) and post the opf inside? 

This will first validate whether Calibre was setup correctly or not.

**Comment by nothing2obvi** [comment]
@majora2007 

Thank you for your quick reply. The opf from the extracted epub is [here](https://pastebin.com/90WnnR8k).

I see that my custom metadata of "Subjects" is listed as "#subjects" and I see that the manually-entered dc:subjects line is indeed there. So, I'm not sure what I'm doing wrong.

Btw, when I do get this going, can I put "Nonfiction, Autobiography, Comedy, Humor" for dc:subjects or should it be using slashes?

**Comment by majora2007** [comment]
So notice how your genre information you're expecting is in a tag called user_metadata. This is a calibre only thing and Kavita can't read it. Instead, see how the correct usage is:

```
    <dc:subject>Fiction</dc:subject>
    <dc:subject>Science Fiction</dc:subject>
    <dc:subject>Military</dc:subject>
    <dc:subject>Action &amp; Adventure</dc:subject>
    <dc:subject>Media Tie-In</dc:subject>
```

This will allow Kavita to read it, as it is what the spec dictates. You can fill this in Calibre itself under the Tags input box.

**Comment by nothing2obvi** [comment]
Oh wow it was much simpler than I thought. I got confused because the documentation says to use "dc:subjects" instead of separate "dc:subject" lines. Anyway, I got it to work. Thanks so much for your help!

**Comment by majora2007** [comment]
Oh, nice catch, I'll update the documentation to reflect the correct tag.

**Comment by nothing2obvi** [comment]
Excellent! Thank you for all that you do. Kavita is awesome. I wish I set it up sooner. Take care!

**Comment by nothing2obvi** [comment]
@majora2007 

Excellent! Thank you for all that you do. Kavita is awesome. I wish I set it up sooner. Take care!
