### ISSUE TITLE
Kavita uses deleted /memfd:doublemapper

### ISSUE THREAD

**Issue by OniriCorpe** [Kareadita/Kavita#2587]
hi!

[needrestart](https://github.com/liske/needrestart) restarts Kavita each time I run it

I turned on the verbosity and it returns this:
```text
$ sudo needrestart -v l
...
[main] #35805 uses deleted /memfd:doublemapper
[main] #35805 is not a child
[main] #35805 exe => /var/www/kavita/Kavita
[main] #35805 is kavita.service
```

so needrestart wants to relaunch kavita to free the deleted doublemappers? idk

but anyway, using this command I see that the number grows by a few dozen each time I interact with my Kavita instance:
```bash
$ sudo cat /proc/35805/maps | grep doublemapper | wc -l
1080
$ sudo cat /proc/35805/maps | grep doublemapper | wc -l
1145
$ sudo cat /proc/35805/maps | grep doublemapper | wc -l
1200
```

and it grows slowly by 1 or 2 every few tens of seconds or once a minute when I don't interact with my Kavita instance

**Comment by DieselTech** [comment]
Can you explain what the problem is here? As kavita is running more of the code gets ran through the JIT compiler and stays in memory. This is how .NET app generally behave. After the app is running a few hours the garbage collection process will kick off and reclaim memory, freeing it back to the system.

**Comment by OniriCorpe** [comment]
I never learned .NET and kavita is the only software (among many other I self-host) that needrestart would systematically restart, so I reported this behavior
If it's a normal one, okay!

**Comment by majora2007** [comment]
I'm not sure what this program does, but it's normal for interaction with a server to eat memory. Garbage collection usually kicks off every 6 hours with .NET and will free up unused memory.

Perhaps you have a hard limit and kavita is passing it? First scan will eat lots of ram. For me, my instance averages 200MB at any given time (with folder watching).

**Comment by majora2007** [comment]
https://github.com/dotnet/runtime/issues/89776

It seems like this is normal behaviour. I'm not sure why you're running out of memory. Can you provide any information about your system, OS, etc to help us understand more?

**Comment by DieselTech** [comment]
> I'm not sure what this program does

Same. Whats the point of running something like this? It doesn't seem beneficial to kill the app that often. Their own repo doesn't even really explain what this is for or why it might be good to run.
