### ISSUE TITLE
I am on v0.5.5/kavita-linux-x64.tar.gz ; what is my upgrade path to latest version?

### ISSUE THREAD

**Issue by somenewaccountthen** [Kareadita/Kavita#2589]
I am on v0.5.5/kavita-linux-x64.tar.gz ; 
I see there's no SQL migration scripts that look at DB version and run the old updates one by one.
This bricked my Kavita when i upgraded to latest because a new DB field was introduced in DB at some point.

What is my upgrade path to latest version? Anyone know?

**Comment by scare376** [comment]
You need to restore from a backup and then update incrementally. Updating by 2 stable releases at a time should get you going.

**Comment by somenewaccountthen** [comment]
yeah i am just doing all of them.
the updates don't take too long.
Just laborious.

fwiw these are the versions i upgraded:
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.5.5/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.5.6/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.6.0/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.6.1/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.1/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.1.4/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.2/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.3/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.3.1/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.4/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.5/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.6/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.7/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.8/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.9/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.10/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.10.1/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.10.2/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.11/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.11.1/kavita-linux-x64.tar.gz -O kavita.tar.tgz
#v0.7.11.1
#v0.7.11.2
RUN wget -q https://github.com/Kareadita/Kavita/releases/download/v0.7.12/kavita-linux-x64.tar.gz -O kavita.tar.tgz

I accidentally skipped 2 minor versions but it seems not matter as per above comment by scare.
