### ISSUE TITLE
Covers are black and white after nightly-0.7.11.2 and before nightly-0.7.11.14

### ISSUE THREAD

**Issue by eyd** [Kareadita/Kavita#2591]
![image](https://github.com/Kareadita/Kavita/assets/3900558/90b0f0b6-621d-478a-a5e5-929656f2c818)

Adding new comics or refreshing (deleting the comic and scanning) shows the black and white covers.

**Comment by majora2007** [comment]
I need the original image and the bad output please. Not screenshots so I can look at the underlying image data.

**Comment by eyd** [comment]
Thanks. Let me know if this isn't what you need. 
![bad-v11093_c60491](https://github.com/Kareadita/Kavita/assets/3900558/3af5fd6d-9d29-472b-901f-fe297f4f1d94)
![Good-v10974_c59669](https://github.com/Kareadita/Kavita/assets/3900558/8b7f73ba-0164-4698-937e-0a3a8e2920da)

**Comment by majora2007** [comment]
Issue opened with downstream library:
https://github.com/kleisauke/net-vips/issues/226

**Comment by majora2007** [comment]
This issue is likely due to your CPU not supporting SSE4. If you're using a Hypervisor, please use the Host CPU rather than "default" or a custom one. One user has already validated this fix.

Please let me know about your CPU and OS/Env so we can validate.

**Comment by eyd** [comment]
That fixed my issue. Thanks!

**Comment by Leicas** [comment]
I’m using the latest (tried nightly as well) version on docker and having the same issue, my cpu supports SSE4 and I copied the docker-compose from the installation page.

**Comment by scare376** [comment]
Netvips updated so let's wait for kavita to include the update before reporting more on the same issue.
