### ISSUE TITLE
Volumes with multiple chapters

### ISSUE THREAD

**Issue by FritzHeiden** [Kareadita/Kavita#2596]
I have one file for one volume, which consists of multiple chapters. When naming the file accordingly (`Vol.1 Ch.1-8`) the chapters are not recognized properly. It still shows each volume having one chapter (Vol. 1 Ch. 1, Vol. 2 Ch.2, etc.)

Would be nice if the UI indicates that there are multiple chapters in a single volume, or atleast don't assume there is one chapter in one volume.

**Comment by majora2007** [comment]
Sorry it took a while to get to this issue. I'm not sure I fully understand. Kavita doesn't assume a volume is just one file. If you have a file that is vol 1 ch 1-8, it should render it out that 1-8 (as one file) is part of the volume. If you also have volume 1 ch 9, it will still group and show correctly. 

Can you show me visually what you're seeing?

**Comment by FritzHeiden** [comment]
The problem is the other way around. I have one file with multiple chapters, but Kavita displays it so that one chapter is in one file:

```
'One Piece (2001) Vol.001 Ch.1-8 [Carlsen Verlag].cbz'
'One Piece (2001) Vol.002 Ch.9-17 [Carlsen Verlag].cbz'
'One Piece (2001) Vol.003 Ch.18-26 [Carlsen Verlag].cbz'
```

![image](https://github.com/Kareadita/Kavita/assets/9076000/7931c920-8609-4aec-9ec3-d8c0c5951c05)

I would expect this view to either show the range of chapters (like Chapter 1-8 for the first entry) or while keeping each chapter as one entry, chapter 1-8 will refer to the same file.

I also tried to start a discussion on specifying chapters in the ComicInfo.xml with page ranges and titles [here](https://github.com/anansi-project/comicinfo/discussions/52)

**Comment by majora2007** [comment]
I'm not having the same results:
![image](https://github.com/Kareadita/Kavita/assets/735851/20cd959e-fa20-4be4-9fd4-5dd62617f092)

`Adabana Vol 01 Ch 01-03.zip`

Can you validate the ComicInfo for me doesn't have Issue filled out as 1 for 1-8?

**Comment by FritzHeiden** [comment]
The ComicInfo file has issue set to 1 because thats the correct issue number. The issue however contains 8 chapters, so I don't think the chapter numbering should be affected by the issue number. (I use ComicVine as a reference for tagging) What do you think?

**Comment by majora2007** [comment]
Yeah that's the problem. You have it as 1, so Kavita is going to take 1. Usually, for manga, you would leave it blank because you don't need to fill it in (esp if you have it in the filename) if it's a Volume (single file volume). 

I don't think the ComicInfo can support ranges in the issue number, although Kavita can. ComicInfo was built for ComicRack and built for Comics. It's not very flexible for Manga. 

In my opinion  and what I do in practice) is just leave the Issue number off on single issue volumes. Leaving in the filename is optional, but Kavita will read that in. This way you get the best of both worlds.

**Comment by FritzHeiden** [comment]
Ok now I see that the terminology for comic and manga is different here. From what I understand comics and mangas are rather similar in terms of publishing, they just have different names. Manga is released as single chapters and rereleased as volumes containing multiple chapters. Comics are released as single issues and also rereleased as volume (Trade Paperbacks), so for both exist the same problem.
The ComicInfo.xml specifies "Volume" as integer, so that would fit manga and comics for volumes, and "Number" as string, which in turn would fits mangas chapters as range and comics issues as range.
I will give that a try and see if this works for me.
