### ISSUE TITLE
Number in Book (PDF) Name Cuts Off Title and Breaks Reader

### ISSUE THREAD

**Issue by wlowen** [Kareadita/Kavita#2597]
Just installed the latest version of Kavita on TrueNAS Scale. One of my books is a PDF that has a number in the name. After scanning, the book shows up but the title is cut off after the number. If I try to open the reader, it never loads. If I remove the number from the directory/file name and re-scan, everything works.

If there's additional information or logs that I could provide, please let me know. Thanks.

**Comment by majora2007** [comment]
You need to provide more information. I need the filename and what Kavita parses it as.

**Comment by wlowen** [comment]
> You need to provide more information. I need the filename and what Kavita parses it as.

Filename: Basics of 3D Printing.pdf
Kavita title: Basics of

**Comment by majora2007** [comment]
For now, you can rename to Basics of 3D Printing SP01.pdf and it will fix it. There are pdf filename parsing enhancements coming later this year.

**Comment by wlowen** [comment]
> For now, you can rename to Basics of 3D Printing SP01.pdf and it will fix it. There are pdf filename parsing enhancements coming later this year.

That worked. Thanks.
