### ISSUE TITLE
Users entire reading progress wiped when marking a single series as read or unread

### ISSUE THREAD

**Issue by yaypad** [Kareadita/Kavita#2598]
### What happened?

When marking a certain series as read or unread, the current user's reading progress for all other series was wiped. Other users reading progress are unaffected.

Repros consistently after restoring from backup. I tested with many (not all) of the series in my library and only one certain series seems to cause the issue. Repros for both mark as read and mark as unread.

A brief look at the db after repro indicates that reading progress is indeed deleted, although for some reason the oldest entry in AppUserProgresses for the user seems to get replaced with one for the series being marked as read/unread.

Will privately share a copy of the db, thanks!

### What did you expect?

Other series to not be affected

### Version

0.7.12.0

### What OS is Kavita being run on?

Docker

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

Running on a RPi. Have enabled WAL on the db.

**Comment by majora2007** [comment]
I was never able to reproduce this, I'm going to caulk it up to some system issue.
