### ISSUE TITLE
Chapters starting halfway through and repeating pages

### ISSUE THREAD

**Issue by chu-byo** [Kareadita/Kavita#2604]
### What happened?

Chapters starting with different pages as page 1, with the same page repeating multiple times at the end.
For example: a 20 page chapter starts with page 5 (005.png) as the "first page" would have the last page (020.png) show up on page 16, repeating until the end of the chapter.
Steps I took:
1. Navigate to the Kavita web UI
2. Select the series I want to read
3. Select the chapter I want to read
4. Encounter issue

### What did you expect?

The pages to be in order with no repeats

### Version

0.7.12.0 Server
1.4.13 Tachiyomi Extension

### What OS is Kavita being run on?

Docker

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Firefox

### Additional Notes

Broken chapters accompanied by 400 Error
Chapters are fine when the files are read locally with something like CDisplay, or opened in an archive viewer.
Doesn't happen with every chapter archive.
Happens in Tachiyomi too

**Comment by majora2007** [comment]
Please provide the reading settings in the UI and DM me this issue with the file you are using to test.

Please also state your server OS.

**Comment by chu-byo** [comment]
Attached is my reader settings.
![Reader](https://github.com/Kareadita/Kavita/assets/128328452/14bf05b4-688e-44e3-892d-e409a8c9bdac)
Server is running Debian 11 on 6.1.0-0 kernel

**Comment by majora2007** [comment]
File received: Asuperu_Kanojo_-_Vol._10_Ch._76.cbz

**Comment by majora2007** [comment]
This has been deployed to the nightlies. If you can, please try it out.
