### ISSUE TITLE
 ipad4 ios 10.3.4 has no login 

### ISSUE THREAD

**Issue by isLaLa** [Kareadita/Kavita#2606]
### What happened?

 ipad4 ios 10.3.4 has no login 

### What did you expect?

 ipad4 ios 10.3.4 has no login 

### Version

 ipad4 ios 10.3.4 has no login 

### What OS is Kavita being run on?

Mac

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Safari

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Safari

### Additional Notes

 ipad4 ios 10.3.4 has no login

**Comment by DieselTech** [comment]
Sorry but your iOS version is no longer supported. Your on a ~12 year old device at this point. The browser that your using doesn't have the necessary updates to run modern web apps like this.

**Comment by therobbiedavis** [comment]
To clarify, it's the version of Angular we use (v17) that no longer supports your iOS version. As per their documentation they only support the previous 2 major release versions iOS 16-17). https://angular.io/guide/browser-support
