### ISSUE TITLE
Unable to delete user

### ISSUE THREAD

**Issue by Sulframus** [Kareadita/Kavita#2607]
### What happened?

While trying to delete the user, the process fails

### What did you expect?

User to be deleted

### Version

0.7.12

### What OS is Kavita being run on?

Docker

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-01-12 22:59:49.071 +01:00  226] [Error] API.Middleware.ExceptionMiddleware There was an exception
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
```

### Additional Notes

![image](https://github.com/Kareadita/Kavita/assets/50105122/6636c02f-e112-4a16-a5ab-c9ced7c72667)
Error 500 http://10.10.1.10:5000/api/users/delete-user?username=redacted

**Comment by majora2007** [comment]
This is likely due to an old bug, I think there were a few bugs around Themes back then. This shouldn't be an issue any longer.
