### ISSUE TITLE
Wrong collection name and i cannot change it

### ISSUE THREAD

**Issue by EvgeniyDoctor** [Kareadita/Kavita#2608]
### What happened?

Wrong collection name and i cannot change it. I have folder called "Зубов" - last name of the author, but collection has completely different name.

### What did you expect?

Collection should called "Зубов" instead of "История России."
Kavita should follow **my** names of folders and do not do whatever it wants. How to change it forever?

### Version

0.7.12.0

### What OS is Kavita being run on?

Docker

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

Here is the view in Kavita:
![Screenshot_20240114_042025](https://github.com/Kareadita/Kavita/assets/15073200/4430715c-5dee-4ca1-bd44-988acf9cddc5)

This is name of the folder in my file browser:
![Screenshot_20240114_042044](https://github.com/Kareadita/Kavita/assets/15073200/1093e0c0-94f2-477a-b03a-b32c043194e1)

My file browser number 2:
![Screenshot_20240114_042133](https://github.com/Kareadita/Kavita/assets/15073200/d94f1dff-25da-4ed9-a0e8-103822ce3641)

And by the way, look at that lovely names of the books in Kavita. #1759 by me a year ago.

**Comment by scare376** [comment]
Kavita does not and will not use folder structure for organization, it uses metadata. I suggest you take a look at our wiki for instructions on how to manage your library or find a software that supports what you are trying to achieve
