### ISSUE TITLE
Webtoon Reader on Desktop stops working when scrolling with up/down arrow keys

### ISSUE THREAD

**Issue by chilliwow** [Kareadita/Kavita#2609]
### What happened?

Webtoon Reader on Desktop stops working when scrolling with up/down arrow keys
Steps to reproduce:
1. Open a webtoon in vertical scrolling mode
2. Start "scrolling" with the down arrow key
3. Let go of the arrow key and stop scrolling
4. Starts loading until you refresh

https://github.com/Kareadita/Kavita/assets/31785430/17d703c0-e78b-407e-840d-da640c1e8234

### What did you expect?

To not start loading indefinitely and just pause it like normal

### Version

0.7.10.2

### What OS is Kavita being run on?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

I am on version 0.7.10.2 because of another bug with the webtoon reader (#2478), so I can't upgrade yet.

**Comment by majora2007** [comment]
I think this should be fixed as of v0.7.14. Please retest for me.

**Comment by chilliwow** [comment]
It works properly now
