### ISSUE TITLE
Library Title can be "undefined"

### ISSUE THREAD

**Issue by ghost** [Kareadita/Kavita#2624]
### What happened?

I created a new Library with the name "Manga"
Website Header, Site Title & Library Settings showed nothing or "undefined"

### What did you expect?

See the Title of the Library.

### Version

0.7.13.0

### What OS is Kavita being run on?

Docker

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Chrome

### Additional Notes

-

**Comment by majora2007** [comment]
Image from support chat:
![image](https://github.com/Kareadita/Kavita/assets/735851/a6c602a3-5818-4bae-94d9-2ee5967d8f03)
