### ISSUE TITLE
Move KavitaEmail into Kavita

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#2626]
Moving Emailer in house and no longer offering email functionalities. 

- Email settings will live in Email Tab
- If email is not setup, all flows that require confirmation will automatically just work. The onus will shift from Kavita to the user to use secure methods. 
- Changing Password and Email will be instant going forward. This isn't a hosted site, we don't need to adhere to such security that impedes users
- Nothing will be managed in appsetting.json
- Update the User creation so that email isn't required by default (like it wont even need to be filled out)
- Email Change Update template needs to be reworked to explain the new email wont take effect until this is clicked.

**Comment by therobbiedavis** [comment]
I know some users have customized their own email's html. With this moving inside Kavita, how will we handle those?

**Comment by majora2007** [comment]
The templates will be in the config/templates in Kavita going forward. I can't migrate that data. 

This release will include a one time migration to write the templates to the config directory. Users after updating can override with their changes.

**Comment by majora2007** [comment]
Actually, I'm not sure how to handle it. If I put them in templates, then Kavita can't make any changes to the wording or easily add new ones. I'll need to think on the customization route.
