### ISSUE TITLE
Cover image files are not deleted when a series is deleted.

### ISSUE THREAD

**Issue by charles7668** [Kareadita/Kavita#2639]
### What happened?

When I delete a series from the library, the cached cover images(normally in config/covers path) are not deleted, which results in increased disk space usage.

### What did you expect?

Delete the cover image when a series is deleted

### Version

0.7.12.0

### What OS is Kavita being run on?

Docker

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Additional Notes

no

**Comment by majora2007** [comment]
Images aren't deleted instantly. There is a nightly cleanup that deletes unused stuff and cleans up the db.
