### ISSUE TITLE
How to naming the Raw Jpg image comics structure ?

### ISSUE THREAD

**Issue by nova168168** [Kareadita/Kavita#2649]
### What happened?

I am a folder as the following structure  

──Is
    ->└── Vol1
            --->├── Image 0001.jpg
            --->├── Image 0002.jpg
            --->└── Image 0003.jpg
    ->└── Vol2
            --->├── Image 0001.jpg
            --->├── Image 0002.jpg
            --->└── Image 0003.jpg

but the Server cannot seperate the Vol by storyline and it seperate with Specials and filename, such as : Image 0001.jpg will have 2 pics in preview screen.  What's wrong with this configuration? 

### What did you expect?

I want to seperate with Storyline by Vol1 , Vol2 

### Version

0.7.13

### What OS is Kavita being run on?

Docker

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Chrome

### Additional Notes

No

**Comment by majora2007** [comment]
What type of library are you using?

**Comment by nova168168** [comment]
@majora2007 Comics

**Comment by majora2007** [comment]
Okay, I would recommend if you're using loose images you use the image library type.

I haven't ever tested loose leaf images with comics because comics don't usually come in loose leaf and you don't usually collect volumes like that, as TPBs are their own series.

Please either try the image library type or pack them into a zip/CBZ.

**Comment by DieselTech** [comment]
Closing as stale. If you still need assistance please open a new issue.
