### ISSUE TITLE
OPDS URL doesn't show sometimes

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#2654]
### What happened?

![image](https://github.com/Kareadita/Kavita/assets/30128380/00eca415-2d4a-403b-ba55-a50c082b8f47)

Sometimes the URL doesn't generate 

### What did you expect?

The URL to show

### Version

0.7.13.5

### What OS is Kavita being run on?

Docker

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
Logs don't show anything wrong

> [Kavita] [2024-01-25 23:13:25.733 -05:00  102] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/account/opds-url responded 200 in 3.6246 ms
```

### Additional Notes

.

**Comment by majora2007** [comment]
This seems to be an edge case, I'm not sure how to reproduce.
