### ISSUE TITLE
Translations/Labels Aren't Loading

### ISSUE THREAD

**Issue by xcjs** [Kareadita/Kavita#2657]
### What happened?

![filters](https://github.com/Kareadita/Kavita/assets/5085205/dfd30fb6-d9d0-4b3a-8de0-93678af41b76)
![more](https://github.com/Kareadita/Kavita/assets/5085205/ac2843fc-16f0-4f2b-b792-efa5457ad2ac)

This happens throughout the UI seemingly randomly. I could upload more examples, but it's practically everywhere.

### What did you expect?

I expect translations or labels to display in place of the key names.

### Version

0.7.13.0

### What OS is Kavita being run on?

Docker

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Firefox

### Additional Notes

No additional notes.

**Comment by majora2007** [comment]
I've seen this happen from updating. There are a few things you can do.
1. Run the task for this:
![image](https://github.com/Kareadita/Kavita/assets/735851/8b6d321e-c07a-4725-a595-3d0243e3f749)
2. Clear browser cookies.

I have fixed this in the upcoming release by implementing my own cache busting mechanism.

**Comment by majora2007** [comment]
This issue is closed, but you can still discuss on this if you still need support.

**Comment by xcjs** [comment]
Thanks for the rapid response! Funny enough, I went to go follow these steps, and now it works before I could do so!
