### ISSUE TITLE
ComicInfo 'Count' tag does not appear to update publication status

### ISSUE THREAD

**Issue by lyingloverr** [Kareadita/Kavita#2671]
### What happened?

Prior to current nightly, publication status worked fine for series that I had. After a fresh install and starting over. Some series that I have not altered the metadata of whatsoever, that showed up as `Completed` prior to reinstall, now show up as ongoing. This happens on series that I do not have Volumes for, so that may be it. But Horo tells me that they think it should not matter whether I have volumes or not. Again to reiterate, volumes or no volumes, the series were 100% marked as completed in their publication status prior to reinstall. 

### Publication status pictured
![image](https://github.com/Kareadita/Kavita/assets/108381076/fd4b6386-be4b-42fd-9414-7fdec5be16b3)

### My chapter count, I have all the chapters.
![image](https://github.com/Kareadita/Kavita/assets/108381076/9c956b6a-e78c-4f1a-9f9d-1e8e62e0cfdf)

### The series showing up under `Completed` prior to reinstall.
![image](https://github.com/Kareadita/Kavita/assets/108381076/c70a4cea-6182-4c05-b7f9-76dc31f7b995)

### Lastly, my ComicInfo
![image](https://github.com/Kareadita/Kavita/assets/108381076/46a341ef-dcb9-4310-8f07-ce2469935a5a)

### What did you expect?

For the publication status to be marked as complete

### Version

0.7.13 Nightlky

### What OS is Kavita being run on?

Docker

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

Might potentially have some relation to #1697 
Not sure though.

**Comment by majora2007** [comment]
This is working correctly.

You said there are either 7 volumes or 7 chapters. The Count field doesn't specify volume/chapter, it's made for comics. 

Then you have 19 chapters. When the number or chapters is higher than the Count, Kavita is smart enough to know that it's bad data or incorrect. 

The reason why the prior version was Completed was that the publication logic was fixed up to work better in more cases:
> Fixed: Fixed a bug where a Ended series could get flagged as Completed Publication Status
>  Kavita will fallback much better for Series that have a total Count in how it matches against Volumes or Chapters. These will need a force scan to pickup, but I think overall, leads to a much better experience.

I just validated this as well that when you have Count set to the number of chapters in a series, it moves from Ended -> Completed.

**Comment by lyingloverr** [comment]
Yes the issue arises because Komf and MangaManager by default add the `Count` tag based on Volumes, and there is no way to make them behave differently, iirc. So this in turn kinda screws over anyone, such as myself, that doesn't really base their collection off of volumes and instead just chapters. Most sites don't support volumes either, MangaDex is the only major one afaik. So in order for it to be correct you would have to manually tag all your non-volume based manga according to Chapter count. This could be a hassle on a large library.

**Comment by majora2007** [comment]
Yes, it's annoying, but the ComicInfo standard isn't very flexible. Luckily Kavita does support both, so a script to scrape the data from AniList would work if you wanted to build a tool like that.

**Comment by lyingloverr** [comment]
Actually since my last comment i did work out a solution. Using komf in API mode only sets my series to Ended. its a bandaid solution but its much better than having 90% of my library set to `Ongoing`.  Things will show as, for example, `0/12 Ended` which honestly works for me. 

Cheers!!

**Comment by Sonny-Crockett** [comment]
Would it be possible to have a toggle in Kavita for ignoring updating if Publication if status is already marked "Completed"? In basically every other situation the Count logic makes sense, but typically if something is completed, its done. That could help with Kavita not over-writing komf or custom inputs.

Toggle so if people prefer or workflow supports the current Count logic, nothing changes for them, gotta be opt-in.

**Comment by majora2007** [comment]
@Sonny-Crockett raise a feature request. I don't read closed issues for planning future changes.

**Comment by Sonny-Crockett** [comment]
My bad! I have even made requests there before, I forgot 🤦‍♂️. 

Thanks!

https://github.com/Kareadita/Kavita/discussions/3033
