### ISSUE TITLE
[Enhancement] Allow testing email settings without saving (0.7.14)

### ISSUE THREAD

**Issue by RobertD502** [Kareadita/Kavita#2702]
### What happened?

After updating to `0.7.14`, I transferred my `kavita-email` docker email settings to the admin email tab. Upon pressing the test button, I was met with this error:

![Kavita-email-test-fail](https://github.com/Kareadita/Kavita/assets/52541649/61cda318-195d-4b50-b41f-e1da5d18f341)

I was a bit confused as the settings should have worked. I then tried the same settings followed by saving them and then pressing the test button. Now, the test email sent without a problem:

![Kavita-email-test-success](https://github.com/Kareadita/Kavita/assets/52541649/f2d0b28a-9059-4471-81ed-8c4855982a23)

### What did you expect?

Although it may be seen by some users as a bug, this is more of an enhancement request to improve the end-user experience.

**When pressing the test button, Kavita should use the currently provided email settings instead of requiring the settings to be saved prior to testing.**

As it stands, a user has to save the settings prior to testing - this has one particular downfall for the end-user experience: A user utilizing the test button, prior to saving, may be led to believe that their settings are incorrect.

Side note: The github issues template needs to be updated to reflect `0.7.14` being the latest version number

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.13 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Microsoft Edge

**Comment by majora2007** [comment]
What was the error in your logs?

**Comment by RobertD502** [comment]
```
[Kavita] [2024-02-08 17:11:47.137 -05:00  44] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/settings/test-email-url responded 200 in 1.9997 ms
```

That is the only thing logged (I am inspecting the logs directly with `docker logs kavita`).

`Note:` If a valid setting was saved prior to testing, the test e-mail will always be successful regardless of if a user changes one of the fields (as long as the user doesn't save prior to testing).

For example:
1) I create a valid setting, save it, and then press the test button to confirm that it worked.
2) I then change the valid username of `mygmail@gmail.com` to `mygmail@gmail.commmmm` and press the test button (without saving).
3) The test will be successful as it will use the settings stored on Kavita to test instead of the values that are currently present in the fields on the frontend.

**Comment by majora2007** [comment]
While I do agree, it might be confusing that you need to save, in the end, I think that is the better flow to go with. I added an extra warning to inform the user they must save before using Test button.
