### ISSUE TITLE
0.7.14.0 Update Loading Window and Red Message

### ISSUE THREAD

**Issue by kim08384** [Kareadita/Kavita#2704]
### What happened?

<img width="1760" alt="20240209_100428" src="https://github.com/Kareadita/Kavita/assets/149031356/a1b1dbfd-884a-4fd6-950e-e4f2207ffcab">

0.7.14.0 After updating, access the administrator dashboard, check the system information
If you check it, there's a loading in the update details
A red window appears in the attached image, and a green loading mark appears
It keeps coming out

### What did you expect?

0.7.14.0 After updating, access the administrator dashboard, check the system information
If you check it, there's a loading in the update details
A red window appears in the attached image, and a green loading mark appears
It keeps coming out

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Chrome

### Additional Notes

<img width="1760" alt="20240209_100428" src="https://github.com/Kareadita/Kavita/assets/149031356/9e2f485e-30fd-4b9d-99ed-cbb51e0a8e18">

**Comment by majora2007** [comment]
Can you try again? That error means that Github had a moment that it couldn't resolve the request.

**Comment by kim08384** [comment]
> 다시 시도 할 수 있습니까? 이 오류는 Github가 요청을 해결할 수 없는 순간이 있었음을 의미합니다.

It's the same if you try again
It's the same when you reboot NARS
It's still like this
<img width="1115" alt="20240209_233406" src="https://github.com/Kareadita/Kavita/assets/149031356/620102bc-17c8-417e-8704-44f0cc9a1bf7">
