### ISSUE TITLE
Statistics for formats are not being updated

### ISSUE THREAD

**Issue by Sulframus** [Kareadita/Kavita#2705]
### What happened?

The statistics in the admin tab showing the formats are not updating, even after force scan and allowing days to pass.

### What did you expect?

Stats to update.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Safari

**Comment by Bartype** [comment]
I can add to this, statistics are not being updated anymore, while at first they did. I am using the linuxserver docker version of kavita.

**Comment by majora2007** [comment]
I can't reproduce the Formats. I had 376, added a new cbr file and scanned library, refreshed the dasbhoard and it's reporting 377. 

Can anyone give more information?
