### ISSUE TITLE
Updating from old version seems to have broken database

### ISSUE THREAD

**Issue by Kalidibus** [Kareadita/Kavita#2713]
### What happened?

I was running on 0.6.10 and went to pull the newest docker image (0.7.14). I didn't realize that the two version were incompatible. 

When this gave me "your account is disabled" errors, I searched here and saw that the solution was to update more slowly, and from https://github.com/Kareadita/Kavita/issues/2517#issuecomment-1877276546 I tried updating to kizaing/kavita:nightly-0.7.1.4 as I couldn't find any docker images without the nightly tag. 

Loading this one up prompted SQL errors, so I gave up and went back to 0.6.10. Only problem is, I'm getting the same SQL errors "SQLite Error 1: 'no such column: s.NameLocked'. " and my Libraries are all gone. 

Thankfully I have a backup I can restore from, but other than restoring that and continuing on 0.6.10 I'm not really sure how to proceed if I wanted to upgrade (I could just completely start over with a new DB, but I had a lot of custom covers and stuff which would be a bit of a pain to re-do). 

### What did you expect?

A way to update, ideally with considerations for older versions (either a full block on database conversion with a relevant error message, or a longer migration period), as many of us like to leave our docker containers alone for a while when they're stable.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
You cannot update that many versions in one go. There is an update order posted (almost everywhere). See here:
v0.5.6 > v0.7.1.4 > v0.7.3.1 > v0.7.6 > v0.7.14.

Every 6 months I remove heavy manual migrations hence why you cannot jump ahead so much. As of v0.7.14, there shouldn't be any more issues with jumping, but as of now, you need to either do 2 versions (note, we don't follow semver) or follow the guide above. 

Edit: Thanks for updating! It's a huge issue given Kavita's fast development pace.

**Comment by Kalidibus** [comment]
> You cannot update that many versions in one go. There is an update order posted (almost everywhere). See here: v0.5.6 > v0.7.1.4 > v0.7.3.1 > v0.7.6 > v0.7.14.
> 
> Every 6 months I remove heavy manual migrations hence why you cannot jump ahead so much. As of v0.7.14, there shouldn't be any more issues with jumping, but as of now, you need to either do 2 versions (note, we don't follow semver) or follow the guide above.

Was the docker image of "kizaing/kavita:nightly-0.7.1.4" incorrect then? Because I was trying to follow that order. If there's somewhere with docker images without the nightly tags I could not find them.

**Comment by majora2007** [comment]
The docker repository moved in v0.7.8. You also do not update to nightly ever. You would use the exact tag. Let me get you the links:

v0.7.1 is a year old, hence why it might have been hard to find. 

v0.7.1
https://hub.docker.com/layers/kizaing/kavita/0.7.1/images/sha256-a0e0f511b48f7117746c3e738754c9a63612d9bce105a44f5f07eaf153cf4075?context=explore

v0.7.3.1 (looks like the hotfix was just overwritten)
https://hub.docker.com/layers/kizaing/kavita/0.7.3/images/sha256-d9dce54f23b7a8017ec2a6abb95737eb0e0b478d48d2328323f6dfa4a9bb900b?context=explore

 v0.7.6
https://hub.docker.com/layers/kizaing/kavita/0.7.6/images/sha256-f301678cb64eb1e24412eb5d6ac5d838df9d37f8f7fd1742c1317ffbd5182009?context=explore

v0.7.14 (notice the change in repo here)
https://hub.docker.com/layers/jvmilazz0/kavita/0.7.14/images/sha256-9cbe62ea84c250f41e0f04f620537a4687345868612a40c840e464f34b5bbfe5?context=explore

Remember, anything that says "nightly" is a build for testers and may contain code that breaks your DB. You should always use the exact tag (stable) or latest. 

Hope this helps. Let me know if you need anything else.

**Comment by majora2007** [comment]
Sorry, I've been a bit busy, going to get to it this week.

**Comment by DieselTech** [comment]
Just took a look at your `kavita_old_b4updating.db` and it looks like it's already been upgraded. I see migrations from `7.0.10` and `7.0.12` that shouldn't be there if you didn't already try upgrading it. That means you need to go back further and use a older backup. One that hasn't been ran against a new version.

**Comment by DieselTech** [comment]
@Kalidibus Were you able to use an older backup?

**Comment by DieselTech** [comment]
No response from user, closing ticket. If you're still having this issue you can reopen it.
