### ISSUE TITLE
epub files are downloaded as zip files

### ISSUE THREAD

**Issue by demaniak** [Kareadita/Kavita#2715]
### What happened?

When downloading epub files, the result is a zip file.

The zip file can not be used by ebook readers (I tried a few different ones on android).
Renaming the file to epub extension does not help.

The archive seems ok (files can be extracted).

### What did you expect?

An epub file to be downloaded, which can be opened and read in a compatible ebook reader

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Firefox, Chrome

### Additional Notes

I'm also running calibre-web currently, backed by the same calibre library backing kavita . 
Downloading the exact same book via calibre-web results in the expected, and readable epub file.

Might be regression of https://github.com/Kareadita/Kavita/issues/399 ?

**Comment by DieselTech** [comment]
I just tried on Desktop and on Chrome Mobile and wasn't able to reproduce. Is there any additional steps you might be taking that would help us identify this?

**Comment by demaniak** [comment]
This does not seem to happen with every book, but so far I've not really been able to spot a reason for when it does happen

**Comment by demaniak** [comment]
@DieselTech - without actually sharing the problem books in question, not sure what I can do.

Can I possibly check for anything in the books where the issue occurs? Older formats or something?

**Comment by DieselTech** [comment]
Are you clicking download on a specific book once you are already in a series? The only time I see a zip file download is when I hit download at the series level.

**Comment by majora2007** [comment]
Please add reproduction steps to help us debug and fix the issue.

**Comment by demaniak** [comment]
*sigh* ok, that could be it, just tried with a book that I know is single - results are as expected.

Sorry for the bother, closing this one as "user stupidity" and "not understanding how series are handled".

Thanks for the help.

PS: Kudos on the fast response - that was brilliant :)
