### ISSUE TITLE
400 Error There was an issue saving progress

### ISSUE THREAD

**Issue by Dragonatorul** [Kareadita/Kavita#2719]
### What happened?

While reading a manhwa in continuous reading mode, a red banner is displayed in the lower right corner which says "400 Error There was an issue saving progress" similar as seen in issue #878  

The progress in individual chapters appears to be saved most of the time, however the "continue" progress isn't saved. So when I click on the "Continue" button I'm taken to chapter 2, even though in my previous reading session I progressed to chapter 18. However, when I progress from Chapter 2 to Chapter 3 the reader automatically scrolls down to the last page. This is in most chapters, some of them only scroll down part way.

### What did you expect?

I expect to be able to continue from where I left off when pressing "Continue".

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome, Safari

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Relevant log output

```shell
[Kavita] [2024-02-15 21:04:04.304 +02:00  159] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 400 in 11.3615 ms
   at API.Services.ReaderService.SaveReadingProgress(ProgressDto progressDto, Int32 userId) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\ReaderService.cs:line 282
   at API.Data.UnitOfWork.CommitAsync() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Data\UnitOfWork.cs:line 92
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
--- End of stack trace from previous location ---
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at System.Data.Common.DbDataReader.NextResultAsync(CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteDataRecord.Dispose()
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
[Kavita] [2024-02-15 21:04:04.298 +02:00  159] [Error] API.Services.ReaderService Could not save progress
[Kavita] [2024-02-15 21:04:04.297 +02:00  159] [Error] Microsoft.EntityFrameworkCore.Update An exception occurred in the database while saving changes for context type 'API.Data.DataContext'.
[Kavita] [2024-02-15 21:04:08.203 +02:00  84] [Error] Microsoft.EntityFrameworkCore.Update An exception occurred in the database while saving changes for context type 'API.Data.DataContext'.
[Kavita] [2024-02-15 21:04:08.198 +02:00  58] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=33233&apiKey=******REDACTED******&page=45" responded 304 in 2.4668 ms
```

### Additional Notes

I am running Kavita in Docker on a debian 11 guest OS VM with the volume on an SSD.

**Comment by Dragonatorul** [comment]
Note: this seems to happen only when switching to a new chapter.

**Comment by majora2007** [comment]
Do you have WAL enabled on your DB? (See FAQ on wiki)? This is the usual fix to this issue.

**Comment by Dragonatorul** [comment]
I enabled WAL and it seems to have fixed this issue. Thanks!

**Comment by Dragonatorul** [comment]
I hate to have to reopen this issue, but the issue appears to persist. The 400 errors are much less frequent, but the logs are still showing a lot of `database is locked` errors. That is even after having enabled WAL on the DB.

I'm not sure if this is related, but the errors are at least correlated with a new weird behavior: when scrolling a webtoon, sometimes the pages are shuffled randomly, and even the same page is repeated multiple times. This obviously makes it impossible to read the chapter. I suspect this is at least in part caused by the fact that webtoons/manhwa often have a lot of relatively small "pages", and scrolling through a chapter results in loading a lot of pages very quickly. At least when compared to reading a regular comic or manga. 

@majora2007 Is there a way to migrate to a dedicated DB such as MariaDB or PostgreSQL? I wouldn't mind reinstalling and starting from scratch if a migration is not possible. 

EDIT: One more thing to note. I'm not sure if this is related or not, but the server is also under high CPU load at this time as I'm using it for some video transcoding.

**Comment by Dragonatorul** [comment]
[_kavita_logs.txt](https://github.com/Kareadita/Kavita/files/14670323/_kavita_logs.txt)

Maybe the issue with the scrambled pages isn't related after all. Here are the logs from a recent event where the pages got scrambled. Should I raise a new issue? 

For the record this is happening in any browser on the iPad and in Firefox and Safari on my Macbook Air M1. I didn't check if it happens on Windows, but it doesn't seem to matter. 

This is an example of how it looks like when the pages get scrambled. Notice the jarring cut between panels. That's where the page cuts and displays unrelated panels. 
![image](https://github.com/Kareadita/Kavita/assets/109987846/417c3082-5a27-42e8-bdac-2079e1d4f769)

**Comment by majora2007** [comment]
There is no way to use a different db with kavita. It's coded only for SQLite. Please create different issues for different problems you're facing.
