### ISSUE TITLE
While on dashboard or Main Library view, the library details cannot be saved when the sidebar is collapsed

### ISSUE THREAD

**Issue by Nebelherr23** [Kareadita/Kavita#2726]
### What happened?

When on the dashboard or main library view, you cannot click the save button at any time, because it remains disabled.

### What did you expect?

I would expect to be able to click the save button, thus being able to save the edited library settings.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Firefox, Chrome

**Comment by majora2007** [comment]
Can you please attach reproduction steps?

**Comment by Nebelherr23** [comment]
1. Collapse sidebar
2. In Main Library view, open the Library Settings via the 3-dot menu -> Settings (I found it works when doing it from the admin settings)
![repro1](https://github.com/Kareadita/Kavita/assets/138651224/9dc844b9-68fe-4484-b8c8-4db1f9e96b7f)
![repro2](https://github.com/Kareadita/Kavita/assets/138651224/0fb84e1e-3d8d-4c3b-99a2-ba2f1f0b79b2)
3. Edit something in the settings, try to click save

**Comment by majora2007** [comment]
Ahh I understand. When invoking it NOT from the side nav. Thanks, will look into it.
