### ISSUE TITLE
After deletion of a comic book set, a rescan of the library will not reimport it.

### ISSUE THREAD

**Issue by maximo1984** [Kareadita/Kavita#2727]
### What happened?

I was attempting to remove some comic sets from a collection and was unaware that it was actually going to remove from Kavita completely. There does not seem to be a feature for removing from a collection. I attempted to rescan the library folder and the missing comic sets did not reimport. I then moved them out of that folder on my harddrive, rescanned, then put them back in and rescanned again and this still did not remedy the issue.

### What did you expect?

I expect the missing files to reimport.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
Can you help me understand a bit more? When you remove a series from a collection, it does not remove the series itself. 

Can you look at the logs (or attach) which will tell us why it's not re-importing and can you also validate via search that one of the files is not still in the system?

**Comment by maximo1984** [comment]
There is no "remove from collection". So that's where I was confused, thinking that "other > delete" was the removal from collection, but it was removal from the library.

I just started using Kavita yesterday. If you can point me where to find the logs I can post. (Ubuntu 22.04)

Edit: Probably possible to simply remove the library and reimport it, but this is not a good solution.

**Comment by majora2007** [comment]
You can first get logs in config/logs or download them from admin > tasks .

To remove a series from a collection you go into edit collection and I select the series you no longer want in that collection.

**Comment by MrJackLantern** [comment]
Made also this mistake. So an "Remove from Collection" button would be nice (under "other").
