### ISSUE TITLE
Cover Images Not Saving

### ISSUE THREAD

**Issue by maximo1984** [Kareadita/Kavita#2728]
### What happened?

After changing the cover image for epub and comic books, the image changes at first, but then clicking off to something else and coming back, the image is not saved.

### What did you expect?

I expect the cover image to save.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
Images are cached in the browser. When you change, Kavita tells you it may take a few minutes to take effect. Please refresh your browser after a few minutes. It should be reflected.

**Comment by maximo1984** [comment]
Thanks
