### ISSUE TITLE
Mail server configuration doesn't allow having empty login / password

### ISSUE THREAD

**Issue by llaumgui** [Kareadita/Kavita#2739]
### What happened?

When I set my mail server configuration without login / password, I have an error: `You need to fill in more information in settings and ensure your account has a valid email to send a test email`.

### What did you expect?

Allowed to use empty login / password.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
{"successful":false,"errorMessage":"You need to fill in more information in settings and ensure your account has a valid email to send a test email","emailAddress":"******@*****.**"}
```

**Comment by majora2007** [comment]
I have fixed this already in the nightly release. I will have it fixed for next stable (since LSIO doesn't have nightly where it's fixed), but the next stable is some time away as I'm bringing some big items that require substantial development time and testing time.
