### ISSUE TITLE
Separate Comic Volumes grouping same Issue #'s together 

### ISSUE THREAD

**Issue by maximo1984** [Kareadita/Kavita#2743]
### What happened?

Unless I am using the v# wrong, I believe these should automatically separate out into volumes, but they are not. It is even group the #001 Annual with the #001 of v1 and v2.
![Screenshot from 2024-02-25 05-34-40](https://github.com/Kareadita/Kavita/assets/40921347/73a10f81-fe3c-4e28-8492-b966734c897d)

### What did you expect?

see above

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
Would need a bit more information like what's in the ComicInfo as usually comics are well tagged and ComicInfo trumps filename parsing. 

You are correct that vol 1 and vol 2 should split. It might be also filename parsing failing for some naming convention, like try using "vol 1" instead of "v1"

**Comment by maximo1984** [comment]
I see, I tagged them myself in comictagger, I will redo them and check for correctness.

**Comment by DieselTech** [comment]
@maximo1984 if you're still having this issue reach out to us on discord or open a new issue.
