### ISSUE TITLE
Storyline Web link favicon not exist

### ISSUE THREAD

**Issue by daydreamrabbit** [Kareadita/Kavita#2749]
### What happened?

![스크린샷 2024-02-27 213729](https://github.com/Kareadita/Kavita/assets/80138664/bc475602-7aa6-4988-84a5-9e8bbca11db8)

### What did you expect?

A favicon is created for the default main link, but the favicon is not created for the Storyline link and is left blank.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Microsoft Edge

**Comment by DieselTech** [comment]
Just to add some extra info here, this is when the series is in list view. The spot for the link has the URL embedded, just not the icon. 

![image](https://github.com/Kareadita/Kavita/assets/30128380/17bbe2b3-82c3-4f15-a53b-6506014cdde5)
