### ISSUE TITLE
Series name "&" created an issue

### ISSUE THREAD

**Issue by nuclearedc** [Kareadita/Kavita#2753]
### What happened?

After I added a manga series in a folder named "&" containing the files: "& V01.cbz", "& V02.cbz"...
(https://myanimelist.net/manga/23519/_)
Every manga series I added afterwards in the hosting media folder for that library would not be added to the library itself.
I would have an error that the volumes being added are already existing.
When scanning the library or force scanning the library, I would get the same error.

### What did you expect?

I expected for Kavita to create a series with the name "&" and not interfering with other series folders.

In the guidelines for Naming convention / File Structure, there was no indication that special characters could create an issue. 
There was even an example with a series name using exclamation mark:
(Library Root
  ┖── Again!!
      ┖── Specials
            ┖── Again The After Story SP01.cbz)

I ended up renaming the folder series "And" with "And V01.cbz", "And V02.cbz",...
That solved my issue.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

**Comment by majora2007** [comment]
I'm sure you can imagine it's difficult parsing out useful information from filenames when there is no uniform naming system, so sometimes edge cases like this happen.

However, a series named & is not common and in my opinion an acceptable edge case. For those edge cases you can use comicinfo to enforce the series name for the files. 

Hope you can understand my position.

**Comment by nuclearedc** [comment]
Thank you for the quick reply and I totally understand that the naming of that series was very uncommon.
It is a very acceptable edge case.

Thank you for the recommendation of using comicinfo to enforce the series name, I didn't think about that before renaming the series to "And". 

My request was more to add some sort of disclaimer in the Naming guide webpage. (https://wiki.kavitareader.com/en/guides/managing-your-files#:~:text=Naming%20convention%20%2F%20File%20Structure,-It's%20important%20to&text=Kavita%20uses%20parsing%20(not%20folder,root%20level%20of%20the%20library.)
Something like "Series name with less than x characters or with the following special characters &, etc. could create errors"

That webpage was the first thing that I checked and I could not understand why the folders that met the naming convention were not being added to the library.
It took me a week to figure out that it was because of the "&" series already in the library.

**Comment by majora2007** [comment]
The problem with a disclaimer like that is it isn't true. You can have A - vol 2.cbz and Kavita will work fine. But some non-alpha characters definitely will trip it up.

@DieselTech would appreciate your thoughts on this for the new wiki when you have some time.

**Comment by nuclearedc** [comment]
Once again, thank you.
And thank you for looking into a potential disclaimer in the wiki (but the edge case may be so unique that it's most likely not warranted)

If I had known that the support on GitHub would be so reactive, I would have reached out here instead of struggling for days trying to figure out and solve the issue by myself...

**Comment by majora2007** [comment]
Yes we also have a discord with even faster support, so next time you hit a block, don't hesitate to reach out.
