### ISSUE TITLE
[epub] 400 Error - Could not find the appropriate html for that page

### ISSUE THREAD

**Issue by YodaDaCoda** [Kareadita/Kavita#2759]
### What happened?

I started reading a new epub and encountered the following error after about 3 pages.

![image](https://github.com/Kareadita/Kavita/assets/365349/20f18da9-3138-4e68-adcb-602c9d80deb8)

### What did you expect?

Expected the next page in the epub to open

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
kavita            | [Kavita] [2024-03-04 13:06:01.116 +11:00  6] [Error] API.Services.BookService There was an issue reading one of the pages for /app/kavita/config/cache/213/Christelle Dabos - A Winter's Promise.epub
kavita            | System.NullReferenceException: Object reference not set to an instance of an object.
kavita            |    at API.Services.BookService.InlineStyles(HtmlDocument doc, EpubBookRef book, String apiBase, HtmlNode body) in C:\Users\Will\github\Kavita\API\Services\BookService.cs:line 390
kavita            |    at API.Services.BookService.ScopePage(HtmlDocument doc, EpubBookRef book, String apiBase, HtmlNode body, Dictionary`2 mappings, Int32 page) in C:\Users\Will\github\Kavita\API\Services\BookService.cs:line 922
kavita            |    at API.Services.BookService.GetBookPage(Int32 page, Int32 chapterId, String cachedEpubPath, String baseUrl) in C:\Users\Will\github\Kavita\API\Services\BookService.cs:line 1162
kavita            | [Kavita] [2024-03-04 13:06:01.118 +11:00  6] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/book/213/book-page?page=3 responded 400 in 4.6759 ms
```

### Additional Notes

I've debugged the error & will raise a PR soon

**Comment by DieselTech** [comment]
Resolved by PR https://github.com/Kareadita/Kavita/pull/2760
