### ISSUE TITLE
Scan Library not importing any titles.

### ISSUE THREAD

**Issue by maximo1984** [Kareadita/Kavita#2761]
### What happened?

At first I thought perhaps it was due to trying to import obscure titles, but will not work with even mainstream marvel.

### What did you expect?

see above

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
Please attach logs from a forced library scan. Can you elaborate more information, like library type, file types, etc.

**Comment by maximo1984** [comment]
Having a hard time finding where the log files are. It is not listed on the wiki

**Comment by majora2007** [comment]
Logs can be found in config/logs or can be downloaded from admin > tasks > download logs

**Comment by maximo1984** [comment]
[kavita20240304.log](https://github.com/Kareadita/Kavita/files/14484712/kavita20240304.log)

**Comment by maximo1984** [comment]
is that not helpful?

**Comment by maximo1984** [comment]
Hope there is a solution soon, I just became a monthly contributor :(

**Comment by majora2007** [comment]
First off, I see some database is locked. You can fix this with:
https://wiki.kavitareader.com/en/faq#q-im-seeing-database-is-locked-errors-in-my-logs

Second, I'm not seeing Scan library not importing any titles. I see many series being imported. So you're going to need to provide more information.

**Comment by maximo1984** [comment]
Thank you . I will try to unlock the SQLite file following your link instructions. However, there are multiple files with this pre-fix. Is it one of these? Might consider elucidating this on the help page.
![Screenshot from 2024-03-06 08-40-18](https://github.com/Kareadita/Kavita/assets/40921347/675c12d2-49c1-4f20-b466-179f3115df3d)

How does something like this happen anyway? Working fine one minute, go to sleep, reopen, not working. NO changes made.

edit: Nothing is ever crystal clear with any of this stuff. I installed sqlite on linux but don't see instructions anywhere how to start it. Plenty of instructions what to do after it started though.

**Comment by maximo1984** [comment]
Figured it out. But there is no SQLite.db file. I am assuming this should be performed on my SQLite.db meaning Kavita.db. SO I did that.
![Screenshot from 2024-03-06 08-53-31](https://github.com/Kareadita/Kavita/assets/40921347/d45e8d13-a517-446c-9730-0dd7630c4c69)
![Screenshot from 2024-03-06 08-54-10](https://github.com/Kareadita/Kavita/assets/40921347/8ef3f62b-b74e-4915-a88c-8f4273b8be3e)

then re-scanned a library. Nothing came up. Here is the log.
[kavita20240306.log](https://github.com/Kareadita/Kavita/files/14510788/kavita20240306.log)

**Comment by majora2007** [comment]
Okay can you please provide the series that are "not importing". As I mentioned, from the original logs, I saw many series being imported. I can't help without more information.

**Comment by Cantello** [comment]
I have a rather similar problem, as of this morning, no more scans seems to be performed. Log is attached. Kavita is running in a docker container on a debian system with the latest version (0.7.14). The database is on a local drive mounted as a bind and the books are stored on an external NAS shared via SMB. I did not knowingly change anything and my docker-compose.yml is fairly standard apart from the changed mount binds. The docker container was restarted multiple times to start fresh. "Scan queued for [library name]" appears as an info pop-up but nothing seems to happen.

[kavita20240307.log](https://github.com/Kareadita/Kavita/files/14522987/kavita20240307.log)

**Comment by majora2007** [comment]
@Cantello your logs aren't very helpful because you're on too high of a log level. Please enable debug logging. You might want to try a forced scan. I'm not 100% familiar with SMB, but if Kavita doesn't see either new folders or modified folders since last scan (some OS don't report well), then it will skip. Debug logs will help us understand more. 

Also please let me know if you're using folder watching or not. This looks like folder watching is reporting a scan is already enqueued.

**Comment by Cantello** [comment]
@majora2007 Sorry for the non-debug logs. I have attached new logs with debugging enabled, although I can't see much of a difference. I cut out several hundred lines of Kavita refreshing covers, which was running fine. Still no library scan, whether forced or not. I can see the API call in the log but nothing happens after that. I have now disabled folder watch for all libraries and globally.

Anything you can see in this log?

[kavita20240307_debug.log](https://github.com/Kareadita/Kavita/files/14524763/kavita20240307_debug.log)

**Comment by majora2007** [comment]
@Cantello  let's move you to a separate issue. Too many users are hijacking this with different issues. Please create an issue with your logs attached. 

Please provide also the mount point and which docker container you are using.

**Comment by maximo1984** [comment]
It is literally the same issue.

**Comment by Cantello** [comment]
> @Cantello let's move you to a separate issue. Too many users are hijacking this with different issues. Please create an issue with your logs attached.
> 
> Please provide also the mount point and which docker container you are using.

[Done](https://github.com/Kareadita/Kavita/issues/2768).

**Comment by maximo1984** [comment]
I created a fresh install on a separate laptop. The same comics that imported on library scan for my desktop won't even get scanned on this laptop version.

[kavita20240308.log](https://github.com/Kareadita/Kavita/files/14536064/kavita20240308.log)

Have you tried it on your computer just to rule out this isn't a widespread issue? Already a 2nd user has popped on here with the same problem.
