### ISSUE TITLE
Card/list switch slow performance

### ISSUE THREAD

**Issue by moisesbelda** [Kareadita/Kavita#2763]
### What happened?

With a large number of cards (issues) when you switch from cards to list, performances is very slow, almost unrresponsive. 
Tested in :
Firefox : slow
Safari : slowest

Also in Safari, when the list of issues is presented (instead of Cards), the UI seems slower and almost not responsive).

### What did you expect?

No performance issues

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Mac

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Safari

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Firefox, Safari

### Relevant log output

```shell
No logs problem detected.
```

**Comment by DieselTech** [comment]
Can you give some background info on your hardware running kavita? What CPU it has, number of cores, are you using a SSD for the database? 

How many issues are in the series that you're trying to view? I tried this with a series that had ~200 issues and it was pretty snappy yet.

**Comment by moisesbelda** [comment]
Running Kavita using a
-  Synology NAS with docker. 10GB ram and CPU is Intel Celeron J3355 dual-core 2.0 GHz.
-  HDD are not SSD
-  Series of 300 issues. 
It is not a high performance machine but I don't have any performance issue rendering the card list  for this series, or others. The performance problem happens seems happeninng only when I click on the LIST view of a large number of issues (more than 200).

**Comment by DieselTech** [comment]
Took a look at this, seems it's all the client side rendering that takes up a bulk of the processing power. It's hitting the API for each file in the series to get their details, but it's creating the view that takes a long time. 

![image](https://github.com/Kareadita/Kavita/assets/30128380/052cb696-e7c5-4f8b-bd66-b7c06a69d879)

**Comment by majora2007** [comment]
Ahh it's in the card item view. I might need to tackle that appropriately then. In order to show the summary, it makes a call to collect the information needed for each item. I don't use that view often nor for large series, so I never got to experience it like this. I'll take a look at what can be done.
