### ISSUE TITLE
Some books keep disappearing without a known reason

### ISSUE THREAD

**Issue by mangosaftlama** [Kareadita/Kavita#2764]
### What happened?

I added a new book (.epub) format to my kavita library and after a short period of time, the book just disappeared. Simultaneously another whole **series** with two books disappeared. There are no relevant media issues coherent to this problem. 

I found a way temporarily solve this problem:
- Move the missing book files (.epub) to another directory
- Move them to their old directory
- Scan the library again

After this steps, everything looks like it should again, but the books keep vanishing from the Kavita UI after a short period of time.

### What did you expect?

I expected that the book which I added to my library would be visible in the UI.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

Running on a virtual root server with Ubuntu 22.04.3 LTS x86_64 installed, kernel version 5.15.0-94-generic.

**Comment by majora2007** [comment]
Can you attach logs from your scans where they either appeared or were removed please?

**Comment by mangosaftlama** [comment]
[library-scan-log.txt](https://github.com/Kareadita/Kavita/files/14487274/library-scan-log.txt)

I did a scan around 22:13 where the books appeared again, because as I already described I moved the files into another directory and then moved it back into the old directory.

**Comment by majora2007** [comment]
Okay but can you help me help you? Can you give me a series name that is appearing and disappearing? 

I can read the logs, but without the context, I can't actually discern much.

**Comment by majora2007** [comment]
Can you tell me explicitly what files you moved out and back in again?

**Comment by mangosaftlama** [comment]
Yes, of course. I know that books from the following files are disappearing:

1. "K:\jann\books\Alles\Der Herr Der Ringe\Der Herr der Ringe - Band 1.epub"
3. "K:\jann\books\Alles\Der Herr Der Ringe\Der Herr der Ringe - Band 2.epub"
4. "K:\jann\books\Alles\Der Hexer\Der Hexer - Das Erbe der Elfen.epub"
5. "K:\jann\books\Alles\Der Hexer\Der Hexer - Der letzte Wunsch.epub"
6. "K:\jann\books\Alles\Winnetou\Winnetou - I.epub"
7. "K:\jann\books\Alles\Winnetou\Winnetou - II.epub"
8. "K:\jann\books\Alles\Winnetou\Winnetou - III.epub"
9. "K:\jann\books\Alles\Winnetou\Winnetou - IV.epub"
10. "K:\jann\books\Alles\Achtsam morden - Dusse, Karsten.epub"

I also discovered two things:
- All of the disappearing books except the 9th one which I listed above are grouped into a series with the help of this script https://gist.github.com/duplaja/8605140e6f84d6dba9c765f264a40ce2
- If I move one file from the disappearing books and then trigger a scan then all the books show up, but if I do a scan for a 2nd time all the books which showed up are disappearing again

**Comment by majora2007** [comment]
Can you dm me the first epub of der hexter and winnetou?

**Comment by majora2007** [comment]
I took a look and not sure to be honest what the underlying issue is. Perhaps we can do a call in discord where you show me the files and we can walk through together? 

The only time that series are removed like this is if you manually delete from Kavita DB, the series name is changed (so it would delete and re-add with new name), the series is no longer there (all files are missing), or there is another series somewhere parallel to the root (this will log the error and send a message to the UI with that information).

**Comment by majora2007** [comment]
From the discord call, what I observed was:
1. There were loose leaf epubs at the library root. The logs did indeed say these files (in the nested folder were not found and thus removed). 
2. Once we moved the loose leaf files into a nested folder, it fixed itself.
