### ISSUE TITLE
Folder structure with raw images mostly doesn't work

### ISSUE THREAD

**Issue by wcamicase** [Kareadita/Kavita#2769]
### What happened?

I currently have my libraries set as such:

- Root
   - Manga Name
      - Chapter 1
         - JPG files
      - Chapter 2
         - JPG files

And so on.

The thing is, it's working with some but most show up as "Chapter X" and I have my library all over the place.

For example, Shaman King has its chapters as "Reincarnation (chapter number)" and that works perfectly but others that don't work have "Chapter (chapter number)" for example.

I can't figure out what the problem is, as I'm following the guide with raw images and it seems like it should work consistently.

### What did you expect?

I was hoping to see every manga in the library with the respective chapters and pages inside, instead of each chapter showing up as an "individual manga".

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Chrome

### Additional Notes

I'm running Kavita on docker on a Synology NAS.

**Comment by majora2007** [comment]
What library type are you using?

**Comment by wcamicase** [comment]
The Type is Manga

**Comment by majora2007** [comment]
Can you switch to image library type and do a force scan? The image type was built explicitly for people that collect manga in loose leaf format.

**Comment by wcamicase** [comment]
I switched to Image type and forced a scan twice but sadly it didn't fix it.

**Comment by majora2007** [comment]
Okay took a look at this and you are correct, the image library type isn't working particularly well. I didn't get any validation from the users that wanted to keep the loose leaf image support once I delivered the improvements and new library type. 

I'll update the Image library to work better. I'm seeing with your structure it's taking the Chapter 01 as the series where it should be the folder above.
