### ISSUE TITLE
Mangas with chapters X.1, X.2, not working properly

### ISSUE THREAD

**Issue by wcamicase** [Kareadita/Kavita#2770]
### What happened?

I noticed that mangas that have chapters X.1, X.2, X.3, and so forth, Kavita will join them all as a single chapter and that's awesome, however, I can't seem to be able to read any further than the last page of the X.1.

Every page from that point forward is the same.

### What did you expect?

I expected to be able to read the remaining pages.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Chrome

### Additional Notes

I'm running Kavita on Docker on a Synology NAS.

**Comment by majora2007** [comment]
I need a bit more information on this? Are you saying you have Chapter 1, 1.1, 1.2 and Kavita is stacking them? 

Or is it like this? 
![image](https://github.com/Kareadita/Kavita/assets/735851/f464ea16-c683-4f4a-bb4a-11a23e932777)

**Comment by wcamicase** [comment]
The issue is as follows:

I have Chapters 1.1 and 1.2.
Kavita sees them as Chapter 1.

As I'm reading, I get to the last page of Chapter 1.1
![image](https://github.com/Kareadita/Kavita/assets/18102526/f2f5f904-2a91-4f9e-9c0d-ed74aa329723)

When I go to the next page (page 1 of chapter 1.2), I simply get the same page again
![image](https://github.com/Kareadita/Kavita/assets/18102526/156decda-c55e-44b2-9977-09e139f19d0f)

It shows the same page for the remaining pages, even though the number of pages is correct.
If I go back to the previous pages, it starts working as intended
![image](https://github.com/Kareadita/Kavita/assets/18102526/601dc650-0e31-4668-877b-8ac99a60ee22)

**Comment by majora2007** [comment]
What is your library type and filenames? I need to be able to reproduce to see how to fix it.

**Comment by wcamicase** [comment]
It's Image Type.

I have:

```
 To Your Eternity (Manga Name)
 - # 1
 - # 2
 - # 3.1
 - # 3.2
 - # 3.3
 - # 4
```

Not all chapters have a X.X, but the ones that do, suffer from this issue.

**Comment by majora2007** [comment]
Ohhh Image type. Are you on v0.8 or still on v0.7.14? Because I fixed a lot in that library type in v0.8

**Comment by majora2007** [comment]
Alright I was able to reproduce on v0.8.

**Comment by wcamicase** [comment]
Only now have I managed to get back to you, I also confirm that the same happened when I changed the Type to Manga.

**Comment by majora2007** [comment]
Yes, it is an issue when the underlying media type is images. I will work on it soon.
