### ISSUE TITLE
Downloading Series of Epubs Sends Unzipped Folders, Rather than Epub File Format

### ISSUE THREAD

**Issue by duplaja** [Kareadita/Kavita#2771]
### What happened?

When downloading a series that contains more than a single epub, the downloaded zip file contains unpacked folders for each epub, with the raw epub contents inside, rather than files in the .epub format.

### What did you expect?

The zip folder should contain files in the .epub format.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by ShivamAmin** [comment]
Ive noticed this for epub series' since atleast novemberish, only because I was travelling with spotty internet and was using an offline reader to read. Also just tried downloading larger manga series that ask if youre sure if you want to download. Those go through the download process on the server, then fail when it's being transferred to the client (Afaik), subsequent downloads also fail. Don't currently have bandwidth to look into this :(

**Comment by ShivamAmin** [comment]
Was able to download a manga series of cbz files, but it's extracting the cbz files into folders, and compressing the folders into seriesname.zip as well. The bug might be somewhere in DownloadController.cs. Starting point could be this pr #2599 though that's a guess for now.

**Comment by majora2007** [comment]
When you download a series, it will now unzip cbzs and create a mega zip file essentially. This is new behaviour as downloading a zip of zips isn't helpful.

This issue has a side effect where epubs are getting unzipped. I will work on it post Comic Rework.

**Comment by ShivamAmin** [comment]
> When you download a series, it will now unzip cbzs and create a mega zip file essentially. This is new behaviour as downloading a zip of zips isn't helpful.

Whats the use case for unzipping cbz? Sorry, I don't have experience reading mangas outside physical media and Kavita so far, so not sure about the flow for reading cbzs on external apps. Do you mean in external manga readers they expect a folder of images instead of cbz files?

**Comment by majora2007** [comment]
The use case is imagine you're downloading a full series or volume (which contains multiple individual cbz chapters) to your tablet for a flight. 

In the old model, it would download all the files as one zip, then you'd need to manually unzip them on your tablet. In the new model, it will process them on the server and present to you a zip that is immediately readable by other software. No extra step needed. There are no readers that I know of that support reading a zip of zips. 

For epub, this doesn't work though and that's the oversight. Epubs would need to be a zip of epubs.

**Comment by ShivamAmin** [comment]
yeah that use case isn't one I've encountered yet, so I was confused. Thanks for clarifying that for me.
