### ISSUE TITLE
JWT Refresh not occurring on devices sitting unused 

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#2784]
### What happened?

I wonder if there isn't a way to keep a key alive longer. Like if the refresh token expired it could reach out and get a new key if it's within x days. Or if there hasn't been any account related actions taken (like changing password, admin changing users settings) that it would refresh the login token. That way the user stays logged in unless something was done specifically that should log them out. 

### What did you expect?

Not to need to relog into every device I use (4+) every few days depending on which ones I'm using at the time. 

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
As mentioned in chat, I'm not having this experience. This issue is here for me to investigate and do extended testing on other user's devices to find a better experience so it matches mine.
