### ISSUE TITLE
Brightness control stop to work in "endlsess scrolling" Reading Mode

### ISSUE THREAD

**Issue by Gluca235** [Kareadita/Kavita#2785]
### What happened?

It work in single page, but brightness back to 100% in endless scroll, even if the bar is set at lower amount. 

I have other minor issues: a red banner appear sometimes with a 400 error if i scroll too fast, and it say can't save progress... but progress are always saved correctly.
If i change theme, it revert to Dark, if change reading options. I have multiple Dark theme in the Theme page...

![Screenshot 2024-03-16 at 12-52-31 Kavita - User Preferences](https://github.com/Kareadita/Kavita/assets/106470268/b2ac797c-1c98-47cb-aca7-89dbba0abfd7)

### What did you expect?

In the Theme folder i added only Nord, so i should see only Dark and Nord themes.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Firefox

**Comment by majora2007** [comment]
Please create separate issues for each of your issues. It helps drastically with tracking and closing them, as I only work one issue at a time. 

Also please provide some reproduction steps like the template describes. 

For your 400 errors, please see:
https://wiki.kavitareader.com/en/faq#q-im-seeing-database-is-locked-errors-in-my-logs
