### ISSUE TITLE
Cannot find "Send to Device" button

### ISSUE THREAD

**Issue by nothing2obvi** [Kareadita/Kavita#2786]
### What happened?

I am using version 0.7.14. I successfully set up the email settings, but I cannot find a "Send to Device" button when viewing a book while using Opera browser on a Mac. Do I need to be on the actual Kindle to see this button?

### What did you expect?

"Save to Device" button.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Other (List in "Additional Notes" box)

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

Browser: Opera version: 107.0.5045.36

**Comment by majora2007** [comment]
You need to setup a Device for the target email, so you can send it to that email.
https://wiki2.kavitareader.com/guides/user-settings/devices#devices

**Comment by nothing2obvi** [comment]
Got it. Thanks so much.
