### ISSUE TITLE
Not all pdf files are coming up to be displayed

### ISSUE THREAD

**Issue by tan-yong-sheng** [Kareadita/Kavita#2801]
### What happened?

I used a network mounted drive (=Google drive with rclone) and Docker to self host Kavita.

I found some of my pdf files not detected 

Here is my folder structure:

```
- Books
       - DevOps
             - Book 1.pdf
       - Math
             - Book 2.pdf
```

Here is the sample pdf file that is not recognized by the system: https://drive.google.com/file/d/12rYioE4Fy8vJG3I_XKcNdz263mkadZ-9/view?usp=drivesdk

https://drive.google.com/file/d/1sbfMPBXSLPMqPtD9N0_SNlbzVTqPtoR-/view?usp=drivesdk

Is it because of a metadata error?

___
Also, I have tried to read this similar issue, but still not sure what's wrong....

### What did you expect?

It can read all pdf files I have put inside the folder, based on folder structure I have mentioned above.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?
Ubuntu 20.04

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by scare376** [comment]
A few things. You can check the media issues section of the media tab in the admin dashboard to see if Kavita is unable to read an item due to an error. Also is the Books folder the root of the library or do you have separate libraries the DevOps and Math folders as the root folder?

**Comment by tan-yong-sheng** [comment]
Thanks for the info. I spotted my mistake that I set the library path to `/books/DevOps` and `/books/Math` to create libraries instead of creating one library with `/books` path.

Btw, I wish to ask another question:

I put both epub and pdf into the same directory as follows:

```
- Books
      - DevOps
            - Book 1.pdf
            - Book 2.epub
      - Math
             - Book 3.pdf
             - Book 4.pdf
```
I expect 2 series to be created, which supposed to be "DevOps" series and "Math" series.

But, to my surprise, there are 3 series created, namely "Book 1" series, "Book 2" series (which is in epub format) and then "Math" series.

Does that mean epub files cannot be in the same series with pdf? What if I want to put them in same series?

Thanks in advance?

**Comment by scare376** [comment]
A series can only have one file type correct. There is no way to merge them you would need to create a collection or reading list to get them in one place. Another thing to keep in mind. Epub uses series metadata to create a series in Kavita while PDF uses filename parsing at this time. The reason for this is that PDF metadata is a mess but there is a chance that the comicinfo spec might be used in its place.

**Comment by tan-yong-sheng** [comment]
I see, thanks a lot.

I think I had my problem solved.

Thanks, once again, for helping out.
