### ISSUE TITLE
Custom Theme "un"-applys at random.

### ISSUE THREAD

**Issue by ghost** [Kareadita/Kavita#2803]
### What happened?

This is not really reproducable.
Sometimes my Theme just either needs a second to load or doesnt load at all.
When it doesnt load at all, i need to reapply it manually.

### What did you expect?

The custom Theme to always be there.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Chrome

### Additional Notes

Maybe the bug comes from that you load the default Theme first, only to overwrite it with the custom one afterwards. (or it seems that way looking at this bug)

**Comment by DieselTech** [comment]
There was a bunch of work done in the last release around themes and the theme repo. If this is still occurring, please open a new issue.
