### ISSUE TITLE
When scrolling webtoons/manhwa the images are sometimes scrambled

### ISSUE THREAD

**Issue by Dragonatorul** [Kareadita/Kavita#2806]
Here are the logs from a recent event where the pages got scrambled. [_kavita_logs.txt](https://github.com/Kareadita/Kavita/files/14670323/_kavita_logs.txt)

For the record this is happening in any browser on the iPad and in Firefox and Safari on my Macbook Air M1. I didn't check if it happens on Windows, but it doesn't seem to matter. 

I tried clearing the cache and refreshing, at least as best as I can on these apple devices. It doesn't seem to help. Moving to another browser seems to load the chapter just fine most of the time. However, I think sometimes even going to an entirely different browser and in incognito still persists the issue with the same chapter. I'm not 100% sure on this one, but will test when I can.

This is an example of how it looks like when the pages get scrambled. Notice the jarring cut between panels. That's where the page cuts and displays unrelated panels. 
![image](https://github.com/Kareadita/Kavita/assets/109987846/417c3082-5a27-42e8-bdac-2079e1d4f769)

_Originally posted by @Dragonatorul in https://github.com/Kareadita/Kavita/issues/2719#issuecomment-2010144235_

**Comment by majora2007** [comment]
So to help me understand, you're reading on the webtoon reader and pages are getting rendered out of order. Can you please provide your version of Kavita?

**Comment by Dragonatorul** [comment]
Version
    0.7.14.0
Install ID
    2003b255

This is installed in docker on a debian 12 host. 

That's right. I'm reading in this mode: 

![image](https://github.com/Kareadita/Kavita/assets/109987846/5513187d-8aac-403f-9b1e-4c89251985e9)

Sometimes the pages are rendered out of order. Even when starting a new chapter it starts in the middle of the chapter, the half that is displayed is rendered out of order, then the last half is just the last page repeated over and over for however many pages are left. Say there are 87 pages. It starts rendering page 32, renders the rest of the pages out of order, or renders one page again and again every other page, then renders the last page until for every page between page 55 and 87.

**Comment by hstraten** [comment]
Can you check for media errors?
Do you have something like these errors:
<img width="1831" alt="error" src="https://github.com/Kareadita/Kavita/assets/44365426/c6d1122a-8ca9-47de-9093-22f187446a2e">
Seems related to #2494 , Same behaviour at least

**Comment by DieselTech** [comment]
There was a lot of work done in the last few releases around webtoons. Other users have reported they are not having issues anymore, so if this is still occurring please open a new issue to report it.
