### ISSUE TITLE
Scrolling reading list on mobile (touchscreen) reorders items

### ISSUE THREAD

**Issue by Fmstrat** [Kareadita/Kavita#2813]
### What happened?

The reading list can be reordered by clicking and dragging anywhere on an item, instead of just on the three line icon.

This means, when attempting to scroll on a touchscreen, you end up reordering items. You have to be really careful and only scroll using the far right.

### What did you expect?

Reordering should only occur when using the three line icon.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
I've had this experience as well on customize dashboard. I'll take a look and fix it up.
