### ISSUE TITLE
Login Form Username Enumeration Vulnerability

### ISSUE THREAD

**Issue by kmt-t** [Kareadita/Kavita#2829]
### What happened?

I noticed that the login form displays different error messages for incorrect usernames and passwords when the language is set to Japanese. This behavior might be leveraged by attackers to enumerate valid usernames.

In the Japanese setting, the error message "資格情報が正しくありません" is shown for a correct username with an incorrect password, while an English message is displayed for an incorrect username.

### What did you expect?

To mitigate the risk of username enumeration, consider using a generic error message for both incorrect username and password scenarios. For example:

"ユーザー名またはパスワードが正しくありません。"
(Translation: "Username or password is incorrect.")

By providing a consistent error message, it becomes more challenging for potential attackers to differentiate between valid and invalid usernames.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by YodaDaCoda** [comment]
This is interesting. 

If the username is incorrect, the code defaults to returning an english string
https://github.com/Kareadita/Kavita/blob/0dacc061f1954c0503253ec95c648b5b14f164a1/API/Controllers/AccountController.cs#L207

If the username is correct, but the auth fails, the code uses the translation service to return the same error message, but translated to the user's language
https://github.com/Kareadita/Kavita/blob/0dacc061f1954c0503253ec95c648b5b14f164a1/API/Controllers/AccountController.cs#L228-L229

So it's not a global user enumeration, only enumeration of non-english users, but it might still be good to replace all instances of `.Translate(user.Id, ` with `.Get('en', ` in the `Login()` function.

@majora2007 if you like I'll raise a PR for this :)

**Comment by majora2007** [comment]
@YodaDaCoda feel free to. You're right, we should just default to English for this case. Please be sure to check if the localization key is used elsewhere and if not, remove it from en.json (weblate will automatically purge from other locales).
