### ISSUE TITLE
Tap to paginate restricts one from tapping on ePub links when they are rendered under the gutters

### ISSUE THREAD

**Issue by gmahomarf** [Kareadita/Kavita#2835]
### What happened?

Tried to click on a link in an ePub, but it moved to the previous page instead.

Steps:
- Open an ePub
- Try to click a link that is rendered in the gutter areas 

### What did you expect?

I expected my click to go through the gutter to the link

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

This was working before #2471.

In the GIF below, you can see the links being underlined on mouseover when the text falls outside the gutter. When the text falls inside the gutter, nothing happens. 
![2024-04-08-17-43-07-ezgif com-optimize](https://github.com/Kareadita/Kavita/assets/137055/31726ffd-750b-4b38-991c-6dda4a8c139f)

**Comment by YodaDaCoda** [comment]
same fundamental issue as #2694, would similiarly be resolved by #2754

**Comment by gmahomarf** [comment]
> same fundamental issue as #2694

Agree. Will probably close this issue. 

>would similiarly be resolved by #2754

Disagree, since this still affects desktop clients, where swiping is less intuitive. 


@majora2007 I never actually asked: what were the bugs introduced by #2061?

**Comment by majora2007** [comment]
@gmahomarf I can't recall 100%, but I do recall a few things cropping up that I fixed afterwards. I think they were around highlighting and the overlay.

**Comment by gmahomarf** [comment]
Closed as dupe of #2694

**Comment by ShivamAmin** [comment]
> > same fundamental issue as #2694
> 
> Agree. Will probably close this issue.
> 
> > would similiarly be resolved by #2754
> 
> Disagree, since this still affects desktop clients, where swiping is less intuitive.
> 
> @majora2007 I never actually asked: what were the bugs introduced by #2061?

Hey, actually, commit [2fd756f1f4ed56950ffc3ad40545b08e4ee002f1](https://github.com/Kareadita/Kavita/pull/2754/commits/2fd756f1f4ed56950ffc3ad40545b08e4ee002f1) fixes the issue where when Tap To Paginate is enabled, and you have text underneath the invisible prev/next buttons that pop up. All you have to do once #2754 is reviewed and merged is to tap in the center of the page bringing up the menu, this will hide the buttons and you can then select/click text on the screen. I'll add this to #2694 as well.

**Comment by gmahomarf** [comment]
> All you have to do once #2754 is reviewed and merged is to tap in the center of the page bringing up the menu, this will hide the buttons and you can then select/click text on the screen.

I, personally, dislike the idea of having to do an extra click/tap. I'd rather have it work by just clicking on the link or text to select directly.

I'll keep an eye on #2754 regardless, since this will at least give me a workaround. Thanks for the info.
