### ISSUE TITLE
Swipe action is not reflected when using reverse proxy

### ISSUE THREAD

**Issue by sosboy-san** [Kareadita/Kavita#2844]
### What happened?

Screen does not refresh with swipe action when using reverse proxy. The problem does not occur when connected directly. This symptom can be confirmed on the official demo page.
After swiping, tap the center of the screen to refresh the screen.

### What did you expect?

This problem does not occur when connecting directly by IP address.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome

**Comment by scare376** [comment]
This behavior may be caused by your reverse proxy as I cannot reproduce this on my own setup. You may want to check our reverse proxy configs to see if they differ to yours https://wiki2.kavitareader.com/installation/remote-access

**Comment by scare376** [comment]
I do see the behavior on the demo. There is one swipe transition then you have to tap the center to transition further. You may also want to check your logs for this https://wiki2.kavitareader.com/troubleshooting/faq#q-im-seeing-database-is-locked-errors-in-my-logs as I _think_ it might be related.

**Comment by sosboy-san** [comment]
In my environment, database is locked errors were encountered, so I am operating in WAL mode.

**Comment by sosboy-san** [comment]
The reverse proxy was incorrectly configured.
Websocket was not turned on.

**Comment by scare376** [comment]
So everything is working as intended now?

**Comment by sosboy-san** [comment]
It is working fine. Thank you for your support.
