### ISSUE TITLE
You'll get a message when you get into the system??

### ISSUE THREAD

**Issue by kim08384** [Kareadita/Kavita#2852]
### What happened?

<img width="1247" alt="20240413_075659" src="https://github.com/Kareadita/Kavita/assets/149031356/8f00f709-52e0-4a24-86ac-21ec4041cb87">

You'll get a message when you get into the system  (Please tell me how to solve it)

Call failed. Resource temporarily unavailable (api.github.com:443): GET https://api.github.com/repos/Kareadita/Kavita/releases

After a certain period of time, messages keep coming out

Call failed. Resource temporarily unavailable (api.github.com:443): GET https://api.github.com/repos/Kareadita/Kavita/releases

### What did you expect?

You'll get a message when you get into the system  (Please tell me how to solve it)

Call failed. Resource temporarily unavailable (api.github.com:443): GET https://api.github.com/repos/Kareadita/Kavita/releases

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Call failed. Resource temporarily unavailable (api.github.com:443): GET https://api.github.com/repos/Kareadita/Kavita/releases
```

**Comment by majora2007** [comment]
Can you refresh the page now and see if it loads? I think right after the release Github gets a lot of traffic.

**Comment by kim08384** [comment]
> Can you refresh the page now and see if it loads? I think right after the release Github gets a lot of traffic.

I have refreshed(F5) the current page, but I keep getting the same message

<img width="1249" alt="20240413_082643" src="https://github.com/Kareadita/Kavita/assets/149031356/4fce2012-d1c3-4ba6-ae7d-750d19b4318b">

**Comment by majora2007** [comment]
If you go to this url in your browser, does it load? https://api.github.com/repos/Kareadita/Kavita/releases

**Comment by kim08384** [comment]
> If you go to this url in your browser, does it load? https://api.github.com/repos/Kareadita/Kavita/releases
<img width="1918" alt="20240414_022257" src="https://github.com/Kareadita/Kavita/assets/149031356/d640b817-7338-4fcf-bee9-d5b0188b188a">


If you connect to the link from Chrome, it looks like an image

**Comment by kim08384** [comment]
> If you go to this url in your browser, does it load? https://api.github.com/repos/Kareadita/Kavita/releases

If you connect to the link from Chrome, it looks like an image
<img width="1247" alt="20240414_043024" src="https://github.com/Kareadita/Kavita/assets/149031356/8a74d82b-d6e6-4b5e-b646-0496843eba6c">

**Comment by kim08384** [comment]
> If you go to this url in your browser, does it load? https://api.github.com/repos/Kareadita/Kavita/releases

Problem solved
After releasing the Nas security firewall
I can't get a message

What's the IP for unlocking the Kavita firewall?

<img width="1736" alt="20240414_090922" src="https://github.com/Kareadita/Kavita/assets/149031356/25141460-f3fc-4a27-b755-5bfcd7add53a">

<img width="874" alt="20240414_091252" src="https://github.com/Kareadita/Kavita/assets/149031356/8087126f-59a6-45d5-92b3-91df54b31f09">

**Comment by majora2007** [comment]
> What's the IP for unlocking the Kavita firewall?

Sorry I did not understand. 

You might just be able to add an exception for api.github.com (this website essentially) and plus.kavitareader.com (in case you ever use Kavita+).

**Comment by majora2007** [comment]
For context to others, other users have seen this issue due to using a VPN and likely cloudflare blocking their IP for checks against Kavita+ or Github.

**Comment by kim08384** [comment]
> For context to others, other users have seen this issue due to using a VPN and likely cloudflare blocking their IP for checks against Kavita+ or Github.

I solved the problem

NAS firewall Apply IP

Source IP: 172.16.0.0
Net Mask: 255.240.0.0

<img width="1755" alt="20240425_023345" src="https://github.com/Kareadita/Kavita/assets/149031356/47f638ca-c49a-4640-b18e-3e5353a0c698">
