### ISSUE TITLE
Individual Issue Metadata Edit

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#2855]
- Allow the user to edit (via a modal) individual chapter metadata.
- Allow the user to edit sort order per issue and Lock the field. 
- (Stretch) Allow a user to set volume cover and keep chapter separate

**Comment by michnmi** [comment]
As an enhancement to your suggestion, I hope this is the correct place to suggest something, as in it doesn't need a new topic. I 've only just installed Kavita (great job, well done!) and uploading in a test folder in it, I see that the system can't recognise the Series. Might I suggest the ability to find the series/chapter in one of your metadata web sources and then provide in the GUI the box where we can enter the ID in that web source and then "force" it to fill the metadata from that particular comic/series.

**Comment by majora2007** [comment]
@michnmi  I would suggest raising a feature request. This issue is already pre-determined work whereas your idea needs input from the community and thought before making a decision.

**Comment by majora2007** [comment]
This was already delivered with v0.8.3.
