### ISSUE TITLE
Internal Strings are displayed instead of intended values

### ISSUE THREAD

**Issue by nachfuellbar** [Kareadita/Kavita#2858]
### What happened?

I just updated docker install to current version (0.8.0.1 - can't seem to select it in "Kavita Version Number" further down) and some strings seem to be internal and not the intended values
This issue occurs on mobile and desktop chrome browser

![image](https://github.com/Kareadita/Kavita/assets/5123484/01cd2131-4f8b-482a-942d-58bd224573e0)
![image](https://github.com/Kareadita/Kavita/assets/5123484/6a53bd1f-6a9c-4778-ac5c-17da5378bb59)

### What did you expect?

The intended values are displayed like count of files etc

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome

**Comment by majora2007** [comment]
This is just an issue with your localizations being cached. Just tasks > clear locale cache and if that doesn't work, clearing site data will.

**Comment by nachfuellbar** [comment]
Thanks
Doing both helped
