### ISSUE TITLE
Manga, option to set side padding

### ISSUE THREAD

**Issue by eswiig** [Kareadita/Kavita#2871]
### What happened?

Hi, I am coming from Komga as I want to try give Kavita a try.

Added a library as Manga, don't see any option to add side padding on the left and right side.

### What did you expect?

Being able to set side padding regardless of library type.

Please let me know if this is not possible.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.0 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by eswiig** [comment]
I am used to this

![image](https://github.com/Kareadita/Kavita/assets/58608430/29e66696-7ac4-4acf-9a9e-ed1c56b2b95e)

set side padding, is this possible in Kavita?

i can't read manga when it's full width and if i set it to height restriction it's too small to read properly, it is annoying and hurts my eyes so I need side padding... T_T

a bandaid is for me to manually zoom out and "create" side padding , but this doesn't really feel like a good solution.

**Comment by majora2007** [comment]
Kavita doesn't support custom margins on the image-based reader. You're best bet would be to raise a Feature Request and if the community also needs this, then I will work on an implementation.

**Comment by eswiig** [comment]
needed it on the manga-based reader, but understand, will raise a feature request to have it implemented regardless of reader type. thanks

**Comment by majora2007** [comment]
The manga reader is an image-based reader as it let's you read images.
