### ISSUE TITLE
No warning given when passwords are too long 

### ISSUE THREAD

**Issue by jdaviescoates** [Kareadita/Kavita#2877]
### What happened?

I tried to register on my new server and used a 128 character length password (I always do, because why not?). 

No warning was given that it was too long. So then I couldn't login and had to start all over again.

### What did you expect?

Really I expect to be able to use much longer passwords, but in the interim if a password of longer than 32 characters is entered a warning message should appear informing the user that 32 characters is the maximum (as I've now discovered by actually clicking on the little i to reveal this message 
![image](https://github.com/Kareadita/Kavita/assets/2113743/d4dc376a-f91a-401e-a67c-22f1039df0d0)

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.0 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

I'm running Kavita on [Cloudron](https://cloudron.io/?refcode=5adcafc820c53c3d)

**Comment by lead0r** [comment]
Does that just cut everything after the 32nd character? I always wondered, why I was unable to log in, but just using the first 32 characters does not seem to work either

**Comment by majora2007** [comment]
Kavita doesn't support passwords that are longer than 32 characters. So yes, it cuts off to the first 32 characters, but so does registration. When I checked the code, I see the validation on all the registration screens is there and it should show under the field like all others. I still need to validate it is doing this inline validation. 

I don't really plan to support more than 32 characters, but someone can raise a PR if they feel it's really needed.

**Comment by xusiai** [comment]
No indication that the password was incompatible and registration appeared to complete for me. It took a few container resets to realize the password was too long. 

This was with Linuxserver's v0.8.1.0.

**Comment by majora2007** [comment]
I'm open to suggestions on how to help users understand. There is a maxLength on the input, so if you're copying 33 characters in, it cuts off automatically. Kavita can't know that the original value was 33 characters as the browser cuts it off. 

I have tooltips (but from the issues I've seen, users RARELY look inside them). But other than that, not sure what else I can do to help users.

**Comment by DieselTech** [comment]
This has been changed in the nightly (0.8.2.2) and will be avilable in the upcoming stable branch 0.8.3 once it is published.

> Changed: Passwords can now be up to 256 characters long
