### ISSUE TITLE
Links in invite and password reset emails are missing https:// and so do not work in many mail clients

### ISSUE THREAD

**Issue by jdaviescoates** [Kareadita/Kavita#2878]
### What happened?

I requested a password reset and tested inviting users.

In all such emails the links to reset password or to accept the invite to not have https:// at the beginning and therefore in e.g. SnappyMail (both stand alone and Nextcloud app version) the link is broken because it gets prepended with the url of the SnappyMail instance, and in Roundcube the link doesn't work at all.

### What did you expect?

I expect links to be properly formed so they work everywhere.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.0 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

I'm running Kavita on [Cloudron](https://cloudron.io/?refcode=5adcafc820c53c3d)

**Comment by majora2007** [comment]
Which links didn't have https? The link back to your server or the social media links included in the template?

**Comment by jdaviescoates** [comment]
> Which links didn't have https? The link back to your server or the social media links included in the template?

The link back to my server. Perhaps this is an issue with the Cloudron package and I should report it there?

Here is the redacted source of an example email received:

`<h1>You've Been Invited!</h1>
        <p>You have been invited to jdaviescoates's Kavita instance.</p>
        <p>Please click the following link to setup an account for yourself and start reading.</p>

        <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="btn btn-primary">
            <tbody>
            <tr>
                <td align="center">
                    <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                        <tbody>
                        <tr>
                            <td> <a href="myserverurl/registration/confirm-email?token=CfDJ8M0lBYW2O5JIt9yJvLL9j6TgrUQmKfkkxHBe%2bhfJCiBHMwDPjmV5cj0DQZY9bmBYD8ajO8ZcRtRtE95s2ATZ0Wa1ZwFpiLzg%2b0gSDnDxBeVWs3IgACi6blyd13zqFJ4UgJVudwX6IiusRPhqdXBrgsp%2bHSxu4Ui6PhUwpy14Hx%2btiCN1rbmZFnodLD%2fz9l%2blFw%3d%3d&email=emailaddress" target="_blank">ACCEPT INVITE</a> </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            </tbody>
        </table>

        <p class="small">If the button above does not work, please find the link here: <a class="small" href="myserversurl/registration/confirm-email?token=CfDJ8M0lBYW2O5JIt9yJvLL9j6TgrUQmKfkkxHBe%2bhfJCiBHMwDPjmV5cj0DQZY9bmBYD8ajO8ZcRtRtE95s2ATZ0Wa1ZwFpiLzg%2b0gSDnDxBeVWs3IgACi6blyd13zqFJ4UgJVudwX6IiusRPhqdXBrgsp%2bHSxu4Ui6PhUwpy14Hx%2btiCN1rbmZFnodLD%2fz9l%2blFw%3d%3d&email=emailaddress" target="_blank">myserverurl/registration/confirm-email?token=CfDJ8M0lBYW2O5JIt9yJvLL9j6TgrUQmKfkkxHBe%2bhfJCiBHMwDPjmV5cj0DQZY9bmBYD8ajO8ZcRtRtE95s2ATZ0Wa1ZwFpiLzg%2b0gSDnDxBeVWs3IgACi6blyd13zqFJ4UgJVudwX6IiusRPhqdXBrgsp%2bHSxu4Ui6PhUwpy14Hx%2btiCN1rbmZFnodLD%2fz9l%2blFw%3d%3d&email=emailaddress</a></p>`

Instead of "myserverurl/registration/confirm-email?token=..." it should be "https://myserverurl/registration/confirm-email?token=..."

**Comment by majora2007** [comment]
The links to your server are setup by you in Host name setting under Email tab. Can you validate that you have it set with https there?

**Comment by jdaviescoates** [comment]
OK, I think this is probably an issue with the Cloudron package not automatically setting that correctly then. I shall report it to them. Thanks.

**Comment by gramakri** [comment]
Cloudron package maintainer here. This was indeed a packaging bug. Fixed in https://git.cloudron.io/cloudron/kavita-app/-/commit/f4af00533f0037de10ee19033733e839289362be
