### ISSUE TITLE
Image library and chapters with decimal numbers

### ISSUE THREAD

**Issue by 0N1rick** [Kareadita/Kavita#2879]
### What happened?

After the 0.8.0 update, finally the image library is working! Thank you for this <3

However I have noticed that it doesn't detect chapter folders if they have a decimal number, for example "Chapter 18.5". It completely ignores them.
This is a huge issue with manga, they often have X.Y chapters at the end of volumes.

### What did you expect?

Every chapter folder should be detect, even X.Y numbered chapters.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.0 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
I took a look and it seems that it was using comic regex for parsing chapter number from folders instead of Manga.
