### ISSUE TITLE
Kavita doesn't show my entire ebook library unless I use force scan

### ISSUE THREAD

**Issue by meyou69** [Kareadita/Kavita#2881]
### What happened?

Kavita shows only 34 ebooks in my library, when the actual number should be 49.

Using the Force Scan feature temporarily restores the missing ebooks, but only for a short period of time (less than 24 hours)

### What did you expect?

I expect for all 49 books to always be shown

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.0 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by therobbiedavis** [comment]
Not a whole lot of details. Are they all epubs? What do the logs say?

**Comment by meyou69** [comment]
Not all, some are PDFs and others are EPUBs, in the same directory. And as far as logs are concerned, all I'm getting is
"Skipped File Scan for /books/Computer Science as it hasn't changed since last scan" in the latest logs, which isn't particularly helpful

**Comment by scare376** [comment]
Are all of the books in the Computer Science folder directly or are they in subfolders. and is that folder the root of that library?

**Comment by majora2007** [comment]
I would suggest you provide the following information:
Logs
Library folders and type 
A sample of where files are in said folders

Usually these issues are either bad files, which are listed in media issues or files at the root of the library folder, which Kavita does not support and should be in folders.

**Comment by meyou69** [comment]
I will attach the latest log.
[log.txt](https://github.com/Kareadita/Kavita/files/15044751/log.txt)

On a different note, the library folders are the following:

Manga: of type Manga and for the folder /manga 

CS Books: of type Books and for the folder /books/Computer Science 

And, finally, Fiction: of type Books and for the folder  /books/fiction/Horror

In my particular case, all the books (both epub and pdf) are stored in the /books/Computer Science directory

**Comment by majora2007** [comment]
So if you have the folder library setup to `/books/Computer Science` and you have files like `/books/Computer Science/History of .NET.pdf`, the History of .NET will never show in Kavita as it MUST be in a folder FROM the library root. 

If you have instead `/books/Computer Science/.NET/History of .NET.pdf`, then you will see the files loaded in. 

The logs weren't very helpful. You should delete the log file, do a scan on a library you believe isn't showing all the files, then attach once that scan is complete. I would do a force scan via ... -> Edit Library to ensure it visits every file. 

Also please note you are out of date. Kavita does not support users on out of date versions.

**Comment by meyou69** [comment]
Deleting the log file and doing a manual re-scan, and then a forced scan as well, did not recreate the log file for today.

Once the log file was deleted, the server doesn't seem to generate another one, regardless of how many scans I issue.

On doing a forced scan, it appears that all my books get detected, but when doing a normal scan, only a portion of them get detected.

As far as the issue with the outdated version is concerned, I'm using the Kavita version from the jvmilazz0/kavita:latest docker image. I don't know for there to be an official docker image for this server, so that's what I use.

If there is a newer image I can use, please let me know, but please keep in mind that it has to be in Docker. I don't want to have to install the image outside of Docker.

**Comment by meyou69** [comment]
OK, so, your suggestion would be to move all my books into subdirectories under the library root?

**Comment by scare376** [comment]
Yes. Kavita is meant to ignore books at the library root to help with the scan loop. Seems there might be a bug that was allowing them to be scanned in by hitting force scan.

**Comment by therobbiedavis** [comment]
These requirements are also listed in the wiki: https://wiki.kavitareader.com/guides/scanner#file-layout

**Comment by meyou69** [comment]
OK, so I tried what you guys recommended and it worked. Now all my books get displayed.

However, I still have a pretty big issue, and that is now, when I organized all my books into subdirectories under the library root, now the collections are entirely broken, since I mixed books of different formats under the same directories (i.e. I added both PDF and EPUB books under the directory called Architecture) and now Kavita can't seem to figure out how to show both types of books. It just auto-picks PDFs and only show the PDF books in that collection, and not the EPUB ones.

How would I solve this?

**Comment by scare376** [comment]
Check your library settings and make sure both PDF and epub are selected in the advanced section
![msedge_3RlSdoltu9](https://github.com/Kareadita/Kavita/assets/2068470/e980132c-838c-48bd-b255-cee5a4be18ce)

**Comment by meyou69** [comment]
I checked. Both Pdf and Epub are checked. In theory, they should both apppear in my library.

Keep in mind though, that both PDFs and EPUBs appear in my library, it's just that the PDFs appear under the collections (where they belong, since they are under the collection's subdirectory) but the EPUBs appear outside those collections as their own thing, which makes a whole mess of the library

**Comment by majora2007** [comment]
Those collections are called series in Kavita and that is how it functions. PDF and epub will be separate series always. You can link them together with series relationships or build collections and only use that to navigate, but having multiple file types in one series isn't supported.

**Comment by meyou69** [comment]
I really can't say that I like this project. It seems to have a lot of arbitrary limitations that only serve to complicate things for me.

I think I'll move on with a different solution, since Kavita clearly requires a structure that I simply don't have for my library.

Thank you all for your support

**Comment by YonierGomez** [comment]
Tuve varios problemas con kavita pero finalmente descubrí cómo funciona, kavita lee son subdirectorios, principalmente había creado un "/book" pero no funcionó, lo que hice fue crear un subdirectorio "/book/allbooks" volví a escanear y aparecieron todos mis archivos.
