### ISSUE TITLE
The sort order of Chinese series name 

### ISSUE THREAD

**Issue by newyorker123** [Kareadita/Kavita#2882]
### What happened?

Most of my manga series names are in Chinese. When they are sorted by 'Sort Name' (the default), the order is just weird. They don't look sorted at all.

Chinese characters should be sorted by Pinyin. On the Windows file system, they behave correctly. Additionally, Emby also sorts Chinese titles correctly. I believe there must be something wrong with how Kavita implements the sort.

### What did you expect?

Chinese series name sorted by pinyin.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.0 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
Please give some examples of filenames and how they SHOULD sort vs how they DO sort. 

I'm not sure I can support, but with extra info I can take a look.

**Comment by newyorker123** [comment]
Thank you for your reply. I'll give 6 examples and the corresponding Pinyin. 

```
name               Pinyin
冰菓               bing guo
链锯人             lian ju ren
迷宫饭             mi gong fan
神明大人搞错了     shen ming da ren gao cuo le
我家的英雄         wo jia de ying xiong
终将成为你         zhong jiang cheng wei ni
```

Pinyin uses the alphabet. You can treat Pinyin as English words and sort them according to alphabetical order. Since the first letter of each Pinyin is distinct, the order is determined by the first letter (i.e. b -> l -> m -> s -> w -> z). Therefore, the above list is already in the correct order, which is consistent with Windows file system. 
![image](https://github.com/Kareadita/Kavita/assets/43869995/c05c1e15-fe23-4263-9953-19a47e136214)


The order in Kavita is :
![image](https://github.com/Kareadita/Kavita/assets/43869995/e1595a63-772d-4c49-b5cc-17ce1bd7f483)

I guess it's because the default sort method uses unicode code point.

**Comment by majora2007** [comment]
Are you using the Chinese locale at all?

**Comment by newyorker123** [comment]
No, I use English locale.

But I just tried changing the locale to Chinese and recreate the library. The order is still the same.

**Comment by majora2007** [comment]
I would raise a feature request for the sorting request. It's really outside the scope of Kavita and I would need to see how important it is before I commit to owning such a feature.
