### ISSUE TITLE
Can't access files via OPDS

### ISSUE THREAD

**Issue by Simsala91** [Kareadita/Kavita#2884]
### What happened?

When trying to access (download) files using the OPDB interface, server keeps responding with HTTP code 400 (Bad Request). I can view all items in my collection, but I can't actually read them.

Tried with:

FBReader
Moon+ Reader
Mihon

In every client I can see my collection, but I can't download my files (see log) - 200 for regular requests, 400 for download.

### What did you expect?

File download to happen as expected.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.0 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-04-18 01:39:34.726 +02:00  128] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/opds/efa57f53-40e5-4396-8789-f7e3bfd8b6e5/on-deck responded 200 in 5.3354 ms
[Kavita] [2024-04-18 01:39:35.714 +02:00  81] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/opds/efa57f53-40e5-4396-8789-f7e3bfd8b6e5/series/7 responded 200 in 16.3439 ms
[Kavita] [2024-04-18 01:39:37.614 +02:00  81] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/opds/efa57f53-40e5-4396-8789-f7e3bfd8b6e5/series/7/volume/7/chapter/27/download/redacted.redacted.redacted.redacted.redacted.2024.pdf responded 400 in 2.6790 ms
[Kavita] [2024-04-18 01:39:39.207 +02:00  134] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/opds/efa57f53-40e5-4396-8789-f7e3bfd8b6e5/series/7/volume/7/chapter/27/download/redacted.redacted.redacted.redacted.redacted.2024.pdf responded 400 in 2.6300 ms
[Kavita] [2024-04-18 01:39:40.074 +02:00  134] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/opds/efa57f53-40e5-4396-8789-f7e3bfd8b6e5/series/7/volume/7/chapter/27/download/redacted.redacted.redacted.redacted.redacted.2024.pdf responded 400 in 2.7152 ms
[Kavita] [2024-04-18 01:40:16.090 +02:00  134] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/users/has-library-access?libraryId=3 responded 200 in 1.8256 ms
[Kavita] [2024-04-18 01:40:16.126 +02:00  4] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/stream/sidenav?visibleOnly=true responded 200 in 2.3719 ms
[Kavita] [2024-04-18 01:40:16.132 +02:00  134] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/metadata?seriesId=6 responded 200 in 2.0767 ms
```

**Comment by majora2007** [comment]
Can you confirm your account has the download role assigned to it?

**Comment by Simsala91** [comment]
You are right, it was due to the missing download role. Now it works.

Only thing I would mention is that the appropriate HTML error code here would be 403 and not 400, since the request was valid just missing necessary permissions.

**Comment by majora2007** [comment]
I will look but OPDS isn't even able to display the error message to the user, so it wouldn't matter much.

**Comment by Simsala91** [comment]
I did get the error code 400 through FBReader and Moon+ Reader though, think I wouldn't have thought it was a config problem if I got a 403 here.

**Comment by majora2007** [comment]
Haha yeah, I don't expect many people are in that position. But I'll look into it and test with the software we support out of the box.
