### ISSUE TITLE
Duplicated chapters after v0.8 update

### ISSUE THREAD

**Issue by Roshri** [Kareadita/Kavita#2885]
### What happened?

After updating to latest stable (v0.8) I noticed that chapters would get duplicated in my manga libraries. 
![image](https://github.com/Kareadita/Kavita/assets/29184137/8e88e27d-a3cb-48de-8322-4f91cdce4a52)

Neither scanning the series nor force scanning the library again seem to help.
Deleting and readding the series fixed it to some extent but the numbering seems odd
![image](https://github.com/Kareadita/Kavita/assets/29184137/6a221d2e-97af-4c86-9d6f-a909506d3dc3)

Following this I checked the actual metadata on the files and found that when zero padding is present in the Number field, it creates that effect.

![image](https://github.com/Kareadita/Kavita/assets/29184137/ce7f3227-279d-4842-aa4a-35cb36319e70)
![image](https://github.com/Kareadita/Kavita/assets/29184137/e86cedf2-3e69-46af-93cf-0e341a5cf3be)

So to get this result:

1. Have a series in a manga library in previous stable
2. The series should have comicinfo
3. Number field should use zero padding
4. Update to 0.8
5. Scan/Force scan library after updating to v0.8

### What did you expect?

Chapters appearing only once.
Don't know about zero padding. I wouldn't strip it.
Ideally show only the actual numbering on the comicinfo

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.0 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox, Chrome

**Comment by chilliwow** [comment]
Having the same exact issue after updating to v0.8 and force scanning. Happens when there's one or multiple zeroes in front of the chapter number. Chapter reverted back to normal after removing the zeroes from the filename.
![image](https://github.com/Kareadita/Kavita/assets/31785430/4953687d-845e-43dd-9e42-0dfa6284bf43)

**Comment by chilliwow** [comment]
If anyone has issues in the future, a quick fix is to move all files except for one out of the series folder and do a scan. Then add the files back and scan again.

**Comment by majora2007** [comment]
I think this is due to the migration from v0.8 and there are likely some leftover chapters in the DB or something. Removing the chapters then readding should work. 

I tried to reproduce myself by taking an existing chapter 1.cbr (already scanned in) then adding chapter 001 for the issue number in ComicInfo and no duplicate chapter did appear.

**Comment by Roshri** [comment]
Yeah definitely something broke during migration.
Doing the plex dance for hundreds of series will probably take weeks but there's probably no other way.
I should notify my users, this would reset the series progress I think

**Comment by majora2007** [comment]
Yeah, it might be beneficial to write a script that marks as read for each of your users from that csv. You can also write some SQL likely to remove the chapters in the db.

It's really unfortunate you got hit so hard. Please wait till after the v0.8.1 release as I fixed more bugs with non-english locales creating duplicates.
