### ISSUE TITLE
X.X chapters not working correctly - sort order, duplicates

### ISSUE THREAD

**Issue by chilliwow** [Kareadita/Kavita#2887]
### What happened?

I have a bunch of problems with x.x chapters. It's not just the sort order, but we'll get to that.

This first problem is the sort order being completely off with all x.x chapters. Of course it works if you only have x.5 chapters, then it fits in nicely between the chapters, but when there's x.1, x.2, etc. It's completely off. Below are examples of chapter numbers and their respective sort order.

Chapter Number >> SortOrder
20.5 >> 20.1
20.6 >> 21.1
![image](https://github.com/Kareadita/Kavita/assets/31785430/e192abef-4ca4-4260-a7a7-eacf78ac738f)
131.5 >> 131.1
131.6 >> 132.1
131.7 >> 133.1
132.2 >> 133.1
131.8 >> 134.1
Chapter 132.1 also has a SortOrder of 132.1, which is correct because that is the actual chapter number.
![image](https://github.com/Kareadita/Kavita/assets/31785430/e3c34327-e94b-4625-b100-771b345086d8)

Secondly,

Some x.5 chapters are at the start of the list with a sort order of 0. And when I tried to rename it to see if it would do anything, it wouldn't replace the chapter with the renamed chapter, and just duplicate it, so now both links to the same file, hence why you see 2 similar chapters at the beginning.
![image](https://github.com/Kareadita/Kavita/assets/31785430/fc095cbf-d232-412f-9b6e-b1ddb85eaea0)

Thirdly,

When I go to continue a series where the next chapter is a X.X chapter, it tells me to "Continue Ch 0", and when I open to continue the chapter, it's on the correct chapter, but it tells me that it's chapter 0 in the top left. The chapter number in details/info is correct though.
![image](https://github.com/Kareadita/Kavita/assets/31785430/629dbeea-5fb1-4973-a467-df7d402b64fc)![image](https://github.com/Kareadita/Kavita/assets/31785430/9b212d4b-9a8d-4dab-8416-d5af8aa6a636)

Series scan, force scan, and restarting Kavita has not worked for any of these problems.

I'm willing to hop on a call to show more if that would help out.

### What did you expect?

- Correct sort order for X.X chapters
- No duplicates
- Correct numbering for "Continue Ch X"

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.0 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
I believe this is likely due to your DB being in a weird state from the v0.8 migration. I just tested quickly:
![image](https://github.com/Kareadita/Kavita/assets/735851/9dbe35b8-0449-49fb-90ae-f5b3a90ce70e)

**Comment by chilliwow** [comment]
Thanks for checking, any thoughts on what I can do with that?

Also, I tested the duplication issue more and it's not only with x.x chapters.

Reproduction steps:

- Change filename/comicinfo chapter number to something different
- Scan library
- Change back to previous chapter number
- Scan library
- You should see duplicated chapters with different chapter numbers that link to the same file

Quick fix for this is to move the chapters out of the folder, do a scan, then move files back.

**Comment by majora2007** [comment]
Let me try with those reproduction steps and see if I can produce the issue.

**Comment by majora2007** [comment]
Hmm I can't reproduce this on my end (I also am using my prod version upgraded to v0.8).

**Comment by chilliwow** [comment]
Tested is on a fresh install without any metadata on another machine.

- Duplication seems to only affect series that was there before v0.8, because I could not reproduce on a fresh series.

- Sort order is still not working on a new install.
![image](https://github.com/Kareadita/Kavita/assets/31785430/71082cd7-8f7a-4c56-bfce-86bbaac9bc96)
[One-Punch Man files](https://drive.google.com/file/d/1gQxS-2skOLH90au0AXtx3DbGMBwmUjJJ/view?usp=sharing
) for testing. These are the exact ones used in the screenshot above. Please test out the files and let me know if you can reproduce with them.

- "Continue Ch 0" still persists on a new install. Did you try this yet? To reproduce, just mark chapters up until a x.x chapter like in the image below.

![image](https://github.com/Kareadita/Kavita/assets/31785430/488b01f8-bf4a-40e5-8777-871241205cca)![image](https://github.com/Kareadita/Kavita/assets/31785430/b7ba0afb-9fde-4978-97bc-ad27bbaa783c)

**Comment by majora2007** [comment]
@chilliwow Just tested:
![image](https://github.com/Kareadita/Kavita/assets/735851/9b60876b-5361-45e6-a11c-63a47810aecf)

Continue (note: I did tweak this logic for when the continue is on a special, so maybe that is causing different results)
![image](https://github.com/Kareadita/Kavita/assets/735851/36eeb9fe-b9c5-44ce-8378-7588f877234d)

> Duplication seems to only affect series that was there before v0.8, because I could not reproduce on a fresh series.
This makes sense due to how I migrated and how Kavita needs to clean out old chapters.

**Comment by chilliwow** [comment]
@majora2007 Messaged you on Discord because this is similar to something you and I talked about and fixed back in October. IT has to do with my regional format. The sort orders and continue chapter fixed right away after changing regional format to english and then restarting Kavita. #2339

**Comment by majora2007** [comment]
Note for self, I believe I need to use InvariantCulture on any potential ordering based on strings throughout the codebase. Testing now.
