### ISSUE TITLE
Files with Omnibus in the filename do not show up in the OPDS feed

### ISSUE THREAD

**Issue by myrm** [Kareadita/Kavita#2888]
### What happened?

In a Comic Vine library, whenever a file has Omnibus in the filename, it no longer shows up in the OPDS feed, even though it is visible and readable in the Kavita web interface. 

If the word Omnibus is removed from the filename and the series rescanned, the file shows up in the OPDS feed.

The feed was accessed in Panels and Chrome. 

This works just fine in a regular Comic library

### What did you expect?

Files with Omnibus in the filename in a comic vine library should also show up in the OPDS speed

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.0 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome

**Comment by majora2007** [comment]
I'm not able to reproduce this. If I recall, you had some other issue that was fixed. Is this something you can still reproduce?

**Comment by myrm** [comment]
Hi, Yup, still happens when i have omnibus in the file name, on kavita v 8.1.0. Library type is comic vine. Opds in panels; Kavita:File detail:Sent from my iPadOn Jun 3, 2024, at 20:44, Joe Milazzo ***@***.***> wrote:﻿
I'm not able to reproduce this. If I recall, you had some other issue that was fixed. Is this something you can still reproduce?

**Comment by majora2007** [comment]
This is what I have:
Floats - Chapter 0.1 Omnibus.cbr
![image](https://github.com/Kareadita/Kavita/assets/735851/6d0b50e9-65ac-42b6-b398-53d3c1153a10)

I need more information from you on the underlying filename and file type.

**Comment by myrm** [comment]
Hey,

It happens on at least two comics that i've checked.

file type: cbz

If you want, i can also send you the

separate libraries:

[image: image.png]

filenames:
[image: image.png]


[image: image.png]

opds xml:
[image: image.png]

[image: image.png]

**Comment by majora2007** [comment]
Worked with the user over discord. Here is what we found.

1. There is a bug where acquisitions have /api/opds//api/opds
2. ComicVine library type is causing the XML to be empty for the Series.

**Comment by majora2007** [comment]
Okay I still wasn't able to reproduce this issue. I couldn't find /api/opds//api/opds happening and ComicVine was able to show everything perfectly. 

Can you do a series scan on the Omnibus series and see if that fixes anything? 

I did however identify some performance optimizations that I placed in the OPDS code which should help users with larger series.

**Comment by majora2007** [comment]
Was finally able to reproduce with the user's files explicitly. Will investigate and report back.

**Comment by majora2007** [comment]
Got it. There was an issue where the issues weren't in an expected property but another one and OPDS feed was empty.
