### ISSUE TITLE
Comic Vine library series with Omnibus in series name

### ISSUE THREAD

**Issue by myrm** [Kareadita/Kavita#2889]
### What happened?

in a Comic Vine library, if a series has the word Omnibus in the series name, Omnibus gets removed from the name displayed in the UI (e.g. the series B.P.R.D. Omnibus would be displayed as just B.P.R.D. ).

This does not seem in a regular Comics library type

### What did you expect?

Omnibus should be kept in the series name

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.0 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

**Comment by majora2007** [comment]
I can't reproduce this myself. I have the following ComicInfo (with or without Volume):

```
<?xml version='1.0' encoding='utf-8'?>
<ComicInfo>
  <Series>O.P.D.S. Omnibus</Series>
  <Volume>2020</Volume>
</ComicInfo>
```

![image](https://github.com/Kareadita/Kavita/assets/735851/d2b65e48-cdd9-4b17-af88-735e01746fd4)
![image](https://github.com/Kareadita/Kavita/assets/735851/0638d2b3-773f-44ea-b82c-87890cf3a550)

**Comment by myrm** [comment]
[ComicInfo.txt](https://github.com/Kareadita/Kavita/files/15052857/ComicInfo.txt)
I have attached the xml file as txt.

Folder name is B.P.R.D. Omnibus

File name is B.P.R.D. Omnibus #001 (2022).cbz

**Comment by majora2007** [comment]
Okay I was able to reproduce. What is happening is you're using Comic Vine but you don't have the Volume set as the year (which is an expectation of that library type). So it's falling back to taking the folder name and replacing specials out of the folder name.

Although I do agree, for this fallback case, taking from directory should be safe enough to ignore cleaning special words out of them.

**Comment by myrm** [comment]
great! added the volume and the title popped right up after a scan. 

Thank you!

**Comment by majora2007** [comment]
v0.8.1 put an additional fallback check in place, so this is fixed.
