### ISSUE TITLE
Double page/width images are misaligned when Double (Manga) view

### ISSUE THREAD

**Issue by shinji257** [Kareadita/Kavita#2891]
### What happened?

When a double page/width image appears it seems to jump up to the top of the browser viewing area.  It doesn't change image size.

### What did you expect?

Should remain in the same position at least top to bottom as other images.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.0 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Microsoft Edge, Other (List in "Additional Notes" box)

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox

### Additional Notes

This does not happen when viewing in Double mode or even Single mode where images are not split.

Additionally tested on Brave on Windows.

**Comment by scare376** [comment]
Can you please provide a screenshot of what you are experiencing?

**Comment by shinji257** [comment]
Expected:
![image](https://github.com/Kareadita/Kavita/assets/261005/61f5dea7-b8ef-471c-b96a-fdae43922de3)

Actual:
![image](https://github.com/Kareadita/Kavita/assets/261005/5dde1bb5-ee35-4b2a-bef2-8d6562f716b8)

**Comment by shinji257** [comment]
You can see how the lower image (this is one of those double width/page images) is bumped up to hit the top of the viewable browser space where as the other image (two pages combined) have an equal space above and below the page.

EDIT:
Apparently it can happen on cover/back images too... These are not even double width and I don't see why they are like this and none of the others are.  The images I'm screenshotting with are compressed as webp but I also tested with jpg (the original format) and it did the same thing with the same images.  The only thing I can think of is it happens when there is only a single image being presented while in this mode.

![image](https://github.com/Kareadita/Kavita/assets/261005/8bf02399-dccd-4b40-bcb4-f2dd946d033a)
