### ISSUE TITLE
Too large a number of volumes and chapter indistinguishable issues

### ISSUE THREAD

**Issue by ytoaa** [Kareadita/Kavita#2900]
### What happened?

![image](https://github.com/Kareadita/Kavita/assets/24527825/53fba32e-818d-45ed-9315-2401a57203a6)

### What did you expect?

Too large a number of volumes or chapters are not recognized as other chapters or volumes. As shown in the picture above, 1000000000 chapter and 1000000001 are grouped together.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.0 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-04-22 01:20:15.952 +09:00  37] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache directories
[Kavita] [2024-04-22 01:20:15.952 +09:00  37] [Information] API.Services.Tasks.CleanupService Cache directory purged
[Kavita] [2024-04-22 01:20:15.954 +09:00  62] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on T
[Kavita] [2024-04-22 01:20:15.958 +09:00  62] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 5 files for /manga/collect/hit/t/timi
[Kavita] [2024-04-22 01:20:15.959 +09:00  62] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Beginning series update on timi, Forced: true
[Kavita] [2024-04-22 01:20:15.960 +09:00  62] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Processing series timi
[Kavita] [2024-04-22 01:20:15.960 +09:00  62] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Updating 4 volumes on timi
[Kavita] [2024-04-22 01:20:15.960 +09:00  62] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Parsing timi - Volume 1
[Kavita] [2024-04-22 01:20:15.960 +09:00  62] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, timi - Vol 1 Ch 1000000000
[Kavita] [2024-04-22 01:20:15.960 +09:00  62] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Parsing timi - Volume 888888900
[Kavita] [2024-04-22 01:20:15.960 +09:00  62] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, timi - Vol 888888888 Ch 888888888
[Kavita] [2024-04-22 01:20:15.960 +09:00  62] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Parsing timi - Volume 900000000
[Kavita] [2024-04-22 01:20:15.960 +09:00  62] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, timi - Vol 900000000 Ch 900000000
[Kavita] [2024-04-22 01:20:15.960 +09:00  62] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Parsing timi - Volume 900000000
[Kavita] [2024-04-22 01:20:15.960 +09:00  62] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, timi - Vol 899999999 Ch 899999999
[Kavita] [2024-04-22 01:20:15.960 +09:00  62] [Debug] API.Services.Tasks.Scanner.ProcessSeries Updating timi FolderPath to /manga/collect/hit/t/timi
[Kavita] [2024-04-22 01:20:15.960 +09:00  62] [Debug] API.Services.Tasks.Scanner.ProcessSeries Updating timi LowestFolderPath to timi/timi Vol899999999 Ch. 899999999
[Kavita] [2024-04-22 01:20:15.976 +09:00  62] [Information] API.Services.Tasks.Scanner.ProcessSeries Linking up External Recommendations new series (if applicable)
[Kavita] [2024-04-22 01:20:15.976 +09:00  62] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Finished series update on timi in 17 ms
[Kavita] [2024-04-22 01:20:15.976 +09:00  62] [Debug] API.Services.MetadataService [MetadataService] Processing cover image generation for series: timi
[Kavita] [2024-04-22 01:20:15.977 +09:00  62] [Debug] API.Services.MetadataService [MetadataService] Generating cover image for /manga/collect/hit/t/timi/timi Vol1 Ch. 1000000000/스크린샷 2024-04-20 014752.png
[Kavita] [2024-04-22 01:20:15.983 +09:00  7] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/stream/dashboard?visibleOnly=true responded 200 in 0.3730 ms
[Kavita] [2024-04-22 01:20:15.987 +09:00  62] [Debug] API.Services.MetadataService [MetadataService] Generating cover image for /manga/collect/hit/t/timi/timi Vol888888888 Ch. 888888888/스크린샷 2024-04-20 014752.png
[Kavita] [2024-04-22 01:20:15.997 +09:00  62] [Debug] API.Services.MetadataService [MetadataService] Generating cover image for /manga/collect/hit/t/timi/timi Vol900000000 Ch. 900000000/스크린샷 2024-04-20 014752.png
[Kavita] [2024-04-22 01:20:16.007 +09:00  62] [Debug] API.Services.MetadataService [MetadataService] Generating cover image for /manga/collect/hit/t/timi/timi Vol899999999 Ch. 899999999/스크린샷 2024-04-20 014752.png
[Kavita] [2024-04-22 01:20:16.024 +09:00  62] [Information] API.Services.MetadataService [MetadataService] Updated covers for timi in 48 milliseconds
[Kavita] [2024-04-22 01:20:16.025 +09:00  62] [Debug] API.Services.MetadataService Dispatching 9 update events
[Kavita] [2024-04-22 01:20:16.034 +09:00  62] [Information] API.Services.Tasks.Metadata.WordCountAnalyzerService [WordCountAnalyzerService] Updated metadata for timi in 9 milliseconds
[Kavita] [2024-04-22 01:20:16.034 +09:00  62] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished file scan in 1 milliseconds. Updating database
[Kavita] [2024-04-22 01:20:16.041 +09:00  62] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished library scan of 5 files and 1 series in 89 milliseconds for T
[Kavita] [2024-04-22 01:20:16.041 +09:00  62] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan
[Kavita] [2024-04-22 01:20:16.043 +09:00  62] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 0 series that needs to be removed: []
[Kavita] [2024-04-22 01:20:16.043 +09:00  62] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan - complete
```

**Comment by majora2007** [comment]
Can you help me understand the actual use case where you'd hit this issue?

**Comment by ytoaa** [comment]
> Can you help me understand the actual use case where you'd hit this issue?

It's used somewhat less.
I think there will only be strftime ("%Y%m%d%H") for those who crawl.

**Comment by majora2007** [comment]
I'm sorry, I'm not understanding the underlying use case when users would hit this? Yes there may be a limitation, but I'm less inclined to work on this issue unless I can understand when users would hit this.

**Comment by ytoaa** [comment]
> I'm sorry, I'm not understanding the underlying use case when users would hit this? Yes there may be a limitation, but I'm less inclined to work on this issue unless I can understand when users would hit this.

Usually, people specify chapters manually, but some people crawl through specific sites and run chapters by data date. However, when you specify chapters by data date, you get the problem of entering too large a number, and the chapters merge into one despite the following. So it would be nice if you could double-type the chapters to make large numbers possible. This is more of a request than a bug.

**Comment by majora2007** [comment]
Can you showcase a series that has more than 100,000 chapters? Kavita just moved to 100000 as an internal coding. I don't want to change it without a solid reason. If you are requesting this as more of a feature, please shift this to a Github Discussion so other users can upvote and help me prioritize or consider it.

**Comment by ytoaa** [comment]
> Can you showcase a series that has more than 100,000 chapters? Kavita just moved to 100000 as an internal coding. I don't want to change it without a solid reason. If you are requesting this as more of a feature, please shift this to a Github Discussion so other users can upvote and help me prioritize or consider it.

Okay, I'll move this to the discussion.

**Comment by ytoaa** [comment]
> Can you showcase a series that has more than 100,000 chapters? Kavita just moved to 100000 as an internal coding. I don't want to change it without a solid reason. If you are requesting this as more of a feature, please shift this to a Github Discussion so other users can upvote and help me prioritize or consider it.

Can you tell me where to fix it when I personally use it with a fork?

**Comment by majora2007** [comment]
> > Can you showcase a series that has more than 100,000 chapters? Kavita just moved to 100000 as an internal coding. I don't want to change it without a solid reason. If you are requesting this as more of a feature, please shift this to a Github Discussion so other users can upvote and help me prioritize or consider it.
> 
> Can you tell me where to fix it when I personally use it with a fork?

Parser.cs has the values. If you change it, you will likely loose data unless you write a manual migration.

**Comment by ytoaa** [comment]
> Parser.cs has the values. If you change it, you will likely loose data unless you write a manual migration.

Thank you so much.

**Comment by ytoaa** [comment]
> > > Can you showcase a series that has more than 100,000 chapters? Kavita just moved to 100000 as an internal coding. I don't want to change it without a solid reason. If you are requesting this as more of a feature, please shift this to a Github Discussion so other users can upvote and help me prioritize or consider it.
> > 
> > 
> > Can you tell me where to fix it when I personally use it with a fork?
> 
> Parser.cs has the values. If you change it, you will likely loose data unless you write a manual migration.

By adjusting the numbers, it was confirmed that the volume recognizes a large number normally.
However, the chapter was not normal.
So, I wrote an additional debug to output the info value.

[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Processing series txx
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Updating 1 volumes on txx
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Parsing txx - Volume 1
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Info Details:
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Chapters (System.String): 990000002
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Series (System.String): txx
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] SeriesSort (System.String): 
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] LocalizedSeries (System.String): 
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Volumes (System.String): 1
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Filename (System.String): 002_0_1.jpg
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] FullFilePath (System.String): /manga/collect/hit/t/t Omake/txx/txx Vol1 Ch. 990000002 (collect)/002_0_1.jpg
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Format (API.Entities.Enums.MangaFormat): "Image"
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Edition (System.String): 
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] IsSpecial (System.Boolean): false
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] SpecialIndex (System.Int32): 0
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Title (System.String): 002_0_1
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] IssueOrder (System.Single): 990000000
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] ComicInfo (API.Data.Metadata.ComicInfo): null
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Info Details:
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Chapters (System.String): 990000002
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Series (System.String): txx
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] SeriesSort (System.String): 
[Kavita] [2024-05-02 10:45:29.327 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] LocalizedSeries (System.String): 
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Volumes (System.String): 1
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Filename (System.String): 001_0.jpg
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] FullFilePath (System.String): /manga/collect/hit/t/t Omake/txx/txx Vol1 Ch. 990000002 (collect)/001_0.jpg
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Format (API.Entities.Enums.MangaFormat): "Image"
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Edition (System.String): 
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] IsSpecial (System.Boolean): false
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] SpecialIndex (System.Int32): 0
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Title (System.String): 001_0
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] IssueOrder (System.Single): 990000000
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] ComicInfo (API.Data.Metadata.ComicInfo): null
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Info Details:
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Chapters (System.String): 990000001
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Series (System.String): txx
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] SeriesSort (System.String): 
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] LocalizedSeries (System.String): 
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Volumes (System.String): 1
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Filename (System.String): 008_1_a4.jpg
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] FullFilePath (System.String): /manga/collect/hit/t/t Omake/txx/txx Vol1 Ch. 990000001 (collect)/008_1_a4.jpg
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Format (API.Entities.Enums.MangaFormat): "Image"
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Edition (System.String): 
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] IsSpecial (System.Boolean): false
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] SpecialIndex (System.Int32): 0
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Title (System.String): 008_1_a4
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] IssueOrder (System.Single): 990000000
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] ComicInfo (API.Data.Metadata.ComicInfo): null
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Info Details:
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Chapters (System.String): 990000001
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Series (System.String): txx
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] SeriesSort (System.String): 
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] LocalizedSeries (System.String): 
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Volumes (System.String): 1
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Filename (System.String): 005_1_a1.jpg
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] FullFilePath (System.String): /manga/collect/hit/t/t Omake/txx/txx Vol1 Ch. 990000001 (collect)/005_1_a1.jpg
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Format (API.Entities.Enums.MangaFormat): "Image"
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Edition (System.String): 
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] IsSpecial (System.Boolean): false
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] SpecialIndex (System.Int32): 0
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Title (System.String): 005_1_a1
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] IssueOrder (System.Single): 990000000
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] ComicInfo (API.Data.Metadata.ComicInfo): null
[Kavita] [2024-05-02 10:45:29.328 +09:00  95] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, txx - Vol 1 Ch 990000002

There actually seemed to be a difference between the perceived chapter and the value of IssueOrder. Actually the chapter reflected in the webui was IssueOrder. Can you give me any additional help?

**Comment by majora2007** [comment]
Please link me to your fork so I can review you implemented it correctly. IssueOrder is used just for Sorting the chapters and is not visual to the user.

**Comment by ytoaa** [comment]
> Please link me to your fork so I can review you implemented it correctly. IssueOrder is used just for Sorting the chapters and is not visual to the user.

https://github.com/ytoaa/Kavita
Here is my fork link.

**Comment by ytoaa** [comment]
> Please link me to your fork so I can review you implemented it correctly. IssueOrder is used just for Sorting the chapters and is not visual to the user.
![스크린샷 2024-05-02 221017](https://github.com/Kareadita/Kavita/assets/24527825/10b52a07-f5f3-4117-a1da-338fbbca7f7e)
![스크린샷 2024-05-02 221024](https://github.com/Kareadita/Kavita/assets/24527825/b82d5341-ff25-4fe9-9501-801b6159f36a)

**Comment by majora2007** [comment]
I didn't fully look, but there is a place in the UI you also need to update the internal number with, did you do that?

**Comment by ytoaa** [comment]
> I didn't fully look, but there is a place in the UI you also need to update the internal number with, did you do that?

oh... I don't think so, can you tell me where to fix it?

**Comment by ytoaa** [comment]
> I didn't fully look, but there is a place in the UI you also need to update the internal number with, did you do that?

And I don't know if it's simply the ui problem. It's written in db like this.
![스크린샷 2024-05-03 000041](https://github.com/Kareadita/Kavita/assets/24527825/76b92023-c5e0-4937-a68c-5881b12694c4)
![스크린샷 2024-05-03 000057](https://github.com/Kareadita/Kavita/assets/24527825/bcfe4a2d-37ca-4874-8944-438c4159f696)
![스크린샷 2024-05-03 000102](https://github.com/Kareadita/Kavita/assets/24527825/907d5be8-959a-4f43-a460-8d13d044c2aa)

**Comment by ytoaa** [comment]
> I didn't fully look, but there is a place in the UI you also need to update the internal number with, did you do that?

UI/Web/src/app/_models/chapter.ts
I modified the file, but it's the same symptom.

**Comment by ytoaa** [comment]
This is
StringExtensions.cs
I noticed that it was a problem with AsFloat.
Well...

**Comment by ytoaa** [comment]
![image](https://github.com/Kareadita/Kavita/assets/24527825/9303ed4d-379a-456f-91c3-bcb326bf28b7)
We were able to implement the data types of chapters and volumes by changing them from float to double.
