### ISSUE TITLE
Infinite cache creation during raw image series loading

### ISSUE THREAD

**Issue by ytoaa** [Kareadita/Kavita#2910]
### What happened?

This happened in version 0.8.1, no problem in 0.8.0.
After selecting a chapter with approximately over 100 images, I was able to see that it was infinitely created in the cache folder when it was loading.

### What did you expect?

I've seen that the storage is giving out rapidly

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
Can you break this down into steps to reproduce like:
1. Open chapter in Kavita
Expected: See 100 files in cache
Actual: ...

**Comment by ytoaa** [comment]
> Can you break this down into steps to reproduce like:
> 
> 1. Open chapter in Kavita
>    Expected: See 100 files in cache
>    Actual: ...

Okay. First, the root folder is /t, and there is ./test/Vol2 Ch. 16614321/(image files) in it.
There are 100 images in that chapter, and when you press the chapter, the status of the cache folder is as follows.
![스크린샷 2024-04-24 142828](https://github.com/Kareadita/Kavita/assets/24527825/38517d2a-7b6e-4561-be0b-31ad02b6d2a3)
![스크린샷 2024-04-24 142512](https://github.com/Kareadita/Kavita/assets/24527825/ad4b6f61-ee05-4430-9f5f-833b3ed1ecb1)
Then, raise the version to 0.8.1, force a scan of the library with the image, and press the chapter again.
![스크린샷 2024-04-24 142512](https://github.com/Kareadita/Kavita/assets/24527825/693a8783-e87f-45a6-aaf8-874f77f69760)
In the cache folder, folders with a myriad of the same files are created.
![스크린샷 2024-04-24 142637](https://github.com/Kareadita/Kavita/assets/24527825/3bbd759c-7701-416a-b436-c47e122a1a5d)


For your information, there is only one chapter above in that series.

If you create a series with a lot of images in the default state without having to follow the above method, the same problem arises.

Next is the "trace" log
[_kavita-kavita-1_logs (4).txt](https://github.com/Kareadita/Kavita/files/15088334/_kavita-kavita-1_logs.4.txt)

---------------------------------------------------

A few more tests show that you create as many cache folders as images, and then you put the images in the cache folder to create 100*100 = 10000 images

**Comment by majora2007** [comment]
Okay from the Kavita image, it does look like Kavita is functioning correctly. if you see, chapter X has 100 duplicates (likely a bad parsing), so when you open to read, it's moving all those internal files out. 

I'll try to reproduce with your file layout you've given. It might be beneficial for me to build you a dedicated build and have you test it out, since you're a heavy Image library user.

**Comment by ytoaa** [comment]
> 좋아요, Kavita 이미지를 보면 Kavita가 정지 작동하는 것처럼 보입니다. 그렇다면 X 장은 100개의 소수 항목이 있다는 것(잘못된 분석일 가능성이 있음)을 읽기 위해 열면 모든 내부 파일이 외부로 이동됩니다.
> 
> 귀하가 제공하는 파일 형식으로 복사해 드립니다. 당신은 리그 이미지를 많이 사용하는 사용자에게 최고의 빌드를 구축하고 테스트해 보는 데 도움이 될 수 있습니다.

For now, I will stay in version 0.8.0 until the issue is fixed.

**Comment by ytoaa** [comment]
> Okay from the Kavita image, it does look like Kavita is functioning correctly. if you see, chapter X has 100 duplicates (likely a bad parsing), so when you open to read, it's moving all those internal files out.
> 
> I'll try to reproduce with your file layout you've given. It might be beneficial for me to build you a dedicated build and have you test it out, since you're a heavy Image library user.

For now, I will stay in version 0.8.0 until the issue is fixed.
Thank you so much for your care.

**Comment by ytoaa** [comment]
It's like recognizing raw image files like zip or cbz.

**Comment by ytoaa** [comment]
![image](https://github.com/Kareadita/Kavita/assets/24527825/d9148239-a500-4f71-bdd9-6da06b527755)
https://github.com/Kareadita/Kavita/pull/2874
CacheService.cs
After replacing the file with version 0.8.0 and building it
We have confirmed that the problem has disappeared.
It's related to #2770

**Comment by ytoaa** [comment]
"if (files.Count > 0 && files[0].Format == MangaFormat.Image)"

In
"_readingItemService.Extract(file.FilePath, Path.Join(extractPath, extraPath), MangaFormat.Image, files.Count);"

The code
"_readingItemService.Extract(file.FilePath, Path.Join(extractPath, extraPath), MangaFormat.Image);"

I adjusted it to this. If you do this
The cache problem and
#2770
I was able to solve at the same time.
