### ISSUE TITLE
Updated file in nested folder causes entire top level folder scan

### ISSUE THREAD

**Issue by CubeyGlyph** [Kareadita/Kavita#2912]
### What happened?

The most recently touched file in a series folder nested inside a publisher folder  (the root folder for the library being /data/Western Comics) triggers a scan of everything inside that publisher folder.  

See thread below:
https://discord.com/channels/821879810934439936/1232394233760186399

### What did you expect?

Only the updated folder (series) should be scanned

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Other (List in "Additional Notes" box)

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

What is visible on the browser side occurs on Multiple Browsers (scanning takes a long time and then eventually the constant api requests of the home page updating during such a massive scan when left on the home page constantly updating eventually causes SQLite issues). Once scanning issue resolved this GUI symptom will resolve itself.

**Comment by majora2007** [comment]
Note for myself, look into a way to have lower level (lowest series folder) folder changed mechansim to avoid extra work.

**Comment by majora2007** [comment]
I was able to figure out how to do this optimization. It will need extended testing in nightly, but should greatly help for users like yourself that organize by publisher first or acquire a lot of media on a daily basis.
