### ISSUE TITLE
All library and config lost when updating

### ISSUE THREAD

**Issue by Maitresinh** [Kareadita/Kavita#2915]
### What happened?

2 times, i've been updating the docker on Unraid. Lost all my config....

### What did you expect?

to keep my config, and libraries.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
This is not a Kavita issue, but a config issue. Please post your volume mounts and the underlying image you are using. 

We have ample instructions on our wiki for the different images and the requirements for Kavita's config. 
https://wiki.kavitareader.com/installation/docker

**Comment by Maitresinh** [comment]
docker image : on unraid

![Capture d'écran 2024-04-25 223245](https://github.com/Kareadita/Kavita/assets/37817197/f42b71ba-2036-4ece-8b9d-caf7476413ee)

**Comment by scare376** [comment]
the config mount path is incorrect. for the jvmilazz0 repo the internal path should be /kavita/config

**Comment by Maitresinh** [comment]
like this ?
![Capture d'écran 2024-04-26 000621](https://github.com/Kareadita/Kavita/assets/37817197/aa56b338-9fb7-4bfc-a426-d434b68c7aee)


Or do i have to change the host path

**Comment by scare376** [comment]
Container path is correct

**Comment by Maitresinh** [comment]
Corrected. Books are scanned. Thanks.
but i'm afraid i will loose my config every time i update

**Comment by therobbiedavis** [comment]
> Corrected. Books are scanned. Thanks.
> 
> but i'm afraid i will loose my config every time i update

Check /mnt/user/appdata/kavita/ to ensure your DB and configs are being written to. If they are then you're set. Kavita itself doesn't delete your db or config. The issue is that the container was only writing within the container, not to your hard drive (persistent volume) so anytime the container stopped/restarted everything was lost.

**Comment by scare376** [comment]
yes double check the appdata folder. seeing as you didn't error out when you corrected the mount point it _should_ be fine and everything should be there

**Comment by Maitresinh** [comment]
i've got that
![Capture d'écran 2024-04-26 104148](https://github.com/Kareadita/Kavita/assets/37817197/ed7376fa-8869-4c6d-958e-5627d579776a)

What is the config file ?

**Comment by scare376** [comment]
Thats the whole folder. Everything looks to be there. You should be fine next time you update.

**Comment by Maitresinh** [comment]
fine thanks.
The only stranger thing is that it appears to be appdata/kavita. No mnt/ in front (which appear at root, but empty).
But i'm probably don't understand correctly how folders work on unraid.

**Comment by Maitresinh** [comment]
On unraid, if you loose your config after updating....

**Comment by scare376** [comment]
FYI I've been hosting Kavita on an unRAID server for a little over 2 years now. I've had very little issue updating stable releases.
