### ISSUE TITLE
No books scanned

### ISSUE THREAD

**Issue by Maitresinh** [Kareadita/Kavita#2916]
### What happened?

On a fresh install (see other post, Kavita lost all confi after update), i re-installed my libraries. All good for comics, magazines and manga. But no "books" (novels) scanned

### What did you expect?

To see the books (novel) appearing like manga/comics does.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
I'm on unraid, last version. Just made an update of Kavita docker.
All my book are, like before, in the right folders
```

**Comment by majora2007** [comment]
Since you lost config, I can only assume docker. Can you share your docker mount? And please attach logs (you can do the scan then download) so we can see what's happening.

**Comment by scare376** [comment]
Also can you give us an idea on the folder structure of your library folders?

**Comment by Maitresinh** [comment]
thanls for your time

attached the logs (on unraid, righ click on the dock, logs) and a screen capture of folders

![Capture d'écran 2024-04-25 222914](https://github.com/Kareadita/Kavita/assets/37817197/ae0e584c-f7e1-4d17-874b-b9478ece708a)

[logs kavita.txt](https://github.com/Kareadita/Kavita/files/15120420/logs.kavita.txt)

**Comment by Maitresinh** [comment]
and subfolders

![Capture d'écran 2024-04-25 223123](https://github.com/Kareadita/Kavita/assets/37817197/428f31f3-7d3c-464c-b2fe-b2e685b8fbc3)

**Comment by majora2007** [comment]
Okay so as mentioned on the other issue, your config mount point is incorrect. 

Second, your book folders should not be in the kavita config directory. The Kavita config is for Kavita to store it's internal state. You need a separate location for your book files.

**Comment by Maitresinh** [comment]
My book folder is

/mnt/user/Livres/

Kavita config is into

/mnt/user/appdata/kavita/

What do you suggest ? appdata are by default, so is would have to put my media outside user ? Or mnt ?

**Comment by scare376** [comment]
Joe is commenting on the fact that you have a lot of extra folders in your Kavita config folder so it looks like you're storing your library there. Can you please show us the folder structure for the library that is having an issue. Also since you said it's novels I'm assuming they are epubs?

**Comment by Maitresinh** [comment]
![Capture d'écran 2024-04-26 002426](https://github.com/Kareadita/Kavita/assets/37817197/73cc47d2-47dd-4012-9b11-98235c8364f2)
there are also two folder, temp and template

**Comment by scare376** [comment]
That's not what i was looking for. not your full library folder. the folder for the specific library you are having an issue with. you said that 3 of them is working 1 is not. also if it is epub make sure that the epub toggle is turned on in the advanced library settings.

**Comment by Maitresinh** [comment]
it was the two "books" folder, "romans" and "manuels", shown in the list. epub was one.
Now everything is fine, again :)

thanks for this wonderfull work

**Comment by scare376** [comment]
Glad it's working now.

**Comment by pedroponte** [comment]
Can't seem to have this working properly.

Also had a problem when scanning the first library.

I have recreated the server and it worked with the first library/folder. 

Now, having added new library and folder mounted on

/mnt/pdf/xyz

it can't find any files on the second one.

Are there any logs I can share to allow troubleshooting?
Could this be about file/ownership permissions?

The pdf files are hosted on the host server.
The server is running on a docker engine.
The pdf files are mapped into the /mnt/pdf folder.

TIA

[Kavita] [2024-07-16 15:14:27.694 +00:00  75] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on myfiles

[Kavita] [2024-07-16 15:14:27.694 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library myfiles Step 1: Scan Files

[Kavita] [2024-07-16 15:14:27.694 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library myfiles Step 1.A: Process 1 folders

[Kavita] [2024-07-16 15:14:27.695 +00:00  75] [Debug] API.Services.Tasks.ScannerService 	[ScannerService] Library myfiles Step 1.B: Scan files in /mnt/pdf/myfiles

[Kavita] [2024-07-16 15:14:27.695 +00:00  75] [Debug] API.Services.Tasks.ScannerService 	[ScannerService] Library myfiles Step 1.C: Process files in /mnt/pdf/myfiles

[Kavita] [2024-07-16 15:14:27.695 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library myfiles Step 2: Track Found Series

[Kavita] [2024-07-16 15:14:27.695 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library myfiles Step 3: Process Parsed Series

[Kavita] [2024-07-16 15:14:27.695 +00:00  75] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished file scan in 0 milliseconds. Updating database

[Kavita] [2024-07-16 15:14:27.695 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library myfiles Step 4: Save Library

[Kavita] [2024-07-16 15:14:27.711 +00:00  75] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished library scan of 0 series in 18 milliseconds for myfiles. There were no changes

[Kavita] [2024-07-16 15:14:27.711 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library myfiles Step 5: Remove Deleted Series

[Kavita] [2024-07-16 15:14:27.711 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan

[Kavita] [2024-07-16 15:14:27.711 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 0 series that needs to be removed: []

[Kavita] [2024-07-16 15:14:27.711 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan - complete

[Kavita] [2024-07-16 15:14:27.713 +00:00  37] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache directories

[Kavita] [2024-07-16 15:14:27.713 +00:00  37] [Information] API.Services.Tasks.CleanupService Cache directory purged

[Kavita] [2024-07-16 15:14:29.635 +00:00  77] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 1.0041 ms

[Kavita] [2024-07-16 15:14:29.636 +00:00  76] [Information] API.Controllers.AccountController confirm-email failed from invalid registered email: redacted@gmail.com

[Kavita] [2024-07-16 15:14:29.636 +00:00  76] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/account/confirm-email-update responded 400 in 0.7940 ms

[Kavita] [2024-07-16 15:14:29.691 +00:00  76] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 0.4332 ms

[Kavita] [2024-07-16 15:14:29.740 +00:00  76] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 0.3881 ms

[Kavita] [2024-07-16 15:14:47.659 +00:00  77] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 0.8325 ms

[Kavita] [2024-07-16 15:14:47.711 +00:00  73] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 0.6615 ms

[Kavita] [2024-07-16 15:14:47.768 +00:00  73] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 0.6120 ms
