### ISSUE TITLE
PDF Reader unable to search for text

### ISSUE THREAD

**Issue by Kimbaras** [Kareadita/Kavita#2918]
### What happened?

I'm not sure if I'm blind or missed anything but...

Basically when opening a PDF file (under a "Book" library, if that is usefull) I get no "search" button / icon...
The wiki page for the PDF Reader is empty right now but from googling a bit and images from previous issues / posts seems there should be a "text search" inside the PDF...

What I'm getting is
![no-search](https://github.com/Kareadita/Kavita/assets/102742484/1e1f5170-c0b0-4bc1-a62d-8ed2afeb4332)

At the beginning I tought it was a PDF issue as also searching for text in Adobe did not provide any result, so I changed file with text search working properly in Adobe, but in Kavita the search icon is still missing...

### What did you expect?

The search button / icon to be present as depicted the in picture
![search](https://github.com/Kareadita/Kavita/assets/102742484/738b0b69-d5ac-478f-9bcb-4025952e39e5)

Disclaimer: I understand the image I got is old (Sep 2022, coming from https://github.com/Kareadita/Kavita/issues/1523 ) but I don't think I've seen anything about the feature going away (which would be a downgrade in my opinion)

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### Additional Notes

This is a new installation of Kavita (so starting directly with 0.8.1, no upgrading or anything)

**Comment by slaszt** [comment]
This is the case for me also, but there are a couple of ways to search without the search icon:

- On desktop, use the keyboard shortcut Ctrl + F
- On Android, tap the menu icon (three dots), then select 'Find in page'

Assuming that you're using a common browser, these solutions should work for you. I am using Firefox on Linux and Android but Chrome, Edge, and others should behave similarly even on Windows.

It would be nice to have a dedicated search icon like before though.
