### ISSUE TITLE
Translation Error for German Language

### ISSUE THREAD

**Issue by Zombanana** [Kareadita/Kavita#2920]
### What happened?

Hi,

I just setup a new kavita server inside docker and my first impression was, that something is wrong.
I got under every issue the Message "Fehler #1", "Fehler #2", etc...
"Fehler means translated into German Language error"...
![Screenshot 2024-04-27 050453](https://github.com/Kareadita/Kavita/assets/97361360/6ed55867-b426-4bcd-a58e-059a0b61145e)

I have searched for a hour, which problem my server could have, and couldn't find anything.
Well, I had my kavita server before on a Windows machine running.
I have open my library inside this and had noticed, that I have no problem with my server...
![Screenshot 2](https://github.com/Kareadita/Kavita/assets/97361360/c58270e2-e12e-4b7e-916a-11cc479050ee)

Well, seems something has translated the word "Issue" into german, which means "Fehler", which is an error.
The word Issue shouldn't be translated into german language, because the translation is wrong.

So please, I hope you can fix it in future releases.

Also. I have running kavita inside windows, there is the correct word, as "Issue".
I also have running kavita inside a docker container. -> the linuxserver docker container.

### What did you expect?

I would expect the correct translation -> "Issue" as "Issue" in German.
Translating it into "Issue" -> "Fehler" is wrong.

It give german user the assumption, the server has an error and something is broken.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by DieselTech** [comment]
All the translations come from the community using a tool called Weblate. 

https://hosted.weblate.org/projects/kavita/ui/de/

The problem is there is some people that go through and translate strings for projects but they don't understand how the words are used or the context in which they are used. This creates bad translations and becomes very hard for us to spot them. If you want to help translate some of Kavita you can sign up on the weblate site and submit some translations. That will help everyone in the community who speaks that language. Right now it looks like Germany is only at 32% translated.

**Comment by majora2007** [comment]
We also have a role on the server where I reach out to translators. I would love to have it locked down to dedicated translators, but I doubt that would help as then stable releases would have partial localization.

**Comment by Zombanana** [comment]
You can close my issue. I have corrected it in Weblate. The correct word is "Ausgabe".
I have also noticed another "misspelling":

![Screen](https://github.com/Kareadita/Kavita/assets/97361360/cc30ed96-8dff-423e-804a-d9934d492bc1)

Instead of "5er-Serie" now it should show "5 Serien".
I think it is as DieselTech wrote, that people don't know what they translate in which context.

**Comment by majora2007** [comment]
Yes I think you can also leave a comment underneath the string to give context or even an image. Feel free to leave notes so it doesn't happen again.
