### ISSUE TITLE
Upgrade to 0.8.x deletes reading lists

### ISSUE THREAD

**Issue by DireMunchkin** [Kareadita/Kavita#2924]
### What happened?

After upgrading to 0.8.0 or 0.8.1 and then force scanning the library (as 0.8.0 release notes tell you to do) most books disappear from reading lists, there's maybe 1-2 books left out of 30-40 per list.

The series still appear to be in the library, but the list membership for most of them are lost after migrating.

I've looked at the logs but didn't really find anything relevant.

### What did you expect?

I expected no data loss on the upgrade.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
This could be due to the chapters/issues being recreated as a lot of internal codings were changed. Unfortunately there isn't much I can do after the fact, you could probably just reimport the cbl if you used them or you may need to manually create.

Some data loss was expected on the update given the sheer size of the changes.

**Comment by DireMunchkin** [comment]
I should have mentioned - I do have daily snapshots of Kavita so I rolled back to 0.7.13 and the pre-migration database. I still have all my data now, but I can't upgrade without deleting it again.

I created reading lists within Kavita, not from CBL - I don't suppose I could export them to CBL or something and re-import them after migrating?

**Comment by DieselTech** [comment]
To add on to what the Dev said above, I just wanted to address this point: 

> What did you expect?
>I expected no data loss on the upgrade.

I'm sorry but that's just an unreasonable expectation at this stage of development. Even with Kavita not following Semantic Versioning, the general industry perspective is that with software under version 1.0.0 you can/should expect some data loss along the way. While a lot of effort has been made to save the users data at every migration, sometimes it's just not feasible to put the time into making migrations when they can take 100+ hours of work for a single upgrade. That is time best spent working on new features or other core functionality.

**Comment by DireMunchkin** [comment]
OK fair enough, I'll recreate them manually then.

**Comment by majora2007** [comment]
We don't have reading list to CBL export but it has been a thought of mine. If you want it, please create a feature request and I can look into it for future situations like this.
