### ISSUE TITLE
One-Shots showing up as Volume 100000 in UI and scrobble history

### ISSUE THREAD

**Issue by chilliwow** [Kareadita/Kavita#2926]
### What happened?

Was gonna read a oneshot and saw this, tested with 3 different oneshots, either have "SeriesName - Oneshot" as filename or One-Shot as format tag in ComicInfo.

Curious if this will set my progress on AL as volume 100000 too

![image](https://github.com/Kareadita/Kavita/assets/31785430/849f739d-33d3-4903-a3b1-b5d60d41ea5f)![image](https://github.com/Kareadita/Kavita/assets/31785430/8b6eadc5-08d0-4993-a571-9dfaa49f6b2f)

### What did you expect?

- Instead of Volume 100000, display Volume 1, Chapter 1, or just "One-Shot".
- Data in scrobble history to not be Volume 100000

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
It shouldn't report to AL that you've read 100000, it will remap it to 0. Specials/One-Shots are a bit tricky on reporting because usually in Kavita they are just one file but without any chapter/volume information. 

Internal encodings shouldn't be visible in the UI for sure. I'll take a look into this.
