### ISSUE TITLE
Musl release requires libgcc

### ISSUE THREAD

**Issue by alpharde** [Kareadita/Kavita#2934]
### What happened?

Musl release expects libgcc, which shouldn't happen.
```
Error loading shared library libstdc++.so.6: No such file or directory (needed by ./Kavita)
Error loading shared library libgcc_s.so.1: No such file or directory (needed by ./Kavita)
```

### What did you expect?

Application successfully starting.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

Alpine 3.19

**Comment by majora2007** [comment]
I'm not really sure what the issue you're posting about is. Can you provide helpful information so I can help you? Like what is your OS, what is  your mode of consumption of Kavita, etc.

**Comment by alpharde** [comment]
Sorry. I'm using Alpine Linux, which is a musl first OS and doesn't include libgcc. It's weird to expect libgcc on such an environment.

**Comment by DieselTech** [comment]
> Sorry. I'm using Alpine Linux, which is a musl first OS and doesn't include libgcc. It's weird to expect libgcc on such an environment.

libgcc is a requirement of .net 8.0 

https://github.com/dotnet/core/blob/main/release-notes/8.0/linux-packages.md#packages

Looks like they provide a set of commands for Alpine to install the necessary requirements.

**Comment by DieselTech** [comment]
This is a core requirement of being able to run .NET programs and out of scope for this project.
