### ISSUE TITLE
epub not displayed as Special, if there is any pdf in the same folder 

### ISSUE THREAD

**Issue by jingkang99** [Kareadita/Kavita#2935]
### What happened?

even there are more than 1 epub in the same folder, only one displayed

### What did you expect?

epub should be handled

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
if folder has a epub, it isn't recognized as BOOK
```

### Additional Notes

dd

**Comment by majora2007** [comment]
Your post doesn't have much information, but I'm not able to reproduce. See the folder layout:

![image](https://github.com/Kareadita/Kavita/assets/735851/86622c30-85f9-47b1-a912-80c441e176c2)

![image](https://github.com/Kareadita/Kavita/assets/735851/7f54d446-a7be-4c1e-b65a-9ece292f967f)

Both epub and pdf in the folder were able to be parsed and created as series. 

Please check that you have pdfs enabled for the library under Advanced tab in Library Settings modal.

**Comment by jingkang99** [comment]
Thanks a lot for the replying. I understand that Ebooks are controlled entirely around the metadata that is written to the file. I should ask like:

what metadata should be modified or added to an EPUB, then it shows up as Special as other PDF file?

for example, folder created like following, and put some pdf files here
**book/publisher/oreilly**

![image](https://github.com/Kareadita/Kavita/assets/10793075/3021fe5c-0a65-448e-936c-74b31f2af634)

PDFs show up as Special, and looks fine. Thanks for your effort.

![image](https://github.com/Kareadita/Kavita/assets/10793075/0374a9b4-6177-47f8-a741-a35543ac329b)

BUT, EPUB is created as a NEW Series under Publisher. My intension is to group books for each publisher. 

![image](https://github.com/Kareadita/Kavita/assets/10793075/260be9e3-7680-426a-b503-ef4013596218)

any suggestion on how to put epub in the same publisher? by modify metadata or folder name, etc...?

Now I only can put all epub in ONE folder, each book is a series, not very nice. 

similar scenario, I download bunch EPUB books of JOHNdo, and save to a folder, each book shows up as a series, not under ONE AUTHOR. again, what should be changed to group the epub?

btw, it will be great to support mobi format. 

Thanks a lot

**Comment by scare376** [comment]
Mobi support will not be added. Just convert them to epub. You need to add series metadata with an app like calibre or sigil to get epubs to group together correctly

**Comment by majora2007** [comment]
Please see here the wiki entry for the metadata on EPUBs and how Kavita interprets. 

https://wiki.kavitareader.com/guides/metadata/epubs

Based on how you want your files (all to be under Oriely), you would need to edit the series group for the epub file. 

Mobi will not be supported. It is a dead format and limited library support.
