### ISSUE TITLE
Title Issues Removed ... Except for One.

### ISSUE THREAD

**Issue by maximo1984** [Kareadita/Kavita#2938]
### What happened?

I had every issue of Detective Comics imported, and reading lists set up for all trade paperbacks. (a lot of work).
Suddenly, every issue was gone except for one. All reading lists were removed as well.

The issue I suspect, is that the one issue that was remaining, had inside the archive, a folder with the images and the .xml file (not inside the folder). All other issues I assume had the xml inside the folder. I fixed this single issue and rescanned the library. This brought all the issues back. I'm assuming that the parser cannot differentiate between one or the other and so it chose 1 archive structure. I am not sure how this single issue ended up like this and why it was not a problem before.

Is there any way to bring back the reading lists that were removed or do I have to build them again? This is not something that can be easily avoided if you are imported thousands of issues (I'm not going to open every one and ensure the file structure is all the same).

### What did you expect?

I did not expect a large swath of issues to just disappear.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by maximo1984** [comment]
Action Comics is doing the same thing. All issues are no longer available. As you can see here, the only issue that was left, was this one, which was in another folder (Booster Gold). And it has that structure I was talking about. Folder with images, and .xml file.
![Screenshot from 2024-05-05 17-21-23](https://github.com/Kareadita/Kavita/assets/40921347/11c62a1c-d2e1-4af0-a640-f5a5b0ef34d1)

If I fix this, and rescan, should bring them all back in. However, every new scan, will reimport all of Detective Comics and Action Comics so I cannot make any reading lists with them.

**Comment by majora2007** [comment]
I'm not fully grasping the situation. You had a functioning set of series, then randomly during a scan, the series deleted (or the issues within it deleted) without any change to the filenames/metadata/folder location?

**Comment by maximo1984** [comment]
Correct. And once it did that, it erased all of the trade paper back reading lists I had created. It is now reimporting both of these series on every scan. So even if it is fixed that they are in there, I cannot create reading lists as they will just be destroyed on every scan.

**Comment by majora2007** [comment]
Okay the only way for Kavita to remove an issue is if the underlying file is removed from disk, they change volume/issue number, or if you have another series of the same name and format parallel from the library root. 

Can you provide information on your library type and check if between scans, the path of one of the issues doesn't change?

**Comment by maximo1984** [comment]
Given those reasons, I would suspect that the single Action Comics issue that was in Booster Gold likely caused the issue. It will take awhile to look and see if this is the problem for Detective Comics. I removed that issue from Booster Gold so will watch on next scan if Action Comics is re-imported. If not, that will solve the issue and I only need to track down whatever lone issue of Detective Comics is sitting out there.

**Comment by maximo1984** [comment]
I believe that was the issue. Closing thread.
