### ISSUE TITLE
Light Novel Specials not going in the appropriate Series

### ISSUE THREAD

**Issue by edhelcu** [Kareadita/Kavita#2943]
### What happened?

 i have some light novel series that i wanna have specials in. example: Serie: High School DxD 1-25; Special: High School DxD EX. but no mater how i mess around with the metadata (using Metadata Editor) i can get it to work. i tried puting in series but no Series Index (Series: High School DxD, Series Index:   ) which results in that the Special is seprat under the Title name (High School DxD EX) and if put the series index as SP1  it just adds it to the normal series. and i have the File Name set as High School DxD SP1 High School DxD EX. So either the Special Tab is broken or i'm doing something wrong.
 
My structure is like this:
High School DxD
- High School DxD Volume 1 Diabolus of the Old School Building
- ect.
- Special
  - High School DxD SP01 High School DxD EX

and this ih how i have the Metadata set up
![High School DxD knipsel](https://github.com/Kareadita/Kavita/assets/132711445/cf23f493-626d-4660-a595-c486bdbe204d)

but it show up as
![High School DxD knipsel 2](https://github.com/Kareadita/Kavita/assets/132711445/753451cf-80e3-4d84-ad93-5b66705b27d1)

### What did you expect?

That the Special would be onder the Special Tab of the series

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
N.V.T.
```

**Comment by majora2007** [comment]
It's not that you're doing something wrong, it's just that epub doesn't really have a concept of Specials and as such, Kavita never coded up anything to allow this. 

However, many users have been trying to achieve this recently. What I'm thinking is the following must be true for a Special to be captured and displayed.

1. SP marker (SP01, SP02, etc) MUST be in the filename
2. `<meta name="calibre:series">SERIES</meta>` must be in the special epub and the SERIES name must be what's going to match with the other epubs.
