### ISSUE TITLE
On initial scan of series summary not populating

### ISSUE THREAD

**Issue by Cducharme84** [Kareadita/Kavita#2944]
### What happened?

A few days ago it was mentioned on the Support channel in Discord that a user was noticing their newly added ComicVine library type series were not populating on initial scan but with no change to the file's metadata when scanning the series manually the summary pops up. They unfortunately did not have debug logging on. I do, and it seems to be pretty consistent with new series and only affect the summary portions from what I can tell of the ComicInfo.xml read.

Series I noticed it happening on and highlighted for this log is "Relic of Youth", context is this was part of 134 newly tagged archives coming from Mylar into this directory. Scan of the library containing that folder resulted in a fair amount of blank summaries that populate when "scan series" is pressed leading me to believe it may be an issue in coding that's unique to initial scan of an archive but not subsequent as those pick it up as intended.

Put in pastebin as I'm unsure of Git's log size limits.

https://pastebin.com/BAMgczPg

### What did you expect?

Initial scan to also read and populate summaries of issues/archives.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

I'm on nightly but the first user to report in the channel was not.

**Comment by Cducharme84** [comment]
https://pastebin.com/n4Hwif7K Karma police is the series in this log 
https://imgur.com/a/WQsXKYl screens of GUI action, missed grabbing it for the first series. The only GUI user action is "scan series" to fill it in.

**Comment by majora2007** [comment]
So I haven't ever been able to reproduce this. Are you still seeing it?
