### ISSUE TITLE
books fail to appear in library even if in subfolder with other books that do appear

### ISSUE THREAD

**Issue by sshanky** [Kareadita/Kavita#2945]
### What happened?

Sometimes, books don't appear in the front end.

### What did you expect?

I have some epubs that are in a folder called "other" (to ensure they are not in the library's root folder). Nearly all of them appear in the front end, but a few do not unless they're placed in another folder of their own.
![image](https://github.com/Kareadita/Kavita/assets/7282969/d0bc3b11-ea26-4abc-abe1-37efade901b8)
These books are all in a library I have called "Uncategorized". "1493" did not appear in this library until I placed it in the "1493" folder. However, 1491 and 2312 both do appear, as do the books above the "other" folder that are in their own folders. If I move "1493" next to "1491", it will disappear from the front end. This seems to happen frequently, and without reason (that I understand). 

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

Unraid. Works beautifully except for the missing books.

**Comment by adriy-be** [comment]
Hi,
I have a similar problem. But after some search I found my not listed books are inside the "Specials" part in an other book.

**Comment by adriy-be** [comment]
After I put each book in separated folders, that listed correctly.
I have used this bash command that put each files in one different folder
``for file in *; do mkdir -p "${file%.*}"; mv "$file" "${file%.*}"; done``
