### ISSUE TITLE
Kavita fails to ignore @eaDir. Regression of #311

### ISSUE THREAD

**Issue by MaxRenaud** [Kareadita/Kavita#2946]
### What happened?

I have some manga stored on a Synology NAS which creates extended directory attributes under a @eaDir directory. #311 committed a fix 3 years ago but Kavita still indexed the @eaDir files. 

this is the path that was indexed:

`./DLRAW.TO_Fujiko F. Fujio Daizenshu Doraemon vol 01-20/DLRAW.TO_Fujiko F. Fujio Daizenshu Doraemon v11-15/DLRAW.TO_小学館 藤子・F・不二雄大全集 ドラえもん 第13巻/@eaDir/DLRAW.TO_00624.jpeg@SynoEAStream`

These files aren't jpeg but Kavita indexes them and tries to serve them. I confirmed this by downloading the image and receiving `DLRAW.TO_00624.jpeg@SynoEAStream` through the browser.

The regex in #311 seems correct and inputting `@eaDir|\.DS_Store` in a [Regex tester](http://regexstorm.net/tester) with the path above returns a match. I also tried `@eaDir|\.DS_Store|\.qpkg|__MACOSX|@Recently-Snapshot|@recycle|\.@__thumb|\.caltrash|#recycle` which is what's in 0.8.1.

I don't have experience with C# and don't understand why this is happening so I'm hoping someone with more experience with the project or language can chime in.

### What did you expect?

I expected the manga viewer to display jpeg instead of the @SynoEAStream file under the @eaDir directory. Under the hood, I believe these are to be ignored by the indexer altogether but how these are ignored isn't an expectation; just that they are ignored from the viewer.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Mac

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

Running on Kubernetes and pulled latest, which points to [v0.8.1-ls36](https://github.com/linuxserver/docker-kavita/releases/tag/v0.8.1-ls36)

**Comment by majora2007** [comment]
I'm unable to reproduce this. Here is my simple test case.

Library root: E:/test
Series in: E:/test/test/@eaDir/My Daughter..../files.cbz

![image](https://github.com/Kareadita/Kavita/assets/735851/2c90a480-b7b0-41eb-9baa-320cb761d8fd)

```
[Kavita] [2024-05-14 17:59:01.081 -05:00  53] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 0 files for E:\test\test
[Kavita] [2024-05-14 17:59:01.081 -05:00  53] [Information] API.Services.Tasks.ScannerService [ScannerService] E:\test\test is empty, no longer in this location, or has no file types that match Library File Types

```

Nothing is found as `@eaDir` is a blacklisted folder.
