### ISSUE TITLE
The series volume number listing mixed.

### ISSUE THREAD

**Issue by anarasumanara** [Kareadita/Kavita#2950]
### What happened?

Manga volumes are listed in a mixed 

![2024-05-13_17-57-37](https://github.com/Kareadita/Kavita/assets/169653989/ed063eb0-7eb6-4b6a-80b7-f576570fd2e9)

![Screenshot 2024-05-13 at 18 03 15](https://github.com/Kareadita/Kavita/assets/169653989/9c0deba8-868a-467e-ad23-dcacd68b0e2b)

![Screenshot 2024-05-13 at 18 03 55](https://github.com/Kareadita/Kavita/assets/169653989/40a2005e-5cdf-4577-bdb3-b43613e77cf2)

I was using version 0.7.**, but recently updated to version 0.8.1.
But an unexpected problem arose.

The numbering order was mixed up.
This is so inconsistent that it's hard to figure out the problem.

I tried changing the number of digits just in case, but it did not solve the problem.
(Old: 1,2,3,4,5,6,7,8,9,10 --> New: 01,02,03,04,05,06,07,08,09,10)

earlier versions did not have this problem.

How can I solve this problem?

### What did you expect?

Series number listing normalized

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome

**Comment by majora2007** [comment]
I recall that padded numbers had some issues, but in 0.8.1 I had fixed them. I'll take a second look.

**Comment by anarasumanara** [comment]
I tried downgrading to 0.7.13 and the issue was fixed. I'm going to use this 0.7.13 version for a while. Thanks to you, I'm using kavita well, thank you for the constant updates.

**Comment by ZukaZero** [comment]
I have the same issue after the update from 7.1 to 8.1

no problems after downgrade to 0.7.8.2

**Comment by majora2007** [comment]
v0.8.0 is the version that introduced the custom sort order mechanism for anyone that is experiencing this. I still need to take a deeper look into this as I can't reproduce. 

I can assume you already did a series scan and are still seeing the volumes out of order?

**Comment by maximo1984** [comment]
I think I am having a similar issue. I imported 4 volumes (the same as I have been doing with other series), and it is putting all #1 together, then #2, and so on. Adding individual volumes to a reading list seems to parse out the proper ones though.

**Comment by ZukaZero** [comment]
> v0.8.0 is the version that introduced the custom sort order mechanism for anyone that is experiencing this. I still need to take a deeper look into this as I can't reproduce.
> 
> I can assume you already did a series scan and are still seeing the volumes out of order?

a new scan didnt worked for me but now...
i made a new libary and scan complete new ,and it works

**Comment by majora2007** [comment]
Okay for future reference, the changelog mentioned a force scan which ensures every file is rechecked. That's accessed from library settings. 

Going to close as it seems you are sorted.
