### ISSUE TITLE
Searching takes a long time

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#2953]
### What happened?

Search is starting to take a long time to come back with results. As you start typing it starts searching right away, but that takes time to complete, then when you finally finish typing what your looking for, it needs to compete searching for everything before that point.

This makes it feel like a bad experience because you don't know if it's still searching in the background or if there really is "no results found" There is no indication that it's actively searching, so you just sit there for 10+ seconds waiting to see if the dialog changes. 

### What did you expect?

Search should state that it is searching. Not default to "no results found" while waiting for the operation to complete. 

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
/api/search/search?queryString=day responded 200 in 6507.0227 ms
/api/search/search?queryString=day%20off responded 200 in 6373.9703 ms
```

**Comment by majora2007** [comment]
What I found was the search indicator wasn't hooked up. 

I hooked it up and also changed so Chapters and Files aren't included by default. The UI will now let you click to enable a search against those. That should drastically improve search times as well for larger installs.
