### ISSUE TITLE
Cannot delete Library

### ISSUE THREAD

**Issue by wcamicase** [Kareadita/Kavita#2963]
### What happened?

I am trying to delete a Library and it won't do anything, I've tried looking at the logs but nothing appears to be logged. I was able to delete one Library before but it seems that I cannot anymore.

### What did you expect?

To be able to delete the Library.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

Running Kavita on a Synology NAS

**Comment by majora2007** [comment]
I've seen this happen occasionally on large libraries. Sometimes it's easiest to bulk select by selecting the first series then holding shift and selecting another series further down in the list, and deleting those series first. Once you delete a good amount of series, then you can try to delete the library again.

**Comment by majora2007** [comment]
Did that work for you? If not, please attach logs of when you attempted to delete as I cannot reproduce myself.

**Comment by wcamicase** [comment]
Hello,
Sorry, I completely forgot to reply.

It has not, sadly, it seems that the size itself has no bearing on the issue that I'm encountering.
I check the logs but nothing new is showing up.
It's almost as if the button didn't get clicked.

I was able to delete one of the Libraries using Kavita on Chrome on my Android phone, but when I tried it again with another Library, the result was the same as on my desktop and I wasn't able to delete any other ever since.

It seems to be something very specific and I have no idea what might be causing it.

**Comment by wcamicase** [comment]
I've been around this issue and still am facing it.
I glanced at the LibraryController and saw that you have a logger that should say that the Library was deleted by x user.

I get no such message on my logs, which makes me think that the button itself might be the problem.

Since I'm having this issue on multiple browsers and OS's, I'm inclined to believe that this might be a bug.

The only thing I haven't tried out is downloading the source code and put a breakpoint on the delete method.

**Comment by wcamicase** [comment]
Hello again,

I managed to finally delete the Libraries.
I hadn't noticed that we also had the option on the Admin console, it worked through there.
I have been trying by doing this:
![image](https://github.com/Kareadita/Kavita/assets/18102526/d8af66e2-2d51-45d1-8b50-9741a18dce41)

I don't know if I should leave this open, as the original issue still exists.

**Comment by majora2007** [comment]
Ahh! Maybe that button doesn't work. I never used that (and forgot I added it). 

Let's leave this open and I'll fix that actionable menu item

**Comment by majora2007** [comment]
Okay I just tried with that button and it deleted the library just fine. Only thing I noticed is the side nav wasn't updated to remove the library instantly (but on refresh it was gone).
