### ISSUE TITLE
Special Keyword Removal

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#2967]
Remove Extras. Omnibus, etc from Special keywords. Too many false positives. Let's stick to encodings like SP01 only to prevent bad parsing.

**Comment by therobbiedavis** [comment]
I'm ok with this as long as the comicinfo.xml format will still trigger it being a special

**Comment by Roshri** [comment]
Depending on the library type even if they're present on the xml I think they probably shouldn't be parsed either, afaik CV takes most of those special keywords as different volumes altogether.
Maybe people more invested on this could offer more insight though

**Comment by scare376** [comment]
I agree. SP markers should be used for marking specials with filename parsing. If someone wants it to have it marked as a certain type of special they should use a comicinfo. Or you could "chain" it with the SP marker in some way with filename parsing.

**Comment by slaszt** [comment]
I'm fine with this change, people can use comicinfo if they really care that much. Given that there's really no accepted standard for metadata or different types of releases and that many libraries are organized based on personal preference, I think it makes sense not to parse specials so broadly.

**Comment by Nebelherr23** [comment]
I have a title where the 'Special' keyword backfired for me...

The Parser decided that "A Returner's Magic should be Special" is all specials of a series named "A Returner's Magic should be". 

While I still have a few ways open to fix this, I think that keywords like Omnibus, Annual, Special and what not should not be inferred from Filename, but from metadata. (Filesystem is not metadata.)

**Comment by ghost** [comment]
I agree on this one Specials & Extras parsing only backfired on me so far

**Comment by majora2007** [comment]
I'm moving forward with this.
