### ISSUE TITLE
PDF has no option of adding to "Collection"

### ISSUE THREAD

**Issue by jingkang99** [Kareadita/Kavita#2975]
### What happened?

PDF file in Special, click 3 dots, only "Add to Reading List"
No "Add to Collection"

![image](https://github.com/Kareadita/Kavita/assets/10793075/9d5217d4-532d-4cf0-a26b-1f3fa03aa36f)

### What did you expect?

able to add to Collection for grouping purpose

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by scare376** [comment]
Collections is made for series not for individual items. If you click on the 3 dots in the top right of the series page you will see the option to add to collection

**Comment by jingkang99** [comment]
Thanks a lot. get better understanding of the internal logic
