### ISSUE TITLE
Kavita merging similarly named series

### ISSUE THREAD

**Issue by Hobogrammer** [Kareadita/Kavita#2976]
### What happened?

I have two series with the following ComicInfo.xmls

不安の種＊
```
<ComicInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<Title>不安の種（１） フタの章</Title>
<Series>不安の種＊</Series>
<Volume>1</Volume>
<Summary>生ぬるい風、落下する不快感、背中に刺さる冷たい視線…。闇の種が発芽する時、非日常のモノ共が出現する！！ </Summary>
<Year>2004</Year>
<Month>6</Month>
<Day>24</Day>
<Writer>中山昌亮</Writer>
<PageCount>138</PageCount>
<LanguageISO>ja</LanguageISO>
<Pages>
<Page Image="0" ImageWidth="1782" ImageHeight="1200" Type="FrontCover"/>
</Pages>
</ComicInfo>
```

不安の種＋
```
<ComicInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<Title>不安の種＋（１）</Title>
<Series>不安の種＋</Series>
<Volume>1</Volume>
<Summary>階下の暗闇に気配を感じるような、ドアごしの殺した息づかいのような、視界の隅に映りこんだ視線のような、ざらりとした質感、気分、戦慄。 </Summary>
<Year>2007</Year>
<Month>7</Month>
<Day>6</Day>
<Writer>中山昌亮</Writer>
<LanguageISO>ja</LanguageISO>
</ComicInfo>
```

Instead of creating two distinct series, Kavita merges the two titles into 不安の種＊

### What did you expect?

Two series should be created `不安の種＊` and `不安の種＋`.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes
File structure

/manga/不安の種＋/
 * 不安の種＋ - 01.cbz
 * 不安の種＋ - 02.cbz
 * 不安の種＋ - 03.cbz
 * 不安の種＋ - 04.cbz

/manga/不安の種＊/
 * 不安の種＊ - 01.cbz
 * 不安の種＊ - 02.cbz
 * 不安の種＊ - 03.cbz

**Comment by DieselTech** [comment]
How are the files on disk? I'm not seeing the same behavior that your reporting but the files are overwriting each other when I scan. I have a feeling it's due to the character at the end of the series name. 

Was able to reproduce using the same folder / filename setup as the user.

**Comment by Hobogrammer** [comment]
Still encountering this bug after updating, performing a force scan and scanning the series unfortunately.

**Comment by majora2007** [comment]
You're right. I had written some unit tests, but forgot to re-test. This is still happening from another mechanism.

**Comment by majora2007** [comment]
Okay the issue is you're using full-width asterisk and plus symbols, whereas Kavita doesn't support them. This is a bit of a problem, because I don't want to keep adding a list of exclude characters. 

Can you elaborate why they aren't `*` and `+` respectively?

**Comment by Hobogrammer** [comment]
The metadata for these series was pulled from amazon.co.jp via Calibre.

*  [不安の種＋](https://www.amazon.co.jp/dp/B074CJGCWZ)
*  [不安の種＊](https://www.amazon.co.jp/dp/B074CKJCBL)

IIRC the metadata provided on these pages is set by the publisher and is considered to be official. I assume they aren't regular ASCII characters due to the titles being Japanese.

**Comment by majora2007** [comment]
Okay, interesting. I guess in order to support, I'll need to handle these on a case-by-case basis. I reverted adding * and added ＊！＋.
