### ISSUE TITLE
Chapter before a chapter with a dot with wrong pages

### ISSUE THREAD

**Issue by wcamicase** [Kareadita/Kavita#2978]
### What happened?

Let's say I have a chapter 5, the one after is 5.5, the pages of 5 are the pages from 5.5 repeated a couple of times.

### What did you expect?

To be able to read chapter 5 and not 5.5 multiple times.
You can see it here:
![image](https://github.com/Kareadita/Kavita/assets/18102526/0fd13a94-da87-4d6b-91db-c9465016337a)

Here is my folder with chapter 5:
<img width="671" alt="image" src="https://github.com/Kareadita/Kavita/assets/18102526/b0a091d2-f192-4f28-82fd-5f836c3a798f">

And chapter 5.5:
<img width="670" alt="image" src="https://github.com/Kareadita/Kavita/assets/18102526/2123aa67-37c1-449b-9d1b-59588904073d">

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox, Chrome

### Additional Notes

I'm running Kavita on a docker container on my Synology NAS

**Comment by majora2007** [comment]
I'm not able to reproduce. I have the following:

Runelite/Chapter 5/files 1-5.png
Runelite/Chapter 5.5/files 1.3.png

![image](https://github.com/Kareadita/Kavita/assets/735851/85db0c36-7db1-4e83-a400-de0c21296584)

When I read, I am reading Chapter 5 then Chapter 5.5

**Comment by wcamicase** [comment]
What Library type are you using? Could it be that?

**Comment by majora2007** [comment]
Library type doesn't matter on reading order. What exactly is the issue you're facing as it wasnt clear to me. 

Stable has an active bug where image series during reading extract too much. Maybe you're facing that?

**Comment by majora2007** [comment]
Just checking back now that v0.8.2 has released, are you still having this issue?

**Comment by wcamicase** [comment]
Hello!

First of all, sorry for taking so long to reply.

So, I took a bit of time to check out the behavior.
Before the latest update, if I had chapters 1.1, 1.2, and 1.3, it would also create a chapter 1 on Kavita to try to join all the 1.x chapters.
It doesn't seem like the bug still happens, however, all the chapters that had been "created" by Kavita, still exist and I haven't found a way to fix it, even when trying to force a scan. I may need to delete the Library and create a new one.

Also, it doesn't seem like the images have been all messed up like previously reported, it seems to be fixed as well.

Thank you so very much for your hard work!

**Comment by majora2007** [comment]
@wcamicase It is likely that there is some "bug" in the series when Kavita migrated to the new parsing system in v0.8.0. I would say you probably can delete the series and re-add it to have it get fixed. Sometimes these weird things happen due to big changes in how Kavita functions.
