### ISSUE TITLE
In certain situations, the night version "Exclude Pattern" function does not work

### ISSUE THREAD

**Issue by ytoaa** [Kareadita/Kavita#2982]
### What happened?

I'm having trouble with the latest branch that came up about a few hours ago. I'm not having trouble with the branch from a week ago.

jmg/*

In the same grammar above, images and compressed files in the jmg subfolders should not be detected, but the problem of detecting occurs

Nightly Testing Branch

**Comment by majora2007** [comment]
Can you attach logs from during the scan that shows `jmg/` directory being scanned?

**Comment by majora2007** [comment]
I just tested on mine. Library root is /test/. 

Exclude pattern is "One Piece/*".

test/One Piece/My Series/My Series.cbz

and everything in One Piece is skipped.

**Comment by ytoaa** [comment]
[Kavita] [2024-06-06 04:47:49.613 +09:00  51] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/v2 responded 200 in 21.6353 ms
[Kavita] [2024-06-06 04:47:49.617 +09:00  41] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/delete-multiple responded 200 in 53.9196 ms
[Kavita] [2024-06-06 04:47:49.648 +09:00  50] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/v2 responded 200 in 21.7324 ms
[Kavita] [2024-06-06 04:48:02.424 +09:00  50] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/users/has-library-access?libraryId=4 responded 200 in 2.6566 ms
[Kavita] [2024-06-06 04:48:02.433 +09:00  50] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/users/has-library-access?libraryId=4 responded 200 in 2.3780 ms
[Kavita] [2024-06-06 04:48:02.463 +09:00  54] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library/jump-bar?libraryId=4 responded 200 in 1.9103 ms
[Kavita] [2024-06-06 04:48:02.464 +09:00  41] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/filter responded 200 in 1.1152 ms
[Kavita] [2024-06-06 04:48:02.507 +09:00  50] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/v2 responded 200 in 41.7155 ms
[Kavita] [2024-06-06 04:48:03.763 +09:00  50] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/users/has-library-access?libraryId=29 responded 200 in 3.2764 ms
[Kavita] [2024-06-06 04:48:03.771 +09:00  51] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/users/has-library-access?libraryId=29 responded 200 in 2.9204 ms
[Kavita] [2024-06-06 04:48:03.808 +09:00  51] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library/jump-bar?libraryId=29 responded 200 in 1.6576 ms
[Kavita] [2024-06-06 04:48:03.810 +09:00  54] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/filter responded 200 in 1.0960 ms
[Kavita] [2024-06-06 04:48:03.831 +09:00  51] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/v2 responded 200 in 21.6898 ms
[Kavita] [2024-06-06 04:48:03.831 +09:00  50] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/v2 responded 200 in 22.0888 ms
[Kavita] [2024-06-06 04:48:05.680 +09:00  51] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/settings/library-types responded 200 in 0.8117 ms
[Kavita] [2024-06-06 04:48:05.784 +09:00  51] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library/name-exists?name=test responded 200 in 1.3816 ms
[Kavita] [2024-06-06 04:48:13.486 +09:00  50] [Information] API.Services.TaskScheduler Enqueuing library scan for: 29
[Kavita] [2024-06-06 04:48:13.488 +09:00  50] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/library/scan?libraryId=29&force=true responded 200 in 3.3336 ms
[Kavita] [2024-06-06 04:48:13.489 +09:00  23] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache directories
[Kavita] [2024-06-06 04:48:13.489 +09:00  23] [Information] API.Services.Tasks.CleanupService Cache directory purged
[Kavita] [2024-06-06 04:48:13.491 +09:00  51] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on test
[Kavita] [2024-06-06 04:48:13.494 +09:00  51] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 1 files for /manga/collect/hit/t/t Omake
[Kavita] [2024-06-06 04:48:13.494 +09:00  51] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Beginning series update on jmg, Forced: true
[Kavita] [2024-06-06 04:48:13.495 +09:00  51] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Processing series jmg
[Kavita] [2024-06-06 04:48:13.495 +09:00  51] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Updating 1 volumes on jmg
[Kavita] [2024-06-06 04:48:13.495 +09:00  51] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Parsing jmg - Volume 100000
[Kavita] [2024-06-06 04:48:13.495 +09:00  51] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, jmg - Vol 100000 Ch -100000
[Kavita] [2024-06-06 04:48:13.495 +09:00  51] [Debug] API.Services.Tasks.Scanner.ProcessSeries Updating jmg FolderPath to /manga/collect/hit/t/t Omake
[Kavita] [2024-06-06 04:48:13.495 +09:00  51] [Debug] API.Services.Tasks.Scanner.ProcessSeries Updating jmg LowestFolderPath to /t Omake/jmg
[Kavita] [2024-06-06 04:48:13.513 +09:00  51] [Information] API.Services.Tasks.Scanner.ProcessSeries Linking up External Recommendations new series (if applicable)
[Kavita] [2024-06-06 04:48:13.514 +09:00  51] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Finished series update on jmg in 19 ms
[Kavita] [2024-06-06 04:48:13.514 +09:00  51] [Debug] API.Services.MetadataService [MetadataService] Processing cover image generation for series: jmg
[Kavita] [2024-06-06 04:48:13.514 +09:00  51] [Debug] API.Services.MetadataService [MetadataService] Generating cover image for /manga/collect/hit/t/t Omake/jmg/1.png
[Kavita] [2024-06-06 04:48:13.553 +09:00  50] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/v2 responded 200 in 33.1123 ms
[Kavita] [2024-06-06 04:48:13.553 +09:00  41] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/v2 responded 200 in 33.6007 ms
[Kavita] [2024-06-06 04:48:13.587 +09:00  51] [Information] API.Services.MetadataService [MetadataService] Updated covers for jmg in 73 milliseconds
[Kavita] [2024-06-06 04:48:13.587 +09:00  51] [Debug] API.Services.MetadataService Dispatching 3 update events
[Kavita] [2024-06-06 04:48:13.596 +09:00  51] [Information] API.Services.Tasks.Metadata.WordCountAnalyzerService [WordCountAnalyzerService] Updated metadata for jmg in 8 milliseconds
[Kavita] [2024-06-06 04:48:13.596 +09:00  51] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished file scan in 0 milliseconds. Updating database
[Kavita] [2024-06-06 04:48:13.609 +09:00  51] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished library scan of 1 files and 1 series in 120 milliseconds for test
[Kavita] [2024-06-06 04:48:13.609 +09:00  51] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan
[Kavita] [2024-06-06 04:48:13.611 +09:00  51] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 0 series that needs to be removed: []
[Kavita] [2024-06-06 04:48:13.611 +09:00  51] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan - complete

**Comment by ytoaa** [comment]
> I just tested on mine. Library root is /test/.
> 
> Exclude pattern is "One Piece/*".
> 
> test/One Piece/My Series/My Series.cbz
> 
> and everything in One Piece is skipped.

Occurs when a special related word such as "Omake" is entered in the upper folder.

**Comment by ytoaa** [comment]
In this state, you will recognize the png file even if you put a pattern like *.png.

**Comment by majora2007** [comment]
I'm not able to reproduce. I also did `*.png` and on scan with the latest code, all my png's in my series were not scanned nor added to the library.

**Comment by ytoaa** [comment]
> I'm not able to reproduce. I also did `*.png` and on scan with the latest code, all my png's in my series were not scanned nor added to the library.

This is how I reproduce it.
Add the top-level "T" folder to the library folder and
Add the "T Omake" folder to the subfolder
The jmg folder is located in the "T Omake" folder subfolders.

**Comment by majora2007** [comment]
Okay if you have:
library root: T
Folder:
T/T Omake/jmg/files

then you need to use a different syntax. I just looked at the wiki and it's not very helpful, but this supports Glob syntax, so `**/jmg/*` is what is needed. 

This is because `jmg/*` tells Kavita to ignore it from the library root, while `**/jmg/*` says ignore as a folder any depth deep. 

I will update the wiki to explain this.

**Comment by ytoaa** [comment]
![image](https://github.com/Kareadita/Kavita/assets/24527825/432023fc-42d3-4229-9b82-a97860953614)
Is it still impossible in that nightly version?

**Comment by ytoaa** [comment]
> Okay if you have: library root: T Folder: T/T Omake/jmg/files
> 
> then you need to use a different syntax. I just looked at the wiki and it's not very helpful, but this supports Glob syntax, so `**/jmg/*` is what is needed.
> 
> This is because `jmg/*` tells Kavita to ignore it from the library root, while `**/jmg/*` says ignore as a folder any depth deep.
> 
> I will update the wiki to explain this.

![image](https://github.com/Kareadita/Kavita/assets/24527825/e2c36c7f-7ffd-4885-ba55-818de7872528)
umm.....

**Comment by majora2007** [comment]
@DieselTech can I get a spot check? I can't reproduce this on the nightly.

**Comment by ytoaa** [comment]
![1](https://github.com/Kareadita/Kavita/assets/24527825/452b15e5-c2e6-4534-9a45-12106c829c07)
![2](https://github.com/Kareadita/Kavita/assets/24527825/508fdd65-a8bf-463f-8355-daa6e0a04379)
![3](https://github.com/Kareadita/Kavita/assets/24527825/097188e8-e364-4ee5-9253-68a0948c969e)

**Comment by ytoaa** [comment]
This is another piece of information that has occurred as a result of some experiments.

![1](https://github.com/Kareadita/Kavita/assets/24527825/6c3e76a0-9565-433c-a0a4-32adb2f2a593)
![2](https://github.com/Kareadita/Kavita/assets/24527825/b2bd8803-bee5-4bec-a5b4-f8b53522749e)
![3](https://github.com/Kareadita/Kavita/assets/24527825/39ef9848-56e9-4447-8614-5e39d1dd4437)
![4](https://github.com/Kareadita/Kavita/assets/24527825/70eec55a-1ca9-4677-9c97-2e1e912bf271)

The method of excluding certain extensions also doesn't seem to work.

**Comment by ytoaa** [comment]
Also, this is not a problem with "nightly-0.8.1.5." This is a problem with the latest release, "nightly-0.8.1.6."


---------------------------------------------------------------------------------------------------------------------------------
API/Services/Tasks/Scanner/ParseScannedFiles.cs


![image](https://github.com/Kareadita/Kavita/assets/24527825/24cc4c47-5604-46d5-a896-01821f0433b1)
                        
                     
Fixed an issue by returning some of the changed codes back to the previous commit. The problem occurred in that area.

**Comment by ytoaa** [comment]
![image](https://github.com/Kareadita/Kavita/assets/24527825/c083a995-7fc9-40c9-9692-b8c0f1daf944)

After adding the "Match" argument, I was able to confirm that the "Exclusion from Pattern" function works normally.

**Comment by majora2007** [comment]
> ![image](https://private-user-images.githubusercontent.com/24527825/337585746-c083a995-7fc9-40c9-9692-b8c0f1daf944.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjIzMzgsIm5iZiI6MTcxNzc2MjAzOCwicGF0aCI6Ii8yNDUyNzgyNS8zMzc1ODU3NDYtYzA4M2E5OTUtN2ZjOS00MGM5LTk2OTItYjhjMGYxZGFmOTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEyMDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNDE4MDIyZWIzYzY2YWVlNTVjYWEzZDBiNGU3NDMxZWFhMDQwYWRhZWI4N2MwMDQzNmRlMzBlZmY5YjQyMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TxUP8rx2iIW0uCc8Yw79LwRaM2NxhVh3StIG2op4MPU)
> 
> After adding the "Match" argument, I was able to confirm that the "Exclusion from Pattern" function works normally.

Yes, I had found that when working this issue and have it locally. That code only is used for Scan Series. I thought you were doing scan library only.
