### ISSUE TITLE
Since 0.8x specials (like One-Shot, Special, Annual) are not sorted under the "Specials" tab anymore

### ISSUE THREAD

**Issue by Bartype** [Kareadita/Kavita#2986]
### What happened?

Since i updated from 0.7.14 to 0.8.1 almost all specials i have are sorted within the main series "Issues" tab, often showing up as multiple issues within one issue number, see picture.

![Screenshot 2024-06-07 134403](https://github.com/Kareadita/Kavita/assets/89315829/573584af-9d4e-4e51-be6e-fcd268d76993)

In this example, all Specials with issue number "1" are combined under Preacher-Cassidy. "Saint of killers" is a multiple issue special. The folder structure and naming is as the following screenshots:

![Comic-1](https://github.com/Kareadita/Kavita/assets/89315829/f0ca4924-8f98-472e-bac8-c46cf14f01a3)
![Comic-2](https://github.com/Kareadita/Kavita/assets/89315829/0db79da7-c948-4dd4-bb25-9686cbbedace)
![Comic-3](https://github.com/Kareadita/Kavita/assets/89315829/203a0636-c9d8-45d1-8eb4-ee9f0625cc1e)

When i was using 0.7.14 i tagged all my specials to let them sorted within the Specials tab like the following screenshot:

![Comic-4](https://github.com/Kareadita/Kavita/assets/89315829/8aaabddf-50b8-478d-994b-03d6e2e4964a)

With 0.7.14 these tags where enough to let it work, the filename didn't seem to matter.

### What did you expect?

Well, of course i expected the treating of specials would mostly staying the same after the update to 0.8.1. I did the update by downloading and activating the latest linuxserver container the way i always do. After that i did a full re-scan of all the libraries as was mentioned. Since this re-scan is completed i experience the current issue with the specials.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
Please include a full excerpt of the Comicinfo in one of your specials and the library type

**Comment by Bartype** [comment]
Hereby the comicinfo file from one of the specials. The library type is "Comic"

[ComicInfo.zip](https://github.com/user-attachments/files/15747397/ComicInfo.zip)

**Comment by majora2007** [comment]
This comicinfo doesn't have the Format tag to say it's a special, so it's relying on filename parsing. Special is one of the keywords, so let me take a look. It might just be the placement. `Preacher Special - NUMBER` looks like the Series is `Preacher Special` and the regex might be avoiding matching it as a special given it's location as sometimes series names end with Special or have Special within it. 

For future reference, using the `Format` tag is the advisable way to go, especially with Comics. 

I'll take a further look. 

Edit: The Format tag was set in the ComicInfo.

**Comment by majora2007** [comment]
Okay what I'm seeing is the the Issue number (because it's tagged) is overriding the special identification. 

I'm pretty sure this code is here in case a false positive occurs but the user has tagged something as an issue/chapter. I'll need to do some extended testing around this to see what's the best course of action for Kavita.

**Comment by Bartype** [comment]
Ok, that's true, it's not possible to tag with comictagger without issue number.
