### ISSUE TITLE
Continue leads to an incorrect chapter

### ISSUE THREAD

**Issue by tomerh2001** [Kareadita/Kavita#2990]
### What happened?

It's been like 5 times over the past month. I'm currently reading jujutsu kaisen, and I'm currently roughly in chapter 150, but I accidentally once opened chapter 100, and since then, when I press continue, it always opens chapter 100 back, and not where I actually am in the series. 

### What did you expect?

I expect continue to open the latest (highest number) chapter I'm reading, not the last I opened.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

I'm on the latest stable version, and am a Kavita+ subscriber.

**Comment by majora2007** [comment]
Does this chapter 100 show as fully read or has partial progress on it? Because if it's not fully read, then Kavita is opening the first chapter with progress not fully complete, which makes sense. 

If you've already read it, then mark it as complete.

**Comment by majora2007** [comment]
I'm going to close this until information is given.
