### ISSUE TITLE
[Bug] 400 Error: There was an issue saving progress

### ISSUE THREAD

**Issue by Vallevert** [Kareadita/Kavita#2999]
### What happened?

Doesn't depend on OS. Same issue on macOS, iOS...
Installed on TrueNAS Scale (= Kubernetes + Docker)

Every 4 pages I read, I got the same error:
"400 Error: There was an issue saving progress"

![Screenshot 2024-06-13 at 6 45 32 PM](https://github.com/Kareadita/Kavita/assets/25406430/1be6605f-d329-432f-90dd-bc70bdb27aa4)

I didn't have this issue before version 0.8

### What did you expect?

Fix the bug

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Mac

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Safari

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Safari

### Relevant log output

```shell
Nothing in log
```

**Comment by majora2007** [comment]
Are you on WAL already?

**Comment by Vallevert** [comment]
What is WAL ?

**Comment by majora2007** [comment]
https://wiki.kavitareader.com/troubleshooting/faq#q-im-seeing-database-is-locked-errors-in-my-logs

If you don't want to do this yourself, in the next stable version Kavita will turn WAL on by default.

**Comment by Vallevert** [comment]
"SQLite Error 5: 'database is locked"
I have this line in my logs.

I will wait the next version.
I don't want to brake my app.

**Comment by Vallevert** [comment]
I turned my db to WAL.
Error fixed
