### ISSUE TITLE
[Bug] wrong volume number

### ISSUE THREAD

**Issue by Vallevert** [Kareadita/Kavita#3000]
### What happened?

Doesn't depend on OS. Same issue on macOS, iOS...
Installed on TrueNAS Scale (= Kubernetes + Docker)

My library structure:
/Books/Author/AuthorName/SPXX_Comic_Name

UI Bug:
Wrong volume number
![Screenshot 2024-06-13 at 6 54 43 PM](https://github.com/Kareadita/Kavita/assets/25406430/a3e7bf51-8cc5-49cf-b4b0-0638085897a6)

Instead of "Volume 1"

### What did you expect?

Fix bug

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Mac

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Safari

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Safari

### Relevant log output

```shell
No log
```

**Comment by majora2007** [comment]
This is already fixed in the nightly and will come with v0.8.2.
