### ISSUE TITLE
[Bug] Reading list randomly disappears

### ISSUE THREAD

**Issue by Vallevert** [Kareadita/Kavita#3001]
### What happened?

Doesn't depend on OS. Same issue on macOS, iOS...
Installed on TrueNAS Scale (= Kubernetes + Docker)

I always create a reading list named "To delete", I fill it with some comics, and 3 days later, this reading list is gone.

### What did you expect?

Fix bug

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Mac

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Safari

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Safari

### Relevant log output

```shell
No log
```

### Additional Notes

Request: stop deleting a reading list when it is empty

**Comment by majora2007** [comment]
From the request, I'm seeing this is likely more of a feature request than a bug. Kavita does cleanup empty reading lists as empty reading lists don't add any value to the user. 

Please create a feature request via discussions for your request and provide information to help me understand the use case to this.

If however you are saying that Kavita is removing a non-empty reading list, please comment.

**Comment by DieselTech** [comment]
Also note that just saying "fix bug" is not helpful at all. We don't know if what you are encountering is a bug or intended behavior because you're not explaining with enough detail.

**Comment by Vallevert** [comment]
okay guys
I thought this was a bug, because empty reading list are importants to me.
I never believed this can be a feature.

I'm not sure, but I believe Kavita has already delete a non empty list. I will check this during next week because I'm not totally sure for now. I will contact you again if this is true.

**Comment by majora2007** [comment]
Feel free to open a feature request for ability to keep empty lists. It's not something I wouldn't think as important but it may open the idea to new ways of thinking about management or different features altogether.
