### ISSUE TITLE
[API] [OPDS] Extra layer on reading list

### ISSUE THREAD

**Issue by MnsieurJF** [Kareadita/Kavita#3002]
### What happened?

Hello, as discussed on the [Panels discord](https://discord.com/channels/1103436296153747522/1250839537089904690) I open this bug report here to track the issue.

I noticed something that bugs me about the reading list functionality of Kavita. I made a [video](https://github.com/Kareadita/Kavita/assets/165181180/fee25a53-a524-4bd5-ba2e-9037a6d6b521) to show the problem.

### What did you expect?

Have all issues of a reading list directly when you click on a reading list and remove the fake layer of 1 issue series

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

I tried to do a little digging and I understand why it did this 🕵️‍♂️
When you access the « Reading Lists » option through Kavita server browsing via Panels, the first OPDS call is made to get all reading lists (see [attachment 1](https://github.com/user-attachments/files/15827906/reading-list.txt)).

Then when you click on one, the id is used to perform a second call to retrieve all issues in the reading list (see [attachment 2](https://github.com/user-attachments/files/15827909/Readinglist32.txt)).

**Comment by majora2007** [comment]
As mentioned in the Panels discord, I can fix this up to reduce the Series navigation.

**Comment by majora2007** [comment]
I already mentioned in the Panels discord, but Kavita does produce the correct OPDS and there shouldn't be an extra layer of navigation to get to the chapter. I'll work with Panels team to get to the bottom of this. 

I did notice while in the code that the summary for the individual reading list item (chapter) is not coming through, so I'll update that to pass through.

**Comment by majora2007** [comment]
As noted also in the discord, I ended up finding a great enhancement to the OPDS Reading List feeds which solves your concern. 
When there is only one underlying file (common), send an acquisition link rather than a subsection. This allows the removal of one of the clicks for nearly all users.
