### ISSUE TITLE
Komf Refusing To Connect?

### ISSUE THREAD

**Issue by ThoughtzThruKeyz** [Kareadita/Kavita#3009]
### What happened?

So, I've been trying to connect Komf to my Kavita for like two weeks or so at this point lol, I've pretty much exhausted myself which led me here. I tried getting help within the discord, but, with all due respect to the mod who offered help, it wasn't of much use. I don't know if it was due to the misinterpretation of the issue or what-have-you, but my issue was not resolved. I tried reaching out to other fellow members I knew as well, but none really have/had my setup so I was able to get help there either. Enough exposition though, here's the issue:

As the title suggests, Komf, for me, is not working in conjunction with Kavita. Which I thought would be much easier than when I set it up on _redacted_ due to Komf being developed in conjunction with the Kavita team. So, for some reason every time I try to connect komf, I'm getting a network error. Though that exact same port, ip, etc. Works and is connected perfectly fine on _redacted_ so that's my biggest hiccup. I've tried altering my domain in the user script, changing port numbers, altering the config, restarting komf and more...Essentially the whole nine yards; nothing has worked. 

### What did you expect?

I expected it to just connect similar to how I did the other app Komf supports. I followed Kavita's setup guide and again, for some reason, even though I thought it to be easier, it's been much harder to troubleshoot this issue.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by DieselTech** [comment]
Honestly this sounds like more of a ticket for komf than kavita. We have guide with the basic instructions needed for connecting the two [on our wiki](https://wiki.kavitareader.com/guides/external-tools/komf)

I suspect your running into the issues of having the services behind domains / https. You can check out the issues on komfs side that deal with that: https://github.com/Snd-R/komf/issues/58

**Comment by ThoughtzThruKeyz** [comment]
Sorry for the ignorance, but I'm afraid I don't know what Traefik is, nor am I even aware if I have access to it. I'll try and make a ticket in Komf, and see what's up. Thanks again.
