### ISSUE TITLE
Similarly named folders for different volumes & series - Only shows 1

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [Kareadita/Kavita#3014]
### What happened?

Hi,
So I have two folders - 
1. Wonder Woman (1942)
2. Wonder Woman (1987)

Kavita during a scan picks up only 1 series and then during a rescan it picks up the other but replaces the original series. All the volume and issue metadata is mapped properly according to comicInfo. But I suspect the uniqueness is done on the basis of series name instead of folder name.

### What did you expect?

Both series picked up and as separate series together.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-06-22 21:05:08.790 +01:00  285] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 329 files for /comics/Wonder Woman (1942)
[Kavita] [2024-06-22 21:05:09.378 +01:00  285] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 228 files for /comics/Wonder Woman (1987)
API.Services.Tasks.Scanner.ProcessSeries Updating Wonder Woman FolderPath to /comics/Wonder Woman (1942)
[Kavita] [2024-06-22 21:05:10.596 +01:00  285] [Debug] API.Services.Tasks.Scanner.ProcessSeries Updating Wonder Woman LowestFolderPath to /Wonder Woman (1942)
[Kavita] [2024-06-22 21:05:22.083 +01:00  285] [Debug] API.Services.Tasks.Scanner.ProcessSeries Updating Wonder Woman FolderPath to /comics/Wonder Woman (1987)
[Kavita] [2024-06-22 21:05:22.083 +01:00  285] [Debug] API.Services.Tasks.Scanner.ProcessSeries Updating Wonder Woman LowestFolderPath to /Wonder Woman (1987)
```

**Comment by majora2007** [comment]
This type of layout is solved by using the comic vine library type. This should meet your expectations.

**Comment by Gandalf-the-Blue** [comment]
That solved it. Thank you!
