### ISSUE TITLE
Cover generation is not working on newest nightly build.

### ISSUE THREAD

**Issue by TheDarkMage** [Kareadita/Kavita#3019]
### What happened?

When I add a new chapter or refresh covers for a series no cover is generated and an error is shown under media issues. The comment is "This archive cannot be read or not supported" and the details say "This operation is not supported". 

I'm able to read the chapter just fine and downgrading back to 0.8.1.12 fixes the problem. I've tried generating the cover as PNG, WebP, and Avif at both normal and medium resolutions, but it always throws the same error. I've also double checked file permissions and everything is rw-rw-rw-.

### What did you expect?

When I add a new chapter or refresh covers for it to generate the cover.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-06-25 19:17:14.623 -04:00  89] [Debug] API.Services.MetadataService [MetadataService] Generating cover image for /manga/Now I'm a Demon Lord! Happily Ever After with Monster Girls in My Dungeon/Now I'm a Demon Lord! Happily Ever After with Monster Girls in My Dungeon v10 c065.cbz
[Kavita] [2024-06-25 19:17:14.624 -04:00  89] [Warning] API.Services.ArchiveService [GetCoverImage] There was an exception when reading archive stream: /manga/Now I'm a Demon Lord! Happily Ever After with Monster Girls in My Dungeon/Now I'm a Demon Lord! Happily Ever After with Monster Girls in My Dungeon v10 c065.cbz. Defaulting to no cover image
System.NotSupportedException: This operation is not supported.
   at System.IO.Compression.DeflateStream.set_Position(Int64 value)
   at API.Services.ImageService.WriteCoverThumbnail(Stream stream, String fileName, String outputDirectory, EncodeFormat encodeFormat, CoverImageSize size) in /home/runner/work/Kavita/Kavita/API/Services/ImageService.cs:line 223
   at API.Services.ArchiveService.GetCoverImage(String archivePath, String fileName, String outputDirectory, EncodeFormat format, CoverImageSize size) in /home/runner/work/Kavita/Kavita/API/Services/ArchiveService.cs:line 235
```

### Additional Notes

Running on unraid.

**Comment by DieselTech** [comment]
Yup, we are aware of this in the nightly branch. While opening tickets for it on github does help, using the [Discord #Nightly-testing](https://discord.gg/kavita-821879810934439936) channel is best for this. That way we can talk in real time and troubleshoot problems with nighty builds faster.

**Comment by TheDarkMage** [comment]
Gotcha, I'll do that in the future.
