### ISSUE TITLE
No matter what I do, I can't seem to get the scan to recognize books

### ISSUE THREAD

**Issue by sosukeinu** [Kareadita/Kavita#3036]
### What happened?

I've been trying over the past few weeks to get Kavita  working on my home network. Every time I start it up, I try force scanning, but nothing shows up. I've even set up two very minimal folders just to try and get it figured out.

```bash
.
└── J.R.R. Tolkien
    └── Middle Earth
        ├── Beowulf_ A Translation and Commentary - J.R.R. Tolkien.epub
        ├── Letters From Father Christmas - J. R. R. Tolkien.epub
        ├── Poems - J.R.R. Tolkien.pdf
        ├── The Adventures of Tom Bombadil - J. R. R. Tolkien.epub
        ├── The Book of Lost Tales _ Part One - J.R.R. Tolkien.epub
        ├── The Book of Lost Tales _ Part Two - J.R.R. Tolkien.epub
        ├── The Children of Hurin - J.R.R. Tolkien.epub
        ├── The Fall of Arthur - J.R.R. Tolkien.epub
        ├── The Hobbit - J.R.R. Tolkien.epub
        ├── The Legend of Sigurd and Gudrun - J.R.R. Tolkien.epub
        ├── The Letters of J.R.R. Tolkien - J.R.R. Tolkien.epub
        ├── The Lord of the Rings - J.R.R. Tolkien.epub
        ├── The Silmarillion - J.R.R. Tolkien.epub
        ├── Unfinished Tales - J. R. R. Tolkien.epub
        └── Unfinished Tales of Numenor and Middle-ear - J.R.R. Tolkien.epub
```
and

```bash
.
└── Fafhrd and the Gray Mouser
    ├── Ill Met In Lankhmar - Howard Chaykin.cbr
    ├── Lean Times in Lankhmar; When The Sea King' - Howard Chaykin.cbr
    └── The Price of Pain Ease; Bazaar of the Biza - Howard Chaykin.cbz
```

The only reason I have that extra level in J.R.R. Tolkien, is just incase I didn't have the requisite nesting correct.

### What did you expect?

The scan to find the files and add them to the library.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-07-03 00:00:09.269 +00:00  7] [Information] API.Services.Tasks.CleanupService Performing cleanup of Series that are Completed and have been fully read that are in Want To Read list
[Kavita] [2024-07-03 00:00:09.272 +00:00  53] [Information] API.Services.Tasks.CleanupService Starting Cleanup
[Kavita] [2024-07-03 00:00:09.280 +00:00  53] [Information] API.Services.Tasks.CleanupService Cleaning temp directory
[Kavita] [2024-07-03 00:00:09.281 +00:00  53] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache & Temp directories
[Kavita] [2024-07-03 00:00:09.281 +00:00  53] [Information] API.Services.Tasks.CleanupService Cache and temp directory purged
[Kavita] [2024-07-03 00:00:09.281 +00:00  53] [Information] API.Services.Tasks.CleanupService Cleaning old database backups
[Kavita] [2024-07-03 00:00:09.285 +00:00  53] [Information] API.Services.Tasks.CleanupService Beginning cleanup of Database backups at "2024-07-03T00:00:09.2851204+00:00"
[Kavita] [2024-07-03 00:00:09.285 +00:00  53] [Information] API.Services.Tasks.CleanupService Finished cleanup of Database backups at "2024-07-03T00:00:09.2857505+00:00"
[Kavita] [2024-07-03 00:00:09.285 +00:00  53] [Information] API.Services.Tasks.CleanupService Cleaning deleted cover images
[Kavita] [2024-07-03 00:00:09.287 +00:00  53] [Information] API.Services.Tasks.CleanupService Performing cleanup of logs directory
[Kavita] [2024-07-03 00:00:09.287 +00:00  53] [Information] API.Services.Tasks.CleanupService Finished cleanup of logs at "2024-07-03T00:00:09.2874442+00:00"
[Kavita] [2024-07-03 00:00:09.287 +00:00  53] [Information] API.Services.Tasks.CleanupService Cleaning up any progress rows that exceed chapter page count
[Kavita] [2024-07-03 00:00:09.287 +00:00  53] [Information] API.Services.Tasks.CleanupService Cleaning up any progress rows that exceed chapter page count - complete
[Kavita] [2024-07-03 00:00:09.288 +00:00  53] [Information] API.Services.Tasks.CleanupService Cleanup finished
[Kavita] [2024-07-03 00:00:09.289 +00:00  7] [Information] API.Services.Tasks.CleanupService Performing cleanup of Series that are Completed and have been fully read that are in Want To Read list, completed
[Kavita] [2024-07-03 01:20:39.408 +00:00  31] [Information] API.Services.TaskScheduler A Scan is already running, rescheduling ScanLibrary in 3 hours
[Kavita] [2024-07-03 02:00:09.471 +00:00  324] [Information] API.Services.Tasks.BackupService Beginning backup of Database at "2024-07-03T02:00:09.4712260+00:00"
[Kavita] [2024-07-03 02:00:09.475 +00:00  324] [Debug] API.Services.Tasks.BackupService Backing up to /kavita/config/backups
[Kavita] [2024-07-03 02:00:09.502 +00:00  324] [Information] API.Services.Tasks.BackupService Database backup completed
[Kavita] [2024-07-03 04:20:39.716 +00:00  31] [Information] API.Services.TaskScheduler A Scan is already running, rescheduling ScanLibrary in 3 hours
[Kavita] [2024-07-03 07:20:40.025 +00:00  31] [Information] API.Services.TaskScheduler A Scan is already running, rescheduling ScanLibrary in 3 hours
[Kavita] [2024-07-03 10:20:40.332 +00:00  31] [Information] API.Services.TaskScheduler A Scan is already running, rescheduling ScanLibrary in 3 hours
[Kavita] [2024-07-03 13:20:40.648 +00:00  31] [Information] API.Services.TaskScheduler A Scan is already running, rescheduling ScanLibrary in 3 hours
[Kavita] [2024-07-03 16:20:40.971 +00:00  31] [Information] API.Services.TaskScheduler A Scan is already running, rescheduling ScanLibrary in 3 hours
[Kavita] [2024-07-03 19:20:41.282 +00:00  31] [Information] API.Services.TaskScheduler A Scan is already running, rescheduling ScanLibrary in 3 hours
[Kavita] [2024-07-03 22:20:41.589 +00:00  31] [Information] API.Services.TaskScheduler A Scan is already running, rescheduling ScanLibrary in 3 hours
```

**Comment by scare376** [comment]
Can you reboot the container, start another scan, and then give the log output. Looks like it might have gotten stuck during a scan

**Comment by sosukeinu** [comment]
I restarted the server, and it does, indeed seem to find the files. However,  they are never added to the library.

LOGS:
[kavita20240705.log](https://github.com/user-attachments/files/16113304/kavita20240705.log)

**Comment by scare376** [comment]
odd. looks like its getting stuck on that folder. can you try pulling the books out, restarting kavita, and running the scan again?

**Comment by pedroponte** [comment]
Can't seem to have this working properly.

Also had a problem when scanning the first library.

I have recreated the server and it worked with the first library/folder. 

Now, having added new library and folder mounted on

/mnt/pdf/xyz

it can't find any files on the second one.

Are there any logs I can share to allow troubleshooting?
Could this be about file/ownership permissions?

The pdf files are hosted on the host server.
The server is running on a docker engine.
The pdf files are mapped into the /mnt/pdf folder.

TIA

[Kavita] [2024-07-16 15:14:27.694 +00:00  75] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on myfiles

[Kavita] [2024-07-16 15:14:27.694 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library myfiles Step 1: Scan Files

[Kavita] [2024-07-16 15:14:27.694 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library myfiles Step 1.A: Process 1 folders

[Kavita] [2024-07-16 15:14:27.695 +00:00  75] [Debug] API.Services.Tasks.ScannerService 	[ScannerService] Library myfiles Step 1.B: Scan files in /mnt/pdf/myfiles

[Kavita] [2024-07-16 15:14:27.695 +00:00  75] [Debug] API.Services.Tasks.ScannerService 	[ScannerService] Library myfiles Step 1.C: Process files in /mnt/pdf/myfiles

[Kavita] [2024-07-16 15:14:27.695 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library myfiles Step 2: Track Found Series

[Kavita] [2024-07-16 15:14:27.695 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library myfiles Step 3: Process Parsed Series

[Kavita] [2024-07-16 15:14:27.695 +00:00  75] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished file scan in 0 milliseconds. Updating database

[Kavita] [2024-07-16 15:14:27.695 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library myfiles Step 4: Save Library

[Kavita] [2024-07-16 15:14:27.711 +00:00  75] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished library scan of 0 series in 18 milliseconds for myfiles. There were no changes

[Kavita] [2024-07-16 15:14:27.711 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library myfiles Step 5: Remove Deleted Series

[Kavita] [2024-07-16 15:14:27.711 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan

[Kavita] [2024-07-16 15:14:27.711 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 0 series that needs to be removed: []

[Kavita] [2024-07-16 15:14:27.711 +00:00  75] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan - complete

[Kavita] [2024-07-16 15:14:27.713 +00:00  37] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache directories

[Kavita] [2024-07-16 15:14:27.713 +00:00  37] [Information] API.Services.Tasks.CleanupService Cache directory purged

[Kavita] [2024-07-16 15:14:29.635 +00:00  77] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 1.0041 ms

[Kavita] [2024-07-16 15:14:29.636 +00:00  76] [Information] API.Controllers.AccountController confirm-email failed from invalid registered email: redacted@gmail.com

[Kavita] [2024-07-16 15:14:29.636 +00:00  76] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/account/confirm-email-update responded 400 in 0.7940 ms

[Kavita] [2024-07-16 15:14:29.691 +00:00  76] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 0.4332 ms

[Kavita] [2024-07-16 15:14:29.740 +00:00  76] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 0.3881 ms

[Kavita] [2024-07-16 15:14:47.659 +00:00  77] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 0.8325 ms

[Kavita] [2024-07-16 15:14:47.711 +00:00  73] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 0.6615 ms

[Kavita] [2024-07-16 15:14:47.768 +00:00  73] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 0.6120 ms

**Comment by majora2007** [comment]
There were some bugs in how Kavita saw some folders and if they were dirty or not. In v0.8.4, I rewrote the scanner. This will likely fix your issue. Since this was reported in v0.8.1, please either re-test on the latest (v0.8.3) or wait till v0.8.4 and if the issue persists, reopen this ticket.

**Comment by wsdookadr** [comment]
This persists. The scanner just doesn't see certain pdf files.
This happens at least on the following docker images:

```
ghcr.io/kareadita/kavita:canary-0.8.4.7
linuxserver/kavita:v0.8.4.2-ls60
jvmilazz0/kavita:nightly-0.8.4.6
ghcr.io/kareadita/kavita:0.7.8.2
```
