### ISSUE TITLE
Kavita including chapter names in manga titles

### ISSUE THREAD

**Issue by lyingloverr** [Kareadita/Kavita#3053]
### What happened?

Kavita will include unique chapter names in the titles of the manga.

Examples:

`Sakamoto Days - Days 001.cbz`
`My Hero Academia - No. 001.cbz`
`Blue Period - Stroke 001.cbz`

### What did you expect?

Kavita to not include the chapter name in the title. 

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox, Chrome, Safari

**Comment by majora2007** [comment]
As replied in discord, this type of pattern is not possible to distinguish from a series. You should have your files named `Series - c001 - title`. Having title after the number helps a lot more and using a chapter marker helps to separate the title from the other text.
