### ISSUE TITLE
Qnap TVS-872XT 

### ISSUE THREAD

**Issue by Gretarsson67** [Kareadita/Kavita#3059]
### What happened?

I have tried to install your program from MyQnap and even tied manually but dont work, most of program from NyQnap have same issus
![qn](https://github.com/user-attachments/assets/b799b8ea-eebc-4051-b02a-807c589ed582)

### What did you expect?

I can  not install it so

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
Error	2024-07-17	10:10:37	Jon	192.168.50.224	Web Desktop	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (K	App Center	App Installation	[App Center] Failed to install Kavita.NET (Apache81) 0.8.2.0.0. The installation package is incompatible. Use the compatible package.
```

### Additional Notes

Model:TVS-872XT
Current firmware version:QTS 5.1.7.2770

**Comment by DieselTech** [comment]
We don't maintain or publish the packages on the qnap store. That said, it looks like you might be trying to install the wrong version based on the logs provided. Maybe another qnap user can chime in here to help out.

**Comment by majora2007** [comment]
Only thing I know about QNap is this forum post and a few versions ago, they had some incompatibility with the SQL version that ships with .NET. 

As Diesel mentioned, Kavita doesn't maintain any packages for QNap, so you are probably best reaching out to the publisher of the app on the QNap store and seeing if there is anything he can do (or he  can contact me to see if there is anything I can do).

https://www.forum-nas.fr/threads/kavita-net-a-fast-feature-rich-cross-platform-reading-server.16507/

**Comment by OneCDOnly** [comment]
@Gretarsson67, you're attempting to install the wrong QPKG arch (arm64) for your NAS (amd64). 

There's an X86 QPKG arch available on myQNAP.org, suggest you try that one instead.
