### ISSUE TITLE
Forcing something comics out of special

### ISSUE THREAD

**Issue by bojtalepenye** [Kareadita/Kavita#3066]
### What happened?

I have a 3 part comic series I want to put in kavita, and 2 files are perfectly in place, however one of the comic (cbz) files gets recognized as a special of the second comic. Is it possible to somehow tell Kavita that a comic it's seeing should be put as a standalone comic, not a special feature? (I can't do anything with the metadata)

### What did you expect?

Correct way of recognizing comics. I didn't expect it to put it in as a special

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

Kavita is running on a Raspberrypi 400. (arm64)

**Comment by majora2007** [comment]
Please provide the filename of the special. It's likely a false positive. I have an open ticket to remove special filename parsing due to cases like this, feel free to comment on it your opinion.

**Comment by bojtalepenye** [comment]
Okay, so there are three comics. These are the files' names:
"The Art of How to Train Your Dragon.cbz"
"The Art of How to Train Your Dragon 2.cbz"
"The Art of How to Train Your Dragon The Hidden World.cbz"

Now, in kavita, the "The Art of How to Train Your Dragon 2.cbz" file is detected as "The Art of How to Train Your Dragon". The first one. That shouldn't be.
![image](https://github.com/user-attachments/assets/1973f13a-6059-4785-a8a9-5332806384bf)
And the actual first comic, of the first film, gets put into the specials:
![image](https://github.com/user-attachments/assets/9f59d887-6070-4678-be5b-a60ca6edde42)
I want kavita to detect the first comic like it did with the other two: Separately:
![image](https://github.com/user-attachments/assets/a1d68d6e-476f-458f-b532-d9939bd9b68e)

Thank you. If you need any more info, or logs, I will provide that

**Comment by majora2007** [comment]
Are these all in a folder called how to train your dragon? Specials usually look up to the folder name to fallback for series name parsing as people usually name it just the title.

**Comment by bojtalepenye** [comment]
Yes they are:
pi@raspberrypi:/media/HDD/myComics $ ls
'How To Train Your Dragon'
pi@raspberrypi:/media/HDD/myComics $ tree
.
└── How To Train Your Dragon
    ├── Dragons Defenders of Berk
    │   ├── Dragons Defenders of Berk Snowmageddon.cbz
    │   └── Dragons Defenders of Berk The Endless Night.cbz
    ├── Dragons Riders of Berk
    │   ├── Dragons Riders of Berk Dangers of the Deep.cbz
    │   ├── Dragons Riders of Berk Dragon Down.cbz
    │   ├── Dragons Riders of Berk The Ice Castle.cbz
    │   ├── Dragons Riders of Berk The Legend of Ragnarok.cbz
    │   ├── Dragons Riders of Berk The Stawaway.cbz
    │   └── Dragons Riders of Berk Underworld.cbz
    ├── How to Train Your Dragon Dragonvine.cbz
    ├── How To Train Your Dragon The Serpent's Heir.cbz
    ├── Night fury anatomy and dissection.cbz
    ├── The Art of How to Train Your Dragon 2.cbz
    ├── The Art of How to Train Your Dragon.cbz
    └── The Art of How to Train Your Dragon The Hidden World.cbz

3 directories, 14 files
pi@raspberrypi:/media/HDD/myComics $

**Comment by bojtalepenye** [comment]
So how will I be able to tell Kavita to not put it in as a special? By changing the file's name? Or the directory's? Or the structure of the directory?

**Comment by DieselTech** [comment]
Related issue for special keyword removal: https://github.com/Kareadita/Kavita/issues/2967

**Comment by majora2007** [comment]
Special recognition from filename has been removed in the nightly, in v0.8.4 (unless you want to try the nightly on a new instance), should solve this issue for you.

**Comment by majora2007** [comment]
Kavita v0.8.4 is released and should fix this issue by removing filename parsing for Specials. Please validate.
