### ISSUE TITLE
[Kavita+] Current MAL-Interest Stack import feature is limited to just 10 entries.

### ISSUE THREAD

**Issue by Paraxes** [Kareadita/Kavita#3069]
### What happened?

As discussed in Discord, here my original comment:

"Hello, is there any way to specify what stacks Kavita should pull for the "MAL Interest Stack" list from the Myanmelist-Website itself? I have roughly 200+ collections on MAL but can only see (and track) 10 that seem to be chosen randomly. I assume that's a very intentional limitation but are there plans to up the limit or at least be able to choose what stacks it should pull from the MAL-Website? Because otherwise this great feature has limited use currently for people with more than 10 interest stacks."

Your answer: "Wow, that's a lot. Throw a quick issue up for me and I'll buff it for you. I had kept it simple (I don't recall putting a limit tho) because there is no API so I had to scrape and thus wasn't sure how performant it would be."

### What did you expect?

That I can pick and choose my interest stacks from MAL freely. Currently, they are limited to 10 and are picked at random and also never change, so it's always the same 10 stacks.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

**Comment by majora2007** [comment]
This was totally an oversight by me to not handle pagination. This will be released at the latest with v0.8.3 release (but ideally earlier)

**Comment by majora2007** [comment]
This has been deployed to Kavita+. Thanks again for the bug report.
