### ISSUE TITLE
[Enhancement] Caching is too aggressive at keeping translation strings

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#3101]
### What happened?

This is for tracking talk and progress on working on a different caching system. Too many people over time report issues with having translation strings showing up in the UI.

### What did you expect?

Strings not showing up to users.

**Comment by majora2007** [comment]
As discussed with Diesel, I likely need to build my own system since the one provided out of the box doesn't work well.

**Comment by majora2007** [comment]
I updated the code and made it so when a new Kavita version is released, strings are automatically reloaded. This should solve the issue.
