### ISSUE TITLE
UX Bugs

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#3102]
Some bugs found during release testing:

- [x] Bad strings
- [x] Setting value disappearing after interaction
- [x] Sliders need a value display during edit mode
- [x] Generate colorscape needed on series detail
- [x] Darken the card text background
- [x] Library adv settings needs new design
- [x] Double check resetting or changing cover regenerates the color scheme
- [x] Recommended on list view is broken
- [x] Save Preferences API call is taking up to 4 seconds
- [x] Preview recommendation (external) drawer isn't rendering correctly
- [ ] Double check Last Active on manage users (for a never online user)
- [x] Increase local and external review character count to 149.
- [x] Fix sliders on preference screen not showing percentage
- [x] Volume edit modal on series detail not hooked up
- [x] Tab routes (i.e. #details/#volumes/etc) on details cards need to be hooked up
- [x] All tabs need to be in a carousel component
- [x] Fix series detail progress bar
- [x] Series preview drawer read more does not work properly
- [x] SourceProvider (review card) icons need to be higher res
- [x] Upload volume cover is overriding chapter cover
- [x] PDF/Epub readers have some weird cropping
- [x] Series detail add to collection broken
- [x] Side nav items will show highlight if 2 smart filters are bound
- [ ] After saving AniList token, the scrobbling section should close
- [x] Epub reader isn't resuming progress
- [x] We need format on the series card overlay
- [x] Entity-title component needs an overhaul to work more reliably (or a new one for the way I want in detail pages) (http://localhost:4200/library/5/series/2889/chapter/58581)
- [x] Volume detail tab needs chapter cards to have actionables
- [x] Preview external series drawer is now broken for people card
- [x] Add Release Date to the Volume/Chapter details page
- [x] Breakpoint margin top issue (Robbie)
- [x] All pages are now cutoff due to changes on container width (open side nav on desktop to see) (Robbie)
- [x] Series/Volume/Chapter detail pages NEED format tag
- [x] Settings items input extend past the Edit/Close button
- [x] The progress bar under volume/chapter cover images isn't matching the series thickness/design
- [x] The read hover button is missing from volume/chapter cover images
- [x] Edit Series tags doesn't work
- [x] Age Rating is not clickable to load a filtered view
- [ ] Base url is getting stripped on loading series detail
- [x] Webtoon reader is currently broken (next chapter overlay is non-dismissable)
- [x] Scrollbar on epub reader is still currently missing (might need to make a setting for this)
- [x] Downloads from series menu on the library page does not do anything
- [x] Click to continue reading overlay is not quite centered, on series image in series page, sometimes (vertically) (Cover Image component)
- [ ] Maybe make "continue" message under cover on series page clickable. And possibly either the whole series cover at the top of that page clickable, or remove the hand icon indicating it's interactive, since clicking it (outside the continue reading icon) does nothing
- [x] wrap long lists of tags / genres instead of putting in carousel (use tag expander)
- [x] Last line of any tab is hard to read with opacity blur
- [x] Bust locale cache needs toastr and to automatically refresh the page so it works.
- [x] Komf Dev needs to know about changes to structure or finally use the id to inject content into. 
- [x] Donate button is not aligned correctly
![image](https://github.com/user-attachments/assets/49960172-0bb0-4c1e-aad7-df450c67e279)
- [x] Book library types is using Chapter instead of Book "Continue Ch 2"
- [x] Bulk actionables is cutoff
![image](https://github.com/user-attachments/assets/2f4dceb6-b5f1-4a03-96af-35c0c41ba08d)
- [x] Triple Scrollbar
- [x] Jump Bar hover effect broken on FF
![image](https://github.com/user-attachments/assets/1b815eac-6fd7-45a2-b9e4-30e7a4dd3ba5)
- [x] Settings page doesn't scale the whole width for Fire 10 HD Tablet
- [x] MAL Import Stack isn't showing for some users. https://discord.com/channels/821879810934439936/851515194185744464/1277447772022374443
- [x] Allow horizontal scroll on settings page. https://discord.com/channels/821879810934439936/851515194185744464/1277582383935393963
- [x] Background image not filling up background on details pages
- [x] Pref side nav clips the media issue count when scrollbar visible
![image](https://github.com/user-attachments/assets/7be0bee0-0c4d-44f6-9ca2-31c8e963682a)
- [x] Manga reader has scaling/cutoff issue
- [x] PDF reader has scaling/cutoff issue
- [x] Can't scroll horizontally on tables
- [x] Loading Reading list page is having a long change detection cycle causing jump bar to render out slowly. 
- [x] Clicking on a router item on the mobile side nav isn't closing the menu automatically (regression)
- [ ] Collection detail page (and likely reading list detail) need the top area to scroll up, like the series detail page does
- [x] Side nav item on mobile isn't overflowing correct 
- [x] Missing main container: Reading lists, reading list detail, collection detail, bookmarks, want to read, all series, smart filters, announcements,
- [ ] Side nav item needs a tooltip on overflow
- [x] Continue title with specials is not ideal. It should just say "Continue from Special" instead of the title as it almost always overflows
- [x] When clicking directly on read from all series/library detail, going back doesn't bring us back to the card we clicked on.
- [x] On mobile clicking on and more doesn't focus on the details card, needs to scroll to it.
- [ ] If selecting the same route over again, side nav should collapse
- [ ] Nested menu for actionables isn't showing the hover css
![image](https://github.com/user-attachments/assets/e0da143f-8844-4b63-aeb6-4670721d11c0)
- [x] Scalling options disappears after edit
- [x] Locale is disabled and not able to be switched
- [x] After clicking into a volume/chapter detail, the page should scroll to top
- [x] Collection detail when there is 20+ series, has multiple scrollbars (css needs looking at)
- [x] Collection detail series count needs to be fixed
- [x] Event Widget needs css work
- [x] Edit Chapter Modal has details leaking to non-admin users
- [x] Actionables button on series detail isn't aligned
![image](https://github.com/user-attachments/assets/238141bf-0fee-4c5d-9e67-0f773caf0216)

- [ ] 

Small things to update: 
- [x] Review tooltip should be a modal. Tooltip is hard to interact with on mobile. 
- [x] Remove all the dead components 
- [x] Tidy up the localizations and ping translation team

Deleted Components:
- [x] List Items (all)
- [x] Card detail Drawer
- [x] chapter-metadata-detail
- [x] series-info-cards
- [x] external-list-item
- [x] entity-info-cards

**Comment by ivanjx** [comment]
possible to add: when trying to continue reading (eg. from page 50) using reading mode scrolling it tries to load all the previous images making ux so bad because it keeps jumping. also seemingly making it crash on ios.

**Comment by majora2007** [comment]
> possible to add: when trying to continue reading (eg. from page 50) using reading mode scrolling it tries to load all the previous images making ux so bad because it keeps jumping. also seemingly making it crash on ios.

This is outside the scope of what this issue is tracking. Please create a separate issue so we can properly track.
