### ISSUE TITLE
Permission denied exception when kavita try to update base url in `wwwroot/index.html` on docker is not suppressed

### ISSUE THREAD

**Issue by FirelightFlagboy** [Kareadita/Kavita#3116]
### What happened?

On startup I see an `UnauthorizedAccessException` exception when kavita try to update the baseUrl in the `/kavita/wwwroot/index.html` on docker.

> The docker container is not run with root permission

### What did you expect?

I expect the exception to be supressed

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-08-17 10:01:44.997 +02:00  1] [Error]  There was an error setting base url
System.UnauthorizedAccessException: Access to the path '/kavita/wwwroot/index.html' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at HtmlAgilityPack.HtmlDocument.Save(String filename)
   at API.Startup.UpdateBaseUrlInIndex(String baseUrl) in /home/runner/work/Kavita/Kavita/API/Startup.cs:line 445
[Kavita] [2024-08-17 10:01:45.572 +02:00  1] [Information] API.Program Starting with base url as /
```

### Additional Notes

The docker image I'm using is [jvmilazz0/kavita](https://hub.docker.com/r/jvmilazz0/kavita) with the tag `0.8.2`.

I've taken a look at the method `UpdateBaseUrlInIndex` to see why the exception is raised and I've found this block that tries to suppress the _permission denied_ exception on certain condition:

https://github.com/Kareadita/Kavita/blob/c850f49cd4429a1d2fc470e0be45a9b44a72f0ef/API/Startup.cs#L451-L457

But I don't understand why this condition do not work:

- The exception contains `UnauthorizedAccessException`.
- The value of `baseUrl` is `/` (cf the log line `Starting with base url as /`)

  The variable `basePath` is used to call `UpdateBaseInIndex`

  https://github.com/Kareadita/Kavita/blob/c850f49cd4429a1d2fc470e0be45a9b44a72f0ef/API/Startup.cs#L318
  
  And is used for the log `Starting with ...`

  https://github.com/Kareadita/Kavita/blob/c850f49cd4429a1d2fc470e0be45a9b44a72f0ef/API/Startup.cs#L434

- The docker image I'm using set to variable `DOTNET_RUNNING_IN_CONTAINER=true` that is used to determine the value of `OsInfo.IsDocker`.
 
  https://github.com/Kareadita/Kavita/blob/c850f49cd4429a1d2fc470e0be45a9b44a72f0ef/Kavita.Common/EnvironmentInfo/IOsInfo.cs#L13-L15

**Comment by majora2007** [comment]
Changing base url is not supported on docker running as non-root, for that, you can use the LSIO image instead.

**Comment by FirelightFlagboy** [comment]
> Changing base url is not supported on docker running as non-root, for that, you can use the LSIO image instead.

To be more specific, I'm not trying to change the base url. I'm using the default one (cf: `Starting with base url as /`) 

https://github.com/Kareadita/Kavita/blob/c850f49cd4429a1d2fc470e0be45a9b44a72f0ef/Kavita.Common/Configuration.cs#L13

I discovered that the exception can be suppressed on certain conditions but I don't know why those conditions aren't fulfilled on my setup which seems to check all the boxes

**Comment by NickSica** [comment]
I'm getting the same issue, no base url set but an error setting the base url. It seems like it may not matter though in the end and the error can be ignored?

**Comment by FirelightFlagboy** [comment]
Yes, the error can be safely ignored since you use the default base URL (`/`) as the provided `index.html` use that base url as default.
