### ISSUE TITLE
Saving the layout mode doesn't save unless I go to user preference to save it

### ISSUE THREAD

**Issue by Stevonthy** [Kareadita/Kavita#3122]
### What happened?

I tried to save the layout mode to manga (double) 

### What did you expect?

but it didn't save after refreshing the tab 
The funny thing is that **only** single page saves all the others don't I have to go to user preferences to save those two

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

I'm using version 0.8.2.0 and I'm using Portainer

**Comment by majora2007** [comment]
Looks like another property (Page split) isn't being sent to the backend so the whole request fails. I'll get this fixed up.

**Comment by majora2007** [comment]
Forgot to include this in the nightly changelog, but this is fixed and will be in the upcoming stable (v0.8.3).
