### ISSUE TITLE
[Wiki] Add URL to Installation and explain in README.md how it works

### ISSUE THREAD

**Issue by superbonaci** [Kareadita/Kavita#3124]
### What happened?

https://wiki.kavitareader.com/installation/native

Add at the end that the program is accessed by a web browser, using the default URL http://127.0.0.1:5000

Also the `README.md` does not make clear that this programs works by providing a local web service, and using a web browser to connect to it. It's not program with native user interface.

### What did you expect?

Understand how the program works.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
I feel like the readme, while not explicit, has tons of information to help a user understand that. 

1. We provide a demo pointing to a live instance indicating it's not a native program.
2. We never metion anything native
3. We link to our wiki for setup where it's clear that it's webserver based.

**Comment by DieselTech** [comment]
This has been changed on the wiki, but for future reference if there is problem with the wiki please open tickets on the github page for the project. Also, If there is enhancements that can be made you can open a feature request on the wiki github with your changes directly.
