### ISSUE TITLE
Kavita didn't show web link from metadata (ComicInfo.xml)

### ISSUE THREAD

**Issue by BabaYetuLiye** [Kareadita/Kavita#3125]
### What happened?

Hello, so I have .cbz file with ComicInfo.xml that has web link data. All other metadata are successfully shown on Kavita except that web link. Here's the xml :
```
<?xml version="1.0"?>
<ComicInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Title>All Hail The Sect Leader 01</Title>
  <Series>All Hail The Sect Leader</Series>
  <Summary>All the members of my sect are abnormally strong. All my disciples turn out to be big shots, and I'll definitely become invincible in this world!</Summary>
  <Writer>Jiang Hu Zai Jian</Writer>
  <Genre>Action, Adventure, Comedy, Fantasy</Genre>
  <Tags>Isekai, Wuxia, Male Protagonist, Full Color, Martial Arts, Reincarnation</Tags>
  <Web>https://anilist.co/manga/136499/All-Hail-The-Sect-Leader</Web>
  <LanguageISO>en</LanguageISO>
  <Translator></Translator>
  <AgeRating>M</AgeRating>
  <Manga>Yes</Manga>
  <Characters></Characters>
</ComicInfo>
```

Not shown on kavita :
![ss](https://github.com/user-attachments/assets/1cbf11b7-a29c-4f0b-9448-b67464f5c819)

Also when I use [komf](https://github.com/Snd-R/komf-userscript), the web link are successfully shown. 

Is there something I miss here?

*And thank you for the dev for this amazing app :D

### What did you expect?

The links are shown like when I manually adding it using kavita's gui :
![ss](https://github.com/user-attachments/assets/0399a557-af15-469b-8043-8a129a4c9eed)

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
Weblinks don't populate on the series level actually. The reason is many comic users tag each issue with a link and if we surfaced them up to the series, it wouldn't link correctly.

You can open a FR to perform this perhaps just for Manga library types, where it would make sense.
