### ISSUE TITLE
Covers not generated for some pdf files (magazine)

### ISSUE THREAD

**Issue by mister-bogus** [Kareadita/Kavita#3136]
### What happened?

Covers are not being generated from some pdf files, like this one https://issuu.com/gamberorossointernational/docs/winetravelfood133

With a comment of: "There was a critical error and prevented thumbnail generation"
and details: "unable to call thumbnail_image pngload_source: IDAT stream error"

Version 0.8.0.0 does generate covers rightfully.

### What did you expect?

First page of the magazine pdf to be shown as the cover, as produced by 0.8.0.0

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Mac

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Mac

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Safari

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-08-28 10:59:28.080 +02:00  46] [Warning] API.Services.BookService [BookService] There was a critical error and prevented thumbnail generation on /Users/******/test_kavita/files/Gambero Rosso {2019}/Gambero Rosso {2019} 22.133 - October.pdf. Defaulting to no cover image
NetVips.VipsException: unable to call thumbnail_image
pngload_source: IDAT stream error
```

**Comment by majora2007** [comment]
Please dm or email me the file in question

**Comment by mister-bogus** [comment]
E-mail sent!

**Comment by majora2007** [comment]
I'm unable to reproduce:
![image](https://github.com/user-attachments/assets/b65bcad8-3e9c-4e4c-9756-6b0e2830ced3)

Perhaps it has something to do with your underlying OS? It may have to do with NetVips Native for MacOS. Can you provide full information about your OS?

**Comment by mister-bogus** [comment]
I am using macOS Monterrey 12.7.6 as a testing environment, but my real library is on Synology as a docker container, and the same result. Is it maybe the wrong settings for the library. I am using comic with all file types selected.

**Comment by majora2007** [comment]
Let me share the file with some members of the team and see if anyone else has an issue. I did test on a slightly updated version of NetVips (underlying library), but there wasn't anything around this in the release notes.

**Comment by mister-bogus** [comment]
It works again in 0.8.3!

**Comment by majora2007** [comment]
Music to my ears!
