### ISSUE TITLE
Scheduled tasks are using GMT timezone instead of local

### ISSUE THREAD

**Issue by bri3k** [Kareadita/Kavita#3143]
### What happened?

The library scan is happening at 5pm for me in MST, which is midnight GMT. Kavita is not using local timezone for scheduled tasks.

### What did you expect?

Need to respect the local timezone on the server.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by DieselTech** [comment]
What do you have your tz variable set to? We haven't seen any reports of this not working for users of the LSIO container. 

Output from the LSIO container:

![image](https://github.com/user-attachments/assets/c28a02cd-7033-4bb1-b873-0aaebf9dfe8f)

**Comment by DieselTech** [comment]
60 days have passed with no response, if you are still having this issue you can reopen the ticket,
