### ISSUE TITLE
Base URL not respected in Library URL and smart filter hrefs

### ISSUE THREAD

**Issue by Fesaa** [Kareadita/Kavita#3146]
### What happened?

The baseurl set up, is not respected/used in the library pages. Nor in the links to smart filtered in the dashboard customize page.

They're simply not used, which works fine while on the web app. But reloading the page, or opening it at a later time may cause issues.

I've made a video, with a side by side setup of the stable, and nightly branch.

https://github.com/user-attachments/assets/b318d7ef-e6d6-47ad-b499-ee53fddb1458
If you look closely, the /kavita/ part is included when going to it. But removed when the page loads, maybe this helps a bit.

The issue also occurs with the "load filter" references on this page. I've not included this in the video, as this is also an issue on the stable branch. (The code just doesn't add it)
![image](https://github.com/user-attachments/assets/e3d2f176-4cb1-491d-844b-71a676522419)

### What did you expect?

The baseURL to be appended at all times.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome, Safari

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

### Additional Notes

Relevant discord messages;

https://discord.com/channels/821879810934439936/851515194185744464/1278814185093857280
https://discord.com/channels/821879810934439936/851515194185744464/1277175419463794690
https://discord.com/channels/821879810934439936/851515194185744464/1275565898996125737

**Comment by majora2007** [comment]
I was able to reproduce this but not sure how to fix it honestly. I'm linking the way I always have, so something weird is happening. I need more time to investigate.

**Comment by kayhos** [comment]
I don't know if it has already been fixed as per the pull request from resterday, but under 0.8.3.0, it is still hapening. Kavita is using the correct Base Url in Home, Want to Read, Collections, Reading Lists, Bookmarks, Libraries and Smart Filters. When going in a Series from a library, Kavita redirects from the Base Url to the Stripped Url after loading the page. 

I am using a  docker image (image: jvmilazz0/kavita:latest) and a reverse proxy under Caddy 2.

**Comment by majora2007** [comment]
Is the base URL respected when you Ctrl click a card title? I'm trying to understand which routing mechanisms respect the base URL and which don't.

**Comment by Fesaa** [comment]
The issue wasn't the routing, the routing works just fine. The issue was the page manually updating the url after the page had loaded to include which tab it was open on, but not using the correct url. So the base url got stripped. 


As for what respects it, you can look at the other issue, which shows it clearly. Using any of angulars routing stuff appends it fine, so [routerLink], etc. But using the plain href does not. Which is what causes the issue in settings. 
But we couldn't use routerLink there, as it re-encodes the passed string. Breaking the url, as you pass it an already encoded part

**Comment by majora2007** [comment]
Ahh I see. Let me look at the PR and test today. I'll try and see if I can get this into the hotfix.

**Comment by majora2007** [comment]
Okay here is what I observed after my fixes:
1. I can use Load filter to load a smart filter from customize and no issue
2. I can open a smart filter bound to side nav or dashboard without any issue
3. After any of the above, I can alter the filter and it would reflect and reload a browser refresh completely fine. 

I can build a native build for anyone that is free in the next hour or 2 to test, before I ship the hotfix.

**Comment by majora2007** [comment]
Got the seal of approval from Fresaa :)
