### ISSUE TITLE
Series with similar name in two distinct folders keeps replacing each other

### ISSUE THREAD

**Issue by erradtke** [Kareadita/Kavita#3147]
### What happened?

I have two folders with files as follows:
Folder-1
ComicFile v1988 ch.1
ComicFile v1988 ch.2
ComicFile v1988 ch.3

Folder-2
ComicFile v1989 ch.1
ComicFile v1989 ch.2

The series name is the same, only the vYYYY differs. When I issue a scan of that folder in Kavita, if the v1988 folder is visible, it gets overwritten by the v1989 folder and files. If v1989's files are visible in the UI, then those disappear and only v1988 are visible in the UI. Both version are never visible simultaneously despite having different files names, root folders, and metadata.

### What did you expect?

I expect both series to appear in the UI as different Versions under the series ComicFile.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

 I have tried removing the entire library and starting over with a fresh rescan and rebuild.

**Comment by majora2007** [comment]
You need to switch to the comic vine library type and that will fix this issue.

**Comment by erradtke** [comment]
> You need to switch to the comic vine library type and that will fix this issue.

This did indeed fix the issue, many thanks!
