### ISSUE TITLE
Covers not generated for some pdf files

### ISSUE THREAD

**Issue by LittleOne3** [Kareadita/Kavita#3150]
### What happened?

Unable to see some of the covers for the PDFs.

### What did you expect?

The first page of the pdf is to be shown as the cover, as produced in earlier Kavita versions.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
[Kavita] [2024-09-02 10:15:31.761 -07:00  184] [Debug] API.Services.MetadataService [MetadataService] Generating cover image for /library/learn/Encyclopedia/DK - Super Shark Encyclopedia {2015}.pdf
[Kavita] [2024-09-02 10:15:34.751 -07:00  184] [Warning] API.Services.BookService [BookService] There was a critical error and prevented thumbnail generation on /library/learn/Encyclopedia/DK - Super Shark Encyclopedia {2015}.pdf. Defaulting to no cover image
NetVips.VipsException: unable to call thumbnail_image
pngload_source: IDAT stream error

   at NetVips.Operation.Call(String operationName, VOption kwargs, Image matchImage, Object[] args)
   at API.Services.ImageService.WriteCoverThumbnail(Stream stream, String fileName, String outputDirectory, EncodeFormat encodeFormat, CoverImageSize size) in /home/runner/work/Kavita/Kavita/API/Services/ImageService.cs:line 235
   at API.Services.BookService.GetPdfCoverImage(String fileFilePath, String fileName, String outputDirectory, EncodeFormat encodeFormat, CoverImageSize size) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 1255
```

### Additional Notes

I am currently running Kavita on Qnap Docker.

**Comment by contributor** [comment]
Same here, 0.8.2, fresh install (docker on Synology DSM7). The covers have not been generated for 57 out of 240 pdf books, with the same error in log as above.

Example: free book [Under the Hood of .NET Memory Management](https://www.red-gate.com/simple-talk/wp-content/uploads/RedGateBooks/ChrisFarrell/Under_the_Hood_of_NET_Management.pdf) - direct link, 6.6MB

**Comment by DieselTech** [comment]
@contributor @LittleOne3 Can you both check to see if this issue is still occurring in version 0.8.4.2 of Kavita?

**Comment by contributor** [comment]
@DieselTech  0.8.4.2 works perfectly, thank you. Please link here PR/commit with the fix
