### ISSUE TITLE
Parts of part numbers in filenames misread as series names

### ISSUE THREAD

**Issue by scgtrp** [Kareadita/Kavita#3156]
### What happened?

I created a Reference library in my Kavita instance and dropped a pile of manuals and datasheets into it. Among others, I had these filenames in subdirectories thereof:

- `2N7000_2N7002_NDS7002A N-Channel Enhanceme - Fairchild Semiconductor.pdf`
- `IS31FL3731_DS.pdf`
- `mks_monster8_v2.pdf`

These are misidentified as:
- S7002 of a series called "2N7000 2N7002 ND"
- S31 of a series called "I"
- volume 2 of a series called "mks monster8"

### What did you expect?

The above filenames to be categorized by the directories they are in, not by their misparsed filenames.

This is, of course, a slightly weird use of this software (most of my files are reference material and other nonfiction works so it makes somewhat more sense in context), and it's probably Non-Trivial to solve in a way that always works. I would be happy with a "use only directory structure and never parse filenames" checkbox at the library level.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
Kavita doesn't work the way you are intending. If you need something that does work more like that, I believe Komga and Ubooquity both present series as the lowest folder and present the files with their names intact. Kavita will not behave that way and I have no intention to change that.

**Comment by scgtrp** [comment]
Fair enough.

In case anyone else lands here with the same question: I don't have the motivation to maintain a public fork just for this, but I'm now running my instance with this patch, which disables volume/series/chapter parsing for libraries of type `Book`.

<details>
<summary>patch</summary>

```diff
diff --git a/API/Services/Tasks/Scanner/Parser/Parser.cs b/API/Services/Tasks/Scanner/Parser/Parser.cs
index 840e7a6d..1544e3e2 100644
--- a/API/Services/Tasks/Scanner/Parser/Parser.cs
+++ b/API/Services/Tasks/Scanner/Parser/Parser.cs
@@ -850,7 +850,6 @@ public static class Parser
         {
             LibraryType.Manga => ParseMangaSeries(filename),
             LibraryType.Comic => ParseComicSeries(filename),
-            LibraryType.Book => ParseMangaSeries(filename),
             LibraryType.Image => ParseMangaSeries(filename),
             LibraryType.LightNovel => ParseMangaSeries(filename),
             LibraryType.ComicVine => ParseComicSeries(filename),
@@ -864,7 +863,6 @@ public static class Parser
         {
             LibraryType.Manga => ParseMangaVolume(filename),
             LibraryType.Comic => ParseComicVolume(filename),
-            LibraryType.Book => ParseMangaVolume(filename),
             LibraryType.Image => ParseMangaVolume(filename),
             LibraryType.LightNovel => ParseMangaVolume(filename),
             LibraryType.ComicVine => ParseComicVolume(filename),
@@ -878,7 +876,6 @@ public static class Parser
         {
             LibraryType.Manga => ParseMangaChapter(filename),
             LibraryType.Comic => ParseComicChapter(filename),
-            LibraryType.Book => ParseMangaChapter(filename),
             LibraryType.Image => ParseMangaChapter(filename),
             LibraryType.LightNovel => ParseMangaChapter(filename),
             LibraryType.ComicVine => ParseComicChapter(filename),
```
</details>

**Comment by contributor** [comment]
Looking for a way to "disable series" brought me here. I use Kavita only for books, and the problem is that search book by name doesn't work if a book was recognized as a part of series with other books.

Until there's a better solution, I'm disabling series with your patch to get "must have" feature - search. Thank you @scgtrp
