### ISSUE TITLE
When opening a PDF comic using a Windows browser, IDM（Internet Download Manager） download software will prompt to download, and it cannot be opened after canceling the download.

### ISSUE THREAD

**Issue by chong206** [Kareadita/Kavita#3159]
### What happened?

When opening a PDF comic using a Windows browser, IDM（Internet Download Manager） download software will prompt to download, and it cannot be opened after canceling the download.
![1](https://github.com/user-attachments/assets/d927a643-2a1a-4347-b742-a6d661cb7103)
![2](https://github.com/user-attachments/assets/883bb8fa-24f3-473d-bf9b-175febbb1691)

### What did you expect?

repair

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by scare376** [comment]
https://github.com/mozilla/pdf.js/issues/9722 its a known issue with PDF.js. https://stackoverflow.com/questions/29954361/prevent-pdf-auto-download-by-idm-using-pdf-js  mentions a way that you can stop IDM from intercepting
