### ISSUE TITLE
(Manga Reader) When there is previous and next chapter, next chapter is fetched in full without reason

### ISSUE THREAD

**Issue by artem-schegolev** [Kareadita/Kavita#3168]
### What happened?

1. Start reading https://demo.kavitareader.com/library/2/series/10/manga/14?incognitoMode=false from the beginning (page 1)
2. It fetches `/api/reader/next-chapter?seriesId=10&volumeId=10&currentChapterId=14`, gets `13`
3. It fetches `/api/reader/prev-chapter?seriesId=10&volumeId=10&currentChapterId=14`, gets `16`
4. It fetches `/api/reader/chapter-info?chapterId=16&includeDimensions=false`, gets `89 pages`
5. As soon as you go to next page, it fires **89 requests** (I assume for 89 pages of `16`), but somehow directed to `13`:
```
https://demo.kavitareader.com/api/reader/image?chapterId=13&apiKey=...&page=0
...
https://demo.kavitareader.com/api/reader/image?chapterId=13&apiKey=...&page=89
```
While these 89 requests are being processed by the browser, new requests for current chapter (if you want to go to page 2, for example) are not being processed.
For big cbz files (300+mb) it heavily impacts the bandwidth and slows down browsing.
Tested on FIrefox, Opera, Chrome on Windows 10.

### What did you expect?

1. I would expect step 5 to only occur at N-10 page of current chapter, not at the second page
2. I would expect step 5 to not fetch the whole next chapter, but only 5-10 pages of it

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

I thought that maybe it's due to metadata issues in `ComicInfo.xml`, but various combinations of `Pages` / `PageCount` seem to not have effect.

**Comment by majora2007** [comment]
I'm not sure I fully understand what you're experiencing. The way the web ui works is that when you are within 10 pages of a boundary (aka page 0 - 10 or page N-10 - N), the prev/next chapter is fetched. These operations don't impact the browser as they make a single call and the backend has the heavy work of opening the archive and caching the pages in cache directory. 

I've never seen anything where multiple apis are called like you're describing.

**Comment by artem-schegolev** [comment]
@majora2007 so you cannot reproduce steps 1-5 on demo server from the link that is in step 1?

**Comment by artem-schegolev** [comment]
![opera_fvzY4iVy6L](https://github.com/user-attachments/assets/c3ff300c-f36c-4fc7-bd43-b17f3578e0c0)

**Comment by majora2007** [comment]
Okay what I'm seeing is it prefetching the pages ahead, which is normal. Kavita maintains something like a 10 page prefetch buffer so that the images load quickly. 

I was able to reproduce it on the demo, but not on my actual instance. I'm a bit clueless what's happening on the demo, but are you seeing this occur on your local as well?

**Comment by artem-schegolev** [comment]
> Okay what I'm seeing is it prefetching the pages ahead, which is normal.

it would be normal if it prefetched 5-10 pages, but it tries to prefetch the whole thing. And it's doing it at the start (on second page), not near the end.

> are you seeing this occur on your local as well?

Yes, I was struggling with it on my local docker image instance, tried various metadata combinations, nothing helped, so I went to demo server to see if I'm doing something wrong. It turns out that demo has the same issue.

Seems that it appears when there is more than 2 chapters. So for example https://demo.kavitareader.com/library/3/series/15 is not affected.

**Comment by majora2007** [comment]
Okay I dug a little deeper and this seems to be some sort of Firefox bug. On chrome, it's loading the initial 10 then one after another, however, FF I'm seeing the issue of the next page triggering more than 10 pages of prefetch. 

I'll have to do a deep dive into this. I haven't noticed it when I'm reading, but I'll dive into the code and see what might be causing this issue.

**Comment by artem-schegolev** [comment]
> On chrome, it's loading the initial 10 then one after another, however, FF I'm seeing the issue of the next page triggering more than 10 pages of prefetch.

For me it's like this:
https://demo.kavitareader.com/library/2/series/10/manga/14?incognitoMode=false - Chrome, FF, Opera are all affected
https://demo.kavitareader.com/library/3/series/15/manga/24?incognitoMode=false - Chrome, FF, Opera are all not affected.

**Comment by artem-schegolev** [comment]
UPD:
https://demo.kavitareader.com/library/3/series/15/manga/25?incognitoMode=false is also affected if you start from Volume 2.

It fires ~210 requests, but as they are fortunately incorrectly targeted to "-1" chapterId they don't consume much traffic, as they all return 204:
```
/api/reader/image?chapterId=-1&apiKey=...&page=3
...
/api/reader/image?chapterId=-1&apiKey=...&page=210
```

**Comment by majora2007** [comment]
I figured it out:

```
/**
   * Loads the first 5 images (throwaway cache) from the given chapterId
   * @param chapterId
   * @param direction Used to indicate if the chapter is behind or ahead of current chapter
   */
  prefetchStartOfChapter(chapterId: number, direction: PAGING_DIRECTION) {
    let pages = [];

    if (direction === PAGING_DIRECTION.BACKWARDS) {
      if (this.continuousChapterInfos[ChapterInfoPosition.Previous] === undefined) return;
      const n = this.continuousChapterInfos[ChapterInfoPosition.Previous]!.pages;
      // Ensure we only load up to 5 pages backward 
      pages = Array.from({ length: Math.min(n + 1, 5) }, (v, k) => n - k);
// Original Code: pages = Array.from({length: n + 1}, (v, k) => n - k);
    } else {
      pages = [0, 1, 2, 3, 4];
    }

    const images = [];
    pages.forEach((_, i: number) => {
      const img = new Image();
      img.src = this.getPageUrl(i, chapterId);
      images.push(img)
    });
  }
  ```

**Comment by artem-schegolev** [comment]
Bless you, good sir! Even a multi-terabyte collection of 0.5-3GB HQ doujins should be working like a charm after the fix! (no idea who would have such a collection of course 😄 ) Because other than that bug, I haven't encountered any problems hosting large files.

It is a great project, especially in these troubled times when content is being erased from services left and right.
