### ISSUE TITLE
Use Pagination for OPDS Reading Lists

### ISSUE THREAD

**Issue by rad96** [Kareadita/Kavita#3178]
### What happened?

I noticed performance discrepancy between Kavita and Komga when using them in Panels IPad client with OPDS

When I open large reading list ([example in cbl repo](https://github.com/DieselTech/CBL-ReadingLists/blob/main/Marvel/Master%20Reading%20Order/CBRO%20-%20With%20Events/%5BMarvel%5D%20Marvel%20Master%20Reading%20Order%20Part%20%2301%20(WEB-CBRO).cbl) it take Kavita more then 5 seconds to load it.

Komga, in comparison, start showing issues instantly, on same IPad and Client.

Which is looks like happened - that Kavita tries to push whole list to Client, when Komga somewhat lazy loads list to client

Video of behavior - https://pixeldrain.com/u/aUN7CTsa

### What did you expect?

Faster reading list opening

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

**Comment by rad96** [comment]
I'm not saying that Kavita is working wrong, just want to be sure that there is no underlying issue and this part of Kavita working as expected
And it was on previous version too, not only on new one

**Comment by majora2007** [comment]
What you're asking is to include pagination on the OPDS feed for reading lists. Since more users are using reading lists from CBL project, it makes sense to make this sort of enhancement.

**Comment by rad96** [comment]
> What you're asking is to include pagination on the OPDS feed for reading lists. Since more users are using reading lists from CBL project, it makes sense to make this sort of enhancement.

idk I asked that or not (at least in Panels it looks like infinity scroll for komga too)

**Comment by majora2007** [comment]
I just looked and this issue was opened in Panels already and I did implement pagination. I have confirmation it is working for a local user. So there may just be more processing done by Kavita, since komga just has the filenames and no grouping.

**Comment by majora2007** [comment]
Okay I took a real look this time. I did add pagination support on the reading lists themselves, but unfortunately, it's not on the actual reading list. 

This is a non-trivial thing to add due to the fact that depending on the library type we have to use a different naming convention. So it's a bit more involved due to how Kavita functions. 

I'm not going to reject it, but I will ask if you can create a Feature Request to have pagination on the reading list OPDS route so we can see if other users need this feature. It's a great idea, but due to the amount of work to implement, I need some other users to chip in.

**Comment by cwar** [comment]
> I just looked and this issue was opened in Panels already and I did implement pagination. I have confirmation it is working for a local user. So there may just be more processing done by Kavita, since komga just has the filenames and no grouping.

I know this issue that the OP is referring turns out to be slightly different but than the one @majora2007 is talking about here.. but to add some additional context here, I am that local user that confirmed the pagination is working for the reading lists view! Thanks again for that.

**Comment by ririnto** [comment]
I'm using cantook. And this client does not support Pagination and "Sync read progress" with Kavita.

[Komga said](https://komga.org/docs/guides/opds/) this client support that features.

Plz support that features.

I really like Kavita and Cantook.

**Comment by majora2007** [comment]
As mentioned, please create a feature request. I'm going to close out the issue. If you don't create the FR, I will forget about it, so please do.
