### ISSUE TITLE
Modified settings cannot be saved

### ISSUE THREAD

**Issue by kofzhanganguo** [Kareadita/Kavita#3180]
### What happened?

![image](https://github.com/user-attachments/assets/9ebdaae3-f588-474a-8df9-e59a49ca6388)
Once the options are set here, they cannot be saved.

### What did you expect?

![image](https://github.com/user-attachments/assets/9ebdaae3-f588-474a-8df9-e59a49ca6388)
Once the options are set here, they cannot be saved.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by kofzhanganguo** [comment]
https://github.com/user-attachments/assets/f3c9a886-a711-4e99-87d4-5776c6e87964

Video Description

**Comment by majora2007** [comment]
Nice catch, I'll get this fixed up for the upcoming hotfix

**Comment by kofzhanganguo** [comment]
> Nice catch, I'll get this fixed up for the upcoming hotfix


https://github.com/user-attachments/assets/bc743582-ce86-4e6f-9a90-c7f4e14584d7

It seems that this type of option cannot automatically save the settings. I don’t know what the problem is.

**Comment by majora2007** [comment]
Don't worry, I fixed it up. A hotfix will be issues this weekend.

**Comment by DeepHueStudios** [comment]
This is also occurring for the Base Url setting.  It broke my NGINX reverse proxy after I upgraded, and I can't fix it.  Hopefully your hotfix will fix that issue too

**Comment by majora2007** [comment]
@DeepHueStudios just an fyi, you are likely installing incorrectly if you are loosing settings between versions.
