### ISSUE TITLE
No save button when setting an email server

### ISSUE THREAD

**Issue by orangebrush72** [Kareadita/Kavita#3185]
### What happened?

I am trying to set up an email server using gmail. In the latest version with the new admin menu there is no Save button. See screenshot. 

![image](https://github.com/user-attachments/assets/dca86b37-2834-4b11-8386-dbc509b91692)

![image](https://github.com/user-attachments/assets/4d42146a-93a7-460f-af9d-71e87720b033)

Hosting on Unraid 6.12.11

### What did you expect?

I expected a Save button as per the prompt.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
There are no more save buttons in the UI anymore. After you edit something it automatically saves.

**Comment by orangebrush72** [comment]
Thanks for the prompt response. I am getting this prompt:

![image](https://github.com/user-attachments/assets/a9e93a70-d167-4c07-b5d0-245ae85152b7)

I have clicked into other fields but still get this error:

![image](https://github.com/user-attachments/assets/ea8748ae-4bfb-4b53-a417-e6634d8c529f)

Am I doing something wrong?

Cheers
Tim

**Comment by majora2007** [comment]
Nothing wrong, I just forgot to tweak the wording. What the message means is, you need to ensure you've filled out the email settings before using test button. Although now, the message is irrelevant since settings automatically save. 

I'll adjust the language for the upcoming hot fix.

**Comment by orangebrush72** [comment]
Thanks @majora2007  Now I just need to work out why the settings I have inputted don't work. BTW you are doing an awesome job, keep it up. Cheers Tim

**Comment by majora2007** [comment]
If you do need a bit more hands on support, feel free to drop by the discord.
