### ISSUE TITLE
Password Length Cannot Be Longer Than 32

### ISSUE THREAD

**Issue by Menghini** [Kareadita/Kavita#3186]
### What happened?

I read in the change notes for today (v0.8.3) that "Changed: Passwords can now be up to 256 characters long". However, when I tryied to change my password to be longer, I got this error
```
400 Error
{"type":"https://tools.ietf.org/html/rfc9110#section-15.5.1","title":"One or more validation errors occurred.","status":400,"errors":{"Password":["The field Password must be a string with a minimum length of 6 and a maximum length of 32."]},"traceId":"00-8c476e7a123c7be9ea5b310860b6904d-089785bc682a4b6c-00"}
```
This occured on the `/settings#account` page.

### What did you expect?

For my password to be changed to a longer password.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Other (List in "Additional Notes" box)

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

Using Brave on Windows. But the server is Ubuntu Server.

**Comment by yoppayop** [comment]
I just encountered this same error 400 with a new Docker Portainer install hosted on Ubuntu Server.

A password less than 32 characters bypassed the issue.
