### ISSUE TITLE
[Kavita 0.8.3.0] Chapter sorting inconsistently incorrect with volumes

### ISSUE THREAD

**Issue by merlinmarijn** [Kareadita/Kavita#3196]
### What happened?

i've made a script to split up each manga series into volumes of 1-250... this has caused some weird sorting issue where the first chapter in the volume appears as the last but has the correct sorting value and a few random ones appear at the start

![image](https://github.com/user-attachments/assets/09998ca5-c6df-4527-a534-3e3121c6c2f5)
this is chapters 1000-1249, chapter 1000 is at the end and 1033/1029/130/1031/1032 are for no reason at the start,
Here are the xml files of the wrongly placed chapters
![image](https://github.com/user-attachments/assets/dfe9150e-2769-4f3e-976d-32acddc40bc6)
![image](https://github.com/user-attachments/assets/7da083e4-8d63-4402-9d73-a08b39acfca4)
![image](https://github.com/user-attachments/assets/9167b938-a4ac-4530-a237-1a2ece722a9d)
![image](https://github.com/user-attachments/assets/ff6f5791-fc98-4c9b-9607-9c6297326a7d)
![image](https://github.com/user-attachments/assets/60dbde8c-8212-4444-adb3-75d8604267fc)
![image](https://github.com/user-attachments/assets/cb51cbb0-107f-4843-b9e3-d312966c80c5)

and here is the xml from the first one thats actually where it should be (1001)
![image](https://github.com/user-attachments/assets/ca912cdc-f172-44a0-9db3-1e03f0731831)

### What did you expect?

Chapters to be sorted correctly in my case in volume 4 chapters 1000-1249

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other (List in "Additional Notes" box)

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox, Chrome, Safari, Other iOS Browser

### Additional Notes

Browser: Opera GX (tested in edge and also had the same problem)

**Comment by majora2007** [comment]
The view in the screenshot, is that Storyline/Chapters tab or is that from Volume details? I just fixed an issue where Volume Details wasn't loading in the correct order.

**Comment by merlinmarijn** [comment]
![savemysoul](https://github.com/user-attachments/assets/aeec5558-6e6e-4a9d-8a38-416d41179b55)
it's when you go to a series and click volumes, this is when you click volume 4
@majora2007

**Comment by majora2007** [comment]
Perfect, then this is fixed in the nightly.
