### ISSUE TITLE
Kavita Komf Network Error

### ISSUE THREAD

**Issue by leocordis27** [Kareadita/Kavita#3199]
### What happened?

I tried installing Komf from docker for my Synology DS420+

I first created "komf" folder and "config" subfolder in my docker folder:
I also put the application.yml file inside the config subfolder. I use the code from [kavita wiki](https://wiki.kavitareader.com/guides/external-tools/komf).

kavita:
  baseUri: "http://192.168.1.134:5471" #or env:KOMF_KAVITA_BASE_URI
  apiKey: "YOUR_API_KEY_HERE!" #or env:KOMF_KAVITA_API_KEY
 
database:
  file: /volume1/docker/komf/config/database.sqlite # database file location.

![image](https://github.com/user-attachments/assets/aa70f07b-dcdf-461a-9e50-14cfc04aeaef)

I then use portainer to compose the docker container, the compose file is from [komf wiki](https://github.com/Snd-R/komf/wiki/Installation):

version: "3.7"
services:
  komf:
    image: sndxr/komf:latest
    container_name: komf
    ports:
      - "8085:8085"
    user: "1000:1000"
    environment:
      - KOMF_KAVITA_BASE_URI=http://192.168.1.134:5471
      - KOMF_KAVITA_API_KEY=my-api-key
      - KOMF_LOG_LEVEL=INFO
      # optional jvm options. Example config for low memory usage. Runs guaranteed cleanup up every 3600000ms(1hour)
      - JAVA_TOOL_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -XX:ShenandoahGuaranteedGCInterval=3600000 -XX:TrimNativeHeapInterval=3600000
    volumes:
      - /path/to/config:/config #path to directory with application.yml and database file
    restart: unless-stopped

The container is created successfully. I then setup the tampermonkey based on the kavita wiki.
[https://wiki.kavitareader.com/guides/external-tools/komf](https://wiki.kavitareader.com/guides/external-tools/komf)

The jigsaw icon appeared but I cannot connect it to Kavita. It says network error.

![image](https://github.com/user-attachments/assets/1a66e245-c083-40fb-88eb-1f5b583e2194)

Any idea how to fix this?

### What did you expect?

The connection should be connected successfully

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

Running Kavita 0.8.3.0 via Docker from Synology DS 420+

**Comment by scare376** [comment]
Komf is a 3rd party application that has kavita integration. This belongs in https://github.com/Snd-R/komf or https://github.com/Snd-R/komf-userscript although we do also have a channel in the kavita discord server for komf.

**Comment by sarhatabaot** [comment]
@leocordis27 Sorry to comment on this completed issue, but have you had any luck with this issue? Stuck on this too honestly.

**Comment by scare376** [comment]
Like I said previously. Please refer to the komf GitHub or we have a komf channel in the discord that you can ask around in. Komf troubleshooting does not belong here
