### ISSUE TITLE
Sometimes changing the page or refreshing does not load properly Kavita

### ISSUE THREAD

**Issue by zsuatem** [Kareadita/Kavita#3202]
### What happened?

Sometimes changing the page or refreshing does not load properly Kavita.
Closing the tab and entering the page in a new tab solves the problem until it reappears, which seems to be random.

In browser
![image](https://github.com/user-attachments/assets/8f8089b1-5ba1-488b-9dff-c2d4bab6c28d)

Server log (nothing interesting)
![image](https://github.com/user-attachments/assets/361c50a1-fe8d-4b39-8acf-a2d46b9f2acb)

### What did you expect?

Correct loading of the page

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge, Other (List in "Additional Notes" box)

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox, Chrome, Other iOS Browser

### Additional Notes

Sometimes changing the page or refreshing does not load properly Kavita.
Closing the tab and entering the page in a new tab solves the problem until it reappears, which seems to be random.

In browser
![image](https://github.com/user-attachments/assets/8f8089b1-5ba1-488b-9dff-c2d4bab6c28d)

Server log (nothing interesting)
![image](https://github.com/user-attachments/assets/361c50a1-fe8d-4b39-8acf-a2d46b9f2acb)

**Comment by majora2007** [comment]
Does this happen on localhost? This looks like something related to how your reverse proxy is setup. I've never had any issue or seen these logs even on our demo instance which is constantly being hit.

**Comment by zsuatem** [comment]
Right, my mistake :) For some reason, after upgrading to version 0.8.3, the rate limits turned out to be too low
