### ISSUE TITLE
Can't generate webp bookmarks

### ISSUE THREAD

**Issue by Roshri** [Kareadita/Kavita#3204]
### What happened?

After updating to 0.8.3 (and the hotfix) I got an error when trying to create a bookmark, both in windows and docker.

In docker, it additionally restarted the service.

Error in docker

```
[Kavita] [2024-09-21 12:35:11.420 -03:00  48] [Debug] API.Services.MediaConversionService Converting /bookmarks/1/12669/1220623/hitara, Betsu no Tatakai ga Hajimatta. - 001.webp image into "WEBP" at /bookmarks/1/12669/1220623/

/entrypoint.sh: line 33:     7 Segmentation fault      (core dumped) ./Kavita

Starting Kavita

ls -l /kavita/config/appsettings.json

[Kavita] [2024-09-21 12:35:15.560 -03:00  6] [Information] API.Program Running Manual Migrations`
```

Error in windows

```
[Kavita] [2024-09-21 12:46:21.726 -03:00  53] [Debug] API.Services.Plus.ScrobblingService Overriding scrobble event for Magical Girl Tsubame: I Will (Not) Save The World! from vol 100000 ch 41 -> vol 100000 ch 41
[Kavita] [2024-09-21 12:46:24.190 -03:00  48] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/bookmark responded 200 in 70.5671 ms
[Kavita] [2024-09-21 12:46:24.196 -03:00  4] [Debug] API.Services.MediaConversionService Converting C:\Kavita\config\bookmarks\1\21964\1219432\Magical Girl Tsubame I Will (Not) Save The World! - 015.webp image into "WEBP" at C:\Kavita\config\bookmarks\1\21964\1219432\
[Kavita] [2024-09-21 12:46:24.202 -03:00  4] [Error] API.Services.MediaConversionService Could not convert image 1\21964\1219432\Magical Girl Tsubame I Will (Not) Save The World! - 015.webp to "WEBP"
NetVips.VipsException: unable to call VipsForeignSaveWebpFile
C:\Users\roshr\Documents\WindowsPowerShell\Kavita\config\bookmarks\1\21964\1219432\Magical Girl Tsubame I Will (Not) Save The World! - 015.webp: unable to open for write
windows error: The device does not recognize the command.


   at NetVips.Operation.Call(String operationName, VOption kwargs, Image matchImage, Object[] args)
   at NetVips.ExtensionMethods.Call(Image image, String operationName, VOption kwargs, Object[] args)
   at NetVips.Image.WriteToFile(String vipsFilename, VOption kwargs)
   at API.Services.ImageService.ConvertToEncodingFormat(String filePath, String outputPath, EncodeFormat encodeFormat) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\ImageService.cs:line 312
   at API.Services.MediaConversionService.SaveAsEncodingFormat(String imageDirectory, String filename, String targetFolder, EncodeFormat encodeFormat) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\MediaConversionService.cs:line 303
```
   
 
I tried testing to change the encoding and create a png bookmark and found out that since the files were already in webp format, the bookmarks could be saved as webp

![image](https://github.com/user-attachments/assets/fb769d7c-2052-44b1-b361-590ddca6efdf)

### What did you expect?

Bookmarks creation flow should check beforehand if encoding is webp and should save it as is before trying to convert the file

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox

**Comment by majora2007** [comment]
Learning from discussion, check the source file extension to tell if we need to do any conversion.
