### ISSUE TITLE
Specials not showing in main series

### ISSUE THREAD

**Issue by earth4s** [Kareadita/Kavita#3208]
### What happened?

I have the following file structure for one of my series:
```
Library Root
  ┖── Doraemon - Chronological Edition
      ┖── Doraemon - Chronological Edition v01 (2013) (Digital).cbz
      ┖── Doraemon - Chronological Edition v02 (2013) (Digital).cbz
      ┖── Doraemon - Chronological Edition v03 (2013) (Digital).cbz
      ┖── etc... (50 volumes total)
      ┖── Specials
          ┖── Doraemon - Chronological Edition SP01 - Chapter List.pdf
```
But the PDF in the specials folder refuses to join the main series properly. What odd is that on the home page the series is  combined on the "Recently Updated Series" section but not the "Newly Added Series" section.
Example:
![exp1](https://github.com/user-attachments/assets/ebab6b07-43fe-4e03-a694-2c39a16fc2dd)

In the "Manga" type library that contains the series it also shows separated:
![exp2](https://github.com/user-attachments/assets/6455f96f-8c76-49d8-8da4-efaeaf07350a)

### What did you expect?

I expected the Series and special to be combined. 

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

This is one of the few series that I have added since going to the 8.3.x line

**Comment by scare376** [comment]
Cbzs and PDFs cannot be combined in a single series and will always be split

**Comment by Sawtaytoes** [comment]
> Cbzs and PDFs cannot be combined in a single series and will always be split

I wish there was some way to combine them. I've run into this myself.
