### ISSUE TITLE
"Include Chapters & Files" toggle closes the search window when search results are empty

### ISSUE THREAD

**Issue by lundbergg** [Kareadita/Kavita#3210]
### What happened?

Clicking the switch results in the search window closing. 
![search](https://github.com/user-attachments/assets/f6a39e08-4148-4e92-b713-ad118668df61)

### What did you expect?

The search window should stay open and the toggle should switch.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox

**Comment by majora2007** [comment]
Looks like this is a regression from when the UX overhaul took place. I'll look into it.
