### ISSUE TITLE
No action when trying to delele a number in a series

### ISSUE THREAD

**Issue by cristianconti** [Kareadita/Kavita#3212]
### What happened?

Deleting a comic number doesn't do nothing. This happens when i select the three points menu on a comic number, and when i select the comic and trying to do the same on the top bar. This is what happens in a gif video https://imgur.com/Y9Y9Wuk

### What did you expect?

I expect to see a popup asking me if i'm sure to delete the file.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome, Other (List in "Additional Notes" box)

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by scare376** [comment]
first off i see you're having issues with translation keys. can you try the steps here to fix it and then retry? https://github.com/Kareadita/Kavita/discussions/3177#discussioncomment-10683465
I was unable to reproduce the issue.
