### ISSUE TITLE
Localization issue (Irish)  - translations not appearing - keys being displayed instead of translation

### ISSUE THREAD

**Issue by aindriu80** [Kareadita/Kavita#3213]
### What happened?

Irish has been fully translated on Weblate however when switching to Irish in Kavita keys are being displayed and not the translated text.  I have noticed other languages (Indonensian) with same issue.  Here is a screen shot of User Preferences:-

![Xnip2024-09-23_09-21-28](https://github.com/user-attachments/assets/19642fb1-7d43-4396-bc7c-fdd64bf00747)

Translations have been translated where applicable however the {{ }} items were left as is,  he is a screenshot of some translations:

![Xnip2024-09-23_09-24-16](https://github.com/user-attachments/assets/54982225-1617-4410-b9cd-312e1fd76864)

### What did you expect?

Expected to see everything translated without the keys being displayed.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

 [Information] API.Program Kavita - v0.8.3.2

### What operating system is Kavita being hosted from?

run on a Raspberry Pi 4, Docker container

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

viewed on a macOS

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

All seems well, last few lines of log file:
[Kavita] [2024-09-23 08:25:40.164 +00:00  120] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/account/refresh-account responded 200 in 40.2841 ms

[Kavita] [2024-09-23 08:25:40.187 +00:00  120] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 1.4439 ms

[Kavita] [2024-09-23 08:25:40.188 +00:00  114] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/device responded 200 in 2.9453 ms

[Kavita] [2024-09-23 08:25:40.244 +00:00  122] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 0.7738 ms

[Kavita] [2024-09-23 08:25:43.763 +00:00  114] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/users/update-preferences responded 200 in 22.4651 ms

[Kavita] [2024-09-23 08:25:43.781 +00:00  122] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/device responded 200 in 2.7627 ms

[Kavita] [2024-09-23 08:25:43.816 +00:00  115] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/account/refresh-account responded 200 in 39.3483 ms

[Kavita] [2024-09-23 08:25:43.839 +00:00  122] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/device responded 200 in 2.4131 ms

[Kavita] [2024-09-23 08:25:43.843 +00:00  115] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 0.6783 ms

[Kavita] [2024-09-23 08:25:43.844 +00:00  122] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 2.2569 ms

**Comment by scare376** [comment]
https://github.com/Kareadita/Kavita/discussions/3177#discussioncomment-10683465 please follow the steps here

**Comment by aindriu80** [comment]
I tried those steps but it didn't make any difference, I have tried Firefox and Chrome, I don't usually use Chrome and haven't used it with Kavita before but followed the steps (clearning all local storage) and there were no changes

**Comment by aindriu80** [comment]
I re pulled the docker container however the display issue is still there
` image: jvmilazz0/kavita:latest`

**Comment by aindriu80** [comment]
You can view the issue here https://demo.kavitareader.com/settings#preferences 

Change language settings to Irish

**Comment by majora2007** [comment]
This is a cache issue and not an issue with the localization file. The steps linked, should help fix the issue. You can validate that it is a caching issue, by opening up the Kavita URL in a browser you've never used before or incognito mode. That will load a fresh copy of the locale file.

**Comment by aindriu80** [comment]
no luck with Irish but your solution works with Korean..   Korean has the same issue however when I hit hard refresh it brought in the Korean strings.  I tried Safari which I never use and Firefox Developer Edition (incognito mode) but it is not pulling in the strings and is using the keys.

**Comment by majora2007** [comment]
Let me take a deeper look. Last night I did notice some weirdness in all the locales, maybe something with weblate or some manual merges. 

While I can't release another hotfix, I can give instructions on how to update your locale files manually.

**Comment by aindriu80** [comment]
Thats fine! I will wait for your instructions:)

**Comment by majora2007** [comment]
Okay this is a very strange issue because it only affects Irish, but the json is valid. I'm stumped. I raised an issue with the underlying library to get some expert help on it. I did just push and sync weblate with updated json files (the underlying store for the locale files). 

I'll update you once I have some more understanding.

**Comment by aindriu80** [comment]
I see, that is very strange seeing the JSON is valid.  It is hard to say why it isn't working.  Kavita has the right keys (one key example is `ga.user-preferences.global-settings-title`  ga is the language code for Irish).  I look forward to your findings, many thanks for investigating!

**Comment by alaya233** [comment]
The same issue with Chinese

**Comment by majora2007** [comment]
https://github.com/jsverse/transloco/issues/803

For tracking the issue with library. 

@alaya233 chinese does work. Follow the steps in the first comment to clear your cache.

**Comment by bronko83** [comment]
@majora2007 @aindriu80 
randomly found this ticket here, but I think i found the issue.

languageCodes registers the available transloco languages. 'GA' is not in the list.

https://github.com/Kareadita/Kavita/blob/b44f89d1e8b89e478f5216891c6937d8c0397d7c/UI/Web/src/main.ts#L78-L108

so we see 
![image](https://github.com/user-attachments/assets/91f37b33-5818-4ca2-b644-34fd3ac830c8)

adding 'ga' to languageCodes
![image](https://github.com/user-attachments/assets/f88a2daa-1cbb-49a8-b4aa-c5ca9773b6ac)

gives us
![image](https://github.com/user-attachments/assets/8915d8b8-140c-43f0-8b80-82f0d8d54550)

I did not create a PR because of the comment above the languageCodes. GA is not in the linked list but comment says that this is what will be supported. 

HTH

**Comment by majora2007** [comment]
Good find, it's always the simple stuff you gloss over. I suppose I'll need to build a better code mapping. Weblate uses a different standard for languages than Transloco.

**Comment by aindriu80** [comment]
Great find !

`'ie_GA' `would be Ireland or just `ga` for irish
