### ISSUE TITLE
Kavita installation on Raspberry Pi 4 does not detect all the files in folder

### ISSUE THREAD

**Issue by vineethkartha** [Kareadita/Kavita#3217]
### What happened?

Hi,

I have a huge collection of pdfs, epubs etc (around 2000 files). All these files are located in a nested hierarchy of the form

Library Root
--- Author
-------Book title
------------ Book.pdf(epub etc)

This is the folder structure that was used by Calibre.

In Kavita, only 670 books are getting detected and the remaining are not getting detected after multiple attempts to rescan the library.
Seems like books in .mobi format are not getting detected.
### What did you expect?

I expect to see all the files in the library.

### Kavita Version Number - If you do not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
You are going to need to provide more information to get support. You do know that Kavita does not mimic folder structure and relies on parsing filename or metadata from files to group into Series correct?

**Comment by vineethkartha** [comment]
After spending some more time I realised that Kavita does not recognize files of .azw. azw3 and .mobi format
