### ISSUE TITLE
[nightly] Series page displaying float value not rounded in "Time Left"

### ISSUE THREAD

**Issue by Cducharme84** [Kareadita/Kavita#3224]
### What happened?

Due to the change in value type the series page isn't rounding as expected, per the discord discussion this is here as a reminder for Joe to tidy that up before stable.

![Screenshot_20240924_083335](https://github.com/user-attachments/assets/a4f067e2-7d27-4bd0-9a6c-cae376bdedaf)

### What did you expect?

An hour or half/quarter hour display similar to "1.5 hours" in the case of the attached screen.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by Cducharme84** [comment]
Less series detail related but in the spirit of tidying up the presentation of stats, when hovering over either a user account stats page `Time Spent Reading` or the server stats page under `Total Read Time` you'll get the number of hours used in the calculation but it doesn't designate that it's hours being displayed. It's an easy inference but to match labeling through other presentation of read times it should read `XXX hours` for consistency's sake

**Comment by majora2007** [comment]
Got this fixed in one of the nightlies in v0.8.3.x for the v0.8.4 release.
