### ISSUE TITLE
Release and Language fields missing from details page after UX revamp

### ISSUE THREAD

**Issue by Roshri** [Kareadita/Kavita#3225]
### What happened?

In the old UX when you browsed a series you could see more detailed metadata from a series, including Language and Release Year (Format is also missing)

![firefox_D4JvGfYxOw](https://github.com/user-attachments/assets/ea11b382-9fb4-45a7-b412-17f7708f07a5)

After the revamp these fields no longer fit on the new UX

![image](https://github.com/user-attachments/assets/82b0a479-de24-4161-9183-3e90dec4fa8c)

So I propose moving it to the Details Page to have easier access to metadata, instead of having to browse to the Edit Series modal

![image](https://github.com/user-attachments/assets/217f41c2-47dc-4810-b66f-c602fa245b6a)

Something like before the Web Links could be a good option imo

### What did you expect?

Being able to see more metadata at a glance when browsing a series

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox

**Comment by jncmney** [comment]
I’d like to have release year back on the main series page!
