### ISSUE TITLE
Missing fields error messages in server email configuration

### ISSUE THREAD

**Issue by DevEkode** [Kareadita/Kavita#3226]
### What happened?

1. Open `settings#admin-email` in kavita
2. Enter wrong hostname like `example.com` (should be `https://example.com`)
3. Click on close button
4. Re-click on edit button of hostname, the field is showing an error but without any message
![image](https://github.com/user-attachments/assets/eb080107-4abd-4c15-b64a-fccd00702385)
And when you click on test, only a vague message appear
![image](https://github.com/user-attachments/assets/80837fb6-1d0e-4cbe-8689-1510dff96a9d)

### What did you expect?

The field should not close if not valid or at least show why the field cannot be validated.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by daurpam** [comment]
I had the same problem in my first deployment of kavita. I've resolved write down the URL of my host on the hostname field, ex:
https://kavita.domain.com

Aftert that the field save correctly and test works. Hope it helps
