### ISSUE TITLE
Mobile send to actionable menu is broken

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#3230]
### What happened?

![msedge_ZBar8pCYQt](https://github.com/user-attachments/assets/6600bf6c-e7bb-45da-88cc-eeccce2acddb)
send to actionable menu doesnt appear to be fully hooked up. uses the translation keys and the button does not function correctly.

### What did you expect?

The menu functions as normal.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome

**Comment by majora2007** [comment]
Where are you triggering this from? I need to know the source location as each place handles it differently.

**Comment by scare376** [comment]
This came from the 3 dots on series details. I see it happen on the series as a whole and for individual volumes. Seeing it on volume/chapter detail pages as well.

**Comment by jshank** [comment]
Same issue here but only on the mobile/web interface

Book triple-dot - **Send to** shows a menu with items 
- actionable.
  - actionable.Jim's Device
  - actionable.SO's Device

Selecting either of these doesn't send the book via email. Upon clicking, the back button becomes
- Back to actionable.Jim's Device

**Comment by Neriderc** [comment]
Checking in to say I also have this issue. I'm on the stable 0.8.3.2 not nightly like OP. 

Desktop seems fine for me.

**Comment by Orybon** [comment]
Hi,

Same issue here on smartphone Chrome 130.0.6723.58 using 0.8.3.2.

Still working fine on computer.

**Comment by stunrelay** [comment]
Hi,
Same issue here on multiple browsers. Also on latest branch.

**Comment by Net0o** [comment]
It's still not working for me, I am on latest stable build. Desktop is not affected, just sending from mobile, tried Android & iOS / Chrome, Firefox, Safari.

**Comment by majora2007** [comment]
The next stable is right around the corner. I close issues as I release them into the nightly testing branch. I am in the final testing phases for the next stable.

**Comment by Net0o** [comment]
It seems the function displays correctly but doesnt work on mobile (tested just Android device newesr release)
