### ISSUE TITLE
OPDS collection behaves strangely with Panels on iOS

### ISSUE THREAD

**Issue by Rob117** [Kareadita/Kavita#3231]
### What happened?

This is an extension of #3079.

Quoting from there:

> 
> Hi! Tested with [nightly-0.8.3.4](https://hub.docker.com/layers/jvmilazz0/kavita/nightly-0.8.3.4/images/sha256-48780794c35baf16546bd03fe5a8b44d152952d6ab5d2964300ba6196ea8bdaf?context=explore)
> 
> Upside:
> panels will now connect!
> 
> Downside:
> A comic with 100 pages will now show up as 100 1-page items. Each item is (for some reason?) a copy of the first page.
> As in the preview thumbnail is page 1 for all 100 pages, and clicking on any page shows the image for the first page.

### What did you expect?

I expected a single 100-page comic to be a reported as a single collection of files instead of 100 1-page collections. Also, I expected each page of the comic to be the correct page and not a copy of the cover.

I confirmed the comic works correctly in the native Kavita reader

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

**Comment by majora2007** [comment]
Can you describe the source media? It sounds like you have a folder of images that you are serving via OPDS and expecting it to "zip" them for you, which is not how OPDS works.

**Comment by Rob117** [comment]
I do have a folder of images!

I may actually be misunderstanding how OPDS works. Tachiyomi lets me read a collection of images as a single book, but is it most likely the case that this is not a function of OPDS but instead a feature of Tachiyomi?

**Comment by scare376** [comment]
Correct. Also tachiyomi doesn't actually use OPDS it just uses the OPDS url to get all the data it needs to connect via api

**Comment by Rob117** [comment]
Understood! Sorry for the confusion, thank you very much!
