### ISSUE TITLE
Series folders with certain names are ignored by the manga library scan 

### ISSUE THREAD

**Issue by mattialuzi** [Kareadita/Kavita#3234]
### What happened?

I am not able to make Kavita recognize some manga series using their names as the name of folder in wich their files are located. I'll try to explain the issue with an example. My folder structure is the following:

- manga/ -> root folder
    - Pluto -> series folder
        - Pluto v01.cbz -> volumes
        - Pluto v02.cbz
        - ...
        - Pluto v09.cbz
 
After a library scan the manga series Pluto is not recongized and doesn't show up in Kavita even though this is the suggested structure for manga series according to the wiki (https://wiki.kavitareader.com/guides/scanner/manga). The strange thing is that if I try to change a the folder name from Pluto to something like "Pluto (2003)" or even "Plut", leaving the files inside untouched, the series shows up in Kavita as expected. 
Believing was something related to my specific configuration or DB file, I've tried with a clean installation but the issue persists.
When the series is not recognized the log output suggests that the scanner is not able to find files inside the folder.

### What did you expect?

The manga series to be recognized 

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-09-28 00:14:35.130 +02:00  4] [Debug] API.Services.DirectoryService [ScanFiles] called on /home/raspberry/data/media/manga/Pluto
[Kavita] [2024-09-28 00:14:35.130 +02:00  4] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 0 files for /home/raspberry/data/media/manga/Pluto
[Kavita] [2024-09-28 00:14:35.131 +02:00  4] [Information] API.Services.Tasks.ScannerService [ScannerService] /home/raspberry/data/media/manga/Pluto is empty or is no longer in this location
```

### Additional Notes

Also tested v0.8.1 arm64 (raspberry pi 4B)

**Comment by majora2007** [comment]
This looks to be a configuration issue because I have this layout for nearly my whole library without issue.

Follow up info needed:
1. Library type
2. Any exclude patterns?
3. What file types are selected for the library?
4. Docker or native install? If docker please give mount points.

**Comment by mattialuzi** [comment]
UPDATE: I've found the culprit. 
In my folder library there was an hidden an forgotten folder at root level (.covers-backup) with some old covers jpeg. Moving this folder solved the problem. It was strange so i checked again the logs and i found that the library scanner tried to parse the content of this folder but obviously not finding any legitimate series files. After this, every other folder parsing attemp failed.  It seems that changing the folder names of the series also changes the parsing order of the scanner so for example "Pluto" was parsed after the hidden folder giving problems, instead "Pluto (2003)" was parsed before the hidden folder without any issue

I don't know if this can be considered a bug or if the user is supposed to avoid or exclude this folder, anyway thanks for the (fast) response.

**Comment by majora2007** [comment]
Well the user can exclude the folder in the library exclude patterns, but that is extremely strange. I've never heard of something like that happening before. 

I'll close the issue for now.
