### ISSUE TITLE
Reading List hyperlinks no longer available while viewing a series

### ISSUE THREAD

**Issue by maximo1984** [Kareadita/Kavita#3235]
### What happened?

I created Trade Paper Back lists for each series, and these would show up as convenient links on the page. This is no longer the case. Was this a feature that was removed in the updates?

### What did you expect?

Hyperlinks to each reading list created for any given series.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

I am using update 0.8.3.2

**Comment by majora2007** [comment]
Reading lists and collections should show under the details tab now. We moved them down to improve and have a consistent experience across all devices. 

Can you double check that are there?

**Comment by maximo1984** [comment]
Looks like they appear in "Related" and a scroll menu. I quite like that alot.
![Screenshot from 2024-09-28 07-55-54](https://github.com/user-attachments/assets/21f091fe-3e9f-45aa-b25f-811ca2a01369)

**Comment by majora2007** [comment]
Oh yeah, related tab! You can click on the reading button to start reading them immediately if you like or shift+click to open them in a new tab. I tried to bring more functionality for the trade off of moving things around, but I think this is a much better experience. Thanks for confirming.

**Comment by majora2007** [comment]
Also you might want to run Generate Colorscape on your library to get the dynamic colorscape feature working. I noticed your background doesn't match any colors from your cover image.

**Comment by maximo1984** [comment]
Thanks, I was trying to find that. Really impressed with this update. You added the view single issues which I asked for with others.

**Comment by maximo1984** [comment]
> Also you might want to run Generate Colorscape on your library to get the dynamic colorscape feature working. I noticed your background doesn't match any colors from your cover image.

Still cannot find that anywhere

**Comment by majora2007** [comment]
![image](https://github.com/user-attachments/assets/4f562db6-490f-4bf3-bc6e-83bc2776a067)
