### ISSUE TITLE
From library page, series download button not hooked up

### ISSUE THREAD

**Issue by Cducharme84** [Kareadita/Kavita#3238]
### What happened?

While I'm on nightly this is confirmed affecting the Stable 0.8.3.2 as well, was originally reported in Discord support channel as iOS related. Confirmed it is present on desktop/tablet views as well.

Replication steps:
Open library
Click 3 dots on series
Press download
Logs will not reflect download nor will activity widget come alive

Downloads work outside of the Library screen such as from the series detail screen.

### What did you expect?

Download to start once series is zipped

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
No recognition of button press in logs.
```

**Comment by majora2007** [comment]
Validated this on v0.8.3.x and all is working as expected. Can you revalidate? Are you saying it's only for iOS?

**Comment by Cducharme84** [comment]
https://www.mediafire.com/file/n95kuxerxxogexb/RPReplay_Final1729855882.mp4/file Here’s a video of the behavior, this happens on all browsers and devices from the library screen themselves.

**Comment by majora2007** [comment]
Hmm it's working for me, but I did do a bunch of fixes in that mobile actionables component, so I'll assume it fixed it.

**Comment by Cducharme84** [comment]
I do get it on desktop too, but yeah if you've worked actionables I'd not be surprised if it was resolved by proxy :)
