### ISSUE TITLE
Related Tab Scrolling

### ISSUE THREAD

**Issue by maximo1984** [Kareadita/Kavita#3239]
### What happened?

When I click the left / right button, it moves to far and you cannot click on some reading lists.

### What did you expect?

I would like an option to scroll through there with the mouse wheel if that is doable. Otherwise, the amount that scrolls through on button push probably needs to be dropped by 75%

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by maximo1984** [comment]
![Screenshot from 2024-09-28 13-27-31](https://github.com/user-attachments/assets/c87e3931-204d-42f8-aad8-1ec0e4f052a6)
![Screenshot from 2024-09-28 13-27-42](https://github.com/user-attachments/assets/34f73595-0ba0-44b5-80bc-327782df3383)

YOu can the one that is getting clipped

**Comment by majora2007** [comment]
Am I understanding correctly that on the related tab there's not enough padding on the bottom so you can't see everything?

**Comment by maximo1984** [comment]
Correct, it scrolls past some reading lists, looks like maybe 1, but could be more than 1. The top image has 1 cut off, it is next to the one on the bottom right. I thought maybe it was my browser window width, made it full screen, but its the same.
