### ISSUE TITLE
Incorrect Ordering of Single Issues by Volume

### ISSUE THREAD

**Issue by maximo1984** [Kareadita/Kavita#3244]
### What happened?

![Screenshot from 2024-10-01 08-28-31](https://github.com/user-attachments/assets/08596818-f3e2-4cca-ab57-35c5e8397a66)

All of the numbers ones are together, numbers twos, etc. They should be ordered by date and volume. I tagged these single issues using the "v1, v2" etc and also used {} instead of ()

### What did you expect?

v1 #001 - end, then
v2 #001 - end, etc

Listed in order

Not every series does this so I  have yet to determine anything on my end.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by maximo1984** [comment]
When Volumes ("v1, v2" etc) are added to reading lists. They also do not appear in order.
![Screenshot from 2024-10-01 08-33-56](https://github.com/user-attachments/assets/65d8b068-fab0-4bd0-a877-215de0f10a28)

**Comment by majora2007** [comment]
How are you creating the reading list? Bulk selecting volumes in the Series then add to reading list? 

And you're saying it's adding all of issues from vol 1 then all issues from vol 2? Because that seems to be the correct order imo.

**Comment by maximo1984** [comment]
Just double checked the actually reading lists, and they are intact, in order. It is when you click on a title and then volume that they appear out of order. And the larger issue is on the "Issues" tab they are also out of order with all of the "#" of issues together , 1,1,2,2,3,3,3 etc

**Comment by majora2007** [comment]
Then this is an already known (and fixed on nightly) issue. it's just a visual issue on the Volume detail page. 

Which issues tab? On the series detail page? I believe that should be fixed on the nightly as well.

**Comment by maximo1984** [comment]
Ok. Thanks.
