### ISSUE TITLE
Series with almost identical name are merged as one series

### ISSUE THREAD

**Issue by hstraten** [Kareadita/Kavita#3248]
### What happened?

Recently added two series to the library:
Karakai Jouze no Takagi-san
Karakai Jouze no (Moto) Takagi-san

Kavita merges these as a single series, messing up the chapters and volumes.
Only series is Karakai Jouze no Takagi-san the one with (Moto) in the title merged under the same title.

### What did you expect?

I expected both series to be a separate series

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
https://pastebin.com/LsVutrys
```

### Additional Notes

It seems anything between () is completely ignored

**Comment by hstraten** [comment]
Never mind, saw this on the naming page:
When parsing filenames, anything between () themselves will be removed from the series name.

**Comment by majora2007** [comment]
This is correct, but if you tag the series it will not combine them. The removing () is because a lot of files have (Digital) or other things in them and that would be a bad experience.
