### ISSUE TITLE
Web Links not displayed on issue page

### ISSUE THREAD

**Issue by Fesaa** [Kareadita/Kavita#3254]
### What happened?

I've added some links in the `web` field in `comicinfo.xml`; but they're not showing up in the issue page. You can find the file in the discord conversation (linked below) to reproduce if needed. 

### What did you expect?

I expected to find the links above the summary, like they would for the series page

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Mac

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

Discord conversation: https://discord.com/channels/821879810934439936/840693141082341406/1292447487902220309

**Comment by unfixa1** [comment]
Make sure the comicinfo.xml file is formatted correctly, especially in the web link section. Any formatting errors may cause the link to not be parsed correctly.
In addition, you can use the tool [servbay](servbay.com) to build a development environment to eliminate environment bugs.

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Fesaa** [comment]
Just saw this comment, in the code
<img width="605" alt="image" src="https://github.com/user-attachments/assets/b8fa1e1d-a4c1-406a-9094-03fb1cc3214a">
Does this mean it's not possible to set WebLinks via ComicInfo.xml?

I was under the impressive that it was (from the comics guide table on the wiki)
<img width="836" alt="image" src="https://github.com/user-attachments/assets/e3ac8a83-302d-4b53-84a2-8da591bcccee">

**Comment by majora2007** [comment]
This means that weblinks in the files don't populattonthe series level. This is because of comics which has different links for series and issues. 

There should be a FR to change it so manga libraries do perform the propagation. I personally have weblinks in my files but don't want it propagating as I have Kavita+ which handles the ability to open in AL for me.

**Comment by Fesaa** [comment]
Ah, I see. Then this isn't really a bug. I'll try and find the FR, and upvote it. Thanks

**Comment by majora2007** [comment]
There is still a bug here because on chapter detail page, there is no way to see the weblinks.
