### ISSUE TITLE
"No Volume.cbz" doesn't parse correctly

### ISSUE THREAD

**Issue by Kalidibus** [Kareadita/Kavita#3255]
### What happened?

Often times when I get a smaller series or web series, it will be in a file called "No Volume.cbz". Folder structure looks like this:

`Manga/`
`    "Series Name"/`
`        cover.jpg`
`        No Volume.cbz`

Rather than pick this up as "Series Name", Kavita will often add the file to a series called "No". 

I can rename the file to Volume 1 (inaccurate) or "Series Name.cbz" and that works, but I need to delete the series "No" in Kavita first or it will keep failing to read the files.

### What did you expect?

Is there a way Kavita could recognize "No Volume" and refer to the folder name like it does for "Volume #.cbz" files?

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox, Chrome

**Comment by majora2007** [comment]
This makes sense because volume is a marker. What are you trying to do? Is this a special?

**Comment by Kalidibus** [comment]
> This makes sense because volume is a marker. What are you trying to do? Is this a special?

This is how mangadex-dl automatically packages anything without serialized volume numbers. Example: https://mangadex.org/title/cf1c93cc-4bb5-4311-b926-0f02ad123ad2/imasara-desu-ga-osananajimi-wo-suki-ni-natte-shimaimashita which is designated as "No Volume".

While I can manually change the filename as a work around, doing so breaks my ability to perform updates with mangadex-dl when new chapters come out.

**Comment by majora2007** [comment]
I would recommend you raise an issue to mangadex-dl. FMD2 for example would download each as an individual chapter. Otherwise, you can manually tag this to not have a volume and have Chapter 1-X and Series Name.

I'm not sure how mangadex-dl is keeping track when everything is zipped into one archive, but none of the other tools work this way and I there isn't anything I can do on my side unfortunately.
