### ISSUE TITLE
Blank entry showing in filters

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#3256]
### What happened?

![image](https://github.com/user-attachments/assets/81630c29-4fc7-4821-8b6c-1e619d16d93b)

`<option _ngcontent-ng-c680156717="" value="12" class="ng-star-inserted"></option>`

### What did you expect?

A name of whatever said filter is. 

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by majora2007** [comment]
This was fixed somewhere in the nightly.
