### ISSUE TITLE
`Promote` and `Un-Promote` buttons not hooked up

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#3257]
### What happened?

`Promote` and `Un-Promote` buttons not hooked up when you are viewing the details of the reading list page. 

Have to go into edit --> Then turn the slider on for promote

### What did you expect?

Promotion of the reading list

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
