### ISSUE TITLE
High CPU usage and long load opening CBZ chapters

### ISSUE THREAD

**Issue by FooSoft** [Kareadita/Kavita#3259]
### What happened?

I have my manga organized as one directory per series. Each directory contains a number of CBZ files named like `vol_01.cbz` through `vol_XX.cbz`. The files contain sequentially numbered JPEGs with no metadata. Scanning the collection is fast. 

The problem happens in two situations:
1. I try to open a volume for the first time.
2. I proceed many pages into a volume (after the initial load).

I see a loading spinner and two of my cores two of my cores get pegged to 100% (running on an i7-6700). They stay at 100% for a long time (many minutes), but eventually it unblocks itself and everything works again for a while.

I don't know what Kavita is doing, but it seems like there is something unexpected going on that is causing it to do a lot more work than required to process a 50MB CBZ file. 

### What did you expect?

No long delay / high CPU usage when trying to view relatively small volumes.
![Screenshot from 2024-10-07 22-34-49](https://github.com/user-attachments/assets/f3583f79-c965-4cdf-b464-a7b83adbe3aa)

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
Nothing shows up in the logs during the stalls
```

**Comment by majora2007** [comment]
Please email/DM me a file. I've never seen that before either.

**Comment by FooSoft** [comment]
@majora2007 email sent, thank you for the quick response!

**Comment by DieselTech** [comment]
@FooSoft I took a look at the file you provided and found the following:

The archives are not zip files like the extension says, they are 7zip compressed files that are incorrectly named. 
They have LZMA2:24 compression enabled.
They are solid packed archives

All 3 of these factors are working against you when it comes to open / unpacking / decompressing them. 

The compression on the files takes CPU cycles to handle unpacking. [Solid archives](https://en.wikipedia.org/wiki/Solid_compression) means that kavita cannot just pull out a single file from the archive and send it to the client, it has to unpack the entire file first. 

If you want to avoid using a lot of CPU power, you should use "store" compression inside zip files. That will let the system unpack them very quickly without using barely any resources on the PC. If your goal is space savings, then converting the images to a better format will yield much better results than trying to compress the archive itself. 

![image](https://github.com/user-attachments/assets/508aea54-96ed-4a3f-91db-f64b25161653)


I was able to shave about 30MB off your original size by converting to web. As opposed to the ~2MB of savings by compressing the archive.

**Comment by FooSoft** [comment]
@DieselTech thanks for helping troubleshoot -- I have confirmed that storing with no compression fixes the issue on my end as well. It did not occur to me that compression would lead to a degenerate use case, but it makes sense now that I think about it.

I have created a tiny script on the off chance that someone ever needs to bulk fix their manga collection:

```python
#!/usr/bin/env python

import os
import sys
import subprocess
import shutil

def repair(cbz_path):
    print(cbz_path)
    tmp_dir = cbz_path + '.tmp'
    bak_path = cbz_path + '.bak'

    subprocess.check_call(['7za', 'x', cbz_path, '-o' + tmp_dir])
    os.rename(cbz_path, bak_path)

    files = map(lambda p: os.path.join(tmp_dir, p), os.listdir(tmp_dir))
    subprocess.check_call(['zip', '-j', '-0', cbz_path] + list(files))

    shutil.rmtree(tmp_dir)
    os.remove(bak_path)

def main(scan_dir):
    for root, dirs, files in os.walk(scan_dir):
        for f in files:
            if os.path.splitext(f)[1] == '.cbz':
                repair(os.path.join(root, f))

if __name__ == '__main__':
    main(sys.argv[1])
```
