### ISSUE TITLE
Scanner grouping unrelated folders into same series

### ISSUE THREAD

**Issue by KobraKid** [Kareadita/Kavita#3264]
### What happened?

My library folder structure is as follows:

/manga/EN/<Author>/<Series>
![image](https://github.com/user-attachments/assets/08d24ae7-e34d-42cc-8b4e-3414aa761032)

When scanning my library (which has a root folder of "/manga/EN"), all series in the author's folder are grouped together.
I used Manga Manager to set the Series and LocalizedSeries in the ComicInfo.xml for each .cbz in the Series folder.
![image](https://github.com/user-attachments/assets/17178a3a-0c9e-4233-a7bd-99be0a0270cd)
![image](https://github.com/user-attachments/assets/a065e239-cb50-4883-ad2c-8ecb422709a0)

For some reason, the scanner things the series folder path should be at the author level:
![image](https://github.com/user-attachments/assets/ff183988-cd5d-4948-9a10-f3d38ba616a5)

![image](https://github.com/user-attachments/assets/2df6d7ae-a3c3-4f44-ab22-fe5c493362a5)

### What did you expect?

From what I've read on the wiki, my folder structure file naming scheme, and comicinfo files should be sufficient to keep these as separate series. Nothing would indicate to me that these are the same series, so I would expect them to be kept separate.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
2024-10-08 14:38:10 kavita  | [Kavita] [2024-10-08 19:38:10.933 +00:00  121] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 473 files for /manga/EN/OSHIMI Shuzo
2024-10-08 14:38:16 kavita  | [Kavita] [2024-10-08 19:38:16.057 +00:00  121] [Error] API.Services.Tasks.ScannerService [ScannerService] There are multiple series within one folder that contain localized series. This will cause them to group incorrectly. Please separate series into their own dedicated folder or ensure there is only 2 potential series (localized and series):  Avant-garde Yumeko, Blood on the Tracks, Devil Ecstasy, Drifting Net Café, femme fatale - The Art of Shuzo Oshimi, The Flowers of Evil, Inside Mari, Shino Can't Say Her Name, Sweet Poolside, Welcome Back, Alice
```

**Comment by majora2007** [comment]
This is indeed weird, what is the series they are both grouping into?

**Comment by KobraKid** [comment]
They're grouping into the first one - Avant-garde Yumeko

**Comment by KobraKid** [comment]
I'm stepping through the code, and it looks like in `API.Services.Tasks.Scanner.ParseScannedFiles.ScanDirectories()` the folder "OSHIMI Shuzo" is not detected as containing multiple series. I would expect `seriesPaths` to be populated, and to enter the `else if` block here:
![image](https://github.com/user-attachments/assets/1aee5535-5c18-4c2b-b626-0969eac256e1)
but initially `seriesPaths` is empty and the code falls into the `else` block. This makes it treat all files within the "OSHIMI Shuzo" folder as part of the same series during `API.Services.Tasks.Scanner.ParseScannedFiles.MergeLocalizedSeriesWithSeries()` - before the merge, the two parsed files have distinct `LocalizedSeries` values:
![image](https://github.com/user-attachments/assets/57a8ccc7-7a30-4ab9-ad98-6871b7dfb5a2)

On subsequent scans, `API.Services.Tasks.Scanner.ParseScannedFiles.ScanDirectories()` has a populated `seriesPaths`, however now the series has a folder path of "[...]/OSHIMI Shuzo" instead of "[...]/OSHIMI Shuzo/Avant-garde Yumeko" because `API.Services.Tasks.Scanner.ProcessSeries.UpdateSeriesFolderPath()` is experiencing a bug where the FolderPath is one level higher than it should be:
![image](https://github.com/user-attachments/assets/cb16b8eb-1d56-4a6b-bdd8-ee2a709e2bf9)

-- 
I'm also noticing that `API.Services.Tasks.Scanner.ParseScannedFiles.MergeLocalizedSeriesWithSeries()` checks if the `nonLocalizedSeriesFound.Count` is >2, but shouldn't it be >=2? Otherwise this wouldn't catch the case where there are exactly two distinct series in a folder.

**Comment by KobraKid** [comment]
I think I've determined the root cause. `API.Services.Tasks.Scanner.ParseScannedFiles.MergeLocalizedSeriesWithSeries()` calls this out in a comment: 

    // NOTE: If we have multiple series in a folder with a localized title, then this will fail. It will group into one series. User needs to fix this themselves.

Removing the LocalizedSeries tag from the ComicInfo on every .cbz in the folder will work around the issue. However, I don't think that's an appropriate "solution" - users should be able to have series subfolders in the same root folder regardless of whether the LocalizedSeries tag is present.

**Comment by majora2007** [comment]
This is fixed in the upcoming release (note to me to tag it for release notes).

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by majora2007** [comment]
Kavita v0.8.4 is released and should fix this issue. Please validate.
