### ISSUE TITLE
The manga volume is labeled as 'special' on the volume details page

### ISSUE THREAD

**Issue by newyorker123** [Kareadita/Kavita#3269]
### What happened?

For any manga volume that is not marked as special, it is still labeled as 'special' on the volume details page. I'm not sure whether this is by design or a bug. Why isn't it labeled as 'Volume xxx,' as it is on the series details page?

Another issue on the volume details page is the 'Chapters' tab. For a single volume file (e.g., 'vol.x.cbz') that doesn't consist of multiple 'vol.x ch.yy.cbz' files, it would be better to have a 'Volume' tab instead of a 'Chapters' tab.

![image](https://github.com/user-attachments/assets/28d83df8-6229-4794-950f-bf5825467bef)

### What did you expect?

Change "special" to "Volume xxx"

Change "Chapters" tab to "Volume" tab.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by scare376** [comment]
Because it's meant to hold chapters there if there is no chapter indicator it defaults to special. It doesn't make sense to have it say volume there on the volume details page. That's just duplicate information. I could see having a volume title there if it exists but manga rarely has individual volume titles.

**Comment by newyorker123** [comment]
> Because it's meant to hold chapters there if there is no chapter indicator it defaults to special. It doesn't make sense to have it say volume there on the volume details page. That's just duplicate information. I could see having a volume title there if it exists but manga rarely has individual volume titles.

I understand why it's designed this way, but it just looks really weird and confusing for a volume that doesn't consist of external chapters.

**Comment by scare376** [comment]
If you think about it technically a volume release is a "special" as it is a compilation of chapters. Usually with an extra short story included

**Comment by majora2007** [comment]
I'm open to some more suggestions. It's a tough issue because `special` is confusing 100% but the actual card has to be there to allow you to edit the individual metadata that makes up the Volume and you still need the Volume edit to set the Volume cover (which is something komf users have asked for a lot).

**Comment by SleepingPanda** [comment]
@majora2007 is there no way to indicate that a volume contains chapters 5-10 of manga? or issue 82 to 95 of a comic? I imagine this would clear up a lot of issues concerning volumes, TPBs and etc.

**Comment by majora2007** [comment]
> @majora2007 is there no way to indicate that a volume contains chapters 5-10 of manga? or issue 82 to 95 of a comic? I imagine this would clear up a lot of issues concerning volumes, TPBs and etc.

Realistically no. While you can put the chapter information in the ComicInfo and Kavita would render that out, in practice that information is not available.

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by majora2007** [comment]
I found a better way to handle this
![image](https://github.com/user-attachments/assets/b08557c4-56b9-494c-b186-e0edec4e0616)
