### ISSUE TITLE
wrong sort order for decimal number on volume detail page

### ISSUE THREAD

**Issue by newyorker123** [Kareadita/Kavita#3270]
### What happened?

Chapter X.5 always appears before Chapter X on the volume detail page.

I noticed that the ordering issue is reported in #3214, but I only see cases involving integers. I just wanted to remind you that it also occurs with decimal numbers. I'm not sure if the fix addresses this as well.

![image](https://github.com/user-attachments/assets/181ccf06-1dbe-40e1-831e-ec47cdd16b9d)

### What did you expect?

correct order

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by majora2007** [comment]
This is a visual bug on volume-detail page that will be fixed in v0.8.4. The fix linked works for everything.
