### ISSUE TITLE
Child account can change age rating.

### ISSUE THREAD

**Issue by blissd** [Kareadita/Kavita#3274]
### What happened?

One of my children has an age restriction set to "Teen" and I've configured their account so the permission for them to change their age restriction is absent, but they are able to go to their settings and set the age restriction to whatever they want and view age inappropriate items.

### What did you expect?

Child should not be able to change their own age restriction.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Safari

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Safari

**Comment by majora2007** [comment]
You are correct, this looks like an oversight or likely just a bug coming from the big UX update. I'll prioritize this for the next stable.

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
