### ISSUE TITLE
Cant put any Recurring Tasks on Custom Cron

### ISSUE THREAD

**Issue by impishlucy** [Kareadita/Kavita#3276]
### What happened?

I try to edit an Recurring Task and want to have it use a cronjob timer instead of every day.
If i try to select Custom it shows the both fields for 20ms and then it resets to just the time selection, but the time beeing empty.
A Video showing what i mean is in your dms (from Elry).

### What did you expect?

That i can enter the Cronjob timer.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by impishlucy** [comment]
@DieselTech can you ban this virus bot from the repo thanks

**Comment by DieselTech** [comment]
I'm still seeing this issue after the bugifx release. Once custom cron is selected I can't change to anything else. 

Sidenote: When custom cron is selected and no cron is defined, it seems to still scan daily at 00:00.
