### ISSUE TITLE
Username already taken, if email is the same

### ISSUE THREAD

**Issue by impishlucy** [Kareadita/Kavita#3280]
### What happened?

Im not using the Emails so i decided to just set the Username and Email the same for my Friends (I myself was using localhost as email), but now they get an error "Username is already taken", even tho its not i checked.
After changing the email to local-marika, my Friend could then use the username Marika. Seems like the Username box is checking the email field ?

### What did you expect?

That the email field doesnt affect the username at all.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### Additional Notes

![image](https://github.com/user-attachments/assets/a3f1d378-e17b-42cb-9088-320334aa5a97)

**Comment by scare376** [comment]
I am not seeing this behavior on nightly. Created an account with the username test and email test with no issue.
