### ISSUE TITLE
Active online Users is merged with the Task Symbol

### ISSUE THREAD

**Issue by impishlucy** [Kareadita/Kavita#3281]
### What happened?

The active online user count is merged with the task symbol, this is unintuative and confused me multiple times when i looked what task could be running only to see "no current tasks".
![{7273E9D9-316D-49CF-8AC5-AFEA866D2C71}](https://github.com/user-attachments/assets/eb2cf6aa-6a6e-4e9a-9fcf-7aaa8e1c7cf3)

### What did you expect?

The active user count should be a seperate Icon to avoid confusion
![{4FC35ADF-E3E2-44EE-B955-321FA1039AB2}](https://github.com/user-attachments/assets/1b4b76c8-a226-49c7-9a60-8d587a0f9905)

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome

**Comment by impishlucy** [comment]
Upon clicking on the user icon you get a small popup like with the task and see which users are online

**Comment by scare376** [comment]
This shouldn't be an issue and instead a discussion as that is where feature requests go

**Comment by impishlucy** [comment]
This is not a feature request tho, this is visual unclarity and should count as a bug
