### ISSUE TITLE
Volume name when mouseover

### ISSUE THREAD

**Issue by silic1** [Kareadita/Kavita#3285]
### What happened?

Doesn't show volume name when mouseover.

![kavita_volumename2](https://github.com/user-attachments/assets/544cbb90-09cf-4587-bd7f-e330adaab126)
![kavita_volumename1](https://github.com/user-attachments/assets/0fba63b9-9eeb-49ef-9197-20bd367e3bb9)

### What did you expect?

Show volume name when mouseover.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by saitoh183** [comment]
I would like to add to this to add the volume number under the name and not just mouse over
