### ISSUE TITLE
Special shows -100000 as title

### ISSUE THREAD

**Issue by jncmney** [Kareadita/Kavita#3287]
### What happened?

On ComicVine library type, a Series has 11 issues and 4 Specials.

One of the Specials displays -100000 for title even though the file has a title in the ComicInfo.xml. 

Another one of the Specials displays 1985 as title even though the title is different in the ComicInfo.xml.

**Example 1:**

Filename: "Calvin and Hobbes Complete Collection Exploring Calvin and Hobbes An Exhibition Catalogue (2015) SP01.cbz"

![image](https://github.com/user-attachments/assets/e16f7097-0540-480b-b50d-7dabd6e985f1)

![image](https://github.com/user-attachments/assets/86843154-9776-459c-b613-24bfa2e9715d)

**Example 2:**

Filename: "Calvin and Hobbes Complete Collection Calvin and Hobbes Sunday Pages 1985-1995 (2001) SP01.cbz"

![image](https://github.com/user-attachments/assets/f3bb1aaf-ff2c-49f8-b4d7-bf6175f11ac2)

![image](https://github.com/user-attachments/assets/69953d0f-6b27-4ded-a8b3-b252be00b5c0)

### What did you expect?

The Titles from the metadata in the ComicInfo.xml file to show in Kavita properly

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Mac

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Safari

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Safari

### Additional Notes

Running Kavita on Docker with this image: image: jvmilazz0/kavita:latest

**Comment by jncmney** [comment]
I should've included the file structure in case it's relevant since you're working on improvements to the Publisher structure:

Inside .../media/comics I have:

- Publisher (folder)
   - Series (folder)
       - Issue 001 (file)
       - Issue 002 (file)
       - ...
    - Specials (folder)
       - Special Issue (file)

In the case above it's:

.../media/comics/Andrews McMeel Publishing/Calvin and Hobbes Complete Collection/Specials/Calvin and Hobbes Complete Collection Exploring Calvin and Hobbes An Exhibition Catalogue (2015) SP01.cbz

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
