### ISSUE TITLE
Download option from the "On Deck" menu does not initiate a download

### ISSUE THREAD

**Issue by TheFlemoid** [Kareadita/Kavita#3291]
### What happened?

When at the "On Deck" menu, selecting the "Download" option from the menu on a books title card does not initiate a download.  From a quick inspection of browser network traffic, this option does not appear to make a network request at all.  Download options in other areas of the UI work as expected.

This is the download selection that does not appear to do anything:

![Not_Functioning_Download_Option](https://github.com/user-attachments/assets/d639f0c8-34e2-4ff7-a0e0-cdd1bb139920)

Other download selections, such as the two shown below, behave as expected:

![Functioning_Download_Option](https://github.com/user-attachments/assets/a172d48e-1bf2-4a75-a10a-1db09418a278)

![Other_Functioning_Download_Option](https://github.com/user-attachments/assets/29f0e581-4bb4-4971-92c2-fabacbf10284)

### What did you expect?

Selecting the "Download" option from the "On Deck" menu should initiate a download of the selected title.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox

### Additional Notes

Running Kavita as a Dockerhub container.  Docker itself is being run on a headless Ubuntu 22.04 VM.

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
