### ISSUE TITLE
Chapters from PDF aren't working

### ISSUE THREAD

**Issue by DoodleCup** [Kareadita/Kavita#3313]
### What happened?

The Chapters from a PDF File aren't working. If i click on the chapters nothing happens. When i open the raw PDF on Browser its working.

### What did you expect?

Jumping to the chapter i clicked on

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
This bug report needs more context for me to help you. I just tested a bunch of PDF stuff for another issue and everything looked fine. Please add more information like steps to reproduce and potentially issues to help me understand.

**Comment by DieselTech** [comment]
No information was ever provided when asked, closing.
