### ISSUE TITLE
Issues/chapters show “-“ rather than issue number or title

### ISSUE THREAD

**Issue by Cducharme84** [Kareadita/Kavita#3320]
### What happened?

![IMG_0692](https://github.com/user-attachments/assets/3e8a2efe-514c-495b-a7ad-fae906cee772)
On the individual chapter/issue cards the above display is happening in the newest nightly.

### What did you expect?

Either title display or if not title “Issue 1” etc

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by rix8675** [comment]
encountered this one last night
