### ISSUE TITLE
Chapter title mistakenly becomes Volume title

### ISSUE THREAD

**Issue by newyorker123** [Kareadita/Kavita#3327]
### What happened?

The current implementation of Kavita inherits volume metadata from its underlying chapter metadata. This works well when the volume is a standalone file, since the volume and chapter are the same thing.

However, when a volume consists of multiple chapter files, the volume mistakenly treats the title of the first chapter as the volume-level title. Similarly, the first chapter would mistakenly consider a volume title as its own title when only the volume title is intended.

The title, which is supposed to be just a chapter title, also becomes the volume title.
![image](https://github.com/user-attachments/assets/d716cd70-0058-45ef-95e0-771de983b4a3)

### What did you expect?

Although most of the time, volume metadata is the same as that of the constituent chapters, it is very common for a volume to have a title while each chapter has its own title. Therefore, despite inheriting metadata from the underlying chapters, a volume should have its own metadata (title at least, maybe summary also), which takes precedence when displaying information on the volume detail page.

This will fix the above bug and allow for independent configuration of volume-level metadata and chapter-level metadata.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
I don't consider this a bug, but it's fine to leave here. You will need to give documentation of examples where the volume name is different than the underlying chapter title and how you expect it to work.

**Comment by newyorker123** [comment]
The first example is "金田一少年の事件簿 File". The chapters have title "xxx①",  "xxx②", etc, while the volume title is just "xxx". Now that I give the first chapter the tittle "xxx①", it automatically become the volume title too. But how do I get rid of the "①" in the volume title? This is exactly the issue I mentioned above, and I’m not sure how to fix it.

<img src="https://github.com/user-attachments/assets/ee5987dd-bd8a-466c-8d58-08e801413a75" width=60%>

---

Another case is with two-volume manga, which often have volume titles like "xxx 上", “xxx 下”. For example, take a look at [タコピーの原罪](https://bookwalker.jp/series/340881/list). 

<img src="https://github.com/user-attachments/assets/275e7445-78e3-4519-a968-36ba842ee2d7" width=60%>


In these cases, the chapter titles are different. Check the table of contents below:


<img src="https://github.com/user-attachments/assets/57ed1b05-30fe-4d61-8a45-b0a4abaf88c9" width=50%>


---

For manga where the volume and chapter titles are more distinct, look at [伊藤潤二傑作集](https://bookwalker.jp/series/5093/list/). Each volume has its own title.

<img src="https://github.com/user-attachments/assets/76d278c5-2630-4e47-b0b4-b20dca16934d" width=110%>

For instance, volume 8 has title "うめく排水管", but the first chapter title is "超自然転校生".

<img src="https://github.com/user-attachments/assets/891e7e46-26fa-402a-9050-6ee25125cea2" width="60%">

---

I hope this clarifies the need to support separate titles for volumes and chapters.

Essentially, I’d like the relationship between volumes and chapters to work more like the relationship between series and volumes. Even though a series is a container for volumes, you can still edit the series title and volume titles separately. I’d like that same flexibility between volumes and chapters. Currently, you can’t edit anything for volumes—they just inherit everything from the underlying chapter.

**Comment by majora2007** [comment]
This doesn't help me much because it's all in Japanese, so I can't fully grasp. What you want requires a huge effort is the problem, hence why this should be best for a Feature Request as I would need the community to upvote to help me understand if it's worth the effort of coding and maintaining. 

In my honest opinion, it's not. Most people do not tag the chapters within a Volume to start or even Volume names. You are an edge case (as there is not good metadata sites to get this from) and reworking a core of Kavita to support an edge case doesn't make much sense to me. 

Please create a Feature Request with as much information to help others see your point and link it to this issue. I'm going to close the issue for now.

**Comment by newyorker123** [comment]
Well, I’m directly showcasing Japanese content since I’m talking about the Manga Library type, which is meant to feature Japanese works.

I understand it requires a lot of effort and isn’t the top priority right now. I’ll figure out how to manage without this feature. Thanks for your explanation anyway.

**Comment by newyorker123** [comment]
On second thought, I still believe it’s a bug. Please let me try one last time to show you.

1. You can merge chapter files into a volume by naming them “Series Name Vol.01 Ch.1,” etc. This is officially supported and documented in the wiki.
2. The title metadata is also officially supported. Chapter titles display on the chapter card, and volume titles display on the volume detail page.

However, if you use both of these features together, the titles inevitably get mixed up.

If you want only a volume title, that title will still be treated as a chapter title and will display on the chapter card for the first chapter in the volume. On the other hand, if you want only chapter titles, the title of the first chapter will automatically become the volume title and display on the volume detail page. Not to mention having separate titles for both.

The problem is that Kavita system just can’t distinguish between chapter and volume titles in this case, and **it forces the title to function as both.**

In my opinion, the merging chapters feature and title metadata feature don’t really work together. Once you use merged chapters, the title metadata won’t work properly, no matter what you’re aiming for. Maybe tagging every chapter is an edge case. But what about using merged chapters and also want to have a volume name? The two features conflict logically, which is why I think it’s a bug, not just an enhancement request.

That said, I understand if you don’t see it as a priority to fix, since it requires a core rework. Kavita is an amazing piece of software, and that’s why I’m sticking with it and hope to help make it even better. Thank you for all the hard work!

**Comment by majora2007** [comment]
Kavita doesn't support metadata only for the volume level, this is why it's a feature request. It was never designed that way. I'm not saying it's not a valid request or feature for Kavita, but I don't think of this as a bug and if we leave it as a bug, there is very low probability it will get implemented. 

However when I see community engagement, it helps push big pieces of work. Like the comic rework that took me hundreds of hours reworking Kavita's foundations.

So please open a feature request and if we get community engagement I can consider it.
