### ISSUE TITLE
User rating filter doesn't work

### ISSUE THREAD

**Issue by DireMunchkin** [Kareadita/Kavita#3335]
### What happened?

I'm seeing several issues with user rating filter:
- Filtering all books less then or equal to 100% yields no results, when it should be all books per definition.
- Greater than also doesn't seem to work right, I.E greater than 80% also returns a book with 60%. 
- Equal to never yields any results.

### What did you expect?

I'd expect a mathematically correct numerical comparison on the rating to be applied.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Other (List in "Additional Notes" box)

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

I'm using LibreWolf browser (which is mostly identical to Firefox).

This sounds similar to the bug in https://github.com/Kareadita/Kavita/issues/3154 which was supposedly already fixed.

**Comment by DireMunchkin** [comment]
Ah, one more thing - I saw now that that the old bug is for Smart Filters, whereas where I saw this issue was in Library > Filter.

**Comment by majora2007** [comment]
Took a look at this and you're right, it's completely broken. Not sure what happened with that last bug, but essentially Kavita stores user ratings as 0-5 (decimal). 

The metadata filter takes a percentage for some reason, where-as it should be 0-5 to make it much easier and more consistent.

**Comment by majora2007** [comment]
![image](https://github.com/user-attachments/assets/fdb1f3bd-b542-4a9c-b3f2-c883d1d32a9d)

I think this will work better. While yes we display a percentage on the UI, that is because if other users rate, Kavita will average their rating + yours. 

Taking a percentage will lead to rounding issues and translation issues. This is a stop gap solution, I'm 100% open to an alternative if anyone can think of one.

**Comment by DireMunchkin** [comment]
Hey, thanks for taking a look.

I don't really have a strong view on 1-5 vs 0-100% in the UI. Either or is fine by me.

Normalizing the rating to a integer value for the comparison would make sense to me - Then you don't have problems with rounding or floating point equality or such.
