### ISSUE TITLE
Slow page loading with firefox behind caddy reverse proxy

### ISSUE THREAD

**Issue by ailelix** [Kareadita/Kavita#3338]
### What happened?

I have kavita installed on my home server and use wireguard to access my server outside home  
And I use caddy with self-signed certificates to reverse proxy my selfhost services  

However, when I watch `.cbz` mangas, the page loading is SLOW in firefox  
I tried accessing kavita directly and the page loading is normal.  
I also tried edge with caddy reverse proxy and page load is fast  
So I guess there is something wrong between caddy and firefox  

Here's my server setup:  
> AMD Ryzen 7 5800X
> DDR4 16G 3200Mhz RAM
> Arch Linux with linux-lts kernel
> Kavita 0.8.3.2-1 from AUR
> Caddy 2.8.4

Here is my kavita `appsettings.json`:
`172.24.233.1 is my server's IP in wireguard`  
```json
{                                                                                                                                                                   
"TokenKey": "...",
"Port": 25600,
"IpAddresses": "127.0.0.1, 172.24.233.1",
"BaseUrl": "/",
"Cache": 128,
"AllowIFraming": false
}
```
I also set hostname in `Settings`>`General`>`Networking` to  `https://comic.nas.alx` 

Here is my caddyfile setup:
```Caddyfile
(tls-alx) {
    tls ...nas.alx.crt ...nas.alx.key {
        ca_root ...ca.crt
    }
}
comic.nas.alx {
    import tls-alx
    encode gzip
    reverse_proxy :25600 {
        header_up X-Forwarded-Host {host}:25600
        header_up -Origin
        header_up -Referer
    }
}
```

### What did you expect?

I expect the page loading speed to be normal  
However I haven't seen anything sus in neither firefox's dev console nor caddy's log  
So hopefully this issue could be solved  

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
This is not something I can support you with. You are free to join our Lounge in discord to ask the community or reddit, but this doesn't belong as a bug report.
