### ISSUE TITLE
Unable to open mangas in Firefox only

### ISSUE THREAD

**Issue by soodoh** [Kareadita/Kavita#3339]
### What happened?

When using Kavita in Firefox, opening my manga/comics library (all using CBZ format) does not work through all possible flows (see images). It also doesn't work for starting a new series with no progress.
<img width="175" alt="Screenshot 2024-11-03 at 3 57 58 PM" src="https://github.com/user-attachments/assets/bf84f8ed-73cd-4e33-97c7-f208d02d3768">
<img width="514" alt="Screenshot 2024-11-03 at 3 58 18 PM" src="https://github.com/user-attachments/assets/dc655ece-67e7-4078-a15e-ffde76e45e7c">

What's interesting here is that I am only seeing this behavior for manga in Firefox. Reading epubs seems to work as expected in Firefox. And reading either format works without issues when using Chrome.

When opening the console, I see the following error log for every click when trying to open a manga in Firefox.
`ERROR SyntaxError: missing } in compound statement`
<img width="1494" alt="Screenshot 2024-11-03 at 4 01 12 PM" src="https://github.com/user-attachments/assets/91ae2c1e-6407-464b-b1d3-9cb1ca639b31">

### What did you expect?

I would expect the manga to open when using Firefox.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Mac

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
ERROR SyntaxError: missing } in compound statement
```

**Comment by corrosive4354** [comment]
The error message in the console indicates that there may be a problem with the JavaScript code. You can try to look at the Kavita code, especially the part related to comic opening, to confirm whether there are any syntax errors.

Seeing that you are using Docker, I would like to recommend Servbay to you, which is more professional and easy to use than Docker on Mac.

**Comment by majora2007** [comment]
I've seen this issue before, can you do a hard refresh on FF and see if that fixes the issue?

**Comment by soodoh** [comment]
Wow, that fixed it. I should have thought to try that first. Thanks!
