### ISSUE TITLE
Deleting libraries via 3-dot menus does nothing

### ISSUE THREAD

**Issue by Nebelherr23** [Kareadita/Kavita#3342]
### What happened?

I'm currently trying various eBook directory layouts, in the course of it I realized the delete options in the 3-dot menus does nothing.

Steps to reproduce:
* click any 3-dot menu associated to libraries
* select delete
* nothing happens

The deletion only works via the settings -> Library view.

### What did you expect?

The deletion should happen

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome, Other (List in "Additional Notes" box)

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android 14

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox, Chrome

### Additional Notes

Additional browsers: Opera, LibreWolf (Firefox fork)

**Comment by majora2007** [comment]
I need to know the pages it doesn't work or at least the URL paths.

**Comment by scare376** [comment]
There's also 2 different menus. The normal one appears off the button. The mobile one will appear in the center of the screen. Can you specify which menu.

**Comment by majora2007** [comment]
> There's also 2 different menus. The normal one appears off the button. The mobile one will appear in the center of the screen. Can you specify which menu.

Just for reference, they are both the same handler, so it shouldn't matter.

**Comment by Nebelherr23** [comment]
The one on top of any `/library/` and basically any library in the `SideNav` element.

**Comment by DieselTech** [comment]
Confirmed this isn't working from the sidenav.
