### ISSUE TITLE
UI Console Error: Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#3343]
### What happened?

When just doing basic navigation around the site or even sitting on a page not touching anything for a few minutes I see errors coming up in the browser console. I do NOT see any errors in the kavita logs. 

### What did you expect?

.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

**Comment by majora2007** [comment]
Can't seem to reproduce this. I navigated around, left the browser idle for a few hours, no errors ever popped up.

**Comment by DieselTech** [comment]
I did more digging and this ended up being caused by a 3rd party extension. Even though TamperMonkey didn't have an active script loaded (komf), it was causing the error to happen only on kavitas page.
