### ISSUE TITLE
Volume Detail Page does not show issues correctly

### ISSUE THREAD

**Issue by moisesbelda** [Kareadita/Kavita#3360]
### What happened?

I have the following folders and files structure ( ellipsis dots means that it is a large list of files): 
- (folder) BATMAN
-- (folder)DETECTIVE COMICS VOL1
---DETECTIVE COMICS VOL1 - 034.cbr
---DETECTIVE COMICS VOL1 - 035.cbr
---DETECTIVE COMICS VOL1 - 036.cbr
--- .........
-- (folder)DETECTIVE COMICS VOL2
---DETECTIVE COMICS VOL2- 500.cbr
---DETECTIVE COMICS VOL2- 501.cbr
---DETECTIVE COMICS VOL2- 502.cbr
--- ........

After analysing the library, I found some issues how the comics are displayed:
- There is a Detective Comics item created (series) => Good
- Inside there in tab Volumes, there are 3 items created as volumes: 
--- 3 expected volumes: Volume1, Volume2, Volume3 => Good

When I click on the volumes:
- Volume 1:  Inside there is a single item  "Issue#1"  with a small box with a number of comics (526) which I think is the number of comics within the volume.. If I click on it to read, it seems that is opening something big (maybe all files merged?) because the loading never ends.  There is no way to access from here to the full list of comics inside Volume 1.
- Volume 2:  Inside there is a single item "Issue#2" with same small box with number of comics (56) . If I click on it to read, it happens the same ... it seems that is opening something big.
- Volume 3  : Same behaviour than Volume 1 and 2.

Inside issues tab, there is the list of the items that I described inside each volume

### What did you expect?

I expect the following : 
Volumes : only volumes related to the prefixes I set in the list of my file structure ( VOL 1, VOL 2, VOL 3).
Inside Volumes : when I click on a volume, I expect the list of issues within the volume, not a single big item.
Issues : All single comics, no compiled big  items.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Mac

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome, Safari

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Additional Notes

In case it helps, this weird grouping seems to be happening in the analysis of the comics in the versions I tested (0.8.3.2 and 0.8.3.4 nightly). 

Some comics (which were scanned with 0.8.2.0) with same file and folders structure are displayed correctly, so it seems a problem of the scanning.

**Comment by majora2007** [comment]
What Library type are you using? Comic or Comic Vine?

**Comment by moisesbelda** [comment]
Comic

**Comment by moisesbelda** [comment]
I've just noticed that : 
"--- 2 non expected voumes: Volume 1937, Volume 2016, => Wrong"
This is not an issue. These strange volumes were created due to a comicinfo.xml inside some comics (not all). So this case is the expected case., so apologies to report it as issue. Im going to remove this part in the description of the issue above.

The pending issue is why the Volumes 1,2,3 are created with a single item inside, which seems to open the full list of comics int he volume with all pages all together (actually it never load fully).

**Comment by moisesbelda** [comment]
In order to help in the investigation, could you let me know if there is any expected case that produces in volumes tab details a single big issue item (with all pages merged of different files of the same volume) related to files with same volume prefix : series vol1 - 01.cbz, series vol1 - 02.cbz etc..? or is it a bug?

**Comment by majora2007** [comment]
@DieselTech can you provide any support on this? I'm pretty slammed with release work.

**Comment by DieselTech** [comment]
Now that the main post has been edited I am even more confused now.  We are likely going to need screenshots to understand what is showing up and where. 

I think the problem here is your expecting something that kavita doesn't really do.

```
I expect the following :
Volumes : only volumes related to the prefixes I set in the list of my file structure ( VOL 1, VOL 2, VOL 3).
```

The basic "comic" library type doesn't have a lot of options and would combine series that had the same names together. That is why the "comicvine" library type was created. So metadata (comicinfo.xml) can define how people want the series to show up in their library. My suggestion would be to add more metadata to your files if anything, not removing the `comicinfo.xml`'s

**Comment by moisesbelda** [comment]
All my series has the following file structure : 
(folder) BATMAN
-- (folder)DETECTIVE COMICS VOL1
---DETECTIVE COMICS VOL1 - 034.cbr
---DETECTIVE COMICS VOL1 - 035.cbr
---DETECTIVE COMICS VOL1 - 036.cbr
--- .........
-- (folder)DETECTIVE COMICS VOL2
---DETECTIVE COMICS VOL2- 500.cbr
---DETECTIVE COMICS VOL2- 501.cbr
---DETECTIVE COMICS VOL2- 502.cbr
--- ........

This serie was scanned with kavita 0.8.2.0 and is working as I descrbied :
1.- 2 volumes
<img width="551" alt="image" src="https://github.com/user-attachments/assets/1861abee-547f-42bc-a3e6-087c37048032">
2.- If I click on one of the volumes, a list of all the issues of the volume I clicked on is displayed , so I can go to any specific issue within the volume : 
<img width="732" alt="image" src="https://github.com/user-attachments/assets/09b229b4-6e88-42a4-97de-b1c1751a3d4b">
 
In the other hand, the series I analysed with kavita 0.8.3.2, has the same file structure, but it is not working in the same way:
1.- Volumes displayed ok
<img width="538" alt="image" src="https://github.com/user-attachments/assets/a44fc888-c3a1-4e93-a868-3657b3557d36">
2.- If I click on one of the volumes, this screen appears with just one single item, with a green number (52) which is the number of issues of the volume. As you can see, the item has 1.6k pages, so I assume that all the issues seems "merged" in one, and when I click to read, it tryes to open a super big comic which I think has all pages.
<img width="610" alt="image" src="https://github.com/user-attachments/assets/2c137336-ed59-4eaf-9fda-a35431dfd190">
3.- If I click on read it never ends:
<img width="595" alt="image" src="https://github.com/user-attachments/assets/0bafec6d-7017-4a62-a988-92c42ac0068b">

Therefore, I think that what I expect is supported by kavita since the volumes and issues within are displayed correctly in all the series I scanned in previous versions of Kavita(or maybe Im doing something wrong?). 

Thanks and Regards.

**Comment by majora2007** [comment]
> d in previous versions of Kavita(or maybe Im doing so

Okay I understand what you are reporting finally. You're saying that volume detail page in the UI is not showing the issues as separate cards. 

I can look at that.

**Comment by moisesbelda** [comment]
Yes @majora2007 , but, take into account that I have on my collection , at the same moment, other series/volumes that are displayed correctly. So IMHO, it  seems also related to the analysis process, because other series/volumes analysed with a previous version of kavita are displayed correctly (screenshots provided are from my current collection, both wrong and right screenshots).

**Comment by majora2007** [comment]
Yeah I just tried to reproduce and it's working as expected, but due not, I'm testing on the new scanner. For now, let's wait until v0.8.4 and retest then. I rewrote the scanner and a lot changed to bring about stability.

**Comment by moisesbelda** [comment]
Just to try....Is the new scanner incorporated in the new [nightly-0.8.3.28]?

**Comment by majora2007** [comment]
Yes, but you will not be able to roll back. We are very close to v0.8.4, I just pushed out my 5th polish release. 

I would advise you to setup a small test container to try it and not update your main, as you will not have release notes to understand all the changes and actions required.

**Comment by moisesbelda** [comment]
There is no prob, I have multiple kavita containers to play/test.

**Comment by moisesbelda** [comment]
Tested with [nightly-0.8.3.29:
- Reduced the number of issues and volume (1 volumen, 7 issues) to make easier the test
- I've removed the entire library and added again from scratch
- This is my folder list (exactly):
<img width="518" alt="image" src="https://github.com/user-attachments/assets/95774ba9-726a-4626-9f84-a28f0a0b4dc1">

- Same result, one issue card with all comics within :(

Could it be something related to the files?

**Comment by majora2007** [comment]
I would say, let's look at the internal metadata next to understand why it might show this way. I tested without any internal metadata and your filename. 

To quickly test without metadata, rename the cbz -> zip and Kavita wont look for metadata within the files.

**Comment by moisesbelda** [comment]
From the very begining I've checked the files with ComicTagger to ensure no tags or metadata, and I extracted all contents of the files to check there is no file except the images.

But, in any case, I did your test. Same wrong results.

<img width="523" alt="image" src="https://github.com/user-attachments/assets/9d401445-3a64-4548-baba-b0045edf28a0">

**Comment by majora2007** [comment]
Can you run this script for me and send me the json file? 

```python
import os
import json


def map_files(root_dir):
    files_map = []

    for dirpath, dirnames, filenames in os.walk(root_dir):
        # Skip directories that start with "."
        dirnames[:] = [d for d in dirnames if not d.startswith('.')]

        for filename in filenames:
            # Skip files that start with "."
            if not filename.startswith('.'):
                # Get the relative path of the file
                relative_path = os.path.relpath(os.path.join(dirpath, filename), root_dir)
                files_map.append(relative_path)

    # Export the map to a JSON file
    with open('files_map.json', 'w') as outfile:
        json.dump(files_map, outfile, indent=4)


if __name__ == "__main__":
    root_dir = os.getcwd()
    map_files(root_dir)
    print("File map generated and saved to files_map.json.")
```

**Comment by moisesbelda** [comment]
Done. Attached.
[
[files_map.json](https://github.com/user-attachments/files/17753846/files_map.json)
](url)

**Comment by majora2007** [comment]
Okay I reproduced it. It looks to just be due to the filename. Naming as `DETECTIVE COMICS - VOL 1 #1 (anything after that)` worked perfectly.

**Comment by moisesbelda** [comment]
The problem is to have whatever after the number? or the specific words I have ? or not to use # before the number?

**Comment by majora2007** [comment]
The problem is you don't use the `#` which for Comics is extremely common in the filename patterns that I have seen. So because of that, the Volume 1 is causing confusion and the issue number is seeing 1 from the Volume instead of the correct one.

**Comment by moisesbelda** [comment]
super! thx a lot for your clarifications and patience. It seems that in previous versions the parser doesn't need the #, since I have several series scanned in the previous version correctly recognised with issues numbers without #. Now I tested with all my files with # and it works.

Anyway, I will rename my files with #, but I will keep some of them without, just in case you want me to test any fix in a future nightly or stable version.

Thanks and Regards.

**Comment by majora2007** [comment]
I don't recall updating the comic library parser, but I've made a lot of changes as bugs are reported, so it is likely some existing cases did break. I think switching to using the `#` is probably the best bet.
