### ISSUE TITLE
Frontend sends too many requests after setting up email

### ISSUE THREAD

**Issue by johnxu16** [Kareadita/Kavita#3362]
### What happened?

When I fill the form on email setup page, every time I click "close" button aside for filling one of the field, I detect hundreds of requests been sended.

### What did you expect?

Every change of the fields on email setup page should only trigger one request at a time.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
Nice find, looks like some debounce is missing
