### ISSUE TITLE
No marker to show a comic or series as read.

### ISSUE THREAD

**Issue by Surgical17** [Kareadita/Kavita#3373]
### What happened?

In my screenshot below I have read all 3 comics in Kavita and also manually selected "Mark as read" but the is no visual indicators to show the comic was read:

![image](https://github.com/user-attachments/assets/b3b4d6dd-8e30-4084-8499-0d6def705cd9)

### What did you expect?

Display a tag to show comic or series was read. Can maybe be a optional tag for people who do not want to see it.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by DieselTech** [comment]
The screenshot you provided doesn't seem to be the right one.

**Comment by scare376** [comment]
also this should be in a discussion since it is a feature request not an issue. there is an indicator that an item is unread/in progress but if there is nothing that means it is read.

**Comment by Surgical17** [comment]
> The screenshot you provided doesn't seem to be the right one.

Thanx I updated

**Comment by Surgical17** [comment]
> also this should be in a discussion since it is a feature request not an issue. there is an indicator that an item is unread/in progress but if there is nothing that means it is read.

Thanx. I actually thought it was a bug hence why reported it as one as I did not know it was just a missing feature

**Comment by DieselTech** [comment]
Yeah the lack of indicator is what indicates it has been read. The indicator only shows up when it is unread. 

You can see it in the top right corner of the card:

![image](https://github.com/user-attachments/assets/76d89b7d-6264-4dbd-83ed-e47ae7c691d0)

**Comment by scare376** [comment]
![msedge_9QvRT4Ugeg](https://github.com/user-attachments/assets/dd30d004-0b6e-43fe-b0d7-3c27b2a130d7)
here's all 3. if a book is in progress you'll have a progress bar at the bottom

**Comment by Surgical17** [comment]
Thanx for correcting and assisting guys
