### ISSUE TITLE
Multi select actions not hooked up in the series page

### ISSUE THREAD

**Issue by Fesaa** [Kareadita/Kavita#3380]
### What happened?

https://github.com/user-attachments/assets/a7d09b7f-63c1-47f2-9412-5445c1e34fa4

I've only tested delete, but kept the title more general in case other weren't working either.

### What did you expect?

Them to work

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Mac

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Safari

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
Just to let you know, you can shift+delete. Select the first, hold shift, select the 3rd card.
