### ISSUE TITLE
Default theme setting for Book Reader is not functional

### ISSUE THREAD

**Issue by rayyume** [Kareadita/Kavita#3382]
### What happened?

I tried to set the default theme of book reader from "dark" to "paper" in setting meau, but the default theme is still the "dark". So I have to set the theme each time I opened a book.

### What did you expect?

The default theme setting for book reader is functional.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by scare376** [comment]
Where are you trying to set it? As in which settings menu.

**Comment by rayyume** [comment]
> Where are you trying to set it? As in which settings menu.

click the user name on the front page and then click the settings button.

**Comment by scare376** [comment]
wait what version are you on? all of the settings are in the gear menu next to the name now

**Comment by rayyume** [comment]
> wait what version are you on? all of the settings are in the gear menu next to the name now

![image](https://github.com/user-attachments/assets/9f03fe85-50ff-42ed-bd2a-d53c3b9c1fb9)
![image](https://github.com/user-attachments/assets/5c9008f9-d0c3-407b-82d3-545bfc10e111)
here it is

**Comment by scare376** [comment]
so i see its on paper right now. but when you open an epub its on dark?

**Comment by rayyume** [comment]
> so i see its on paper right now. but when you open an epub its on dark?

yup I have to switch the theme again when opening a book.

**Comment by scare376** [comment]
im not able to reproduce. can you try clearing your browser cache/cookies?

**Comment by rayyume** [comment]
Tried to clean the browser cache both on PC and iOS and tried to open kavita in private mode, still not working. If it is not a common issue, I think it may be caused by the deployment of my container. Checking on it.

**Comment by rayyume** [comment]
> im not able to reproduce. can you try clearing your browser cache/cookies?

I think I find the cause of this issue. When I switch the default language from English to Chinese, and switch the theme option, the theme is not changed. But I switch the language from Chinese to English, the theme setting works. It caused by the language setting.
