### ISSUE TITLE
Merged albums

### ISSUE THREAD

**Issue by aragorn74** [Kareadita/Kavita#3386]
### What happened?

I will point out that there is always the problem of all-in-one numbering of the files (I use CBZ or PDF format); I have the 397 roll and the 397bis roll and Kavita combines them ...

![Screenshot_4](https://github.com/user-attachments/assets/adb9203c-51b1-4d7a-8a4c-63a3ee27cfa4)
![Screenshot_5](https://github.com/user-attachments/assets/1978aad4-eaec-4a7c-b3b1-0542bfd943b6)

### What did you expect?

Is there any way to avoid this handling?

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
If there isn't internal metadata, then that is because there is no filename parsing for `Tex 123`.

**Comment by aragorn74** [comment]
Okay, that's clear.
If it is not possible for Kavita to read the filename, how can I add metadata to more than 3000 files in batch mode?
I tried with Comictagger but I can't ...
Another thing: If it is true that Kavita does not find the metadata why doesn't it read the files and folders as they are loaded?
I split one folder (too many files, they were not being loaded by the Panels client app) into two folders: albs 001-400 and albs 401-800.
Why does Kavita recognize only one of the two folders?

**Comment by majora2007** [comment]
Well Kavita supports a ton of different filename patterns, just not that. I'm sure that is a foreign language and if that's common in your language, you can raise a Feature Request to have Kavita support those patterns.

I would have to see the filename/folder layout and know the library folder (root) to answer that question. 

For batch tagging, comic box (cli) or manga manager both support bulk tagging. 

The way Kavita works is when it sees a file, it tries to find internal metadata if that fails or there is partial information, it tries to parse it from the file. If there is no series information or we've detected it's a special, Kavita will try the folders up to the root to try to extract data. All these files are then grouped into series.

**Comment by aragorn74** [comment]
this is folder layout:
![image](https://github.com/user-attachments/assets/3b90742d-c95e-4c20-95b2-8abe167ab238)
![image](https://github.com/user-attachments/assets/1e13ae27-abf1-4472-a5a7-7c49ca403186)
![image](https://github.com/user-attachments/assets/4c792fb7-f376-4a1d-b148-802caa669b38)

**Comment by majora2007** [comment]
Is Tex the series name or Fumetti? You're using a very loose filename, so it's thinking Tex is the series name. 

The easiest way is to name your files in a way that makes it easy for Kavita to understand. `Series - #number - title`. I'm not sure again what Tex means, but if it's chapter or volume, either submit for parser enhancements, use an existing thing like `Volume`, `Ch`, or hash, or use internal metadata.

**Comment by aragorn74** [comment]
exactly. Comics is my folder; Tex is a series (all comics uploaded are Italian).

https://www.sergiobonelli.it/sezioni/10/tex

**Comment by aragorn74** [comment]
Comics (traslated) = Fumetti

**Comment by majora2007** [comment]
Hmm okay and the library type is comics and the library root is Fumetti? I would have a series folder, so

Fumetti/Tex/Tex 1-400
Fumetti/Tex/Tex 401- 700

What's happening is you have 2 series parallel from the library root, which is not allowed. Using this structure should allow Kavita to group them correctly.

**Comment by aragorn74** [comment]
no ... under the root Fumetti I have the various folders each for each series ... I split the Tex folder (for example) into two folders 001-400 and 401-800 because otherwise Panels won't load the files for me ... 
Previously I had all the albums in one folder called Tex.

![image](https://github.com/user-attachments/assets/746d8c62-eb56-4065-88a5-bd9714802458)

I still always have the problem even in the other folders (the other series) where the metadata is not loaded.

I tried editing the metadata: mangamanager can't find any matches, comictagger can, but I can't edit all the albums in the same series.
In the following example, I can edit the metadata of each album individually, but I can't do it on multiple albums.
Also, the Comic Vine database is out of date: the Tex Willer series is now 72 albi, in the database it is 61 ...

I cannot edit thousands of files one by one ...

![Video 2](https://github.com/user-attachments/assets/e5f93953-4d14-431c-8ba1-5316bc9d03d8)

Sorry if I can't make myself understood, but I'm using a translator

**Comment by majora2007** [comment]
Okay 2 things:
1. Move your 2 Text folders under 1 from Fumetti, so `Fumetti/Tex/Text 1-400` and `Fumetti/Tex/Text 401-700`
2. Don't use Calibre to edit metadata. It doesn't write anything to the archive. 

Kavita (and other software) expects metadata for archives in ComicInfo.xml format. Calibre is just writing to it's own internal DB and Kavita will not be able to read that. You need to use the appropriate tooling for the appropriate file type, hence why I mentioned ComicTagger (or Mylar).

**Comment by aragorn74** [comment]
Okay, I will move the folders.
For the metadata, the video I uploaded in the discussion refers precisely to ComicTagger, which I cannot use for multiple files.

Thank you for your patience

**Comment by majora2007** [comment]
Oh yeah, sorry, I wasn't looking well enough. Yes, ComicTagger does not support bulk tagging. 

As I mentioned, Manga Manager DOES, but does not support scraping from Comic Sources, it's made for Manga. 

I can't help more than that, you can ask in the discord for other solutions. I would first look at something like Mylar to manage your files and metadata.

**Comment by aragorn74** [comment]
okay, thank you very much for your time ...
