### ISSUE TITLE
Send To not working across app

### ISSUE THREAD

**Issue by Net0o** [Kareadita/Kavita#3404]
### What happened?

Send As not working on mobile device, in comparison to the older version it displays correctly now, but seems it does nothing. (tested on Android)

It works from desktop.

Version: 0.8.4.0

### What did you expect?

Send As should work as intented on mobile devices

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.4 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

**Comment by majora2007** [comment]
Found the sneaky piece of code that broke the whole send to menu from calling the action handler. Since this is a pretty big issue, I'll be doing a small hotfix.

**Comment by Net0o** [comment]
Thanks for your hard work! Appreciated.
