### ISSUE TITLE
Mobile Actions not all wired up

### ISSUE THREAD

**Issue by Net0o** [Kareadita/Kavita#3405]
### What happened?

Force Scan is sometimes not working from mobile device, I think this issue mostly happen on vertical view. Once I rotated the phone to horizontal view it worked.

After clicking on Force Scan, nothing happens sometimes. 

Desktop not affected

### What did you expect?

Force Scan should work as before.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.4 - Stable

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

**Comment by majora2007** [comment]
Where are you triggering it from? Force Library Scan is only available from the library settings modal and has no special component for mobile.

**Comment by Net0o** [comment]
My apologies, I was yesterday testing some heavy loading/force scans and after I restarted my instance in the docker container it seems to work now. Most likely issue between my seat and monitor lol :)
