### ISSUE TITLE
Handle disapears in Reading List when the number of books in a reading list is over 100

### ISSUE THREAD

**Issue by heyhippari** [Kareadita/Kavita#3438]
### What happened?

I created a reading list from a CBL file (This one: https://github.com/DieselTech/CBL-ReadingLists/blob/main/Image/Master%20Reading%20Order/Massive-Verse%20(Radiant%20Black)/%5BImage%5D%20%5B2014-2024%5D%20Massive-Verse%20(CBT).cbl).

It was outdated, so I started adding new issues. When I got over 100 issues, the handles to reorder the issues do not show up anymore and I have to resort to the number inputs instead.

### What did you expect?

The handles should show up, no matter how much books are in a reading list.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.4.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
This is intended functionality. After 100 items, virtualization is used and drag and drop doesn't work well at that scale.
