### ISSUE TITLE
Calculation of Pages and Readtime

### ISSUE THREAD

**Issue by Saetron** [Kareadita/Kavita#3452]
### What happened?

The issue appears with EPUBs in the Manga & Comic section.
With EPUBs, Kavita seems to consistently default to a read time of under one hour, even when it correctly detects pages instead of words.
![Image1](https://github.com/user-attachments/assets/33f77a62-b3b8-40cf-a964-aff9132ec10d)
![Image2](https://github.com/user-attachments/assets/b8c48578-e19a-4746-b739-f92bd3970a5e)
![Image3](https://github.com/user-attachments/assets/2c1b8a0c-a299-4a48-b9f5-3c94eedda992)
![Image4](https://github.com/user-attachments/assets/a3501387-78a0-45f1-b89a-968030ac1f7d)

Sometimes it attempts to count words in the Comic and Manga section, resulting in a 0 Words count.
![Image5](https://github.com/user-attachments/assets/cd5e36c0-a172-4fe7-842e-b82256d2a38b)

### What did you expect?

The expected behavior is for Kavita to disregard word counts and solely rely on page counts (typically the number of XHTML files in EPUB manga and comics). And would use the read time calculation method for PDFs and CBZs.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.4.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
Epubs should always use the word count for estimation and archives/loose images use the page count. 

Epubs using page count would be poor as most epubs I've ever come across are text-oriented. If you're using epubs for comics/manga, why? They are a worse reading experience than just extracting the images and sticking into an archive.

**Comment by Saetron** [comment]
ePub is the standard format for eBooks.

All mayor eBooks stores deliver as ePub. If you buy Manga on official stores, you get ePubs. Of all the eBooks I have bought only some Humble Bundle books are PDF/CBZ.
Kobo, J Novel Club, Tolino all ePub.

I like to keep the original files as intact as possible and as ePub is the standard format for officially sold eManga, I would prefer it. The Calibre Page Count plugin can count the pages as it should be for inspiration. I mean Kavita also almost always gets the count of pages correct, just not the readtime. Thats why i would say it should ignore words for comics and Manga, as there arent "words", its all image based.

**Comment by majora2007** [comment]
I understand your perspective, but it's not really the whole truth. Most ebooks are text-based files, like Light Novels or books. Since they are html inside, the whole book could be one file. Now imagine they packed Harry Potter that way and on Kavita it uses page count and says 1, but inside is 20 chapters of text. 

This is the problem when it comes to different file formats and how to best represent them. I would argue that most people have epubs with text content inside of them, I know I have all of mine like that. Your use case is completely valid, but it's not trivial to solve it in a way that just works or doesn't add a lot of extra complexity to the different areas that need to use these calculated values.

**Comment by Saetron** [comment]
Understandable. Haven't checked the code and thought it had different ways of handling if between Manga and Light Novel/Books libraries as some things are different between them.

No worries. Its just a small thing anyways and doesn't impact it in a meaningful way.

**Comment by majora2007** [comment]
We should move this into a Feature Request and maybe the community can shine some light or upvote to see if it's more than 1 person affected, to help justify the extra maintenance cost of customizing.
