### ISSUE TITLE
Add Server Admin About Tab

### ISSUE THREAD

**Issue by jmeacoe** [Kareadita/Kavita#391]
I wanted to quickly see what version I was running without having to check my docker images.  Couldn't find that in the UI, so you may as well create a full admin tab for this.

Include: 
   - current version.
   - links to github, websites, discord channels / IRC / Matrix (whatever is used)
   - project license type
   - AppData directory
   - Any other pertinent about info

**Comment by majora2007** [comment]
Great idea, I'll put it in the upcoming release.

**Comment by majora2007** [comment]
Just a heads up, the "AppData" directory is currently there, but disabled (Nav bar top right, server settings). But Current version is def missing and having the support information would be ideal.
