### ISSUE TITLE
[Feature Request] Scrobbing to AL

### ISSUE THREAD

**Issue by toprak** [Kareadita/Kavita#400]
It has way better database than MAL.

**Comment by toprak** [comment]
will add to https://feathub.com/Kareadita/Kavita

**Comment by majora2007** [comment]
You can actually add to this issue, which is the epic to track all sources:
[#148](https://github.com/Kareadita/Kavita/issues/148)

If this is explicitly scrobbing and not metadata source, then please do add to FeatHub. Scrobbing is a planned feature and would def like inputs on other sources besides MAL.
