### ISSUE TITLE
Bug: Long filenames with no spaces are causing overflow on Info/Edit modal for Volume.

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#403]
Potentially use the readmore component for thsi?

**Comment by magujun** [comment]
I'll take a look at this one, maybe use the readmore component as you've suggested.
<img width="930" alt="image" src="https://user-images.githubusercontent.com/75567460/176923075-2f5d83f9-f1de-4f9e-bb78-ecd58fad7ac9.png">

**Comment by magujun** [comment]
CSS offers a simple solution, would your prefer the readmore component anyway?
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/75567460/176929745-997caa75-19ad-41a5-b4b9-7e5c932126c5.png">

**Comment by magujun** [comment]
It seems to be kind of the same issue, just not in the series header...
This is the original issue, right?

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/75567460/176934758-71ee2c44-f5bb-4ee0-81fe-ac514ee57470.png">

**Comment by magujun** [comment]
Same solution...

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/75567460/176935149-fc07409d-20c9-43d5-b224-8d116b9ba94a.png">

**Comment by magujun** [comment]
# Closed
- Fixed: Fixed the word wrapping for long filenames on headers that would cause modals to overflow.
