### ISSUE TITLE
Ignore Mac metadata hidden files `._*`

### ISSUE THREAD

**Issue by pxtang** [Kareadita/Kavita#440]
Macs sometimes like to create [hidden metadata files](https://apple.stackexchange.com/questions/14980/why-are-dot-underscore-files-created-and-how-can-i-avoid-them). These make Kavita take a little when scanning files and trying to get cover art, since there is anything meaningful for Kavita in those files.

Since these metadata files are created by MacOS per-file, the filenames are incredibly similar. Kavita would look at `._Manga_vol_1.cbz`, find nothing meaningful inside, skip cover art generation, then skip search `Manga_vol_1.cbz` for the cover art.

I can still open `Manga_vol_1.cbz` to read, so the reading works fine.

**Comment by majora2007** [comment]
I think you're our first MacOs user, welcome. I've only come across these ._ files once. I can definitely add this exclusion this release.

**Comment by majora2007** [comment]
This has been implemented, if you are on docker, you can pull the latest :nightly to test, otherwise, please wait for the release.

**Comment by pxtang** [comment]
Thanks for the quick fix!

I'm actually running it on Linux, but I have a few manga directories that were created from Mac, which is how I ran into this issue.
