### ISSUE TITLE
Ignore cover images inside a series folder

### ISSUE THREAD

**Issue by therobbiedavis** [Kareadita/Kavita#455]
Currently cover images are showing as a duplicate series image type. We need to add an exception.

**Comment by majora2007** [comment]
I thought about this and one way to approach this is after we get all the process folders,we do a check to remove process info's that have only 1 image file and it matches IsCover () (in parser). 

This allows it to work with image libraries without much pain. Can also trial if only 1 image to skip moving forward with that series.
