### ISSUE TITLE
Disabling Authentication for the server

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#465]
To enable an easier experience for servers that are going to be used only on LAN, this feature will allow disabling authentication. 

This story handles authentication differently than other applications. First flow will require the user to setup a password for the admin account. 

The admin can now disable authentication for the server. Going forward, any authentication will no longer need a password for all accounts except the admin. Admin accounts will always require authentication. 

When an admin creates a new account with authentication disabled, the new account will receive a static password. This will be attached later to this issue. 

When a user comes to Kavita, they are prompted with a user picker to quickly login. They will remain logged in, like an authenticated user is, until they log out manually (or if JWT token is manually updated). 

If authentication is re-enabled after the fact, the admin will be prompted to change passwords for his users or request his users to change their password from the static, predefined password to a new one. Likewise, if enabled again, all user passwords will be reset to the static one. 

https://feathub.com/Kareadita/Kavita/+5

**Comment by buddyhollyy** [comment]
Where do I find this option to disable authentication?

**Comment by majora2007** [comment]
> Where do I find this option to disable authentication?

You don't. It was removed. You're commenting on a release that is 3 years old now. 

If you want something similar, you can bookmark the login page with apiKey=YOURKEY and it will auto log you in.

**Comment by amirasyraf** [comment]
@majora2007 

~~Can you give an example of that?~~

~~I tried but can't get it to work. I tried~~

~~`http://myIp:port/apiKey=98sg787fdsg-3ef4-udsg9-9f01-a5a6018a4d8b`~~

~~and~~

~~`http://myIp:port/?apiKey=98sg787fdsg-3ef4-udsg9-9f01-a5a6018a4d8b`~~

nvm figured it out, it's in the `/login` path

`http://myIp:port/login?apiKey=98sg787fdsg-3ef4-udsg9-9f01-a5a6018a4d8b`
