### ISSUE TITLE
Bug: Comics in collections are not in alphabetical order.

### ISSUE THREAD

**Issue by mahenkpatel** [Kareadita/Kavita#485]
- The comics in collections shows up in the order they were added in collection
- This causes the comics to be out of order is not added to the collections in sequence.
- The collection should either show the comics in alphabetical order or there should be an option to manually change the order of comics in collection

**Comment by majora2007** [comment]
Can you give me an example of how your collection is out of order? 

Collections are series that are retrieved by the Library they are in, then by the SortName of the Series. If you want more discrete control over sorting, you'll might have to wait for Reading Lists (#268)

**Comment by majora2007** [comment]
Closing this until questions are answered. Please answer and reopen. Thanks.
