### ISSUE TITLE
Feature Request: Book Uploading

### ISSUE THREAD

**Issue by Kizaing** [Kareadita/Kavita#488]
Idea for possible feature, users being able to upload book files via the Web UI. 

- User permissions, users could be flagged by the admin to have access to uploading or not
- Ability to choose which library the file gets uploaded to, and then it will be placed in the destination folder accordingly
- Possible batch uploading?

Could be useful for other users on your server uploading and sharing their book libraries to you, or just easier way of uploading a single book file to your own server rather than placing it in the needed folder.

**Comment by majora2007** [comment]
Hello, I am closing this out. If you still want it, please move your feature request to https://feats.kavitareader.com. All feature requests should go there.
