### ISSUE TITLE
Feature Request: Tachiyomi Support

### ISSUE THREAD

**Issue by ZhunCn** [Kareadita/Kavita#496]
For Android devices, it would be nice to get support with [Tachiyomi](https://github.com/tachiyomiorg/tachiyomi) via a plugin/extension.

https://github.com/tachiyomiorg/tachiyomi-extensions

**Comment by majora2007** [comment]
This is already a planned feature. Initial support will be via OPDS, but a full plugin is planned.

**Comment by majora2007** [comment]
Change of plans, this will be done along with OPDS support.

**Comment by majora2007** [comment]
Change of plans again, I gave it a fair shot, but this is not something I have enough of a need for to struggle through Kotlin. If someone wants to pick this up, I would love it. But for now, I will put this on the back burner. 

Sorry to get your hopes up.

**Comment by majora2007** [comment]
This is in progress. If you're interested in helping test, please join the discord channel.

**Comment by majora2007** [comment]
This is done, but somehow didn't get closed
