### ISSUE TITLE
"Next Chapter/Volume" Button is not working correctly?

### ISSUE THREAD

**Issue by Table-Dropper** [Kareadita/Kavita#537]
Used Version: kavita-linux-x64.tar.gz - Linux v0.4.4
![Animation2](https://user-images.githubusercontent.com/35638111/131397469-2fee976e-6f1e-4ef6-89aa-0625b77eb247.gif)

As seen, in the Animation, the  "Next Chapter/Volume" Button does not seem to work correctly.
Tested with multiple Series and Browsers.

Are you able to reproduce the issue?

**Comment by majora2007** [comment]
Hello, the data in the top left is not the idea, as it is populated from parsing the filenames. Can you give me a bit more information, for example:

there are 2 files in question, which file are you on? when you hit next you are going to which file?

**Comment by Table-Dropper** [comment]
I am on Chapter 65. It jumps back to Chapter 8.
The filenames given, are foolproof, i think:
ex:
...
Liar-Game-chapter-008.cbz
....
Liar-Game-chapter-065.cbz
....

In another Series, it always jumps back to chapter 2.

In the Chapter Overview, the Chapters are in correct order.

**Comment by majora2007** [comment]
Hmm, I'm not able to reproduce. I have this:
Liar-Game-chapter-008.cbr
Liar-Game-chapter-009.cbr
Liar-Game-chapter-065.cbr
Liar-Game-chapter-066.cbr

When I open 8 and use next chapter, I go 8->9->65->66. 

I noticed your naming, are yours coming under Specials or as Chapters? Because due to the -'s, Kavita is unlikely able to parse those (just a side note).

**Comment by Table-Dropper** [comment]
You are right. Kavita doesnt like "-" at all and yes they are shown as specials.
I batch-renamed a series and replaced "-" with spaces; Jumping between chapters works now as expected.
Thank you! In that case, I am going to rename my Library.
Is the "-" documented, as bad character? For I would never have guessed that.

Still i think its weird, that "-" work on your side, but not on mine.

The Reader shows following behaviour with "-" in Filename:
Chapters from 1 to 200+ are in this library.
I can go back to the Chapter Overview and click on the next Chapter to read.
But if I try to use the Button "Next Chapter/Volume" Button, the Reader Jumps back to Chapter 8 for this Series.
After that the "Next Chapter/Volume" Button becomes unavailable.

**Comment by majora2007** [comment]
Yeah it's very interesting. The only thing I could think that might be an issue is how they are grouped (but you mentioned they are individual specials) or some unique character that would cause the sorting to bug out. I named mine exactly as I showed. 

When sorting specials like that, I use the filename and apply a natural sort, kinda like how Windows might show the files in order. That could theoretically be the issue.

**Comment by Table-Dropper** [comment]
Maybe this was misscommunication on my side.
I never had any specials. (Though I dont know the criteria for deciding whats a special and whats a chapter.)
The whole Series was listed as "Special" before renaming. After renaming, the Chapters are now in "Volume/Chapters".
![grafik](https://user-images.githubusercontent.com/35638111/131409700-a48d0ac0-adf4-482d-a3dc-33310ce094f7.png)

But if  you can't reproduce the error, then I am going to re-install my server at a later date, and try to reproduce the error.
(The re-install was planned anyway)

**Comment by majora2007** [comment]
Yeah I'm really not sure why I can't reproduce the error. 

If you're re-installing and are interested in updating your naming conventions, you might want to reference our wiki for our best practices:
https://wiki.kavitareader.com/en/faq/folders-and-file-structure

Drop by our discord if you want to engage or get extra support. Let me know.

**Comment by majora2007** [comment]
This was sorted with the user. After many attempts, could not reproduce.
