### ISSUE TITLE
error 400 could not save progress

### ISSUE THREAD

**Issue by moisesbelda** [Kareadita/Kavita#570]
**Describe the bug**
Radomly, when I'm reading a book  (epub), a message is displayed saying "400 Could not save progress".
I've checked inspector, and there are a lot of /progress requests with 200, but there are few with 400 COuld not save progress, so the endpoints is working, but failing radomly.

**To Reproduce**
- Open a epub.
- click NEXT PAGE several times until the error is displayed.

**Expected behavior**
No errors displayed when I iterate through the pages.

**Screenshots**

**Desktop (please complete the following information):**
 - Docker image

**Additional context**
I'm running Kavita from a docker image using NAS synology.

**Comment by majora2007** [comment]
I've also been seeing this occur, I'll take a look into it.

**Comment by majora2007** [comment]
This has been fixed via a performance improvement effort. Please wait for it to be merged (docker users on nightly can use early, else wait for stable release)
