### ISSUE TITLE
LDAP support?

### ISSUE THREAD

**Issue by tdehaeze** [Kareadita/Kavita#577]
Hi guys,

First of all, thank you for this amazing software that I use on my server.
I would like to share my instance with friends.
They already have an account using on my server for other services and I would like that share the authentication with Kavita instead of asking all of them to create a new account just for Kavita.

Do you plan to support something like LDAP?
I think that would be awesome.
Not sure how hard it is to implement that as I never touched C#.

Cheers

**Comment by majora2007** [comment]
I have no plans to implement LDAP. The main way to share is to have user accounts for your friends and have them authenticate through that. If that doesn't interest you, you can wait around for #465 (not slated for a release yet).

**Comment by tdehaeze** [comment]
Thanks you for your reply.

What do you mean by
> The main way to share is to have user accounts for your friends and have them authenticate through that.

#465 would be nice enough for me as I can authenticate my friends using Authelia before accessing the Kavita instance.

**Comment by majora2007** [comment]
"The main way to share is to have user accounts for your friends and have them authenticate through that."

It means, you setup the Kavita instance and add accounts for your friends. You can give them a default password, they can change themselves. Then they log in through that account that was setup.

As everything in Kavita is based around role based security and an account to store progress against.
