### ISSUE TITLE
Support Signed MacOS app install

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#578]
Currently on later MacOS versions, GateKeeper will require manually allowing each dll for Kavita in order to use. 

Investigate a new packaging method and getting a signed build.

**Comment by majora2007** [comment]
This story is under review for feasibility. Due to low usage on MacOS, it might be advisable to not provide a build and have MacOS users use docker instead.

**Comment by petrovicstefanrs** [comment]
+1 for MacOS installer

**Comment by majora2007** [comment]
Some documentation:
https://www.xamboy.com/2020/05/28/net-core-application-macos-packaging-and-notarization/

Signing an app is out of question. $99/year plus mac requirements for 2 users that have alternative ways of using doesn't add up.

**Comment by majora2007** [comment]
I have decided not to proceed on this due to cost overhead, small user base, and alternatives being available. 

MacOS users can follow the instructions here:
https://wiki.kavitareader.com/en/install/linux-install
