### ISSUE TITLE
Up/Down keys should not change the page when scrolling

### ISSUE THREAD

**Issue by arvigeus** [Kareadita/Kavita#579]
**Describe the bug**
When setting Image Scaling to anything different than "height", a scrollbar appears. It scrolls fine with the mouse, but KeyUp event for Up/Down keys changes the page. Would be better if it only happens when reaching top/bottom of the page.

**To Reproduce**
1. Set image scaling to "width" or "original"
2. Press up/down key

**Expected behavior**
Should change the page only when reached top/bottom

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Chromium
 - Version: 0.4.5.1

**Comment by majora2007** [comment]
Hello, I took a look, there seems to be a bug in how the reader should work. This is what I'm proposing:

1. When reader mode is set to Left->Right, only left/right keys
2. When reader mode is set to Up->Down, only up/down keys work
3. Reading direction will now be disabled with up/down. Up will always go back one page, Down will always go forward one page. 

This allows you to read on original of scale to width and still us up/down on your keyboard without me having to implement complicated scroll checking for the pagination.

**Comment by majora2007** [comment]
Don't close the issue. I will close it when it has been implemented and merged in.
