### ISSUE TITLE
If a library path has a & (ampersand) in it, it is unable to read anything under it

### ISSUE THREAD

**Issue by zachron** [Kareadita/Kavita#593]
**Describe the bug**
If you are trying to choose a directory, or after you have chosen a directory if a folder underneath the folder you have chosen, has a & in any of the names, then you get a 400 and it will not read it correctly

**To Reproduce**
1. have a directory structure like /sample/directory/D&D/somethingelse/somethingelse
2. Create a new library, it can be named anything, and type does not matter
3. Click the + to add a directory
4. navigate to /sample/directory/
5. click on D&D in the list
6. see 400 error that gets returned.
7. If you click on the share button on the row for the D&D folder, it will try to add things in that folder, and work as long as there are not any &'s in any folders beneath that folder you have chosen

**Expected behavior**
to be able to traverse and parse all directories and filenames even if they have a & in the name

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 91.0.2
 - Version: 0.4.5.0

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
N/A

**Comment by majora2007** [comment]
Nice find! I will fix this with the next release. (Don't close the comment)

**Comment by zachron** [comment]
awesome, glad i was able to help, i really like the look of this project :)
