### ISSUE TITLE
Remove Sentry

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#629]
Sentry has not been providing any valuable errors and as such, is just extra bloat. This story is to remove it from the project.

**Comment by bruno-garcia** [comment]
@majora2007 I'm curious why wasn't it providing any value. Could you please share some of your experience with it?

**Comment by majora2007** [comment]
@bruno-garcia In this project, most of the errors that are produced are due to user's files, things like being corrupted, missing metadata, etc. What I found was that most errors coming in were around that. Even after excluding and filtering errors, still many were creeping through. 

During the 6 months of using, we only found 2 errors that were due to our code rather than user's files. At the end of the day, it wasn't worth keeping it in and having to filter through, so we removed it. Hope that helps.
