### ISSUE TITLE
[Feature Request] - Filter by Read and Unread series

### ISSUE THREAD

**Issue by jmeacoe** [Kareadita/Kavita#647]
Currently the only filter is to show the format of the file.  Please add a filter to only show unread material in the WebUI for the logged in user.

1. Open a library
2. Click on the filter button
3. Wish deeply for a unread/read filter.

**Comment by majora2007** [comment]
I'm closing this since it's now being tracked here:
https://github.com/Kareadita/Kavita/issues/846
