### ISSUE TITLE
"2000 AD" comic name isn't parsed correctly from filename

### ISSUE THREAD

**Issue by wyldphyre** [Kareadita/Kavita#649]
**Describe the bug**
I have a bunch of "2000 AD" comics and I noticed while setting up Kavita for the first time that the name isn't parsed correctly.

**To Reproduce**
1. Have a file called "2000 AD 0366 [1984-04-28] (flopbie).cbz".
2. Scan library to include file
3. results in a comic entry called "AD 0364"

**Expected behavior**
The result I'd expect is a comic entry with "2000 AD" at the series, and "364" as the issue/chapter number (no point keeping the leading zero).

**Screenshots**
![2000 AD 0364](https://user-images.githubusercontent.com/3920750/136682931-d26eb799-f97c-4e3b-a679-2bed3c4a7843.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: MS Edge
 - Version: 0.4.6.0

**Additional context**
On a side note, these archives contain ComicRack metadata information which contains the series, so it would be ideal if that information would be used if present when scanning files.

**Comment by majora2007** [comment]
This is fixed and will be released with next stable (shortly as all other stories are done).
