### ISSUE TITLE
Kavita not parsing folders properly\merging comics series

### ISSUE THREAD

**Issue by ITguy3118** [Kareadita/Kavita#705]
**Describe the bug**
my structure goes as comics\publisher\series\issues.ext
say, batman for example
if i set the library to share at the "comics" level I see batman>batman vol 1 vol3 and chapter 66 as volumes (each of these are seperate series) 
If i open any one of those, it's a single comic....should be many comics below that
on the other hand, Advanced Dungeons and dragons show properly
then I have Batman Gotham Adventures, that also shows properly
same for Batman the Detective (series)
so it seems that anything labeled "Batman" is grouped together, even though they are separate series

Naming convention is as follows 

comicname (year)\series name- volume- issue- year.ext

**To Reproduce**
Drilling down folders after library creation  

**Expected behavior**

**Screenshots**
Screenshot of batman layers 
![10-25-2021 -  20_58_13 - Kavita - Comics - Vivaldi](https://user-images.githubusercontent.com/90217713/138795836-49e3d904-3881-4ed8-8863-e92260eed4be.png)
![10-25-2021 -  20_58_18 - Kavita - Batman Details - Vivaldi](https://user-images.githubusercontent.com/90217713/138795839-fe3d8954-fe2c-4494-9861-5c1f5143fb36.png)
![10-25-2021 -  20_58_23 - Kavita - Batman Details - Vivaldi](https://user-images.githubusercontent.com/90217713/138795840-a760893f-84d0-4e33-82f4-ea4a3771a5d4.png)

**Desktop (please complete the following information):**
 Windows 10
  Vivaldi 
 - Version [e.g. 22] (can be found on Server Settings -> System tab)
Version
0.4.6.0

**Additional context**

**Comment by majora2007** [comment]
I took a look and all tests are passing for this on the latest code. Your issue is missing some information though, so I had to piece together the exact conditions. 

Can you please give me the full path of a file that is failing to parse correctly?

For example:
/comics/yourpublisher/Batman the Detective (2019)/Batman the Detective - v6 - 11 - (2019).cbr

Something like this will let me reproduce exactly what's happening.

**Comment by ITguy3118** [comment]
sure, it would be 

"C:\Comics\DC Comics\Batman (1940)\Batman - 000 - (1994).cbz"
"C:\Comics\DC Comics\Batman (2011)\Batman - 002 - (2011).cbz"
"C:\Comics\DC Comics\Batman (2016)\Batman - 003 - (2016).cbz"

as examples, the C:\ comics are symlinks, I experienced a separate issue where kavita was not recognizing a mapped drive when ran as a service, so we found the workaround to be creating symlinks and placing them on the C:\ to work

**Comment by majora2007** [comment]
I see, I believe I discussed this on the Discord. Year is not accounted for in parsing, the work around is to have the name in the filename. 

So for you, the easiest would be:
"C:\Comics\DC Comics\Batman (1940)\Batman 1940 - 000 - (1994).cbz"

Then in Kavita UI, you can change the Series name from "Batman 1940" to "Batman (1940)". The customized UI will persist between scans.
