### ISSUE TITLE
Demo login credentials wrong? Can not login

### ISSUE THREAD

**Issue by fklappan** [Kareadita/Kavita#706]
**Describe the bug**
Tried the demo at https://demo.kavitareader.com/ 

Page states
> Authentication is disabled. Only type password if this is an admin account. 

So I tried with both the provided credentials from the readme.md and also without, but always get the following error

> Your credentials are not correct. 

**To Reproduce**
1. Go to https://demo.kavitareader.com/ 
2. Click on "demouser"
3. It doesn't matter if the password from the readme is entered. So either provide the password or just click "Login"

**Expected behavior**
I expected to be logged in and try the demo :) 
OR
If the demo currently is disabled, it should be stated in the readme document.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/5860600/139418206-cbcb0ca3-9968-4ccd-bfef-a91b456217e6.png)

**Desktop (please complete the following information):**
Using both Chrome (95.0.4638.69) and Firefox (93.0 (64-Bit)) on Windows 10 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Kizaing** [comment]
Password has been reset and authentication re-enabled, you should be able to log in now :)
