### ISSUE TITLE
 20th Century Boys - chapters not being detected

### ISSUE THREAD

**Issue by Tyestor** [Kareadita/Kavita#711]
Hi,

I assume that this is because of the naming scheme of the files, unfortunately renaming them is not possible (I seed all my downloads). It would be nice if Kavita could mass rename and hardlink, similar to sonarr and radarr. But I digress.

Example files, chapters in bold:
## Volume 1 Chapter 1 Page 1
../20th Century Boys/20th_Century_Boys_v01[Hawks][MS]/**20cb_v01_c01[Hawks][MS]**/20th Century Boys v01c01p001.jpg

## Volume 18 Chapter 1 Page 1
../20th Century Boys/20th_Century_Boys_v18[Manga-Heaven]/**20cb_v18_c01[Manga-Heaven]**/20th Century Boys v18c01p001.jpg

## Volume 22 Chapter 13 "credits" (first image in the zip)
../20th Century Boys/20th_Century_Boys_v22[complete][Manga-Heaven]/**20cb_v22_c13[end][Manga-Heaven]**/20th Century Boys v22c13credits.jpg

![image](https://user-images.githubusercontent.com/4704145/139693764-9eea066e-45d3-45ba-b088-96eb52bbeb62.png)

![image](https://user-images.githubusercontent.com/4704145/139694392-134df67b-b200-418f-9e11-9647ac247a9e.png)

**Comment by majora2007** [comment]
I'm not understanding what the bug is from what you've shown. Can you please fill out the report like:

Expected:
Have files like this
file1
file2

Expected to group as X and Y

Actual:

Groups as Z and W

**Comment by Tyestor** [comment]
Hi,

This is my first time using Kavita so perhaps I am misunderstanding how it works but there are volumes listed under the "chapters" heading, as you can see in my screenshot. I expected the 249 chapters to show up under a "chapters" heading, not the 22 volumes. Volumes could possibly show up under a "volumes" heading, separately. Clicking, for example, volume 1 takes me directly to the JPG images contained within the chapter folders. As far as I can tell, everything is there and ordered properly.  I expected to be able to browse both chapters and volumes. not only volumes. Or for there to be a setting where I can choose to display one or the other. 

Is this behaviour intended?

**Comment by majora2007** [comment]
Yes this is intended behavior. Kavita performs grouping up to volumes if there are markers in filename or folder name in this case. 

When you click the volume, it will read through the chapters. You can use reader to jump through or use the volume overflow menu to open info/edit modal and click a chapter image to jump directly to that chapter.

**Comment by Tyestor** [comment]
Glad to hear it's not a bug. Unfortunate though that there is no way to directly view chapters.

**Comment by majora2007** [comment]
You can remove the volume markers from your names. If you can't move due to seeding, then you can soft link it. Kavita will handle all the chapters internally so you don't have to worry which chapter you're on, etc.
