### ISSUE TITLE
[Feature Request] Check root folder exists before scan

### ISSUE THREAD

**Issue by BohemianGecko** [Kareadita/Kavita#713]
**Describe the bug**
If the folder where the media is stored is not present, doing a library scan will wipe out that library

**To Reproduce**
1. have your media mounting somewhere (i.e. /media/books/)
2. Add libraries from folders inside that mount point (i.e. /media/books/comics/, /media/books/manga/, etc)
3. The mount fails (i.e. drive plugged in, network share not available, etc)
4. Library gets wiped out at the next automated scan

**Desired behavior**
1. have your media mounting somewhere (i.e. /media/books/)
2. Add libraries from folders inside that mount point (i.e. /media/books/comics/, /media/books/manga/, etc)
3. The mount fails (i.e.drive plugged in, network share not available, etc)
4. Kativa checks that the root folder /media/books/comics/ does not exist at the moment and fails the scan, thus preserving the library until the mount point can be fixed

**Comment by majora2007** [comment]
Seems like a good idea, I'll add a check if the library root is accessible and if all are not, then the library scan will be stopped.

But, what should happen if you have a library of 2 paths, 1 is accessible, and one isn't? The scan would still continue and you would lose some series.

**Comment by BohemianGecko** [comment]
All my libraries have only one path so I didn't think about that scenario, but in my opinion/preference any missing root folder is indicative of a problem and it's preferable to abort the scan, than potentially drop a portion of your library because another part happened to still be accessible.
