### ISSUE TITLE
[Feature Request] Magazine Type for libraries

### ISSUE THREAD

**Issue by faustzar** [Kareadita/Kavita#726]
**Describe the feature**
Add a Magazine type for the library
**To Reproduce**
1. Go to +Add Library
2. Click on Type Dropdown
3.No Magazine Type

**Expected behavior**
A magazine type should be on the type dropdown

**Desktop (please complete the following information):**
 - OS:Docker
 - Browser Opera
 - Version Version
0.4.8.1
.NET Version
5.0.11

**Additional context**
Thank you advance

**Comment by majora2007** [comment]
I think @ChristofferGreen was working on this previously. I'm def not against it, but the issue remains, I need naming conventions to build the paring code out of. 

You can add filenames on your disk here and we can build out some mechanisms. 

Library Types are solely for how the Parser works and (in the future), which metadata sources get pulled from.

**Comment by majora2007** [comment]
Hi @faustzar, could you please elaborate on what you are wanting from the feature or can I close this issue out?

**Comment by majora2007** [comment]
If this is a feature request and you have more information that you'd like to give for me to understand, please create a request on https://feats.kavitareader.com.
