### ISSUE TITLE
[Feature Request] PDF books support

### ISSUE THREAD

**Issue by kingvall** [Kareadita/Kavita#740]
Hello,

I have a lot of books in pdf format and unless I am mistaken kavita only seems to support pdf in image format and not text.

Is their support considered? I dream of having a pdf reader with support for a night mod (which ubooquity doesn't do).

I hope this is not a duplicate issue

![image](https://user-images.githubusercontent.com/34210863/141204315-7770c458-14ca-45e8-b651-246daff35c31.png)

**Comment by majora2007** [comment]
Hi, Kavita supports pdf in image format only. There are no plans as of right now to support text.
