### ISSUE TITLE
Series Editing 

### ISSUE THREAD

**Issue by Jerome2103** [Kareadita/Kavita#746]
That you can edit series yourself, and if 2 series are the same, that they come together automatically.

**Comment by majora2007** [comment]
This is already a planned feature in the future. I will close this feature request.

**Comment by arvigeus** [comment]
I have the same problem: all books in my language are marked as part of series for some reason.

**Comment by majora2007** [comment]
Offtopic, but @arvigeus what is happening is likely a naming issue or your epubs have a certain metadata tag that groups them as a series, think Harry Potter books, each with different title but group as the series of Harry potter. Check our documentation or join discord for support.
https://wiki.kavitareader.com/en/faq/folders-and-file-structure/ebooks
