### ISSUE TITLE
Series generated because of number 

### ISSUE THREAD

**Issue by Jerome2103** [Kareadita/Kavita#747]
As soon as the first number appears in the name of the file, it generates a series. 

I have a few comic series that have a number in the name, and the series is no longer true at all. 

The same goes for "extra" and "special".

I use the newst docker Image ( :lastest )

**Comment by majora2007** [comment]
Please provide your filenames and what is happening exactly.

For example:
Adventure time 01.cbz -> Series: Adventure time

**Comment by Jerome2103** [comment]
Filename: "xyz_Meine_23_things_01"
Serie: "xyz Meine 23 things"
but Kavita say now: "xyz Meine" is the serie

**Comment by majora2007** [comment]
Yes. Kavita is behaving as it should. Kavita uses filenames for parsing. 

So if you don't want xyz you have 2 options:
1. Rename your files (see our wiki for some best practices)
2. Let it say xyz Meine and in the UI you can change the name/sort name to just be Meine. This will keep your xyz Meine filename but show it as Meine only in the UI.

Kavita is different than most other programs in this area. Please see our wiki to bring yourself up to speed or join our discord.

https://wiki.kavitareader.com
