### ISSUE TITLE
Some comic naming conventions are failing to parse Series

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#758]
Demon 012 (Sep 1973) c2c.cbz

**Comment by LeeThompson** [comment]
Here's a list of more.  I have _not_ yet checked each group to make sure it doesn't contain entries that don't belong.

[kavita_parsing.txt](https://github.com/Kareadita/Kavita/files/7541436/kavita_parsing.txt)

**Comment by majora2007** [comment]
I've gone through your list, here are a few I'm not sure how they SHOULD parse as:

Rising Stars 000 and Initiations - A Lost Tale of the Specials (2012) (digital-Empire)
/manga/Comics/DC/D/DCU/Millennium/1987/Millennium Checklist.jpg (this is falling back to the folder for the name, maybe it should be Millennium?)

**Comment by majora2007** [comment]
I don't think I can handle this case either:

Epic Illustrated 002 (Dreadstar - Metamorphosis Odyssey - Chapter 4)

You have a chapter marker, so Kavita is parsing it as "Epic Illustrated 002 (Dreadstar - Metamorphosis Odyssey - " for Series. I'm not really sure what this is, so if you can elaborate, maybe we can find a compromise.

**Comment by LeeThompson** [comment]
> Millennium

Millennium would be fine, I actually expected it to just ignore a loose jpg.

**Comment by LeeThompson** [comment]
> I don't think I can handle this case either:
> 
> Epic Illustrated 002 (Dreadstar - Metamorphosis Odyssey - Chapter 4)
> 
> You have a chapter marker, so Kavita is parsing it as "Epic Illustrated 002 (Dreadstar - Metamorphosis Odyssey - " for Series. I'm not really sure what this is, so if you can elaborate, maybe we can find a compromise.

A lot of serialized content or cross-overs are sometimes referenced in this way - sometimes in () sometimes like "Epic Illustrated 002 - Dreadstar" - from a parser standpoint I'd almost say ignore any titles after what can be parsed as the number?   But I'm sure something will break that too.

**Comment by majora2007** [comment]
> Millennium would be fine, I actually expected it to just ignore a loose jpg.
Actually, Kavita has the ability to support loose leaf images, so in this case, it's creating a Series for it. 

> A lot of serialized content or cross-overs are sometimes referenced in this way - sometimes in () sometimes like "Epic Illustrated 002 - Dreadstar" - from a parser standpoint I'd almost say ignore any titles after what can be parsed as the number? But I'm sure something will break that too.

So for this, usually it would be "Epic Illustrated" as the series, however, because of the chapter marker, it's getting confused. I don't see a path forward for this one. 

I'm going to deliver the rest of your parser fixes in our latest nightly, which will close this issue. Feel free to create another for the above naming case and I can take a look later.
