### ISSUE TITLE
Container Stops (It Kills Itself)

### ISSUE THREAD

**Issue by LeeThompson** [Kareadita/Kavita#767]
**Describe the bug**
Periodically, the container stops.   I'm not sure why, the last entry in the container's log is:
`/entrypoint.sh: line 31:     8 Killed                  ./Kavita`

**To Reproduce**
I cannot reproduce this on demand, other than it's done this 5 times.

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Chrome
 - Version 0.4.8.1

**Additional context**
Not appearing in Kavita's log but in the container's log:

```
(process:8): VIPS-WARNING **: 20:51:23.074: read gave 2 warnings
(process:8): VIPS-WARNING **: 20:51:23.171: VipsJpeg: Premature end of JPEG file
/entrypoint.sh: line 31:     8 Killed                  ./Kavita
```

**Docker Image**
`kizaing/kavita:latest`
`sha256:4294a507cc310135e4162efa0480d6734b1c840f26b295aa36676c8dd96301e1`

**Comment by LeeThompson** [comment]
I tried turning on debug to see if I could at least see what it's working on but it doesn't seem to write that to disk, it only outputs that to terminal.    I can now reproduce this basically Kavita will crash within a few minutes on my system clearly it's a jpg it doesn't like but I have no idea archive is involved.

**Comment by LeeThompson** [comment]
It looks like this is due to too low of a memory allocation in Docker.   
When it's doing the metadata refresh (cover generation) it uses a *lot* more memory than normal.

If anyone else runs into this, try setting the memory resource limit to 1536 (or even 2048 MB for large libraries) for these peak moments.

**Comment by majora2007** [comment]
Closing as this was solved.

**Comment by fake-name** [comment]
I'm seeing this myself, with 2048MB of ram and 512 MB of swap (in LXC, not docker).
