### ISSUE TITLE
Star Wars (2015) and (2020)

### ISSUE THREAD

**Issue by CoreyVidal** [Kareadita/Kavita#771]
**Describe the bug**
I can't get my Star Wars series' to split. Kavita sees them all as one.

**To Reproduce**
I followed the Kavita instructions:

> If you have multiple comics from different years, you can name them as "Fables 2004" and "Fables 1989". Then in Kavita's UI, you can rename the "Name" field to be "Fables (2004)" and "Fables (1989)" so they are separate series. This workaround is the only way for different releases of the same series to be supported in Kavita.

Have a folder: Star Wars (2015)
Renamed the files in it to all start with:
Star Wars 2015 001 (2015) (Digital).cbr
Do the same thing with folder: Star Wars (2020)
Star Wars 2020 001 (2020) (Digital).cbr

**Expected behavior**
Kavita would know that these are 2 different series.

**Screenshots**
![image](https://user-images.githubusercontent.com/20746389/142562324-dbd20b79-a531-4faa-bce3-f9852b0d4024.png)

Instead, it thinks that I have a comic with 2 issues: issue number 2015 and issue number 2020.

I've tried moving the folders, refreshing/scanning in Kavita, returning the folders, and no luck.

**Comment by majora2007** [comment]
Hmm this should work as I have a case like this myself. Can you delete the star wars entry in Kavita (it will not touch your actual files) and rescan for me?

**Comment by majora2007** [comment]
This has been documented that you need to either rename to "Star Wars 2020" and "Star wars 2015" to separate and rename them in the UI OR wait for v0.5 (you can try it out in nightly) for the local metadata to avoid the file scanner.
