### ISSUE TITLE
Local Metadata Integration

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#774]
Investigate hooking in ComicInfo into the Parser/ProcessFile code so that we can prefer local metadata over file parsing

- [x] Archives: Prefer ComicInfo.xml series, volume, and chapter numbers over filenames
- [x] Archives: Populate people from ComicInfo.xml during metadata refresh
- [x] Epub: Populate people from epub during metadata refresh
- [x] Metadata Refresh: ChapterMetadata should be refreshed from ComicInfo
- [x] Metadata Refresh: SeriesMetadata should be refreshed from aggregated chapterMetadata
- [x] Implement People Cleanup
- [x] Implement people component
- [x] Implement Genre tags
- [x] Add Genre cleanup
- [x] Fix Unit Tests for MetadataService
- [x] Performance Pass for MetadataService/ComicInfo
- [x] GetComicInfo unit tests
- [x] Refactor how checking if updates need to happen occur
- [x] Ability for SortOrder to change Kavita Series during metadata refresh
- [x] Figure out how to handle SortOrder on Series for epubs that fall in a series
- [x] BUG: There is some funky stuff happening with refreshing metadata not being executed when a file changes
- [x] Epub Summary field needs to be converted from html to regular text
- [x] Age Rating implementation
- Rating implementation: This is not possible as there are multiple users. Can be done via a Plugin instead.
- [x] Year implementation on DB

**Comment by majora2007** [comment]
Development Issues:
- [ ] LastModified for Series Refresh Metadata is not working on the first load (aka created then refreshed, it gets skipped). This is because the times are equal to each other on first load, thus short circuit is activated
- [ ] People aren't being returned on ChapterMetadata query (projection isn't working)

**Comment by xcjs** [comment]
@majora2007 I know you're implementing collections based on tags, but would it be possible to also display tags on the series or book page? Thanks!

**Comment by majora2007** [comment]
@xcjs This is not the right place for feature requests. Please use feats.kavitareader.com
