### ISSUE TITLE
Migration to 0.4.8 fails on docker image

### ISSUE THREAD

**Issue by short-circuit** [Kareadita/Kavita#777]
**Describe the bug**
Docker:
During Migration from pre 0.4.8, an unhandled exception is thrown. Container reboots to the same exception continuously.

**To Reproduce**
1. Pull new image
2. Change to new folder (/kavita/config instead of /kavita/data)
3. Recreate container (docker-compose up -d)

**Expected behavior**
Migration to new settings/db without problems

**Additional context**
Logs:
```kavita_1      | Migrating files from pre-v0.4.8. All Kavita config files are now located in config/
kavita_1      | Moving folders to config
kavita_1      | Moving folders to config...DONE
kavita_1      | Unhandled exception. System.IO.IOException: Device or resource busy
kavita_1      |    at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo directory, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
kavita_1      |    at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
kavita_1      |    at System.IO.DirectoryInfo.Delete(Boolean recursive)
kavita_1      |    at API.Services.DirectoryService.ClearAndDeleteDirectory(String directoryPath) in /home/runner/work/Kavita/Kavita/API/Services/DirectoryService.cs:line 238
kavita_1      |    at API.Data.MigrateConfigFiles.DeleteAppFolders() in /home/runner/work/Kavita/Kavita/API/Data/MigrateConfigFiles.cs:line 98
kavita_1      |    at API.Data.MigrateConfigFiles.Migrate(Boolean isDocker) in /home/runner/work/Kavita/Kavita/API/Data/MigrateConfigFiles.cs:line 52
kavita_1      |    at API.Program.Main(String[] args) in /home/runner/work/Kavita/Kavita/API/Program.cs:line 36
kavita_1      |    at API.Program.<Main>(String[] args)
kavita_1      | /entrypoint.sh: line 31:     7 Aborted                 (core dumped) ./Kavita

```

**Comment by majora2007** [comment]
From what I'm seeing in the logs, it is saying a resource is busy. So perhaps it's trying to copy the files out of the old data mount and the hard drive has permission issues or us in use with another move? 

What's the underlying OS?

**Comment by short-circuit** [comment]
OS is Ubuntu Server 20.04.
Don't think it's a permission issue as I have tried copying the folder and setting permissions again, recreating the whole container. Can we pinpoint which file it is actually accessing somewhere?

**Comment by short-circuit** [comment]
By following the instructions in the log from pre 0.4.8 docker mount point:
```
kavita_1      | Checking if migration to config/ is needed
kavita_1      | Migration to config/ not needed
kavita_1      | Generating JWT TokenKey for encrypting user sessions...
kavita_1      | info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
kavita_1      |       Entity Framework Core 5.0.10 initialized 'DataContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: None
kavita_1      | crit: API.Startup[0]
kavita_1      |       WARNING! Mount point is incorrect, nothing here will persist. Please change your container mount from /kavita/data to /kavita/config
```
Obviously the mount point will contain all the files as before.  
Keeping both mount points just stops the container with the above message, so no migration is done from one folder to another.
It says that no migration is needed on the old mount point, so I do not know what the problem may be.
The lsof output is empty, so no access from the `fs`.
I tried with only the database, and it fails too so I guess it is the db.

Should I start with a fresh configuration maybe?


Thank you for your time BTW, I greatly enjoy Kavita!

**Comment by majora2007** [comment]
Hmm are you saying that, regardless of Kavita running, you can't copy the files from the mount point out?

Ideally, this would be the easiest way:
1. Copy all the files from the mount point out to another folder elsewhere
2. Open the appsettings.json and change: 
![image](https://user-images.githubusercontent.com/735851/142887761-d755130a-1e6f-4cc3-b3e7-baf9594db91e.png)
DefaultConnection and Path need to start with "config//"
3. Ensure your container has the correct mount point (config/)
4. Copy the backed up files (with the modifications above) to the mount point
5. Start Kavita

This is essentially what the migration is doing. This should work. Let me know, else yeah, you can start from scratch. If you have a lot of progress, I can help you extract it from the DB into a csv.

**Comment by short-circuit** [comment]
Oh boy, that was it.
I am curious to why the appsettings.json could not be accessed by Kavita as it is the only process going for that file.

Anyway, thank you again. It is working now!
