### ISSUE TITLE
Problem with first file in cbr

### ISSUE THREAD

**Issue by Dunkler2Engel** [Kareadita/Kavita#783]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

It is not a bug but not a request, at least not entirely.
I have my Mangas with the file that have the cover named "!000.jpg".
By having the "!" The first thing always comes as the first file either when opening the cbr with some program or when opening it with Winrar.
But not with Kavita, this file not show anywhere would there be any option to modify it so that it gets it first? Changing all my rar files is unthinkable I have too many.

Greetings

**Comment by majora2007** [comment]
Sorry, let this one slip. I will take a look, but the code I use to sort emulates Windows OS sorting, however, it's very complicated and I'm not super keen on trying to modify it given how critical it is to Kavita. I've tried in the past and have never been successful.
