### ISSUE TITLE
Issues reading zip/cbz files on rpi3/Docker

### ISSUE THREAD

**Issue by jcoady9** [Kareadita/Kavita#796]
**Describe the bug**
When reading a chapter the reader will only display the first page. When moving to further pages leads to a black screen with the loading spinner. When I check the console for the browser it looks like the server returned a HTTP 500 response when it tried fetching the second page. I have only noticed this with zip and cbz files. I have not tried other file types.

**To Reproduce**
1. Open a chapter to read in web reader
2. Click right-arrow button or move tick on progress bar to 2nd page
3. Web reader at this point will still show the image for the first page
4. Click right-arrow button or move tick on progress bar again to 3rd page
5. Web reader will go black and display progress spinner

**Screenshots**
![image](https://user-images.githubusercontent.com/6423746/143792215-bf162e5b-9187-4356-bd9e-ad4e5c312504.png)

**System Info:**
 - Hardware: Raspberry Pi 3
 - OS: Raspbian v10
 - Docker: v20.10.9
 - Image: kizaing/kavita:latest
 - Browser: Firefox/Edge
 - Version: 0.49.1

**Additional context**
I am running Kavita using the latest docker image on a Raspberry Pi 3.

**Comment by majora2007** [comment]
Interesting, I've never seen that error before, but it is totally a UI issue. Can you please share with me the archive (either here or on discord)? From the error, it looks like the image is corrupted.

**Comment by jcoady9** [comment]
Attached is one of the smaller archive files (zip) I've tested. Let me know if you need anything else.

[A Story About A Grampa And Granma Returned Back To Their Youth. 01.zip](https://github.com/Kareadita/Kavita/files/7621924/A.Story.About.A.Grampa.And.Granma.Returned.Back.To.Their.Youth.01.zip)

**Comment by majora2007** [comment]
I just tested it and it renders fine. Can you send me your logs please? For example, clear your logs, try to read, then send them to me (you can download from web ui in admin settings)

**Comment by jcoady9** [comment]
I tried downloading the logs from the system tab on the admin but kept getting a 400 [object blob] message so I've puttied into the raspberry pi and the running container and copied the log from there (after clearing the log) and have attached. 

Logs should show from the point of selecting the chapter and then scrolling through each page.

[kavita.log](https://github.com/Kareadita/Kavita/files/7622454/kavita.log)

![image](https://user-images.githubusercontent.com/6423746/143974130-ab6cd21c-7789-4478-8d4e-a2fdb0a11dcb.png)

**Comment by majora2007** [comment]
I found this in the logs:
There was a problem extracting /manga/A Story About A Grampa And Granma Returned Back To Their Youth/A Story About A Grampa And Granma Returned Back To Their Youth. 01.zip to /kavita/config/cache/6122/System.UnauthorizedAccessException: Access to the path '/kavita/config/cache/6122/01.jpg' is denied.
 ---> System.IO.IOException: Operation not permitted
 
 This implies that Kavita does not have write access to the cache directory. Please make sure you grant read and write access for Kavita to the location it is installed.
