### ISSUE TITLE
Federated Kavita with ActivityPub support

### ISSUE THREAD

**Issue by aschrijver** [Kareadita/Kavita#797]
It looks like Kavita is ideally suited to add federation support via [ActivityPub](https://www.w3.org/TR/activitypub/) protocol, so that self-hosted instances start to federate together. I'll allow different people to share resources, follow each other, create multiple communities and groups, and comment, rate, review and do other social interactions on the collections of their friends.

There's a number of _somewhat_ similar Fediverse applications already and multiple ways you might facilitate cool integrations to other federated apps, such as [Mastodon](https://joinmastodon.org/), [Pixelfed](https://pixelfed.org/), [Lemmy](https://join-lemmy.org/) and [Peertube](https://joinpeertube.org/).

Here's [Fediverse Party](https://fediverse.party) website to see some apps, and the [ActivityPub Application Watchlist](https://git.feneas.org/feneas/fediverse/-/wikis/watchlist-for-activitypub-apps) with many more.

Btw, found you via [Hacker News](https://news.ycombinator.com/item?id=29377450).

**Comment by majora2007** [comment]
Welcome, I'm glad that post did better than mine. Please create a feature request on our dedicated site: https://feats.kavitareader.com. I use that site for feature requests rather than Github.

**Comment by aschrijver** [comment]
Done, thank you!
