### ISSUE TITLE
Any chance of using an ORM for out-of-box TCP/IP DB connection support besides SQLite?

### ISSUE THREAD

**Issue by immanuelfodor** [Kareadita/Kavita#809]
When the SQLite file is stored on an NFS mount (e.g. a Kubernetes cluster with multiple nodes), the DB is prone to corruption as NFS is not fully Posix compliant and SQLite depends on Posix file locking. I've seen many projects aiming for a lightweight portable DB solution with SQLite (Plex, Emby, Jellyfin, Radarr, etc) but it would be great to have support for at least one of MySQL/MariaDB/PostgreSQL with Kavita. Maybe using an ORM could make the transition easier as it usually provide DB engine support by default. The config option is already there, we could just use another DB connection string with a format, for example `username:password@IP:port/dbname`.

**Comment by majora2007** [comment]
Feature requests need to be posted on https://feats.kavitareader.com. Thank you.

**Comment by immanuelfodor** [comment]
Oh, I was not aware of that, thanks!

**Comment by gramakri** [comment]
https://feats.kavitareader.com/ is gone . Looks like https://github.com/Kareadita/Kavita/discussions/categories/ideas is the new place
