### ISSUE TITLE
OOM Crashes during library scan

### ISSUE THREAD

**Issue by fake-name** [Kareadita/Kavita#824]
**Describe the bug**

Kavita consistently crashes during library scan due to OOM errors on my library.

```
info: API.Services.Tasks.ScannerService[0]
      [ScannerService] Processing series Ruse
Killed
```

**To Reproduce**
1. Try to add a very large library (971 GB, in this case)
2. Wait
3. OOM Crash

This is fairly hard to reproduce, as it only seems to occur after hours of scanning. I'm going to give the server another 2GB of ram, though I don't have a lot of available unused RAM on the hypervisor I'm running this on.

**Expected behavior**

I'd expect (or at least hope) that kavita would either run the scanning in a separate process so the OOM killer wouldn't completely nuke the server, or monitory memory pressure somehow. 

OTOH, it can be very difficult to manage that kind of thing in higher level languages. Some of my python projects have similar issues that are a pain to deal with.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04, running in a LXC container with 2048 MB RAM, 512 MB swap.
 - Browser: None 
 - Version: `Kavita - v0.4.9.0`

**Comment by fake-name** [comment]
Watching the system in question during a scan, there appears to be basically linear growth in memory usage as the scan progresses. 

This sounds a lot like some result of the scan is in memory stored on a per-file basis. This is problematic for large libraries (the directory I'm scanning for this test is *one of my smaller ones*).

**Comment by majora2007** [comment]
Can you please attach your logs? I need to understand better (ideally in DEBUG mode)

I think if you have a large set of files, it would be ideal for the first scan to give more than 2GBs of RAM. The first scan is the heaviest and also does cover extraction. Working with images will use larger amounts of RAM without much control. 

I have 20k files (750GB) for one of my libraries and have no issues during scan. First scan jumps past 2GB (if you have 3GB, you should likely be fine) but subsequent scans only take up to 400MB of extra ram from idle (130MB).

**Comment by majora2007** [comment]
I'm going to close this issue since no response for 3 months. Please repopen if you are still having issues. We have multiple users with 100k+ books that are able to do filescans.
