### ISSUE TITLE
Parser did not work for Books

### ISSUE THREAD

**Issue by sissiwup** [Kareadita/Kavita#825]
The most of the books are not in a series. I have sorted my books in folders.
I want to see the foldername and the title. How can I manage that.

I have tried manga, comic and book.
There are books connected only over the title (I use pdf as format).
There are covers swapped. There is a book with a cover from another book. No collection! Only this book in the series.

**Comment by majora2007** [comment]
Hello, if you want your epub files to be grouped by a series, the need to be tagged appropriately.

https://wiki.kavitareader.com/en/faq/folders-and-file-structure/ebooks

If you have pdf or non-epub books, then file naming is going to be critical. Library type is just for how Kavita chooses to parse the filename. Comic will use more comic conventions (like TBP, Issue, etc), Manga uses volumes, chapters. Book tries with Manga (for light novels) then uses epub metadata if nothing could be parsed out.

You're going to need to provide more information to help me help you. Like filenames, type of library, what it's being parsed as.

**Comment by majora2007** [comment]
Closing until further information.
