### ISSUE TITLE
Add OpenID connect support or allow user login by header

### ISSUE THREAD

**Issue by tomlawesome** [Kareadita/Kavita#830]
https://feats.kavitareader.com/ is down, I would have posted this feature request there otherwise. 

I would like to request support for OpenID connect. Kavita is fantastic. I wish to put it behind my authentication system, Authentik/Authelia and allow a user to use their existing Single Sign on. 

If OpenID connect is supported, it's easy. If header login (or similar mechanism) were supported, it would be possible to login a user (with auth. turned off in settings). 

SSO is really important for self-hosting in my experience, because friends/family don't want lots of logins!

Great app either way, many thanks.

**Comment by majora2007** [comment]
I just fixed the issue, please re-request there. Appreciate checking there first.

**Comment by gruselglatz** [comment]
Down again, and what happend with the idea?

**Comment by majora2007** [comment]
All feature requests are on the discussions tab of GitHub. The existing feature requests were migrated.

**Comment by gruselglatz** [comment]
I found it already and link this one here, if someone is also searching for it: https://github.com/Kareadita/Kavita/issues/2518
