### ISSUE TITLE
Enhancement for mobile readers (700px window width behavior)

### ISSUE THREAD

**Issue by mvalley21** [Kareadita/Kavita#831]
Hi,

I noticed that mobile readers always get defaulted to 0% margin if their screen size is below 700 pixels.

This code is located in UI/Web/src/app/book-reader/book-reader/book-reader.component.ts: 
 if (windowWidth <= 700) {
      margin = '0%';
    }

Could we make that 700 configurable in settings so users who are just on the edge can avoid the auto 0% margin behavior?

**Comment by majora2007** [comment]
Hi, just curious if this is still an issue for you? I know I haven't changed the auto margin pixel limit, but I did change the default to 5%. Do you still find this a need to have the pixel width customizable for you?

**Comment by mvalley21** [comment]
I think a configurable default margin would still be ideal. It's a relatively low priority since it's easy enough to change the code.

**Comment by majora2007** [comment]
Yes I understand that the ideal would be a configurable setting, what I'm asking is this still an issue with the 5% default now?

**Comment by majora2007** [comment]
yes it is.

**Comment by mvalley21** [comment]
Thanks, looks like your 5% change fixed it on the iPhone 13 pro max screen.

**Comment by majora2007** [comment]
Sweet, I'll close this issue for now. I have other enhancements in mind that will be more ideal. Thanks again for quickly testing.
