### ISSUE TITLE
Special issues with no issue number assume the folder for their series naming even if it is not related

### ISSUE THREAD

**Issue by apoapostolov** [Kareadita/Kavita#834]
Comics without an Issue number such as the case below fall back to other methods of catalogization that uses the name of the folder instead. 

I had the same issue with the following comics (using their names, not localmetadata contained inside).

EDIT: This has been always before my eyes but I was blind to it. This affects the Specials only, not every comic without an issue.

E:\/OneDrive/Comics/~WEEKLY\2021.11.03 Weekly Pack\2021.11.03 INDIE Week\Stranger Things - Winter Special SP01 (2021).cbr
E:\/OneDrive/Comics/~WEEKLY\2021.02.03 Weekly Pack\2021.02.03 INDIE Week\DIE!namite - Valentine's Special - Our Bloody Valentine (2021).cbr
E:\/OneDrive/Comics/~WEEKLY\2021.02.03 Weekly Pack\2021.02.03 INDIE Week\Vampirella - Valentine's Day Special (2021).cbr
E:\/OneDrive/Comics/~WEEKLY\2021.02.10 Weekly Pack\2021.02.10 INDIE Week\Red Sonja Valentine's Special (2021).cbr
E:\/OneDrive/Comics/~WEEKLY\2021.07.07 Weekly Pack\2021.07.07 INDIE Week\2000AD Sci-Fi Special (2021).cbr
E:\/OneDrive/Comics/~WEEKLY\2021.08.11 Weekly Pack\2021.08.11 DC Week\Batman Special Edition.cbr
E:\/OneDrive/Comics/~WEEKLY\2021.08.11 Weekly Pack\2021.08.11 DC Week\Batman and Robin...and Howard-Amethyst - Princess of Gemworld Special Edition Flipbook.cbr
E:\/OneDrive/Comics/~WEEKLY\2021.08.11 Weekly Pack\2021.08.11 DC Week\Suicide Squad Special Edition.cbr
E:\/OneDrive/Comics/~WEEKLY\2021.08.11 Weekly Pack\2021.08.11 DC Week\Teen Titans - Beast Boy Loves Raven Special Edition.cbr

As you can see, the common between them is the lack of any identifier of issue and in some cases lack of year. This should be handled by making each of these comics their own series and assuming Issue #1 for  that series. 

![image](https://user-images.githubusercontent.com/4083812/145085532-bfd2f85c-23cb-4181-bdf2-aacb767a26ab.png)

**Comment by majora2007** [comment]
I know I've been sitting on this one for a while, sorry about that. Can you help me understand what you are expecting vs what is happening? I've read it a few times, but not fully grasping if this is a misunderstanding or a bug.

**Comment by majora2007** [comment]
This has been stale for a while. Please reopen with information requested.
