### ISSUE TITLE
Ability to use Tome instead of Volume for European comics

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#835]
https://feats.kavitareader.com/posts/18/ability-to-use-tome-instead-of-volume-european-way

**Comment by hbooo** [comment]
Thanks for implementing this in Kavita!

I got another case for Asterix :
Astérix T.01 - 1961 - Astérix le Gaulois.cbr

Also parsing on this one is incorrect : Tintin - T22 Vol 714 pour Sydney.cbz

Detected name is "Tintin - T22" instead of Tintin

**Comment by majora2007** [comment]
@hbooo This is on the nightly?

**Comment by hbooo** [comment]
yes it is

**Comment by majora2007** [comment]
Okay I took care of it. It will release on next push.
