### ISSUE TITLE
Failure to scan directory due to PathTooLongException

### ISSUE THREAD

**Issue by angry-kittten** [Kareadita/Kavita#836]
**Describe the bug**
Attempts to scan specific directory immediately fail

**To Reproduce**
1. Go to 'Add Library'
2. Add Specified Directory
3. Kavita attempts library scan
4. Library scan immediately fails

**Expected behavior**
Library should get scanned

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Safari
 - Version: 0.4.9.1

**Additional context**
[kavita_logs_12_08_2021(1).zip](https://github.com/Kareadita/Kavita/files/7678437/kavita_logs_12_08_2021.1.zip)

[history.txt](https://github.com/Kareadita/Kavita/files/7672509/history.txt)

**Comment by majora2007** [comment]
Do you have any logs from when you did this to help me debug?

**Comment by angry-kittten** [comment]
I switched kavita over to debug mode, restarted it, attempted a scan of the directory, downloaded the logs, and attached it to the original post. Let me know if you need anything else.

**Comment by majora2007** [comment]
So from looking at the logs, I see that series are being added to your library. 

I also see you have some corrupted PDFs (first time seeing this with Kavita, but I don't use pdfs):
/library/History/2-Ancient-e-Classical/Asia, Indo-Europe/Charles F. W. Higham - Encyclopedia of Ancient Asian Civilizations.pdf

DocnetLoadDocumentException: unable to open the document: ErrorCode=3, ReasonPhrase=file not in PDF format or corrupted


But I def see it adding series, you can see by these messages:
Processing chunk 26 / 137 with size 50. Series (1300 - 1350
[ScannerService] Added 105 series in 75838 milliseconds for History

The only thing I can think of is It might be slow because of a) networked storage or b) you have pdf and epubs next to each other so each pdf is likely being generated into a series of it's own making all the looping slower.

**Comment by angry-kittten** [comment]
I was just watching the portainer logs while it scanned that directory and came across this, it seemed to stop after hitting this one.

         at API.Services.Tasks.ScannerService.ScanLibrary(Int32 libraryId) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/ScannerService.cs:line 218,
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task),
warn: Hangfire.AutomaticRetryAttribute[0],
      Failed to process the job 'e1a9bd10-0ff1-4b8e-8a8d-d42aa983cca6': an exception occured. Job was automatically deleted because the retry attempt count exceeded 0.,
      System.IO.PathTooLongException: The path '/library/History/5-Ancient-and-Classical-Civilizations-Series/Royal Inscriptions of the Neo-Assyrian Period' is too long, or a component of the specified path is too long.,
         at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext(),
         at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items),
         at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength),
         at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source),
         at System.IO.Directory.GetDirectories(String path),
         at API.Services.DirectoryService.TraverseTreeParallelForEach(String root, Action`1 action, String searchPattern, ILogger logger) in /home/runner/work/Kavita/Kavita/API/Services/DirectoryService.cs:line 382,
         at API.Services.Tasks.Scanner.ParseScannedFiles.ScanLibrariesForSeries(LibraryType libraryType, IEnumerable`1 folders, Int32& totalFiles, Int64& scanElapsedTime) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ParseScannedFiles.cs:line 169

**Comment by majora2007** [comment]
Interesting, the only reason that would be thrown is if the path is longer than 32,767 characters OR the underlying OS throws it. I think only Windows would throw it if you hadn't enabled long paths. 

This is very interesting, I'll have to try reproducing.

**Comment by angry-kittten** [comment]
Its currently being hosted on docker in ubuntu server 20.04 with the data on an ext4 formatted wd red plus 4tb 5400rpm drive. Can't say I've had anything else on it throw this issue and I have some other files in my media collection with far longer names

**Comment by majora2007** [comment]
I can't reproduce this. I tried with this file, scanning at the first level of the directory and no exceptions were thrown. 

`C:\manga\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\supercalifragilisticexpialidocious\file_29.jpg`

**Comment by majora2007** [comment]
This issue cannot be reproduced. Please reopen if you have any ideas on how to reproduce it.
