### ISSUE TITLE
Main folder as issue name ?

### ISSUE THREAD

**Issue by aroundmyroom** [Kareadita/Kavita#848]
I am a Ubooquity 'runner'  (almost) and one of of the things I miss in the Kavita part functionality is that not all my comics are grouped as series correctly

ie 

Alex - A04 - De Reizen Van Alex Griekenland 2
421 - 01 - Koude Oorlog
421 - 02 - Groetjes Uit De 7de Hemel

Those names are seen as seperate comics and displayed 'alone'  not in the series. 
As I do not know the whole naming convention part yet I wonder what I could change to have those comics (which resides per title in 1 folder) to be seen as issue

the most simples part for me would that
main folder = comic name / issues
sub folder of the main folder of that comic = special

This takes away that names of comics and or wrong conventions are shown incorrectly especially as comics are from all around the world in various languages

If there are options or ways to get this right I like to read them or pinpointed to it I would be grateful

**Comment by majora2007** [comment]
Hello, welcome from Ubooquity. Unfortunately, this is not in my plans for Kavita. I would suggest instead getting familiar with our naming conventions, which you can find on our [wiki](wiki.kavitareader.com).
