### ISSUE TITLE
question: how to name to get chapter title too?

### ISSUE THREAD

**Issue by benpoe** [Kareadita/Kavita#864]
i have comics like this: seriestitle -01 - chapter name. 
this gets parsed like seriestitle/issue 01.
is it possible to get the chapter name too like seriestitle/ 01 (chapter name)

**Comment by majora2007** [comment]
Chapter name is not supported with filename parsing due to having too many inconsistencies and false positives. Instead, it is supported by parsing embedded ComicInfo.xml files. This is planned for the next release (v0.5).
