### ISSUE TITLE
Comics series and magazines yearvolumes?

### ISSUE THREAD

**Issue by benpoe** [Kareadita/Kavita#866]
i have comics with multiple series (or even better example) magazines with different year volumes.

how should they be named to have it sort correctly per year/series? like. 
mad magazine/year 1980/ issue 1

not sure if this is a feature request or not...

**Comment by majora2007** [comment]
Sorry I missed this, some how you opened this and the label didn't get added. 

What you have as an example will work perfectly. Just don't put them in () else they will be merged together as one unified series.
