### ISSUE TITLE
comics specials are not parsed as special

### ISSUE THREAD

**Issue by benpoe** [Kareadita/Kavita#868]
i've been testing using the docker latest image 
Version
0.4.9.1
**Describe the bug**
when a comic has the special/oneshot in the name with a #, the parser does not process it as special. instead it add it as an issue

**Expected behavior**
i'd expect the specials/oneshots sorted into the specials-tab

**Screenshots**
(https://ibb.co/P61VQHr
https://ibb.co/r7vt9QR
https://ibb.co/zrwtvMZ)

**Additional context**
removing the # does mark them as special, but they will be sorted in their own titile.

https://ibb.co/p4cMJNv
https://ibb.co/6nsvYJC

**Comment by majora2007** [comment]
This is not a bug, for cases like this, use the special marker SP or special keywords like One-Shot, Artbook, etc. You can find a list on our wiki.
