### ISSUE TITLE
Horizontal Manga Pages

### ISSUE THREAD

**Issue by PostiFROW** [Kareadita/Kavita#872]
Some manga pages are horizontal like in Akira and Spy x Family, so, when you see it in kavita, you only see a portion of the page. The only fix currently is manually rotating the pages if they're individual pages in a folder. It'll be trickier for pdfs and even harder for .cbr or .cbz files. I think one fix would either be allow a rotate button in the reader so the user could rotate when they need to, or just allowing both horizontal and vertical image resolutions.

**Comment by majora2007** [comment]
Can you show me an example of what you're describing? When cover images are found (aka spans two pages side by side), there are multiple ways to split them to keep within reader frame. Likewise, if you're reading long strips, like with a webtoon, we have a webtoon reader.

**Comment by PostiFROW** [comment]
Some pages in a manga take up the whole page, but the panel is actually sideways including text and text bubbles. Here are a few examples:
![akira_6_p003-p004](https://user-images.githubusercontent.com/95349960/147398859-7e4df278-e10f-41b1-b27d-222cc90204db.jpg)
![akira_6_p429-p430](https://user-images.githubusercontent.com/95349960/147398868-afe24e7b-ab2b-478d-8436-cfcba103623c.jpg)
![akira_6_p385-p386](https://user-images.githubusercontent.com/95349960/147398870-b70a4a40-4dc8-4eef-bcd1-e6ff836c403e.jpg)
![akira_6_p369-p370](https://user-images.githubusercontent.com/95349960/147398872-7a614cf4-ae7c-41a8-ac01-232da72d9478.jpg)
![akira_6_p341-p342](https://user-images.githubusercontent.com/95349960/147398873-da408b55-a870-4504-8770-9c10657522e5.jpg)
Here are a few screenshots of how it looks like on the Kavita Desktop reader, and I've tried all the combinations of splitting with scaling and they all look the same. They all only show the top right corner of the page and the only way to fix it would be to rotate the pages manually, meaning it would be hard for rotating pdfs and I don't even think you can rotate .cbz or .cbr files.
![Screenshot 2021-12-25 233201](https://user-images.githubusercontent.com/95349960/147398946-b4d17633-39b6-4f29-8af4-3cbaeb6eb544.png)
![Screenshot 2021-12-25 233250](https://user-images.githubusercontent.com/95349960/147398949-c606a5b9-c66d-4466-8265-33e919aebb88.png)

**Comment by colino17** [comment]
I'm also experiencing this issue with a comic with horizontal pages:
![Fables - The Wolf Among Us (2014-) 001-002](https://user-images.githubusercontent.com/51090962/147882464-7bddb411-0bfb-43c2-abc3-6cce0e26ad46.jpg)

**Comment by colino17** [comment]
![Screenshot from 2022-01-02 12-31-48](https://user-images.githubusercontent.com/51090962/147882553-3469de43-fe6a-4e43-99be-8795505d2f7c.png)

**Comment by majora2007** [comment]
This is def a bug with the new Fit to Screen splitting mode. If anyone is on discord, please pm me the files here so I can test on them as well as my own. 

Also can I assume this is desktop?

**Comment by PostiFROW** [comment]
I sent, you a friend request on discord. My user name is bruhmoment#4707 and this problem occurs on both desktop and iphone.
