### ISSUE TITLE
Error processing known good epubs

### ISSUE THREAD

**Issue by romwil** [Kareadita/Kavita#876]
Log is showing: 

today at 5:15:38 PMwarn: API.Services.Tasks.ScannerService[0]
today at 5:15:38 PM      [Scanner] Could not parse series from /library/Calibre Library/Adams Douglas/HHGTTG 4 (142)/HHGTTG 4 - Adams Douglas.epub
today at 5:15:38 PMwarn: API.Services.BookService[0]
today at 5:15:38 PM      [BookService] There was an exception when opening epub book: /library/Calibre Library/Adams Douglas/HHGTTG 1 (141)/HHGTTG 1 - Adams Douglas.epub
today at 5:15:38 PM      System.IO.InvalidDataException: End of Central Directory record could not be found.
today at 5:15:38 PM         at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
today at 5:15:38 PM         at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
today at 5:15:38 PM         at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
today at 5:15:38 PM         at VersOne.Epub.EpubReader.OpenBookAsync(String filePath)
today at 5:15:38 PM         at API.Services.BookService.ParseInfo(String filePath) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 404

for all epubs in the directory structure.  After scanning all of the folders, only PDFs that were co-mingled in with the epub files were visible. 

Running Docker : latest on unraid

**Comment by majora2007** [comment]
This issue is saying that the underlying epub archive is missing metadata and the library Kavita uses to read the epub can't find the end of the file, so it can't read it. 

"System.IO.InvalidDataException: End of Central Directory record could not be found."

I believe Calibre has a solution to fix this issue.

**Comment by romwil** [comment]
This is a huge library of epubs. No epubs are picked up by Kavita at all.
Hundreds of them.

These are valid epubs. Are we saying that Kavita cannot process epubs
unless they have a particular set of metadata included?  I think that
becomes a limitation of the platform.

Will

**Comment by majora2007** [comment]
I'm not trying to say they aren't valid, I'm saying that the archive doesn't tell where the end of the file is. Imagine if you had a stream of data

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

This is 2 files on the disk. I ask you to read only the first file. How can you without the metadata to tell where the end is? This is the problem that is occurring. If not a single epub of yours is reading, perhaps there is some sort of permission issue on the files that is coming into play?

Can you send me a file please? I would like to validate everything on my system. I have ran into the end of directory problem a few times, but not very often in my own library.
