### ISSUE TITLE
Issue with chapter processing and books containing images

### ISSUE THREAD

**Issue by GitKepler** [Kareadita/Kavita#877]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
There is an issue when a book is imported as a folder of PNG/JPG files. The chapters are not properly processed:
With the following folder structure, everything is working as intended:
```
test
├───author_name
│       book_name.cbz
│
└───other_author_name
        other_book_name Ch. 1.cbz
        other_book_name Ch. 2.cbz
```
When I tried to unzip the cbz files hoping to increase the loading speed (some of them are over 100MB and take ~30s to open on a raspberry pi), I ended up with the following folder structure:
```
test
├───author_name
│   └───book_name
│           001.png
│           002.png
│           003.png
│
└───other_author_name
    ├───other_book_name Ch. 1
    │       001.png
    │       002.png
    │       003.png
    │
    └───other_book_name Ch. 2
            001.png
            002.png
```

In the second case, when the book has multiple chapters, (i.e. books from other_author_name), I have the expected result (i.e. 2 chapters with 3 & 2 pages each):

![2022-01-02 023537](https://user-images.githubusercontent.com/23261056/147863813-902fdbb7-a88c-4447-bf8f-960013feb021.png)

However, when the book only has 1 chapter (or if the author only has 1 book associated), I have an unexpected result (seemingly 3 "chapters" with 1 page each):

![2022-01-02 023925](https://user-images.githubusercontent.com/23261056/147863831-2729a378-b6ba-43e6-b44b-d22a589204fe.png)

**To Reproduce**
1. Create a library (type= manga) folder with a structure similar to the one above
2. Scan the library
3. Open one of the books from one of the authors

**Expected behavior**

In the case of test/author_name/book_name, I would expect only 1 chapter to be present (taking the name of the book would be ideal) with 3 pages inside instead of 3 chapters with 1 page each

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox 95
 - Version 0.4.9.1

**Comment by majora2007** [comment]
The later result is because Kavita can't parse out a chapter from the file or folder. So it assumes it's a special and thus each page is treated like that. This is expected behaviour on how Kavita performs grouping. 

The solution would be put Chapter (or Volume) 1 in a folder above the images so it groups correctly.
