### ISSUE TITLE
'Cannot read' for PDFs

### ISSUE THREAD

**Issue by akashkj** [Kareadita/Kavita#879]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
Unable to read pdf files

**To Reproduce**
Add the pdf in the library folder

**Expected behavior**
pdf readable 

**Screenshots**
![image](https://user-images.githubusercontent.com/14318173/147872245-fe334196-91bb-4d0b-9c67-19b3f3ed4005.png)

**Desktop (please complete the following information):**
 - OS: Docker/ubuntu 20/arm64
 - Browser - Chrome
 - Version - 0.4.9.1

**Smartphone (please complete the following information):**
 NA

**Additional context**

**Comment by majora2007** [comment]
This is a known issue in the latest release (v0.4.9.1). It has been fixed in the latest nightly and will be pushed out in the next stable.

**Comment by DjidaneJex** [comment]
I have the same issue on docker/arm64 image with version 0.5.4.0

**Comment by majora2007** [comment]
@DjidaneJex please create your own ticket. It would not be due to the same issue. Without a ticket, it wont be looked into. Thanks.
