### ISSUE TITLE
Backcover is used as thumbnail instead of the cover when both are available

### ISSUE THREAD

**Issue by Zzo911** [Kareadita/Kavita#892]
**Describe the bug**
When a epub contains both a cover and a backs over, Kavita uses the backcover as the epub thumbnail instead of the (front) cover.

**To Reproduce**
1. Open a epub with Sigil
2. Check the **manifest** and **spine** tags in the OPF file :
```
<manifest>
  <item id="cover" href="xhtml/00_cover.xhtml" media-type="application/xhtml+xml"/>
  <item id="backcover" href="xhtml/24_backcover.xhtml" media-type="application/xhtml+xml"/>
  ...
  <item id="cover-image" href="images/cover.jpg" media-type="image/jpeg"/>
  <item id="back" href="images/backcover.jpg" media-type="image/jpeg"/>
  ...
</manifest>
<spine toc="ncx">
  <itemref idref="cover" linear="no"/>
  ...
  <itemref idref="backcover"/>
  ...
</spine>
```
3. Refresh Metadata of the epub

**Expected behavior**
The cover should be used for the thumbnail instead of the backcover.

**Desktop (please complete the following information):**
 - OS: Docker on Synology NAS
 - Browser : Safari 15.2
 - Version : 0.4.9.1

**Comment by majora2007** [comment]
Can you pm me this book please on discord? I can take a look.

**Comment by Zzo911** [comment]
PM sent.
I've started a 2nd instance of docker using the nightly (0.4.9.30) and I confirm the same issue, the back cover is used as the thumbnail.
Regards
