### ISSUE TITLE
Admin dashboard accessible by unprivileged user

### ISSUE THREAD

**Issue by TheSelox** [Kareadita/Kavita#894]
**Describe the bug**
While logged in with an unprivileged user it is possible to manually access `kavita.example/admin` .
The general settings are not available but it is possible to access the library and create a **new admin user**.

**To Reproduce**

1. Log in with any non-admin user
2. manually enter `kavita.example/admin` in the address bar of the browser

**Screenshots**
![image](https://user-images.githubusercontent.com/91619275/148265060-b5b9a3ac-2ebb-40b8-82ce-53e0a9ef3f2f.png)
![image](https://user-images.githubusercontent.com/91619275/148264492-e0f42cbc-17b5-48a5-bf40-3a87c8ed9eed.png)

**Mitigation**
Block access to `/admin` via reverse proxy.
nginx example:

```
location /admin {
  return 404;
}
```

**Comment by majora2007** [comment]
Thanks for reporting this, I'm not sure how both the UI and the backend missed the admin check. I've written a fix for this and will get it out ASAP.

**Comment by majora2007** [comment]
This has been released as a hotfix. Thanks again.
