### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#912]
- [x] Update image on demo to show in Dark mode
- [x]  Show better naming conventions as well as how to handle series with multiple years
- [x] Update Filtering page to show new filters and how they work
- [x] Update Metadata
- [x] Series Detail to show new tags
- [x] Edit Series
- [x] Chapter/Issue Detail
- [x] Creating a library explain what each library option does (Manga, Comic, Book)
- [x] Adding a library, put a line to tell them to not add series directly as if it's empty, scanner will abort
- [x] Metadata to populate series (summary/language) comes from first chapter in series. For Books, it's different than non-book library types. (See FirstWithChapters)
- [x] Tachiyomi Extension
- [x] NSSM add exact commands for a Quick Start since many users seems to be less literate in self hosting
- [x] Reading Lists
- [x] Filtering Update
- [x] Series Detail Update
- [x] OPDS Update
- Settings Update (not doing, waiting for v0.5.2)
- [x] Scanning and Refreshing Metadata Update to discuss ComicInfo.xml
- Book Reader mention Fullscreen mode (not doing, waiting for v0.5.2)
- Web Reader mention Fullscreen mode (not doing, waiting for v0.5.2)
- [x] Web Reader Bookmarks needs filling out
- [x] Update favicon on wiki to be Kavita's

v0.5.1 Stuff:
- [x] Invite User flow
- [x] Account Email stuff
- [x] Keyboard shortcuts for Manga/Book reader
- [x] FAQ - Stat collection, add the 2 new fields

**Comment by tocotronaut** [comment]
What about a new Task: 

- [ ] Update wiki "Install on MacOS"?

it was not easy for me, to install Kavita in Macos.
**But it now works** on my intel mac mini 2018 with (most recent) macOS 12 Monterey.

this is what i have done:

1. Download Kavita. Easy.
2. Unpack Kavita. Okay.

3. Make Kavita executable. 
In Terminal: sudo chmod +x ~/Downloads/Kavita/Kavita

4. Disable Gatekeeper for Kavita
In Terminal: attr -r -d com.apple.quarantine ~/Downloads/Kavita

5. i needed to copy the Folders config & wwwroot directly inside my user Folder. (~/)
while Kavita Folder stays in ~/Downloads/Kavita
(someone said this is unneccesary - maybe its only a little mess i did on MY system)

Sorry for my bad English.
toco
