### ISSUE TITLE
Investigate: When series are parsed by volume, prompt to add single issue via info option does not prompt reading list addition

### ISSUE THREAD

**Issue by DannyLancaster1** [Kareadita/Kavita#918]
**Describe the bug**

When the series is parsed by volume such as "Detective Comics vol. 1" the only way to navigate and access each issue is by the Info option. It also gives the option to add single issues to a reading list but the prompt to add to an existing reading list or a new one does not come up. This is a problem I'm having on **Google Chrome** and **Safari Web Application** on IOS.

**To Reproduce**
1. Go to a library where something is parsed by volumes and can navigate the issues or books contained in a volume
2. Click on the options of a single issue and click "info" and attempt to reach reading list prompt
3. This is where nothing happens for me, no prompt to add or create a reading list.

**Expected behavior**
When selecting a comic book issue from a volume and adding to a reading list should bring up the prompt to do so but does not on either my Google Chrome browser or Safari Web Application.

**Screenshots**
![image](https://user-images.githubusercontent.com/1707714/148670977-4bbdbb8d-076e-4afa-81bd-eb7c6a170fe4.png)
![image](https://user-images.githubusercontent.com/1707714/148670986-8410aec1-41cd-4ec1-bbae-dcd1062ca6ff.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 0.4.9.2

**Smartphone (please complete the following information):**
 - Device: Iphone 13 Ori
 - OS: [iOS15.11]
 - Browser Safari Web Browser 

Please let me know if you need anything else from me, I am currently on the Kavita Discord @Danko

**Comment by majora2007** [comment]
I like the idea, but please move it to feats.kavitareader.
