### ISSUE TITLE
Scanning a library that has lost access/connectivity to it's Shared Folders will results in loosing all progress related to it's content

### ISSUE THREAD

**Issue by Draknars** [Kareadita/Kavita#925]
Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
Scanning a library that has lost access/connectivity to it's Shared Folders will results in loosing all progress related to it's content

**More Context**
After Losing Power earlier today, I didn’t realize that the NAS where I store my Manga had some connectivity issues, when I performed Scan to my library with the NAS unavailable, the whole library disappeared, after investigation, I found The NAS Issue I had. However upon restoring connectivity and re-scanning the library, Even though I got all the managa back, I did lost all the progress of the dozen or so Manga that I was reading. 

**To Reproduce**
1. Take any library with some form of progress (on Deck, completed, etc.)
2. Stop connectivity to the Shared Folder (Could be renaming the folder, blocking the port, whatever is the easiest)
3. Perform a Scan of the library - All content will be removed
4. Restore Connectivity
5. Perform another Scan - Content will be restored, but all progress has been lost.

**Expected behavior**
I would expect something more resilient like Plex does. I believe they cache the progress of items separately, so even if you scan the library while not having access to the source, it does not remove what was already there. Even after intentionally trying to brick it, I was not able to lose the progress that I had in my test Plex library.

**Server / Host (please complete the following information):**
OS: Ubuntu 20.04.3 LTS running Kavita in Docker
Version 0.4.9.2
Docker Image : kizaing/kavita:latest

**Smartphone (please complete the following information):**
Device: iPhone XR & iPad Pro Gen3
Browser : Safari / Edge

**Troubleshooting**
Was able to recreate the issue

**Comment by majora2007** [comment]
We have some protection like this in our nightly, but the Trash functionality that Plex has isn't something I'm particularly keen on. I hope you have a backup you can restore to. 

We do store progress separately, but we also clean up any deleted series and the relationships after a scan, hence why the progress was lost. When external scrobbling comes, this shouldn't be a problem.

**Comment by Draknars** [comment]
My backup failed me, but that is on me, I will need to find a replacement to duplicati. 

I'm curious, you mentioned External Scrobbling, can you elaborate on how this will no longer be an issue with it?

Hopefully those safeguard measures help, I had not realized that my progress was that vulnerable to disappear, I think it is a bit bothersome that if I happen to lose connectivity for more than 24 hours, the daily scan will delete all my progress saved.

**Comment by majora2007** [comment]
I'm hoping that it will work in such a way, that it's 2 way. So if you loose progress on Kavita's side, when the scrobbing sync happens, it can find the items and update them. 

I understand it's really frustrating loosing reading progress. The best thing to do is backup daily. Preserving progress is my top priority for myself, so I think about this often. Once I get to implementing scrobbing I'll get to have more time to look at alternatives and reworks.
