### ISSUE TITLE
Share collection tags between users ?

### ISSUE THREAD

**Issue by gittynick** [Kareadita/Kavita#936]
Hello - as an admin, i added a few tags that are conveniently available via the "collection" tab
but for the other (normal) users, there is no trace of these tags... is this normal ? is there a way to share the tags i created with other users ? Thanks

**Comment by majora2007** [comment]
Collections can be promoted which allows users to view them. Only admins can promote the collections. 

From the collection page, click context menu (...) and Edit. There you can click Promote. This will make it public on your server. 

Note: Users are still restrained by library permissions. If your collection is all from Manga library, a user with Book access only won't see anything inside the Collection, but will see the Collection itself.

**Comment by gittynick** [comment]
Cool ! Thank 👍
