### ISSUE TITLE
Ebook (EPUB) - Image rendering issues

### ISSUE THREAD

**Issue by RevelingSeven** [Kareadita/Kavita#938]
**Describe the bug**
Images are not rendering when viewing EPUB files produced by Manning Publications.  The text on the page indicates there should be an image rendered.  I'm able to reproduce the issue with Multiple Operating systems and browsers.  It is extracting the cover image properly.

**To Reproduce**
1. Load a Manning Publications book by adding a Book library
2. Navigate to the book via recently added or accessing in Libraries
3. Click Next 8 times to get to the location\page to match the screen shots
4. See screen shots below showing the rendering output does not render the images.

**Expected behavior**
The EPUB should render with images matching the output of other EPUB readers and the PDF.  Please see screen shots below for example. 

**Screenshots**
This is how the EPUB renders.  After the highlighted text You'll learn in chapter 7 how to package" there should be an image rendered.
![EPUBRender01_missing_image](https://user-images.githubusercontent.com/1787499/149431188-0fb7b082-fe2a-46db-8e65-5461f288ab4b.png)

This is an example of the image from the PDF version of the EBook.
![PDF01_show_image](https://user-images.githubusercontent.com/1787499/149433705-5bd7cb27-dea0-436b-a379-1b864f596d33.png)

**Tested Operating systems and Browsers**
- OS: Windows 10
- Browser: Microsoft Edge (97.0.1072.55, 97.0.1072.62)
- Browser: Chrome (97.0.4692.71)
- Browser: Firefox (96.0)

OS: MacOS
- Browser: Safari (15.1 (16612.29.1.30, 16612)
- Browser: Microsoft Edge (97.0.1072.55)
- Browser: Chrome (97.0.4692.71)
- Browser: Firefox (96.0)

OS: Fedora Linux 35
- Browser: Microsoft Edge (97.0.1072.62)
- Browser: Chrome (97.0.4692.71)
- Browser: Firefox (96.0)

**Install Information**
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Kavita Information**
Version
0.4.9.1

Install ID
819d7621

**Additional context**
I was also able to reproduce it the issue with the kavata-win-x64 build.

Version
0.4.9.2

Install ID
c1150b2c

I have attached the logs from the test utilizing the kavata-win-x64 build.
[kavita.zip](https://github.com/Kareadita/Kavita/files/7866891/kavita.zip)

**Comment by majora2007** [comment]
Can you please send me the file so I can see what's happening?

**Comment by RevelingSeven** [comment]
I just sent over a file via google drive.  Let me know if you have any issues.

Thanks

**Comment by majora2007** [comment]
Thanks, I downloaded it. I'll take a look. This issue will be moved to Done when it is validated on Nightly branch. Next stable release is still a ways off.

**Comment by majora2007** [comment]
Okay, sorted this issue out. The underlying issue was the metadata of the epub defined the image as "OEPBS/Images/1-4.jpg", but the document page defined it as "../Images/1-4.jpg". I now have a correction for when relative pathing is used (in this case, incorrectly) to do a different type of lookup.

This fix is paired with another story, so it wont be released yet. This issue will close when it's been merged in. Appreciate the detailed issue report. Made it really easy to fix.

**Comment by RevelingSeven** [comment]
Thank you very much for the fix and fantastic project. Have a great weekend.
