### ISSUE TITLE
Local metadata volume and issue not taking precendence over filenaming

### ISSUE THREAD

**Issue by therobbiedavis** [Kareadita/Kavita#945]
**Describe the bug**
A fully tagged comic with issue and volume is not being parsed with it's info. Instead Kavita is parsing volume and issue from the filename.

**To Reproduce**
1. Fill out metadata for a comic. volume 1, issue 1
2. Add/replace filename with vol. 20, issue 20
3. Scan series/library
4. See it parsed as Series Vol. 20 Issue 20 in Kavita

**Expected behavior**
Vol. 1 and Issue 1 should be the expected parsing. Filename parsing should only be used if relevant metadata is missing

**Screenshots**
![unknown](https://user-images.githubusercontent.com/7907265/149672394-0feca31a-0c3c-4836-a4f4-169a26d91408.png)
![unknown1](https://user-images.githubusercontent.com/7907265/149672395-198f579f-3963-43ed-9d7e-b757dd09236b.png)

**Desktop (please complete the following information):**
 - OS: ALL
 - Browser: ALL
 - Version: 0.4.9.48

**Comment by majora2007** [comment]
I can't reproduce this issue on my end. Renaming then doing a scan series kept it as Vol 1.
![image](https://user-images.githubusercontent.com/735851/149682677-e9812b79-89d5-4762-b852-be00b91b80f3.png)

**Comment by therobbiedavis** [comment]
Turns out this was caused by two comicinfo.xml files within the archive
![unknown](https://user-images.githubusercontent.com/7907265/149684796-f5d26fb8-a0f1-473b-bdb5-b4139a35fb08.png)
![unknown](https://user-images.githubusercontent.com/7907265/149684802-d02ea7e6-1390-403c-ab32-71afbc84df14.png)
Deleting the second one within the folder resolved the issue.
