### ISSUE TITLE
Libriaries - only 30 items / site

### ISSUE THREAD

**Issue by Orthos79** [Kareadita/Kavita#981]
Hey!

If I click on a library I only see 30 items each site maximum. Is it possible to increase that (Maybe infinite also)?

In fullscreen on my 4k monitor the first two rows shows 14 books each. The third row shows only 2 books. Maybe an option to generally show x rows each page, depending on display resolution, also where an additional option?

Marc

System: Kavita Version 0.4.9.2 in an unraid Docker container

**Comment by majora2007** [comment]
This is not a bug, this is intended functionality. Please upvote the existing request instead:
https://feats.kavitareader.com/posts/52/be-able-to-choose-the-number-of-books-displayed-by-pages
