### ISSUE TITLE
Docker Healthcheck

### ISSUE THREAD

**Issue by sachinwadhwa** [Kareadita/Kavita#985]
What is the best recommendation to implement a healthcheck in docker image?

There is no curl, wget netstat or anything to check if port is open.

**Comment by majora2007** [comment]
Why not just call one of the APIs to validate it's still responsive? 

/api/admin/exists is an api that does not require any authentication to be passed.

**Comment by majora2007** [comment]
@Kizaing Do you have any information to help this user?

**Comment by Kizaing** [comment]
Yeah I can add curl no problem. I'll figure out the best health check method
