### ISSUE TITLE
Characters aren't sorted in the filtering part

### ISSUE THREAD

**Issue by hbooo** [Kareadita/Kavita#988]
**Describe the bug**
Characters aren't sorted in the filtering part

**To Reproduce**
1. Go to comics list
2. Click on filter
3. Scroll down to character and expand the list
4. See that character names aren't sorted alphabetically

**Expected behavior**
In order to easily find a character, they should be sorted by name alphabetically

**Screenshots**
![image](https://user-images.githubusercontent.com/242125/150944691-be2fa7ba-54c0-4a6b-b016-d03063ecacad.png)

**Comment by majora2007** [comment]
Nice catch
